### ISSUE TITLE
How to include code from another file?

### ISSUE THREAD

**Issue by AngryMaciek** [lfortran/lfortran#1050]
I have a _functions.f90_ file with some very long and complex `subroutines`.  
I was wondering if there is a way to `include` it in the notebook such that I can later `call` them in subsequent cells?

**Comment by certik** [comment]
We definitely want this feature. 

You can create a standalone module:
```fortran
module functions

contains

integer function f(x)
integer, intent(in) :: x
f = x + 1
end function

integer function g(x)
integer, intent(in) :: x
g = 2*x
end function

end module
```
And compile it:
```console
$ lfortran -c functions.f90 -o functions.o
```
You can then write a separate program to test it out:
```fortran
program test_functions
use functions, only: f, g
integer :: x
x = g(f(3))
print *, x
end program
```
which works:
```console
$ lfortran a.f90 
8
```


The next step is now to move the statements out of the program into the global scope, as that is how it would be used in the notebook:
```fortran
use functions, only: f, g
integer :: x
x = g(f(3))
print *, x
```
This currently does not work yet:
```console
$ lfortran a.f90 
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1907
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 829
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 234
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 256
    compiler_options.symtab_only, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 47
    auto res = symbol_table_visitor(al, ast, diagnostics, symbol_table,
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1589
    SymbolTableVisitor v(al, symbol_table, diagnostics, compiler_options, implicit_mapping);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 113
    visit_ast(*x.m_items[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4764
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4723
    case astType::program_unit: { v.visit_program_unit((const program_unit_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4776
    void visit_unit_decl1(const unit_decl1_t &b) { visit_unit_decl1_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4382
    switch (x.type) {
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1428
    ASR::symbol_t *t = current_scope->parent->resolve_symbol(msym);
  File "../libasr/asr_scopes.h", line 40
  File "/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/map", line 1380
    iterator find(const key_type& __k)             {return __tree_.find(__k);}
  File "/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/__tree", line 2466
    iterator __p = __lower_bound(__v, __root(), __end_node());
  File "/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/__tree", line 1079
    {return static_cast<__node_pointer>(__end_node()->__left_);}
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Segfault: Signal SIGSEGV (segmentation fault) received
```

If you want to help us fix it, we would really appreciate any help. 

After that, the next step would be to get it working in the interactive mode, there might be additional bugs to fix. I don't think any of the bugs are too difficult at this point.

One option is to have the module in a cell. Another option is to have it locally, and we just have to ensure we tell the kernel where to find it, perhaps with some `%%` style magic commands in the notebook cell.

**Comment by AngryMaciek** [comment]
> If you want to help us fix it, we would really appreciate any help.

I don't think I am able to - I don't know _Fortran_. I just need to use some old code from a module for a quick interactive inspection, results I will later export to a textfile and process downstream in Python.

> One option is to have the module in a cell. 

That is exactly what I'd like to avoid - pasting hundreds of lines into notebook cells is pretty messy, if you ask me...

> Another option is to have it locally, and we just have to ensure we tell the kernel where to find it, perhaps with some %% style magic commands in the notebook cell.

That sounds reasonable: we could first have a bash cell with the compilation command for the external module and later another one loading the module into the notebook's namespace. I assume `%%bash` cells are supported?

**Comment by certik** [comment]
Great idea about the `%%bash` cells. Does Jupyter allow to use multiple kernels in the same notebooks? If not, then we'll have to implement the bash cells in the Fortran kernel.

To help us fix it, you don't need to know Fortran, just C++.

**Comment by AngryMaciek** [comment]
No, _Jupyter_ does not support mixed kernels for one notebook. I mean, you could switch kernels midway but that is kernel restart and your variables are gone, that's far from optimal...

I guess we should then first open an issue regarding magic cells with `%%bash`?

I know some basic _C++_, how can I help?

**Comment by certik** [comment]
I see. We should do it like the IPython kernel does it then.

The way you can help is to setup LFortran and use the above stacktrace and see if you can figure out how to fix it. We have some tutorials at https://docs.lfortran.org/en/contributing/. If you get stuck, let me know and I'll help.

(If you want to learn Fortran, you can do so here: https://fortran-lang.org/en/learn/, we have some very nice tutorials there.)
