### ISSUE TITLE
[SciPy]: LCompilersException: visit_DataImpliedDo() not implemented

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1088]
```fortran
      DOUBLE PRECISION FUNCTION dt1(p,q,df)

      DOUBLE PRECISION df,p,q
      INTEGER i
      DOUBLE PRECISION coef(5,4)

      DATA (coef(i,1),i=1,5)/1.0D0,1.0D0,3*0.0D0/

      RETURN

      END
```
throws the following error 
```
Internal Compiler Error: Unhandled exception
```

>Stacktrace

```
Traceback (most recent call last):
  Binary file "/home/pranavchiku/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 1850, in ??
    return emit_asr(arg_file, lfortran_pass_manager,
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 612, in ??
    r = fe.get_asr2(input, lm, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 240, in LFortran::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LFortran::LocationManager&, LFortran::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 262, in LFortran::FortranEvaluator::get_asr3(LFortran::AST::TranslationUnit_t&, LFortran::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 63, in LFortran::ast_to_asr(Allocator&, LFortran::AST::TranslationUnit_t&, LFortran::diag::Diagnostics&, LFortran::SymbolTable*, bool, LFortran::CompilerOptions&)
    requirement_map, implicit_mapping);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2202, in LFortran::body_visitor(Allocator&, LFortran::AST::TranslationUnit_t&, LFortran::diag::Diagnostics&, LFortran::ASR::asr_t*, LFortran::CompilerOptions&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LFortran::ASR::asr_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LFortran::ASR::asr_t*> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LFortran::ASR::asr_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LFortran::ASR::asr_t*> > > > > >&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LFortran::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LFortran::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LFortran::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LFortran::ASR::ttype_t*> > > > > >&)
    b.visit_TranslationUnit(ast);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 114, in LFortran::BodyVisitor::visit_TranslationUnit(LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4764, in LFortran::AST::BaseVisitor<LFortran::BodyVisitor>::visit_ast(LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4723, in ??
    case astType::program_unit: { v.visit_program_unit((const program_unit_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4772, in LFortran::AST::BaseVisitor<LFortran::BodyVisitor>::visit_program_unit(LFortran::AST::program_unit_t const&)
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4375, in ??
    case program_unitType::Function: { v.visit_Function((const Function_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1203, in LFortran::BodyVisitor::visit_Function(LFortran::AST::Function_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 90, in LFortran::BodyVisitor::transform_stmts(LFortran::Vec<LFortran::ASR::stmt_t*>&, unsigned long, LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4809, in LFortran::AST::BaseVisitor<LFortran::BodyVisitor>::visit_stmt(LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4482, in ??
    case stmtType::DataStmt: { v.visit_DataStmt((const DataStmt_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 917, in LFortran::CommonVisitor<LFortran::BodyVisitor>::visit_DataStmt(LFortran::AST::DataStmt_t const&)
    this->visit_expr(*a->m_object[0]);
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4860, in LFortran::AST::BaseVisitor<LFortran::BodyVisitor>::visit_expr(LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4540, in ??
    case exprType::DataImpliedDo: { v.visit_DataImpliedDo((const DataImpliedDo_t &)x); return; }
LCompilersException: visit_DataImpliedDo() not implemented
```

**Comment by certik** [comment]
I would evaluate the loop at compile time (it seems this is a compile time feature) and then I would use our existing array assignment in DATA feature and reuse it here.
