### ISSUE TITLE
CI: Windows error

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1097]
The Windows CI sometimes fails with this error:
```
... do i = 1, n                                                                │
...     if (i .LT. 100) then                                                   │
...         if (i .EQ. 42) r = (n**2)**(0.5)                                   │
...         if (i .EQ. 42) then                                                │
...             print *, "To be more precise, the answer is: ", r              │
...         endif                                                              │
...     endif                                                                  │
... enddo                                                                      │
... end subroutine                                                       13,15 ┘
style suggestion: Use '<' instead of '.lt.'
 --> input:6:11
  |
6 |     if (i .LT. 100) then
  |           ^^^^ help: write this as '<'

style suggestion: Use '==' instead of '.eq.'
 --> input:7:15
  |
7 |         if (i .EQ. 42) r = (n**2)**(0.5)
  |               ^^^^ help: write this as '=='

style suggestion: Use '==' instead of '.eq.'
 --> input:8:15
  |
8 |         if (i .EQ. 42) then
  |               ^^^^ help: write this as '=='

style suggestion: Use 'end if' instead of 'endif'
  --> input:10:9
   |
10 |         endif
   |         ^^^^^ help: write this as 'end if'

style suggestion: Use 'end if' instead of 'endif'
  --> input:11:5
   |
11 |     endif
   |     ^^^^^ help: write this as 'end if'

style suggestion: Use 'end do' instead of 'enddo'
  --> input:12:1
   |
12 | enddo
   | ^^^^^ help: write this as 'end do'


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
>>>                                                                      1,1   ]>>> c                                                                    1,2   ]>>> ca                                                                   1,3   ]>>> cal                                                                  1,4   ]>>> call                                                                 1,5   ]>>> call                                                                 1,6   ]>>> call h                                                               1,7   ]>>> call h(                                                              1,8   ]>>> call h(4                                                             1,9   ]>>> call h(42                                                            1,10  ]>>> call h(42.                                                           1,11  ]>>> call h(42.0                                                          1,12  ]>>> call h(42.0)                                                         1,13  ]>>> call h(42.0)                                                         1,13  ]
Traceback (most recent call last):
  File "ci\build_tmp.xsh", line 67, in <module>
  File "C:\Users\runneradmin\micromamba-root\envs\lf\lib\site-packages\xonsh\built_ins.py", line 196, in subproc_captured_hiddenobject
    return xonsh.procs.specs.run_subproc(cmds, captured="hiddenobject", envs=envs)
  File "C:\Users\runneradmin\micromamba-root\envs\lf\lib\site-packages\xonsh\procs\specs.py", line 903, in run_subproc
    return _run_specs(specs, cmds)
  File "C:\Users\runneradmin\micromamba-root\envs\lf\lib\site-packages\xonsh\procs\specs.py", line 936, in _run_specs
    command.end()
  File "C:\Users\runneradmin\micromamba-root\envs\lf\lib\site-packages\xonsh\procs\pipelines.py", line 458, in end
    self._end(tee_output=tee_output)
  File "C:\Users\runneradmin\micromamba-root\envs\lf\lib\site-packages\xonsh\procs\pipelines.py", line 477, in _end
    self._raise_subproc_error()
  File "C:\Users\runneradmin\micromamba-root\envs\lf\lib\site-packages\xonsh\procs\pipelines.py", line 599, in _raise_subproc_error
    raise subprocess.CalledProcessError(rtn, spec.args, output=self.output)
subprocess.CalledProcessError: Command '['./src/bin/lfortran', '<', '../src/bin/example_input.txt']' returned non-zero exit status 3221226356.
ci\build_tmp.xsh:49:$lfortran_version=$(cat version).strip()
ci\build_tmp.xsh:50:$dest="lfortran-" + $lfortran_version
ci\build_tmp.xsh:51:bash ci/create_source_tarball0.sh
ci\build_tmp.xsh:52:tar xzf dist/lfortran-$lfortran_version.tar.gz
ci\build_tmp.xsh:53:cd lfortran-$lfortran_version
Exception ignored in: <function _removeHandlerRef at 0x00000257131D0E50>
Traceback (most recent call last):
  File "C:\Users\runneradmin\micromamba-root\envs\lf\lib\logging\__init__.py", line 836, in _removeHandlerRef
  File "C:\Users\runneradmin\micromamba-root\envs\lf\lib\site-packages\xonsh\tracer.py", line 87, in trace
TypeError: 'NoneType' object is not callable
```
And restarting it usually fixes it. 

So far we have not figured out how to reproduce it, nor what might be causing it.

**Comment by czgdp1807** [comment]
Seems like a heap corruption error. See `Command '['./src/bin/lfortran', '<', '../src/bin/example_input.txt']' returned non-zero exit status 3221226356`. `3221226356` is nothing but, `0xC0000374` which is https://stackoverflow.com/q/45086471. That's why its flaky (sometimes it works, sometimes it doesn't).

Probably we need to increase the size of the heap available to a process on Windows CI.

**Comment by certik** [comment]
I see. I think there is a real bug somewhere.

I would rework the test. It is outputting a bunch of data. We are just testing that it works, so let's use a shorter example, like `print *, "OK"`.

**Comment by certik** [comment]
The PR https://github.com/lfortran/lfortran/pull/1159 might help with this, let's watch this.
