### ISSUE TITLE
[SciPy] visit_BlockData() not implemented.

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1101]
```fortran
      block data
      integer illin ,ntrep
      common  illin, ntrep
      data illin/0/, ntrep/0/
      end
```
Returns the following stacktrace on executing `lfortran --no-warnings --fixed-form --implicit-typing --allow-implicit-interface --show-asr`

```
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/pranavchiku/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 1850, in ??
    return emit_asr(arg_file, lfortran_pass_manager,
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 612, in ??
    r = fe.get_asr2(input, lm, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 240, in LFortran::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LFortran::LocationManager&, LFortran::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 262, in LFortran::FortranEvaluator::get_asr3(LFortran::AST::TranslationUnit_t&, LFortran::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 48, in LFortran::ast_to_asr(Allocator&, LFortran::AST::TranslationUnit_t&, LFortran::diag::Diagnostics&, LFortran::SymbolTable*, bool, LFortran::CompilerOptions&)
    compiler_options, requirement_map, implicit_mapping);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1665, in LFortran::symbol_table_visitor(Allocator&, LFortran::AST::TranslationUnit_t&, LFortran::diag::Diagnostics&, LFortran::SymbolTable*, LFortran::CompilerOptions&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LFortran::ASR::asr_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LFortran::ASR::asr_t*> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LFortran::ASR::asr_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LFortran::ASR::asr_t*> > > > > >&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LFortran::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LFortran::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LFortran::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LFortran::ASR::ttype_t*> > > > > >&)
    v.visit_TranslationUnit(ast);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 113, in LFortran::SymbolTableVisitor::visit_TranslationUnit(LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4764, in LFortran::AST::BaseVisitor<LFortran::SymbolTableVisitor>::visit_ast(LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4722, in ??
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4767, in LFortran::AST::BaseVisitor<LFortran::SymbolTableVisitor>::visit_mod(LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4364, in ??
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
LCompilersException: visit_BlockData() not implemented
(lf3) pranavchiku@pranavchiku-Yoga-Slim-7-14IIL05:~/lfortran(main)$ lfortran --no-warnings --fixed-form --implicit-typing --allow-implicit-interface --show-asr /home/pranavchiku/scipy/scipy/integrate/odepack/blkdta000.f
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/pranavchiku/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 1850, in ??
    return emit_asr(arg_file, lfortran_pass_manager,
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 612, in ??
    r = fe.get_asr2(input, lm, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 240, in LFortran::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LFortran::LocationManager&, LFortran::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 262, in LFortran::FortranEvaluator::get_asr3(LFortran::AST::TranslationUnit_t&, LFortran::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 48, in LFortran::ast_to_asr(Allocator&, LFortran::AST::TranslationUnit_t&, LFortran::diag::Diagnostics&, LFortran::SymbolTable*, bool, LFortran::CompilerOptions&)
    compiler_options, requirement_map, implicit_mapping);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1665, in LFortran::symbol_table_visitor(Allocator&, LFortran::AST::TranslationUnit_t&, LFortran::diag::Diagnostics&, LFortran::SymbolTable*, LFortran::CompilerOptions&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LFortran::ASR::asr_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LFortran::ASR::asr_t*> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LFortran::ASR::asr_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LFortran::ASR::asr_t*> > > > > >&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LFortran::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LFortran::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LFortran::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LFortran::ASR::ttype_t*> > > > > >&)
    v.visit_TranslationUnit(ast);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 113, in LFortran::SymbolTableVisitor::visit_TranslationUnit(LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4764, in LFortran::AST::BaseVisitor<LFortran::SymbolTableVisitor>::visit_ast(LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4722, in ??
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4767, in LFortran::AST::BaseVisitor<LFortran::SymbolTableVisitor>::visit_mod(LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4364, in ??
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
LCompilersException: visit_BlockData() not implemented
```

**Comment by Pranavchiku** [comment]
This is not a difficult task to do, we have COMMON block, Data statement lowering to ASR we just need to fit all in place and it will be done.

**Comment by certik** [comment]
Example:
```
      block data jacobian
      implicit none

      double precision bands
      dimension bands(4,5)
      common /jac/ bands

c     The data for a banded Jacobian stored in packed banded
c     format.  The full Jacobian is
c
c           -1,  0.25,     0,     0,     0
c         0.25,    -5,  0.25,     0,     0
c         0.10,  0.25,   -25,  0.25,     0
c            0,  0.10,  0.25,  -125,  0.25
c            0,     0,  0.10,  0.25,  -625
c
c     The columns in the following layout of numbers are
c     the upper diagonal, main diagonal and two lower diagonals
c     (i.e. each row in the layout is a column of the packed
c     banded Jacobian).  The values 0.00D0 are in the "don't
c     care" positions.

      data bands/
     +      0.00D0,   -1.0D0, 0.25D0, 0.10D0,
     +      0.25D0,   -5.0D0, 0.25D0, 0.10D0,
     +      0.25D0,  -25.0D0, 0.25D0, 0.10D0,
     +      0.25D0, -125.0D0, 0.25D0, 0.00D0,
     +      0.25D0, -625.0D0, 0.00D0, 0.00D0
     +      /

      end
```
using f2c:
```
struct jac_1_ {
    double bands[20]    /* was [4][5] */;
};

#define jac_1 (*(struct jac_1_ *) &jac_)

/* Initialized data */

struct {
    double e_1[20];
    } jac_ = { 0., -1., .25, .1, .25, -5., .25, .1, .25, -25., .25, .1, .25, 
        -125., .25, 0., .25, -625., 0., 0. };
```
and seeing the LLVM via:
```
clang -S -emit-llvm -c banded5x5.c -o a.ll
```
Gives:
```
; ModuleID = 'banded5x5.c'
source_filename = "banded5x5.c"
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"
target triple = "arm64-apple-macosx12.0.0"

%struct.anon = type { [20 x double] }

@jac_ = global %struct.anon { [20 x double] [double 0.000000e+00, double -1.000000e+00, double 2.500000e-01, double 1.000000e-01, double 2.500000e-01, double -5.000000e+00, double 2.500000e-01, double 1.000000e-01, double 2.500000e-01, double -2.500000e+01, double 2.500000e-01, double 1.000000e-01, double 2.500000e-01, double -1.250000e+02, double 2.500000e-01, double 0.000000e+00, double 2.500000e-01, double -6.250000e+02, double 0.000000e+00, double 0.000000e+00] }, align 8

; Function Attrs: noinline nounwind optnone ssp uwtable
define i32 @jacobian_() #0 {
  ret i32 0
}
```

**Comment by certik** [comment]
TODO:
* [ ] figure out how to create struct initializers in the LLVM backend
* [ ] Figure out how to represent them in ASR.

**Comment by certik** [comment]
The above will represent it in ASR. Then in the LLVM backend, we will provide some special handling for these common block modules, and generate the equivalent of:
```llvm
%struct.anon = type { [218 x double], i32, [10 x i32], i32, [27 x i32] }

@ls0001_ = global %struct.anon { [218 x double] zeroinitializer, i32 101, [10 x i32] zeroinitializer, i32 102, [27 x i32] zeroinitializer }, align 8
```
Here the global module variable becomes `@ls0001_ = global %struct.anon`, and the `StructConstant(ArrayConstant(...), ...)` becomes `{ [218 x double] zeroinitializer, i32 101, [10 x i32] zeroinitializer, i32 102, [27 x i32] zeroinitializer }`.
