### ISSUE TITLE
AssertFailed: `ASR::is_a<ASR::RealConstant_t>(*value)`

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1161]
For 
```fortran
program main
    implicit none
    double precision :: x(3) = (/ 1.0, 2.0, 3.0 /)
    double precision :: y = 0.0
    integer :: i
    do i = 1, 3
        y = y + dabs(x(i))
        print *, y
    end do
end program
```
>GFortran
```console
$ gfortran a.f90 && ./a.out
   1.0000000000000000     
   3.0000000000000000     
   6.0000000000000000     
```
>LFortran
```console
$ lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/pranavchiku/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 1932, in ??
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 833, in ??
    result = fe.get_asr2(input, lm, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 240, in LFortran::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LFortran::LocationManager&, LFortran::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 262, in LFortran::FortranEvaluator::get_asr3(LFortran::AST::TranslationUnit_t&, LFortran::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 82, in LFortran::ast_to_asr(Allocator&, LFortran::AST::TranslationUnit_t&, LFortran::diag::Diagnostics&, LFortran::SymbolTable*, bool, LFortran::CompilerOptions&)
    compiler_options, requirement_map, implicit_mapping);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1665, in LFortran::symbol_table_visitor(Allocator&, LFortran::AST::TranslationUnit_t&, LFortran::diag::Diagnostics&, LFortran::SymbolTable*, LFortran::CompilerOptions&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LFortran::ASR::asr_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LFortran::ASR::asr_t*> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LFortran::ASR::asr_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LFortran::ASR::asr_t*> > > > > >&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LFortran::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LFortran::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LFortran::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LFortran::ASR::ttype_t*> > > > > >&)
    v.visit_TranslationUnit(ast);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 113, in LFortran::SymbolTableVisitor::visit_TranslationUnit(LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4764, in LFortran::AST::BaseVisitor<LFortran::SymbolTableVisitor>::visit_ast(LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4722, in ??
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4767, in LFortran::AST::BaseVisitor<LFortran::SymbolTableVisitor>::visit_mod(LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4365, in ??
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 291, in LFortran::SymbolTableVisitor::visit_Program(LFortran::AST::Program_t const&)
    visit_unit_decl2(*x.m_decl[i]);
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4778, in LFortran::AST::BaseVisitor<LFortran::SymbolTableVisitor>::visit_unit_decl2(LFortran::AST::unit_decl2_t const&)
    void visit_unit_decl2(const unit_decl2_t &b) { visit_unit_decl2_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4391, in ??
    case unit_decl2Type::Declaration: { v.visit_Declaration((const Declaration_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 867, in LFortran::SymbolTableVisitor::visit_Declaration(LFortran::AST::Declaration_t const&)
    visit_DeclarationUtil(x);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 1367, in LFortran::CommonVisitor<LFortran::SymbolTableVisitor>::visit_DeclarationUtil(LFortran::AST::Declaration_t const&)
    ImplicitCastRules::set_converted_value(al, x.base.base.loc, &init_expr, init_type, type);
AssertFailed: ASR::is_a<ASR::RealConstant_t>(*value)
```
Pardon me for the wage issue name.

**Comment by Smit-create** [comment]
I'm trying to resolve this in https://github.com/lfortran/lfortran/pull/1049. There is some progress on ASR but fails in the LLVM.
