### ISSUE TITLE
Verify failed in LLVM passes

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1164]
Here is a minimal example:
```fortran
subroutine find_fit(expr)
interface
    integer function expr()
    end function
end interface
end subroutine

program useissue
end program
```
This gives:
```console
$ lfortran a.f90
ASR verify pass error: ASR verify: Var::m_v `expr` cannot point outside of its symbol table
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1932
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 862
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 334
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6700
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 201
    _apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 102
    throw LFortran::LCompilersException("Verify failed");
LCompilersException: Verify failed
```

**Comment by czgdp1807** [comment]
Will fix this on Tuesday.
