### ISSUE TITLE
Bug in pass `subroutine_from_function`

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1194]
While trying to compile `minpack/examples/example_primes.f90`, I came across
```fortran
subroutine find_fit(expr)
interface
    function expr() result(y)
    implicit none
    real :: y(1)
    end function
end interface
end subroutine
    
program main
    implicit none
    call find_fit(expression)
    contains
    function expression() result(y)
    real :: y(1)
    end function
end program
```
>LFortran

```console
$ lfortran a.f90
ASR verify pass error: ASR verify: Var::m_v `expression` cannot point outside of its symbol table
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/pranavchiku/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 1934, in ??
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 862, in ??
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 338, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6753, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_manager.h", line 215, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _apply_passes(al, asr, _passes, pass_options, diagnostics);
LCompilersException: Verify failed
```

**Comment by Pranavchiku** [comment]
On investigating, I found out this happens because of a function `create_subroutine_from_function` in passes `subroutine_from_function` and `array_op`. Which tries to convert Function `expression` to subroutine changing `return_var` to "nullptr".
But here in the above case, `expression` is a dependency for subroutine `find_fit(expr)` which has an interface Function `expr`.
