### ISSUE TITLE
CI: Ubuntu tests sometimes fail

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1218]
https://github.com/lfortran/lfortran/actions/runs/4020469349/jobs/6908432312

```
 START TEST:  subroutine1.f90
 START TEST:  ../integration_tests/template_add.f90
 START TEST:  ../integration_tests/template_nested.f90
 START TEST:  ../integration_tests/template_travel.f90
 START TEST:  ../integration_tests/template_triple.f90
 START TEST:  ../integration_tests/template_array.f90
subroutine1.f90 * tokens ✓ 
../integration_tests/template_nested.f90 * ast ✓ 
../integration_tests/template_add.f90 * ast ✓ 
../integration_tests/template_travel.f90 * ast ✓ 
subroutine1.f90 * ast ✓ 
../integration_tests/template_triple.f90 * asr ✓ 
 START TEST:  ../integration_tests/test_backspace_01.f90
../integration_tests/template_add.f90 * asr ✓ 
 START TEST:  subroutine2.f90
../integration_tests/template_array.f90 * asr ✓ 
 START TEST:  subroutine3.f90
../integration_tests/template_travel.f90 * asr ✓ 
 START TEST:  subroutine3b.f90
subroutine1.f90 * ast_indent ✓ 
../integration_tests/test_backspace_01.f90 * asr ✓ 
 START TEST:  do1.f90
../integration_tests/template_nested.f90 * asr ✓ 
 START TEST:  do2.f90
subroutine1.f90 * asr_indent ✓ 
subroutine2.f90 * ast ✓ 
subroutine3.f90 * ast ✓ 
subroutine3b.f90 * ast ✓ 
do1.f90 * ast ✓ 
 START TEST:  do3.f90
do2.f90 * ast ✓ 
 START TEST:  do4.f90
subroutine1.f90 * julia ✓ 
 START TEST:  do5.f90
subroutine3.f90 * asr ✓ 
subroutine2.f90 * julia ✓ 
 START TEST:  do6.f90
subroutine3b.f90 * asr ✓ 
do4.f90 * ast ✓ 
 START TEST:  do7.f90
do3.f90 * ast ✓ 
 START TEST:  derived_types_07.f90
../integration_tests/derived_types_11.f90 * asr ✓ 
 START TEST:  modules1.f90
+ lfortran -c tests/modules1_module1.f90
../integration_tests/derived_types_01.f90 * asr ✓ 
../integration_tests/derived_types_03.f90 * asr ✓ 
 START TEST:  modules2.f90
+ lfortran -c tests/modules2_module_a.f90
+ lfortran -c tests/derived_types_05.f90
derived_types_04.f90 * asr ✓ 
 START TEST:  modules3.f90
+ lfortran -c tests/modules2_module_a.f90
+ lfortran -c tests/modules1_module2.f90
+ lfortran -c tests/modules2_module_b_base.f90
derived_types_07.f90 * asr ✓ 
 START TEST:  modules4.f90
+ lfortran -c tests/modules2_module_a.f90
../integration_tests/derived_types_01.f90 * llvm ✓ 
 START TEST:  fn2.f90
+ lfortran -c tests/modules2_module_b_base.f90
+ lfortran -c tests/modules2_module_b.f90
+ lfortran -c tests/modules2_module_b_base.f90
fn2.f90 * asr ✓ 
Internal Compiler Error: Unhandled exception
fn2.f90 * cpp ✓ 
 START TEST:  fn3.f90
Traceback (most recent call last):
LCompilersException: read_int64: String is too short for deserialization.
Command failed.
 START TEST:  fn4.f90
+ lfortran -c tests/modules2_module_b.f90
+ lfortran -c tests/modules2_module_b.f90
+ lfortran -c tests/modules2.f90
+ lfortran -c tests/modules2.f90
modules1.f90 * asr ✓ 
 START TEST:  fn5.f90
derived_types_06.f90 * asr ✓ 
 START TEST:  fn6.f90
fn3.f90 * ast ✓ 
fn4.f90 * ast ✓ 
+ lfortran -c tests/modules3.f90
fn6.f90 * asr ✓ 
fn5.f90 * asr ✓ 
+ lfortran -c tests/modules4_module.f90
fn4.f90 * ast_f90 ✓ 
modules3.f90 * asr ✓ 
modules4.f90 * asr ✓ 
Traceback (most recent call last):
  File "ci/test.xsh", line 44, in <module>
    ./run_tests.py
  File "/home/runner/micromamba-root/envs/lf/lib/python3.10/site-packages/xonsh/built_ins.py", line 196, in subproc_captured_hiddenobject
    return xonsh.procs.specs.run_subproc(cmds, captured="hiddenobject", envs=envs)
  File "/home/runner/micromamba-root/envs/lf/lib/python3.10/site-packages/xonsh/procs/specs.py", line 903, in run_subproc
    return _run_specs(specs, cmds)
  File "/home/runner/micromamba-root/envs/lf/lib/python3.10/site-packages/xonsh/procs/specs.py", line 936, in _run_specs
    command.end()
  File "/home/runner/micromamba-root/envs/lf/lib/python3.10/site-packages/xonsh/procs/pipelines.py", line 458, in end
    self._end(tee_output=tee_output)
  File "/home/runner/micromamba-root/envs/lf/lib/python3.10/site-packages/xonsh/procs/pipelines.py", line 477, in _end
    self._raise_subproc_error()
  File "/home/runner/micromamba-root/envs/lf/lib/python3.10/site-packages/xonsh/procs/pipelines.py", line 599, in _raise_subproc_error
    raise subprocess.CalledProcessError(rtn, spec.args, output=self.output)
subprocess.CalledProcessError: Command '['./run_tests.py']' returned non-zero exit status 1.
```

**Comment by certik** [comment]
My guess is the issue comes from:
```
+ lfortran -c tests/modules2_module_b_base.f90
+ lfortran -c tests/modules2_module_b.f90
+ lfortran -c tests/modules2_module_b_base.f90
fn2.f90 * asr ✓ 
Internal Compiler Error: Unhandled exception
```
The file `tests/modules2_module_b_base.f90` is compiled twice in parallel, so the mod file gets destroyed and then it fails to read properly.
