### ISSUE TITLE
CI: Linux failure with LCompilersException: read_int64: String is too short for deserialization

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1229]
https://github.com/lfortran/lfortran/actions/runs/4030237778/jobs/6928769858

```
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
LCompilersException: read_int64: String is too short for deserialization.
+ lfortran -c tests/modules2.f90
Command failed.
 START TEST:  forall1.f90
 START TEST:  subroutine8.f90
fn4.f90 * ast_f90 ✓ 
forall1.f90 * ast ✓ 
fn6.f90 * asr ✓ 
subroutine8.f90 * ast ✓ 
fn5.f90 * asr ✓ 
+ lfortran -c tests/modules3.f90
forall1.f90 * ast_f90 ✓ 
+ lfortran -c tests/modules4_module.f90
Traceback (most recent call last):
  File "/home/runner/work/lfortran/lfortran/./run_tests.py", line 309, in <module>
    tester_main("LFortran", single_test)
  File "/home/runner/work/lfortran/lfortran/src/libasr/compiler_tester/tester.py", line 412, in tester_main
    for f in futures:
  File "/home/runner/micromamba-root/envs/lf/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/home/runner/micromamba-root/envs/lf/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/home/runner/micromamba-root/envs/lf/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/runner/micromamba-root/envs/lf/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/runner/micromamba-root/envs/lf/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/runner/work/lfortran/lfortran/./run_tests.py", line 167, in single_test
    run_test(
  File "/home/runner/work/lfortran/lfortran/src/libasr/compiler_tester/tester.py", line 329, in run_test
    raise RunException(
compiler_tester.tester.RunException: Testing with reference output failed.
modules2.f90 * asr
The JSON metadata differs against reference results
Reference JSON: tests/reference/asr-modules2-f9ba4aa.json
Output JSON:    tests/output/asr-modules2-f9ba4aa.json
Omitting 6 identical items
Differing items:
{'returncode': 1} != {'returncode': 0}
{'stderr_hash': '2ac584e3efb244415c17d94ea2bded96b724f298e9aeaccd6eaf5c04'} != {'stderr_hash': None}
{'stdout_hash': None} != {'stdout_hash': '53f2f4c20c4c84ed8c277c2babd2db5ff656f8cdc7459a560b1c2d0b'}
{'stdout': None} != {'stdout': 'asr-modules2-f9ba4aa.stdout'}
{'stderr': 'asr-modules2-f9ba4aa.stderr'} != {'stderr': None}No output stdout_hash available for modules2.f90

modules4.f90 * asr ✓ 
Traceback (most recent call last):
  File "ci/test.xsh", line 44, in <module>
    ./run_tests.py
  File "/home/runner/micromamba-root/envs/lf/lib/python3.10/site-packages/xonsh/built_ins.py", line 196, in subproc_captured_hiddenobject
    return xonsh.procs.specs.run_subproc(cmds, captured="hiddenobject", envs=envs)
  File "/home/runner/micromamba-root/envs/lf/lib/python3.10/site-packages/xonsh/procs/specs.py", line 903, in run_subproc
    return _run_specs(specs, cmds)
  File "/home/runner/micromamba-root/envs/lf/lib/python3.10/site-packages/xonsh/procs/specs.py", line 936, in _run_specs
    command.end()
  File "/home/runner/micromamba-root/envs/lf/lib/python3.10/site-packages/xonsh/procs/pipelines.py", line 458, in end
    self._end(tee_output=tee_output)
  File "/home/runner/micromamba-root/envs/lf/lib/python3.10/site-packages/xonsh/procs/pipelines.py", line 477, in _end
    self._raise_subproc_error()
  File "/home/runner/micromamba-root/envs/lf/lib/python3.10/site-packages/xonsh/procs/pipelines.py", line 599, in _raise_subproc_error
    raise subprocess.CalledProcessError(rtn, spec.args, output=self.output)
subprocess.CalledProcessError: Command '['./run_tests.py']' returned non-zero exit status 1.
```

**Comment by certik** [comment]
I think this is the same error as https://github.com/lfortran/lfortran/issues/1218

**Comment by certik** [comment]
This one probably comes from `lfortran -c tests/modules2.f90`.
