### ISSUE TITLE
"Exit" causes segmentation fault when used inside block.

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1293]
```fortran
subroutine hybrd(n)
    implicit none
    real :: n

    main : block
        if ( n <= 0 ) then
            exit main
        else 
            n = n + 1
        end if 
        n = n + 2
    end block main
    n = n + 3


end subroutine hybrd

program main
    implicit none
    real :: n = -1.0
    call hybrd(n)
end program main
```

> LFortran

```console
$ lfortran ./src/a.f90
Traceback (most recent call last):
  Binary file "/home/pranavchiku/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 1938, in ??
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 865, in ??
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 342, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6858, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4426, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4402, in ??
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4427, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4162, in ??
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1276, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4429, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4172, in ??
    case symbolType::Function: { v.visit_Function((const Function_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3494, in LCompilers::ASRToLLVMVisitor::visit_Function(LCompilers::ASR::Function_t const&)
    generate_function(x);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3849, in LCompilers::ASRToLLVMVisitor::generate_function(LCompilers::ASR::Function_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4444, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4228, in ??
    case stmtType::BlockCall: { v.visit_BlockCall((const BlockCall_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4429, in LCompilers::ASRToLLVMVisitor::visit_BlockCall(LCompilers::ASR::BlockCall_t const&)
    this->visit_stmt(*(block->m_body[i]));
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4444, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4205, in ??
    case stmtType::If: { v.visit_If((const If_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4652, in LCompilers::ASRToLLVMVisitor::visit_If(LCompilers::ASR::If_t const&)
    create_if_else(tmp, [=]() {
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 309, in void LCompilers::ASRToLLVMVisitor::create_if_else<LCompilers::ASRToLLVMVisitor::visit_If(LCompilers::ASR::If_t const&)::{lambda()#1}, LCompilers::ASRToLLVMVisitor::visit_If(LCompilers::ASR::If_t const&)::{lambda()#2}>(llvm::Value*, LCompilers::ASRToLLVMVisitor::visit_If(LCompilers::ASR::If_t const&)::{lambda()#1}, LCompilers::ASRToLLVMVisitor::visit_If(LCompilers::ASR::If_t const&)::{lambda()#2})
    if_block();
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4654, in LCompilers::ASRToLLVMVisitor::visit_If(LCompilers::ASR::If_t const&)::{lambda()#1}::operator()() const
    this->visit_stmt(*x.m_body[i]);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4444, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4201, in ??
    case stmtType::Exit: { v.visit_Exit((const Exit_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4691, in LCompilers::ASRToLLVMVisitor::visit_Exit(LCompilers::ASR::Exit_t const&)
    builder->CreateBr(current_loopend);
  File "/home/pranavchiku/conda_root/envs/lf/include/llvm/IR/IRBuilder.h", line 953, in llvm::IRBuilderBase::CreateBr(llvm::BasicBlock*)
    return Insert(BranchInst::Create(Dest));
  File "/home/pranavchiku/conda_root/envs/lf/include/llvm/IR/Instructions.h", line 3017, in llvm::BranchInst::Create(llvm::BasicBlock*, llvm::Instruction*)
    return new(1) BranchInst(IfTrue, InsertBefore);
  Binary file "/home/pranavchiku/lfortran/src/bin/lfortran", in llvm::BranchInst::BranchInst(llvm::BasicBlock*, llvm::Instruction*)
  Binary file "/home/pranavchiku/lfortran/src/bin/lfortran", in llvm::BasicBlock::getValueSymbolTable()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __GI___sigaction()
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by Pranavchiku** [comment]
I am able to generate below given LLVM, 
```console
$ lfortran /home/pranavchiku/Desktop/minpack/src/a.f90  --implicit-typing --implicit-interface --show-llvm
; ModuleID = 'LFortran'
source_filename = "LFortran"

define void @hybrd(float* %n) {
.entry:
  %0 = load float, float* %n, align 4
  %1 = fcmp ule float %0, 0.000000e+00
  br i1 %1, label %then, label %else

then:                                             ; preds = %.entry
  br label %unreachable_after_exit

unreachable_after_exit:                           ; preds = %then
  br label %ifcont

else:                                             ; preds = %.entry
  %2 = load float, float* %n, align 4
  %3 = fadd float %2, 1.000000e+00
  store float %3, float* %n, align 4
  br label %ifcont

ifcont:                                           ; preds = %else, %unreachable_after_exit
  %4 = load float, float* %n, align 4
  %5 = fadd float %4, 2.000000e+00
  store float %5, float* %n, align 4
  %6 = load float, float* %n, align 4
  %7 = fadd float %6, 3.000000e+00
  store float %7, float* %n, align 4
  br label %return

return:                                           ; preds = %ifcont
  ret void
}

define i32 @main(i32 %0, i8** %1) {
.entry:
  call void @_lpython_set_argv(i32 %0, i8** %1)
  %n = alloca float, align 4
  store float -1.000000e+00, float* %n, align 4
  call void @hybrd(float* %n)
  ret i32 0
}

declare void @_lpython_set_argv(i32, i8**)
```

I used a `bool in_block` and made a check in "visit_Exit", `if ( in_block )` , yes, then just `br label %unreachable_after_exit` which actually is not correct as it will result in n = n+ 2, and then n = n+3 but we want is just n = n +3

In simple terms output with GFortran diverges as shown below
>LFortran
```console
$ lfortran a.f90  --implicit-typing --implicit-interface
 n =  4.00000000e+00
```
>GFortran
```console
$ gfortran a.f90 && ./a.out
  n =    2.00000000 
```

**Comment by Pranavchiku** [comment]
With this `modern_minpack/src/minpack.f90` compiles to LLVM.

**Comment by Pranavchiku** [comment]
Final LLVM, which aligns output with GFortran.
```console
; ModuleID = 'LFortran'
source_filename = "LFortran"

define void @hybrd(float* %n) {
.entry:
  br label %block_block_start

block_block_start:                                ; preds = %.entry
  %0 = load float, float* %n, align 4
  %1 = fcmp ule float %0, 0.000000e+00
  br i1 %1, label %then, label %else

block_block_end:                                  ; preds = %ifcont, %then
  %2 = load float, float* %n, align 4
  %3 = fadd float %2, 3.000000e+00
  store float %3, float* %n, align 4
  br label %return

then:                                             ; preds = %block_block_start
  br label %block_block_end

else:                                             ; preds = %block_block_start
  %4 = load float, float* %n, align 4
  %5 = fadd float %4, 1.000000e+00
  store float %5, float* %n, align 4
  br label %ifcont

ifcont:                                           ; preds = %else
  %6 = load float, float* %n, align 4
  %7 = fadd float %6, 2.000000e+00
  store float %7, float* %n, align 4
  br label %block_block_end

return:                                           ; preds = %block_block_end
  ret void
}

define i32 @main(i32 %0, i8** %1) {
.entry:
  call void @_lpython_set_argv(i32 %0, i8** %1)
  %n = alloca float, align 4
  store float -1.000000e+00, float* %n, align 4
  call void @hybrd(float* %n)
  ret i32 0
}

declare void @_lpython_set_argv(i32, i8**)
```

**Comment by Pranavchiku** [comment]
@certik you can find the full llvm here.

**Comment by certik** [comment]
This is the correct LLVM. Can you now post LLVM if you always keep the line `builder->CreateBr(mergeBB);` ?

**Comment by Pranavchiku** [comment]
Here you go.
```console
; ModuleID = 'LFortran'
source_filename = "LFortran"

@0 = private unnamed_addr constant [2 x i8] c" \00", align 1
@1 = private unnamed_addr constant [2 x i8] c"\0A\00", align 1
@2 = private unnamed_addr constant [5 x i8] c"n = \00", align 1
@3 = private unnamed_addr constant [13 x i8] c"%s%s%13.8e%s\00", align 1

define void @hybrd(float* %n) {
.entry:
  br label %block_block_start

block_block_start:                                ; preds = %.entry
  %0 = load float, float* %n, align 4
  %1 = fcmp ule float %0, 0.000000e+00
  br i1 %1, label %then, label %else

block_block_end:                                  ; preds = %ifcont6, %else3, %then
  %2 = load float, float* %n, align 4
  %3 = fadd float %2, 3.000000e+00
  store float %3, float* %n, align 4
  %4 = load float, float* %n, align 4
  %5 = fpext float %4 to double
  call void (i8*, ...) @_lfortran_printf(i8* getelementptr inbounds ([13 x i8], [13 x i8]* @3, i32 0, i32 0), i8* getelementptr inbounds ([5 x i8], [5 x i8]* @2, i32 0, i32 0), i8* getelementptr inbounds ([2 x i8], [2 x i8]* @0, i32 0, i32 0), double %5, i8* getelementptr inbounds ([2 x i8], [2 x i8]* @1, i32 0, i32 0))
  br label %return

then:                                             ; preds = %block_block_start
  br label %block_block_end
  br label %ifcont6

else:                                             ; preds = %block_block_start
  %6 = load float, float* %n, align 4
  %7 = fcmp uge float %6, 2.000000e+00
  br i1 %7, label %then1, label %else4

then1:                                            ; preds = %else
  %8 = load float, float* %n, align 4
  %9 = fcmp ule float %8, 4.000000e+00
  br i1 %9, label %then2, label %else3

then2:                                            ; preds = %then1
  %10 = load float, float* %n, align 4
  %11 = fadd float %10, 1.000000e+00
  store float %11, float* %n, align 4
  br label %ifcont

else3:                                            ; preds = %then1
  br label %block_block_end

ifcont:                                           ; preds = %then2
  br label %ifcont5

else4:                                            ; preds = %else
  %12 = load float, float* %n, align 4
  %13 = fadd float %12, 9.000000e+00
  store float %13, float* %n, align 4
  br label %ifcont5

ifcont5:                                          ; preds = %else4, %ifcont
  br label %ifcont6

ifcont6:                                          ; preds = %ifcont5, %then
  %14 = load float, float* %n, align 4
  %15 = fadd float %14, 2.000000e+00
  store float %15, float* %n, align 4
  br label %block_block_end

return:                                           ; preds = %block_block_end
  ret void
}

declare void @_lfortran_printf(i8*, ...)

define i32 @main(i32 %0, i8** %1) {
.entry:
  call void @_lpython_set_argv(i32 %0, i8** %1)
  %n = alloca float, align 4
  store float 1.000000e+00, float* %n, align 4
  call void @hybrd(float* %n)
  ret i32 0
}

declare void @_lpython_set_argv(i32, i8**)
code generation error: asr_to_llvm: module failed verification. Error:
Terminator found in the middle of a basic block!
label %then
```

**Comment by Pranavchiku** [comment]
Here at 
```llvm
then:                                             ; preds = %block_block_start
  br label %block_block_end
  br label %ifcont
```
We get an extra `br label %ifcont`.
