### ISSUE TITLE
Get generics template examples working with WASM

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1294]
We currently have 7 tests for generics: https://github.com/lfortran/lfortran/blob/46bc01c11f53f35ed2bca28a5c2df38fcae5c0c9/integration_tests/CMakeLists.txt#L648-L654, currently they only work with the LLVM backend.  Let's get them all working with the `wasm` backend. It shouldn't be complicated, no new features should be needed, everything should be already properly instantiated in ASR, you might just need to ignore some ASR generics nodes.

Currently this is the error that I am getting:
```console
$ lfortran --show-wat integration_tests/template_array_01.f90
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1878
    return emit_wat(arg_file, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 909
    LCompilers::Result<std::string> r = fe.get_wat(input, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 408
    Result<Vec<uint8_t>> wasm = get_wasm(code, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 395
    return asr_to_wasm_bytes_stream(*asr.result, al, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 2187
    pass_unused_functions(al, asr, pass_options);
  File "../libasr/asr.h", line 4426
  File "../libasr/asr.h", line 4402
  File "../libasr/asr.h", line 4427
  File "../libasr/asr.h", line 4161
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 297
    ASR::symbol_t *mod = x.m_global_scope->get_symbol(item);
  File "../libasr/asr.h", line 4429
  File "../libasr/asr.h", line 4170
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 344
    declare_all_functions(*x.m_symtab);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 329
    ASR::Function_t *s =
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 663
    return;
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 599
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4444
  File "../libasr/asr.h", line 4192
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 825
    *(ASR::down_cast<ASR::ArrayItem_t>(x.m_target)));
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 1426
    this->visit_expr(*m_dims[i].m_start);
  File "../libasr/asr.h", line 4489
  File "../libasr/asr.h", line 4489
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by Shaikh-Ubaid** [comment]
If there is no `lower_bound` specified when declaring an array in `fortran`, what is the default value for `lower_bound`?

https://github.com/lfortran/lfortran/blob/b1b149a7db935ead3ab48f30fc668103262449ce/integration_tests/template_array_02.f90#L61-L69

For `line 65`, `r = zero_t(a(0))`, should the `ArrayItem` index be `0` or `1`?

**Comment by certik** [comment]
The default is 1, I think this is a bug in the test, great catch!

**Comment by Shaikh-Ubaid** [comment]
Are we allowed to update the two tests to use the index `1` instead of `0`?

**Comment by certik** [comment]
Yes, can you create a PR that just updates the tests to use 1 instead of 0 (and nothing else)? See if things still work.

**Comment by Shaikh-Ubaid** [comment]
Yes, submitted here https://github.com/lfortran/lfortran/pull/1299

**Comment by certik** [comment]
Current status with WASM (they all work with LLVM):
* [ ] template_add 
* [ ] template_nested
* [ ] template_travel
* [ ] template_triple
* [ ] template_array_01
* [ ] template_array_02
* [ ] template_array_03

**Comment by certik** [comment]
Here is one bug:
```console
$ lfortran --show-wat template_array_01.f90 
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1878
    return emit_wat(arg_file, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 909
    LCompilers::Result<std::string> r = fe.get_wat(input, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 408
    Result<Vec<uint8_t>> wasm = get_wasm(code, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 395
    return asr_to_wasm_bytes_stream(*asr.result, al, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 2187
    pass_unused_functions(al, asr, pass_options);
  File "../libasr/asr.h", line 4450
  File "../libasr/asr.h", line 4426
  File "../libasr/asr.h", line 4451
  File "../libasr/asr.h", line 4184
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 297
    ASR::symbol_t *mod = x.m_global_scope->get_symbol(item);
  File "../libasr/asr.h", line 4453
  File "../libasr/asr.h", line 4193
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 344
    declare_all_functions(*x.m_symtab);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 329
    ASR::Function_t *s =
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 663
    return;
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 599
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4468
  File "../libasr/asr.h", line 4215
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 825
    *(ASR::down_cast<ASR::ArrayItem_t>(x.m_target)));
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 1426
    this->visit_expr(*m_dims[i].m_start);
  File "../libasr/asr.h", line 4513
  File "../libasr/asr.h", line 4513
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by certik** [comment]
The second bug is now fixed, just the first one remains.

**Comment by certik** [comment]
This issue is now fixed. I opened up a new issue for the last remaining bug: https://github.com/lfortran/lfortran/issues/1332
