### ISSUE TITLE
`Where` is not implemented.

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1312]
```fortran
subroutine where_1
    implicit none
    integer a(10)
    integer b(10)

    where (a > b) a = -1
    where (b>a)
        b = -1
    end where
    
end subroutine

program main
call where_1
end program
```

>LFortran

```console
$ lfortran a.f90 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/pranavchiku/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 1938, in ??
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 836, in ??
    result = fe.get_asr2(input, lm, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 248, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 270, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 97, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    requirement_map, implicit_mapping);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2445, in LCompilers::LFortran::body_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::ASR::asr_t*, LCompilers::CompilerOptions&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::asr_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::asr_t*> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::asr_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::asr_t*> > > > > >&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&)
    b.visit_TranslationUnit(ast);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 115, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4764, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4723, in ??
    case astType::program_unit: { v.visit_program_unit((const program_unit_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4772, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_program_unit(LCompilers::LFortran::AST::program_unit_t const&)
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4373, in ??
    case program_unitType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1335, in LCompilers::LFortran::BodyVisitor::visit_Subroutine(LCompilers::LFortran::AST::Subroutine_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 91, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4809, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4512, in ??
    case stmtType::Where: { v.visit_Where((const Where_t &)x); return; }
LCompilersException: visit_Where() not implemented
```

**Comment by Pranavchiku** [comment]
Workaround
```fortran
subroutine where_1
    implicit none
    integer a(10)
    integer b(10)
    integer i
    do i = 1, 10
        if (a(i) > b(i)) then
            a(i) = -1
        else
            b(i) = -1
        end if
    end do
    
end subroutine

program main
call where_1
end program
```

**Comment by Pranavchiku** [comment]
I guess this will not be difficult to implement, just replace `where` with a do loop over ( a ) and create if statements.

**Comment by Pranavchiku** [comment]
I am trying to implement this. The design goes as:
* Whenever encountering a `where` statement in `AST`, create a do loop over the length of target array.
* Do loop body will contain if statements and its body.
This approach is not optimized but I guess I can build something on it.

**Comment by Pranavchiku** [comment]
I have made progress on it. I will open PR soon.
