### ISSUE TITLE
`a(m:n)` results in SIGSEGV (segmentation fault) for LLVM

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1316]
```fortran
subroutine vecfcn(n)
    use iso_fortran_env, only: wp => real64
    implicit none
    integer :: n
    real(wp) :: fvec(n)
    real(wp) :: zero = 0.0_wp

    fvec(2:n) = zero

end subroutine vecfcn
```

> LFortran

```console
$ lfortran --implicit-typing --implicit-interface a.f90 --show-llvm
Traceback (most recent call last):
  Binary file "/home/pranavchiku/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 1862, in ??
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 775, in ??
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 287, in LCompilers::FortranEvaluator::get_llvm(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&)
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 309, in LCompilers::FortranEvaluator::get_llvm2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&)
    diagnostics, lm.files.back().in_filename);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 342, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6929, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_manager.h", line 213, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_manager.h", line 104, in LCompilers::PassManager::_apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/home/pranavchiku/lfortran/src/libasr/pass/array_op.cpp", line 1095, in LCompilers::pass_replace_array_op(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    u.visit_TranslationUnit(unit);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4669, in LCompilers::ASR::BaseWalkVisitor<LCompilers::PassUtils::UpdateDependenciesVisitor>::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/home/pranavchiku/lfortran/src/libasr/asr.h", line 4476, in LCompilers::ASR::BaseVisitor<LCompilers::PassUtils::UpdateDependenciesVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/asr.h", line 4217, in ??
    case symbolType::Function: { v.visit_Function((const Function_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_utils.h", line 287, in LCompilers::PassUtils::UpdateDependenciesVisitor::visit_Function(LCompilers::ASR::Function_t const&)
    BaseWalkVisitor<UpdateDependenciesVisitor>::visit_Function(x);
  File "/home/pranavchiku/lfortran/src/libasr/asr.h", line 4694, in LCompilers::ASR::BaseWalkVisitor<LCompilers::PassUtils::UpdateDependenciesVisitor>::visit_Function(LCompilers::ASR::Function_t const&)
    self().visit_stmt(*x.m_body[i]);
  File "/home/pranavchiku/lfortran/src/libasr/asr.h", line 4491, in LCompilers::ASR::BaseVisitor<LCompilers::PassUtils::UpdateDependenciesVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/asr.h", line 4234, in ??
    LCOMPILERS_ASSERT(x.base.type == asrType::stmt)
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __GI___sigaction()
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by Pranavchiku** [comment]
Fixed in #1319.
