### ISSUE TITLE
LLVM: `fvec(:n) = 0.0` fails

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1335]
```fortran
program main
    call vecfcn(10)

contains

subroutine vecfcn(n)
    integer, intent(in) :: n
    real :: fvec(n)

    fvec(:n) = 0.0
    print *, fvec

end subroutine vecfcn

end program main
```
gives:
```console
$ lfortran integration_tests/array_section_01.f90 
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1942
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 865
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 342
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7014
    v.nested_func_types = pass_find_nested_vars(asr, context,
  File "../libasr/asr.h", line 4477
  File "../libasr/asr.h", line 4453
  File "../libasr/asr.h", line 4478
  File "../libasr/asr.h", line 4210
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1288
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 4480
  File "../libasr/asr.h", line 4219
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2480
    declare_needed_global_types(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3938
    if (ASRUtils::get_FunctionType(s)->n_type_params == 0) {
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3538
    visit_procedures(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3890
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4495
  File "../libasr/asr.h", line 4241
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4315
    this->visit_expr_wrapper(x.m_value, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4502
    this->visit_expr(*x);
  File "../libasr/asr.h", line 4540
  File "../libasr/asr.h", line 4303
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4995
    this->visit_expr_wrapper(x.m_left, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4502
    this->visit_expr(*x);
  File "../libasr/asr.h", line 4540
  File "../libasr/asr.h", line 4341
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6973
    visit_expr_wrapper(x.m_dim, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4502
    this->visit_expr(*x);
  File "../libasr/asr.h", line 4540
  File "../libasr/asr.h", line 4540
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by Pranavchiku** [comment]
This probably might be because of assignment
```c
ASR::expr_t* start_expr = target_section->m_args[0].m_left;
head.m_start = start_expr;
```
Where `start_expr` is nullptr, which will be called out anywhere and hence results in segmentation fault.
I guess adding a check over `start_expr` to be nullptr, if yes then keeping it Integer 1 will work in this case.

**Comment by certik** [comment]
Yes, more logic has to be put in the code to handle this case.

**Comment by Pranavchiku** [comment]
Yeah, I did that will open PR once integration_tests run.
