### ISSUE TITLE
bug: array casting from single to double

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1403]
```fortran
program expr2
implicit none

real(8) :: x(3)

x = [1., 2., 3.]
print *, x
print *, sin(x)

end program
```
Gives:
```console
$ lfortran examples/expr2.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1942
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 836
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 248
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 270
    compiler_options.symtab_only, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 96
    auto res = body_visitor(al, ast, diagnostics, unit, compiler_options,
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2484
    b.requirement_map = requirement_map;
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 116
    visit_ast(*x.m_items[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4764
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4721
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4767
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4364
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1282
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 92
    this->visit_stmt(*m_body[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4809
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4465
    case stmtType::Assign: { v.visit_Assign((const Assign_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1676
    value_type, target_type);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/asr_implicit_cast_rules.h", line 162
    LCOMPILERS_ASSERT(ASR::is_a<ASR::RealConstant_t>(*value))
AssertFailed: ASR::is_a<ASR::RealConstant_t>(*value)
```

**Comment by Pranavchiku** [comment]
```fortran
program expr2
    implicit none
    
    real(8) :: x(3)
    
    x = [1., 2., 3.]
    
end program
```

This code produces same error.
