### ISSUE TITLE
bug: passing constant arrays to sin

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1405]
```fortran
program expr2
implicit none

print *, sin([1., 2., 3.])

end program
```
gives:
```console
$ lfortran examples/expr2.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1942
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 865
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 342
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7571
    v.nested_func_types = pass_find_nested_vars(asr, context,
  File "../libasr/asr.h", line 4527
  File "../libasr/asr.h", line 4503
  File "../libasr/asr.h", line 4528
  File "../libasr/asr.h", line 4258
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1312
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 4530
  File "../libasr/asr.h", line 4268
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3754
    visit_procedures(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4107
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4545
  File "../libasr/asr.h", line 4289
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4588
    bool is_value_data_only_array = ASRUtils::expr_abi(x.m_value) == ASR::abiType::BindC;
  File "../libasr/asr_utils.h", line 200
LCompilersException: Cannot extract the ABI of 3 expression.
```

**Comment by Pranavchiku** [comment]
One way to resolve this can be replacing `print *, sin([1.0,2.0,3.0])` to `print *, sin(1.0), sin(2.0), sin(3.0)` in ASR Pass.

**Comment by certik** [comment]
Currently the ASR is:
```console
$ lfortran --show-asr b.f90 --indent
(TranslationUnit
    (SymbolTable
        1
        {
            expr2:
                (Program
                    (SymbolTable
                        2
                        {
                            
                        })
                    expr2
                    []
                    [(Print
                        ()
                        [(IntrinsicFunction
                            Sin
                            [(ArrayConstant
                                [(RealConstant
                                    1.000000
                                    (Real 4 [])
                                )
                                (RealConstant
                                    2.000000
                                    (Real 4 [])
                                )
                                (RealConstant
                                    3.000000
                                    (Real 4 [])
                                )]
                                (Real 4 [((IntegerConstant 1 (Integer 4 []))
                                (IntegerConstant 3 (Integer 4 [])))])
                                ColMajor
                            )]
                            0
                            (Real 4 [((IntegerConstant 1 (Integer 4 []))
                            (IntegerConstant 3 (Integer 4 [])))])
                            ()
                        )]
                        ()
                        ()
                    )]
                )
        })
    []
)
```
And we need to add a compile time value for the IntrinsicFunction call. That should fix everything.

**Comment by czgdp1807** [comment]
I am working on it. The following case is the most general which I could figure out,

```fortran
program expr2
implicit none

real :: x = 1.0
real, allocatable :: a(:, :)
allocate(a(5, 10))
print *, sin([[1., 2., 3.], a, 5.])

end program
```

I noticed that the input "array constant" is flattened out by `gfortran`. The result would also be an allocatable with the size as the sum of the sizes of all the elements of "array constant"s (if any one element is an allocatable). If all the sizes are constants then we can create a fixed size result array. 

I will send a PR tomorrow for this.

**Comment by certik** [comment]
Thanks for fixing it, it works now.
