### ISSUE TITLE
Bug in `array_op.cpp`

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1445]
```fortran
module minpack_module

    implicit none


contains
    subroutine chkder(m, Err)

        implicit none

        integer, intent(in) :: m
        real, intent(out) :: Err(m)
        real :: zero = 0.0

        ! select case (Mode)
        Err = zero

    end subroutine chkder

end module minpack_module
```

> LFortran

```console
$ lfortran a.f90 --show-llvm
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/pranavchiku/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 1870, in ??
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 777, in ??
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 287, in LCompilers::FortranEvaluator::get_llvm(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&)
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 309, in LCompilers::FortranEvaluator::get_llvm2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&)
    diagnostics, lm.files.back().in_filename);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 342, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7940, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_manager.h", line 252, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_manager.h", line 136, in LCompilers::PassManager::_apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/home/pranavchiku/lfortran/src/libasr/pass/array_op.cpp", line 1169, in LCompilers::pass_replace_array_op(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    v.visit_TranslationUnit(unit);
  File "/home/pranavchiku/lfortran/src/libasr/pass/array_op.cpp", line 967, in LCompilers::ArrayOpVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*item.second);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4550, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayOpVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4287, in ??
    case symbolType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/pass/array_op.cpp", line 999, in LCompilers::ArrayOpVisitor::visit_Module(LCompilers::ASR::Module_t const&)
    this->visit_symbol(*item.second);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4550, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayOpVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4288, in ??
    case symbolType::Function: { v.visit_Function((const Function_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 41060, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayOpVisitor>::visit_Function(LCompilers::ASR::Function_t const&)
    self().transform_stmts(xx.m_body, xx.n_body);
  File "/home/pranavchiku/lfortran/src/libasr/pass/array_op.cpp", line 880, in LCompilers::ArrayOpVisitor::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    visit_stmt(*m_body[i]);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4565, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayOpVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4309, in ??
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/pass/array_op.cpp", line 1159, in LCompilers::ArrayOpVisitor::visit_Assignment(LCompilers::ASR::Assignment_t const&)
    visit_AssignmentUtil(x);
  File "/home/pranavchiku/lfortran/src/libasr/pass/array_op.cpp", line 1102, in LCompilers::ArrayOpVisitor::visit_AssignmentUtil(LCompilers::ASR::Assignment_t const&)
    this->call_replacer();
  File "/home/pranavchiku/lfortran/src/libasr/pass/array_op.cpp", line 863, in LCompilers::ArrayOpVisitor::call_replacer()
    replacer.replace_expr(*current_expr);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 40345, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceArrayOp>::replace_expr(LCompilers::ASR::expr_t*)
    self().replace_Var(down_cast<ASR::Var_t>(x));
  File "/home/pranavchiku/lfortran/src/libasr/pass/array_op.cpp", line 174, in LCompilers::ReplaceArrayOp::replace_Var(LCompilers::ASR::Var_t*)
    create_do_loop(loc, var_rank, result_rank, idx_vars,
AssertFailed: var_rank == (int) loop_vars.size()
```

**Comment by Pranavchiku** [comment]
Workaround
```diff
- Err = zero
+ Err = 0.0
```
