### ISSUE TITLE
[SciPy] FITPACK: ASR Assert Failed

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1447]
Pardon me for poor description of issues, I am using those to populate current status of SciPy compilation with LFortran. 
```console
$ lfortran --fixed-form --implicit-typing --implicit-interface /home/pranavchiku/scipy/scipy/interpolate/fitpack/fpcons.f --show-asr
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/pranavchiku/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 1864, in ??
    return emit_asr(arg_file, lfortran_pass_manager,
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 612, in ??
    r = fe.get_asr2(input, lm, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 248, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 270, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 97, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    requirement_map, implicit_mapping);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2700, in LCompilers::LFortran::body_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::ASR::asr_t*, LCompilers::CompilerOptions&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::asr_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::asr_t*> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::asr_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::asr_t*> > > > > >&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&)
    b.visit_TranslationUnit(ast);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 123, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4764, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4723, in ??
    case astType::program_unit: { v.visit_program_unit((const program_unit_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4772, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_program_unit(LCompilers::LFortran::AST::program_unit_t const&)
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4373, in ??
    case program_unitType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1539, in LCompilers::LFortran::BodyVisitor::visit_Subroutine(LCompilers::LFortran::AST::Subroutine_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 99, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4809, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4505, in ??
    case stmtType::DoLoop: { v.visit_DoLoop((const DoLoop_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2360, in LCompilers::LFortran::BodyVisitor::visit_DoLoop(LCompilers::LFortran::AST::DoLoop_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 99, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4809, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4466, in ??
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1815, in LCompilers::LFortran::BodyVisitor::visit_Assignment(LCompilers::LFortran::AST::Assignment_t const&)
    this->visit_expr(*x.m_value);
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4860, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_expr(LCompilers::LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4528, in ??
    case exprType::FuncCallOrArray: { v.visit_FuncCallOrArray((const FuncCallOrArray_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 3611, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_FuncCallOrArray(LCompilers::LFortran::AST::FuncCallOrArray_t const&)
    create_implicit_interface_function(x, var_name, true, old_type);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 3428, in void LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_implicit_interface_function<LCompilers::LFortran::AST::FuncCallOrArray_t>(LCompilers::LFortran::AST::FuncCallOrArray_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, LCompilers::ASR::ttype_t*)
    visit_expr_list(x.m_args, x.n_args, c_args);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4442, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_expr_list(LCompilers::LFortran::AST::fnarg_t*, unsigned long, LCompilers::Vec<LCompilers::ASR::call_arg_t>&)
    this->visit_expr(*ast_list[i].m_end);
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4860, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_expr(LCompilers::LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/lfortran/ast.h", line 4528, in ??
    case exprType::FuncCallOrArray: { v.visit_FuncCallOrArray((const FuncCallOrArray_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 3609, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_FuncCallOrArray(LCompilers::LFortran::AST::FuncCallOrArray_t const&)
    current_scope->erase_symbol(var_name);
AssertFailed: scope.find(name) != scope.end()
```

**Comment by Pranavchiku** [comment]
#1739

**Comment by Pranavchiku** [comment]
Fixed with Latest main
