### ISSUE TITLE
Bug in pass_array_by_data.cpp

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1477]
```fortran
program example_primes
implicit none
contains

subroutine find_fit(data_x, expr)
real, intent(in) :: data_x(:)
interface
    function expr(x) result(y)
        real, intent(in) :: x
        real :: y
    end function expr
end interface
end subroutine find_fit
end program example_primes
```

> LFortran

```console
$ lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/pranavchiku/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 1946, in ??
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 867, in ??
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 342, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8034, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_manager.h", line 253, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_manager.h", line 137, in LCompilers::PassManager::_apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 541, in LCompilers::pass_array_by_data(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    v.visit_TranslationUnit(unit);
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 265, in LCompilers::PassArrayByDataProcedureVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4543, in LCompilers::ASR::BaseVisitor<LCompilers::PassArrayByDataProcedureVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4281, in ??
    case symbolType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 306, in LCompilers::PassArrayByDataProcedureVisitor::visit_Module(LCompilers::ASR::Module_t const&)
    visit_SymbolContainingFunctions(x);
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 286, in void LCompilers::PassArrayByDataProcedureVisitor::visit_SymbolContainingFunctions<LCompilers::ASR::Module_t>(LCompilers::ASR::Module_t const&)
    ASR::symbol_t* sym = insert_new_procedure(subrout, arg_indices);
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 171, in LCompilers::PassArrayByDataProcedureVisitor::insert_new_procedure(LCompilers::ASR::Function_t*, std::vector<unsigned long, std::allocator<unsigned long> >&)
    arg = ASRUtils::EXPR2VAR(x->m_args[i]);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr_utils.h", line 98, in ??
    return ASR::down_cast<ASR::Variable_t>(symbol_get_past_external(
AssertFailed: is_a<T>(*f)
```

**Comment by Pranavchiku** [comment]
This happens as on inserting a new procedure ( for `find_fit` ), the argument list is expected to contain all `Variable_t*`, but `expr` is `Function_t*` and hence throws an error at downcasting.
