### ISSUE TITLE
ASR verify pass error for ASR from pass_array_by_data

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1486]
```fortran
subroutine find_fit(expr)
interface
    real function expr(x)
        real, intent(in) :: x(:)
    end function expr
end interface
end subroutine find_fit

program example_primes
implicit none
call find_fit(expression)

contains
real function expression(x)
    real, intent(in) :: x(:)
end function expression

end program example_primes
```

> LFortran

```console
$ lfortran a.f90 
ASR verify pass error: ASR verify: Var::m_v `expression` cannot point outside of its symbol table
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/pranavchiku/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 1946, in ??
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 867, in ??
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 342, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8035, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_manager.h", line 253, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _apply_passes(al, asr, _passes, pass_options, diagnostics);
LCompilersException: Verify failed
```

**Comment by Pranavchiku** [comment]
I have code to resolve this issue, but after this I get a code generation error because of #1488.

**Comment by certik** [comment]
You can submit what you have, and just test that. The nested function stuff will get fixed in a general way using https://github.com/lfortran/lfortran/pull/1464.

**Comment by Pranavchiku** [comment]
I will prefer to wait till #1464 gets merged as it has major revamp, any update in the code of pass_array_by_data will be of no use once that gets merged.
