### ISSUE TITLE
Unhandled nullptr exception for updating return type in pass_array_by_data

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1516]
This is because I forgot to check if return variable is nullptr in #1491.
```fortran
module find_fit_module
contains
subroutine find_fit(data_x)
real, intent(in) :: data_x(:)

contains
    subroutine fcn()
    end subroutine fcn
end subroutine find_fit

end module find_fit_module

program example_primes

use find_fit_module, only: find_fit

implicit none

real :: data_x(20)
integer :: i
do i = 1, 20
    data_x(i) = real(i)
end do
call find_fit(data_x)

end program example_primes
```

> LFortran 

```console
$ lfortran ./tests/temp.f90 
Traceback (most recent call last):
  Binary file "/home/pranavchiku/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 1946, in ??
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 867, in ??
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 342, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8078, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_manager.h", line 270, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_manager.h", line 144, in LCompilers::PassManager::_apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 662, in LCompilers::pass_array_by_data(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    v.visit_TranslationUnit(unit);
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 272, in LCompilers::PassArrayByDataProcedureVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4543, in LCompilers::ASR::BaseVisitor<LCompilers::PassArrayByDataProcedureVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4281, in ??
    case symbolType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 351, in LCompilers::PassArrayByDataProcedureVisitor::visit_Module(LCompilers::ASR::Module_t const&)
    visit_SymbolContainingFunctions(x);
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 321, in void LCompilers::PassArrayByDataProcedureVisitor::visit_SymbolContainingFunctions<LCompilers::ASR::Module_t>(LCompilers::ASR::Module_t const&)
    ASR::symbol_t* sym = insert_new_procedure(subrout, arg_indices);
  File "/home/pranavchiku/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 132, in LCompilers::PassArrayByDataProcedureVisitor::insert_new_procedure(LCompilers::ASR::Function_t*, std::vector<unsigned long, std::allocator<unsigned long> >&)
    symbol_duplicator.duplicate_symbol(item.second, new_symtab);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr_utils.h", line 2686, in LCompilers::ASRUtils::SymbolDuplicator::duplicate_symbol(LCompilers::ASR::symbol_t*, LCompilers::SymbolTable*)
    new_symbol = duplicate_Function(function, destination_symtab);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr_utils.h", line 2806, in LCompilers::ASRUtils::SymbolDuplicator::duplicate_Function(LCompilers::ASR::Function_t*, LCompilers::SymbolTable*)
    if (new_return_var && ASR::is_a<ASR::Var_t>(*new_return_var)) {
  File "/home/pranavchiku/lfortran/src/libasr/asr.h", line 32, in bool LCompilers::ASR::is_a<LCompilers::ASR::Var_t, LCompilers::ASR::expr_t>(LCompilers::ASR::expr_t const&)
    return T::class_type == x.type;
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __GI___sigaction()
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by Pranavchiku** [comment]
Closed as completed via #1510.
