### ISSUE TITLE
[Minpack]: Segfault: LCOMPILERS_ASSERT(x.base.type == asrType::expr)

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1564]
```fortran
program main
    implicit none

    call compare_solutions()

    contains

    subroutine compare_solutions()
    implicit none
    real, dimension(:), allocatable :: temp
    temp = solution()

    end subroutine compare_solutions

    pure function solution() result(x)
        implicit none
        real,dimension(:),allocatable :: x
        x = [0.10,0.10]
    end function solution
end program main
```

> LFortran
```console
$ lfortran a.f90
Traceback (most recent call last):
  Binary file "/home/pranavchiku/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 1870, in ??
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 777, in ??
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 287, in LCompilers::FortranEvaluator::get_llvm(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&)
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 309, in LCompilers::FortranEvaluator::get_llvm2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&)
    diagnostics, lm.files.back().in_filename);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 342, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7755, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4540, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4516, in ??
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4541, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4272, in ??
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1359, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4543, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4280, in ??
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2627, in LCompilers::ASRToLLVMVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    visit_procedures(x);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4037, in void LCompilers::ASRToLLVMVisitor::visit_procedures<LCompilers::ASR::Program_t>(LCompilers::ASR::Program_t const&)
    visit_Function(*s);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3677, in LCompilers::ASRToLLVMVisitor::visit_Function(LCompilers::ASR::Function_t const&)
    generate_function(x);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3985, in LCompilers::ASRToLLVMVisitor::generate_function(LCompilers::ASR::Function_t const&)
    define_function_entry(x);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3913, in LCompilers::ASRToLLVMVisitor::define_function_entry(LCompilers::ASR::Function_t const&)
    declare_local_vars(x);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3659, in void LCompilers::ASRToLLVMVisitor::declare_local_vars<LCompilers::ASR::Function_t>(LCompilers::ASR::Function_t const&)
    declare_vars(x);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3261, in void LCompilers::ASRToLLVMVisitor::declare_vars<LCompilers::ASR::Function_t>(LCompilers::ASR::Function_t const&, bool)
    fill_array_details_(ptr, m_dims, n_dims,
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3027, in LCompilers::ASRToLLVMVisitor::fill_array_details_(llvm::Value*, LCompilers::ASR::dimension_t*, unsigned long, bool, bool, bool, LCompilers::ASR::ttype_t*, bool)
    fill_array_details(ptr, llvm_data_type, m_dims, n_dims, is_data_only);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 547, in LCompilers::ASRToLLVMVisitor::fill_array_details(llvm::Value*, llvm::Type*, LCompilers::ASR::dimension_t*, int, bool)
    visit_expr(*(m_dim.m_start));
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4603, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4350, in ??
    LCOMPILERS_ASSERT(x.base.type == asrType::expr)
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __GI___sigaction()
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by Thirumalai-Shaktivel** [comment]
The following diff seems to work:
```diff
diff --git a/examples/expr2.f90 b/examples/expr2.f90
index 010e4d7dc..427fb497d 100644
--- a/examples/expr2.f90
+++ b/examples/expr2.f90
@@ -8,13 +8,15 @@ program main
     subroutine compare_solutions()
     implicit none
     real, dimension(:), allocatable :: temp
+    allocate(temp(2))
     temp = solution()
-
+    print *, temp(1), temp(2)
     end subroutine compare_solutions
 
     pure function solution() result(x)
         implicit none
         real,dimension(:),allocatable :: x
+        allocate(x(2))
         x = [0.10,0.10]
     end function solution
 end program main
```

**Comment by Pranavchiku** [comment]
Okay, but the trouble is `x` in `solution()` is of variable length.

**Comment by Thirumalai-Shaktivel** [comment]
Can you please share the actual code that fails with this error?

**Comment by Pranavchiku** [comment]
```fortran
program main
    implicit none

    call compare_solutions()

    contains

    subroutine compare_solutions()
    implicit none
    real, dimension(:), allocatable :: temp
    temp = solution()

    end subroutine compare_solutions

    pure function solution(nprob) result(x)
        implicit none
        real,dimension(:),allocatable :: x
        integer,intent(in) :: nprob
        select case(nprob)
        case(1); x = [0.10,0.10]
        case(2); x = [0.10,0.10, 0.10]
        case(3); x = [0.10,0.10, 0.10, 0.10]
    end function solution
end program main
````
