### ISSUE TITLE
Importing modules does not work in interactive mode

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1588]
```fortran
module funcmod
implicit none
contains
function add(x,y)
real :: x, y
real :: add
add = x+y
end function add
function subtract(x,y)
real :: x, y
real :: subtract
subtract = x-y
end function subtract
end module funcmod
```
Compile using:
```console
lfortran -c a.f90 -o a.o
```
and import using:
```
$ lfortran 
Interactive Fortran. Experimental prototype, not ready for end users.
LFortran version: 0.18.0-1172-g6eeb126cd
  * Use Ctrl-D to exit
  * Use Enter to submit
  * Use Alt-Enter or Ctrl-N to make a new line
    - Editing (Keys: Left, Right, Home, End, Backspace, Delete)
    - History (Keys: Up, Down)
>>> use funcmod, only : add, subtract                                    1,34  ]
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1794
    return prompt(arg_v);
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 293
    std::cerr << diagnostics.render(lm, cu);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 94
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 270
    compiler_options.symtab_only, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 81
    auto res = symbol_table_visitor(al, ast, diagnostics, symbol_table,
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 2116
    SymbolTableVisitor v(al, symbol_table, diagnostics, compiler_options, implicit_mapping);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 114
    visit_ast(*x.m_items[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4765
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4724
    case astType::program_unit: { v.visit_program_unit((const program_unit_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4777
    void visit_unit_decl1(const unit_decl1_t &b) { visit_unit_decl1_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4383
    switch (x.type) {
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1858
    ASR::symbol_t *t = current_scope->parent->resolve_symbol(msym);
  File "../libasr/asr_scopes.h", line 42
  File "/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/map", line 1380
    iterator find(const key_type& __k)             {return __tree_.find(__k);}
  File "/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/__tree", line 2466
    iterator __p = __lower_bound(__v, __root(), __end_node());
  File "/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/__tree", line 1079
    {return static_cast<__node_pointer>(__end_node()->__left_);}
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by AkhilAkkapelli** [comment]
I am getting segmentation fault.

testmod.f90
`
module testmod
implicit none
contains
function add(x,y)
real :: x, y
real :: add
add = x+y
end function add
function subtract(x,y)
real :: x, y
real :: subtract
subtract = x-y
end function subtract
end module testmod
`

`akhil@KHUSHI:~/lfortran/mytest$ ../src/bin/lfortran -c testmod.f90 -o a.o
akhil@KHUSHI:~/lfortran/mytest$ ../src/bin/lfortran
Interactive Fortran. Experimental prototype, not ready for end users.
LFortran version: 0.18.0-1172-g6eeb126cd
  * Use Ctrl-D to exit
  * Use Enter to submit
  * Use Alt-Enter or Ctrl-N to make a new line
    - Editing (Keys: Left, Right, Home, End, Backspace, Delete)
    - History (Keys: Up, Down)
>>> use funcmod, only : add, subtract                                    1,34  ]
Segmentation fault (core dumped)`

**Comment by certik** [comment]
@AkhilAkkapelli you probably compiled without stacktraces. If you look, I am also getting a segmentation fault, it just prints a stacktrace.

**Comment by Shaikh-Ubaid** [comment]
I think you need to pass `-DWITH_STACKTRACE=yes` to cmake.
