### ISSUE TITLE
Semantic error for `type(real(kind=4))`

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1628]
This code:
```fortran
      program main

      integer, parameter :: N = 7
    
      type(real(kind=4)), allocatable :: x(:)
      integer :: i

      allocate(x(N))
      do i = 1, N
        x(i) = real(i, 4) / real(N, 4)
      end do
      write (*,*) "x = ", x

      end program main
```
Gives:
```console
$ lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1944
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 838
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 252
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 274
    compiler_options.symtab_only, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 81
    auto res = symbol_table_visitor(al, ast, diagnostics, symbol_table,
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 2125
    SymbolTableVisitor v(al, symbol_table, diagnostics, compiler_options, implicit_mapping);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 114
    visit_ast(*x.m_items[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4767
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4724
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4770
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4367
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 463
    visit_unit_decl2(*x.m_decl[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4781
    void visit_unit_decl2(const unit_decl2_t &b) { visit_unit_decl2_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4394
    case unit_decl2Type::Declaration: { v.visit_Declaration((const Declaration_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1010
    visit_DeclarationUtil(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 1462
    ASR::ttype_t *type = determine_type(x.base.base.loc, sym, x.m_vartype, is_pointer,
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 1805
    LCOMPILERS_ASSERT(sym_type->m_name);
AssertFailed: sym_type->m_name
```

**Comment by Shaikh-Ubaid** [comment]
Also, the following example fails:
```fortran
(lf) $ cat examples/expr2.f90 
program main
  type(integer) :: a
  a = 25
  print *, a
end program
(lf) $ gfortran examples/expr2.f90 
(lf) $ ./a.out 
          25
(lf) $ lfortran examples/expr2.f90
ASR verify pass error: ASR verify: Struct::m_derived_type cannot point outside of its symbol table
 --> examples/expr2.f90:2:3
  |
2 |   type(integer) :: a
  |   ^^^^^^^^^^^^^^^^^^ failed here


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that must be fixed).
```

**Comment by certik** [comment]
Thanks @Shaikh-Ubaid for fixing this!
