### ISSUE TITLE
Minpack test_hybrd: Verify failed in the pass: where

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1633]
```console
$ lfortran -c src/minpack.f90
$ lfortran test/test_hybrd.f90     
ASR verify pass error: ASR verify: The input and output type of elemental intrinsics must exactly match, input type: r64 output type: r32
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1945
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 868
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 346
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7850
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 277
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 153
    + passes[i]);
LCompilersException: Verify failed in the pass: where
```

**Comment by Pranavchiku** [comment]
I know this error, it will be quick to fix if I am guessing this correctly. I will open PR soon.

**Comment by certik** [comment]
Thanks for fixing it @Pranavchiku !

It is now fixed. Here is the next error: https://github.com/lfortran/lfortran/issues/1636.
