### ISSUE TITLE
Minpack test_hybrd: segfault in LLVM fill_array_details

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1636]
```console
$ lfortran -c src/minpack.f90
$ lfortran test/test_hybrd.f90
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1945
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 868
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 346
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7850
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "../libasr/asr.h", line 4564
  File "../libasr/asr.h", line 4540
  File "../libasr/asr.h", line 4565
  File "../libasr/asr.h", line 4294
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1354
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 4567
  File "../libasr/asr.h", line 4303
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2624
    visit_procedures(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4074
    if (ASRUtils::get_FunctionType(s)->n_type_params == 0) {
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3717
    visit_procedures(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4022
    if (!prototype_only) {
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3950
    declare_args(x, *F);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3700
    declare_vars(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3271
    ASR::expr_t* init_expr = v->m_symbolic_value;
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3032
    fill_array_details(ptr, llvm_data_type, m_dims, n_dims, is_data_only);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 542
    visit_expr(*(m_dim.m_start));
  File "../libasr/asr.h", line 4627
  File "../libasr/asr.h", line 4627
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by Pranavchiku** [comment]
Yes, this is because of #1631, which I think will get fixed by #1630.

**Comment by Thirumalai-Shaktivel** [comment]
It might be related to the `tmp return variable` not using Allocatable as storageType. Yup, I think #1630 will fix it.

**Comment by czgdp1807** [comment]
I think instead of adding more partial fixes, we should enable testing compilation of `test/test_hybrd.f90` on CI and then in the same PR make it pass. Otherwise we will never know whatever we are doing is correct or not. On using #1630 (after rebasing on top of `main`) I get the following,

```zsh
Traceback (most recent call last):
  File "/Users/czgdp1807/lfortran_project/lfortran/src/bin/lfortran.cpp", line 1945
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/czgdp1807/lfortran_project/lfortran/src/bin/lfortran.cpp", line 868
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/fortran_evaluator.cpp", line 346
    compiler_options, run_fn, infile);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7856
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 4564
  File "../libasr/asr.h", line 4540
  File "../libasr/asr.h", line 4565
  File "../libasr/asr.h", line 4295
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1354
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 4567
  File "../libasr/asr.h", line 4303
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2624
    visit_procedures(x);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4075
    visit_Function(*s);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3717
    visit_procedures(x);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4026
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4582
  File "../libasr/asr.h", line 4337
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5098
    this->visit_expr_wrapper(x.m_test, true);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4741
    this->visit_expr(*x);
  File "../libasr/asr.h", line 4627
  File "../libasr/asr.h", line 4387
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4896
    this->visit_expr_wrapper(x.m_left, true);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4741
    this->visit_expr(*x);
  File "../libasr/asr.h", line 4627
  File "../libasr/asr.h", line 4424
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2055
    tmp = arr_descr->get_single_element(array, indices, x.n_args,
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 484
    idx = cmo_convertor_single_element(array, m_args, n_args, check_for_bounds);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 428
    llvm::Value* dim_des_arr_ptr = LLVM::CreateLoad(*builder, llvm_utils->create_gep(arr, 2));
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/llvm_utils.cpp", line 121
    return LLVM::CreateGEP(*builder, ds, idx_vec);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/llvm_utils.cpp", line 24
    llvm::Type *t = x->getType();
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x18042ea83
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by Pranavchiku** [comment]
Above one is #1563, we have a workaround for it mentioned in that issue itself.

**Comment by Thirumalai-Shaktivel** [comment]
Cool @czgdp1807, Let me try to set up a CI to test test_hybrid and fix all the issues related to it there.

**Comment by czgdp1807** [comment]
So https://github.com/lfortran/lfortran/issues/1636#issuecomment-1530931154 happens because nested_vars pass only handles those variables and arrays which don't have `parameter` attribute. See the two codes below,

**info_original** is not a `parameter`

```fortran
program expr2
implicit none

integer,dimension(55) :: info_original = [1,1,1,4,4,4,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,&
                                                        1,1,1,4,4,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,1,1,&
                                                        1,1,1,1,1,1,1,1,1]

contains

subroutine compare_solutions(ic, x, reltol, abstol)
    implicit none

    integer, intent(in) :: ic
    real(8), dimension(:), intent(in) :: x

    real(8), intent(in) :: reltol

    real(8), intent(in) :: abstol !! absolute tolerance for `x` to pass

    real(8), dimension(size(x)) :: diff, absdiff, reldiff

    if (info_original(ic) < 5) then
        diff = solution(ic) - x
        absdiff = abs(diff)
        if (any(absdiff>abstol)) then
            reldiff = absdiff
            where (solution(ic) /= 0.0_8) reldiff = absdiff / abs(solution(ic))
            if (any(reldiff > reltol)) then
            end if
        end if
    end if

end subroutine compare_solutions

pure function solution(nprob) result(x)
implicit none

    integer, intent(in) :: nprob
    real(8), dimension(:), allocatable :: x

    select case (nprob)
        case (1); x = [0.1000000000000000E+01_8,0.1000000000000000E+01_8]
        case (2); x = [0.1000000000000000E+01_8,0.1000000000000000E+01_8]
        case (3); x = [0.1000000000000000E+01_8,0.1000000000000054E+01_8]
        case default
            error stop 'invalid case'
    end select

end function solution

end program
```

```zsh
(lf) 12:04:08:~/lfortran_project/lfortran % lfortran /Users/czgdp1807/lfortran_project/debug.f90 --skip-pass=unused_functions --show-llvm > ../debug.ll 
```

**info_original** is a `parameter`

```fortran
program expr2
implicit none

integer,dimension(55),parameter :: info_original = [1,1,1,4,4,4,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,&
                                                        1,1,1,4,4,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,1,1,&
                                                        1,1,1,1,1,1,1,1,1]

contains

subroutine compare_solutions(ic, x, reltol, abstol)
    implicit none

    integer, intent(in) :: ic
    real(8), dimension(:), intent(in) :: x

    real(8), intent(in) :: reltol

    real(8), intent(in) :: abstol !! absolute tolerance for `x` to pass

    real(8), dimension(size(x)) :: diff, absdiff, reldiff

    if (info_original(ic) < 5) then
        diff = solution(ic) - x
        absdiff = abs(diff)
        if (any(absdiff>abstol)) then
            reldiff = absdiff
            where (solution(ic) /= 0.0_8) reldiff = absdiff / abs(solution(ic))
            if (any(reldiff > reltol)) then
            end if
        end if
    end if

end subroutine compare_solutions

pure function solution(nprob) result(x)
implicit none

    integer, intent(in) :: nprob
    real(8), dimension(:), allocatable :: x

    select case (nprob)
        case (1); x = [0.1000000000000000E+01_8,0.1000000000000000E+01_8]
        case (2); x = [0.1000000000000000E+01_8,0.1000000000000000E+01_8]
        case (3); x = [0.1000000000000000E+01_8,0.1000000000000054E+01_8]
        case default
            error stop 'invalid case'
    end select

end function solution

end program
```

```zsh
(lf) 12:04:59:~/lfortran_project/lfortran % lfortran /Users/czgdp1807/lfortran_project/debug.f90 --skip-pass=unused_functions --show-llvm > ../debug.ll
Traceback (most recent call last):
  File "/Users/czgdp1807/lfortran_project/lfortran/src/bin/lfortran.cpp", line 1869
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/czgdp1807/lfortran_project/lfortran/src/bin/lfortran.cpp", line 778
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/fortran_evaluator.cpp", line 291
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/fortran_evaluator.cpp", line 313
    diagnostics, lm.files.back().in_filename);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/fortran_evaluator.cpp", line 346
    compiler_options, run_fn, infile);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7858
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 4564
  File "../libasr/asr.h", line 4540
  File "../libasr/asr.h", line 4565
  File "../libasr/asr.h", line 4295
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1354
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 4567
  File "../libasr/asr.h", line 4303
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2624
    visit_procedures(x);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4077
    visit_Function(*s);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3718
    visit_procedures(x);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4028
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4582
  File "../libasr/asr.h", line 4337
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5100
    this->visit_expr_wrapper(x.m_test, true);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4743
    this->visit_expr(*x);
  File "../libasr/asr.h", line 4627
  File "../libasr/asr.h", line 4387
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4898
    this->visit_expr_wrapper(x.m_left, true);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4743
    this->visit_expr(*x);
  File "../libasr/asr.h", line 4627
  File "../libasr/asr.h", line 4424
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2055
    tmp = arr_descr->get_single_element(array, indices, x.n_args,
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 484
    idx = cmo_convertor_single_element(array, m_args, n_args, check_for_bounds);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 428
    llvm::Value* dim_des_arr_ptr = LLVM::CreateLoad(*builder, llvm_utils->create_gep(arr, 2));
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/llvm_utils.cpp", line 121
    return LLVM::CreateGEP(*builder, ds, idx_vec);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/llvm_utils.cpp", line 24
    llvm::Type *t = x->getType();
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x18042ea83
Segfault: Signal SIGSEGV (segmentation fault) received
```

So there are two things here,

1. `nested_vars` - I think it shouldn't always ignore `parameter` variables which are arrays. Because `ArrayItem` cannot always be evaluated to a compile time constant. Its only possible when both the array and the index are compile time constants (in the above case index is runtime input argument).
2. `ArrayItem` isn't evaluated to compile time values whenever possible. Something for later.

@Thirumalai-Shaktivel I will push a fix to your branch in an hour or so. Meanwhile enable `test_hybrd.f90` on CI in your PR and rebase on top of `main`. Let me know when you are done.
