### ISSUE TITLE
[Scipy] lbfgsb.f AssertFailed: s.source_code.size() > 0

### ISSUE THREAD

**Issue by gptsarthak** [lfortran/lfortran#1692]
Compiling ```scipy/optimize/lbfgsb_src/lbfgsb.f``` with ```lfortran --show-asr --fixed-form --implicit-typing --implicit-interface lbfgsb.f``` yeilds:
```console
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/sarthak/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/sarthak/lfortran/src/bin/lfortran.cpp", line 1886, in ??
    return emit_asr(arg_file, lfortran_pass_manager,
  File "/home/sarthak/lfortran/src/bin/lfortran.cpp", line 640, in ??
    std::cerr << diagnostics.render(lm, compiler_options);
  File "/home/sarthak/lfortran/src/libasr/diagnostics.cpp", line 72, in LCompilers::diag::Diagnostics::render[abi:cxx11](LCompilers::LocationManager&, LCompilers::CompilerOptions const&)
    out += render_diagnostic_human(d, lm, compiler_options.use_colors,
  File "/home/sarthak/lfortran/src/libasr/diagnostics.cpp", line 151, in LCompilers::diag::render_diagnostic_human[abi:cxx11](LCompilers::diag::Diagnostic&, LCompilers::LocationManager const&, bool, bool)
    populate_spans(d, lm);
  File "/home/sarthak/lfortran/src/libasr/diagnostics.cpp", line 138, in LCompilers::diag::populate_spans(LCompilers::diag::Diagnostic&, LCompilers::LocationManager const&)
    populate_span(s, lm);
AssertFailed: s.source_code.size() > 0
```
Will work on minimal reproduction of the error after registering the issues.

**Comment by certik** [comment]
With this change:
```diff
diff --git a/src/libasr/diagnostics.cpp b/src/libasr/diagnostics.cpp
index e6d8618ad..e43ff3a64 100644
--- a/src/libasr/diagnostics.cpp
+++ b/src/libasr/diagnostics.cpp
@@ -128,7 +128,7 @@ void populate_span(diag::Span &s, const LocationManager &lm) {
     for (uint32_t i = s.first_line; i <= s.last_line; i++) {
         s.source_code.push_back(get_line(input, i));
     }
-    LCOMPILERS_ASSERT(s.source_code.size() > 0)
+    //LCOMPILERS_ASSERT(s.source_code.size() > 0)
 }
 
 // Loop over all labels and their spans, populate all of them
@@ -150,7 +150,7 @@ std::string render_diagnostic_human(Diagnostic &d, const LocationManager &lm,
     // Convert to line numbers and get source code strings
     populate_spans(d, lm);
     // Render the message
-    out += render_diagnostic_human(d, use_colors);
+    out += render_diagnostic_short(d, lm);
     return out;
 }
```
We get the ASR, there are some warnings like this:
```console
$ lfortran --show-asr --fixed-form --implicit-typing --implicit-interface lbfgsb.f
lbfgsb.f:3931-42:825205836-7: warning: Format statement is not implemented yet, for now we will ignore it
lbfgsb.f:3931-42:841983052-7: warning: Format statement is not implemented yet, for now we will ignore it
lbfgsb.f:3931-42:858760268-7: warning: Format statement is not implemented yet, for now we will ignore it
...
lbfgsb.f:3931-42:875537484-7: warning: Format statement is not implemented yet, for now we will ignore it


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that must be fixed).
(TranslationUnit
    (SymbolTable
        1
        {
            active:
                (Function
                    (SymbolTable
                        4
                        {
                            boxed:
                                (Variable
                                    4
                                    boxed
                                    []
...
```

The bug comes from having incorrect location information.

**Comment by gptsarthak** [comment]
I had a hunch that the error might be related to the ```format``` statement, and I was right.
I removed all the ```format``` statements from the file and it produced the ASR for me.
We need to produce a proper error till we implement it, https://github.com/lfortran/lfortran/issues/1718#issuecomment-1568471541 also seems to be a related error.

**Comment by gptsarthak** [comment]
This issue is fixed in master.
