### ISSUE TITLE
[SciPy]: ASR COMMON block issue

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1715]
```fortran
      subroutine solsy ()
      double precision rowns
      common /ls0001/ rowns(209)
      end
```

> LFortran
```console
% lfortran /Users/pgoswami/repos/scipy/scipy/integrate/odepack/solsy.f --show-asr --fixed-form --implicit-typing --implicit-interface
LCOMPILERS_ASSERT failed: /Users/pgoswami/Desktop/lfortran/src/libasr/asr.h
function down_cast(), line number 40 at 
f != nullptr
zsh: abort      lfortran /Users/pgoswami/repos/scipy/scipy/integrate/odepack/solsy.f
```

**Comment by gptsarthak** [comment]
The error I get with this code is different now:
```console
(lf) sarthak@pop-os:~/scipy/scipy/integrate/odepack$ lfortran --show-asr --fixed-form --implicit-typing --implicit-interface solsy_copy.f 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/sarthak/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/sarthak/lfortran/src/bin/lfortran.cpp", line 1886, in ??
    return emit_asr(arg_file, lfortran_pass_manager,
  File "/home/sarthak/lfortran/src/bin/lfortran.cpp", line 639, in ??
    r = fe.get_asr2(input, lm, diagnostics);
  File "/home/sarthak/lfortran/src/lfortran/fortran_evaluator.cpp", line 252, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/home/sarthak/lfortran/src/lfortran/fortran_evaluator.cpp", line 274, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/home/sarthak/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 85, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    compiler_options, requirement_map, implicit_mapping, common_variables_hash);
  File "/home/sarthak/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 2210, in LCompilers::LFortran::symbol_table_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, LCompilers::CompilerOptions&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::asr_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::asr_t*> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::asr_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::asr_t*> > > > > >&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompilers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&)
    v.visit_TranslationUnit(ast);
  File "/home/sarthak/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 119, in LCompilers::LFortran::SymbolTableVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/sarthak/lfortran/src/lfortran/ast.h", line 4768, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/sarthak/lfortran/src/lfortran/ast.h", line 4727, in ??
    case astType::program_unit: { v.visit_program_unit((const program_unit_t &)x); return; }
  File "/home/sarthak/lfortran/src/lfortran/ast.h", line 4776, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_program_unit(LCompilers::LFortran::AST::program_unit_t const&)
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/home/sarthak/lfortran/src/lfortran/ast.h", line 4377, in ??
    case program_unitType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/home/sarthak/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 529, in LCompilers::LFortran::SymbolTableVisitor::visit_Subroutine(LCompilers::LFortran::AST::Subroutine_t const&)
    visit_unit_decl2(*x.m_decl[i]);
  File "/home/sarthak/lfortran/src/lfortran/ast.h", line 4782, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_unit_decl2(LCompilers::LFortran::AST::unit_decl2_t const&)
    void visit_unit_decl2(const unit_decl2_t &b) { visit_unit_decl2_t(b, self()); }
  File "/home/sarthak/lfortran/src/lfortran/ast.h", line 4395, in ??
    case unit_decl2Type::Declaration: { v.visit_Declaration((const Declaration_t &)x); return; }
  File "/home/sarthak/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1027, in LCompilers::LFortran::SymbolTableVisitor::visit_Declaration(LCompilers::LFortran::AST::Declaration_t const&)
    visit_DeclarationUtil(x);
  File "/home/sarthak/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 1387, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_DeclarationUtil(LCompilers::LFortran::AST::Declaration_t const&)
    this->visit_expr(*expr);
  File "/home/sarthak/lfortran/src/lfortran/ast.h", line 4864, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_expr(LCompilers::LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/sarthak/lfortran/src/lfortran/ast.h", line 4532, in ??
    case exprType::FuncCallOrArray: { v.visit_FuncCallOrArray((const FuncCallOrArray_t &)x); return; }
  File "/home/sarthak/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4145, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_FuncCallOrArray(LCompilers::LFortran::AST::FuncCallOrArray_t const&)
    ASR::symbol_t* asr_owner_sym = ASR::down_cast<ASR::symbol_t>(current_scope->asr_owner);
AssertFailed: f != nullptr
```
