### ISSUE TITLE
Support c_null_ptr

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1729]
Currently this diff:
```diff
diff --git a/integration_tests/bindc4.f90 b/integration_tests/bindc4.f90
index 4da43f045..77bb9c246 100644
--- a/integration_tests/bindc4.f90
+++ b/integration_tests/bindc4.f90
@@ -1,6 +1,7 @@
 program bindc4
-use iso_c_binding, only: c_associated, c_loc, c_ptr, c_f_pointer
+use iso_c_binding, only: c_associated, c_loc, c_ptr, c_f_pointer, c_null_ptr
 type(c_ptr) :: queries
+type(c_ptr) :: queries2 = c_null_ptr
 integer :: i, j
 integer(2), target :: xv(3, 4), yv(3,4)
 integer :: newshape(2)
@@ -41,4 +42,7 @@ end do
 if (c_associated(queries, c_loc(x(0, 0)))) error stop
 if (.not. c_associated(queries, c_loc(x))) error stop
 if (c_associated(queries, c_loc(y))) error stop
+
+if (.not. c_associated(queries)) error stop
+if (c_associated(queries2)) error stop
 end program
```
Fails with:
```console
$ lfortran bindc4.f90 
semantic error: Only function call assignment is allowed for now
 --> bindc4.f90:4:1
  |
4 | type(c_ptr) :: queries2 = c_null_ptr
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
```

**Comment by certik** [comment]
And another different but related bug:
```diff
--- a/integration_tests/bindc4.f90
+++ b/integration_tests/bindc4.f90
@@ -1,6 +1,7 @@
 program bindc4
-use iso_c_binding, only: c_associated, c_loc, c_ptr, c_f_pointer
+use iso_c_binding, only: c_associated, c_loc, c_ptr, c_f_pointer, c_null_ptr
 type(c_ptr) :: queries
+type(c_ptr) :: queries2
 integer :: i, j
 integer(2), target :: xv(3, 4), yv(3,4)
 integer :: newshape(2)
@@ -11,6 +12,7 @@ newshape(2) = 3
 
 x => xv
 y => yv
+queries2 = c_null_ptr
 
 do i = lbound(x, 1), ubound(x, 1)
     do j = lbound(x, 2), ubound(x, 2)
@@ -41,4 +43,7 @@ end do
 if (c_associated(queries, c_loc(x(0, 0)))) error stop
 if (.not. c_associated(queries, c_loc(x))) error stop
 if (c_associated(queries, c_loc(y))) error stop
+
+if (.not. c_associated(queries)) error stop
+if (c_associated(queries2)) error stop
 end program
```
Gives:
```console
$ lfortran bindc4.f90 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1968
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 868
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 252
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 274
    compiler_options.symtab_only, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 99
    auto res = body_visitor(al, ast, diagnostics, unit, compiler_options,
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2813
    b.requirement_map = requirement_map;
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 133
    visit_ast(*x.m_items[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4768
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4725
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4771
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4368
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1498
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 104
    this->visit_stmt(*m_body[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4813
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4469
    case stmtType::Assign: { v.visit_Assign((const Assign_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1920
    value_type, target_type);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/asr_implicit_cast_rules.h", line 127
    LCOMPILERS_ASSERT(source_type2->type < num_types);
AssertFailed: source_type2->type < 7
```
Let's add a test and fix both.
