### ISSUE TITLE
Assignment to `ArrayItem` from module throws LCOMPILERS_ASSERT failed

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1735]
```fortran
module file_common_block_block_1
    integer :: c(5)
end module

program main
    use file_common_block_block_1
    c(1) = 1
end program
```

> LFortran

```console
% lfortran ./tests/temp.f90 --show-llvm
LCOMPILERS_ASSERT failed: /Users/pgoswami/Desktop/lfortran/src/libasr/codegen/llvm_utils.cpp
function CreateGEP(), line number 25 at 
t->isPointerTy()
zsh: abort      lfortran ./tests/temp3.f90 --show-llvm
```

**Comment by Pranavchiku** [comment]
This is because, the `integer :: c(5)` in module is declared as `@c = global i32 0` in LLVM that is uninitialised

**Comment by certik** [comment]
@czgdp1807 do you know how to fix it? It segflaults in  `cmo_convertor_single_element`.

**Comment by certik** [comment]
Here is the bug:
```fortran
module file_common_block_block_1
    integer :: c(5)
end module

program main
    use file_common_block_block_1
    !c(1) = 1
    !c(2:) = 0
    !print *, c
end program
```
This gives:
```console
$ lfortran --show-llvm a.f90
; ModuleID = 'LFortran'
source_filename = "LFortran"

@c = global i32 0

define i32 @main(i32 %0, i8** %1) {
.entry:
  call void @_lpython_set_argv(i32 %0, i8** %1)
  ret i32 0
}

declare void @_lpython_set_argv(i32, i8**)
```
But it should declare `@c` as an array. That's why it fails later on when we treat it as an array.

**Comment by certik** [comment]
With https://github.com/lfortran/lfortran/pull/1742, we now get an error:
```console
$ lfortran --show-llvm a.f90 --show-stacktrace
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1892
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 807
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 291
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 313
    diagnostics, lm.files.back().in_filename);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 346
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8526
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "../libasr/asr.h", line 4775
  File "../libasr/asr.h", line 4751
  File "../libasr/asr.h", line 4776
  File "../libasr/asr.h", line 4496
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1357
    ASR::symbol_t *mod = x.m_global_scope->get_symbol(item);
  File "../libasr/asr.h", line 4778
  File "../libasr/asr.h", line 4505
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2767
    visit_Variable(*v);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2474
    throw CodeGenError("Arrays are not supported by visit_Variable");
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 86
    { }
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 85
    : d{diag::Diagnostic(msg, diag::Level::Error, diag::Stage::CodeGen)}
code generation error: Arrays are not supported by visit_Variable
```
So that's where the error is and we just need to implement proper array support.

**Comment by czgdp1807** [comment]
Well `c` is declared inside a module and then used inside the main program. The use case supported right now is arrays declared and used inside functions/subroutines and the main program. This is the same thing as `list`, `dict` being declared globally in LPython module. There we use `global_stmts` pass to wrap all such declarations and initialisations of `list`, `dict` inside functions. The same thing should be done here to populate the descriptor of `c`.

**Comment by czgdp1807** [comment]
> we just need to implement proper array support.

Its not as much related to arrays as its related to handling of variables declared inside modules and then used inside main program and functions/subroutines.

**Comment by certik** [comment]
Yes, I thought it is related to the `global_stmts` pass.

**Comment by Pranavchiku** [comment]
Okay, I am not sure what the translated code should look like, can anyone please help me over it!

**Comment by Pranavchiku** [comment]
On looking at https://github.com/lcompilers/lpython/pull/1384#issuecomment-1385938153, we are already having a variable inside a module, and export from it is not supported as mentioned by @czgdp1807. How can we initialize it using a function or subroutine?

**Comment by czgdp1807** [comment]
I will take a look at it tomorrow.

**Comment by czgdp1807** [comment]
So I assume there are two cases here for array variables declared inside a module,

1. Arrays with fixed shape and fixed size (product of all dimension sizes) like, `integer :: c(5, 10)` 
2. Arrays with deferred shape (only possible with allocatable array variables when declared inside a module) like, `integer, allocatable :: c(:, :)`.

Cases like `integer :: c(m, n)` are not possible inside a module because `m` and `n` will be local variables which is not allowed.

So, case 2 is easy, you treat them just like we treat lists in LPython. The descriptor isn't required to be filled at the time of declaration. It will only be filled inside a function/subroutine when `allocate(c(5, 10))` will be called. So nothing to worry about.

For case 1, since the array is of fixed size, you can simply treat as a `llvm::ArrayType`. Physical type of such array will be `FixedSizeArray` (naming is not a concern in this idea). Other options like initialising the descriptor inside a function and stuff doesn't make much sense to me and is very hectic to implement. In fact once we have physical types, arrays of fixed size should always use `llvm::ArrayType`, no need to use a descriptor for such arrays. It will be easy distinguish between a descriptor based array, a simple data pointer based array and `llvm::ArrayType` based array by looking at its physical type. Physical type of descriptor based array can be `XYZDescriptor`, simple data pointer based array can be `DataPointer` and `llvm::ArrayType` based array can be `FixedSizeArray`.

To implement the above idea we need to get started with Physical types and clean up LLVM backend.

**Comment by certik** [comment]
Here is how to get started with the physical types for arrays: https://github.com/lfortran/lfortran/issues/1813

**Comment by harperjf** [comment]
On removing the ! from @certik's #1735 program I get
```
module file_common_block_block_1
    integer :: c(5)
end module

program main
    use file_common_block_block_1
    c(1) = 1
    c(2:) = 0
    print *, c
end program
```
Output from  lfortran 0.56.0 showing the bug seems to be dead:
```
 1    0    0    0    0
```
