### ISSUE TITLE
Get `log(x)` working with C and C++ backends

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1746]
```fortran
program simple
implicit none
real :: A, B
B = 2.0D0
A = log(B) ! It works with sin(B).
print *, A
end program simple
```
Currently in C:
```console
$ lfortran --show-c a.f90  
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1914
    return emit_c(arg_file, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 711
    LCompilers::Result<std::string> cpp = fe.get_c(input, lm, diagnostics, 1);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 456
    return get_c2(*asr.result, diagnostics, default_lower_bound);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 467
    return asr_to_c(al, asr, diagnostics, compiler_options,
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_c.cpp", line 1344
    v.visit_asr((ASR::asr_t &)asr);
  File "../libasr/asr.h", line 4775
  File "../libasr/asr.h", line 4751
  File "../libasr/asr.h", line 4776
  File "../libasr/asr.h", line 4496
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_c.cpp", line 713
    if( ASRUtils::get_body_size(mod) != 0 ) {
  File "../libasr/asr.h", line 4778
  File "../libasr/asr.h", line 4505
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_c.cpp", line 822
    ASR::Function_t *s = ASR::down_cast<ASR::Function_t>(sym);
  File "../libasr/codegen/asr_to_c_cpp.h", line 598
  File "../libasr/asr.h", line 4793
  File "../libasr/asr.h", line 4527
  File "../libasr/codegen/asr_to_c_cpp.h", line 840
  File "../libasr/asr.h", line 4839
  File "../libasr/asr.h", line 4672
  File "../libasr/asr.h", line 4935
LCompilersException: visit_IntrinsicFunctionSqrt() not implemented
```
And C++:
```console
$ lfortran --show-cpp a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1911
    return emit_cpp(arg_file, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 687
    LCompilers::Result<std::string> cpp = fe.get_cpp(input, lm, diagnostics, 1);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 431
    return get_cpp2(*asr.result, diagnostics, default_lower_bound);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 442
    return asr_to_cpp(al, asr, diagnostics, compiler_options,
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_cpp.cpp", line 750
    v.visit_asr((ASR::asr_t &)asr);
  File "../libasr/asr.h", line 4775
  File "../libasr/asr.h", line 4751
  File "../libasr/asr.h", line 4776
  File "../libasr/asr.h", line 4496
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_cpp.cpp", line 457
    ASR::symbol_t *mod = x.m_global_scope->get_symbol(item);
  File "../libasr/asr.h", line 4778
  File "../libasr/asr.h", line 4505
  File "../libasr/codegen/asr_to_c_cpp.h", line 246
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_cpp.cpp", line 367
    this->visit_expr(*v.m_symbolic_value);
  File "../libasr/asr.h", line 4839
  File "../libasr/asr.h", line 4582
  File "../libasr/asr.h", line 4845
LCompilersException: visit_StructTypeConstructor() not implemented
```

**Comment by certik** [comment]
With #1747, it now produces C and C++ code. The C code can be tested using:
```console
$ lfortran --show-c a.f90 > x.c
$ clang -Isrc/libasr/runtime x.c -ferror-limit=1 -Lsrc/runtime -llfortran_runtime -Wl,-rpath -Wl,src/runtime
$ ./a.out
0.693147
$ lfortran a.f90 
6.93147182e-01
```
The last line tests the LLVM backend, the second to last is the C backend.

**Comment by certik** [comment]
With #1747 everything now works: `lfortran --backend=c a.f90`. C++ also works.
