### ISSUE TITLE
[SciPy][Linalg]: segmentation fault on `external`

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1753]
```fortran

        subroutine iddr_rsvd(matvect)

        implicit none
        external matvect

        end
```
> LFortran
```console
lfortran --no-warnings --fixed-form --implicit-typing --implicit-interface --show-asr /Users/pgoswami/repos/scipy/scipy/linalg/src/id_dist/src/iddr_rsvd.f
zsh: segmentation fault  lfortran --no-warnings --fixed-form --implicit-typing --implicit-interface
```

**Comment by Pranavchiku** [comment]
```console
$ lfortran ./tests/temp.f90 --implicit-typing --implicit-interface
Traceback (most recent call last):
  Binary file "/home/pranavchiku/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 1975, in ??
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 874, in ??
    result = fe.get_asr2(input, lm, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 252, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 274, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/home/pranavchiku/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 90, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    if (!asr_verify(*tu, true, diagnostics)) {
  File "/home/pranavchiku/lfortran/src/libasr/asr_verify.cpp", line 1030, in LCompilers::asr_verify(LCompilers::ASR::TranslationUnit_t const&, bool, LCompilers::diag::Diagnostics&)
    v.visit_TranslationUnit(unit);
  File "/home/pranavchiku/lfortran/src/libasr/asr_verify.cpp", line 109, in LCompilers::ASR::VerifyVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4777, in LCompilers::ASR::BaseVisitor<LCompilers::ASR::VerifyVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4513, in ??
    case symbolType::Function: { v.visit_Function((const Function_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/asr_verify.cpp", line 426, in LCompilers::ASR::VerifyVisitor::visit_Function(LCompilers::ASR::Function_t const&)
    this->visit_symbol(*a.second);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4777, in LCompilers::ASR::BaseVisitor<LCompilers::ASR::VerifyVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4520, in ??
    case symbolType::Variable: { v.visit_Variable((const Variable_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/asr_verify.cpp", line 637, in LCompilers::ASR::VerifyVisitor::visit_Variable(LCompilers::ASR::Variable_t const&)
    visit_ttype(*x.m_type);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4937, in LCompilers::ASR::BaseVisitor<LCompilers::ASR::VerifyVisitor>::visit_ttype(LCompilers::ASR::ttype_t const&)
    void visit_ttype(const ttype_t &b) { visit_ttype_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4687, in ??
    LCOMPILERS_ASSERT(x.base.type == asrType::ttype)
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __GI___sigaction()
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by Pranavchiku** [comment]
#1776

**Comment by Pranavchiku** [comment]
@certik @czgdp1807 what can be the type of `external matvect` as implicit none is defined earlier?

**Comment by Pranavchiku** [comment]
I have an implementation ready, few tests are failing will soon open a PR.

**Comment by certik** [comment]
Let's fix this:
```
subroutine g(matvect)
external matvec
call f(matvec)
print *, matvec(5, 4)
end
```
Here we know that implicit typing gives matvec an integer return value, and the call `matvec(5, 4)` gives it two integer arguments. so we know the full interface and that's how we should declare it.

Then let's fix this one:
```
subroutine g(matvect)
external matvec
call f(matvec)
print *, matvec(5, 4)
end
```

**Comment by certik** [comment]
And finally:
```
subroutine g(matvect)
call f(matvec)
end
```
Which already seems to work, but let's make sure we have a solid test for this.
