### ISSUE TITLE
LCompilersException: LLVMUtils::deepcopy isn't implemented for Allocatable[str]

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1859]
With https://github.com/lfortran/lfortran/pull/1858, I am getting a different error in fastGPT:
```console
$ lfortran --show-llvm main.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2018
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 806
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 290
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 312
    diagnostics, lm.files.back().in_filename);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 345
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8612
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "../libasr/asr.h", line 4890
  File "../libasr/asr.h", line 4866
  File "../libasr/asr.h", line 4891
  File "../libasr/asr.h", line 4605
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1368
    ASR::symbol_t *mod = x.m_global_scope->get_symbol(item);
  File "../libasr/asr.h", line 4893
  File "../libasr/asr.h", line 4614
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2887
    finish_module_init_function_prototype(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4308
    ASR::Function_t *s = ASR::down_cast<ASR::Function_t>(item.second);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3915
    visit_procedures(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4261
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4910
  File "../libasr/asr.h", line 4666
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5616
    }, [=]() {
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 324
    start_new_block(loopbody); {
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5618
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4910
  File "../libasr/asr.h", line 4638
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4859
    asr_target_type, module.get(), name2memidx);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 365
    module, name2memidx);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 378
    throw LCompilersException("LLVMUtils::deepcopy isn't implemented for " +
LCompilersException: LLVMUtils::deepcopy isn't implemented for Allocatable[str]
```

**Comment by certik** [comment]
@czgdp1807 is this the right fix: https://github.com/lfortran/lfortran/pull/1860/commits/60b69d580b855f8138c7f17a857abe0fd1aabe1e ?
