### ISSUE TITLE
Array pointer issues

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1874]
Here is a minimal reproducible example:
```fortran
program array_pointer
implicit none
type :: model_t
    integer, allocatable :: decoder_idx(:)
end type
type(model_t) :: m
allocate(m%decoder_idx(10))
m%decoder_idx(:) = 0        ! Pointer array issue here
m%decoder_idx(5) = 5
call decode(m%decoder_idx)  ! Pointer array issue here

contains

    subroutine decode(idx)
    integer, intent(in) :: idx(:)
    if (idx(4) /= 0) error stop
    if (idx(5) /= 5) error stop
    end subroutine

end program
```
Gives:
```console
$ lfortran a.f90 
Assertion failed: (Ty && "Invalid GetElementPtrInst indices for type!"), function checkGEPType, file Instructions.h, line 897.
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2097
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 902
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 345
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8595
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "../libasr/asr.h", line 4890
  File "../libasr/asr.h", line 4866
  File "../libasr/asr.h", line 4891
  File "../libasr/asr.h", line 4605
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1382
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 4893
  File "../libasr/asr.h", line 4614
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2936
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4910
  File "../libasr/asr.h", line 4638
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4949
    this->visit_expr_wrapper(x.m_value, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5087
    this->visit_expr(*x);
  File "../libasr/asr.h", line 4956
  File "../libasr/asr.h", line 4703
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5974
    handle_SU_IntegerBinOp(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5904
    this->visit_expr_wrapper(x.m_left, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5087
    this->visit_expr(*x);
  File "../libasr/asr.h", line 4956
  File "../libasr/asr.h", line 4749
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8509
    llvm::Value* dim_des_val = arr_descr->get_pointer_to_dimension_descriptor_array(llvm_arg1);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 201
    llvm::Value* dim_des_arr_ptr = llvm_utils->create_gep(arr, 2);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 125
    return LLVM::CreateGEP(*builder, ds, idx_vec);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 27
    return builder.CreateGEP(t2, x, idx);
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/IRBuilder.h", line 1773
    return Insert(GetElementPtrInst::Create(Ty, Ptr, IdxList), Name);
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 943
    NameStr, InsertBefore);
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1151
    }
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1143
    : Instruction(getGEPReturnType(PointeeType, Ptr, IdxList), GetElementPtr,
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1074
    Type *PtrTy = PointerType::get(checkGEPType(getIndexedType(ElTy, IdxList)),
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 897
    assert(Ty && "Invalid GetElementPtrInst indices for type!");
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18024972b
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18024a313
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x18030ceaf
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Abort: Signal SIGABRT (abort) received

zsh: abort      lfortran a.f90
```

**Comment by certik** [comment]
One can debug it using:
```diff
--- a/src/libasr/codegen/asr_to_llvm.cpp
+++ b/src/libasr/codegen/asr_to_llvm.cpp
@@ -8506,6 +8506,13 @@ public:
         visit_expr_wrapper(x.m_v);
         ptr_loads = ptr_loads_copy;
         llvm::Value* llvm_arg1 = tmp;
+        bool is_pointer_array = llvm_arg1->getType()->getContainedType(0)->isPointerTy();
+        if (is_pointer_array) {
+            throw CodeGenError("Pointer Array", x.m_v->base.loc);
+            tmp = llvm::ConstantInt::get(context, llvm::APInt(4 * 8, 1));
+            return;
+        }
+
         llvm::Value* dim_des_val = arr_descr->get_pointer_to_dimension_descriptor_array(llvm_arg1);
         visit_expr_wrapper(x.m_dim, true);
         llvm::Value* dim_val = tmp;
```
Which gives:
```console
$ lfortran a.f90 
code generation error: Pointer Array
 --> a.f90:8:1
  |
8 | m%decoder_idx(:) = 0        ! Pointer array issue here
  | ^^^^^^^^^^^^^^^^ 
```

**Comment by certik** [comment]
@czgdp1807 This issue is related, so I also assigned it to you.

**Comment by certik** [comment]
This issue was fixed by https://github.com/lfortran/lfortran/pull/1875, test added.
