### ISSUE TITLE
Kind parameter specified with a named constant fails

### ISSUE THREAD

**Issue by btrettel** [lfortran/lfortran#1921]
Minimum working example:

    program test

    implicit none
    integer, parameter :: RP = selected_real_kind(15, 307)
    real(kind=RP), parameter :: PI = 3.141592653589793_RP
    write(unit=*, fmt=*) PI

    end program test

Command line output:

    lfortran -c -o kind1.o kind1.f90 
    semantic error: Variable 'RP' not declared
     --> kind1.f90:5:34
      |
    5 | real(kind=RP), parameter :: PI = 3.141592653589793_RP
      |                                  ^^^^^^^^^^^^^^^^^^^^ 

    Note: if any of the above error or warning messages are not clear or are lacking
    context please report it to us (we consider that a bug that must be fixed).

Clearly LFortran is recognizing `RP` the first time it appears in the line, but not the second.

Replacing the named constant `RP` with a literal integer works.

Version:

    lfortran --version
    LFortran version: 0.19.0
    Platform: Linux
    Default target: x86_64-pc-linux-gnu

I also tried with the latest development tarball with the same result:

    /home/ben/ramdisk/lfortran-0.19.0-121-g917611d90/inst/bin/lfortran --version
    LFortran version: 0.19.0-121-g917611d90
    Platform: Linux
    Default target: x86_64-pc-linux-gnu

**Comment by certik** [comment]
Thanks!

With the latest LFortran I even get this:
```
$ lfortran a.f90 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2114
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 888
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 251
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 273
    compiler_options.symtab_only, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 84
    auto res = symbol_table_visitor(al, ast, diagnostics, symbol_table,
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 2503
    SymbolTableVisitor v(al, symbol_table, diagnostics, compiler_options, implicit_mapping, common_variables_hash, external_procedures_mapping);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 122
    visit_ast(*x.m_items[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4768
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4725
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4771
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4368
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 505
    visit_unit_decl2(*x.m_decl[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4782
    void visit_unit_decl2(const unit_decl2_t &b) { visit_unit_decl2_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4395
    case unit_decl2Type::Declaration: { v.visit_Declaration((const Declaration_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1108
    visit_DeclarationUtil(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 2090
    this->visit_expr(*s.m_initializer);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4864
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4531
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4893
    tmp = create_FunctionCallWithASTNode(x, v, args);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 3294
    return create_Function(x.base.base.loc, args, v);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 3253
    ASRUtils::set_absent_optional_arguments_to_null(args, func, al);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_utils.h", line 1951
    LCOMPILERS_ASSERT(args.size() == (func->n_args - offset));
AssertFailed: args.size() == (func->n_args - offset)
```

It's due to the `selected_real_kind`. With this:
```fortran
program test

implicit none
integer, parameter :: RP = kind(0.d0)
real(kind=RP), parameter :: PI = 3.141592653589793_RP
write(unit=*, fmt=*) PI

end program test
```
I get:
```console
$ lfortran a.f90
semantic error: Variable 'RP' not declared
 --> a.f90:5:34
  |
5 | real(kind=RP), parameter :: PI = 3.141592653589793_RP
  |                                  ^^^^^^^^^^^^^^^^^^^^ 
```
And finally, with using lowercase `rp` it works:
```fortran
program test

implicit none
integer, parameter :: rp = kind(0.d0)
real(kind=rp), parameter :: PI = 3.141592653589793_rp
write(unit=*, fmt=*) PI

end program test
```
I get:
```console
$ lfortran a.f90 
3.14159265358979312e+00
```
So there are two bugs here:
* Uppercase RP vs lowercase rp
* selected_real_kind

Thanks for the report, we'll fix it.
