### ISSUE TITLE
fastGPT: ASR verify: Old physical type conflicts with the physical type of argument 1 0

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1932]
Using the lf3 branch in fastGPT:

```
$ lfortran --show-llvm main.f90 
ASR verify pass error: ASR verify: Old physical type conflicts with the physical type of argument 1 0
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2035
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 821
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 290
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 312
    diagnostics, lm.files.back().in_filename);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 345
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8983
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 281
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 155
    + passes[i]);
LCompilersException: Verify failed in the pass: array_op
```

We have to create a minimal example and fix this.

**Comment by czgdp1807** [comment]
I can't see any `lf3` branch in https://github.com/certik/fastGPT. Could you please push it to your fork?

**Comment by certik** [comment]
Sure, here it is: https://github.com/certik/fastGPT/tree/lf3, in there do `lfortran main.f90`.
