### ISSUE TITLE
[SciPy]: asr_to_llvm: module failed verification. Error: Operand is null

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#1977]
```fortran
      subroutine dqc25f()
      external f
      call dqk15w(f)
      end
```

> LFortran

```console
% lfortran  /Users/hkalani/Desktop/scipy/scipy/integrate/quadpack/dqc25f.f --fixed-form --implicit-typing --implicit-interface --implicit-argument-casting --show-llvm
; ModuleID = 'LFortran'
source_filename = "LFortran"

define void @dqc25f() {
.entry:
  call void @dqk15w(<null operand!>)
  br label %return

return:                                           ; preds = %.entry
  ret void
}

declare void @dqk15w(float ()*)

declare float @f()
code generation error: asr_to_llvm: module failed verification. Error:
Operand is null
  call void @dqk15w(<null operand!>)
```

**Comment by HarshitaKalani** [comment]
If I get it right, this issue is because f is null and it is used as a function parameter. To resolve it, we need to make sure that function parameters should never be null. Is it?

**Comment by certik** [comment]
I just pushed in https://github.com/lfortran/lfortran/pull/1982/commits/3323cdc01a0a45bb8415480dc7017bbfb72432fb, and the bug is actually that the function "f" (and its hash "h") is not even present in the `llvm_symtab_fn_arg` hashtable:
```
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6998
    LCOMPILERS_ASSERT(llvm_symtab_fn_arg.find(h) != llvm_symtab_fn_arg.end());
AssertFailed: llvm_symtab_fn_arg.find(h) != llvm_symtab_fn_arg.end()
```
So we need to ensure it gets created there in the first place.

**Comment by Pranavchiku** [comment]
Okay, while creating external function we specify `ASR::deftypeType::Interface` [here](https://github.com/lfortran/lfortran/blob/main/src/lfortran/semantics/ast_common_visitor.h#L1589) and then when you see `visit_Function` in `asr_to_llvm` [here](https://github.com/lfortran/lfortran/blob/main/src/libasr/codegen/asr_to_llvm.cpp#L3186) it exits without populating `llvm_symtab_fn_arg`.

That is what the error is showing now, so you can apply the following diff and it will work
```diff
diff --git a/src/lfortran/semantics/ast_common_visitor.h b/src/lfortran/semantics/ast_common_visitor.h
index a8ec66b30..a4b40e220 100644
--- a/src/lfortran/semantics/ast_common_visitor.h
+++ b/src/lfortran/semantics/ast_common_visitor.h
@@ -1586,7 +1586,7 @@ public:
                 /* a_body */ nullptr,
                 /* n_body */ 0,
                 /* a_return_var */ to_return,
-                ASR::abiType::BindC, ASR::accessType::Public, ASR::deftypeType::Interface,
+                ASR::abiType::BindC, ASR::accessType::Public, ASR::deftypeType::Implementation,
                 nullptr, false, false, false, false, false, nullptr, 0, nullptr, 0,
                 false, false, false);
             parent_scope->add_or_overwrite_symbol(sym, ASR::down_cast<ASR::symbol_t>(tmp));
```

@HarshitaKalani you can go ahead apply this diff and complete the issue, make sure to register test and update test references.

**Comment by HarshitaKalani** [comment]
@certik I changed f from Interface to Implementation following this actually

**Comment by certik** [comment]
I see. @Pranavchiku it seems it's needed to change Interface to Implementation, but in here https://github.com/lfortran/lfortran/pull/1988#discussion_r1264492604 it should stay Interface. Do you know when it should be changed?

**Comment by Pranavchiku** [comment]
Looks like, if we donot have implementation of external function inside ASR then will have to keep it Implementation else Interface will work. This might work by simpling peeforming `current_scope->resolve_symbol(sym_name)`, if it's output is nullptr, make it Implementation else Interface.

**Comment by Pranavchiku** [comment]
I was working on this, and I made progress but when I tried to run a complex case, I realized the current approach might not work. 
For the below-given case, we can directly apply https://github.com/lfortran/lfortran/issues/1977#issuecomment-1644940188 
```fortran
subroutine dqc25f()
   external f
   call dqk15w(f)
end
```
but things become slightly more complex when we face 
```fortran
function f(x) result (r)
   real r, x
   r = x
end function

subroutine dqk15w(f)
   interface
      function f(x) result (r)
         real r, x
      end function
   end interface
   real r
   r = f(2.0)
   print *, r
end subroutine

subroutine dqc25f()
   external f
   call dqk15w(f)
end

program main
   call dqc25f()
end program
```

For this case, I realized that the subroutine call `call dqk15w(f)` contains an interface `dqk15w`. Because of this we do not populate the arguments of this call and hence it throws an Assert Failure stating `llvm_symtab_fn_arg.find(h) != llvm_symtab_fn_arg.end()`. 

I feel we will somehow need to let the compiler know that `dqk15w` is an external function and point to the implementation.

**Comment by certik** [comment]
When visiting the function `dqc25f` in the body visitor, check if there are any external symbols in it. If so, resolve them fully, that is, find `f` in the global symbol table, if available, update the interface stub to be conforming. If it is not available, then don't do anything, since the function `f` will be linked in a separate compilation, in which case it's fine if the type doesn't match.

**Comment by certik** [comment]
The current status of the example above is:
```console
$ lfortran a.f90 --show-llvm --implicit-interface
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2224
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 828
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 292
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 314
    diagnostics, lm.files.back().in_filename);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 358
    = asr_to_llvm(asr, diagnostics,
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9214
    pass_manager.apply_passes(al, &asr, co.po, diagnostics, lm);
  File "../libasr/asr.h", line 5057
  File "../libasr/asr.h", line 5033
  File "../libasr/asr.h", line 5058
  File "../libasr/asr.h", line 4765
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 938
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5060
  File "../libasr/asr.h", line 4775
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3673
    visit_procedures(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3870
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5077
  File "../libasr/asr.h", line 4825
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8388
    std::vector<llvm::Value *> args2 = convert_call_args(x, is_method);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7870
    LCOMPILERS_ASSERT(llvm_symtab_fn_arg.find(h) != llvm_symtab_fn_arg.end());
AssertFailed: llvm_symtab_fn_arg.find(h) != llvm_symtab_fn_arg.end()
```

**Comment by certik** [comment]
@Pranavchiku knows how to fix this, so I assigned it to him.

**Comment by Pranavchiku** [comment]
```diff
diff --git a/src/lfortran/semantics/ast_common_visitor.h b/src/lfortran/semantics/ast_common_visitor.h
index 517471f66..13207deae 100644
--- a/src/lfortran/semantics/ast_common_visitor.h
+++ b/src/lfortran/semantics/ast_common_visitor.h
@@ -4981,7 +4981,8 @@ public:
         } else {
             v = current_scope->resolve_symbol(var_name);
         }
-        if (!v) {
+        if (!v || (v && is_external_procedure)) {
+            ASR::symbol_t* external_sym = is_external_procedure ? v : nullptr;
             if (var_name == "float" || var_name == "dble") {
                 Vec<ASR::call_arg_t> args;
                 visit_expr_list(x.m_args, x.n_args, args);
@@ -4998,7 +4999,7 @@ public:
             if( !is_function ) {
                 return;
             }
-            if (compiler_options.implicit_interface && is_function && !v) {
+            if (compiler_options.implicit_interface && is_function && ( !v || (v && is_external_procedure))) {
                 // Function Call is not defined in this case.
                 // We need to create an interface and add the Function into
                 // the symbol table.
@@ -5007,6 +5008,15 @@ public:
                 create_implicit_interface_function(x, var_name, true, type);
                 v = current_scope->resolve_symbol(var_name);
                 LCOMPILERS_ASSERT(v!=nullptr);
+                // check if external sym is updated, or: say if signature of external_sym and original_sym are different
+                if (v && external_sym && is_external_procedure && ASRUtils::is_external_sym_changed(v, external_sym)) {
+                    changed_external_function_symbol[ASRUtils::symbol_name(v)] = v;
+                }
+                // remove from external_procedures_mapping
+                if (v && is_external_procedure) {
+                    erase_from_external_mapping(var_name);
+                }
+                ASRUtils::update_call_args(al, current_scope, compiler_options.implicit_interface, changed_external_function_symbol);
             }
         }
         // if v is a function which has null pointer return type, give error
diff --git a/src/libasr/asr_utils.cpp b/src/libasr/asr_utils.cpp
index 794727cfc..f7eee9fa5 100644
--- a/src/libasr/asr_utils.cpp
+++ b/src/libasr/asr_utils.cpp
@@ -211,6 +211,26 @@ void update_call_args(Allocator &al, SymbolTable *current_scope, bool implicit_i
             }
         }
 
+        void visit_FunctionCall(const ASR::FunctionCall_t& x) {
+            ASR::FunctionCall_t* func_call = (ASR::FunctionCall_t*)(&x);
+            for (size_t j = 0; j < func_call->n_args; j++) {
+                ASR::call_arg_t arg = func_call->m_args[j];
+                ASR::expr_t* arg_expr = arg.m_value;
+                if (ASR::is_a<ASR::Var_t>(*arg_expr)) {
+                    ASR::Var_t* arg_var = ASR::down_cast<ASR::Var_t>(arg_expr);
+                    ASR::symbol_t* arg_sym = arg_var->m_v;
+                    ASR::symbol_t* arg_sym_underlying = ASRUtils::symbol_get_past_external(arg_sym);
+                    ASR::symbol_t* sym = fetch_sym(arg_sym_underlying);
+                    if (sym != arg_sym) {
+                        ASR::expr_t** current_expr_copy = current_expr;
+                        current_expr = const_cast<ASR::expr_t**>(&(func_call->m_args[j].m_value));
+                        this->call_replacer_(sym);
+                        current_expr = current_expr_copy;
+                    }
+                }
+            }
+        }
+
         void visit_Function(const ASR::Function_t& x) {
             ASR::Function_t* func = (ASR::Function_t*)(&x);
             scope = func->m_symtab;
```


With this diff, we have latest interface is used everywhere, still it throws same error.
