### ISSUE TITLE
transform_optional_argument_functions: LCOMPILERS_ASSERT(i < x.n_args)

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2010]
in fastgpt:
```
[ 58%] Building Fortran object CMakeFiles/chat.dir/chat.f90.o
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2141
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 917
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 345
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8171
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 281
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 150
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/transform_optional_argument_functions.cpp", line 401
    ReplaceSubroutineCallsWithOptionalArgumentsVisitor y(al);
  File "../libasr/asr.h", line 39639
  File "../libasr/asr.h", line 5025
  File "../libasr/asr.h", line 4741
  File "../libasr/pass/pass_utils.h", line 175
  File "../libasr/pass/pass_utils.h", line 150
  File "../libasr/asr.h", line 5042
  File "../libasr/asr.h", line 4791
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/transform_optional_argument_functions.cpp", line 384
    if( !fill_new_args(new_args, al, x, current_scope) ) {
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/transform_optional_argument_functions.cpp", line 275
    LCOMPILERS_ASSERT(i < x.n_args);
AssertFailed: i < x.n_args
```

**Comment by certik** [comment]
Duplicate of https://github.com/lfortran/lfortran/issues/2018, which has more information how to workaround the bug.
