### ISSUE TITLE
Using a local structure with compile time array lengths

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2059]
```
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2141
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 917
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 345
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8230
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "../libasr/asr.h", line 5024
  File "../libasr/asr.h", line 5000
  File "../libasr/asr.h", line 5025
  File "../libasr/asr.h", line 4734
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 869
    ASR::symbol_t *mod = x.m_global_scope->get_symbol(item);
  File "../libasr/asr.h", line 5027
  File "../libasr/asr.h", line 4743
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2619
    finish_module_init_function_prototype(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3418
    ASR::Function_t *s = ASR::down_cast<ASR::Function_t>(item.second);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3190
    visit_procedures(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3371
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5044
  File "../libasr/asr.h", line 4795
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4964
    }, [=]() {
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 277
    start_new_block(loopbody); {
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4966
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5044
  File "../libasr/asr.h", line 4767
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4164
    this->visit_expr_wrapper(x.m_value, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4457
    this->visit_expr(*x);
  File "../libasr/asr.h", line 5090
  File "../libasr/asr.h", line 4879
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2032
    LCOMPILERS_ASSERT(ASR::is_a<ASR::Character_t>(*ASRUtils::expr_type(x.m_v)) &&
AssertFailed: ASR::is_a<ASR::Character_t>(*ASRUtils::expr_type(x.m_v)) && n_dims == 0
```

**Comment by certik** [comment]
Actually, this causes it:
```
t%pmlp_fc_w = mlp_fc_w(:,:,i)
```
