### ISSUE TITLE
[SciPy][Specfun]: `scipy/special/tests/test_basic.py::TestKelvin::test_keip_zeros ` Halts on execution 

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#2117]
Responsible Subroutine: `scipy/special/specfun`

```fortran
        SUBROUTINE KLVNZO(NT,KD,ZO)
C
C       ====================================================
C       Purpose: Compute the zeros of Kelvin functions
C       Input :  NT  --- Total number of zeros
C                KD  --- Function code
C                KD=1 to 8 for ber x, bei x, ker x, kei x,
C                          ber'x, bei'x, ker'x and kei'x,
C                          respectively.
C       Output:  ZO(M) --- the M-th zero of Kelvin function
C                          for code KD
C       Routine called:
C                KLVNA for computing Kelvin functions and
C                their derivatives
C       ====================================================
C
```

Test logs:

```console
$ python dev.py test -t scipy.special.tests.test_basic -v
💻  ninja -C /home/pranavchiku/scipy/build -j4
ninja: Entering directory `/home/pranavchiku/scipy/build'
[4/4] Generating scipy/generate-version with a custom command
Build OK
💻  meson install -C build --only-changed
Installing, see meson-install.log...
Installation OK
SciPy from development installed path at: /home/pranavchiku/scipy/build-install/lib/python3.10/site-packages
Running tests for scipy version:1.12.0.dev0+1345.9b3bbc1, installed at:/home/pranavchiku/scipy/build-install/lib/python3.10/site-packages/scipy
============================================================================== test session starts ==============================================================================
platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0 -- /home/pranavchiku/mambaforge/envs/scipy-dev/bin/python
cachedir: .pytest_cache
rootdir: /home/pranavchiku/scipy
configfile: pytest.ini
plugins: xdist-3.3.1, timeout-2.1.0, cov-4.1.0
collected 1303 items / 1 deselected / 1302 selected                                                                                                                             
.......
scipy/special/tests/test_basic.py::TestKelvin::test_kei_zeros PASSED                                                                                                      [ 16%]
scipy/special/tests/test_basic.py::TestKelvin::test_keip_zeros 
```

Reproducible code:

```fortran
subroutine klvnzo_(nt,kd)
   implicit double precision (a-h,o-z)
   dimension zo(nt),rt0(8)
   rt0(1)=2.84891
   rt0(2)=5.02622
   rt0(3)=1.71854
   rt0(4)=3.91467
   rt0(5)=6.03871
   rt0(6)=3.77268
   rt0(7)=2.66584
   rt0(8)=4.93181
   rt=rt0(kd)
   do 15 m=1,nt
10    call klvna(rt,ber,bei,ger,gei,der,dei,her,hei)
      if (kd.eq.1) then
         rt=rt-ber/der
      else if (kd.eq.2) then
         rt=rt-bei/dei
      else if (kd.eq.3) then
         rt=rt-ger/her
      else if (kd.eq.4) then
         rt=rt-gei/hei
      else if (kd.eq.5) then
         ddr=-bei-der/rt
         rt=rt-der/ddr
      else if (kd.eq.6) then
         ddi=ber-dei/rt
         rt=rt-dei/ddi
      else if (kd.eq.7) then
         gdr=-gei-her/rt
         rt=rt-her/gdr
      else
         gdi=ger-hei/rt
         rt=rt-hei/gdi
      endif
      if (dabs(rt-rt0(kd)).gt.5.0d-10) then
         rt0(kd)=rt
         go to 10
      endif
      zo(m)=rt
15 rt=rt+4.44d0
   return
end

program main
    call klvnzo_(5,8)
end program
```

> LFortran

```console
$ lfortran a.f90 --implicit-typing --implicit-interface --implicit-argument-casting
^C
```

**Comment by Pranavchiku** [comment]
Minimal code to reproduce

```fortran
subroutine klvnzo_(nt,kd)
   implicit double precision (a-h,o-z)
   dimension zo(nt),rt0(8)
   call klvna(rt)
   return
end

program main
   call klvnzo_(5,8)
end program
```

The trouble here is, `call klvna(rt)` here, we have `klvna` as an implicit interface, which contains `rt` as type `r32` ideally it should be `r64`.

**Comment by Pranavchiku** [comment]
The above code is fixed by #2118, the actual error can be reproduced using the below given code
```fortran
subroutine klvna(x, hei)
   implicit double precision (a-h,o-z)
   hei=dlog(x)
   return
end


subroutine klvnzo_(nt,kd)
   implicit double precision (a-h,o-z)
   dimension zo(nt),rt0(8)
   do 15 m=1,nt
10    call klvna(rt, hei)
      rt=rt-hei
      if (dabs(rt-rt0(kd)).gt.5.0d-10) then
         go to 10
      endif
15 rt=rt+4.44d0

   return
end

program main
   call klvnzo_(5,8)
end program
```

**Comment by Pranavchiku** [comment]
Ahh got it, we are losing precision and hence it turns into infinite loop, applying the following diff makes it work.
```diff
      -if (dabs(rt-rt0(kd)).gt.5.0d-10)
      +if (dabs(rt-rt0(kd)).gt.5.0d-8)
```

**Comment by HarshitaKalani** [comment]
```console
(lf) harshita@harshita-linux:~/scipy$ python dev.py test -t scipy.special.tests.test_basic -v 
💻  ninja -C /home/harshita/scipy/build -j4
ninja: Entering directory `/home/harshita/scipy/build'
[4/4] Generating scipy/generate-version with a custom command
Build OK
Task Error - build => PythonAction Error
╭─────────────────────────────────────────── build ───────────────────────────────────────────╮
│ Traceback (most recent call last):                                                          │
│   File "/home/harshita/miniconda3/envs/lf/lib/python3.11/site-packages/doit/action.py",     │
│ line 461, in execute                                                                        │
│     returned_value = self.py_callable(*self.args, **kwargs)                                 │
│                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                 │
│   File "/home/harshita/scipy/dev.py", line 667, in run                                      │
│     cls.install_project(dirs, args)                                                         │
│   File "/home/harshita/scipy/dev.py", line 532, in install_project                          │
│     raise RuntimeError("Can't install in non-empty directory: "                             │
│ RuntimeError: Can't install in non-empty directory: '/home/harshita/scipy/build-install'    │
│                                                                                             │
╰──────────────────────────────────── PythonAction Error ─────────────────────────────────────╯
```
I'm getting this while trying to reproduce the issue. Please suggest.

**Comment by HarshitaKalani** [comment]
On running this:
```
subroutine klvnzo_(nt,kd)
   implicit double precision (a-h,o-z)
   dimension zo(nt),rt0(8)
   call klvna(rt)
   return
end

program main
   call klvnzo_(5,8)
end program
```
I get
```console
(lf) harshita@harshita-linux:~/Desktop/lfortran$ lfortran a.f90 --implicit-typing
semantic error: Function 'klvna' not found or not implemented yet (if it is intrinsic)
 --> a.f90:4:4
  |
4 |    call klvna(rt)
  |    ^^^^^^^^^^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
(lf) harshita@harshita-linux:~/Desktop/lfortran$ lfortran a.f90 --implicit-typing --implicit-interface --implicit-argument-casting
/usr/bin/ld: a.out.tmp.o: in function `klvnzo_':
LFortran:(.text+0x24): undefined reference to `klvna'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
The command 'clang -o a.out a.out.tmp.o  -L"/home/harshita/Desktop/lfortran/src/bin/../runtime" -Wl,-rpath,"/home/harshita/Desktop/lfortran/src/bin/../runtime" -llfortran_runtime -lm' failed.
```

**Comment by Pranavchiku** [comment]
This happens because the linker is not able to find an implementation for `klvna`, this is expected behavior ( you may check with GFortran ).

**Comment by Pranavchiku** [comment]
@HarshitaKalani this issue can be reproduced with https://github.com/lfortran/lfortran/issues/2117#issuecomment-1670833875

**Comment by Pranavchiku** [comment]
I am trying to debug this, but it feels as if divergence starts occurring from 6th decimal point and it keeps populating, 

> LFortran

```console
% lfortran a.f90 --implicit-typing --no-warnings
hei here =  0.00000000000000000e+00
2 hei here =  1.13450977192287965e+01
r =  2.46590499999999979e+00
gs =  1.83333333333333326e+00
3 hei here =  1.13450977192287965e+01
r*gs =  -1.39297042185923150e+01
4 hei here =  -2.58460649936351849e+00
r =  -7.59802048286853537e+00
gs =  2.28333333333333321e+00
3 hei here =  -2.58460649936351849e+00
r*gs =  2.67278422808877592e+00
4 hei here =  8.81777287252574205e-02
r =  1.17056243565931806e+00
gs =  2.59285714285714253e+00
3 hei here =  8.81777287252574205e-02
r*gs =  -8.90651886655955544e-02
4 hei here =  -8.87459940338133912e-04
r =  -3.43502105046374073e-02
gs =  2.82896825396825369e+00
3 hei here =  -8.87459940338133912e-04
r*gs =  8.91132572439799872e-04
4 hei here =  3.67263210166595983e-06
....
```

> GFortran
```console
% gfortran a.f90 && ./a.out
 hei here =    0.0000000000000000     
 2 hei here =    11.345096691757769     
 r =    2.4659049510955811     
 gs =    1.8333333333333333     
 3 hei here =    11.345096691757769     
 r*gs =   -13.929702837306214     
 4 hei here =   -2.5846061455484453     
 r =   -7.5980197294397538     
 gs =    2.2833333333333332     
 3 hei here =   -2.5846061455484453     
 r*gs =    2.6727837510231409     
 4 hei here =    8.8177605474695664E-002
 r =    1.1705622267254632     
 gs =    2.5928571428571425     
 3 hei here =    8.8177605474695664E-002
 r*gs =   -8.9065165702890289E-002
 4 hei here =   -8.8756022819462543E-004
 r =   -3.4350201648497634E-002
 gs =    2.8289682539682537     
 3 hei here =   -8.8756022819462543E-004
 r*gs =    8.9113227199621927E-004
 4 hei here =    3.5720438015938343E-006
....
```

**Comment by certik** [comment]
You have to find the first line that introduces an error at the 1e-6 level. This error will then propagate, but we don't care about that.

We need to find what is causing it in the first place.

**Comment by Pranavchiku** [comment]
```fortran
subroutine klvnzo_()
implicit double precision (a-h,o-z)
rt=4.93181
print *, "rt = ", rt
return
end

program main
   call klvnzo_()
end program
```

> LFortran

```console
% lfortran b.f90 --implicit-typing --no-warnings
rt =  4.93180999999999958e+00
```

> GFortran

```console
% gfortran b.f90 && ./a.out
 rt =    4.9318099021911621     
```

**Comment by Pranavchiku** [comment]
I feel output in LFortran is more accurate than GFortran.

**Comment by certik** [comment]
Ok, so the code here has the typical single/double precision corruption in Fortran: https://www.fortran90.org/src/gotchas.html#floating-point-numbers.

Does the SciPy code actually contain line like this? If so, it's a bug in SciPy. To fix it, make it:
```
subroutine klvnzo_()
implicit double precision (a-h,o-z)
rt=4.93181d0
print *, "rt = ", rt
return
end

program main
   call klvnzo_()
end program
```

**Comment by Pranavchiku** [comment]
In scipy it is just `rt=4.93181`. Okay, sure, I will update it :)

**Comment by Pranavchiku** [comment]
```diff
% git diff scipy/special/specfun/specfun.f    
diff --git a/scipy/special/specfun/specfun.f b/scipy/special/specfun/specfun.f
index fb7848f91..e99728985 100644
--- a/scipy/special/specfun/specfun.f
+++ b/scipy/special/specfun/specfun.f
@@ -9185,7 +9185,7 @@ C
 60            CONTINUE
 65         R=-0.25D0*X*X2
            GS=1.5D0
-           HER=1.5D0*R-BER/X-(DLOG(X/2.D0)+EL)*DER+0.25*PI*DEI
+           HER=1.5D0*R-BER/X-(DLOG(X/2.D0)+EL)*DER+0.25d0*PI*DEI
            DO 70 M=1,60
               R=-0.25D0*R/M/(M+1.0D0)/(2.0D0*M+1.0D0)**2*X4
               GS=GS+1.0D0/(2*M+1.0D0)+1.0D0/(2*M+2.0D0)
@@ -9194,7 +9194,7 @@ C
 70         CONTINUE
 75         R=0.5D0*X
            GS=1.0D0
-           HEI=0.5D0*X-BEI/X-(DLOG(X/2.D0)+EL)*DEI-0.25*PI*DER
+           HEI=0.5D0*X-BEI/X-(DLOG(X/2.D0)+EL)*DEI-0.25d0*PI*DER
            DO 80 M=1,60
               R=-0.25D0*R/(M*M)/(2*M-1.0D0)/(2*M+1.0D0)*X4
               GS=GS+1.0D0/(2.0D0*M)+1.0D0/(2*M+1.0D0)
@@ -9825,14 +9825,14 @@ C       ====================================================
 C
         IMPLICIT DOUBLE PRECISION (A-H,O-Z)
         DIMENSION ZO(NT),RT0(8)
-        RT0(1)=2.84891
-        RT0(2)=5.02622
-        RT0(3)=1.71854
-        RT0(4)=3.91467
-        RT0(5)=6.03871
-        RT0(6)=3.77268
-        RT0(7)=2.66584
-        RT0(8)=4.93181
+        RT0(1)=2.84891d0
+        RT0(2)=5.02622d0
+        RT0(3)=1.71854d0
+        RT0(4)=3.91467d0
+        RT0(5)=6.03871d0
+        RT0(6)=3.77268d0
+        RT0(7)=2.66584d0
+        RT0(8)=4.93181d0
         RT=RT0(KD)
         DO 15 M=1,NT
 10         CALL KLVNA(RT,BER,BEI,GER,GEI,DER,DEI,HER,HEI)
```

**Comment by Pranavchiku** [comment]
This now works with following diff, code:
```fortran
subroutine klvna(x,ber,bei,ger,gei,der,dei,her,hei)

implicit double precision (a-h,o-z)
pi=3.141592653589793d0
el=.5772156649015329d0
eps=1.0d-15
if (x.eq.0.0d0) then
   ber=1.0d0
   bei=0.0d0
   ger=1.0d+300
   gei=-0.25d0*pi
   der=0.0d0
   dei=0.0d0
   her=-1.0d+300
   hei=0.0d0
   return
endif
x2=0.25d0*x*x
x4=x2*x2
if (dabs(x).lt.10.0d0) then
   ber=1.0d0
   r=1.0d0
   do 10 m=1,60
      r=-0.25d0*r/(m*m)/(2.0d0*m-1.0d0)**2*x4
      ber=ber+r
      if (dabs(r).lt.dabs(ber)*eps) go to 15
10         continue
15         bei=x2
   r=x2
   do 20 m=1,60
      r=-0.25d0*r/(m*m)/(2.0d0*m+1.0d0)**2*x4
      bei=bei+r
      if (dabs(r).lt.dabs(bei)*eps) go to 25
20         continue
25         ger=-(dlog(x/2.0d0)+el)*ber+0.25d0*pi*bei
   r=1.0d0
   gs=0.0d0
   do 30 m=1,60
      r=-0.25d0*r/(m*m)/(2.0d0*m-1.0d0)**2*x4
      gs=gs+1.0d0/(2.0d0*m-1.0d0)+1.0d0/(2.0d0*m)
      ger=ger+r*gs
      if (dabs(r*gs).lt.dabs(ger)*eps) go to 35
30         continue
35         gei=x2-(dlog(x/2.0d0)+el)*bei-0.25d0*pi*ber
   r=x2
   gs=1.0d0
   do 40 m=1,60
      r=-0.25d0*r/(m*m)/(2.0d0*m+1.0d0)**2*x4
      gs=gs+1.0d0/(2.0d0*m)+1.0d0/(2.0d0*m+1.0d0)
      gei=gei+r*gs
      if (dabs(r*gs).lt.dabs(gei)*eps) go to 45
40         continue
45         der=-0.25d0*x*x2
   r=der
   do 50 m=1,60
      r=-0.25d0*r/m/(m+1.0d0)/(2.0d0*m+1.0d0)**2*x4
      der=der+r
      if (dabs(r).lt.dabs(der)*eps) go to 55
50         continue
55         dei=0.5d0*x
   r=dei
   do 60 m=1,60
      r=-0.25d0*r/(m*m)/(2.d0*m-1.d0)/(2.d0*m+1.d0)*x4
      dei=dei+r
      if (dabs(r).lt.dabs(dei)*eps) go to 65
60            continue
65         r=-0.25d0*x*x2
   gs=1.5d0
   her=1.5d0*r-ber/x-(dlog(x/2.d0)+el)*der+0.25d0*pi*dei
   do 70 m=1,60
      r=-0.25d0*r/m/(m+1.0d0)/(2.0d0*m+1.0d0)**2*x4
      gs=gs+1.0d0/(2*m+1.0d0)+1.0d0/(2*m+2.0d0)
      her=her+r*gs
      if (dabs(r*gs).lt.dabs(her)*eps) go to 75
70         continue
75         r=0.5d0*x
   gs=1.0d0
   hei=0.5d0*x-bei/x-(dlog(x/2.d0)+el)*dei-0.25d0*pi*der
   do 80 m=1,60
      r=-0.25d0*r/(m*m)/(2*m-1.0d0)/(2*m+1.0d0)*x4
      gs=gs+1.0d0/(2.0d0*m)+1.0d0/(2*m+1.0d0)
      hei=hei+r*gs
      if (dabs(r*gs).lt.dabs(hei)*eps) return
80         continue
else
   pp0=1.0d0
   pn0=1.0d0
   qp0=0.0d0
   qn0=0.0d0
   r0=1.0d0
   km=18
   if (dabs(x).ge.40.0) km=10
   fac=1.0d0
   do 85 k=1,km
      fac=-fac
      xt=0.25d0*k*pi-int(0.125d0*k)*2.0d0*pi
      cs=cos(xt)
      ss=sin(xt)
      r0=0.125d0*r0*(2.0d0*k-1.0d0)**2/k/x
      rc=r0*cs
      rs=r0*ss
      pp0=pp0+rc
      pn0=pn0+fac*rc
      qp0=qp0+rs
85            qn0=qn0+fac*rs
   xd=x/dsqrt(2.0d0)
   xe1=exp(xd)
   xe2=exp(-xd)
   xc1=1.d0/dsqrt(2.0d0*pi*x)
   xc2=dsqrt(.5d0*pi/x)
   cp0=dcos(xd+0.125d0*pi)
   cn0=dcos(xd-0.125d0*pi)
   sp0=dsin(xd+0.125d0*pi)
   sn0=dsin(xd-0.125d0*pi)
   ger=xc2*xe2*(pn0*cp0-qn0*sp0)
   gei=xc2*xe2*(-pn0*sp0-qn0*cp0)
   ber=xc1*xe1*(pp0*cn0+qp0*sn0)-gei/pi
   bei=xc1*xe1*(pp0*sn0-qp0*cn0)+ger/pi
   pp1=1.0d0
   pn1=1.0d0
   qp1=0.0d0
   qn1=0.0d0
   r1=1.0d0
   fac=1.0d0
   do 90 k=1,km
      fac=-fac
      xt=0.25d0*k*pi-int(0.125d0*k)*2.0d0*pi
      cs=dcos(xt)
      ss=dsin(xt)
      r1=0.125d0*r1*(4.d0-(2.0d0*k-1.0d0)**2)/k/x
      rc=r1*cs
      rs=r1*ss
      pp1=pp1+fac*rc
      pn1=pn1+rc
      qp1=qp1+fac*rs
      qn1=qn1+rs
90         continue
   her=xc2*xe2*(-pn1*cn0+qn1*sn0)
   hei=xc2*xe2*(pn1*sn0+qn1*cn0)
   der=xc1*xe1*(pp1*cp0+qp1*sp0)-hei/pi
   dei=xc1*xe1*(pp1*sp0-qp1*cp0)+her/pi
endif
return
end

subroutine klvnzo_(nt,kd)
   implicit double precision (a-h,o-z)
   dimension zo(nt),rt0(8)
   rt0(1)=2.84891d0
   rt0(2)=5.02622d0
   rt0(3)=1.71854d0
   rt0(4)=3.91467d0
   rt0(5)=6.03871d0
   rt0(6)=3.77268d0
   rt0(7)=2.66584d0
   rt0(8)=4.93181d0
   rt=rt0(kd)
   print *, "rt = ", rt
   do 15 m=1,nt
10    call klvna(rt,ber,bei,ger,gei,der,dei,her,hei)
      if (kd.eq.1) then
         rt=rt-ber/der
      else if (kd.eq.2) then
         rt=rt-bei/dei
      else if (kd.eq.3) then
         rt=rt-ger/her
      else if (kd.eq.4) then
         rt=rt-gei/hei
      else if (kd.eq.5) then
         ddr=-bei-der/rt
         rt=rt-der/ddr
      else if (kd.eq.6) then
         ddi=ber-dei/rt
         rt=rt-dei/ddi
      else if (kd.eq.7) then
         gdr=-gei-her/rt
         rt=rt-her/gdr
      else
         gdi=ger-hei/rt
         rt=rt-hei/gdi
      endif
      if (dabs(rt-rt0(kd)).gt.5.0d-10) then
         rt0(kd)=rt
         go to 10
      endif
      zo(m)=rt
15 rt=rt+4.44d0
   return
end

program main
    call klvnzo_(5,8)
end program

```

**Comment by certik** [comment]
Very good. The diff above is definitely a bug in SciPy. I think you can go ahead and submit it as a SciPy PR. Hopefully everything passes at their CI, since the numbers will slightly change. For now just keep this diff in our own branch.

**Comment by Pranavchiku** [comment]
completed with https://github.com/scipy/scipy/pull/19107

**Comment by certik** [comment]
I would keep this open, since SciPy might decide not to merge the PR.

**Comment by certik** [comment]
See https://github.com/lfortran/lfortran/issues/2241 for the follow up on this. Not urgent for specfun, we can do it after specfun works well.
