### ISSUE TITLE
Error with fortran example from fortran90.org

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#213]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/112

I tried the example from https://www.fortran90.org/src/rosetta.html

```
lfortranmaster%=$cat test.f90     
integer :: a(3)
a = [1, 2, 3]
print *, shape(a)
print *, size(a)
print *, maxval(a)
print *, minval(a)
print *, sum(a)
end program
lfortranmaster%=$gfortran test.f90
lfortranmaster%=$./a.out
           3
           3
           3
           1
           6
lfortranmaster%=$./lfort test.f90
Traceback (most recent call last):
  File "/home/aaronmeurer/Documents/lfortran/lfortran/parser/fortranParser.py", line 857, in units
    self._errHandler.sync(self)
  File "/home/aaronmeurer/anaconda3/lib/python3.7/site-packages/antlr4/error/ErrorStrategy.py", line 220, in sync
    raise InputMismatchException(recognizer)
antlr4.error.Errors.InputMismatchException: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./lfort", line 6, in <module>
    main()
  File "/home/aaronmeurer/Documents/lfortran/lfortran/cli.py", line 132, in main
    e.evaluate(source)
  File "/home/aaronmeurer/Documents/lfortran/lfortran/codegen/evaluator.py", line 120, in evaluate
    ast_tree0 = self.parse(source)
  File "/home/aaronmeurer/Documents/lfortran/lfortran/codegen/evaluator.py", line 53, in parse
    return src_to_ast(source, translation_unit=False)
  File "/home/aaronmeurer/Documents/lfortran/lfortran/ast/utils.py", line 16, in src_to_ast
    return antlr_parse(source, translation_unit)
  File "/home/aaronmeurer/Documents/lfortran/lfortran/parser/parser.py", line 584, in antlr_parse
    parse_tree = parser.units()
  File "/home/aaronmeurer/Documents/lfortran/lfortran/parser/fortranParser.py", line 918, in units
    self._errHandler.reportError(self, re)
  File "/home/aaronmeurer/anaconda3/lib/python3.7/site-packages/antlr4/error/ErrorStrategy.py", line 126, in reportError
    self.reportInputMismatch(recognizer, e)
  File "/home/aaronmeurer/anaconda3/lib/python3.7/site-packages/antlr4/error/ErrorStrategy.py", line 264, in reportInputMismatch
    recognizer.notifyErrorListeners(msg, e.offendingToken, e)
  File "/home/aaronmeurer/anaconda3/lib/python3.7/site-packages/antlr4/Parser.py", line 314, in notifyErrorListeners
    listener.syntaxError(self, offendingToken, line, column, msg, e)
  File "/home/aaronmeurer/anaconda3/lib/python3.7/site-packages/antlr4/error/ErrorListener.py", line 60, in syntaxError
    delegate.syntaxError(recognizer, offendingSymbol, line, column, msg, e)
  File "/home/aaronmeurer/Documents/lfortran/lfortran/parser/parser.py", line 36, in syntaxError
    raise utils.SyntaxErrorException(message)
lfortran.ast.utils.SyntaxErrorException: Syntax Error:2:0: mismatched input 'a' expecting {<EOF>, ';', NEWLINE}
a = [1, 2, 3]
^
```

**Comment by sloorush** [comment]
I tried running this program with `lfortran` and it generates cpp well but when I try to run it I get this:

```
❯ lfortran ./integration_tests/rosetta_stone.f90
code generation error: Intrinsic 'shape' not implemented yet and compile time value is not available.


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

This is the file:
```f90
❯ cat integration_tests/rosetta_stone.f90
───────┬─────────────────────────────────────────────────────────
       │ File: integration_tests/rosetta_stone.f90
───────┼─────────────────────────────────────────────────────────
   1   │ program rosetta_stone
   2   │     implicit none
   3   │     integer :: a(3)
   4   │     a = [1, 2, 3]
   5   │     print *, shape(a)
   6   │     print *, size(a)
   7   │     print *, maxval(a)
   8   │     print *, minval(a)
   9   │     print *, sum(a)
  10   │ end program rosetta_stone
───────┴─────────────────────────────────────────────────────────
```

Hence not able to reproduce the issue

**Comment by sloorush** [comment]
The previous reply was deleted because I didn't read the instructions clearly 😅 

I tested this out with lfortran and gfortran and I am getting a different error when I run it with lfortran.

```
❯ cat a.py
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: a.py
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ from numpy import array, size, shape, min, max, sum
   2   │ a = array([1, 2, 3])
   3   │ print(shape(a))
   4   │ print(size(a))
   5   │ print(max(a))
   6   │ print(min(a))
   7   │ print(sum(a))
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
❯ cat a.f90
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: a.f90
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ program rosetta
   2   │     implicit none
   3   │     
   4   │     integer :: a(3)
   5   │     a = [1, 2, 3]
   6   │     print *, shape(a)
   7   │     print *, size(a)
   8   │     print *, maxval(a)
   9   │     print *, minval(a)
  10   │     print *, sum(a)
  11   │ end program rosetta
  12   │ 
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
❯ python3 a.py
(3,)
3
3
1
6
❯ gfortran a.f90
❯ ./a.out
           3
           3
           3
           1
           6
❯ python3 a.py
(3,)
3
3
1
6
❯ lfortran a.f90
code generation error: Intrinsic 'shape' not implemented yet and compile time value is not available.


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).

```

Is there something I am still doing wrong running the program? I am following the way mentioned [here](https://www.fortran90.org/src/rosetta.html#how-to-execute-code-snippets)

**Comment by certik** [comment]
You are not doing anything wrong, it is as LFortran said:

> code generation error: Intrinsic 'shape' not implemented yet and compile time value is not available.

Let me know if the message is not clear and if you have any ideas how to improve it. (we simply have not implemented this yet.)
