### ISSUE TITLE
Fortran Strings not implemented

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#215]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/114

I got this error while declaring a string in lofrt interactive compiler and binder notebook:
```Fortran
character(len = 100) :: src
Syntax Error:1:21: mismatched input '::' expecting {<EOF>, ';', NEWLINE}
character(len = 100) :: src
```
Also got the following error in binder:
```FORTRAN
character :: src

​
Traceback (most recent call last):
File "/srv/conda/lib/python3.7/site-packages/fortran_kernel/kernel.py", line 72, in do_execute
result = self.fe.evaluate(code)
File "/srv/conda/lib/python3.7/site-packages/lfortran/codegen/evaluator.py", line 123, in evaluate
r = self.evaluate_statement(ast_tree0, optimize)
File "/srv/conda/lib/python3.7/site-packages/lfortran/codegen/evaluator.py", line 114, in evaluate_statement
mod = self.llvm_code_generation(ast_tree, optimize)
File "/srv/conda/lib/python3.7/site-packages/lfortran/codegen/evaluator.py", line 89, in llvm_code_generation
self.symbol_table_visitor._global_scope))
File "/srv/conda/lib/python3.7/site-packages/lfortran/codegen/gen.py", line 639, in codegen
v.codegen(tree)
File "/srv/conda/lib/python3.7/site-packages/lfortran/codegen/gen.py", line 226, in codegen
self.do_global_vars()
File "/srv/conda/lib/python3.7/site-packages/lfortran/codegen/gen.py", line 264, in do_global_vars
var_type = self.types[type_f]
KeyError: <lfortran.semantic.analyze.Character object at 0x7f72ed958278>

```

Seems like strings have not been implemented in LFortran yet.

**Comment by lucifer1004** [comment]
This issue cannot be reproduced in the latest version. @certik

**Comment by certik** [comment]
This is fixed, thanks!
