### ISSUE TITLE
Calling subroutine take_min(arr) throws internal compiler error 

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#2177]
```
module mintest
    implicit none
contains 
    subroutine take_min(arr)   
        real(8), intent(out) :: arr(:,:)  
        real(8) :: tmp1, tmp2  
        tmp1 = huge(1.d0)
        tmp2 = huge(1.d0)
        arr(:,1) = min( 0.d0,tmp1,tmp2 )   

        if (arr(1, 1) /= 0.d0) error stop
        if (size(arr) /= 2) error stop
        
    end subroutine take_min
end module mintest
program name
    use mintest
    implicit none
    real(8) :: arr(1, 2)
    call take_min(arr)
end program name
```
```console
(lf) harshita@harshita-linux:~/Desktop/lfortran$ lfortran integration_tests/min_three_args.f90 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2201, in ??
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 930, in ??
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 345, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8311, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5037, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5013, in ??
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5038, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4747, in ??
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 871, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*mod);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5040, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4756, in ??
    case symbolType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2658, in LCompilers::ASRToLLVMVisitor::visit_Module(LCompilers::ASR::Module_t const&)
    visit_procedures(x);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3462, in void LCompilers::ASRToLLVMVisitor::visit_procedures<LCompilers::ASR::Module_t>(LCompilers::ASR::Module_t const&)
    visit_Function(*s);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3234, in LCompilers::ASRToLLVMVisitor::visit_Function(LCompilers::ASR::Function_t const&)
    generate_function(x);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3414, in LCompilers::ASRToLLVMVisitor::generate_function(LCompilers::ASR::Function_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5057, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4781, in ??
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4126, in LCompilers::ASRToLLVMVisitor::visit_Assignment(LCompilers::ASR::Assignment_t const&)
    this->visit_expr(*x.m_target);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5104, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4894, in ??
    case exprType::ArraySection: { v.visit_ArraySection((const ArraySection_t &)x); return; }
AssertFailed: ASR::is_a<ASR::Character_t>(*ASRUtils::expr_type(x.m_v)) && n_dims == 0
```

**Comment by Pranavchiku** [comment]
I am able to reproduce this, you may try to fix this.

**Comment by HarshitaKalani** [comment]
The error goes away if we 
```
module mintest
    implicit none
contains 
    subroutine take_min(arr)   
        real(8), intent(out) :: arr(:,:)  
        real(8) :: tmp1, tmp2  
        tmp1 = huge(1.d0)
        tmp2 = huge(1.d0)
        arr(:,1) = min( 0.d0,tmp1,tmp2 )  ---------------> change this to (0, 1, 1) i.e. removing ".d0"
        print *, arr

        if (arr(1, 1) /= 0.d0) error stop
        if (size(arr) /= 2) error stop
        
    end subroutine take_min
end module mintest
program name
    use mintest
    implicit none
    real(8) :: arr(1, 2)
    call take_min(arr)
end program name
```

**Comment by Pranavchiku** [comment]
Minimal code: 
I guess right now we don't support assignment to array slicing.
```fortran
subroutine sub(arr)   
   real(8), intent(out) :: arr(:,:)  
   real(8) :: tmp1
   arr(:,1) = min( 0.d0,tmp1 )   
end subroutine sub

program main
   real(8) :: arr(1, 2)
   interface
      subroutine sub(arr)
         real(8), intent(out) :: arr(:,:)
      end subroutine sub
   end interface
   call sub(arr)
end program
```

**Comment by HarshitaKalani** [comment]
This works with the latest main!

**Comment by certik** [comment]
But not on macOS: https://github.com/lfortran/lfortran/issues/2735.
