### ISSUE TITLE
[SciPy][Specfun]: `TestCephes::test_pbdv Fatal Python error: Segmentation fault`

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#2198]
Package: `scipy/special/specfun`
Resposible subroutine:

```fortran
        SUBROUTINE PBDV_(V,X,DV,DP,PDF,PDD)
C
C       ====================================================
C       Purpose: Compute parabolic cylinder functions Dv(x)
C                and their derivatives
C       Input:   x --- Argument of Dv(x)
C                v --- Order of Dv(x)
C       Output:  DV(na) --- Dn+v0(x)
C                DP(na) --- Dn+v0'(x)
C                ( na = |n|, v0 = v-n, |v0| < 1,
C                  n = 0,±1,±2,… )
C                PDF --- Dv(x)
C                PDD --- Dv'(x)
C       Routines called:
C             (1) DVSA for computing Dv(x) for small |x|
C             (2) DVLA for computing Dv(x) for large |x|
C       ====================================================
C
```

Test logs:

```console
% python dev.py test -t scipy.special.tests.test_basic -v
....
scipy/special/tests/test_basic.py::TestCephes::test_pbdv Fatal Python error: Segmentation fault

Current thread 0x00000001f4f29b40 (most recent call first):
  File "/Users/pranavchiku/repos/scipy/build-install/lib/python3.10/site-packages/scipy/special/tests/test_basic.py", line 804 in test_pbdv
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/python.py", line 194 in pytest_pyfunc_call
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_callers.py", line 80 in _multicall
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_manager.py", line 112 in _hookexec
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_hooks.py", line 433 in __call__
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/python.py", line 1788 in runtest
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/runner.py", line 169 in pytest_runtest_call
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_callers.py", line 80 in _multicall
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_manager.py", line 112 in _hookexec
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_hooks.py", line 433 in __call__
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/runner.py", line 262 in <lambda>
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/runner.py", line 341 in from_call
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/runner.py", line 261 in call_runtest_hook
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/runner.py", line 222 in call_and_report
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/runner.py", line 133 in runtestprotocol
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/runner.py", line 114 in pytest_runtest_protocol
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_callers.py", line 80 in _multicall
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_manager.py", line 112 in _hookexec
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_hooks.py", line 433 in __call__
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/main.py", line 349 in pytest_runtestloop
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_callers.py", line 80 in _multicall
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_manager.py", line 112 in _hookexec
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_hooks.py", line 433 in __call__
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/main.py", line 324 in _main
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/main.py", line 270 in wrap_session
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/main.py", line 317 in pytest_cmdline_main
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_callers.py", line 80 in _multicall
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_manager.py", line 112 in _hookexec
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_hooks.py", line 433 in __call__
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/config/__init__.py", line 166 in main
  File "/Users/pranavchiku/repos/scipy/build-install/lib/python3.10/site-packages/scipy/_lib/_testutils.py", line 109 in __call__
  File "/Users/pranavchiku/repos/scipy/dev.py", line 777 in scipy_tests
  File "/Users/pranavchiku/repos/scipy/dev.py", line 793 in run
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/doit/action.py", line 461 in execute
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/doit/task.py", line 473 in execute
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/doit/runner.py", line 176 in execute_task
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/doit/runner.py", line 220 in run_tasks
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/doit/runner.py", line 254 in run_all
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/doit/cmd_run.py", line 265 in _execute
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/doit/cmd_base.py", line 570 in execute
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/doit/cmd_base.py", line 150 in parse_execute
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/doit/api.py", line 50 in run_tasks
  File "/Users/pranavchiku/repos/scipy/dev.py", line 259 in run_doit_task
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pydevtool/cli.py", line 267 in callback
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/click/core.py", line 783 in invoke
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/click/core.py", line 1434 in invoke
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/click/core.py", line 1688 in invoke
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/click/core.py", line 1078 in main
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/rich_click/rich_group.py", line 21 in main
  File "/Users/pranavchiku/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/click/core.py", line 1157 in __call__
  File "/Users/pranavchiku/repos/scipy/dev.py", line 1468 in <module>

Extension modules: psutil._psutil_osx, psutil._psutil_posix, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, scipy._lib._ccallback_c, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.linalg._flinalg, scipy.special._ellip_harm_2, numpy.linalg.lapack_lite, scipy._lib._fpumode (total: 46)
zsh: segmentation fault  python dev.py test -t scipy.special.tests.test_basic -v
```

Actual code:

```fortran

        subroutine gamma2(x,ga)
        implicit double precision (a-h,o-z)
        dimension g(26)
        pi=3.141592653589793d0
        if (x.eq.int(x)) then
           if (x.gt.0.0d0) then
              ga=1.0d0
              m1=x-1
              do 10 k=2,m1
10               ga=ga*k
           else
              ga=1.0d+300
           endif
        else
           r=1.0d0
           if (dabs(x).gt.1.0d0) then
              z=dabs(x)
              m=int(z)
              do 15 k=1,m
15               r=r*(z-k)
              z=z-m
           else
              z=x
           endif
           data g/1.0d0,0.5772156649015329d0, &
              -0.6558780715202538d0, -0.420026350340952d-1, &
              0.1665386113822915d0,-.421977345555443d-1, &
              -.96219715278770d-2, .72189432466630d-2, &
              -.11651675918591d-2, -.2152416741149d-3, &
              .1280502823882d-3, -.201348547807d-4, &
              -.12504934821d-5, .11330272320d-5, &
              -.2056338417d-6, .61160950d-8, &
              .50020075d-8, -.11812746d-8, &
              .1043427d-9, .77823d-11, &
              -.36968d-11, .51d-12, &
              -.206d-13, -.54d-14, .14d-14, .1d-15/
           gr=g(26)
           do 20 k=25,1,-1
20            gr=gr*z+g(k)
           ga=1.0d0/(gr*z)
           if (dabs(x).gt.1.0d0) then
              ga=ga*r
              if (x.lt.0.0d0) ga=-pi/(x*ga*dsin(pi*x))
           endif
        endif
        return
        end


        subroutine vvla(va,x,pv)
        implicit double precision (a-h,o-z)
        pi=3.141592653589793d0
        eps=1.0d-12
        qe=exp(0.25*x*x)
        a0=dabs(x)**(-va-1.0d0)*dsqrt(2.0d0/pi)*qe
        r=1.0d0
        pv=1.0d0
        do 10 k=1,18
           r=0.5d0*r*(2.0*k+va-1.0)*(2.0*k+va)/(k*x*x)
           pv=pv+r
           if (dabs(r/pv).lt.eps) go to 15
10      continue
15      pv=a0*pv
        if (x.lt.0.0d0) then
           x1=-x
           call dvla(va,x1,pdl)
           call gamma2(-va,gl)
           dsl=dsin(pi*va)*dsin(pi*va)
           pv=dsl*gl/pi*pdl-dcos(pi*va)*pv
        endif
        return
        end        
        
        subroutine dvla(va,x,pd)
        implicit double precision (a-h,o-z)
        pi=3.141592653589793d0
        eps=1.0d-12
        ep=exp(-.25*x*x)
        a0=dabs(x)**va*ep
        r=1.0d0
        pd=1.0d0
        do 10 k=1,16
           r=-0.5d0*r*(2.0*k-va-1.0)*(2.0*k-va-2.0)/(k*x*x)
           pd=pd+r
           if (dabs(r/pd).lt.eps) go to 15
10      continue
15      pd=a0*pd
        if (x.lt.0.0d0) then
            x1=-x
            call vvla(va,x1,vl)
            call gamma2(-va,gl)
            pd=pi*vl/gl+dcos(pi*va)*pd
        endif
        return
        end

        subroutine dvsa(va,x,pd)
        implicit double precision (a-h,o-z)
        eps=1.0d-15
        pi=3.141592653589793d0
        sq2=dsqrt(2.0d0)
        ep=exp(-.25d0*x*x)
        va0=0.5d0*(1.0d0-va)
        if (va.eq.0.0) then
           pd=ep
        else
           if (x.eq.0.0) then
              if (va0.le.0.0.and.va0.eq.int(va0)) then
                 pd=0.0d0
              else
                 call gamma2(va0,ga0)
                 pd=dsqrt(pi)/(2.0d0**(-.5d0*va)*ga0)
              endif
           else
              call gamma2(-va,g1)
              a0=2.0d0**(-0.5d0*va-1.0d0)*ep/g1
              vt=-.5d0*va
              call gamma2(vt,g0)
              pd=g0
              r=1.0d0
              do 10 m=1,250
                 vm=.5d0*(m-va)
                 call gamma2(vm,gm)
                 r=-r*sq2*x/m
                 r1=gm*r
                 pd=pd+r1
                 if (dabs(r1).lt.dabs(pd)*eps) go to 15
10            continue
15            pd=a0*pd
           endif
        endif
        return
        end  
        
        subroutine pbdv(v,x,dv,dp,pdf,pdd)
        implicit double precision (a-h,o-z)
        dimension dv(0:*),dp(0:*)
        xa=dabs(x)
        vh=v
        v=v+sign(1.0d0,v)
        nv=int(v)
        v0=v-nv
        na=abs(nv)
        ep=exp(-.25d0*x*x)
        ja=0
        if (na.ge.1) ja=1
        if (v.ge.0.0) then
           if (v0.eq.0.0) then
              pd0=ep
              pd1=x*ep
           else
              do 10 l=0,ja
                 v1=v0+l
                 if (xa.le.5.8) call dvsa(v1,x,pd1)
                 if (xa.gt.5.8) call dvla(v1,x,pd1)
                 if (l.eq.0) pd0=pd1
10            continue
           endif
           dv(0)=pd0
           dv(1)=pd1
           do 15 k=2,na
              pdf=x*pd1-(k+v0-1.0d0)*pd0
              dv(k)=pdf
              pd0=pd1
15            pd1=pdf
        else
           if (x.le.0.0) then
              if (xa.le.5.8d0)  then
                 call dvsa(v0,x,pd0)
                 v1=v0-1.0d0
                 call dvsa(v1,x,pd1)
              else
                 call dvla(v0,x,pd0)
                 v1=v0-1.0d0
                 call dvla(v1,x,pd1)
              endif
              dv(0)=pd0
              dv(1)=pd1
              do 20 k=2,na
                 pd=(-x*pd1+pd0)/(k-1.0d0-v0)
                 dv(k)=pd
                 pd0=pd1
20               pd1=pd
           else if (x.le.2.0) then
              v2=nv+v0
              if (nv.eq.0) v2=v2-1.0d0
              nk=int(-v2)
              call dvsa(v2,x,f1)
              v1=v2+1.0d0
              call dvsa(v1,x,f0)
              dv(nk)=f1
              dv(nk-1)=f0
              do 25 k=nk-2,0,-1
                 f=x*f0+(k-v0+1.0d0)*f1
                 dv(k)=f
                 f1=f0
25               f0=f
           else
              if (xa.le.5.8) call dvsa(v0,x,pd0)
              if (xa.gt.5.8) call dvla(v0,x,pd0)
              dv(0)=pd0
              m=100+na
              f1=0.0d0
              f0=1.0d-30
              f=0.0d0
              do 30 k=m,0,-1
                 f=x*f0+(k-v0+1.0d0)*f1
                 if (k.le.na) dv(k)=f
                 f1=f0
30               f0=f
              s0=pd0/f
              do 35 k=0,na
35               dv(k)=s0*dv(k)
           endif
        endif
        do 40 k=0,na-1
           v1=abs(v0)+k
           if (v.ge.0.0d0) then
              dp(k)=0.5d0*x*dv(k)-dv(k+1)
           else
              dp(k)=-0.5d0*x*dv(k)-v1*dv(k+1)
           endif
40      continue
        pdf=dv(na-1)
        pdd=dp(na-1)
        v=vh
        return
        end

         program main
            implicit double precision (a-h,o-z)
      
            double precision :: v, x, dv(0:100), dp(0:100), pdf, pdd
            ! Declare the third and fourth arguments as double precision arrays
            
            v = 1.0d0
            x = 0.0d0
            
            ! Call the subroutine with the first two arguments and provide the arrays for the third and fourth arguments
            call pbdv(v, x, dv, dp, pdf, pdd)
      
         end program main

```

**Comment by Pranavchiku** [comment]
Implicit typing in program does not work:
```fortran
program main
implicit double precision (a-h,o-z)
dimension dv(0:100)
end program
```

> LFortran 

```console
 % lfortran b.f90 --implicit-typing
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2201
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 901
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 251
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 273
    compiler_options.symtab_only, compiler_options);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 93
    if (res.ok) {
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 2897
    v.visit_TranslationUnit(ast);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 126
    visit_ast(*x.m_items[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4768
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4725
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4771
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4368
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 520
    visit_unit_decl2(*x.m_decl[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4782
    void visit_unit_decl2(const unit_decl2_t &b) { visit_unit_decl2_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4395
    case unit_decl2Type::Declaration: { v.visit_Declaration((const Declaration_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1052
    visit_DeclarationUtil(x);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 1969
    ASR::Variable_t *v = ASR::down_cast<ASR::Variable_t>(get_sym);
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x18042ea83
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by Pranavchiku** [comment]
With #2200, it actual code starts working, but when I run scipy tests, it still throws me segmentation fault.

**Comment by Pranavchiku** [comment]
The code seg faults as soon as I assign some value to `dv`, this is weird because I am not able to reproduce this locally with actual code that I pasted above, locally it works perfect but segfaults on running tests.

```
        implicit double precision (a-h,o-z)
        dimension dv(0:*),dp(0:*)
        dv(0) = xx
```

**Comment by certik** [comment]
I think we just need to add tests for `dv(0:*)` and `x(*)` and ensure they work on linux and mac at least at the CI. Maybe that itself will already fail.

**Comment by Pranavchiku** [comment]
If I use the following diff, it works
```diff
% git diff scipy/special/specfun/specfun.f 
diff --git a/scipy/special/specfun/specfun.f b/scipy/special/specfun/specfun.f
index ace6f1d2d..751e1c12a 100644
--- a/scipy/special/specfun/specfun.f
+++ b/scipy/special/specfun/specfun.f
@@ -4381,7 +4381,7 @@ C             (2) DVLA for computing Dv(x) for large |x|
 C       ====================================================
 C
         IMPLICIT DOUBLE PRECISION (A-H,O-Z)
-        DIMENSION DV(0:*),DP(0:*)
+        DIMENSION DV(0:100),DP(0:100)
         XA=DABS(X)
         VH=V
         V=V+DSIGN(1.0D0,V)
```

**Comment by Pranavchiku** [comment]
Ahh, I feel I know what is happening: 

Test is present in `scipy/special/tests/test_basic.py`
```python
    def test_pbdv(self):
        assert_equal(cephes.pbdv(1,0),(0.0,1.0))
```

Now, when I lookup `cephes.pbdv` on pressing Command + Click, it takes me to the following declaration

```python
def pbdv(x1, x2, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any:
    "pbdv(x1, x2[, out1, out2], / [, out=(None, None)], *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])\n\npbdv(v, x)\n\nParabolic cylinder function D\n\nReturns (d, dp) the parabolic cylinder function Dv(x) in d and the\nderivative, Dv'(x) in dp.\n\nReturns\n-------\nd\n    Value of the function\ndp\n    Value of the derivative vs x"
    ...
```

Which when I asked chatGPT to expand, gave me the following:

```python
def pbdv(x1, x2, out1=None, out2=None, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True, signature=None, extobj=None) -> typing.Any:
    """
    Calculate the Parabolic Cylinder Function D and its derivative.

    This function computes the values of the parabolic cylinder function Dv(x)
    and its derivative Dv'(x) for given inputs v and x.

    Parameters:
    x1, x2 : array_like
        Input values for which the parabolic cylinder function and its derivative
        will be computed. These can be scalars or arrays of the same shape.
    out1, out2 : ndarray, None, optional
        Arrays to store the computed values of the parabolic cylinder function and
        its derivative, respectively. If not provided, new arrays are created.
    out : tuple, None, optional
        A tuple containing `out1` and `out2` arrays. If not provided, a tuple of
        new arrays is created. This parameter is specified as a keyword-only
        argument.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the condition
        is True, the out array will be set to the ufunc result. Elsewhere, the out
        array will retain its original value. This parameter is specified as a
        keyword-only argument.
    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
        Controls what kind of data casting may occur. This parameter is specified as
        a keyword-only argument.
    order : {'K', 'A', 'C', 'F'}, optional
        Controls the memory layout order of the output. This parameter is specified
        as a keyword-only argument.
    dtype : data-type, optional
        Specifies the data type of the output arrays. If not provided, the data type
        is inferred from the input values. This parameter is specified as a
        keyword-only argument.
    subok : bool, optional
        If True, then sub-classes will be passed through. If False, the returned
        arrays will be forced to be a base-class array. This parameter is specified
        as a keyword-only argument.
    signature : object, optional
        This parameter is associated with the numpy `__array_function__` protocol.
        It can be an arbitrary object that will be passed to any `__array_function__`
        implementations of functions that are called. This parameter is specified as
        a keyword-only argument.
    extobj : object, optional
        If provided, this parameter is passed to the underlying `__array__` method
        of the inputs for custom ufuncs. This parameter is specified as a
        keyword-only argument.

    Returns:
    tuple
        A tuple containing two arrays - `out1` containing the values of the
        parabolic cylinder function Dv(x) and `out2` containing the values of its
        derivative Dv'(x). These arrays have the same shape as the input arrays x1
        and x2.

    Note:
    The parabolic cylinder function Dv(x) and its derivative Dv'(x) are solutions
    to the parabolic cylinder differential equation and have applications in various
    areas of physics and mathematics.
    """
    pass
```


And now if we carefully observe the function arguments shown below, it states `If not provided, new arrays are created.`. This means that `dv` and `dp` are arrays created by some `python` call, whenever I do `dv(0)` in specfun.f, it is not able to access the address of `dv` and hence throws segfault. But when I try to reproduce this, I explicitly specify `double precision :: dv(0:100)` in `program main` and then when we do `dv(0)` we know the address of `dv` accessible, hence it works perfectly.
```
    out1, out2 : ndarray, None, optional
        Arrays to store the computed values of the parabolic cylinder function and
        its derivative, respectively. If not provided, new arrays are created.
```

**Comment by Pranavchiku** [comment]
With the following diff, I get all tests working without any segfault
```diff
% git diff scipy/special/specfun/specfun.f 
diff --git a/scipy/special/specfun/specfun.f b/scipy/special/specfun/specfun.f
index ace6f1d2d..c70bbeea0 100644
--- a/scipy/special/specfun/specfun.f
+++ b/scipy/special/specfun/specfun.f
@@ -4381,7 +4381,7 @@ C             (2) DVLA for computing Dv(x) for large |x|
 C       ====================================================
 C
         IMPLICIT DOUBLE PRECISION (A-H,O-Z)
-        DIMENSION DV(0:*),DP(0:*)
+        DIMENSION DV(0:100),DP(0:100)
         XA=DABS(X)
         VH=V
         V=V+DSIGN(1.0D0,V)
@@ -7977,7 +7977,7 @@ C       ==================================================
 C
         IMPLICIT DOUBLE PRECISION (A-B,D-H,O-Y)
         IMPLICIT COMPLEX*16 (C,Z)
-        DIMENSION CPB(0:*),CPD(0:*)
+        DIMENSION CPB(0:100),CPD(0:100)
         PI=3.141592653589793D0
         X=DBLE(Z)
         A0=ABS(Z)
@@ -11422,7 +11422,7 @@ C             (2) VVLA for computing Vv(x) for large |x|
 C       ===================================================
 C
         IMPLICIT DOUBLE PRECISION (A-H,O-Z)
-        DIMENSION VV(0:*),VP(0:*)
+        DIMENSION VV(0:100),VP(0:100)
         PI=3.141592653589793D0
         XA=DABS(X)
         VH=V
```

**Comment by Pranavchiku** [comment]
With this diff, I get everything working correctly
```diff
% git diff scipy/special/specfun/specfun.f
diff --git a/scipy/special/specfun/specfun.f b/scipy/special/specfun/specfun.f
index ace6f1d2d..679eeaa96 100644
--- a/scipy/special/specfun/specfun.f
+++ b/scipy/special/specfun/specfun.f
@@ -4381,7 +4381,7 @@ C             (2) DVLA for computing Dv(x) for large |x|
 C       ====================================================
 C
         IMPLICIT DOUBLE PRECISION (A-H,O-Z)
-        DIMENSION DV(0:*),DP(0:*)
+        DIMENSION DV(0:100),DP(0:100)
         XA=DABS(X)
         VH=V
         V=V+DSIGN(1.0D0,V)
@@ -7829,12 +7829,12 @@ C
         IMPLICIT DOUBLE PRECISION (A-H,O-Z)
         PI=3.141592653589793D0
         EPS=1.0D-12
-        EP=EXP(-.25*X*X)
+        EP=EXP(-.25D0*X*X)
         A0=DABS(X)**VA*EP
         R=1.0D0
         PD=1.0D0
         DO 10 K=1,16
-           R=-0.5D0*R*(2.0*K-VA-1.0)*(2.0*K-VA-2.0)/(K*X*X)
+           R=-0.5D0*R*(2.0D0*K-VA-1.0D0)*(2.0D0*K-VA-2.0)/(K*X*X)
            PD=PD+R
            IF (DABS(R/PD).LT.EPS) GO TO 15
 10      CONTINUE
@@ -7977,7 +7977,7 @@ C       ==================================================
 C
         IMPLICIT DOUBLE PRECISION (A-B,D-H,O-Y)
         IMPLICIT COMPLEX*16 (C,Z)
-        DIMENSION CPB(0:*),CPD(0:*)
+        DIMENSION CPB(0:100),CPD(0:100)
         PI=3.141592653589793D0
         X=DBLE(Z)
         A0=ABS(Z)
@@ -11422,7 +11422,7 @@ C             (2) VVLA for computing Vv(x) for large |x|
 C       ===================================================
 C
         IMPLICIT DOUBLE PRECISION (A-H,O-Z)
-        DIMENSION VV(0:*),VP(0:*)
+        DIMENSION VV(0:100),VP(0:100)
         PI=3.141592653589793D0
         XA=DABS(X)
         VH=V
```

**Comment by certik** [comment]
The `VV(0:*)` array has to be passed in like `PointerToDataArray`, but we do not know the upper bound, so it has to be something like:
```clojure
                                                    (Array
                                                        (Real 4)
                                                        [((IntegerConstant 0 (Integer 4))
                                                        ())]
                                                        PointerToDataArray
                                                    )
```
But I don't know if this breaks anything or not.

**Comment by Pranavchiku** [comment]
```fortran
cat a.f90 
subroutine sub(x, z)
real :: x(0:*), z(10)
x(0) = 1 
print *, x(0)
end subroutine

program main
real :: y(10), w(10)
call sub(y, w)
end program
```

So on updating it to `PointerToDataArray`, we get the following error, it is because backend is trying to get the upper limit of array, but it is nullptr in this case. I feel we will need to shift to add another array_physicalType.

```console
$ lfortran a.f90 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2201
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 936
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 345
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8640
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 5037
  File "../libasr/asr.h", line 5013
  File "../libasr/asr.h", line 5038
  File "../libasr/asr.h", line 4747
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 877
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5040
  File "../libasr/asr.h", line 4756
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3325
    visit_procedures(x);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3506
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5057
  File "../libasr/asr.h", line 4780
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4238
    is_assignment_target = true;
  File "../libasr/asr.h", line 5104
  File "../libasr/asr.h", line 4893
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2071
    ptr_loads = 2 - !LLVM::is_llvm_pointer(*ASRUtils::expr_type(m_dims[idim].m_length));
  File "../libasr/asr_utils.h", line 191
  File "../libasr/asr.h", line 49234
AssertFailed: f != nullptr
```

**Comment by Pranavchiku** [comment]
> Hm, it looks like we do. UnboundPointerToDataArray ?

Okay, and then at backend we should handle it the way `PointerToDataArray` works, right? If yes, what will be the bound here, it will throw an error again.

**Comment by certik** [comment]
There is no bound. You can't use bound with `UnboundedPointerToDataArray`.

**Comment by Pranavchiku** [comment]
I came across an example when declaring array as  `a(*)` made it work instead of `a(:)`. I was trying to call fortran routine from javascript using `node-js` and `node-gyp` and I remember we did something similar. So here is a stackoverflow explanation on how `a(*)` defers from `a(:)` https://stackoverflow.com/questions/24543329/assumed-size-arrays-colon-vs-asterisk-dimension-arr-vs-arr.
