### ISSUE TITLE
Procedure calls on class types do not work

### ISSUE THREAD

**Issue by ansharlubis** [lfortran/lfortran#2296]
The `push_back` call on `Vector` here does not work:
``` fortran
module template_vector_m
    implicit none
    private
    public :: vector_t

    type :: Vector
        integer, allocatable :: elements(:)
        integer :: sz = 0
    contains
        procedure :: resize
        procedure :: push_back
    end type

contains

    subroutine push_back(this, item)
        class(Vector), intent(in) :: this
        integer, intent(in) :: item

        integer :: new_size
        new_size = this%sz + 1

        call this%resize(new_size)
        this%elements(new_size) = item
        this%sz = new_size
    end subroutine

    subroutine resize(this, n)
        class(Vector), intent(inout) :: this
        integer, intent(in) :: n
        integer, allocatable :: tmp(:)
        integer :: i

        if (.not. allocated(this%elements)) then
            allocate(this%elements(n))
            return
        end if

        if (this%sz >= n) return

        allocate(tmp(this%sz))

        do i = 1, this%sz
            tmp(i) = this%elements(i)
        end do

        allocate(this%elements(n))

        this%elements(1:this%sz) = tmp 
    end subroutine


    subroutine main()
        type(Vector) :: v
        integer :: i
        v = Vector()
        call v%push_back(1)
    end subroutine

end module

program template_vector
    use template_vector_m
    implicit none
    call main()
end program
```

With the following error
```
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/lubis/projects/lfortran/src/bin/lfortran", in _start()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_start_main()
  File "/home/lubis/projects/lfortran/src/bin/lfortran.cpp", line 2212, in ??
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/lubis/projects/lfortran/src/bin/lfortran.cpp", line 936, in ??
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/lubis/projects/lfortran/src/lfortran/fortran_evaluator.cpp", line 345, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/lubis/projects/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8407, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/lubis/projects/lfortran/src/libasr/../libasr/asr.h", line 5037, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/lubis/projects/lfortran/src/libasr/../libasr/asr.h", line 5013, in ??
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/lubis/projects/lfortran/src/libasr/../libasr/asr.h", line 5038, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/lubis/projects/lfortran/src/libasr/../libasr/asr.h", line 4747, in ??
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/lubis/projects/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 871, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*mod);
  File "/home/lubis/projects/lfortran/src/libasr/../libasr/asr.h", line 5040, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/lubis/projects/lfortran/src/libasr/../libasr/asr.h", line 4756, in ??
    case symbolType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/home/lubis/projects/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2665, in LCompilers::ASRToLLVMVisitor::visit_Module(LCompilers::ASR::Module_t const&)
    visit_procedures(x);
  File "/home/lubis/projects/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3529, in void LCompilers::ASRToLLVMVisitor::visit_procedures<LCompilers::ASR::Module_t>(LCompilers::ASR::Module_t const&)
    visit_Function(*s);
  File "/home/lubis/projects/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3301, in LCompilers::ASRToLLVMVisitor::visit_Function(LCompilers::ASR::Function_t const&)
    generate_function(x);
  File "/home/lubis/projects/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3481, in LCompilers::ASRToLLVMVisitor::generate_function(LCompilers::ASR::Function_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/home/lubis/projects/lfortran/src/libasr/../libasr/asr.h", line 5057, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/lubis/projects/lfortran/src/libasr/../libasr/asr.h", line 4807, in ??
    case stmtType::SubroutineCall: { v.visit_SubroutineCall((const SubroutineCall_t &)x); return; }
  File "/home/lubis/projects/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7736, in LCompilers::ASRToLLVMVisitor::visit_SubroutineCall(LCompilers::ASR::SubroutineCall_t const&)
    std::vector<llvm::Value *> args2 = convert_call_args(x, is_method);
AssertFailed: false
```

**Comment by certik** [comment]
Thanks! I fixed up your example code to compile with gfortran. It still fails with the same error as you got in LFortran:
```fortran
module template_vector_m
    implicit none
    private
    public :: Vector, main

    type :: Vector
        integer, allocatable :: elements(:)
        integer :: sz = 0
    contains
        procedure :: resize
        procedure :: push_back
    end type

contains

    subroutine push_back(this, item)
        class(Vector), intent(inout) :: this
        integer, intent(in) :: item

        integer :: new_size
        new_size = this%sz + 1

        call this%resize(new_size)
        this%elements(new_size) = item
        this%sz = new_size
    end subroutine

    subroutine resize(this, n)
        class(Vector), intent(inout) :: this
        integer, intent(in) :: n
        integer, allocatable :: tmp(:)
        integer :: i

        if (.not. allocated(this%elements)) then
            allocate(this%elements(n))
            return
        end if

        if (this%sz >= n) return

        allocate(tmp(this%sz))

        do i = 1, this%sz
            tmp(i) = this%elements(i)
        end do

        allocate(this%elements(n))

        this%elements(1:this%sz) = tmp
    end subroutine


    subroutine main()
        type(Vector) :: v
        integer :: i
        v = Vector()
        call v%push_back(1)
    end subroutine

end module

program template_vector
    use template_vector_m
    implicit none
    call main()
end program
```

**Comment by gxyd** [comment]
Seems like LFortran can compile the above code as well now.
