### ISSUE TITLE
fastGPT --fast doesn't work

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2317]
The commit:
```
1f6f4d28b5624145515c7b00d8cff286917bea91 is the first bad commit
commit 1f6f4d28b5624145515c7b00d8cff286917bea91
Date:   Sat Sep 2 23:40:36 2023 +0530

    Fix in array_op ASR pass

 src/libasr/asr_utils.h         | 34 ++++++++++++++++++++++++++++++++++
 src/libasr/pass/array_op.cpp   |  9 ++++++++-
 src/libasr/pass/pass_utils.cpp |  3 ++-
 3 files changed, 44 insertions(+), 2 deletions(-)
```
Broke `--fast` for fastGPT:
```console
[ 76%] Linking Fortran executable test_basic_input
[ 76%] Built target test_basic_input
[ 82%] Building Fortran object CMakeFiles/test_more_inputs.dir/tests/test_more_inputs.f90.o
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2170
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 937
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 345
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8635
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "../libasr/asr.h", line 5037
  File "../libasr/asr.h", line 5013
  File "../libasr/asr.h", line 5038
  File "../libasr/asr.h", line 4746
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 884
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5040
  File "../libasr/asr.h", line 4755
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2711
    visit_procedures(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3553
    ASR::Function_t *s = ASR::down_cast<ASR::Function_t>(item.second);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3325
    visit_procedures(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3506
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5057
  File "../libasr/asr.h", line 4792
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5111
    this->visit_expr_wrapper(x.m_test, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4635
    this->visit_expr(*x);
  File "../libasr/asr.h", line 5104
  File "../libasr/asr.h", line 4900
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1345
    LCOMPILERS_ASSERT(false);
AssertFailed: false
make[2]: *** [CMakeFiles/test_more_inputs.dir/tests/test_more_inputs.f90.o] Error 1
make[1]: *** [CMakeFiles/test_more_inputs.dir/all] Error 2
make: *** [all] Error 2
```
It compiles with the previous commit, but fails now.

**Comment by certik** [comment]
Good news is that `make gpt2` works and `./gpt2` still works. 

So we might not need it. It would be nice to fix, but if it is hard, we might not need it.

**Comment by certik** [comment]
This PR shows how to trigger the bug: https://github.com/lfortran/lfortran/pull/2319

**Comment by certik** [comment]
This was fixed by https://github.com/lfortran/lfortran/pull/2335.
