### ISSUE TITLE
Bugs in `type(string), optional, intent(in) :: inputs(:)`

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2323]
There are several different bugs. This:
```fortran
program test_optional
implicit none

type :: string
    character(:), allocatable :: s
end type

call f()

contains

    subroutine f(x)
    type(string), optional, intent(in) :: x(:)
    end subroutine

end program
```
Gives:
```console
$ lfortran a.f90 
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2203
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 937
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 345
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8635
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "../libasr/asr.h", line 5037
  File "../libasr/asr.h", line 5013
  File "../libasr/asr.h", line 5038
  File "../libasr/asr.h", line 4746
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 884
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5040
  File "../libasr/asr.h", line 4755
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2752
    declare_vars(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3165
    ASR::expr_t* init_expr = v->m_symbolic_value;
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2801
    fill_array_details(ptr, llvm_data_type, m_dims, n_dims, is_data_only);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 402
    visit_expr(*(m_dim.m_start));
  File "../libasr/asr.h", line 5104
  File "../libasr/asr.h", line 5104
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Segfault: Signal SIGSEGV (segmentation fault) received
```

The combination in fastGPT gives the following error:
```
ASR verify pass error: ASR verify: Struct::m_derived_type 'string' cannot point outside of its symbol table, owner: driver
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2170
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 937
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 345
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8635
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 283
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 157
    + passes[i]);
LCompilersException: Verify failed in the pass: transform_optional_argument_functions
```

**Comment by Pranavchiku** [comment]
On further simplifying, the below given is also not working
```fortran
program test_optional
    implicit none
    
    character(:), allocatable :: s
    
    call f()
    
    contains
    
        subroutine f(x)
        character(*), optional, intent(in) :: x(:)
        end subroutine
end program
```

**Comment by Thirumalai-Shaktivel** [comment]
@certik How do I trigger the asr verify error in fastGPT?

**Comment by certik** [comment]
Just undo the workaround for "chat" and run make.

**Comment by Thirumalai-Shaktivel** [comment]
Minimal example:
```fortran
module test_optional_module_01
    implicit none
    type :: string
        character(:), allocatable :: s
    end type
contains
    subroutine sub_01(x)
        type(string), optional, intent(in) :: x(:)
        if (present(x)) print *, x(1)%s
    end subroutine
end module test_optional_module_01

module test_optional_module_02
    use test_optional_module_01, only: sub_01
    implicit none
contains
    subroutine sub_02()
        call sub_01()
    end subroutine sub_02

end module test_optional_module_02

program test_optional
use test_optional_module_02, only: sub_02
implicit none

call sub_02()

end program
```
