### ISSUE TITLE
Bugs in arrays of character

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2324]
In fastGPT, the following diff
```diff
diff --git a/gpt2.f90 b/gpt2.f90
index 6405c38..a57876e 100644
--- a/gpt2.f90
+++ b/gpt2.f90
@@ -21,7 +21,7 @@ type :: model_t
         ln2_b(:,:), ln2_g(:,:), &
         lnf_b(:), lnf_g(:)
     integer, allocatable :: decoder_idx(:), vocab_idx(:), byte_encoder(:)
-    integer(1), allocatable :: decoder_txt(:), vocab_txt(:)
+    character, allocatable :: decoder_txt(:), vocab_txt(:)
     integer :: model_file_version
 end type
 
diff --git a/tokenizer.f90 b/tokenizer.f90
index 2c4403c..2ae26e4 100644
--- a/tokenizer.f90
+++ b/tokenizer.f90
@@ -8,12 +8,12 @@ end type
 contains
 
 function c2s(x) result(y)
-integer(1), intent(in) :: x(:)
+character, intent(in) :: x(:)
 character(:), allocatable :: y
 integer :: i
 allocate(character(size(x)) :: y)
 do i = 1, size(x)
-    y(i:i) = char(x(i))
+    y(i:i) = x(i)
 end do
 end function
 
@@ -62,7 +62,7 @@ end function
 function word_idx(word, idx, decoder_txt) result(token)
 character(*), intent(in) :: word
 integer, intent(in) :: idx(0:)
-integer(1), intent(in) :: decoder_txt(:)
+character, intent(in) :: decoder_txt(:)
 integer :: token
 integer :: i
 ! This is O(n) search instead of O(1) lookup in a dictionary, so it is slow
@@ -154,7 +154,7 @@ function bpe(token, vocab_idx, vocab_txt) result(tokens)
 ! Takes a token as a string, and returns bpe tokens as an array of strings
 character(*), intent(in) :: token
 integer, intent(in) :: vocab_idx(0:)
-integer(1), intent(in) :: vocab_txt(:)
+character, intent(in) :: vocab_txt(:)
 type(string), allocatable :: tokens(:)
 integer, allocatable :: pair_scores(:)
 integer :: not_found, merge_pair_idx
@@ -195,7 +195,7 @@ function encode(input, idx, decoder_txt, vocab_idx, vocab_txt, byte_encoder) &
         result(tokens2)
 character(*), intent(in) :: input
 integer, intent(in) :: idx(0:), vocab_idx(0:), byte_encoder(0:)
-integer(1), intent(in) :: decoder_txt(:), vocab_txt(:)
+character, intent(in) :: decoder_txt(:), vocab_txt(:)
 integer, parameter :: max_tokens = 2048
 integer :: tokens(max_tokens)
 integer, allocatable :: tokens2(:)
@@ -232,12 +232,12 @@ end function
 
 function decode(tokens, idx, decoder_txt, byte_decoder) result(output)
 integer, intent(in) :: tokens(:), idx(0:), byte_decoder(0:)
-integer(1), intent(in) :: decoder_txt(:)
+character, intent(in) :: decoder_txt(:)
 character(:), allocatable :: output
 character(:), allocatable :: output2, tmp
 integer, parameter :: max_len = 4096
-integer(1) :: output3(max_len)
-integer(1), allocatable :: output4(:)
+character :: output3(max_len)
+character, allocatable :: output4(:)
 integer :: i, j, c, pos
 pos = 0
 do i = 1, size(tokens)
```
Gives:
```console
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2170
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 937
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 345
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8635
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "../libasr/asr.h", line 5037
  File "../libasr/asr.h", line 5013
  File "../libasr/asr.h", line 5038
  File "../libasr/asr.h", line 4746
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 870
    ASR::symbol_t *mod = x.m_global_scope->get_symbol(item);
  File "../libasr/asr.h", line 5040
  File "../libasr/asr.h", line 4755
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2688
    finish_module_init_function_prototype(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3553
    ASR::Function_t *s = ASR::down_cast<ASR::Function_t>(item.second);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3325
    visit_procedures(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3506
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5057
  File "../libasr/asr.h", line 4797
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6669
    ASR::ttype_t* type = ASRUtils::expr_type(x.m_values[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6627
    throw CodeGenError("Type not supported.");
  File "../libasr/codegen/llvm_utils.h", line 52
  File "../libasr/codegen/llvm_utils.h", line 51
code generation error: Type not supported.
```

**Comment by certik** [comment]
I think that this is fixed, at least in fastGPT it now works!

https://github.com/lfortran/lfortran/pull/2330

**Comment by certik** [comment]
I am going to close this issue. Thanks @Thirumalai-Shaktivel !
