### ISSUE TITLE
Verify failure should show the source code

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2383]
It usually does, but not in this case:
```console
$ lfortran --show-llvm llama2.f90   
ASR verify pass error: ASR verify: The symbol table was not found in the scope of `symtab`.

ASR verify pass error: ASR verify: Var::m_v `p` cannot point outside of its symbol table
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2128
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 843
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 291
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 313
    diagnostics, lm.files.back().in_filename);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 346
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8710
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 293
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 167
    + passes[i]);
LCompilersException: Verify failed in the pass: intrinsic_function
```
Using lfortran e1e210c8c1dfe81113a76c951e43a512e24c4231 and llama2.f90 26024db0668962099f0875718b1b105d61ec0dee.

**Comment by Thirumalai-Shaktivel** [comment]
Do you mean something like this?
```console
ASR verify pass error: ASR verify: Allocate should only be called with  Allocatable or Pointer type inputs, found i32[:]
   --> examples/expr2.f90:116:5
    |
116 |     allocate(x(2))
    |     ^^^^^^^^^^^^^^ failed here


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
