### ISSUE TITLE
LFortran segmentation fault

### ISSUE THREAD

**Issue by jkd2016** [lfortran/lfortran#2416]
When compiling the attached module with

```
lfortran --implicit-interface -c modxcifc.f90
```

LFortran version 0.20.3 on Linux gives a segmentation fault.

[modxcifc.zip](https://github.com/lfortran/lfortran/files/12599115/modxcifc.zip)

**Comment by certik** [comment]
I get the following error message:
```
$ lfortran modxcifc.f90 
style suggestion: Use '<=' instead of '.le.'
   --> modxcifc.f90:130:6
    |
130 | if (n.le.0) then
    |      ^^^^ help: write this as '<='

style suggestion: Use '==' instead of '.eq.'
   --> modxcifc.f90:209:16
    |
209 |   if (xctype(1).eq.21) then
    |                ^^^^ help: write this as '=='

style suggestion: Use '==' instead of '.eq.'
   --> modxcifc.f90:216:16
    |
216 |   if (xctype(1).eq.22) then
    |                ^^^^ help: write this as '=='

style suggestion: Use '<=' instead of '.le.'
   --> modxcifc.f90:366:14
    |
366 | if (xctype(1).le.-2) then
    |              ^^^^ help: write this as '<='

semantic error: Module 'libxcifc' not declared in the current source and the modfile was not found
 --> modxcifc.f90:8:1
  |
8 | use libxcifc
  | ^^^^^^^^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
This bug will have to be isolated first.

If you compile the latest main of LFortran and enable stacktraces, then LFortran will print a nice stacktrace instead of a segfault.

**Comment by jkd2016** [comment]
Sorry about that. Here is the stub file for the interface to Libxc which should be compiled first.
[libxcifc_stub.zip](https://github.com/lfortran/lfortran/files/12599593/libxcifc_stub.zip)

**Comment by jkd2016** [comment]
I've reduced it to a simpler form.

Compile this module first:
```
module libxcifc

contains

subroutine xcifc_libxc(xctype,n,tempa,rho)
implicit none
! mandatory arguments
integer, intent(in) :: xctype(3),n
! optional arguments
real(8), optional :: tempa
real(8), optional :: rho(n)
end subroutine

end module
```
and this second:
```
module modxcifc

use libxcifc

contains

subroutine xcifc(xctype,n,tempa)
implicit none
! mandatory arguments
integer, intent(in) :: xctype(3)
integer, intent(in) :: n
! optional arguments
real(8), optional, intent(in) :: tempa
call xcifc_libxc(xctype,n,tempa=tempa)
end subroutine

end module
```

The seg. fault occurs if they are compiled separately. If they are compiled together, viz.:
```
lfortran --implicit-interface -c libxcifc_stub.f90 modxcifc.f90
```
then the problem disappears.

It also compiles without issue if the optional argument rho is included in the call:
```
module modxcifc

use libxcifc

contains

subroutine xcifc(xctype,n,tempa,rho)
implicit none
! mandatory arguments
integer, intent(in) :: xctype(3)
integer, intent(in) :: n
! optional arguments
real(8), optional, intent(in) :: tempa,rho(n)
call xcifc_libxc(xctype,n,tempa=tempa,rho=rho)
end subroutine

end module

```

**Comment by certik** [comment]
Awesome, thanks for the minimal reproducer. I can now reproduce it, this is what I get:
```console
$ lfortran a.f90 --implicit-interface
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2206
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 910
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 252
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 274
    compiler_options.symtab_only, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 116
    if (res.ok) {
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3205
    b.is_body_visitor = true;
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 217
    visit_ast(*x.m_items[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4768
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4725
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4771
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4366
    case modType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1513
    visit_program_unit(*x.m_contains[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4776
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4377
    case program_unitType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1867
    ASRUtils::update_call_args(al, current_scope, compiler_options.implicit_interface);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_utils.cpp", line 216
    ASR::TranslationUnit_t* tu = ASR::down_cast2<ASR::TranslationUnit_t>(asr_);
  File "../libasr/asr.h", line 39708
  File "../libasr/asr.h", line 5040
  File "../libasr/asr.h", line 4755
  File "../libasr/asr.h", line 39726
  File "../libasr/asr.h", line 5040
  File "../libasr/asr.h", line 4756
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_utils.cpp", line 206
    visit_stmt(*func->m_body[i]);
  File "../libasr/asr.h", line 5057
  File "../libasr/asr.h", line 4806
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_utils.cpp", line 173
    ASR::expr_t* arg_expr = arg.m_value;
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Segfault: Signal SIGSEGV (segmentation fault) received
```
