### ISSUE TITLE
[SciPy]: AssertFailed for external functions passed as argument of interface

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#2427]
```fortran
subroutine a()
external f, g

call b(f, g)
end
```

> GFortran

```console
% gfortran a.f90       
Undefined symbols for architecture arm64:
  "_b_", referenced from:
      _a_ in ccPfzGu6.o
  "_f_", referenced from:
      _a_ in ccPfzGu6.o
  "_g_", referenced from:
      _a_ in ccPfzGu6.o
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
```

> GFortran -c
```
% gfortran a.f90 -c
```

> LFortran & LFortran -c --generate-object-code

```console
% lfortran a.f90 --implicit-interface --implicit-typing  --show-llvm
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2128
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 843
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 291
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 313
    diagnostics, lm.files.back().in_filename);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 346
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8966
    std::cout << LCompilers::pickle(asr, true, true, false) << std::endl;
  File "../libasr/asr.h", line 5037
  File "../libasr/asr.h", line 5013
  File "../libasr/asr.h", line 5038
  File "../libasr/asr.h", line 4747
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 880
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5040
  File "../libasr/asr.h", line 4756
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3551
    visit_procedures(x);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3746
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5057
  File "../libasr/asr.h", line 4806
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8140
    std::vector<llvm::Value *> args2 = convert_call_args(x, is_method);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7621
    LCOMPILERS_ASSERT(llvm_symtab_fn_arg.find(h) != llvm_symtab_fn_arg.end());
AssertFailed: llvm_symtab_fn_arg.find(h) != llvm_symtab_fn_arg.end()
```

This happens becase `external f, g` declares `f`, `g`, in parent scope of `b` and hence somehow these are not present in `llvm_symtab_fn_arg.find`

**Comment by Pranavchiku** [comment]
This is also not working

```fortran
subroutine b(f,g)
    ! f, g are functions
    call f()
    call g()
end subroutine

subroutine f()
    print *, "f"
end subroutine

subroutine g()
    print *, "g"
end subroutine

subroutine a()
interface
    subroutine f()
    end subroutine
    subroutine g()
    end subroutine
end interface
call b(f,g)
end subroutine

program main
call a()
end program
```

> GFortran

```console
% gfortran a3.f90 && ./a.out                      
 f
 g
```

> LFortran

```console
% lfortran a3.f90 --implicit-interface  --implicit-typing
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2286
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 962
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 347
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9024
    std::cout << LCompilers::pickle(asr, true, true, false) << std::endl;
  File "../libasr/asr.h", line 5037
  File "../libasr/asr.h", line 5013
  File "../libasr/asr.h", line 5038
  File "../libasr/asr.h", line 4747
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 902
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5040
  File "../libasr/asr.h", line 4756
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3585
    visit_procedures(x);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3780
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5057
  File "../libasr/asr.h", line 4806
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8174
    std::vector<llvm::Value *> args2 = convert_call_args(x, is_method);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7655
    LCOMPILERS_ASSERT(llvm_symtab_fn_arg.find(h) != llvm_symtab_fn_arg.end());
AssertFailed: llvm_symtab_fn_arg.find(h) != llvm_symtab_fn_arg.end()

```
