### ISSUE TITLE
[Compiling dftatom]  Issue with elemental intrinsic function

### ISSUE THREAD

**Issue by Thirumalai-Shaktivel** [lfortran/lfortran#2434]
```fortran
program expr2
implicit none

real(8) :: gamma = 1
real(8) :: x(3)
gamma = 0.3612163121_8
x = [1._8, 2._8, 3._8]

print *, exp(-gamma*sqrt(x))

end program
```
GFortran:
```console
$ gfortran examples/expr2.f90 && ./a.out
  0.69682824978102864       0.59999316978514361       0.53491629349743086
```
LFortran
```console
$ lfortran examples/expr2.f90
ASR verify pass error: ASR verify: The input and output type of elemental intrinsics must exactly match, input type: r64[:] output type: r64
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/thirumalai/Open_Source/lfortran/src/bin/lfortran.cpp", line 2286
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/thirumalai/Open_Source/lfortran/src/bin/lfortran.cpp", line 962
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/thirumalai/Open_Source/lfortran/src/lfortran/fortran_evaluator.cpp", line 347
    compiler_options, run_fn, infile);
  File "/Users/thirumalai/Open_Source/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8955
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/Users/thirumalai/Open_Source/lfortran/src/libasr/pass/pass_manager.h", line 303
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/thirumalai/Open_Source/lfortran/src/libasr/pass/pass_manager.h", line 168
    throw LCompilersException("Verify failed in the pass: "
LCompilersException: Verify failed in the pass: array_op
```

**Comment by czgdp1807** [comment]
This can be workaround using the following pattern,

```fortran
program expr2
implicit none

real(8) :: gamma = 1
real(8) :: x(3), xsqrt(3)
gamma = 0.3612163121_8
x = [1._8, 2._8, 3._8]

xsqrt = -gamma*sqrt(x)
print *, exp(xsqrt)

end program
```

Basically the following expression can be re-written,

```fortran
Z_eff = Z * (1 + alpha*sqrt(x) + beta*x*exp(-gamma*sqrt(x)))**2 * &
    exp(-2*alpha*sqrt(x))
```

Here `exp(-gamma*sqrt(x)))` needs to be re-written and `exp(-gamma*sqrt(x)))` needs to be re-written. Rest assured I will work on the original issue next week (from Monday onwards).

**Comment by czgdp1807** [comment]
Check out from your previous branch (`lf2` to `lf3` and add the above workaround).

**Comment by czgdp1807** [comment]
The following also fails,

```fortran
program expr2
implicit none

real(8) :: gamma = 1
real(8) :: x(3), xsqrt(3)
gamma = 0.3612163121_8
x = [1._8, 2._8, 3._8]

xsqrt = sqrt(x)
print *, exp(-gamma*xsqrt)

end program
```

With the same error.

**Comment by czgdp1807** [comment]
Output should be an `Array` but it isn't,

`[(IntrinsicScalarFunction Exp [(RealBinOp (RealUnaryMinus (Var 2 gamma) (Real 8) ()) Mul (Var 2 xsqrt) (Real 8) ())] 0 (Real 8) ())] () ())])` and there is one more bug in `subroutine_from_functions` pass. I will fix both and meanwhile we can use the workaround to make progress on `dftatom` compilation. Thanks a lot @Thirumalai-Shaktivel for quick investigation. :-)

**Comment by Thirumalai-Shaktivel** [comment]
Another issue, which seems related: 
```console
ASR verify pass error: ASR verify: The variable in ArrayItem must be an array, not a scalar
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/thirumalai/Open_Source/lfortran/src/bin/lfortran.cpp", line 2251
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/thirumalai/Open_Source/lfortran/src/bin/lfortran.cpp", line 962
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/thirumalai/Open_Source/lfortran/src/lfortran/fortran_evaluator.cpp", line 347
    compiler_options, run_fn, infile);
  File "/Users/thirumalai/Open_Source/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8955
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/Users/thirumalai/Open_Source/lfortran/src/libasr/pass/pass_manager.h", line 303
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/thirumalai/Open_Source/lfortran/src/libasr/pass/pass_manager.h", line 168
    throw LCompilersException("Verify failed in the pass: "
LCompilersException: Verify failed in the pass: array_op
```
I did the following workaround:
```diff
diff --git a/src/rdirac.f90 b/src/rdirac.f90
index ac876ce..748239f 100644
--- a/src/rdirac.f90
+++ b/src/rdirac.f90
@@ -118,6 +118,7 @@ real(dp), dimension(size(R)) :: u1, u2, u1p, u2p
 integer :: i
 real(dp) :: Delta, M(2, 2), u1_tmp, u2_tmp
 real(dp) :: R_max
+real(dp) :: tmp_1(4)
 
 nr = size(R)
 
@@ -143,8 +144,10 @@ end do
 u1(i_max+4:) = 0
 u2(i_max+4:) = 0
 
-u1(i_max:i_max+4) = exp(-lambda * (R(i_max:i_max+4)-R(1))) / sqrt(-E/(E+2*c**2))
-u2(i_max:i_max+4) = -exp(-lambda * (R(i_max:i_max+4)-R(1)))
+tmp_1 = -lambda * (R(i_max:i_max+4)-R(1))
+
+u1(i_max:i_max+4) = exp(tmp_1) / sqrt(-E/(E+2*c**2))
+u2(i_max:i_max+4) = -exp(tmp_1)
 
 Ctot(:, 1, 1) = -kappa / R
 Ctot(:, 2, 2) = +kappa / R
```

**Comment by czgdp1807** [comment]
I see. Can you create an MRE for the bug you faced after the workaround? I will fix that first.

**Comment by Thirumalai-Shaktivel** [comment]
MRE for this issue: https://github.com/lfortran/lfortran/issues/2434#issuecomment-1722297480 or upcoming issue?

**Comment by Thirumalai-Shaktivel** [comment]
MRE for https://github.com/lfortran/lfortran/issues/2434#issuecomment-1722297480:
```fortran
program expr2
implicit none

real(8) :: lambda = 1.123
real(8) :: x(10)
integer :: i_max = 2
x = 23.
print exp(-lambda * (x(i_max:i_max+4)-x(1)))

end program
```
