### ISSUE TITLE
[SciPy]: Amos - code generation error: Type mismatch in subroutine call, expected `f64[16]`, passed `f64`

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#2481]
```lfortran
   SUBROUTINE ZUNIK(ZRR, ZRI, FNU, IKFLG, IPMTR, TOL, INIT, PHIR, PHII, ZETA1R, ZETA1I, ZETA2R, ZETA2I, SUMR, SUMI, CWRKR, CWRKI)
      DOUBLE PRECISION CWRKI, CWRKR, FNU, PHII, PHIR, SUMI, SUMR, TOL, ZETA1I, ZETA1R, ZETA2I, ZETA2R, ZRI, ZRR, D1MACH
      INTEGER IKFLG, INIT, IPMTR
      DIMENSION CWRKR(16), CWRKI(16)
      END

      program main
         DOUBLE PRECISION CWRKR, CWRKI
         DIMENSION CWRKR(16,3), CWRKI(16,3)
         CALL ZUNIK(1d0, 1d0, 1d0, 1, 1, 1d0, 1, 1d0, 1d0,1d0, 1d0, 1d0, 1d0, 1d0, 1d0, CWRKR(1,J), CWRKI(1,J))
         ! CALL ZUNIK(ZRR, ZRI, FN, 2, 0, TOL, INIT(J), PHIR(J), PHII(J), ZETA1R(J), ZETA1I(J), ZETA2R(J), ZETA2I(J), SUMR(J), SUMI(J), CWRKR(1,J), CWRKI(1,J))
         end
```
```console
(base) harshita@harshita-linux:~/scipy$ lfortran a.f90 --implicit-typing --implicit-interface --no-warnings
; ModuleID = 'LFortran'
source_filename = "LFortran"

define void @zunik(double* %zrr, double* %zri, double* %fnu, i32* %ikflg, i32* %ipmtr, double* %tol, i32* %init, double* %phir, double* %phii, double* %zeta1r, double* %zeta1i, double* %zeta2r, double* %zeta2i, double* %sumr, double* %sumi, [16 x double]* %cwrkr, [16 x double]* %cwrki) {
.entry:
  %d1mach = alloca double, align 8
  br label %return

return:                                           ; preds = %.entry
  ret void
}

define i32 @main(i32 %0, i8** %1) {
.entry:
  %call_arg_value14 = alloca double, align 8
  %call_arg_value13 = alloca double, align 8
  %call_arg_value12 = alloca double, align 8
  %call_arg_value11 = alloca double, align 8
  %call_arg_value10 = alloca double, align 8
  %call_arg_value9 = alloca double, align 8
  %call_arg_value8 = alloca double, align 8
  %call_arg_value7 = alloca double, align 8
  %call_arg_value6 = alloca i32, align 4
  %call_arg_value5 = alloca double, align 8
  %call_arg_value4 = alloca i32, align 4
  %call_arg_value3 = alloca i32, align 4
  %call_arg_value2 = alloca double, align 8
  %call_arg_value1 = alloca double, align 8
  %call_arg_value = alloca double, align 8
  call void @_lpython_set_argv(i32 %0, i8** %1)
  %cwrki = alloca [48 x double], align 8
  %cwrkr = alloca [48 x double], align 8
  %j = alloca i32, align 4
  store double 1.000000e+00, double* %call_arg_value, align 8
  store double 1.000000e+00, double* %call_arg_value1, align 8
  store double 1.000000e+00, double* %call_arg_value2, align 8
  store i32 1, i32* %call_arg_value3, align 4
  store i32 1, i32* %call_arg_value4, align 4
  store double 1.000000e+00, double* %call_arg_value5, align 8
  store i32 1, i32* %call_arg_value6, align 4
  store double 1.000000e+00, double* %call_arg_value7, align 8
  store double 1.000000e+00, double* %call_arg_value8, align 8
  store double 1.000000e+00, double* %call_arg_value9, align 8
  store double 1.000000e+00, double* %call_arg_value10, align 8
  store double 1.000000e+00, double* %call_arg_value11, align 8
  store double 1.000000e+00, double* %call_arg_value12, align 8
  store double 1.000000e+00, double* %call_arg_value13, align 8
  store double 1.000000e+00, double* %call_arg_value14, align 8
  %2 = load i32, i32* %j, align 4
  %3 = sub i32 %2, 1
  %4 = mul i32 16, %3
  %5 = add i32 0, %4
  %6 = getelementptr [48 x double], [48 x double]* %cwrkr, i32 0, i32 %5
  %7 = load i32, i32* %j, align 4
  %8 = sub i32 %7, 1
  %9 = mul i32 16, %8
  %10 = add i32 0, %9
  %11 = getelementptr [48 x double], [48 x double]* %cwrki, i32 0, i32 %10
  call void @zunik(double* %call_arg_value, double* %call_arg_value1, double* %call_arg_value2, i32* %call_arg_value3, i32* %call_arg_value4, double* %call_arg_value5, i32* %call_arg_value6, double* %call_arg_value7, double* %call_arg_value8, double* %call_arg_value9, double* %call_arg_value10, double* %call_arg_value11, double* %call_arg_value12, double* %call_arg_value13, double* %call_arg_value14, double* %6, double* %11)
  ret i32 0
}

declare void @_lpython_set_argv(i32, i8**)
code generation error: asr_to_llvm: module failed verification. Error:
Call parameter type does not match function signature!
  %6 = getelementptr [48 x double], [48 x double]* %cwrkr, i32 0, i32 %5
 [16 x double]*  call void @zunik(double* %call_arg_value, double* %call_arg_value1, double* %call_arg_value2, i32* %call_arg_value3, i32* %call_arg_value4, double* %call_arg_value5, i32* %call_arg_value6, double* %call_arg_value7, double* %call_arg_value8, double* %call_arg_value9, double* %call_arg_value10, double* %call_arg_value11, double* %call_arg_value12, double* %call_arg_value13, double* %call_arg_value14, double* %6, double* %11)



Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
(base) harshita@harshita-linux:~/scipy$ vi c.f90
(base) harshita@harshita-linux:~/scipy$ lfortran c.f90
syntax error: Newline is unexpected here
 --> c.f90:2:23
  |
2 |       DOUBLE PRECISION
  |                       ^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
(base) harshita@harshita-linux:~/scipy$ lfortran c.f90 --implicit-typing --implicit-interface --no-warnings
syntax error: Newline is unexpected here
 --> c.f90:2:23
  |
2 |       DOUBLE PRECISION
  |                       ^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
(base) harshita@harshita-linux:~/scipy$ lfortran c.f90 --implicit-typing --implicit-interface --no-warnings
/usr/bin/ld: /lib/x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
The command 'clang -o a.out a.out.tmp.o  -L"/home/harshita/Desktop/lfortran/src/bin/../runtime" -Wl,-rpath,"/home/harshita/Desktop/lfortran/src/bin/../runtime" -llfortran_runtime -lm' failed.
(base) harshita@harshita-linux:~/scipy$ lfortran c.f90 --implicit-typing --implicit-interface --no-warnings
; ModuleID = 'LFortran'
source_filename = "LFortran"

%array = type { double*, i32, %dimension_descriptor*, i1, i32 }
%dimension_descriptor = type { i32, i32, i32 }

define void @dqrdc(%array* %x, i32* %ldx) {
.entry:
  %l = alloca i32, align 4
  %t = alloca float, align 4
  %0 = load i32, i32* %l, align 4
  %1 = load i32, i32* %l, align 4
  %2 = getelementptr %array, %array* %x, i32 0, i32 2
  %3 = load %dimension_descriptor*, %dimension_descriptor** %2, align 8
  %4 = getelementptr inbounds %dimension_descriptor, %dimension_descriptor* %3, i32 0
  %5 = getelementptr %dimension_descriptor, %dimension_descriptor* %4, i32 0, i32 1
  %6 = load i32, i32* %5, align 4
  %7 = sub i32 %0, %6
  %8 = getelementptr %dimension_descriptor, %dimension_descriptor* %4, i32 0, i32 0
  %9 = load i32, i32* %8, align 4
  %10 = mul i32 %9, %7
  %11 = add i32 0, %10
  %12 = getelementptr inbounds %dimension_descriptor, %dimension_descriptor* %3, i32 1
  %13 = getelementptr %dimension_descriptor, %dimension_descriptor* %12, i32 0, i32 1
  %14 = load i32, i32* %13, align 4
  %15 = sub i32 %1, %14
  %16 = getelementptr %dimension_descriptor, %dimension_descriptor* %12, i32 0, i32 0
  %17 = load i32, i32* %16, align 4
  %18 = mul i32 %17, %15
  %19 = add i32 %11, %18
  %20 = getelementptr %array, %array* %x, i32 0, i32 1
  %21 = load i32, i32* %20, align 4
  %22 = add i32 %19, %21
  %23 = getelementptr %array, %array* %x, i32 0, i32 0
  %24 = load double*, double** %23, align 8
  %25 = getelementptr inbounds double, double* %24, i32 %22
  %26 = call double @ddot(double* %25)
  %27 = fneg double %26
  %28 = fptrunc double %27 to float
  store float %28, float* %t, align 4
  br label %return

unreachable_after_return:                         ; No predecessors!
  br label %return

return:                                           ; preds = %unreachable_after_return, %.entry
  ret void
}

declare double @ddot(double*)

define void @dqrsl(float (i32*, i32*)* %x) {
.entry:
  %call_arg_value = alloca float, align 4
  %j = alloca i32, align 4
  %t = alloca float, align 4
  %0 = call float %x(i32* %j, i32* %j)
  store float %0, float* %call_arg_value, align 4
  %1 = call double @ddot(float* %call_arg_value)
  %2 = fneg double %1
  %3 = fptrunc double %2 to float
  store float %3, float* %t, align 4
  br label %return

unreachable_after_return:                         ; No predecessors!
  br label %return

return:                                           ; preds = %unreachable_after_return, %.entry
  ret void
}

declare float @x(i32*, i32*)

declare float @x.1(i32*, i32*)

define i32 @main(i32 %0, i8** %1) {
.entry:
  call void @_lpython_set_argv(i32 %0, i8** %1)
  ret i32 0
}

declare void @_lpython_set_argv(i32, i8**)
code generation error: asr_to_llvm: module failed verification. Error:
Call parameter type does not match function signature!
  %call_arg_value = alloca float, align 4
 double*  %1 = call double @ddot(float* %call_arg_value)



Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

**Comment by Pranavchiku** [comment]
Is this issue coming from latest main? I feel we compile Amos to LLVM and we might get no code generation errors.

**Comment by HarshitaKalani** [comment]
I created a file `a.f90` and put one of the subroutines `zbesh` that was called in a test.
Then I brought all other subroutines on which `zbesh` was dependent. 
When I called subroutine `zunik`, I got the error mentioned above.
I created another file `b.f90` with subroutine and created this MRE as mentioned above.

When I'm now running it with the latest main, I'm getting
```console
(scipy-dev) harshita@harshita-linux:~/scipy$ lfortran b.f90 --implicit-typing --implicit-interface --no-warnings
code generation error: Type mismatch in subroutine call, expected `f64[16]`, passed `f64`
    --> b.f90:1311:128
     |
1311 |   CALL ZUNIK(ZRR, ZRI, FN, 2, 0, TOL, INIT(J), PHIR(J), PHII(J), ZETA1R(J), ZETA1I(J), ZETA2R(J), ZETA2I(J), SUMR(J), SUMI(J), CWRKR(1,J), CWRKI(1,J))
     |                                                                                                                                ^^^^^^^^^^ 
```

**Comment by Pranavchiku** [comment]
Ahh, I see this is because of `--legacy-array-sections`. Looks like the way I casted will be. I handled `nD` array to `nD` array, but this is case when we are passing a `1D` array from `2D` array. I will take a look at it.

**Comment by Pranavchiku** [comment]
Minimal code to reproduce:
```fortran
subroutine sub(a)
double precision :: a
dimension :: a(16)
end subroutine

program main
double precision :: a(16,3)
integer :: j
call sub(a(1,j))
end program
```

> LFortran

```cosole
% lfortran a.f90 
code generation error: Type mismatch in subroutine call, expected `f64[16]`, passed `f64`
 --> a.f90:9:10
  |
9 | call sub(a(1,j))
  |          ^^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

> LFortran --legacy-array-sections

```console
% lfortran a.f90 --legacy-array-sections
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2298
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 962
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 347
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8975
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 5037
  File "../libasr/asr.h", line 5013
  File "../libasr/asr.h", line 5038
  File "../libasr/asr.h", line 4747
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 912
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5040
  File "../libasr/asr.h", line 4755
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2993
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5057
  File "../libasr/asr.h", line 4806
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8134
    std::vector<llvm::Value *> args2 = convert_call_args(x, is_method);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7622
    this->visit_expr_wrapper(x.m_args[i].m_value);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4906
    this->visit_expr(*x);
  File "../libasr/asr.h", line 5104
  File "../libasr/asr.h", line 4912
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4846
    visit_ArrayPhysicalCastUtil(tmp, x.m_arg, x.m_type, x.m_type, x.m_old, x.m_new);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4812
    llvm::Type* target_type = llvm_utils->get_type_from_ttype_t_util(m_type, module.get())->getPointerTo();
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1303
    return get_type_from_ttype_t(asr_type, nullptr, m_storage_local, is_array_type_local,
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1144
    LCOMPILERS_ASSERT(ASRUtils::is_fixed_size_array(v_type->m_dims, v_type->n_dims));
AssertFailed: ASRUtils::is_fixed_size_array(v_type->m_dims, v_type->n_dims)
```

**Comment by HarshitaKalani** [comment]
```diff
(lf) harshita@harshita-linux:~/Desktop/lfortran$ git diff
diff --git a/src/lfortran/semantics/ast_body_visitor.cpp b/src/lfortran/semantics/ast_body_visitor.cpp
index a8af12cf0..7216678bd 100644
--- a/src/lfortran/semantics/ast_body_visitor.cpp
+++ b/src/lfortran/semantics/ast_body_visitor.cpp
@@ -2529,8 +2529,16 @@ public:
                                 dims.push_back(al, dim);
                                 ASR::asr_t* descriptor_array = ASR::make_Array_t(al, x.base.base.loc, ASRUtils::type_get_past_array(expected_arg_type),
                                                                 dims.p, dims.size(), ASR::array_physical_typeType::DescriptorArray);
+                                Vec<ASR::dimension_t> dims2;
+                                dims2.reserve(al, 1);
+                                ASR::dimension_t dim2;
+                                dim2.loc = x.base.base.loc;
+                                ASR::Array_t* array_t = ASR::down_cast<ASR::Array_t>(expected_arg_type);
+                                dim2.m_length = array_t->m_dims[0].m_length;
+                                dim2.m_start = nullptr;
+                                dims2.push_back(al, dim2);
                                 ASR::asr_t* expected_array = ASR::make_Array_t(al, x.base.base.loc, ASRUtils::type_get_past_array(expected_arg_type),
-                                                                dims.p, dims.size(), ASRUtils::extract_physical_type(expected_arg_type));
+                                                                dims2.p, dims2.size(), ASRUtils::extract_physical_type(expected_arg_type));
 
                                 // make ArraySection
                                 Vec<ASR::array_index_t> array_indices;
```
This diff makes it work. Thanks to @certik :)

**Comment by HarshitaKalani** [comment]
With this diff, I need to use `--legacy-array-sections` and it works fine
```
(lf) harshita@harshita-linux:~/Desktop/lfortran$ lfortran a.f90 --legacy-array-sections
```
