### ISSUE TITLE
Compiling fortran-primes

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2524]
I think we are quite close on this code:

https://github.com/perazz/fortran-primes

The bugs I noticed:

* [ ] mod
* [ ] `433_IP` (works with `433_ip`), so just a missing `to_lower`

**Comment by Pranavchiku** [comment]
Yes, one more is `trailz` we need to implement. These guys added it today morning.

**Comment by Thirumalai-Shaktivel** [comment]
@Pranavchiku, if you face any blockers, let me know. I can help you!

Great job testing it!

**Comment by Pranavchiku** [comment]
With the following diff I am able to compile `fortran-primes` commit: https://github.com/perazz/fortran-primes/commit/6262b1d65dc40d6391d9667038ecceab8c81bab8 correctly, I have used a workaround for `shifta` which goes as `shifta(n, w) = n / 2**w`, now there is a case where `n` is a 64 bit integer, and `w = 32`, how to handle this, if I do `n / 2**32` it will have arithmetic overflow?

```diff
diff --git a/src/prime_constants.f90 b/src/prime_constants.f90
index aa3262e..eb35b84 100644
--- a/src/prime_constants.f90
+++ b/src/prime_constants.f90
@@ -25,14 +25,14 @@
 module prime_constants
 
     use iso_fortran_env
-    use iso_c_binding, only: c_bool,c_int128_t
+    use iso_c_binding, only: c_bool
 
     implicit none
     public
 
     integer     , parameter :: IP          = int32
     integer     , parameter :: WP          = int64
-    integer     , parameter :: QP          = c_int128_t
+    integer     , parameter :: QP          = int64
     integer     , parameter :: LP          = c_bool
     integer     , parameter :: chunk       = 10000
     integer     , parameter :: N_TABLE     = 5*chunk
diff --git a/src/prime_numbers.f90 b/src/prime_numbers.f90
index b891023..946c6f1 100644
--- a/src/prime_numbers.f90
+++ b/src/prime_numbers.f90
@@ -152,10 +152,18 @@ module prime_numbers
 
     elemental logical function is_prime64(n) result(is_prime)
        integer(WP), intent(in) :: n
-
+       integer :: it
+       logical :: flag
        integer(WP), parameter :: SIMPLE_FACTORS(*) = [3,5,7,11,13,17,19,23]
        integer(IP) :: w
 
+       flag = .false.
+       do it = 1, size(SIMPLE_FACTORS)
+          if (mod(n,SIMPLE_FACTORS(it))==0) then
+             flag = .true.
+          end if
+       end do
+
        if (n<2) then
           is_prime = .false.
        elseif (mod(n,2)==0) then
@@ -164,7 +172,7 @@ module prime_numbers
        elseif (n<N_SMALL) then
           ! Look-up table
           is_prime = odd_min_factor(n)==n
-       elseif (any(mod(n,SIMPLE_FACTORS)==0)) then
+       elseif (flag) then
           ! Very large number. Test simple factors first
           is_prime = .false.
        elseif (n<2_WP**32) then
@@ -178,7 +186,7 @@ module prime_numbers
           else
               w = witnesses_for_64(n)
               is_prime =       is_SPRP64(n,int(iand(w,4095_IP),WP)) &
-                         .and. is_SPRP64(n,int(shifta(w,12_IP),WP))
+                         .and. is_SPRP64(n,int(w / 2**12_IP,WP))
           end if
 
        end if
@@ -189,7 +197,7 @@ module prime_numbers
     elemental integer(WP) function odd_min_factor(n)
        integer(WP), intent(in) :: n
        integer(WP) :: m
-       m = int(min_factor(shifta(n,1)),WP)
+       m = int(min_factor(n / 2**1),WP)
        odd_min_factor = merge(n,m,m==1_IP)
     end function odd_min_factor
 
@@ -239,6 +247,13 @@ module prime_numbers
        end if
     end subroutine quickfind_int
 
+    ! implement btest(n, pos) in Fortran
+      elemental logical(LP) function btest2(n, pos)
+         integer(WP), intent(in) :: n
+         integer(WP), intent(in) :: pos
+         btest2 = iand(n / 2**(-pos),1_WP)==1_WP
+      end function btest2
+
     ! Return number of trailing zeros in the bitwise representation
     elemental integer(WP) function trailing_zeros(n) result(nzero)
        integer(WP), intent(in) :: n
@@ -246,7 +261,7 @@ module prime_numbers
        integer(WP) :: pos
        nzero = 0_WP
        do pos=0,bit_size(n)-1_WP
-           if (btest(n,pos)) return
+           if (btest2(n,pos)) return
            nzero = nzero+1_WP
        end do
     end function trailing_zeros
@@ -265,7 +280,7 @@ module prime_numbers
         ! Find trailing zeros
         do while (iand(d,1_IP)==0)
             s = s+1_IP
-            d = shifta(d,1)
+            d = d / 2**1
         end do
 
         cur = 1_WP
@@ -274,7 +289,7 @@ module prime_numbers
         do while (pw/=0)
             if (iand(pw,1_WP)/=0) cur = mod(cur*aa,n)
             aa = int(mod(int(aa,WP)**2,n),IP)
-            pw = shifta(pw,1)
+            pw = pw / 2**1
         end do
 
         if (cur==1_WP) then
@@ -296,18 +311,18 @@ module prime_numbers
     elemental integer(WP) function witnesses(n)
        integer(WP), intent(in) :: n
        integer(WP) :: i
-       i =      ieor(shifta(n,16), n) * int(z'45d9f3b',WP)
-       i =      ieor(shifta(i,16), i) * int(z'45d9f3b',WP)
-       i = iand(ieor(shifta(i,16), i), 255_WP)
+       i =      ieor(n / 2**16, n) * int(z'45d9f3b',WP)
+       i =      ieor(i / 2**16, i) * int(z'45d9f3b',WP)
+       i = iand(ieor(i / 2**16, i), 255_WP)
        witnesses = int(witnesses32(i+1_WP),WP)
     end function witnesses
 
     elemental integer(IP) function witnesses_for_64(n)
        integer(WP), intent(in) :: n
        integer(WP) :: i
-       i =      ieor(shifta(n,32), n) * int(z'45d9f3b3335b369',WP)
-       i =      ieor(shifta(i,32), i) * int(z'3335b36945d9f3b',WP)
-       i = iand(ieor(shifta(i,32), i), 16383_WP)
+      !  i =      ieor(shifta(n,32), n) * int(z'45d9f3b3335b369',WP)
+      !  i =      ieor(shifta(i,32), i) * int(z'3335b36945d9f3b',WP)
+      !  i = iand(ieor(shifta(i,32), i), 16383_WP)
        witnesses_for_64 = witnesses64(i+1_WP)
     end function witnesses_for_64
 
@@ -322,7 +337,7 @@ module prime_numbers
     elemental integer(IP) function wheel_prime(n)
        integer(IP), intent(in) :: n
        integer(IP) :: d,r
-       d = shifta(n-1,3_IP)
+       d = (n - 1) / 2**3_IP
        r = iand(n-1,7_IP)
        wheel_prime = 30*d+wheel_primes(r+1)
     end function wheel_prime
```

**Comment by certik** [comment]
Do tests run?

**Comment by Pranavchiku** [comment]
Not yet, it shows some assertion error.

**Comment by Pranavchiku** [comment]
With #2533, #2534 diff reduces to
```diff
diff --git a/src/prime_constants.f90 b/src/prime_constants.f90
index aa3262e..eb35b84 100644
--- a/src/prime_constants.f90
+++ b/src/prime_constants.f90
@@ -25,14 +25,14 @@
 module prime_constants
 
     use iso_fortran_env
-    use iso_c_binding, only: c_bool,c_int128_t
+    use iso_c_binding, only: c_bool
 
     implicit none
     public
 
     integer     , parameter :: IP          = int32
     integer     , parameter :: WP          = int64
-    integer     , parameter :: QP          = c_int128_t
+    integer     , parameter :: QP          = int64
     integer     , parameter :: LP          = c_bool
     integer     , parameter :: chunk       = 10000
     integer     , parameter :: N_TABLE     = 5*chunk
diff --git a/src/prime_numbers.f90 b/src/prime_numbers.f90
index 25b023f..4f6ceab 100644
--- a/src/prime_numbers.f90
+++ b/src/prime_numbers.f90
@@ -151,10 +151,19 @@ module prime_numbers
 
     elemental logical function is_prime64(n) result(is_prime)
        integer(WP), intent(in) :: n
+       integer :: it
+       logical :: flag
 
        integer(WP), parameter :: SIMPLE_FACTORS(*) = [3,5,7,11,13,17,19,23]
        integer(IP) :: w
 
+       flag = .false.
+       do it = 1, size(SIMPLE_FACTORS)
+         if (mod(n, SIMPLE_FACTORS(it)) == 0) then
+           flag = .true.
+         end if
+       end do
+
        if (n<2) then
           is_prime = .false.
        elseif (mod(n,2)==0) then
@@ -163,7 +172,7 @@ module prime_numbers
        elseif (n<N_SMALL) then
           ! Look-up table
           is_prime = odd_min_factor(n)==n
-       elseif (any(mod(n,SIMPLE_FACTORS)==0)) then
+       elseif (flag) then
           ! Very large number. Test simple factors first
           is_prime = .false.
        elseif (n<2_WP**32) then
@@ -289,8 +298,8 @@ module prime_numbers
     elemental integer(IP) function witnesses_for_64(n)
        integer(WP), intent(in) :: n
        integer(WP) :: i
-       i =      ieor(shifta(n,32), n) * int(z'45d9f3b3335b369',WP)
-       i =      ieor(shifta(i,32), i) * int(z'3335b36945d9f3b',WP)
+       i =      ieor(shifta(n,32), n) * int(z'45d9f3b',WP)
+       i =      ieor(shifta(i,32), i) * int(z'3335b36',WP)
        i = iand(ieor(shifta(i,32), i), 16383_WP)
        witnesses_for_64 = witnesses64(i+1_WP)
     end function witnesses_for_64
```

**Comment by Pranavchiku** [comment]
How may I run tests, with gfortran I do
```console
% gfortran src/prime_constants.f90 -c
% gfortran src/prime_numbers.f90 -c  
% gfortran ./test/test_primes.f90 
ld: warning: ignoring duplicate libraries: '-lemutls_w', '-lgcc'
ld: Undefined symbols:
  ___prime_numbers_MOD_is_prime32, referenced from:
      _test_is_prime.0 in ccXWSdkg.o
collect2: error: ld returned 1 exit status
```

**Comment by certik** [comment]
You need to link the other files.
```
gfortran -c prime_numbers.f90 -o prime_numbers.o
...
gfortran -o test_primes test_primes.o prime_numbers.o prime_constants.o
```

**Comment by certik** [comment]
With the following diff:
```diff
diff --git a/src/prime_constants.f90 b/src/prime_constants.f90
index aa3262e..eb35b84 100644
--- a/src/prime_constants.f90
+++ b/src/prime_constants.f90
@@ -25,14 +25,14 @@
 module prime_constants
 
     use iso_fortran_env
-    use iso_c_binding, only: c_bool,c_int128_t
+    use iso_c_binding, only: c_bool
 
     implicit none
     public
 
     integer     , parameter :: IP          = int32
     integer     , parameter :: WP          = int64
-    integer     , parameter :: QP          = c_int128_t
+    integer     , parameter :: QP          = int64
     integer     , parameter :: LP          = c_bool
     integer     , parameter :: chunk       = 10000
     integer     , parameter :: N_TABLE     = 5*chunk
diff --git a/src/prime_numbers.f90 b/src/prime_numbers.f90
index c78ec9a..48d403e 100644
--- a/src/prime_numbers.f90
+++ b/src/prime_numbers.f90
@@ -164,9 +164,9 @@ module prime_numbers
        elseif (n<N_SMALL) then
           ! Look-up table
           is_prime = odd_min_factor(n)==n
-       elseif (any(mod(n,SIMPLE_FACTORS)==0)) then
-          ! Very large number. Test simple factors first
-          is_prime = .false.
+!       elseif (any(mod(n,SIMPLE_FACTORS)==0)) then
+!          ! Very large number. Test simple factors first
+!          is_prime = .false.
        elseif (n<2_WP**32) then
           ! Perform Miller-Rabin test
           is_prime = is_prime_32(int(n,IP), int(witnesses(n),IP))
diff --git a/test/test_primes.f90 b/test/test_primes.f90
index 18c0dc2..672b6e8 100644
--- a/test/test_primes.f90
+++ b/test/test_primes.f90
@@ -26,7 +26,7 @@ program test_primes
 
     use prime_numbers
     use prime_constants
-    use iso_fortran_env, only: output_unit
+!    use iso_fortran_env, only: output_unit
 
     implicit none
 
```
I am getting:
```console
$ fpm --compiler=lfortran test          
 + mkdir -p build/dependencies
prime_constants.f90                    done.
FJ32_256.c                             done.
prime_numbers.f90                      done.
libfortran-primes.a                    done.
test_primes.f90                        failed.
[ 83%] Compiling...
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2314
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 933
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 253
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 275
    compiler_options.symtab_only, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 112
    if (res.ok) {
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3307
    b.is_body_visitor = true;
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 217
    visit_ast(*x.m_items[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4848
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4804
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4851
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4438
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1577
    visit_program_unit(*x.m_contains[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4856
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4448
    case program_unitType::Procedure: { v.visit_Procedure((const Procedure_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1903
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 188
    this->visit_stmt(*m_body[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4894
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4540
    case stmtType::Assign: { v.visit_Assign((const Assign_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2170
    ASR::expr_t *target = ASRUtils::EXPR(tmp);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4945
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4596
    case exprType::BoolOp: { v.visit_BoolOp((const BoolOp_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5881
    ASR::expr_t *left = ASRUtils::EXPR(tmp);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4945
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4602
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4843
    bool is_function = true;
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4525
    tmp = create_ArrayAll(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4365
    handle_intrinsic_node_args(x, args, kwarg_names, 1, 2, "all");
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 3754
    this->visit_expr(*x.m_args[i].m_end);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4945
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4601
    case exprType::DefUnaryOp: { v.visit_DefUnaryOp((const DefUnaryOp_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5905
    ASR::expr_t *left = ASRUtils::EXPR(tmp);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4945
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4602
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4843
    bool is_function = true;
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4497
    tmp = create_ArrayPack(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4026
    handle_intrinsic_node_args(x, args, kwarg_names, 2, 3, "pack");
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 3754
    this->visit_expr(*x.m_args[i].m_end);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4945
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4601
    case exprType::DefUnaryOp: { v.visit_DefUnaryOp((const DefUnaryOp_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5911
    current_module_dependencies);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 214
    ASRUtils::expr_value(left))->m_n;
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr.h", line 41
    LCOMPILERS_ASSERT(is_a<T>(*f));
AssertFailed: is_a<T>(*f)
<ERROR> Compilation failed for object " test_test_primes.f90.o "
<ERROR> stopping due to failed compilation
STOP 1
```
This gets quite far!

**Comment by Pranavchiku** [comment]
On applying the following diff

```diff
diff --git a/test/test_primes.f90 b/test/test_primes.f90
index e8f02cb..05bc1b4 100644
--- a/test/test_primes.f90
+++ b/test/test_primes.f90
@@ -26,7 +26,7 @@ program test_primes
 
     use prime_numbers
     use prime_constants
-    use iso_fortran_env, only: output_unit
+    use iso_fortran_env
 
     implicit none
 
@@ -72,8 +72,8 @@ program test_primes
 
         tenthousandth = p1_to_10000(chunk)
 
-        success = all(primes(tenthousandth) == p1_to_10000) .and. &
-                  all(primes(2,tenthousandth) == pack(p1_to_10000,p1_to_10000>=2))
+        ! success = all(primes(tenthousandth) == p1_to_10000) .and. &
+        !           all(primes(2,tenthousandth) == pack(p1_to_10000,p1_to_10000>=2))
 
     end function test_first_10000
 
@@ -176,8 +176,8 @@ program test_primes
 
         do i=1,99999
             call prime_factors(i,factors)
-            success = sign(product(factors(FACTORS_PRIME,:)**factors(FACTORS_POWER,:)),i)==i &
-                      .and. all(is_prime(factors(FACTORS_PRIME,:)))
+            ! success = sign(product(factors(FACTORS_PRIME,:)**factors(FACTORS_POWER,:)),i)==i &
+            !           .and. all(is_prime(factors(FACTORS_PRIME,:)))
             if (.not.success) then
                 print 1, i,factors
                 return
```

```console
LCOMPILERS_ASSERT failed: /Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr_utils.h
function Call_t_body(), line number 4440 at 
ASRUtils::check_equal_type(arg_type, orig_arg_type)
ERROR MESSAGE:
ASRUtils::check_equal_type(i1[:], i32[:])
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2314
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 975
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9062
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 303
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 156
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/subroutine_from_function.cpp", line 349
    u.apply_again = false;
  File "../libasr/asr.h", line 46057
  File "../libasr/asr.h", line 5060
  File "../libasr/asr.h", line 4774
  File "../libasr/asr.h", line 46075
  File "../libasr/asr.h", line 5060
  File "../libasr/asr.h", line 4775
  File "../libasr/asr.h", line 46096
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/subroutine_from_function.cpp", line 309
    visit_stmt(*m_body[i]);
  File "../libasr/asr.h", line 5077
  File "../libasr/asr.h", line 4811
  File "../libasr/asr.h", line 46377
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/subroutine_from_function.cpp", line 309
    visit_stmt(*m_body[i]);
  File "../libasr/asr.h", line 5077
  File "../libasr/asr.h", line 4811
  File "../libasr/asr.h", line 46377
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/subroutine_from_function.cpp", line 309
    visit_stmt(*m_body[i]);
  File "../libasr/asr.h", line 5077
  File "../libasr/asr.h", line 4799
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/subroutine_from_function.cpp", line 337
    }
  File "../libasr/asr.h", line 46283
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/subroutine_from_function.cpp", line 293
    replacer.replace_expr(*current_expr);
  File "../libasr/asr.h", line 45308
  File "../libasr/asr.h", line 44427
  File "../libasr/asr.h", line 45036
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/subroutine_from_function.cpp", line 259
    ASR::stmt_t* subrout_call = ASRUtils::STMT(ASRUtils::make_SubroutineCall_t_util(al, loc,
  File "../libasr/asr_utils.h", line 4486
  File "../libasr/asr_utils.h", line 4468
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x180346a4f
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x180436cbf
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x180465a23
Abort: Signal SIGABRT (abort) received

test_script.sh: line 4:  4831 Abort trap: 6           lfortran -c ./test/test_primes.f90 -o test_primes.o
```

**Comment by Pranavchiku** [comment]
This is weird, I am not sure why this error is there. There is no use of `shape` intrinsic in codebase yet LFortran is somehow creating an ASR node for it through intrinsic_functions pass which screws up type of argument passed.

**Comment by certik** [comment]
As usual, let's create a minimal reproducible example and then you can dump all ASR passes and see which one introduced the broken ASR.

**Comment by jinangshah21** [comment]
Steps to compile it: 
**1) Install fpm**
```
 git clone https://github.com/fortran-lang/fpm.git
cd fpm 
./install.sh
```
Export path in `.bashrc`
**2) Compile with Gfortran**
```
fpm --compiler=gfortran test
```
**3) Compile with LFortran** 
```
fpm --compiler=lfortran test
```


Currently with following diff:
```diff
--- a/src/prime_constants.f90
+++ b/src/prime_constants.f90
@@ -25,14 +25,14 @@
 module prime_constants
 
     use iso_fortran_env
-    use iso_c_binding, only: c_bool,c_int128_t
+    use iso_c_binding, only: c_bool
 
     implicit none
     public
 
     integer     , parameter :: IP          = int32
     integer     , parameter :: WP          = int64
-    integer     , parameter :: QP          = c_int128_t
+    integer     , parameter :: QP          = int64
     integer     , parameter :: LP          = c_bool
     integer     , parameter :: chunk       = 10000
     integer     , parameter :: N_TABLE     = 5*chunk
```


**LFortran** :
```console
[66%]
...........................................................
code generation error: asr_to_llvm: module failed verification. Error:
Both operands to a binary operator are not of the same type!
  %25 = ashr i64 %24, i32 1
Both operands to a binary operator are not of the same type!
  %11 = ashr i64 %9, i32 %10
Both operands to a binary operator are not of the same type!
  %65536 = ashr i64 %65535, i32 1
Both operands to a binary operator are not of the same type!
  %1 = ashr i64 %0, i32 16
Both operands to a binary operator are not of the same type!
  %5 = ashr i64 %4, i32 16
Both operands to a binary operator are not of the same type!
  %9 = ashr i64 %8, i32 16
Both operands to a binary operator are not of the same type!
  %1 = ashr i64 %0, i32 32
Both operands to a binary operator are not of the same type!
  %5 = ashr i64 %4, i32 32
Both operands to a binary operator are not of the same type!
  %9 = ashr i64 %8, i32 32
```

**GFortran** :
Compiles well but 1 test fails, due to above diff.


So there are cases where 128 bit is used we need to ignore them for now. Try to remove code till what the same error can be reproduce and we can fix bugs other than issue of 128 bits
