### ISSUE TITLE
[fortran-primes]: semantic error: mask argument to any must be an array and must not be a scalar

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#2529]
```fortran
program main
integer, parameter :: SIMPLE_FACTORS(*) = [3,5,7,11,13,17,19,23]
integer :: n
if(any(mod(n,SIMPLE_FACTORS)==0)) error stop
end program
```

> LFortran

```console
% lfortran a.f90                  
semantic error: mask argument to any must be an array and must not be a scalar
 --> a.f90:4:8
  |
4 | if(any(mod(n,SIMPLE_FACTORS)==0)) error stop
  |        ^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.

```

**Comment by Thirumalai-Shaktivel** [comment]
I think the mod function must be replaced with the ArrayBroadcast node and later handled in array_op pass.

**Comment by certik** [comment]
I think `mod` is elemental, so it is like `sin` in this respect.

**Comment by Thirumalai-Shaktivel** [comment]
Oh yea!
We haven't tried handling elemental in IntrinsicFunction. If we recognise one of the arguments as an array, we will define it as an elemental function

**Comment by certik** [comment]
Yes. I think we should eventually rework the elemental handling with explicit node, probably "map", that maps the scalar function to the array. Similar to Broadcast. But we don't currently have a way of passing the intrinsic function to "map". So some more design is needed in this respect.

**Comment by HarshitaKalani** [comment]
This works now. 
```fortran
program main
	integer, parameter :: SIMPLE_FACTORS(*) = [3,5,7,11,13,17,19,23]
	integer :: n
	n = 1
	print *, mod(n,SIMPLE_FACTORS)
	print *, any(mod(n,SIMPLE_FACTORS)==0)
	if(any(mod(n,SIMPLE_FACTORS)==0)) error stop
end program
```
```console
$ gfortran b.f90 && ./a.out
           1           1           1           1           1           1           1           1
 F
$ lfortran b.f90
1    1    1    1    1    1    1    1
F
```

**Comment by certik** [comment]
The original code still gives:
```console
$ lfortran b.f90 
ERROR STOP
```

**Comment by HarshitaKalani** [comment]
That is because n is unitialised.
```console
$ gfortran a.f90 && ./a.out
ERROR STOP 

Error termination. Backtrace:
#0  0x7fc9ff623960 in ???
#1  0x7fc9ff6244d9 in ???
#2  0x7fc9ff625b47 in ???
#3  0x621a2a4642ea in ???
#4  0x621a2a464330 in ???
#5  0x7fc9ff229d8f in __libc_start_call_main
	at ../sysdeps/nptl/libc_start_call_main.h:58
#6  0x7fc9ff229e3f in __libc_start_main_impl
	at ../csu/libc-start.c:392
#7  0x621a2a4640c4 in ???
#8  0xffffffffffffffff in ???

```

**Comment by certik** [comment]
Good catch. Let's add a test where everything is initialized and close this issue?
