### ISSUE TITLE
AST->ASR: std::out_of_range: stoi: out of range

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2545]
In the `fortran-primes` project:

```console
$ lfortran -c ././src/prime_numbers.f90   -J build/lfortran_00811D69250C8F7F -Ibuild/lfortran_00811D69250C8F7F -o build/lfortran_00811D69250C8F7F/fortran-primes/src_prime_numbers.f90.o
libc++abi: terminating with uncaught exception of type std::out_of_range: stoi: out of range
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2314
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 933
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 253
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 275
    compiler_options.symtab_only, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 112
    if (res.ok) {
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3307
    b.is_body_visitor = true;
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 217
    visit_ast(*x.m_items[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4848
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4804
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4851
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4436
    case modType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1516
    visit_program_unit(*x.m_contains[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4856
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4448
    case program_unitType::Procedure: { v.visit_Procedure((const Procedure_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1903
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 188
    this->visit_stmt(*m_body[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4894
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4540
    case stmtType::Assign: { v.visit_Assign((const Assign_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2170
    ASR::expr_t *target = ASRUtils::EXPR(tmp);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4945
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4596
    case exprType::BoolOp: { v.visit_BoolOp((const BoolOp_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5764
    ASR::expr_t *left = ASRUtils::EXPR(tmp);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4945
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4602
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5025
    visit_expr_list(x.m_args, x.n_args, args);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 6094
    this->visit_expr(*ast_list[i].m_end);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4945
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4611
    case exprType::Substring: { v.visit_Substring((const Substring_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5950
    int boz_int = std::stoi(boz_str, nullptr, base);
  Binary file "/usr/lib/libc++.1.dylib", local address: 0x1802636e7
  Binary file "/usr/lib/libc++abi.dylib", local address: 0x1802cbc07
  Binary file "/usr/lib/libc++abi.dylib", local address: 0x1802cbc5b
  Binary file "/usr/lib/libc++abi.dylib", local address: 0x1802c8ee3
  Binary file "/usr/lib/libobjc.A.dylib", local address: 0x1801b214f
  Binary file "/usr/lib/libc++abi.dylib", local address: 0x1802baf4b
  Binary file "/usr/lib/libc++abi.dylib", local address: 0x1802c9b4f
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18024a313
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x18030ceaf
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Abort: Signal SIGABRT (abort) received

zsh: abort      lfortran -c ././src/prime_numbers.f90 -J build/lfortran_00811D69250C8F7F  -o 
```

In order to get this stacktrace, I had to do:
```diff
--- a/src/bin/lfortran.cpp
+++ b/src/bin/lfortran.cpp
@@ -2384,9 +2384,6 @@ int main(int argc, char *argv[])
     } catch(const std::exception &e) {
         std::cerr << "std::exception: " << e.what() << std::endl;
         return 1;
-    } catch(...) {
-        std::cerr << "Unknown Exception" << std::endl;
-        return 1;
     }
     return 0;
 }
```

**Comment by certik** [comment]
Weird, I tried doing:
```diff
--- a/src/lfortran/semantics/ast_common_visitor.h
+++ b/src/lfortran/semantics/ast_common_visitor.h
@@ -5947,7 +5947,13 @@ public:
                                 x.base.base.loc);
         }
         std::string boz_str = s.substr(2, s.size() - 2);
-        int boz_int = std::stoi(boz_str, nullptr, base);
+        int boz_int;
+        try {
+            boz_int = std::stoi(boz_str, nullptr, base);
+        } catch (std::out_of_range const& e) {
+            throw SemanticError("The integer is out of range for singed 64bit int",
+                                x.base.base.loc);
+        }
         tmp = ASR::make_IntegerBOZ_t(al, x.base.base.loc, boz_int,
                                 boz_type, nullptr);
     }
```
But it does not catch the `std::out_of_range` exception. I have no idea why.

**Comment by certik** [comment]
I think we need to use:
```diff
--- a/src/lfortran/semantics/ast_common_visitor.h
+++ b/src/lfortran/semantics/ast_common_visitor.h
@@ -5947,7 +5947,7 @@ public:
                                 x.base.base.loc);
         }
         std::string boz_str = s.substr(2, s.size() - 2);
-        int boz_int = std::stoi(boz_str, nullptr, base);
+        int64_t boz_int = std::stoll(boz_str);
         tmp = ASR::make_IntegerBOZ_t(al, x.base.base.loc, boz_int,
                                 boz_type, nullptr);
     }
```
But we need to handle the base correctly and also check for errors.

**Comment by certik** [comment]
https://github.com/lfortran/lfortran/pull/2546 fixes this issue for me. We should still add a test, so I'll keep this issue open until we add a test.

**Comment by Pranavchiku** [comment]
I created a test that fails and PR fixes it, pushed it on PR. Here is the test:

```fortran
module fortran_primes_01_module
   use iso_fortran_env

   implicit none

   integer, parameter :: IP = int32  ! Integer kind parameter for 32-bit integers
   integer, parameter :: WP = int64  ! Integer kind parameter for 64-bit integers
end module fortran_primes_01_module

elemental function witnesses_for_64(n) result(i)
   use fortran_primes_01_module
   implicit none
   integer(WP), intent(in) :: n  ! Input integer with kind parameter WP
   integer(WP) :: i             ! Output integer with kind parameter WP

   ! Compute the number of Miller-Rabin witnesses for n using bitwise XOR, left shift, and multiplication
   i = ieor(shifta(n, 32_WP), n) * int(z'45d9f3b3335b369', WP)

end function witnesses_for_64

program fortran_primes_01
   use fortran_primes_01_module
   implicit none
   integer(WP) :: n, i
   
   interface
      function witnesses_for_64(n) result(i)
         use fortran_primes_01_module
         implicit none
         integer(WP), intent(in) :: n
         integer(WP) :: i
      end function witnesses_for_64
   end interface

   n = 2_WP  ! Set n to 2 (with kind parameter WP)

   i = witnesses_for_64(n)
   print *, i
   if (i /= 629165251193693906_WP) error stop

end program

```

**Comment by certik** [comment]
Thanks @Pranavchiku. The test is there, I can verify that this is now fixed.
