### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2606]
Tests fail for me in the latest main (1b3204f3b1f0af9540808ad53d2a64a2ce84e088) on Apple M1 Max:
```console
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/./run_tests.py", line 431, in <module>
    tester_main("LFortran", single_test)
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/compiler_tester/tester.py", line 446, in tester_main
    for f in futures:
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ondrej/repos/lfortran/lfortran/./run_tests.py", line 205, in single_test
    run_test(
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/compiler_tester/tester.py", line 330, in run_test
    raise RunException(
compiler_tester.tester.RunException: Testing with reference output failed.
../integration_tests/template_add_01b.f90 * asr
The JSON metadata differs against reference results
Reference JSON: tests/reference/asr-template_add_01b-bd911f4.json
Output JSON:    tests/output/asr-template_add_01b-bd911f4.json
Omitting 10 identical items
Differing items:
{'stdout_hash': 'd14a028c2a3a2bc9476102bb288234c415a2b01f828ea62ac5b3e42f'} != {'stdout_hash': '9d1da10d3efca7211238099d4180e3049452e7c99aa6ca920827edb9'}
Diff against: tests/reference/asr-template_add_01b-bd911f4.stdout
```
However it's hard to reproduce. It often works, but sometimes it fails. After a few reruns, I also got this error:
```
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/./run_tests.py", line 431, in <module>
    tester_main("LFortran", single_test)
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/compiler_tester/tester.py", line 446, in tester_main
    for f in futures:
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ondrej/repos/lfortran/lfortran/./run_tests.py", line 205, in single_test
    run_test(
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/compiler_tester/tester.py", line 296, in run_test
    do = json.load(open(jo))
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Pranavchiku** [comment]
It works for me:

```console
% ./run_tests.py
.....
parser/program_without_line_03.f90 * ast ✓ 
 START TEST:  errors/runtime_stacktrace_01.f90
external1.f90 * asr ✓ 
 START TEST:  ../integration_tests/legacy_array_sections_01.f90
errors/subroutine1.f90 * asr ✓ 
../integration_tests/data_implied_do_01.f90 * asr ✓ 
../integration_tests/implicit_argument_casting_01.f90 * asr ✓ 
external2.f90 * asr ✓ 
errors/subroutine3.f90 * asr ✓ 
errors/implicit_typing4.f90 * asr ✓ 
errors/subroutine2.f90 * asr ✓ 
errors/end_sub_name.f90 * asr ✓ 
errors/end_program_name.f90 * asr ✓ 
pragma2.f90 * asr_ignore_pragma ✓ 
../integration_tests/legacy_array_sections_01.f90 * llvm ✓ 
pragma2.f90 * c ✓ 
errors/runtime_stacktrace_01.f90 * run_dbg ✓ 
TESTS PASSED
```

**Comment by certik** [comment]
You have to run it about 10x times. However with https://github.com/lfortran/lfortran/pull/2607 I can't reproduce it anymore so far.

**Comment by certik** [comment]
Weird, I am getting the following hashes:
```
$ shasum -a 224 -b tests/output/asr-template_add_01b-bd911f4.stdout tests/reference/asr-template_add_01b-bd911f4.stdout
9d1da10d3efca7211238099d4180e3049452e7c99aa6ca920827edb9 *tests/output/asr-template_add_01b-bd911f4.stdout
9d1da10d3efca7211238099d4180e3049452e7c99aa6ca920827edb9 *tests/reference/asr-template_add_01b-bd911f4.stdout
$ ipython
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:38:29) [Clang 13.0.1 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import hashlib

In [2]: temp = open("tests/output/asr-template_add_01b-bd911f4.stdout", "rb").re
   ...: ad()

In [4]: hashlib.sha224(temp).hexdigest()
Out[4]: '9d1da10d3efca7211238099d4180e3049452e7c99aa6ca920827edb9'
```
This agrees with the second hash.

**Comment by Shaikh-Ubaid** [comment]
I have experienced this flaky behaviour in one of my CI runs some days back.
