### ISSUE TITLE
dftatom `--fast`: Unsupported type in `where.cpp`

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2636]
```console
lfortran --fast -I../../src -c conv_lda.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2315
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 975
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9106
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 304
    apply_passes(al, asr, _with_optimization_passes, pass_options,
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 158
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/where.cpp", line 344
    WhereVisitor v(al, assignment_hash, return_var_hash);
  File "../libasr/asr.h", line 39817
  File "../libasr/asr.h", line 5060
  File "../libasr/asr.h", line 4774
  File "../libasr/asr.h", line 39835
  File "../libasr/asr.h", line 5060
  File "../libasr/asr.h", line 4775
  File "../libasr/pass/pass_utils.h", line 212
  File "../libasr/pass/pass_utils.h", line 157
  File "../libasr/asr.h", line 5077
  File "../libasr/asr.h", line 4811
  File "../libasr/asr.h", line 40047
  File "../libasr/pass/pass_utils.h", line 157
  File "../libasr/asr.h", line 5077
  File "../libasr/asr.h", line 4826
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/where.cpp", line 279
    throw LCompilersException("Unsupported type");
LCompilersException: Unsupported type
make[2]: *** [conv_lda.o] Error 1
make[1]: *** [all] Error 2
make: *** [all] Error 2
```

**Comment by Thirumalai-Shaktivel** [comment]
Should I make any other changes apart from this to run dftatom in `Release mode`?
```diff
diff --git a/Makefile.manual b/Makefile.manual
index 78a45b2..8c028c8 100644
--- a/Makefile.manual
+++ b/Makefile.manual
@@ -2,7 +2,7 @@
 
 # GFortran
 F90 = lfortran
-F90FLAGS =
+F90FLAGS = --fast
 # F90 = gfortran
 # F90FLAGS = -Wall -std=f95 -Wextra -Wimplicit-interface -fPIC
 # Debug flags:
```

Making the above changes freezes while compiling conv_lda:
```
cd lda; make -f Makefile.manual
lfortran --fast -I../../src -c conv_lda.f90
^Cmake[2]: *** [conv_lda.o] Interrupt: 2
make[1]: *** [all] Interrupt: 2
make: *** [all] Interrupt: 2
```

**Comment by Thirumalai-Shaktivel** [comment]
Adding `--skip-pass=inline_function_calls` works.

**Comment by Thirumalai-Shaktivel** [comment]
This seems to be fixed!

**Comment by certik** [comment]
Yes, I think this is fixed and tested at the CI here: https://github.com/lfortran/lfortran/blob/3dd5707e87c7cd5b9586c0754ac34e79a329d127/.github/workflows/CI.yml#L479.
