### ISSUE TITLE
calling external function as subroutine argument throws internal compiler error

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#2748]
```fortran
double precision function f(x)
  double precision x
  f = x**2
  return
end function f

subroutine sub(f)
  external f
  double precision f
  print *, f(2.0d0)
  return
end subroutine sub

recursive subroutine a()
external f 
call sub(f)
end

program main
  call a()
end
```
```console
$ gfortran b.f90 && ./a.out
   4.0000000000000000     
$ lfortran b.f90  --implicit-typing --implicit-interface --generate-object-code --use-loop-variable-after-loop  --legacy-array-sections
Internal Compiler Error: Unhandled exception
^C
```
Ref: https://github.com/lfortran/lfortran/issues/2714

**Comment by Pranavchiku** [comment]
```console
% lfortran a.f90 --implicit-interface --implicit-typing
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2320
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 935
    res = fe.get_llvm3(*asr, lpm, lm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 358
    = asr_to_llvm(asr, diagnostics,
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9219
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 5057
  File "../libasr/asr.h", line 5033
  File "../libasr/asr.h", line 5058
  File "../libasr/asr.h", line 4766
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 938
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5060
  File "../libasr/asr.h", line 4775
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3673
    visit_procedures(x);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3870
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5077
  File "../libasr/asr.h", line 4825
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8387
    std::vector<llvm::Value *> args2 = convert_call_args(x, is_method);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7869
    LCOMPILERS_ASSERT(llvm_symtab_fn_arg.find(h) != llvm_symtab_fn_arg.end());
AssertFailed: llvm_symtab_fn_arg.find(h) != llvm_symtab_fn_arg.end()
```

**Comment by Pranavchiku** [comment]
This looks similar to https://github.com/lfortran/lfortran/issues/2427

**Comment by HarshitaKalani** [comment]
Yes, they are indeed the same.

**Comment by HarshitaKalani** [comment]
I feel https://github.com/lfortran/lfortran/issues/1977 is similar too.

**Comment by Pranavchiku** [comment]
This works perfectly with #2800.
