### ISSUE TITLE
Generics: matrix example

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2814]
The code is at: https://github.com/j3-fortran/generics/tree/68e2cb849f5e84bc468c4dae0f8b34c6ea4d2432/updated_examples/matrix

See the README for the order, it's a set of modules that build on top of each other. The first one seems to work, the second one currently fails:

One can compile using:
```console
$ lfortran -c semigroup_m.f90 -o semigroup_m.o
$ lfortran -c monoid_m.f90 -o monoid_m.o  
ASR verify pass error: ASR verify: The Requirement::m_symtab->parent is not the right parent
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2272
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 888
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 253
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 275
    compiler_options.symtab_only, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 98
    if (res.ok) {
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 3359
    v.visit_TranslationUnit(ast);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 130
    visit_ast(*x.m_items[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4848
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4804
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4851
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4436
    case modType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 479
    visit_ModuleSubmoduleCommon<AST::Module_t, ASR::Module_t>(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 432
    visit_unit_decl1(*x.m_use[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4860
    void visit_unit_decl1(const unit_decl1_t &b) { visit_unit_decl1_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4456
    switch (x.type) {
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 2504
    t = (ASR::symbol_t*)(ASRUtils::load_module(al, tu_symtab,
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_utils.cpp", line 308
    *symtab, intrinsic, pass_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_utils.cpp", line 456
    ASR::TranslationUnit_t *asr = load_modfile(al, modfile, false, symtab);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/modfile.cpp", line 94
    ASR::asr_t *asr = deserialize_asr(al, asr_binary, load_symtab_id, symtab);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast_serialization.cpp", line 388
    Line not found
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast_serialization.cpp", line 406
    Line not found
LCompilersException: Verify failed
```

I used the following workarounds:
```diff
diff --git a/updated_examples/matrix/monoid_m.f90 b/updated_examples/matrix/monoid_m.f90
index 492caac..71ef1a6 100644
--- a/updated_examples/matrix/monoid_m.f90
+++ b/updated_examples/matrix/monoid_m.f90
@@ -8,15 +8,15 @@ module monoid_m
     public :: monoid, extended_monoid, derive_extended_monoid
 
     requirement monoid(T, combine, empty)
-        requires semigroup(T, combine)
+        require :: semigroup(T, combine)
         pure function empty()
             type(T) :: empty
         end function
     end requirement
 
     requirement extended_monoid(T, combine, sconcat, stimes, empty, mconcat)
-        requires extended_semigroup(T, combine, sconcat, stimes)
-        requires monoid(T, combine, empty)
+        require :: extended_semigroup(T, combine, sconcat, stimes)
+        require :: monoid(T, combine, empty)
         pure function mconcat(list) result(combined)
             type(T), intent(in) :: list(:)
             type(T) :: combined
@@ -24,16 +24,15 @@ module monoid_m
     end requirement
 
     template derive_extended_monoid(T, combine, empty)
-        requires monoid(T, combine, empty)
+        require :: monoid(T, combine, empty)
 
         private
         public :: stimes, mconcat
 
         instantiate derive_extended_semigroup(T, combine), only: stimes
 
-        generic :: mconcat => mconcat_
     contains
-        pure function mconcat_(list) result(combined)
+        pure function mconcat(list) result(combined)
             type(T), intent(in) :: list(:)
             type(T) :: combined
 diff --git a/updated_examples/matrix/semigroup_m.f90 b/updated_examples/matrix/semigroup_m.f90
index eff1097..505c63a 100644
--- a/updated_examples/matrix/semigroup_m.f90
+++ b/updated_examples/matrix/semigroup_m.f90
@@ -19,7 +19,7 @@ module semigroup_m
     end requirement
 
     requirement extended_semigroup(T, combine, sconcat, stimes)
-        requires semigroup(T, combine)
+        require :: semigroup(T, combine)
         pure function sconcat(list) result(combined)
             type(T), intent(in) :: list(:) !! Must contain at least one element
             type(T) :: combined
@@ -32,15 +32,13 @@ module semigroup_m
     end requirement
 
     template derive_extended_semigroup(T, combine)
-        requires semigroup(T, combine)
+        require :: semigroup(T, combine)
 
         private
         public :: sconcat, stimes
 
-        generic :: sconcat => sconcat_
-        generic :: stimes => stimes_
     contains
-        pure function sconcat_(list) result(combined)
+        pure function sconcat(list) result(combined)
             type(T), intent(in) :: list(:)
             type(T) :: combined
 
@@ -56,7 +54,7 @@ module semigroup_m
             end if
         end function
 
-        elemental function stimes_(n, a) result(repeated)
+        elemental function stimes(n, a) result(repeated)
             integer, intent(in) :: n
             type(T), intent(in) :: a
             type(T) :: repeated
```

**Comment by certik** [comment]
Issues to fix:

High priority:

* [ ] https://github.com/lfortran/lfortran/issues/3138

Low priority:

* [ ] generic :: sconcat => sconcat_
