### ISSUE TITLE
Segmentation fault during compilation

### ISSUE THREAD

**Issue by robintw** [lfortran/lfortran#2823]
I am trying to compile some very old Fortran 66 code. I am running this command:

```
lfortran --fixed-form-infer  --implicit-interface -o ABSTRA.o ABSTRA.f
```

and I get this output:

```
[1]    99039 segmentation fault  lfortran --fixed-form-infer --implicit-interface -o ABSTRA.o ABSTRA.f
```

The source file I am compiling is from a model of atmospheric radiative transfer, and the code is freely available - so I've put a copy of that file [here](https://gist.github.com/robintw/a142ceb3dd0020f3a0fdbc62b5255965) if you'd like to have a go at compiling it yourself.

LFortran was installed from conda-forge and the output of `lfortran --version` is:

```
LFortran version: 0.29.0
Platform: macOS ARM
Default target: arm64-apple-darwin21.6.0
```

I'm not very good at debugging segfaults, but happy to do any debugging work you'd like me to do.

**Comment by certik** [comment]
Thanks for the bug report!

I got this:
```console
$ lfortran ABSTRA.f --fixed-form --implicit-typing                     
semantic error: Function 'z' not found or not implemented yet (if it is intrinsic)
  --> ABSTRA.f:32:25
   |
32 |       common /sixs_atm/ z(34),p(34),t(34),wh(34),wo(34)
   |                         ^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
I think we don't yet have a full implementation of a common block.

And with your options:
```console
$ lfortran ABSTRA.f --fixed-form --implicit-typing --implicit-interface
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2307
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 888
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 253
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 275
    compiler_options.symtab_only, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 98
    if (res.ok) {
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 3359
    v.visit_TranslationUnit(ast);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 130
    visit_ast(*x.m_items[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4848
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4805
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4856
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4447
    case program_unitType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 945
    visit_unit_decl2(*x.m_decl[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4862
    void visit_unit_decl2(const unit_decl2_t &b) { visit_unit_decl2_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4465
    case unit_decl2Type::Declaration: { v.visit_Declaration((const Declaration_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1487
    visit_DeclarationUtil(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 1926
    populate_common_dictionary(x, common_block_struct_sym, struct_type, common_block_name, i);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 1577
    ASR::Variable_t* var_ = extract_common_variable(expr, x.base.base.loc, s.loc);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 1566
    var_ = ASRUtils::EXPR2VAR(ASRUtils::EXPR(tmp));
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_utils.h", line 214
    ASR::down_cast<ASR::Var_t>(f)->m_v));
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr.h", line 41
    LCOMPILERS_ASSERT(is_a<T>(*f));
AssertFailed: is_a<T>(*f)
```
I am guessing it's treating the `z(34)` as an implicit function instead of an array, and our preliminary common block implementation fails.
