### ISSUE TITLE
Deferred type-bound procedure with nopass attribute leads to LFortran core dump

### ISSUE THREAD

**Issue by difference-scheme** [lfortran/lfortran#2880]
The following example code fails to compile with LFortran (while it does compile with ifort):
```
module test

   type, abstract :: abstract_type
   contains
      procedure(integer_method), deferred, nopass :: integer_method
   end type abstract_type

   abstract interface
      function integer_method() result(n)
         integer :: n
      end function integer_method
   end interface

   type :: Wrapper
      class(abstract_type),  allocatable :: obj 
   contains
      procedure :: caller
   end type Wrapper
   
contains
   
   subroutine caller(self)
      class(Wrapper), intent(in)  :: self
      integer :: n
      n = self%obj%integer_method()
   end subroutine caller

end module test

```
Here's LFortran's output:
```
LCOMPILERS_ASSERT failed: /home/knk/Github/lfortran/src/libasr/asr.h
function down_cast(), line number 40 at 
f != nullptr
Aborted (core dumped)

```
I've run repeatedly into this bug trying to compile a modern Fortran code base that makes use of OOP. The problem is connected to the `nopass` attribute. If `integer_method` is declared with a (redundant) passed-object dummy argument, then the code compiles.

**Comment by certik** [comment]
Thanks for the bug report, I can reproduce it with the latest main as well. Here is a full stacktrace:
```console
$ lfortran --show-asr a.f90 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2268
    return emit_asr(arg_file, lfortran_pass_manager,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 632
    r = fe.get_asr2(input, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 253
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 275
    compiler_options.symtab_only, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 128
    if (res.ok) {
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3407
    b.is_body_visitor = true;
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 142
    visit_ast(*x.m_items[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4848
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4804
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4851
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4436
    case modType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1457
    visit_program_unit(*x.m_contains[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4856
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4447
    case program_unitType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1909
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 113
    this->visit_stmt(*m_body[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4894
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4540
    case stmtType::Assign: { v.visit_Assign((const Assign_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2241
    ASR::expr_t *target = ASRUtils::EXPR(tmp);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4945
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4602
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5288
    tmp = create_ClassProcedure(x.base.base.loc, x.m_args, x.n_args, v, v_expr); break;
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 3508
    ASRUtils::set_absent_optional_arguments_to_null(args, func, al, v_expr);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_utils.h", line 2416
    *ASR::down_cast<ASR::Var_t>(func->m_args[i + offset])->m_v) ) {
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr.h", line 40
    LCOMPILERS_ASSERT(f != nullptr);
AssertFailed: f != nullptr
```
