### ISSUE TITLE
Unhandled exception with external libblas subroutine

### ISSUE THREAD

**Issue by ettaka** [lfortran/lfortran#2924]
I tried with the snippet here: https://fortran-lang.discourse.group/t/how-many-blas-libraries-have-this-error/4454

gfortran:
```
(lf) ➜  test_blas gfortran test_blas.f90 -lblas -o test_blas
(lf) ➜  test_blas ./test_blas                               
wp kind=4 sdot=15.000 snrm2=5.000
wp kind=8 sdot=.000 snrm2=5.000
```
lfortran:
```
(lf) ➜  test_blas lfortran test_blas.f90 -lblas -o test_blas
semantic error: function interface must be specified explicitly; you can enable implicit interfaces with `--implicit-interface`
 --> test_blas.f90:7:28
  |
7 |      real(wp), external :: sdot, snrm2
  |                            ^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
If we add `--implicit-interface` (https://github.com/lfortran/lfortran/issues/1170#issuecomment-1377809323):
```
(lf) ➜  test_blas lfortran test_blas.f90 -lblas --implicit-interface -o test_blas
Internal Compiler Error: Unhandled exception
BFD: DWARF error: section .debug_info is larger than its filesize! (0x93ef57 vs 0x530ea0)
Traceback (most recent call last):
  Binary file "/home/eelis/git/lfortran/src/bin/lfortran", in _start()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_start_main()
  File "/home/eelis/git/lfortran/src/bin/lfortran.cpp", line 2357, in ??
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/eelis/git/lfortran/src/bin/lfortran.cpp", line 917, in ??
    result = fe.get_asr2(input, lm, diagnostics);
  File "/home/eelis/git/lfortran/src/lfortran/fortran_evaluator.cpp", line 253, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::al
locator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/home/eelis/git/lfortran/src/lfortran/fortran_evaluator.cpp", line 275, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag:
:Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/home/eelis/git/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 127, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompile
rs::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    instantiate_types, instantiate_symbols, entry_functions, entry_function_arguments_mapping, data_structure);
  File "/home/eelis/git/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3334, in LCompilers::LFortran::body_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&,
 LCompilers::diag::Diagnostics&, LCompilers::ASR::asr_t*, LCompilers::CompilerOptions&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::all
ocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_strin
g<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx1
1::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >
 >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompil
ers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_str
ing<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, st
d::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, s
td::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR
::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>,
 std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_t
raits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std:
:__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char,
 std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<s
td::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigne
d int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_tr
aits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > 
>&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, st
d::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char
> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCom
pilers::LFortran::AST::stmt_t*> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<
char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AS
T::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<st
d::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > 
> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char,
 std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::a
llocator<int> > > > >&, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> >&)
    b.visit_TranslationUnit(ast);
  File "/home/eelis/git/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 142, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::Translatio
nUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/eelis/git/lfortran/src/lfortran/ast.h", line 4848, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t 
const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/eelis/git/lfortran/src/lfortran/ast.h", line 4805, in ??
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/home/eelis/git/lfortran/src/lfortran/ast.h", line 4851, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t 
const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/home/eelis/git/lfortran/src/lfortran/ast.h", line 4439, in ??
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/eelis/git/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1515, in LCompilers::LFortran::BodyVisitor::visit_Program(LCompilers::LFortran::AST::Program_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/eelis/git/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 113, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&,
 unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/eelis/git/lfortran/src/lfortran/ast.h", line 4894, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_
t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/eelis/git/lfortran/src/lfortran/ast.h", line 4576, in ??
    case stmtType::Block: { v.visit_Block((const Block_t &)x); return; }
  File "/home/eelis/git/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 84, in LCompilers::LFortran::BodyVisitor::visit_Block(LCompilers::LFortran::AST::Block_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/eelis/git/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 113, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&,
 unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/eelis/git/lfortran/src/lfortran/ast.h", line 4894, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_
t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/eelis/git/lfortran/src/lfortran/ast.h", line 4541, in ??
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/home/eelis/git/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2242, in LCompilers::LFortran::BodyVisitor::visit_Assignment(LCompilers::LFortran::AST::Assignment_t c
onst&)
    this->visit_expr(*x.m_value);
  File "/home/eelis/git/lfortran/src/lfortran/ast.h", line 4945, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_expr(LCompilers::LFortran::AST::expr_
t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/eelis/git/lfortran/src/lfortran/ast.h", line 4603, in ??
    case exprType::FuncCallOrArray: { v.visit_FuncCallOrArray((const FuncCallOrArray_t &)x); return; }
  File "/home/eelis/git/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5382, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_FuncCallOrArray
(LCompilers::LFortran::AST::FuncCallOrArray_t const&)
    tmp = create_FunctionCallWithASTNode(x, v, args);
  File "/home/eelis/git/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 3792, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_FunctionCallWi
thASTNode(LCompilers::LFortran::AST::FuncCallOrArray_t const&, LCompilers::ASR::symbol_t*, LCompilers::Vec<LCompilers::ASR::call_arg_t>&)
    return create_Function(x.base.base.loc, args, v);
  File "/home/eelis/git/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 3748, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_Function(LComp
ilers::Location const&, LCompilers::Vec<LCompilers::ASR::call_arg_t>&, LCompilers::ASR::symbol_t*)
    ASRUtils::set_absent_optional_arguments_to_null(args, func, al);
AssertFailed: args.size() + offset == (func->n_args)
```

**Comment by Pranavchiku** [comment]
I am able to reproduce it.

**Comment by ettaka** [comment]
@Pranavchiku if I try to compile without the `block`, I get 'undefined symbol' error when linking. Even if I have `-lblas` as a flag to lfortran. With `gfortran` it works as expected. Can you confirm?

**Comment by certik** [comment]
@ettaka You can also treat `sdot` as a C function and link any blas you want. However then there are issues with underscore mangling, and we have options to deal with that too.

The recommended approach is to use `iso_c_binding` and provide a proper interface to your C function (`sdot`), then everything will work out of the box.

I do not recommend to use implicit typing or implicit interfaces.
