### ISSUE TITLE
Typed allocation for derived types isn't recognized

### ISSUE THREAD

**Issue by difference-scheme** [lfortran/lfortran#2925]
It seems that typed allocation of derived types, that were extended from a base type, isn't supported yet by LFortran. The following valid code, that attempts to allocate an `array` of `class(Base)` objects, with its single element/object being of the specific type `Extended`, fails to compile:
```
module typed_allocation

   type :: Base
   end type Base
   
   type, extends(Base) :: Extended
   end type Extended
   
contains
   
   subroutine allocator(array)
      class(Base), allocatable, intent(out) :: array(:)
      allocate( Extended :: array(1) )
   end subroutine allocator

end module typed_allocation
```
LFortran's output is:
```
semantic error: `The type-spec: Extended` is not supported yet
  --> typed_allocation.f90:13:17
   |
13 |       allocate( Extended :: array(1) )
   |                 ^^^^^^^^ 


```

**Comment by difference-scheme** [comment]
With the latest main branch this now compiles when using the following options:
```
lfortran -c typed_allocation.f90
```
But it fails with separate compilation, i.e. when using
```
lfortran -c --generate-object-code typed_allocation.f90
```
LFortran's output then is as follows:
```
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
LCompilersException: Not implemented class base

```
Could someone from the team put either the "separate compilation" label on it, and/or adjust the title to something that is now more appropriate?

**Comment by difference-scheme** [comment]
This bug also qualifies for the OOP label. Having done more testing, I also believe that together with bug #7707 it should be given the highest priority for OOP support.

**Comment by certik** [comment]
Thanks @difference-scheme, I told our team the above two issues are the highest priority.

**Comment by difference-scheme** [comment]
Thanks @certik. 

Once these two bugs are fixed we'll be able to compile (including code generation) 80% of that OO application. Getting the remaining 20% to compile should then be easier (modulo the final run-time debugging, that I expect will have to be done in any case).

**Comment by HarshitaKalani** [comment]
```console
$ cat a.f90
module typed_allocation

   type :: Base
   end type Base
   
   type, extends(Base) :: Extended
   end type Extended
   
contains
   
   subroutine allocator(array)
      class(Base), allocatable, intent(out) :: array(:)
      allocate( Extended :: array(1) )
   end subroutine allocator

end module typed_allocation
$ lfortran -c --generate-object-code a.f90
$ lfortran --version
LFortran version: 0.52.0-769-gda75b0e82
Platform: Linux
LLVM: 11.0.1
Default target: x86_64-unknown-linux-gnu
```
This works for me. I'm on linux ubuntu.

**Comment by difference-scheme** [comment]
@HarshitaKalani I just rechecked it with the present main branch. You are actually right. Thanks for pointing this out.

I need to get back to the original application, to see whether the typed allocation case that was failing there somehow differs from this particular example.

**Comment by difference-scheme** [comment]
What is actually failing in the true application is a combination of the above `allocate` statement, and the subsequent immediate initialization of the involved array via some code of the form shown in #7707.

It is probably the latter bug that is responsible for the failure. I'll await the fixing of #7707 to see if this will resolve the issue, or if additional action will be needed.

**Comment by difference-scheme** [comment]
I am afraid that the present bug is not resolved yet. The following variation of the above code still fails:
$ cat test.f90
```
module typed_allocation

   type :: Base
      real :: data = 2.0
   end type Base
   
   type, extends(Base) :: Extended
   end type Extended
   
contains
   
   subroutine allocator(array)
      class(Base), allocatable, intent(out) :: array(:)
      allocate( Extended :: array(1) )
   end subroutine allocator

end module typed_allocation

program test

   use typed_allocation

   class(Base), allocatable :: array(:)

   call allocator(array)

   print *, array(1)%data
   
end program test

```

$ lfortran test.f90 -o test
`Segmentation fault (core dumped)`

**Comment by certik** [comment]
Perfect, the above code gives me:
```
$ lfortran a.f90
Assertion failed: (PointeeType == cast<PointerType>(Ptr->getType()->getScalarType())->getElementType()), function Create, file Instructions.h, line 941.
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/src/bin/lfortran.cpp", line 2726
    LCompilers::print_stack_on_segfault();
  File "/Users/ondrej/repos/lfortran/src/bin/lfortran.cpp", line 2653
    err = compile_src_to_object_file(arg_file, tmp_o, compiler_options.time_report, false,
  File "/Users/ondrej/repos/lfortran/src/bin/lfortran.cpp", line 1185
    std::cerr << diagnostics.render(lm, compiler_options);
  File "/Users/ondrej/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 394
    if (res.ok) {
  File "/Users/ondrej/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 11807
    v.visit_asr((ASR::asr_t&)asr);
  File "/Users/ondrej/repos/lfortran/src/libasr/asr_base_visitor.h", line 342
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/src/libasr/asr_base_visitor.h", line 317
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/src/libasr/asr_base_visitor.h", line 343
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/src/libasr/asr_base_visitor.h", line 22
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1013
    ASR::symbol_t *mod = x.m_symtab->get_symbol(item);
  File "/Users/ondrej/repos/lfortran/src/libasr/asr_base_visitor.h", line 345
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/src/libasr/asr_base_visitor.h", line 30
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3502
    finish_module_init_function_prototype(x);
  File "/Users/ondrej/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4821
    ASR::Function_t *s = ASR::down_cast<ASR::Function_t>(item.second);
  File "/Users/ondrej/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4470
    visit_procedures(x);
  File "/Users/ondrej/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4774
    this->visit_stmt(*x.m_body[i]);
  File "/Users/ondrej/repos/lfortran/src/libasr/asr_base_visitor.h", line 361
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/src/libasr/asr_base_visitor.h", line 52
    case stmtType::Allocate: { v.visit_Allocate((const Allocate_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1196
    visit_AllocateUtil(x, x.m_stat, false);
  File "/Users/ondrej/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1173
    allocate_array_members_of_struct_arrays(x_arr_,
  File "/Users/ondrej/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3897
    [=]() {
  File "/Users/ondrej/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 306
    start_new_block(loopbody); {
  File "/Users/ondrej/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3921
    allocate_array_members_of_struct(
  File "/Users/ondrej/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3759
    llvm::Value* ptr_member = llvm_utils->create_gep2(type, ptr, idx);
  File "/Users/ondrej/repos/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1518
    return LLVMUtils::CreateGEP2(t, ds, idx_vec);
  File "/Users/ondrej/repos/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1707
    return builder->CreateGEP(t, x, idx);
  File "/Users/ondrej/.pixi/envs/lf/include/llvm/IR/IRBuilder.h", line 1773
    return Insert(GetElementPtrInst::Create(Ty, Ptr, IdxList), Name);
  File "/Users/ondrej/.pixi/envs/lf/include/llvm/IR/Instructions.h", line 942
    return new (Values) GetElementPtrInst(PointeeType, Ptr, IdxList, Values,
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x180379eeb
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18037ac5f
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x18047188b
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1804ab623
Abort: Signal SIGABRT (abort) received
```

Yes, if you can get to 80% now, it shouldn't be hard to get to 100%, although since you are compiling separately, there will probably be some linking issues also. And then of course once it creates a binary, it takes time to get rid of all the runtime bugs. But in general we are well on the way.

**Comment by certik** [comment]
I removed the separate compilation label, since as far as we know we have fixed all the bugs for separate compilation (thanks @Pranavchiku !!!), and the last thing to fix here is https://github.com/lfortran/lfortran/issues/2925#issuecomment-2972850965, which is unrelated.

**Comment by krystophny** [comment]
This issue is fixed on main. The exact MRE from comment https://github.com/lfortran/lfortran/issues/2925#issuecomment-2965191824 (the variant with `real :: data = 2.0` that caused a segfault/assertion failure in LLVM codegen at `allocate_array_members_of_struct_arrays`) now compiles and runs correctly, producing the expected output.

```
$ lfortran mre.f90 -o test && ./test
 PASS
```

Verified on Linux/LLVM 11 (v0.59.0-315-gbdda5f74b). Also works with `--separate-compilation`.

Integration test added in #9906 (`class_103.f90`) which will close this issue upon merge.

**Comment by krystophny** [comment]
**Fix attribution:** This was fixed incrementally by the OOP/class allocation infrastructure:
- #7282 (2025-05-14): Fixed the original semantic error ("type-spec not supported")
- #5791 (2025-07-22): ASR struct refactor removing Struct symbol dependency from ttype
- #9462 (2026-01-12): Fix allocate struct memory for each element in class array
- #9509 (2026-01-16): gfortran-like allocation strategy for arrays of classes

No single PR had a `Closes #2925` -- the fix was cumulative across the polymorphism infrastructure.
