### ISSUE TITLE
`real_kinds(i)` from `iso_fortran_env` fails

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2969]
I think this bug has something to do with indexing of module arrays. This fails:
```fortran
program a
use iso_fortran_env
integer :: i
do i = 1, size(real_kinds)
    print *, real_kinds(i)
end do
end program a
```
with:
```console
$ lfortran a.f90 
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2332
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 959
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9320
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "../libasr/asr.h", line 5059
  File "../libasr/asr.h", line 5035
  File "../libasr/asr.h", line 5060
  File "../libasr/asr.h", line 4767
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 945
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5062
  File "../libasr/asr.h", line 4776
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3062
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5079
  File "../libasr/asr.h", line 4829
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5629
    create_loop(x.m_name, [=]() {
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 320
    start_new_block(loopbody); {
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5635
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5079
  File "../libasr/asr.h", line 4815
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7418
    handle_print(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7695
    compute_fmt_specifier_and_arg(fmt, args, x.m_values[i], x.base.base.loc);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7522
    this->visit_expr_wrapper(v, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5109
    this->visit_expr(*x);
  File "../libasr/asr.h", line 5126
  File "../libasr/asr.h", line 4914
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2356
    tmp = arr_descr->get_single_element(array, indices, x.n_args,
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 630
    tmp = llvm_utils->create_gep(array, idx);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1324
    return LLVM::CreateGEP(*builder, ds, idx_vec);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 24
    llvm::Type *t = x->getType();
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Segfault: Signal SIGSEGV (segmentation fault) received
```
But this works:
```fortran
program a
use iso_fortran_env
print *, size(real_kinds)
print *, real_kinds(1)
print *, real_kinds(2)
end program a
```
Which gives:
```console
$ lfortran b.f90 
2
4
8
$ gfortran b.f90 && ./a.out 
           3
           4
           8
```

**Comment by Pranavchiku** [comment]
The above given example works because it uses compile time values. A slight modification leads to same failure:

```fortran
program a
use iso_fortran_env
integer :: i
i = 1
print *, size(real_kinds)
print *, real_kinds(i)
end program a
```

```console
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2332
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 959
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9340
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 5059
  File "../libasr/asr.h", line 5035
  File "../libasr/asr.h", line 5060
  File "../libasr/asr.h", line 4768
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 945
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5062
  File "../libasr/asr.h", line 4776
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3073
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5079
  File "../libasr/asr.h", line 4815
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7432
    handle_print(x);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7709
    compute_fmt_specifier_and_arg(fmt, args, x.m_values[i], x.base.base.loc);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7536
    this->visit_expr_wrapper(v, true);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5123
    this->visit_expr(*x);
  File "../libasr/asr.h", line 5126
  File "../libasr/asr.h", line 4914
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2366
    tmp = arr_descr->get_single_element(array, indices, x.n_args,
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 630
    tmp = llvm_utils->create_gep(array, idx);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1324
    return LLVM::CreateGEP(*builder, ds, idx_vec);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/llvm_utils.cpp", line 24
    llvm::Type *t = x->getType();
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x180465a23
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by certik** [comment]
With the latest LFortran it still fails:
```console
$ lfortran a.f90
Traceback (most recent call last):
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in _start()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_start_main()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_init_first()
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in main()
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in main_app(int, char**)
  File "lfortran.cpp", line 0, in (anonymous namespace)::compile_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
  File "asr_to_llvm.cpp", line 0, in void LCompilers::ASR::visit_asr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::asr_t const&, LCompilers::ASRToLLVMVisitor&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
  File "asr_to_llvm.cpp", line 0, in void LCompilers::ASR::visit_unit_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::unit_t const&, LCompilers::ASRToLLVMVisitor&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
  File "asr_to_llvm.cpp", line 0, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToLLVMVisitor&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASRToLLVMVisitor::visit_Program(LCompilers::ASR::Program_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
  File "asr_to_llvm.cpp", line 0, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in void LCompilers::ASRToLLVMVisitor::create_loop<LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::{lambda()#1}, LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::{lambda()#2}>(char*, LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::{lambda()#1}, LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::{lambda()#2})
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::{lambda()#2}::operator()() const
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
  File "asr_to_llvm.cpp", line 0, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASRToLLVMVisitor::visit_Print(LCompilers::ASR::Print_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in void LCompilers::ASRToLLVMVisitor::handle_print<LCompilers::ASR::Print_t>(LCompilers::ASR::Print_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASRToLLVMVisitor::compute_fmt_specifier_and_arg(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&, LCompilers::ASR::expr_t*, LCompilers::Location const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASRToLLVMVisitor::visit_expr_wrapper(LCompilers::ASR::expr_t*, bool)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
  File "asr_to_llvm.cpp", line 0, in void LCompilers::ASR::visit_expr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ASRToLLVMVisitor&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASRToLLVMVisitor::visit_ArrayItem(LCompilers::ASR::ArrayItem_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LLVMArrUtils::SimpleCMODescriptor::get_single_element(llvm::Value*, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&, int, bool, bool, llvm::Value**, bool, llvm::Type*, bool)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LLVMUtils::create_gep(llvm::Value*, llvm::Value*)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LLVM::CreateGEP(llvm::IRBuilder<llvm::ConstantFolder, llvm::IRBuilderDefaultInserter>&, llvm::Value*, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in llvm::Value::getType() const
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __sigaction()
Segfault: Signal SIGSEGV (segmentation fault) received
```
@HarshitaKalani, @parth121101 or @gxyd, do you want to look into this failure? It would be good to fix it.

**Comment by gxyd** [comment]
I'll look into this issue:
```fortran
program a
    use iso_fortran_env, only : real_kinds
    print *, real_kinds
end program a

```

the above program fails, I'll take that as MRE.

**Comment by kargl** [comment]
Any progress on this bug?  It prevents me from compile the first Fortran code needed to data mine `ISO_FORTRAN_ENV` for supported real kinds.  The upshot is that I can compile zero lines of my >100K of code.

**Comment by certik** [comment]
It still fails for me with the latest main. @gxyd, @kmr-srbh do you want to have a look at this one to see what is going on?

**Comment by kmr-srbh** [comment]
The `real_kinds` array is a `nullptr` when we try to get the array item above. The transformed code after the passes looks like a general module - program setup. I am looking into it.

**Comment by kmr-srbh** [comment]
I think the issue is unrelated to `iso_fortran_env`. The issue seems to be related to how we handle `parameter` variables in modules. Here is a MRE:

```fortran
module main_module
   integer, dimension(2), parameter :: x = [1, 2]
end module main_module

program main
   use main_module
   implicit none
   integer(4) :: i
   i = 2 
   print *, x(i)
end program main
```

**Comment by gxyd** [comment]
I'm sorry, I'll look into the issue in detail tomorrow maybe (I'm outside), but I've a feeling that it should work in *simplifier pass* branch (not sure).

**Comment by certik** [comment]
This is a general issue that we need to fix soon.

If this works in the simplifier pass, then we just need to focus and finish it.
