### ISSUE TITLE
LCompilersException: Unexpected token type 1, expected type 7

### ISSUE THREAD

**Issue by jschueller** [lfortran/lfortran#3027]
it seems the preprocessor does not support the `defined` keyword without parentheses:
```
program hello
#define SAYHELLO 1
#if defined SAYHELLO
  print *, 'Hello, World!'
#endif
end program hello
```

it fails with a cryptic error:
```
$ lfortran --cpp  hello.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
LCompilersException: Unexpected token type 1, expected type 7
```

it works fine with `#if defined(SAYHELLO)`

**Comment by certik** [comment]
Thanks, we need to fix it. Here is the full stacktrace:
```console
$ lfortran --cpp a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2334
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 907
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 243
    res = get_ast2(code_orig, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 197
    tmp = cpp.run(code_orig, lm, cpp.macro_definitions);
  File "preprocessor.re", line 301
  File "preprocessor.re", line 659
  File "preprocessor.re", line 823
  File "preprocessor.re", line 634
LCompilersException: Unexpected token type 1, expected type 7
```
The bug is right here on line 823:
```c++
    if (type == CPPTokenType::TK_NAME && str == "defined") {
        accept(cur, CPPTokenType::TK_LPAREN);
        std::string macro_name = accept_name(cur);
        accept(cur, CPPTokenType::TK_RPAREN);
```
As you can see, the preprocessor parser is expecting a parentheses after `defined`. So it needs to be extended to make those optional.

**Comment by jschueller** [comment]
indeed

**Comment by certik** [comment]
Yes, this is still not fixed:
```console
$ lfortran a.f90      
Hello, World!
$ lfortran --cpp a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2340
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 907
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 243
    res = get_ast2(code_orig, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 197
    tmp = cpp.run(code_orig, lm, cpp.macro_definitions);
  File "preprocessor.re", line 301
  File "preprocessor.re", line 659
  File "preprocessor.re", line 823
  File "preprocessor.re", line 634
LCompilersException: Unexpected token type 1, expected type 7
$ 
```

I am guessing @Kishan-Ved didn't use the `--cpp` option.

**Comment by Kishan-Ved** [comment]
Yes @certik , I didn't use that. I'll see how I can fix this asap.

**Comment by NishantBansal2003** [comment]
Hey @certik, can you please tell me if there is any place in the codebase where optional parentheses are used?
