### ISSUE TITLE
Failure while compiling code with character array

### ISSUE THREAD

**Issue by jkd2016** [lfortran/lfortran#3039]
Compiling the code:

```
program test
implicit none
character b(10)
b(:)=" "
end program
```

with LFortran version 0.30.0 yields:

```
lfortran: /usr/include/llvm-14/llvm/IR/Instructions.h:923: llvm::Type* llvm::checkGEPType(llvm::Type*): Assertion `Ty && "Invalid GetElementPtrInst indices for type!"' failed.
```

**Comment by certik** [comment]
Thanks! Here is a full stacktrace:
```console
$ lfortran a.f90 
Assertion failed: (Ty && "Invalid GetElementPtrInst indices for type!"), function checkGEPType, file Instructions.h, line 897.
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2340
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 949
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9452
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "../libasr/asr.h", line 5085
  File "../libasr/asr.h", line 5061
  File "../libasr/asr.h", line 5086
  File "../libasr/asr.h", line 4792
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 945
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5088
  File "../libasr/asr.h", line 4801
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3064
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5105
  File "../libasr/asr.h", line 4854
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5679
    create_loop(x.m_name, [=]() {
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 314
    start_new_block(loophead); {
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5680
    this->visit_expr_wrapper(x.m_test, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5159
    this->visit_expr(*x);
  File "../libasr/asr.h", line 5152
  File "../libasr/asr.h", line 4891
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5316
    this->visit_expr_wrapper(x.m_right, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5159
    this->visit_expr(*x);
  File "../libasr/asr.h", line 5152
  File "../libasr/asr.h", line 4925
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5884
    tmp = lfortran_str_len(parg, ASRUtils::is_array(arg_type));
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 643
    str = CreateLoad(arr_descr->get_pointer_to_data(str));
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 535
    return llvm_utils->create_gep(arr, 0);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1360
    return LLVM::CreateGEP(*builder, ds, idx_vec);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 27
    return builder.CreateGEP(t2, x, idx);
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/IRBuilder.h", line 1773
    return Insert(GetElementPtrInst::Create(Ty, Ptr, IdxList), Name);
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 943
    NameStr, InsertBefore);
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1151
    }
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1143
    : Instruction(getGEPReturnType(PointeeType, Ptr, IdxList), GetElementPtr,
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1074
    Type *PtrTy = PointerType::get(checkGEPType(getIndexedType(ElTy, IdxList)),
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 897
    assert(Ty && "Invalid GetElementPtrInst indices for type!");
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18024972b
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18024a313
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x18030ceaf
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Abort: Signal SIGABRT (abort) received

zsh: abort      lfortran a.f90
```
