### ISSUE TITLE
ASR Verify: ASR::ttype_t in ASR::FunctionType cannot be tied to a scope

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#3080]
Ref: https://github.com/lfortran/lfortran/issues/3052#issuecomment-1886259999
```fortran
function func(A) result(res)
    real(8), intent(in) :: A(:,:)
    real(8) :: res(minval(shape(A)))
end function func
```
```console
$ lfortran b.f90
ASR verify pass error: ASR verify: Function func doesn't depend on _lcompilers_shape1 but is found in its dependency list.
Internal Compiler Error: Unhandled exception
^C
$ gfortran b.f90
```

**Comment by certik** [comment]
The FunctionType is using "MinVal_4_1_0(_lcompilers_shape1)", while the `res` variable in the function itself is using "MinVal_4_1_0(_lcompilers_shape)". So the function MinVal's instantiation is reused, but the shape function instantiation is not reused. I would see if we can reuse it, which should fix this issue.

A separate question is if FunctionType should depend on a particular scoped symbol table and call functions from it directly (minval and shape in this case). We need to think about it. For now we can ignore this question.

**Comment by HarshitaKalani** [comment]
```console
$ lfortran a.f90 --show-llvm
ASR verify pass error: ASR::ttype_t in ASR::FunctionType cannot be tied to a scope.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2373, in ??
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2254, in main_app(int, char**)
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 847, in ??
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 292, in LCompilers::FortranEvaluator::get_llvm(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&)
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 314, in LCompilers::FortranEvaluator::get_llvm2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&)
    diagnostics, lm.files.back().in_filename);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 360, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9561, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 302, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
LCompilersException: Verify failed in the pass: subroutine_from_function
```
After https://github.com/lfortran/lfortran/pull/3265, this is the new error.

**Comment by HarshitaKalani** [comment]
Closing wrt: https://github.com/lfortran/lfortran/pull/3407
