### ISSUE TITLE
Arrays in interctive mode

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#3089]
```console
>>> real :: xt(2)                                                        1,14  ]
>>> xt(1) = 1.2                                                          1,12  ]
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2187
    return prompt(arg_v, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 300
    std::cerr << diagnostics.render(lm, cu);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 127
    e->add_module(std::move(m));
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/evaluator.cpp", line 244
    add_module(std::move(m->m_m));
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/evaluator.cpp", line 238
    throw LCompilersException("addModule() returned an error: " + msg);
LCompilersException: addModule() returned an error: Duplicate definition of symbol '_xt'
```

Reported at https://fortran-lang.discourse.group/t/interactive-use-of-lfortran/7167.

As a workaround, wrap arrays inside a function:
```console
>>> subroutine f()                                                             ┐
... real :: xt(2)                                                              │
... xt(1) = 1.2                                                                │
... print *, xt                                                                │
... end subroutine                                                       5,15  ┘
>>> call f()                                                             1,9   ]
1.20000005e+00 9.11243221e-35 
```

**Comment by Beliavsky** [comment]
Change "interctive" in title to "interactive". (Sorry to nitpick, but typos impede searches.)
