### ISSUE TITLE
Stdlib: Initializing complex parameter fails

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lfortran/lfortran#3096]
Here is another issue in `stdlib_linalg.f90` file
```fortran
PROGRAM main
    complex(8), parameter :: zero = 0 
END PROGRAM
```
```console
$ gfortran b.f90 && ./a.out
$ lfortran b.f90
^C
```

_Originally posted by @HarshitaKalani in https://github.com/lfortran/lfortran/issues/3052#issuecomment-1886402072_

**Comment by Shaikh-Ubaid** [comment]
MRE:
```bash
(lf2) % cat examples/expr2.f90 
PROGRAM main
    complex(8), parameter :: zero = 0
    print *, zero
END PROGRAM
(lf2) % lfortran_in_main examples/expr2.f90  
Traceback (most recent call last):
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/bin/lfortran.cpp", line 2340
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/bin/lfortran.cpp", line 907
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/lfortran/fortran_evaluator.cpp", line 253
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/lfortran/fortran_evaluator.cpp", line 275
    compiler_options.symtab_only, compiler_options);
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/lfortran/semantics/ast_to_asr.cpp", line 98
    if (res.ok) {
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 3444
    v.visit_TranslationUnit(ast);
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 120
    visit_ast(*x.m_items[i]);
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/lfortran/ast.h", line 4848
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/lfortran/ast.h", line 4804
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/lfortran/ast.h", line 4851
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/lfortran/ast.h", line 4438
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 519
    visit_unit_decl2(*x.m_decl[i]);
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/lfortran/ast.h", line 4862
    void visit_unit_decl2(const unit_decl2_t &b) { visit_unit_decl2_t(b, self()); }
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/lfortran/ast.h", line 4465
    case unit_decl2Type::Declaration: { v.visit_Declaration((const Declaration_t &)x); return; }
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1549
    visit_DeclarationUtil(x);
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/lfortran/semantics/ast_common_visitor.h", line 2530
    if (storage_type == ASR::storage_typeType::Parameter) {
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x18042ea83
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by certik** [comment]
Thanks @Shaikh-Ubaid for fixing it! Why don't you fix this one, that I just discovered, while you are at it: https://github.com/lfortran/lfortran/issues/3098.
