### ISSUE TITLE
Allocatable and pointer types' verify error

### ISSUE THREAD

**Issue by ansharlubis** [lfortran/lfortran#3149]
The following program fails when calling `sum` even though the type all aligns correctly:
``` fortran
module test_m
    type :: matrix
        integer :: elements(2, 2)
    end type
contains
    pure function combine(x, y) result(combined)
        integer, intent(in) :: x, y
        integer :: combined
        combined = x + y
    end function

    pure function sum(list) result(combined)
        integer, intent(in) :: list(2)
        integer :: combined
        integer :: i
        if (size(list) > 0) then
            combined = list(1)
            do i = 2, size(list)
                combined = combine(combined, list(i))
            end do
        else
            combined = 0
        end if
    end function

    elemental function times_integer(x, y) result(product)
        integer, intent(in) :: x, y
        integer :: product
        product = x*y
    end function

    pure function pure_times_integer(x, y) result(product)
        integer, intent(in) :: x(2), y(2)
        integer :: product(2), i
        do i = 1, 2
            product(i) = x(i) * y(i)
        end do
    end function

    elemental function times_matrix(x, y) result(combined)
        type(matrix), intent(in) :: x, y
        type(matrix) :: combined
        integer :: i, j
        integer :: product(2)
        integer :: product_sum
        do i = 1, 2
            do j = 1, 2
                combined%elements(i, j) = sum(times_integer(x%elements(i,:), y%elements(:,j)))             ! this one doesn't work
                combined%elements(i, j) = sum(pure_times_integer(x%elements(i,:), y%elements(:,j)))    ! this one works
            end do
        end do
    end function
end module

program test

end program
```
Giving the following error:
```
ASR verify pass error: ASR verify: Allocatable type conflicts with Pointer type
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/lubis/projects/lfortran/src/bin/lfortran", in _start()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_start_main()
  File "/home/lubis/projects/lfortran/src/bin/lfortran.cpp", line 2371, in ??
    return main_app(argc, argv);
  File "/home/lubis/projects/lfortran/src/bin/lfortran.cpp", line 2334, in main_app(int, char**)
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/lubis/projects/lfortran/src/bin/lfortran.cpp", line 949, in ??
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/lubis/projects/lfortran/src/lfortran/fortran_evaluator.cpp", line 360, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/lubis/projects/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9543, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/lubis/projects/lfortran/src/libasr/pass/pass_manager.h", line 302, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
LCompilersException: Verify failed in the pass: array_op
```

**Comment by HarshitaKalani** [comment]
I tried to reproduce the error but it does not throw any error in my machine (linux)
```console
$ gfortran b.f90 && ./a.out
$ lfortran b.f90
$ 
```

**Comment by ansharlubis** [comment]
Thanks for reproducing it! It does work now.
