### ISSUE TITLE
stdlib: AssertFailed: id_symtab_map.find(symtab_id) != id_symtab_map.end()

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3166]
```fortran
submodule (stdlib_math) stdlib_math_all_close

end submodule stdlib_math_all_close
```

> LFortran

```console
% lfortran a.f90 --show-llvm
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2368
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2254
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 847
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 292
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 309
    Result<ASR::TranslationUnit_t*> asr = get_asr2(code, lm, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 253
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 275
    compiler_options.symtab_only, compiler_options);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 98
    if (res.ok) {
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 3444
    v.visit_TranslationUnit(ast);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 120
    visit_ast(*x.m_items[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4848
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4804
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4851
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4436
    case modType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 478
    visit_ModuleSubmoduleCommon<AST::Submodule_t, ASR::Module_t>(x, std::string(x.m_id));
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 410
    ASR::symbol_t* submod_parent = (ASR::symbol_t*)(ASRUtils::load_module(al, global_scope,
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.cpp", line 308
    *symtab, intrinsic, pass_options);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.cpp", line 456
    ASR::TranslationUnit_t *asr = load_modfile(al, modfile, false, symtab);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/modfile.cpp", line 94
    ASR::asr_t *asr = deserialize_asr(al, asr_binary, load_symtab_id, symtab);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast_serialization.cpp", line 392
    Line not found
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast_serialization.cpp", line 398
    Line not found
  File "../libasr/asr.h", line 35137
  File "../libasr/asr.h", line 35183
  File "../libasr/asr.h", line 35166
  File "../libasr/asr.h", line 35786
  File "../libasr/asr.h", line 35240
  File "../libasr/asr.h", line 35787
  File "../libasr/asr.h", line 35299
  File "../libasr/asr.h", line 36872
  File "../libasr/asr.h", line 35871
  File "../libasr/asr.h", line 39023
  File "../libasr/asr.h", line 36997
  File "../libasr/asr.h", line 39417
  File "../libasr/asr.h", line 39345
  File "../libasr/asr.h", line 39470
  File "../libasr/asr.h", line 39023
  File "../libasr/asr.h", line 36986
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast_serialization.cpp", line 105
    Line not found
AssertFailed: id_symtab_map.find(symtab_id) != id_symtab_map.end()
```

**Comment by certik** [comment]
Submodules are not supported yet, so we just need to implement support for them at the ASR level and then transform AST->ASR correctly.
