### ISSUE TITLE
Segfault while handling optional argument

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3182]
Requested in #3046.

```fortran

module stdlib_math

    implicit none

contains

    elemental logical function is_close(a, rel_tol) result(close)
        real, intent(in) :: a
        real, intent(in), optional :: rel_tol
        
        close = abs(a - 1) <= max(a,1.0)

    end function is_close

    logical pure function all_close(a, b) result(close)

        real, intent(in) :: a(:), b(:)

        close = all(is_close(a, 12.24))

    end function all_close
end module stdlib_math
```

> LFortran

```console
% lfortran a.f90 --show-llvm
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2368
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2254
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 847
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 292
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 314
    diagnostics, lm.files.back().in_filename);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9543
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 302
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 162
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 1923
    v.visit_TranslationUnit(unit);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 1565
    ASR::symbol_t *mod = x.m_symtab->get_symbol(item);
  File "../libasr/asr.h", line 5088
  File "../libasr/asr.h", line 4801
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 1585
    for (auto &item : x.m_symtab->get_scope()) {
  File "../libasr/asr.h", line 5088
  File "../libasr/asr.h", line 4802
  File "../libasr/asr.h", line 46179
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 1536
    visit_stmt(*m_body[i]);
  File "../libasr/asr.h", line 5105
  File "../libasr/asr.h", line 4826
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 1740
    visit_AssignmentUtil(x);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 1622
    current_expr = const_cast<ASR::expr_t**>(&(x.m_value));
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 1516
    replacer.replace_expr(*current_expr);
  File "../libasr/asr.h", line 45383
  File "../libasr/asr.h", line 44464
  File "../libasr/asr.h", line 45115
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 1424
    loc, arr_type, al, current_scope);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_utils.cpp", line 256
    PassUtils::get_dim_rank(var_type, m_dims, ndims);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_utils.cpp", line 256
    PassUtils::get_dim_rank(var_type, m_dims, ndims);
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x18046da23
Segfault: Signal SIGSEGV (segmentation fault) received

```

**Comment by certik** [comment]
Here is a more minimal example with the same error:
```fortran
program X
    
print *, is_close([1., 2.], 12.2)

contains

    elemental logical function is_close(a, rel_tol) result(close)
        real, intent(in) :: a
        real, intent(in), optional :: rel_tol

        close = abs(a - 1) <= max(a,1.0)

    end function is_close

end program
```

**Comment by certik** [comment]
Here is how to make progress fixing it:
```diff
diff --git a/src/libasr/pass/array_op.cpp b/src/libasr/pass/array_op.cpp
index c62d38e04..29787b77f 100644
--- a/src/libasr/pass/array_op.cpp
+++ b/src/libasr/pass/array_op.cpp
@@ -1426,12 +1426,17 @@ class ReplaceArrayOp: public ASR::BaseExprReplacer<ReplaceArrayOp> {
                     ASR::Function_t* func = ASR::down_cast<ASR::Function_t>(ASRUtils::symbol_get_past_external(x->m_name));
                     if (func->m_return_var != nullptr && !ASRUtils::is_array(ASRUtils::expr_type(func->m_return_var))) {
                         ASR::ttype_t* sibling_type = ASRUtils::expr_type(operand);
-                        ASR::dimension_t* m_dims; int ndims;
+                        ASR::dimension_t* m_dims=nullptr; int ndims=0;
                         PassUtils::get_dim_rank(sibling_type, m_dims, ndims);
-                        ASR::ttype_t* arr_type = ASRUtils::TYPE(ASR::make_Array_t(al, loc, ASRUtils::expr_type(func->m_return_var),
-                                                m_dims, ndims, ASR::array_physical_typeType::FixedSizeArray));
-                        result_var = PassUtils::create_var(result_counter, res_prefix,
-                                        loc, arr_type, al, current_scope);
+                        if (m_dims == nullptr) {
+                            result_var = PassUtils::create_var(result_counter, res_prefix,
+                                            loc, first_array_operand, al, current_scope);
+                        } else {
+                            ASR::ttype_t* arr_type = ASRUtils::TYPE(ASR::make_Array_t(al, loc, ASRUtils::expr_type(func->m_return_var),
+                                                    m_dims, ndims, ASR::array_physical_typeType::FixedSizeArray));
+                            result_var = PassUtils::create_var(result_counter, res_prefix,
+                                            loc, arr_type, al, current_scope);
+                        }
                     } else {
                         result_var = PassUtils::create_var(result_counter, res_prefix,
                                         loc, operand, al, current_scope);
```
Now it gives some LLVM error.

**Comment by certik** [comment]
Here is a fix:
```diff
--- a/src/libasr/pass/array_op.cpp
+++ b/src/libasr/pass/array_op.cpp
@@ -1425,8 +1425,8 @@ class ReplaceArrayOp: public ASR::BaseExprReplacer<ReplaceArrayOp> {
                 if( result_var == nullptr ) {
                     ASR::Function_t* func = ASR::down_cast<ASR::Function_t>(ASRUtils::symbol_get_past_external(x->m_name));
                     if (func->m_return_var != nullptr && !ASRUtils::is_array(ASRUtils::expr_type(func->m_return_var))) {
-                        ASR::ttype_t* sibling_type = ASRUtils::expr_type(operand);
-                        ASR::dimension_t* m_dims; int ndims;
+                        ASR::ttype_t* sibling_type = ASRUtils::expr_type(first_array_operand);
+                        ASR::dimension_t* m_dims=nullptr; int ndims=0;
                         PassUtils::get_dim_rank(sibling_type, m_dims, ndims);
                         ASR::ttype_t* arr_type = ASRUtils::TYPE(ASR::make_Array_t(al, loc, ASRUtils::expr_type(func->m_return_var),
                                                 m_dims, ndims, ASR::array_physical_typeType::FixedSizeArray));
```

**Comment by certik** [comment]
Put some assert that `m_dims` is not a nullptr after `get_dim_rank`.
