### ISSUE TITLE
Wrong interface selected

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3244]
Requested in #3046.

```fortran
module temp_module

interface all_close

procedure :: all_close_1_csp
procedure :: all_close_2_csp
end interface all_close
contains

logical pure function all_close_1_csp(a, b) result(close)

    complex, intent(in) :: a(:), b(:)
end function all_close_1_csp
logical pure function all_close_2_csp(a, b) result(close)

    complex, intent(in) :: a(:,:), b(:,:)
end function all_close_2_csp

end module

program example_math_all_close
use temp_module, only: all_close

complex :: z(4, 4)

print *, all_close(z, z)

end program example_math_all_close
```

> LFortran

```console
% lfortran a.f90 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2370
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2336
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 949
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9545
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 302
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 162
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 651
    u.visit_TranslationUnit(unit);
  File "../libasr/asr.h", line 39854
  File "../libasr/asr.h", line 5088
  File "../libasr/asr.h", line 4801
  File "../libasr/asr.h", line 39866
  File "../libasr/asr.h", line 39848
  File "../libasr/asr.h", line 5105
  File "../libasr/asr.h", line 4840
  File "../libasr/asr.h", line 40092
  File "../libasr/asr.h", line 5152
  File "../libasr/asr.h", line 4879
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 578
    visit_Call(x);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 540
    throw LCompilersException("Number of arguments in the new "
LCompilersException: Number of arguments in the new function call doesn't satisfy min_args <= new_args.size() <= max_args, 6 <= 10 <= 6
```

When we see the function call to `all_close`

```clojure
                        (FunctionCall
                            5 all_close@all_close_1_csp !-- should have call all_close_2_csp
                            5 all_close
                            [((ArrayPhysicalCast
                                (Var 5 z)
                                FixedSizeArray
                                DescriptorArray
                                (Array
                                    (Complex 4)
                                    [((IntegerConstant 1 (Integer 4))
                                    (IntegerConstant 4 (Integer 4)))
                                    ((IntegerConstant 1 (Integer 4))
                                    (IntegerConstant 4 (Integer 4)))]
                                    DescriptorArray
                                )
                                ()
                            ))
                            ((ArrayPhysicalCast
                                (Var 5 z)
                                FixedSizeArray
                                DescriptorArray
                                (Array
                                    (Complex 4)
                                    [((IntegerConstant 1 (Integer 4))
                                    (IntegerConstant 4 (Integer 4)))
                                    ((IntegerConstant 1 (Integer 4))
                                    (IntegerConstant 4 (Integer 4)))]
                                    DescriptorArray
                                )
                                ()
                            ))]
                            (Logical 4)
                            ()
                            ()
                        )
```

**Comment by Pranavchiku** [comment]
Closing with reference to #3249.
