### ISSUE TITLE
Selected_real_kind takes only one argument

### ISSUE THREAD

**Issue by ddey** [lfortran/lfortran#3284]
SELECTED_REAL_KIND(PRECISION, RANGE) is showing error. It prints only one argument is allowed.

**Comment by certik** [comment]
Yes, we need to fix it. One can reproduce this by:
```diff
--- a/integration_tests/intrinsics_14.f90
+++ b/integration_tests/intrinsics_14.f90
@@ -5,7 +5,7 @@ integer, parameter :: &
     k3 = selected_int_kind(5_8), &
     k4 = selected_int_kind(8), &
     k5 = selected_int_kind(10), &
-    k6 = selected_real_kind(5), &
+    k6 = selected_real_kind(5, 10), &
     k7 = selected_real_kind(5_4), &
     k8 = selected_real_kind(5_8), &
     k9 = selected_real_kind(8), &
```
and
```console
$ lfortran intrinsics_14.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2371
    LCompilers::print_stack_on_segfault();
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2337
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 907
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 253
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 275
    compiler_options.symtab_only, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 98
    if (res.ok) {
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 3453
    v.visit_TranslationUnit(ast);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 120
    visit_ast(*x.m_items[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4848
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4804
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4851
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4438
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 521
    visit_unit_decl2(*x.m_decl[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4862
    void visit_unit_decl2(const unit_decl2_t &b) { visit_unit_decl2_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4465
    case unit_decl2Type::Declaration: { v.visit_Declaration((const Declaration_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1555
    visit_DeclarationUtil(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 2425
    this->visit_expr(*s.m_initializer);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4945
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4602
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5475
    tmp = create_FunctionCallWithASTNode(x, v, args);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 3840
    return create_Function(x.base.base.loc, args, v);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 3796
    ASRUtils::set_absent_optional_arguments_to_null(args, func, al);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_utils.h", line 2567
    LCOMPILERS_ASSERT(args.size() + offset == (func->n_args));
AssertFailed: args.size() + offset == (func->n_args)
```
