### ISSUE TITLE
tests: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#3287]
I just got the following error:
```console
subroutine3.f90 * julia ✓ 
subroutine5.f90 * julia ✓ 
subroutine4.f90 * julia ✓ 
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/./run_tests.py", line 429, in <module>
    tester_main("LFortran", single_test)
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/compiler_tester/tester.py", line 446, in tester_main
    for f in futures:
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ondrej/repos/lfortran/lfortran/./run_tests.py", line 205, in single_test
    run_test(
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/compiler_tester/tester.py", line 296, in run_test
    do = json.load(open(jo))
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/ondrej/mambaforge/envs/lf/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Rerunning the tests then gives me the error #3286. So I can't reproduce it.

**Comment by Shaikh-Ubaid** [comment]
The reference tests run fine for me.
```console
...
errors/max_01.f90 * asr ✓ 
errors/min_02.f90 * asr ✓ 
errors/min_01.f90 * asr ✓ 
errors/runtime_stacktrace_01.f90 * run_dbg ✓ 
TESTS PASSED
```

Could you try a clean build?
```console
git clean -dfx
./build1.sh
```

**Comment by gxyd** [comment]
I think I remember having the same issue occur for me as well (randomly got this error), and then re-ran tests (without running any command in-between) and it worked just fine.
