### ISSUE TITLE
FunctionType is tied to scope

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3337]
Requested in #3323

```fortran
pure function diag_rsp_mat(A) result(res)
real, intent(in) :: A(:,:)
real :: res(minval(shape(A)))
end function diag_rsp_mat
```

> LFortran

```console
% lfortran stdlib_linalg.f90 --show-llvm                  
ASR verify pass error: ASR::ttype_t in ASR::FunctionType cannot be tied to a scope.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2372
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2256
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 847
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 292
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 314
    diagnostics, lm.files.back().in_filename);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9560
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 302
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 166
    throw LCompilersException("Verify failed in the pass: "
LCompilersException: Verify failed in the pass: subroutine_from_function
```

```clojure
                    (FunctionType
                        [(Array
                            (Real 4)
                            [(()
                            ())
                            (()
                            ())]
                            DescriptorArray
                        )
                        (Array
                            (Real 4)
                            [((IntegerConstant 1 (Integer 4))
                            (FunctionCall
                                1 MinVal_4_1_0
                                1 MinVal_4_1_0
                                [((Var 2 __libasr__created__var__1__func_call_arg_tmp_))] --------- Incorrect FunctionType
                                (Integer 4)
                                ()
                                ()
                            ))]
                            PointerToDataArray
                        )]
                        ()
                        Source
                        Implementation
                        ()
                        .false.
                        .true.
                        .false.
                        .false.
                        .false.
                        []
                        .false.
                    )
```

**Comment by HarshitaKalani** [comment]
Similar to: https://github.com/lfortran/lfortran/issues/3080

**Comment by Pranavchiku** [comment]
This is a bug in `subroutine_from_function` pass. Ideally it should not `replace_FunctionCall` but, it does.

**Comment by certik** [comment]
As part of `FunctionType`, I think `shape` (or an equivalent user-defined function) must be kept in the function form, returning an array. Then everything works.

Then, in the array_op pass, I think we need to skip FunctionType and leave things be. However, everywhere in the code when this type would actually be used, we need to promote subroutines to functions.

**Comment by Pranavchiku** [comment]
Just documenting for reference while implementing. Create a new pass `replace_function_call_in_declaration` and place it just before `array_op` pass. It will be a `ASR::CallReplacerOnExpressionsVisitor<XX>` with special handling for `visit_Function` that sets `current_scope` and then calls `visit_type(m_function_signature)` with special handling for `visit_FunctionType` node. 

* On visiting function type, check if `m_return_var_type` is an array and any of dimension is a function call. If yes, use `current_scope`, set `current_function_symbol` correctly and then call `replace_expr`
* Now, `replace_IntrinsicArrayFunction` or `replace_FunctionCall` will be responsible to create `__lcompilers_created_helper_function_xx` and populating it correctly.
* To populate it, we will iterate over all function arguments of call, get the `FunctionParam` used and duplicate corresponding symbol in newly created function, create an integer return variable and assign it the replace expression and return type of this function will be an Integer 4.
* The replaced expression will be a function call to newly created function now and function type will now be correct.
* Lastly call `PassUtils::UpdateDependenciesVisitor` to update dependencies correctly.

We can improve / update this design moving forward.

**Comment by Pranavchiku** [comment]
I have made progress over this, the example now works. There are few failures in integration tests, will resolve it and open a PR soon.

**Comment by Pranavchiku** [comment]
There are a lot of intermediate codes which fail to compile with LFortran

Example:

```fortran
pure integer function fn1(A) result(r)
implicit none
real, intent(in) :: A(:,:)
r = minval(shape(A))
end function

function diag_rsp_mat(A) result(res)
implicit none
interface
    pure integer function fn1(B)
    implicit none
    real, intent(in) :: B(:,:)
    end function
end interface
real, intent(in) :: A(:,:)
real :: res(fn1(A))
res = 123.45
end function

program functions_19
implicit none
real :: A(5, 5)
real :: res(5)
integer :: result
interface
    function diag_rsp_mat(A) result(res)
    implicit none
    interface
        pure integer function fn1(C)
        implicit none
        real, intent(in) :: C(:,:)
        end function
    end interface
    real, intent(in) :: A(:,:)
    real :: res(fn1(A))
    end function
end interface
res = diag_rsp_mat(A)
print *, res
end program
```

```console
% lfortran c.f90 --show-asr
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2372
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2250
    return emit_asr(arg_file, lfortran_pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 622
    r = fe.get_asr2(input, lm, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 253
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 275
    compiler_options.symtab_only, compiler_options);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 128
    if (res.ok) {
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3386
    b.is_body_visitor = true;
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 143
    visit_ast(*x.m_items[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4848
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4804
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4851
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4438
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1510
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 114
    this->visit_stmt(*m_body[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4894
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4540
    case stmtType::Assign: { v.visit_Assign((const Assign_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2236
    ASR::expr_t *target = ASRUtils::EXPR(tmp);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4945
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4602
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5612
    tmp = create_FunctionCallWithASTNode(x, v, args);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4021
    return create_Function(x.base.base.loc, args, v);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 3951
    return_type = handle_return_type(return_type, loc, args, func);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 3532
    fix_exprs_ttype_t(func_calls, args, f);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 3485
    arg_replacer.current_expr = &expri_copy;
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr.h", line 45317
    self().replace_FunctionCall(down_cast<ASR::FunctionCall_t>(x));
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.h", line 3709
    ASR::Module_t *m = ASR::down_cast2<ASR::Module_t>(f->m_symtab->parent->asr_owner);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr.h", line 51
    ptype *t = down_cast<ptype>(f);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr.h", line 41
    LCOMPILERS_ASSERT(is_a<T>(*f));
AssertFailed: is_a<T>(*f)
```

With following diff:

```diff
diff --git a/src/libasr/asr_utils.h b/src/libasr/asr_utils.h
index 265980c34..22f26a5b5 100644
--- a/src/libasr/asr_utils.h
+++ b/src/libasr/asr_utils.h
@@ -3697,7 +3697,15 @@ class ReplaceArgVisitor: public ASR::BaseExprReplacer<ReplaceArgVisitor> {
                 f = ASR::down_cast<ASR::Function_t>(f_sym);
             }
         }
-        ASR::Module_t *m = ASR::down_cast2<ASR::Module_t>(f->m_symtab->parent->asr_owner);
+        ASR::symbol_t* sym = nullptr;
+        ASR::Module_t *m = nullptr;
+        if (ASR::is_a<ASR::symbol_t>(*f->m_symtab->parent->asr_owner)) {
+            sym = ASR::down_cast<ASR::symbol_t>(f->m_symtab->parent->asr_owner);
+            if (ASR::is_a<ASR::Module_t>(*sym)) {
+                m = ASR::down_cast<ASR::Module_t>(sym);
+            }
+        }
+        if (!m) return;
         char *modname = m->m_name;
         ASR::symbol_t *maybe_f = current_scope->resolve_symbol(std::string(f->m_name));
         ASR::symbol_t* maybe_f_actual = nullptr;
```

```console
% lfortran c.f90 --show-asr
ASR verify pass error: ASR verify: The symbol table was not found in the scope of `symtab`.
  --> c.f90:29:9 - 32:21
   |
29 |            pure integer function fn1(C)
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
32 |            end function
   | ...^^^^^^^^^^^^^^^^^^^^^ failed here

ASR verify pass error: FunctionCall::m_name `fn1` cannot point outside of its symbol table
  --> c.f90:35:17
   |
35 |     real :: res(fn1(A))
   |                 ^^^^^^ failed here


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.

```
