### ISSUE TITLE
Nullptr dimension in `ArrayReshape` node results in code generation error while using it as LowerBound

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3369]
Requested in #3323.
```fortran
program example_diag5
  ! use stdlib_linalg, only: diag
  implicit none
  real :: A(3,3)
  A = reshape([1,2,3,4,5,6,7,8,9], [3,3])
end program example_diag5
```

> LFortran

```console
% lfortran a.f90 --show-llvm --show-stacktrace
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2372
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2256
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 847
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 292
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 314
    diagnostics, lm.files.back().in_filename);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9580
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 5085
  File "../libasr/asr.h", line 5061
  File "../libasr/asr.h", line 5086
  File "../libasr/asr.h", line 4793
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 945
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5088
  File "../libasr/asr.h", line 4801
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3067
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5105
  File "../libasr/asr.h", line 4826
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4763
    ptr_loads = 2 - (ASRUtils::is_character(*value_type) ||
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5180
    this->visit_expr(*x);
  File "../libasr/asr.h", line 5152
  File "../libasr/asr.h", line 4942
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9405
    this->visit_expr_wrapper(m_dims[i].m_start, true);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5177
    throw CodeGenError("Internal error: x is nullptr");
  File "../libasr/codegen/llvm_utils.h", line 56
  File "../libasr/codegen/llvm_utils.h", line 55
code generation error: Internal error: x is nullptr


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.

```

**Comment by gxyd** [comment]
@Pranavchiku , I'm not able to regenerate the error posted in the issue. Also, I don't understand the title of the issue.
