### ISSUE TITLE
Unhandled exception for comparison of logical operand with real/complex operand

### ISSUE THREAD

**Issue by gxyd** [lfortran/lfortran#3444]
### Minimal reproducible example

```f90
program main
    logical :: logicalValue
    complex :: a
    a = (2.0, 0.0)
    logicalValue = .TRUE.

    if (a == logicalValue) then
        print *, "valar morghulis"
    else
        print *, "valar dohaeris"
    end if
end program
```

causes an unhandled exception:
```bash
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2391
    LCompilers::print_stack_on_segfault();
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2355
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 907
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 253
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 275
    compiler_options.symtab_only, compiler_options);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 127
    if (res.ok) {
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3386
    b.is_body_visitor = true;
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 143
    visit_ast(*x.m_items[i]);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4848
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4804
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4851
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4438
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1510
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 114
    this->visit_stmt(*m_body[i]);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4894
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4581
    case stmtType::ForAll: { v.visit_ForAll((const ForAll_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2909
    visit_expr(*x.m_test);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4945
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4601
    case exprType::DefUnaryOp: { v.visit_DefUnaryOp((const DefUnaryOp_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 6472
    CommonVisitorMethods::visit_Compare(al, x, left, right, tmp,
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 182
    LCOMPILERS_ASSERT(
AssertFailed: ASRUtils::check_equal_type(ASRUtils::expr_type(left), ASRUtils::expr_type(right))
```

**Comment by gxyd** [comment]
the same exception results for `Character` and `Integer` comparison as well:
```f90
program main
    character(1) :: x
    integer :: i
    x = 'u'
    i = 10
    if (i > x) then
        print *, "Hello World"
    else
        print *, "fuck the world"
    end if
end program
```
