### ISSUE TITLE
Unhandled exception on passing unsupported "kind" parameter

### ISSUE THREAD

**Issue by gxyd** [lfortran/lfortran#3450]
```bash
> cat a.f90
program main
    integer(3) :: i
end program

> ./src/bin/lfortran a.f90           
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2391
    LCompilers::print_stack_on_segfault();
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2355
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 949
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9599
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 5109
  File "../libasr/asr.h", line 5085
  File "../libasr/asr.h", line 5110
  File "../libasr/asr.h", line 4816
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 945
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5112
  File "../libasr/asr.h", line 4824
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3059
    declare_vars(x);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3399
    type = llvm_utils->get_type_from_ttype_t(
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1409
    llvm_type = getIntType(a_kind);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1624
    LCOMPILERS_ASSERT(false);
AssertFailed: false
```

**Comment by gxyd** [comment]
Probably should be already handled in AST -> ASR phase.

**Comment by gxyd** [comment]
Seems like the issue was partially handled in https://github.com/lfortran/lfortran/pull/1410. I'll try to see if I can come up with a general solution for this now.
