### ISSUE TITLE
[stdlib-string]: Fix handling of set in intrinsic `verify`

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#3477]
Towards: #3201 
```fortran
program main
	character(len=5) :: string = "hello"
	character(len=1) :: set(2) = ["l", "h"]
	integer :: last
	print*, verify(string, set)

end
```
```console
$ gfortran b.f90 && ./a.out
           1           2
$ lfortran b.f90
; ModuleID = 'LFortran'
source_filename = "LFortran"

@main.set = internal global [2 x i8*] zeroinitializer
@main.string = internal global i8* null
@0 = private unnamed_addr constant [6 x i8] c"hello\00", align 1
@1 = private unnamed_addr constant [2 x i8] c"l\00", align 1
@2 = private unnamed_addr constant [2 x i8] c"h\00", align 1
@3 = private unnamed_addr constant [2 x i8] c" \00", align 1
@4 = private unnamed_addr constant [2 x i8] c"\0A\00", align 1
@5 = private unnamed_addr constant [5 x i8] c"%d%s\00", align 1

define i32 @__module_lfortran_intrinsic_string_verify_kind4(i8** %string, i8** %set, i1* %back, i1* %is_back_present_) {
.entry:
  %back_val = alloca i1, align 1
  %i = alloca i32, align 4
  %j = alloca i32, align 4
  %matched = alloca i1, align 1
  %r = alloca i32, align 4
  store i1 false, i1* %back_val, align 1
  store i32 0, i32* %r, align 4
  %0 = load i1, i1* %is_back_present_, align 1
  br i1 %0, label %then, label %else

then:                                             ; preds = %.entry
  %1 = load i1, i1* %back, align 1
  store i1 %1, i1* %back_val, align 1
  br label %ifcont

else:                                             ; preds = %.entry
  br label %ifcont

ifcont:                                           ; preds = %else, %then
  %2 = load i1, i1* %back_val, align 1
  br i1 %2, label %then1, label %else11

then1:                                            ; preds = %ifcont
  %3 = load i8*, i8** %string, align 8
  %4 = alloca i8*, align 8
  store i8* %3, i8** %4, align 8
  %5 = call i32 @_lfortran_str_len(i8** %4)
  %6 = sub i32 %5, -1
  store i32 %6, i32* %i, align 4
  br label %loop.head

loop.head:                                        ; preds = %ifcont9, %then1
  %7 = load i32, i32* %i, align 4
  %8 = add i32 %7, -1
  %9 = icmp sge i32 %8, 1
  br i1 %9, label %loop.body, label %loop.end10

loop.body:                                        ; preds = %loop.head
  %10 = load i32, i32* %i, align 4
  %11 = add i32 %10, -1
  store i32 %11, i32* %i, align 4
  store i1 false, i1* %matched, align 1
  store i32 0, i32* %j, align 4
  br label %loop.head2

loop.head2:                                       ; preds = %ifcont6, %loop.body
  %12 = load i32, i32* %j, align 4
  %13 = add i32 %12, 1
  %14 = load i8*, i8** %set, align 8
  %15 = alloca i8*, align 8
  store i8* %14, i8** %15, align 8
  %16 = call i32 @_lfortran_str_len(i8** %15)
  %17 = icmp sle i32 %13, %16
  br i1 %17, label %loop.body3, label %loop.end

loop.body3:                                       ; preds = %loop.head2
  %18 = load i32, i32* %j, align 4
  %19 = add i32 %18, 1
  store i32 %19, i32* %j, align 4
  %20 = load i32, i32* %i, align 4
  %21 = load i8*, i8** %string, align 8
  %22 = call i8* @_lfortran_str_item(i8* %21, i32 %20)
  %23 = load i32, i32* %j, align 4
  %24 = load i8*, i8** %set, align 8
  %25 = call i8* @_lfortran_str_item(i8* %24, i32 %23)
  %26 = load i8, i8* %22, align 1
  %27 = load i8, i8* %25, align 1
  %28 = icmp eq i8 %26, %27
  br i1 %28, label %then4, label %else5

then4:                                            ; preds = %loop.body3
  store i1 true, i1* %matched, align 1
  br label %ifcont6

else5:                                            ; preds = %loop.body3
  br label %ifcont6

ifcont6:                                          ; preds = %else5, %then4
  br label %loop.head2

loop.end:                                         ; preds = %loop.head2
  %29 = load i1, i1* %matched, align 1
  %30 = xor i1 %29, true
  br i1 %30, label %then7, label %else8

then7:                                            ; preds = %loop.end
  %31 = load i32, i32* %i, align 4
  store i32 %31, i32* %r, align 4
  br label %return

unreachable_after_return:                         ; No predecessors!
  br label %ifcont9

else8:                                            ; preds = %loop.end
  br label %ifcont9

ifcont9:                                          ; preds = %else8, %unreachable_after_return
  br label %loop.head

loop.end10:                                       ; preds = %loop.head
  br label %ifcont25

else11:                                           ; preds = %ifcont
  store i32 0, i32* %i, align 4
  br label %loop.head12

loop.head12:                                      ; preds = %ifcont23, %else11
  %32 = load i32, i32* %i, align 4
  %33 = add i32 %32, 1
  %34 = load i8*, i8** %string, align 8
  %35 = alloca i8*, align 8
  store i8* %34, i8** %35, align 8
  %36 = call i32 @_lfortran_str_len(i8** %35)
  %37 = icmp sle i32 %33, %36
  br i1 %37, label %loop.body13, label %loop.end24

loop.body13:                                      ; preds = %loop.head12
  %38 = load i32, i32* %i, align 4
  %39 = add i32 %38, 1
  store i32 %39, i32* %i, align 4
  store i1 false, i1* %matched, align 1
  store i32 0, i32* %j, align 4
  br label %loop.head14

loop.head14:                                      ; preds = %ifcont18, %loop.body13
  %40 = load i32, i32* %j, align 4
  %41 = add i32 %40, 1
  %42 = load i8*, i8** %set, align 8
  %43 = alloca i8*, align 8
  store i8* %42, i8** %43, align 8
  %44 = call i32 @_lfortran_str_len(i8** %43)
  %45 = icmp sle i32 %41, %44
  br i1 %45, label %loop.body15, label %loop.end19

loop.body15:                                      ; preds = %loop.head14
  %46 = load i32, i32* %j, align 4
  %47 = add i32 %46, 1
  store i32 %47, i32* %j, align 4
  %48 = load i32, i32* %i, align 4
  %49 = load i8*, i8** %string, align 8
  %50 = call i8* @_lfortran_str_item(i8* %49, i32 %48)
  %51 = load i32, i32* %j, align 4
  %52 = load i8*, i8** %set, align 8
  %53 = call i8* @_lfortran_str_item(i8* %52, i32 %51)
  %54 = load i8, i8* %50, align 1
  %55 = load i8, i8* %53, align 1
  %56 = icmp eq i8 %54, %55
  br i1 %56, label %then16, label %else17

then16:                                           ; preds = %loop.body15
  store i1 true, i1* %matched, align 1
  br label %ifcont18

else17:                                           ; preds = %loop.body15
  br label %ifcont18

ifcont18:                                         ; preds = %else17, %then16
  br label %loop.head14

loop.end19:                                       ; preds = %loop.head14
  %57 = load i1, i1* %matched, align 1
  %58 = xor i1 %57, true
  br i1 %58, label %then20, label %else22

then20:                                           ; preds = %loop.end19
  %59 = load i32, i32* %i, align 4
  store i32 %59, i32* %r, align 4
  br label %return

unreachable_after_return21:                       ; No predecessors!
  br label %ifcont23

else22:                                           ; preds = %loop.end19
  br label %ifcont23

ifcont23:                                         ; preds = %else22, %unreachable_after_return21
  br label %loop.head12

loop.end24:                                       ; preds = %loop.head12
  br label %ifcont25

ifcont25:                                         ; preds = %loop.end24, %loop.end10
  br label %return

return:                                           ; preds = %ifcont25, %then20, %then7
  %60 = load i32, i32* %r, align 4
  ret i32 %60
}

declare i32 @_lfortran_str_len(i8**)

declare i8* @_lfortran_str_item(i8*, i32)

define i32 @main(i32 %0, i8** %1) {
.entry:
  %call_arg_value = alloca i1, align 1
  %array_bound = alloca i32, align 4
  call void @_lpython_set_argv(i32 %0, i8** %1)
  %__1_k = alloca i32, align 4
  %__libasr_created_variable_ = alloca i1, align 1
  %last = alloca i32, align 4
  %2 = call i8* (i32, ...) @_lfortran_malloc(i32 6)
  call void (i32, i8*, ...) @_lfortran_string_init(i32 6, i8* %2)
  store i8* %2, i8** @main.string, align 8
  call void @_lfortran_strcpy(i8** @main.string, i8* getelementptr inbounds ([6 x i8], [6 x i8]* @0, i32 0, i32 0), i8 0)
  %3 = load i8*, i8** @main.string, align 8
  br i1 true, label %then, label %else

then:                                             ; preds = %.entry
  store i32 1, i32* %array_bound, align 4
  br label %ifcont

else:                                             ; preds = %.entry
  br label %ifcont

ifcont:                                           ; preds = %else, %then
  %4 = load i32, i32* %array_bound, align 4
  store i32 %4, i32* %__1_k, align 4
  %5 = load i32, i32* %__1_k, align 4
  %6 = sub i32 %5, 1
  %7 = mul i32 1, %6
  %8 = add i32 0, %7
  %9 = getelementptr [2 x i8*], [2 x i8*]* @main.set, i32 0, i32 %8
  store i8* getelementptr inbounds ([2 x i8], [2 x i8]* @1, i32 0, i32 0), i8** %9, align 8
  %10 = load i32, i32* %__1_k, align 4
  %11 = add i32 %10, 1
  store i32 %11, i32* %__1_k, align 4
  %12 = load i32, i32* %__1_k, align 4
  %13 = sub i32 %12, 1
  %14 = mul i32 1, %13
  %15 = add i32 0, %14
  %16 = getelementptr [2 x i8*], [2 x i8*]* @main.set, i32 0, i32 %15
  store i8* getelementptr inbounds ([2 x i8], [2 x i8]* @2, i32 0, i32 0), i8** %16, align 8
  %17 = load i32, i32* %__1_k, align 4
  %18 = add i32 %17, 1
  store i32 %18, i32* %__1_k, align 4
  store i1 false, i1* %call_arg_value, align 1
  %19 = call i32 @__module_lfortran_intrinsic_string_verify_kind4(i8** @main.string, [2 x i8*]* @main.set, i1* %__libasr_created_variable_, i1* %call_arg_value)
  call void (i8*, ...) @_lfortran_printf(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @5, i32 0, i32 0), i32 %19, i8* getelementptr inbounds ([2 x i8], [2 x i8]* @4, i32 0, i32 0))
  ret i32 0
}

declare void @_lpython_set_argv(i32, i8**)

declare i8* @_lfortran_malloc(i32, ...)

declare void @_lfortran_string_init(i32, i8*, ...)

declare void @_lfortran_strcpy(i8**, i8*, i8)

declare void @_lfortran_printf(i8*, ...)
code generation error: asr_to_llvm: module failed verification. Error:
Call parameter type does not match function signature!
[2 x i8*]* @main.set
 i8**  %19 = call i32 @__module_lfortran_intrinsic_string_verify_kind4(i8** @main.string, [2 x i8*]* @main.set, i1* %__libasr_created_variable_, i1* %call_arg_value)



Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues. 
```

**Comment by gxyd** [comment]
I'll try to work on this issue.

**Comment by HarshitaKalani** [comment]
```console
$ lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2389, in ??
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2350, in main_app(int, char**)
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 948, in ??
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 359, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9784, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 311, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 167, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/array_op.cpp", line 2099, in LCompilers::pass_replace_array_op(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    v.visit_TranslationUnit(unit);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/array_op.cpp", line 1683, in LCompilers::ArrayOpVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*item.second);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5160, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayOpVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4871, in ??
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/array_op.cpp", line 1720, in LCompilers::ArrayOpVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    transform_stmts(xx.m_body, xx.n_body);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/array_op.cpp", line 1647, in LCompilers::ArrayOpVisitor::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    visit_stmt(*m_body[i]);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5177, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayOpVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4911, in ??
    case stmtType::Print: { v.visit_Print((const Print_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 47324, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayOpVisitor>::visit_Print(LCompilers::ASR::Print_t const&)
    self().call_replacer();
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/array_op.cpp", line 1627, in LCompilers::ArrayOpVisitor::call_replacer()
    replacer.replace_expr(*current_expr);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 45943, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceArrayOp>::replace_expr(LCompilers::ASR::expr_t*)
    self().replace_IntrinsicElementalFunction(down_cast<ASR::IntrinsicElementalFunction_t>(x));
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/array_op.cpp", line 1427, in LCompilers::ReplaceArrayOp::replace_IntrinsicElementalFunction(LCompilers::ASR::IntrinsicElementalFunction_t*)
    replace_intrinsic_function(x);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/array_op.cpp", line 1368, in void LCompilers::ReplaceArrayOp::replace_intrinsic_function<LCompilers::ASR::IntrinsicElementalFunction_t>(LCompilers::ASR::IntrinsicElementalFunction_t*)
    if( ASRUtils::extract_physical_type(arr_type) ==
LCompilersException: Cannot extract the physical type of 0 type.
```

**Comment by HarshitaKalani** [comment]
Works when we make the last argument an array.
```console
program main
	character(len=5) :: string = "hello"
	character(len=1) :: set(2) = ["l", "h"]
	print*, verify(string, set, kind= [4, 4] )
end
```
I think the issue is present in the `array_op.cpp` file
