### ISSUE TITLE
Implement compile time evaluation of elemental functions

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#3485]
```fortran
program t
integer, parameter :: dp = kind(0.d0)
real(dp), parameter :: A(*) = [1._dp, 2._dp, 3._dp]
real(dp), parameter :: B(*) = sin(A)
print *, A
print *, B
end program
```
This gives:
```console
$ lfortran a.f90 
semantic error: Initialization of `B` must reduce to a compile time constant.
 --> a.f90:4:1
  |
4 | real(dp), parameter :: B(*) = sin(A)
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
And other similar operations, like `B(*) = A + 2` etc.

**Comment by certik** [comment]
Even the simplest `B(*) = A` does not work yet:
```console
$ lfortran a.f90 
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2391
    LCompilers::print_stack_on_segfault();
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2355
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 949
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9662
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 5111
  File "../libasr/asr.h", line 5087
  File "../libasr/asr.h", line 5112
  File "../libasr/asr.h", line 4818
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 945
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5114
  File "../libasr/asr.h", line 4826
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3063
    declare_vars(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3534
    }
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3129
    fill_array_details(ptr, llvm_data_type, m_dims, n_dims, is_data_only);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 447
    visit_expr(*(m_dim.m_start));
  File "../libasr/asr.h", line 5178
  File "../libasr/asr.h", line 5178
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by Pranavchiku** [comment]
I think for intrinsic functions one has to do something like https://github.com/lfortran/lfortran/pull/2918/commits/d9dc188fb05e7321da545c98fec8bf0dced62a48, part of PR #2918.

**Comment by Pranavchiku** [comment]
I have made progress on this, cases shown below works, will polish and open PR soon.
```fortran
    real, parameter :: A(*) = sin([1., 2., 3., 4., 5.])
    real, parameter :: B(*) = sin(A)
    real, parameter :: C(*) = abs(cos(A))
```

**Comment by gxyd** [comment]
This issue seems to be working now though.

**Comment by Pranavchiku** [comment]
let's add a test and close this.
