### ISSUE TITLE
same function param added multiple times in `function_call_in_declaration` pass

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3537]
With #3519 

```fortran
program main
  real :: x(5, 5)
  real :: res(5)
  x = 4.59
  res = corr_2_rsp_rsp(x, 1)
  print *, res
  if (any(abs(res - 21.0681019) > 1e-6)) error stop
contains
  function corr_2_rsp_rsp(x, dim, mask) result(res)
    real, intent(in) :: x(:, :)
    integer, intent(in) :: dim
    logical, intent(in), optional :: mask
    real :: res(merge(size(x, 1), size(x, 2), mask = 1<dim))

    res = x(1, 1) * x(1, 1)
  end function corr_2_rsp_rsp
end program
```

```console
% lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2391
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2355
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 949
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9656
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 306
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 164
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/function_call_in_declaration.cpp", line 417
    FunctionTypeVisitor v(al);
  File "../libasr/asr.h", line 46364
  File "../libasr/asr.h", line 5114
  File "../libasr/asr.h", line 4826
  File "../libasr/asr.h", line 46373
  File "../libasr/asr.h", line 5114
  File "../libasr/asr.h", line 4827
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/function_call_in_declaration.cpp", line 408
    current_scope = x.m_symtab;
  File "../libasr/asr.h", line 5284
  File "../libasr/asr.h", line 5034
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/function_call_in_declaration.cpp", line 397
    current_expr = const_cast<ASR::expr_t**>(&(ASR::down_cast<ASR::Array_t>(x.m_return_var_type)->m_dims[i].m_length));
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/function_call_in_declaration.cpp", line 302
    replacer.replace_expr(*current_expr);
  File "../libasr/asr.h", line 45343
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/function_call_in_declaration.cpp", line 233
    sd.duplicate_symbol(var->m_v, new_scope);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.h", line 4083
    destination_symtab->add_symbol(new_symbol_name, new_symbol);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_scopes.h", line 76
    LCOMPILERS_ASSERT(scope.find(name) == scope.end())
AssertFailed: scope.find(name) == scope.end()
```

**Comment by Pranavchiku** [comment]
I have a fix for this ready.

```diff
--- a/src/libasr/pass/function_call_in_declaration.cpp
+++ b/src/libasr/pass/function_call_in_declaration.cpp
@@ -149,6 +149,15 @@ public:
         }
     }
 
+    bool exists_in_arginfo(int param_number, std::vector<ArgInfo>& indicies) {
+        for (auto arg: indicies) {
+            if (arg.arg_number == param_number) {
+                return true;
+            }
+        }
+        return false;
+    }
+
     void helper_get_arg_indices_used(ASR::expr_t* arg, std::vector<ArgInfo>& indicies) {
         if (is_a<ASR::ArrayPhysicalCast_t>(*arg)) {
             ASR::ArrayPhysicalCast_t* cast = ASR::down_cast<ASR::ArrayPhysicalCast_t>(arg);
@@ -161,7 +170,9 @@ public:
         } else if (is_a<ASR::FunctionParam_t>(*arg)) {
             ASR::FunctionParam_t* param = ASR::down_cast<ASR::FunctionParam_t>(arg);
             ArgInfo info = {static_cast<int>(param->m_param_number), param->m_type, current_function->m_args[param->m_param_number], arg};
-            indicies.push_back(info);
+            if (!exists_in_arginfo(param->m_param_number, indicies)){
+                indicies.push_back(info);
+            }
         } else if (is_a<ASR::ArraySize_t>(*arg)) {
             ASR::ArraySize_t* size = ASR::down_cast<ASR::ArraySize_t>(arg);
             helper_get_arg_indices_used(size->m_v, indicies);
```
