### ISSUE TITLE
runtime values for dim argument is not supported yet

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3540]
```fortran
program main
    real :: a(4, 4)
    integer :: dim
    a = 1.0
    dim = 1
    print *, sum(a, dim)
end program
```

```console
% lfortran b.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2391
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2355
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 949
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9656
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 306
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 164
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/intrinsic_function.cpp", line 383
    u.visit_TranslationUnit(unit);
  File "../libasr/asr.h", line 46364
  File "../libasr/asr.h", line 5114
  File "../libasr/asr.h", line 4827
  File "../libasr/asr.h", line 46403
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/intrinsic_function.cpp", line 363
    visit_stmt(*m_body[i]);
  File "../libasr/asr.h", line 5131
  File "../libasr/asr.h", line 4851
  File "../libasr/asr.h", line 46596
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/intrinsic_function.cpp", line 346
    replacer.replace_expr(*current_expr);
  File "../libasr/asr.h", line 45335
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/intrinsic_function.cpp", line 293
    throw LCompilersException("Runtime values for dim argument is not supported yet.");
LCompilersException: Runtime values for dim argument is not supported yet.
```

**Comment by Pranavchiku** [comment]
I am not aware of any possible workarounds, this is a blocker for `stdlib stats`.

**Comment by certik** [comment]
First: We should give a regular semantic error, not LCompilersException.

**Comment by certik** [comment]
Looks like we'll need to implement a runtime `dim` attribute. To do that, we just need to extend the machinery to handle it by instantiating general loop structure that can handle the `dim` attribute at runtime.

**Comment by Pranavchiku** [comment]
cc @czgdp1807

**Comment by Pranavchiku** [comment]
I have made progress on this, few tests fail will open PR soon.

**Comment by Thirumalai-Shaktivel** [comment]
Great job!
