### ISSUE TITLE
Bug: Passing incorrect number of arguments leads to Assert failure

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lfortran/lfortran#3591]
```console
% cat examples/expr2.f90 
program expr2
implicit none

call my_func(5)

contains

    subroutine my_func()
        print *, "hi"
    end subroutine

end program
% gfortran examples/expr2.f90
examples/expr2.f90:4:15:

    4 | call my_func(5)
      |               1
Error: More actual than formal arguments in procedure call at (1)
% lfortran examples/expr2.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/bin/lfortran.cpp", line 2391
    LCompilers::print_stack_on_segfault();
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/bin/lfortran.cpp", line 2355
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/bin/lfortran.cpp", line 907
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 253
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 275
    compiler_options.symtab_only, compiler_options);
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 127
    if (res.ok) {
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3400
    b.is_body_visitor = true;
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 143
    visit_ast(*x.m_items[i]);
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/lfortran/ast.h", line 4848
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/lfortran/ast.h", line 4804
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/lfortran/ast.h", line 4851
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/lfortran/ast.h", line 4438
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1510
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 114
    this->visit_stmt(*m_body[i]);
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/lfortran/ast.h", line 4894
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/lfortran/ast.h", line 4568
    case stmtType::Stop: { v.visit_Stop((const Stop_t &)x); return; }
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2810
    ASRUtils::set_absent_optional_arguments_to_null(args, f, al, v_expr, nopass);
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/libasr/asr_utils.h", line 2614
    LCOMPILERS_ASSERT(args.size() + offset == (func->n_args));
AssertFailed: args.size() + offset == (func->n_args)
```

We should rather report a nice Semantic Error message like `gfortran` that the number of arguments passed do not match to that of the number of available parameters.

**Comment by gxyd** [comment]
while trying to understand where to fix this issue, found another issue:
```f90
program expr2
    implicit none
    print *, helloWorld("apple")  ! incorrect type being passes for the only argument

contains
    real function helloWorld(x)
        real, intent(in) :: x
        helloWorld = x + 1
    end function helloWorld

end program expr2
```

raises an error:
```bash
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4894
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4564
    case stmtType::Return: { v.visit_Return((const Return_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2934
    visit_expr(*x.m_values[i]);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4945
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4602
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5863
    tmp = create_FunctionCallWithASTNode(x, v, args);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4181
    return create_Function(x.base.base.loc, args, v);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4133
    args.p, args.size(), return_type, value, nullptr);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/asr_utils.h", line 5147
    Call_t_body(al, a_name, a_args, n_args, a_dt, nullptr, false, false);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/asr_utils.h", line 5140
    }
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x180353a1f
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x180446c1f
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x180477583
Abort: Signal SIGABRT (abort) received
```

probably we don't check for the expected types.
