### ISSUE TITLE
Support runtime dim for intrinsic `Count`

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3630]
The current implementation of count expects value of `dim` at compile time.

```fortran
program main
logical :: mask(3, 4)
integer :: dim
mask = .true.
dim = 2
print *, count(mask, dim)
end program
```

```console
% gfortran a.f90 && ./a.out
           4           4           4
% lfortran a.f90 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2391
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2355
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 949
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9739
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 306
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 164
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/intrinsic_function.cpp", line 427
    v.visit_TranslationUnit(unit);
  File "../libasr/asr.h", line 46612
  File "../libasr/asr.h", line 5139
  File "../libasr/asr.h", line 4850
  File "../libasr/asr.h", line 46624
  File "../libasr/asr.h", line 46606
  File "../libasr/asr.h", line 5156
  File "../libasr/asr.h", line 4889
  File "../libasr/asr.h", line 46945
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/intrinsic_function.cpp", line 147
    replacer.replace_expr(*current_expr);
  File "../libasr/asr.h", line 45587
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/intrinsic_function.cpp", line 117
    global_scope, arg_types, x->m_type, new_args, x->m_overload_id);
  File "../libasr/pass/intrinsic_array_function_registry.h", line 1902
  File "../libasr/asr.h", line 41
AssertFailed: is_a<T>(*f)
```

**Comment by Pranavchiku** [comment]
I have made progress on this, will open PR soon.

**Comment by YashNagda17** [comment]
MRE works on current main.
Let's add a test to close this issue:
```
$ lfortran a.f90 
4    4    4
```
