### ISSUE TITLE
`lfortran --fast` fails for fastgPT

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#3661]
There has been a regression from LFortran 0.20.3 to 0.33.1, now `--fast` does not work with fastGPT anymore: https://github.com/certik/fastGPT/pull/73

We need to create a minimal reproducible example and fix it.

**Comment by certik** [comment]
Here is the failure with the latest master:
```console
[  5%] Building Fortran object CMakeFiles/fastgpt.dir/linalg_c.f90.o
[ 11%] Building Fortran object CMakeFiles/fastgpt.dir/tokenizer.f90.o
[ 17%] Building Fortran object CMakeFiles/fastgpt.dir/gpt2.f90.o
[ 23%] Building Fortran object CMakeFiles/fastgpt.dir/omp.f90.o
[ 29%] Building Fortran object CMakeFiles/fastgpt.dir/driver.f90.o
warning: Argument `access` isn't supported yet
  --> /Users/ondrej/repos/fastGPT/driver.f90:80:1
   |
80 | open(newunit=u, file=filename, form="unformatted", access="stream", status="old")
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
[ 35%] Building C object CMakeFiles/fastgpt.dir/linalg_accelerate.c.o
[ 41%] Linking Fortran static library libfastgpt.a
[ 41%] Built target fastgpt
[ 47%] Building Fortran object CMakeFiles/gpt2.dir/main.f90.o
Assertion failed: (Ty && "Invalid GetElementPtrInst indices for type!"), function checkGEPType, file Instructions.h, line 897.
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2386
    LCompilers::print_stack_on_segfault();
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2318
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 948
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 359
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9745
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 5159
  File "../libasr/asr.h", line 5135
  File "../libasr/asr.h", line 5160
  File "../libasr/asr.h", line 4864
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 931
    ASR::symbol_t *mod = x.m_symtab->get_symbol(item);
  File "../libasr/asr.h", line 5162
  File "../libasr/asr.h", line 4872
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2989
    finish_module_init_function_prototype(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3976
    ASR::Function_t *s = ASR::down_cast<ASR::Function_t>(item.second);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3732
    visit_procedures(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3929
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5179
  File "../libasr/asr.h", line 4914
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7461
    tmp = arr_descr->get_pointer_to_data(tmp);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 537
    return llvm_utils->create_gep(arr, 0);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1567
    return LLVM::CreateGEP(*builder, ds, idx_vec);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 27
    return builder.CreateGEP(t2, x, idx);
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/IRBuilder.h", line 1773
    return Insert(GetElementPtrInst::Create(Ty, Ptr, IdxList), Name);
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 943
    NameStr, InsertBefore);
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1151
    }
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1143
    : Instruction(getGEPReturnType(PointeeType, Ptr, IdxList), GetElementPtr,
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1074
    Type *PtrTy = PointerType::get(checkGEPType(getIndexedType(ElTy, IdxList)),
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 897
    assert(Ty && "Invalid GetElementPtrInst indices for type!");
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18024972b
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18024a313
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x18030ceaf
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Abort: Signal SIGABRT (abort) received

make[2]: *** [CMakeFiles/gpt2.dir/main.f90.o] Abort trap: 6
make[1]: *** [CMakeFiles/gpt2.dir/all] Error 2
make: *** [all] Error 2
```
