### ISSUE TITLE
Failure of elemental intrinsic functions on array input

### ISSUE THREAD

**Issue by gxyd** [lfortran/lfortran#3673]
```f90

program main
    implicit none
    print *, sign([1.2, 2.2, 3.3, 4.4], 1.2)  ! fails
    print *, floor([1.2, 2.2, 3.3, 4.4]) ! fails
    print *, ceiling([1.2, 2.2, 3.3, 4.4]) ! fails
end program main

```

each of the above elemental intrinsic function fail with an error:
```bash
Traceback (most recent call last):
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2386
    LCompilers::print_stack_on_segfault();
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2350
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 906
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 252
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 274
    compiler_options.symtab_only, compiler_options);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 126
    if (res.ok) {
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3585
    b.is_body_visitor = true;
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 143
    visit_ast(*x.m_items[i]);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4848
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4804
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4851
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4438
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1546
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 114
    this->visit_stmt(*m_body[i]);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4894
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4564
    case stmtType::Return: { v.visit_Return((const Return_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3058
    visit_expr(*x.m_values[i]);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4945
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4602
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5617
    bool is_function = true;
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5191
    tmp = create_func(al, x.base.base.loc, args, diag);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/intrinsic_function_registry_util.h", line 1286
    m_value = eval_Floor(al, loc, return_type, args_values, diag);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/intrinsic_functions.h", line 1922
    ASR::RealConstant_t* x = ASR::down_cast<ASR::RealConstant_t>(args[0]);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/asr.h", line 41
    LCOMPILERS_ASSERT(is_a<T>(*f));
```

**Comment by gxyd** [comment]
I'll try to see if I can understand the cause of issue.

**Comment by Pranavchiku** [comment]
The trouble here is that all these functions accepts two arguments and the check `args.size() == 1` prevents compile time broadcast of these, however if you do `print *, floor([x, y])` it works well because of `ArrayConstructor` usage. A correct fix will be improving `compiletime_broadcast_elemental_intrinsic` to perform for `n` arguments, this won't be trick to do. Let me know if you need any help.
