### ISSUE TITLE
Stdlib: Bug in elemental subroutine

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lfortran/lfortran#3677]
```console
% cat examples/expr4.f90 
program expr2
    implicit none

    integer :: v_list(5)
    call unused_dummy_argument(v_list)
    print *, "ok"

    contains

    elemental subroutine unused_dummy_argument(dummy)
        class(*), intent(in) :: dummy
        associate(dummy => dummy); end associate
    end subroutine

end program
% gfortran examples/expr4.f90        
% ./a.out 
 ok
% lfortran_in_main examples/expr4.f90 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/bin/lfortran.cpp", line 2386
    LCompilers::print_stack_on_segfault();
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/bin/lfortran.cpp", line 2350
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/bin/lfortran.cpp", line 948
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/lfortran/fortran_evaluator.cpp", line 359
    compiler_options, run_fn, infile);
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/libasr/codegen/asr_to_llvm.cpp", line 9746
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 5163
  File "../libasr/asr.h", line 5139
  File "../libasr/asr.h", line 5164
  File "../libasr/asr.h", line 4868
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/libasr/codegen/asr_to_llvm.cpp", line 945
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5166
  File "../libasr/asr.h", line 4876
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/libasr/codegen/asr_to_llvm.cpp", line 3071
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5183
  File "../libasr/asr.h", line 4927
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/libasr/codegen/asr_to_llvm.cpp", line 8803
    std::vector<llvm::Value *> args2 = convert_call_args(x, is_method);
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/libasr/codegen/asr_to_llvm.cpp", line 8444
    tmp = convert_to_polymorphic_arg(tmp,
  File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/libasr/codegen/asr_to_llvm.cpp", line 8563
    llvm::Value* type_id_addr = llvm_utils->create_gep(abstract_, 0);
  File "../libasr/asr.h", line 41
AssertFailed: is_a<T>(*f)
```

**Comment by gxyd** [comment]
@certik (or any other team member) for who knows the asr_to_llvm code better, I would like to get an understand of the code for it.
