### ISSUE TITLE
code generation error on array addressing via array, sext only operates on integer

### ISSUE THREAD

**Issue by BlameTroi** [lfortran/lfortran#3695]
lfortran 0.34.0

I was working through some example code that used array addressing of arrays. The code works with gfortran 13 but won't compile on lfortran. In the following small program, the lines `write(*,*) somearray(arrayofsubs)` produce errors, but if you comment them and uncomment the lines following them, lfortran compiles and runs as expected. I don't know if the problem is more with the write statement or the array via array addressing.

```
program lfsexting
   ! sext only operates on integer in lfortran
   ! compiles and runs with gfortran
   integer, dimension(1)   :: maxtemp
   integer, dimension(28)  :: feb
   integer, dimension(365) :: nums
   real, dimension(365)    :: x, temps
   integer                 :: i
   nums = [(real(i), i=1, 365)]
   x = nums / 365.0
   do i = 1, 365
      temps(i) = 35.0 * sin(3.14159 * x(i))
   end do
   temps = 35.0 * sin(x * 3.14159)
   feb = [(i, i=32, 59)]
   write (*, *) temps(feb)
!   write (*, *) temps(32:59)
   maxtemp = maxloc(temps)
   write (*, *) temps(maxtemp)
!   write (*, *) temps(maxtemp(1))
end program lfsexting
```

Full output attached.
[out.txt](https://github.com/lfortran/lfortran/files/14735870/out.txt)

**Comment by certik** [comment]
Thanks! Indeed, the following works:
```fortran
program lfsexting
   ! sext only operates on integer in lfortran
   ! compiles and runs with gfortran
   integer, dimension(1)   :: maxtemp
   integer, dimension(28)  :: feb
   integer, dimension(365) :: nums
   real, dimension(365)    :: x, temps
   integer                 :: i
   nums = [(real(i), i=1, 365)]
   x = nums / 365.0
   do i = 1, 365
      temps(i) = 35.0 * sin(3.14159 * x(i))
   end do
   temps = 35.0 * sin(x * 3.14159)
   feb = [(i, i=32, 59)]
!   write (*, *) temps(feb)
   write (*, *) temps(32:59)
   maxtemp = maxloc(temps)
!   write (*, *) temps(maxtemp)
   write (*, *) temps(maxtemp(1))
end program lfsexting
```
But uncommenting any of the write statements will fail, for example with:
```console
$ lfortran a.f90
Assertion failed: (V->getType()->isIntOrIntVectorTy() && DestTy->isIntOrIntVectorTy() && "Can only sign extend/truncate integers!"), function CreateSExtOrTrunc, file IRBuilder.h, line 1991.
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2386
    LCompilers::print_stack_on_segfault();
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2350
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 948
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 359
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9746
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 5163
  File "../libasr/asr.h", line 5139
  File "../libasr/asr.h", line 5164
  File "../libasr/asr.h", line 4868
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 945
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5166
  File "../libasr/asr.h", line 4876
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3071
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5183
  File "../libasr/asr.h", line 4922
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7668
    handle_print(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7956
    compute_fmt_specifier_and_arg(fmt, args, x.m_values[i], x.base.base.loc);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7772
    this->visit_expr_wrapper(v, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5186
    this->visit_expr(*x);
  File "../libasr/asr.h", line 5231
  File "../libasr/asr.h", line 5017
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2364
    tmp = arr_descr->get_single_element(array, indices, x.n_args,
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 634
    idx = cmo_convertor_single_element_data_only(llvm_diminfo, m_args, n_args, check_for_bounds, is_unbounded_pointer_to_data);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 606
    curr_llvm_idx = builder->CreateSExtOrTrunc(curr_llvm_idx, llvm::Type::getInt32Ty(context));
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/IRBuilder.h", line 1989
    assert(V->getType()->isIntOrIntVectorTy() &&
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18024972b
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18024a313
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x18030ceaf
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Abort: Signal SIGABRT (abort) received

zsh: abort      lfortran a.f90
```
We need to fix it.
