### ISSUE TITLE
Implement 'Where'

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#370]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/475

Follow `1 10.2.3 Masked array assignment – WHERE` on pg. 184.
## Example

```fortran
program main
  real :: x(10)
  x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  where (x/=5)
     x = 32.0
  elsewhere
     x = 0.0
  end where
  print *, x
end program
```
### Stacktrace
```bash
Traceback (most recent call last):
  Binary file "/users/home/rog32/Git/Github/Fortran/mylf/inst/bin/lfortran", in _start()
  Binary file "/lib64/libc.so.6", in __libc_start_main()
  File "/users/home/rog32/Git/Github/Fortran/mylf/src/bin/lfortran.cpp", line 1219, in main()
    return compile_to_object_file(arg_file, outfile, false,
  File "/users/home/rog32/Git/Github/Fortran/mylf/src/bin/lfortran.cpp", line 594, in compile_to_object_file()
    result = fe.get_asr2(input);
  File "/users/home/rog32/Git/Github/Fortran/mylf/src/lfortran/codegen/evaluator.cpp", line 478, in LFortran::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    asr = ast_to_asr(al, *ast, symbol_table);
  File "/users/home/rog32/Git/Github/Fortran/mylf/src/lfortran/semantics/ast_to_asr.cpp", line 35, in LFortran::ast_to_asr(Allocator&, LFortran::AST::TranslationUnit_t&, LFortran::SymbolTable*)
    b.visit_TranslationUnit(ast);
  File "/users/home/rog32/Git/Github/Fortran/mylf/src/lfortran/semantics/asr_body_visitor.cpp", line 28, in LFortran::BodyVisitor::visit_TranslationUnit(LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/users/home/rog32/Git/Github/Fortran/mylf/src/lfortran/ast.h", line 4006, in LFortran::AST::BaseVisitor<LFortran::BodyVisitor>::visit_ast(LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/users/home/rog32/Git/Github/Fortran/mylf/src/lfortran/ast.h", line 3968, in void LFortran::AST::visit_ast_t<LFortran::BodyVisitor>(LFortran::AST::ast_t const&, LFortran::BodyVisitor&)
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/users/home/rog32/Git/Github/Fortran/mylf/src/lfortran/ast.h", line 4009, in LFortran::AST::BaseVisitor<LFortran::BodyVisitor>::visit_mod(LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/users/home/rog32/Git/Github/Fortran/mylf/src/lfortran/ast.h", line 3660, in void LFortran::AST::visit_mod_t<LFortran::BodyVisitor>(LFortran::AST::mod_t const&, LFortran::BodyVisitor&)
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/users/home/rog32/Git/Github/Fortran/mylf/src/lfortran/semantics/asr_body_visitor.cpp", line 575, in LFortran::BodyVisitor::visit_Program(LFortran::AST::Program_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/users/home/rog32/Git/Github/Fortran/mylf/src/lfortran/ast.h", line 4047, in LFortran::AST::BaseVisitor<LFortran::BodyVisitor>::visit_stmt(LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/users/home/rog32/Git/Github/Fortran/mylf/src/lfortran/ast.h", line 3795, in void LFortran::AST::visit_stmt_t<LFortran::BodyVisitor>(LFortran::AST::stmt_t const&, LFortran::BodyVisitor&)
    case stmtType::Where: { v.visit_Where((const Where_t &)x); return; }
  File "/users/home/rog32/Git/Github/Fortran/mylf/src/lfortran/ast.h", line 4088, in LFortran::AST::BaseVisitor<LFortran::BodyVisitor>::visit_Where(LFortran::AST::Where_t const&)
    void visit_Where(const Where_t & /* x */) { throw LFortran::LFortranException("visit_Where() not implemented"); }
LFortranException: visit_Where() not implemented
```
## Standard
Note that the relevant standard can be found here: [18-007r1.pdf](/uploads/973db2bfcc64cd2a397f823c32718b39/18-007r1.pdf)

**Comment by HarshitaKalani** [comment]
This works with the latest main!

**Comment by certik** [comment]
Yes, this now works:
```
$ lfortran a.f90 
3.20000000e+01 3.20000000e+01 3.20000000e+01 3.20000000e+01 0.00000000e+00 3.20000000e+01 3.20000000e+01 3.20000000e+01 3.20000000e+01 3.20000000e+01 
```
