### ISSUE TITLE
Compile `stdlib_stats_var`

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3700]
Branch: https://github.com/czgdp1807/stdlib/tree/lf-stats-var

Current status:

```console
 % lfortran stdlib_stats_var.f90 --show-llvm
ASR verify pass error: Allocate should only be called with  Allocatable or Pointer type inputs, found c64[:]
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2386
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2270
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 846
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 291
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 313
    diagnostics, lm.files.back().in_filename);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 359
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9739
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 307
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 169
    throw LCompilersException("Verify failed in the pass: "
LCompilersException: Verify failed in the pass: intrinsic_function
```

**Comment by Pranavchiku** [comment]
This is compiled to LLVM, closing it.
