### ISSUE TITLE
dim attribute for mask of rank 1 is incorrectly handled in intrinsic count

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3702]
```fortran
program main
integer, parameter :: n = 10
logical :: x(n)
integer :: res

x = .false.
x(1:5) = .true.
res = count(x, 1)
print *, res
end program main
```

```console
% lfortran b.f90
ASR verify pass error: FunctionCall::m_name _lcompilers_count must be returning a non-void value.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2386
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2350
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 948
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 359
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9739
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 307
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 169
    throw LCompilersException("Verify failed in the pass: "
LCompilersException: Verify failed in the pass: intrinsic_function
```

I have fix for this ready, will open PR when everything is synced

```diff
diff --git a/src/libasr/pass/intrinsic_array_function_registry.h b/src/libasr/pass/intrinsic_array_function_registry.h
index ca2103175..2b65a3263 100644
--- a/src/libasr/pass/intrinsic_array_function_registry.h
+++ b/src/libasr/pass/intrinsic_array_function_registry.h
@@ -1826,7 +1826,8 @@ namespace Count {
             dim_ = args[1];
             kind = args[2];
         }
-
+        ASR::dimension_t* array_dims = nullptr;
+        int array_rank = extract_dimensions_from_ttype(ASRUtils::expr_type(args[0]), array_dims);
         ASR::ttype_t* mask_type = ASRUtils::expr_type(mask);
         if ( dim_ != nullptr ) {
             size_t dim_rank = ASRUtils::extract_n_dims_from_ttype(ASRUtils::expr_type(dim_));
@@ -1838,6 +1839,9 @@ namespace Count {
 
             overload_id = id_mask_dim;
         }
+        if (array_rank == 1) {
+            overload_id = id_mask;
+        }
         if ( kind != nullptr) {
             size_t kind_rank = ASRUtils::extract_n_dims_from_ttype(ASRUtils::expr_type(kind));
             if (kind_rank != 0) {
@@ -1881,7 +1885,7 @@ namespace Count {
 
         Vec<ASR::expr_t*> arr_intrinsic_args; arr_intrinsic_args.reserve(al, 1);
         arr_intrinsic_args.push_back(al, mask);
-        if( dim_ ) {
+        if( dim_ && array_rank != 1) {
             arr_intrinsic_args.push_back(al, dim_);
         }
         return make_IntrinsicArrayFunction_t_util(al, loc,

```

**Comment by Pranavchiku** [comment]
This fix are super easy when we have MRE with us, the time consuming process is creating MRE. If @HarshitaKalani you are interested you may take up any of stdlib stats package and start sending MREs for it, it will be really helpful. I think you can go ahead and fix those even, these are all really simple. Let me know if you are willing to work on, I'll post detailed instruction on tracker.

**Comment by HarshitaKalani** [comment]
Sure @Pranavchiku , will be happy to help.
