### ISSUE TITLE
Compile `stdlib_stats_mean`

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#3724]
https://github.com/HarshitaKalani/stdlib-fortran-lang/commits/lf_stats_mean_01

**Comment by HarshitaKalani** [comment]
```console
[ 18%] Building Fortran object src/CMakeFiles/fortran_stdlib.dir/stdlib_stats_mean.f90.o
[ 19%] Building Fortran object src/CMakeFiles/fortran_stdlib.dir/stdlib_sorting.f90.o
[ 20%] Building Fortran object src/CMakeFiles/fortran_stdlib.dir/stdlib_ansi.f90.o
[ 21%] Building Fortran object src/CMakeFiles/fortran_stdlib.dir/stdlib_bitsets_64.f90.o
semantic error: Function 'my_merge' not found or not implemented yet (if it is intrinsic)
   --> /home/harshita/stdlib/src/stdlib_stats_mean.f90:189:27
    |
189 |           real(sp) :: res(my_merge(size(x, 1), size(x, 2), mask=1<dim))
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
make[2]: *** [src/CMakeFiles/fortran_stdlib.dir/build.make:478: src/CMakeFiles/fortran_stdlib.dir/stdlib_stats_mean.f90.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by HarshitaKalani** [comment]
```console
semantic error: reshape accepts only 2 arguments, got 3 arguments instead.
  --> /home/harshita/stdlib/test/stats/test_mean.f90:19:44
   |
19 |     integer(int8) :: d4_int8(3, 2, 3, 2) = reshape(d1_int8, [3, 2, 3, 2], [integer(int8) :: 3])
   |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
make[2]: *** [test/stats/CMakeFiles/test_mean.dir/build.make:79: test/stats/CMakeFiles/test_mean.dir/test_mean.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1805: test/stats/CMakeFiles/test_mean.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by HarshitaKalani** [comment]
```console
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 6805, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_Compare(LCompilers::LFortran::AST::Compare_t const&)
    CommonVisitorMethods::visit_Compare(al, x, left, right, tmp,
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 216, in LCompilers::LFortran::CommonVisitorMethods::visit_Compare(Allocator&, LCompilers::LFortran::AST::Compare_t const&, LCompilers::ASR::expr_t*&, LCompilers::ASR::expr_t*&, LCompilers::ASR::asr_t*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, LCompilers::SymbolTable*, LCompilers::SetChar&, LCompilers::SetChar&, LCompilers::CompilerOptions const&)
    int64_t left_value = ASR::down_cast<ASR::IntegerConstant_t>(
AssertFailed: is_a<T>(*f)
make[2]: *** [test/stats/CMakeFiles/test_mean.dir/build.make:79: test/stats/CMakeFiles/test_mean.dir/test_mean.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1805: test/stats/CMakeFiles/test_mean.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by Pranavchiku** [comment]
Let me know if you face any blocker

**Comment by Pranavchiku** [comment]
This is at high priority atm

**Comment by HarshitaKalani** [comment]
```console
ASR verify pass error: Input to Sum intrinsic must always be an array
    --> /home/harshita/stdlib/test/stats/test_mean.f90:1834:23 - 1835:62
     |
1834 |                        , sum(abs(mean(d2_cdp, 1) -&
     |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
     |
1835 |                        sum(d2_cdp, 1)/real(size(d2_cdp, 1), dp))) < dptol&
     | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ failed here


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
make[2]: *** [test/stats/CMakeFiles/test_mean.dir/build.make:79: test/stats/CMakeFiles/test_mean.dir/test_mean.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1805: test/stats/CMakeFiles/test_mean.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by Pranavchiku** [comment]
You will have to store input to abs in a temp array and pass that to abs

Take a look at “XX: abs(X-mean)….” Workaround for stdlib_stats_var

**Comment by HarshitaKalani** [comment]
```console
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2389, in ??
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2318, in main_app(int, char**)
    return compile_to_object_file(arg_file, outfile, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 948, in ??
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 359, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9784, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 311, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 167, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/intrinsic_function.cpp", line 428, in LCompilers::pass_replace_intrinsic_function(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    v.visit_TranslationUnit(unit);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 46990, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5160, in LCompilers::ASR::BaseVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4872, in ??
    case symbolType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 47008, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_Module(LCompilers::ASR::Module_t const&)
    this->visit_symbol(*a.second);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5160, in LCompilers::ASR::BaseVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4873, in ??
    case symbolType::Function: { v.visit_Function((const Function_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 47028, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_Function(LCompilers::ASR::Function_t const&)
    self().transform_stmts(xx.m_body, xx.n_body);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 46983, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    self().visit_stmt(*m_body[i]);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5177, in LCompilers::ASR::BaseVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4909, in ??
    case stmtType::If: { v.visit_If((const If_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 47309, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_If(LCompilers::ASR::If_t const&)
    self().transform_stmts(xx.m_body, xx.n_body);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 46983, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    self().visit_stmt(*m_body[i]);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5177, in LCompilers::ASR::BaseVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4897, in ??
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 47222, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_Assignment(LCompilers::ASR::Assignment_t const&)
    self().call_replacer();
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/intrinsic_function.cpp", line 147, in LCompilers::ReplaceIntrinsicFunctionsVisitor::call_replacer()
    replacer.replace_expr(*current_expr);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 46267, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceIntrinsicFunctions>::replace_expr(LCompilers::ASR::expr_t*)
    self().replace_Cast(down_cast<ASR::Cast_t>(x));
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 45508, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceIntrinsicFunctions>::replace_Cast(LCompilers::ASR::Cast_t*)
    self().replace_expr(x->m_arg);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 46267, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceIntrinsicFunctions>::replace_expr(LCompilers::ASR::expr_t*)
    self().replace_Cast(down_cast<ASR::Cast_t>(x));
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 45508, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceIntrinsicFunctions>::replace_Cast(LCompilers::ASR::Cast_t*)
    self().replace_expr(x->m_arg);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 45947, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceIntrinsicFunctions>::replace_expr(LCompilers::ASR::expr_t*)
    self().replace_IntrinsicArrayFunction(down_cast<ASR::IntrinsicArrayFunction_t>(x));
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/intrinsic_function.cpp", line 116, in LCompilers::ReplaceIntrinsicFunctions::replace_IntrinsicArrayFunction(LCompilers::ASR::IntrinsicArrayFunction_t*)
    ASR::expr_t* current_expr_ = instantiate_function(al, x->base.base.loc,
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/pass/intrinsic_array_function_registry.h", line 1949, in ??
    int dim = ASR::down_cast<ASR::IntegerConstant_t>(m_args[1].m_value)->m_n;
AssertFailed: is_a<T>(*f)
make[2]: *** [test/stats/CMakeFiles/test_mean.dir/build.make:79: test/stats/CMakeFiles/test_mean.dir/test_mean.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1805: test/stats/CMakeFiles/test_mean.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by Pranavchiku** [comment]
Go to `intrinsic_array_function_registry.h:1949`, we do not support runtime dim for count yet, you may work it around https://github.com/czgdp1807/stdlib/commit/9bc606565ca2477435ba1c449f917a07d4bbc03f

**Comment by HarshitaKalani** [comment]
Yes, on it

**Comment by HarshitaKalani** [comment]
```console
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2389, in ??
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2318, in main_app(int, char**)
    return compile_to_object_file(arg_file, outfile, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 948, in ??
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 359, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9784, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 311, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 167, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/array_op.cpp", line 2042, in LCompilers::pass_replace_array_op(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    v.visit_TranslationUnit(unit);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/array_op.cpp", line 1677, in LCompilers::ArrayOpVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*mod);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5160, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayOpVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4872, in ??
    case symbolType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/array_op.cpp", line 1697, in LCompilers::ArrayOpVisitor::visit_Module(LCompilers::ASR::Module_t const&)
    this->visit_symbol(*item.second);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5160, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayOpVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4873, in ??
    case symbolType::Function: { v.visit_Function((const Function_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 47028, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayOpVisitor>::visit_Function(LCompilers::ASR::Function_t const&)
    self().transform_stmts(xx.m_body, xx.n_body);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/array_op.cpp", line 1647, in LCompilers::ArrayOpVisitor::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    visit_stmt(*m_body[i]);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5177, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayOpVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4923, in ??
    case stmtType::SubroutineCall: { v.visit_SubroutineCall((const SubroutineCall_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/array_op.cpp", line 2014, in LCompilers::ArrayOpVisitor::visit_SubroutineCall(LCompilers::ASR::SubroutineCall_t const&)
    visit_call_arg(x.m_args[i]);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 50290, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayOpVisitor>::visit_call_arg(LCompilers::ASR::call_arg_t const&)
    self().call_replacer();
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/array_op.cpp", line 1627, in LCompilers::ArrayOpVisitor::call_replacer()
    replacer.replace_expr(*current_expr);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 46271, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceArrayOp>::replace_expr(LCompilers::ASR::expr_t*)
    self().replace_ArrayPhysicalCast(down_cast<ASR::ArrayPhysicalCast_t>(x));
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/array_op.cpp", line 1444, in LCompilers::ReplaceArrayOp::replace_ArrayPhysicalCast(LCompilers::ASR::ArrayPhysicalCast_t*)
    ASR::BaseExprReplacer<ReplaceArrayOp>::replace_ArrayPhysicalCast(x);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 45521, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceArrayOp>::replace_ArrayPhysicalCast(LCompilers::ASR::ArrayPhysicalCast_t*)
    self().replace_expr(x->m_arg);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 46027, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceArrayOp>::replace_expr(LCompilers::ASR::expr_t*)
    self().replace_RealCompare(down_cast<ASR::RealCompare_t>(x));
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/array_op.cpp", line 1282, in LCompilers::ReplaceArrayOp::replace_RealCompare(LCompilers::ASR::RealCompare_t*)
    replace_ArrayOpCommon<ASR::RealCompare_t>(x, "_real_comp_op_res");
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/array_op.cpp", line 990, in void LCompilers::ReplaceArrayOp::replace_ArrayOpCommon<LCompilers::ASR::RealCompare_t>(LCompilers::ASR::RealCompare_t*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
    create_do_loop(loc, n_dims, result_rank, idx_vars,
AssertFailed: result_rank >= var_rank
make[2]: *** [test/stats/CMakeFiles/test_mean.dir/build.make:79: test/stats/CMakeFiles/test_mean.dir/test_mean.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1805: test/stats/CMakeFiles/test_mean.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by Pranavchiku** [comment]
I suspect this is `test_mean.f90`, try these:

```
cd src
lfortran stdlib_stats_mean.f90 --show-llvm
```

If this works, job done.

**Comment by HarshitaKalani** [comment]
I'm able to generate the llvm

**Comment by Pranavchiku** [comment]
Yes, this works. I suspect you do not have access to @czgdp1807 repo yet, I'll enable CI this time.
