### ISSUE TITLE
[stats/mean]: Incorrect handling of compile time compare operation

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#3729]
https://github.com/lfortran/lfortran/issues/3724
```fortran
program main
  use iso_fortran_env, only: int8
  integer(int8) , parameter :: d1_int8(4) = [-10, 2, 3, 4]
  print*, d1_int8 > 0
end
```
```console
$ gfortran a.f90 && ./a.out
 F T T T
$ lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2389, in ??
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2350, in main_app(int, char**)
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 906, in ??
    result = fe.get_asr2(input, lm, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 252, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 274, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 106, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    instantiate_types, instantiate_symbols, entry_functions, entry_function_arguments_mapping, data_structure);
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3598, in LCompilers::LFortran::body_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::ASR::asr_t*, LCompilers::CompilerOptions&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompilers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::allocator<int> > > > >&, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> >&)
    b.visit_TranslationUnit(ast);
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 143, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4848, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4805, in ??
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4851, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4439, in ??
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1558, in LCompilers::LFortran::BodyVisitor::visit_Program(LCompilers::LFortran::AST::Program_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 114, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4894, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4565, in ??
    case stmtType::Print: { v.visit_Print((const Print_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3070, in LCompilers::LFortran::BodyVisitor::visit_Print(LCompilers::LFortran::AST::Print_t const&)
    visit_expr(*x.m_values[i]);
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4945, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_expr(LCompilers::LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4602, in ??
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 6808, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_Compare(LCompilers::LFortran::AST::Compare_t const&)
    CommonVisitorMethods::visit_Compare(al, x, left, right, tmp,
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 217, in LCompilers::LFortran::CommonVisitorMethods::visit_Compare(Allocator&, LCompilers::LFortran::AST::Compare_t const&, LCompilers::ASR::expr_t*&, LCompilers::ASR::expr_t*&, LCompilers::ASR::asr_t*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, LCompilers::SymbolTable*, LCompilers::SetChar&, LCompilers::SetChar&, LCompilers::CompilerOptions const&)
    int64_t left_value = ASR::down_cast<ASR::IntegerConstant_t>(
AssertFailed: is_a<T>(*f)
```

**Comment by HarshitaKalani** [comment]
Works if we remove parameter 
```fortran
program main
  use iso_fortran_env, only: int8
  integer(int8) :: d1_int8(4) = [-10, 2, 3, 4]
  print*, d1_int8 > 0
end
```
```console
$ gfortran a.f90 && ./a.out
 F T T T
$ lfortran a.f90
False True True True 
```

**Comment by Pranavchiku** [comment]
Let us take normal example:

```fortran
program main
integer :: d1_int8(4) 

d1_int8 = [-10, 2, 3, 4]
print*, d1_int8 > 0
end
```


When we use the following diff, 

```diff
diff --git a/src/lfortran/semantics/ast_common_visitor.h b/src/lfortran/semantics/ast_common_visitor.h
index 55fa13e85..8a15c26b3 100644
--- a/src/lfortran/semantics/ast_common_visitor.h
+++ b/src/lfortran/semantics/ast_common_visitor.h
@@ -190,6 +190,7 @@ public:
     size_t right_dims = ASRUtils::extract_n_dims_from_ttype(ASRUtils::expr_type(right));
     ASR::dimension_t* result_shape = nullptr;
     size_t result_dims = 0;
+    std::cout<<"left_dims: "<<left_dims<<" right_dims: "<<right_dims<<"\n";
     if( left_dims == 0 && right_dims == 0 ) {
 
     } else if( left_dims == 0 ) {
@@ -212,7 +213,15 @@ public:
 
     if (ASRUtils::is_integer(*dest_type)) {
 
+        if (ASRUtils::expr_value(left) == nullptr) std::cout<<"expr value left is null\n";
+        if (ASRUtils::expr_value(right) == nullptr) std::cout<<"expr value right is null\n";
+
         if (ASRUtils::expr_value(left) != nullptr && ASRUtils::expr_value(right) != nullptr) {
+            if (ASR::is_a<ASR::ArrayConstant_t>(*ASRUtils::expr_value(left))) {
+                std::cout<<"expr value left is array\n";
+            } else {
+                std::cout<<"expr value left is not array\n";
+            }
             int64_t left_value = ASR::down_cast<ASR::IntegerConstant_t>(
                                     ASRUtils::expr_value(left))->m_n;
             int64_t right_value = ASR::down_cast<ASR::IntegerConstant_t>(
```

We see that `expr_value(left) = nullptr`, and that is correct as it not compile time and thus it does not go inside to check if it is `ArrayConstant`, whereas for the original case

```fortran
program main
integer, parameter :: d1_int8(4) = [-10, 2, 3, 4]
print*, d1_int8 > 0
end
```

As `d1_int8` is a parameter, it's `expr_value(left)` is not nullptr but an ArrayConstant, so we need to implement correct compile time handling for the same.

**Comment by Pranavchiku** [comment]
Here is the naive fix, I am -1 to merge this diff as is because it only handles tis particular case, I'll prefer to generalise it but this will unblock you and give you an idea of how to proceed on fixing this

```diff
diff --git a/src/lfortran/semantics/ast_common_visitor.h b/src/lfortran/semantics/ast_common_visitor.h
index 55fa13e85..c6abecca6 100644
--- a/src/lfortran/semantics/ast_common_visitor.h
+++ b/src/lfortran/semantics/ast_common_visitor.h
@@ -190,6 +190,7 @@ public:
     size_t right_dims = ASRUtils::extract_n_dims_from_ttype(ASRUtils::expr_type(right));
     ASR::dimension_t* result_shape = nullptr;
     size_t result_dims = 0;
+    std::cout<<"left_dims: "<<left_dims<<" right_dims: "<<right_dims<<"\n";
     if( left_dims == 0 && right_dims == 0 ) {
 
     } else if( left_dims == 0 ) {
@@ -212,26 +213,62 @@ public:
 
     if (ASRUtils::is_integer(*dest_type)) {
 
+        if (ASRUtils::expr_value(left) == nullptr) std::cout<<"expr value left is null\n";
+        if (ASRUtils::expr_value(right) == nullptr) std::cout<<"expr value right is null\n";
+
         if (ASRUtils::expr_value(left) != nullptr && ASRUtils::expr_value(right) != nullptr) {
-            int64_t left_value = ASR::down_cast<ASR::IntegerConstant_t>(
-                                    ASRUtils::expr_value(left))->m_n;
-            int64_t right_value = ASR::down_cast<ASR::IntegerConstant_t>(
+            if (ASR::is_a<ASR::ArrayConstant_t>(*ASRUtils::expr_value(left)) && !ASR::is_a<ASR::ArrayConstant_t>(*ASRUtils::expr_value(right))) {
+                std::cout<<"expr value left is array\n";
+                std::vector<int> left_value;
+                ASR::ArrayConstant_t* left_array = ASR::down_cast<ASR::ArrayConstant_t>(ASRUtils::expr_value(left));
+                for (size_t i = 0; i < left_array->n_args; i++) {
+                    left_value.push_back(ASR::down_cast<ASR::IntegerConstant_t>(left_array->m_args[i])->m_n);
+                }
+
+                int right_value = ASR::down_cast<ASR::IntegerConstant_t>(
                                     ASRUtils::expr_value(right))->m_n;
-            bool result;
-            switch (asr_op) {
-                case (ASR::cmpopType::Eq):  { result = left_value == right_value; break; }
-                case (ASR::cmpopType::Gt): { result = left_value > right_value; break; }
-                case (ASR::cmpopType::GtE): { result = left_value >= right_value; break; }
-                case (ASR::cmpopType::Lt): { result = left_value < right_value; break; }
-                case (ASR::cmpopType::LtE): { result = left_value <= right_value; break; }
-                case (ASR::cmpopType::NotEq): { result = left_value != right_value; break; }
-                default: {
-                    throw SemanticError("Comparison operator not implemented",
-                                        x.base.base.loc);
+
+                Vec<ASR::expr_t*> args; args.reserve(al, left_array->n_args);
+                for (size_t i = 0; i < left_value.size(); i++) {
+                    bool res;
+                    switch (asr_op) {
+                        case (ASR::cmpopType::Eq):  { res = left_value[i] == right_value; break; }
+                        case (ASR::cmpopType::Gt): { res = left_value[i] > right_value; break; }
+                        case (ASR::cmpopType::GtE): { res = left_value[i] >= right_value; break; }
+                        case (ASR::cmpopType::Lt): { res = left_value[i] < right_value; break; }
+                        case (ASR::cmpopType::LtE): { res = left_value[i] <= right_value; break; }
+                        case (ASR::cmpopType::NotEq): { res = left_value[i] != right_value; break; }
+                        default: {
+                            throw SemanticError("Comparison operator not implemented",
+                                                x.base.base.loc);
+                        }
+                    }
+                    args.push_back(al, ASRUtils::EXPR(ASR::make_LogicalConstant_t(
+                        al, x.base.base.loc, res, ASRUtils::TYPE(ASR::make_Logical_t(al, x.base.base.loc, 4)))));
                 }
+                value = ASRUtils::EXPR(ASRUtils::make_ArrayConstructor_t_util(al, x.base.base.loc, args.p, args.size(), type, ASR::arraystorageType::ColMajor));
+            } else if (ASR::is_a<ASR::IntegerConstant_t>(*ASRUtils::expr_value(left)) && ASR::is_a<ASR::IntegerConstant_t>(*ASRUtils::expr_value(right))) {
+                std::cout<<"expr value left is not array\n";
+                int64_t left_value = ASR::down_cast<ASR::IntegerConstant_t>(
+                                        ASRUtils::expr_value(left))->m_n;
+                int64_t right_value = ASR::down_cast<ASR::IntegerConstant_t>(
+                                        ASRUtils::expr_value(right))->m_n;
+                bool result;
+                switch (asr_op) {
+                    case (ASR::cmpopType::Eq):  { result = left_value == right_value; break; }
+                    case (ASR::cmpopType::Gt): { result = left_value > right_value; break; }
+                    case (ASR::cmpopType::GtE): { result = left_value >= right_value; break; }
+                    case (ASR::cmpopType::Lt): { result = left_value < right_value; break; }
+                    case (ASR::cmpopType::LtE): { result = left_value <= right_value; break; }
+                    case (ASR::cmpopType::NotEq): { result = left_value != right_value; break; }
+                    default: {
+                        throw SemanticError("Comparison operator not implemented",
+                                            x.base.base.loc);
+                    }
+                }
+                value = ASR::down_cast<ASR::expr_t>(ASR::make_LogicalConstant_t(
+                    al, x.base.base.loc, result, type));
             }
-            value = ASR::down_cast<ASR::expr_t>(ASR::make_LogicalConstant_t(
-                al, x.base.base.loc, result, type));
         }
```

**Comment by Pranavchiku** [comment]
```console
% cat b.f90 
program main
integer, parameter :: d1_int8(4) = [-10, 2, 3, 4]
print*, d1_int8 > 0
end
% lfortran b.f90 
False True True True 
```

**Comment by HarshitaKalani** [comment]
Yes, this approach helped in moving next but the same issue exists for "real" as well. I'm trying to find a simplified/generalised approach to handle this.

**Comment by Pranavchiku** [comment]
You just need to create a unified approach for `real`, `integer`, `complex` and `{left array, right scalar, ......}` cases.

**Comment by HarshitaKalani** [comment]
I've opened a PR which handles the current issue. Can you please review and lmk if that works for now?
