### ISSUE TITLE
allocating using module variable and using module routine outside module throws error

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3968]
> mms_copy.f90

```fortran
MODULE XX
  IMPLICIT NONE

  INTEGER, PUBLIC :: nx = 1000

END MODULE

MODULE mms_module

  USE XX, ONLY: nx

  IMPLICIT NONE
  REAL, ALLOCATABLE, DIMENSION(:), PUBLIC :: ref_flux

  REAL, ALLOCATABLE, DIMENSION(:), PUBLIC :: ref_fluxm

  CONTAINS

  SUBROUTINE mms_deallocate
  END SUBROUTINE mms_deallocate

  SUBROUTINE mms_allocate ( )
    ALLOCATE( ref_flux(nx), ref_fluxm(nx) )
  END SUBROUTINE mms_allocate
END MODULE mms_module
```

> dealloc.f90

```fortran
MODULE dealloc_module
  USE mms_module, ONLY: mms_deallocate
END MODULE dealloc_module
```

```console
% lfortran -c mms_copy.f90 && lfortran -c dealloc.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2459
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2391
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 906
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 252
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 274
    compiler_options.symtab_only, compiler_options);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 77
    if (res.ok) {
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 3457
    v.visit_TranslationUnit(ast);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 120
    visit_ast(*x.m_items[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4878
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4834
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4881
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4465
    case modType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 471
    visit_ModuleSubmoduleCommon<AST::Module_t, ASR::Module_t>(x);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 424
    visit_unit_decl1(*x.m_use[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4890
    void visit_unit_decl1(const unit_decl1_t &b) { visit_unit_decl1_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4486
    case unit_decl1Type::Use: { v.visit_Use((const Use_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 2565
    t = (ASR::symbol_t*)(ASRUtils::load_module(al, tu_symtab,
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.cpp", line 308
    *symtab, intrinsic, pass_options);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.cpp", line 456
    ASR::TranslationUnit_t *asr = load_modfile(al, modfile, false, symtab);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/modfile.cpp", line 93
    ASR::asr_t *asr = deserialize_asr(al, asr_binary, load_symtab_id, symtab);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast_serialization.cpp", line 414
    Line not found
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast_serialization.cpp", line 430
    Line not found
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_verify.cpp", line 1242
    v.visit_TranslationUnit(unit);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_verify.cpp", line 111
    for (auto &a : x.m_symtab->get_scope()) {
  File "../libasr/asr.h", line 5143
  File "../libasr/asr.h", line 4855
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_verify.cpp", line 333
    for (auto &a : x.m_symtab->get_scope()) {
  File "../libasr/asr.h", line 5143
  File "../libasr/asr.h", line 4856
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_verify.cpp", line 454
    visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5160
  File "../libasr/asr.h", line 4878
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_verify.cpp", line 1218
    BaseWalkVisitor<VerifyVisitor>::visit_Allocate(x);
  File "../libasr/asr.h", line 5477
  File "../libasr/asr.h", line 6619
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_verify.cpp", line 1171
    require_with_loc(ASRUtils::is_integer(
  File "../libasr/asr_utils.h", line 294
  File "../libasr/asr.h", line 50299
AssertFailed: e->m_external
```

**Comment by Pranavchiku** [comment]
The trouble is we do not serialize `m_external` for external symbol and this hurts us in independent module compilation as shown above.

**Comment by Pranavchiku** [comment]
A workaround is to use `get_nx()` function:

```fortran
MODULE XX
  IMPLICIT NONE

  INTEGER, PUBLIC :: nx = 1000

END MODULE

MODULE mms_module

  USE XX, ONLY: nx

  IMPLICIT NONE
  REAL, ALLOCATABLE, DIMENSION(:), PUBLIC :: ref_flux

  REAL, ALLOCATABLE, DIMENSION(:), PUBLIC :: ref_fluxm

  CONTAINS

  SUBROUTINE mms_deallocate
  END SUBROUTINE mms_deallocate

  pure integer function get_nx()
    get_nx = nx
  end function

  SUBROUTINE mms_allocate ( )
    ALLOCATE( ref_flux(get_nx()), ref_fluxm(get_nx()) )
  END SUBROUTINE mms_allocate
END MODULE mms_module
```

**Comment by kmr-srbh** [comment]
Another one when compiling `output.f90`

```console
(lf) saurabh-kumar@Awadh:~/Projects/Packages/SNAP/src$ make
lfortran  -c setup.f90
lfortran  -c output.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main_impl()
  File "./csu/../sysdeps/x86/libc-start.c", line 58, in __libc_start_call_main()
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2462, in main()
    return main_app(argc, argv);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2391, in main_app(int, char**)
    return compile_to_object_file(arg_file, outfile, false,
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 906, in compile_to_object_file()
    result = fe.get_asr2(input, lm, diagnostics);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/fortran_evaluator.cpp", line 252, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/fortran_evaluator.cpp", line 274, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 76, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    instantiate_types, instantiate_symbols, entry_functions, entry_function_arguments_mapping, data_structure);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 3457, in LCompilers::LFortran::symbol_table_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, LCompilers::CompilerOptions&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompilers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::allocator<int> > > > >&, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> >&)
    v.visit_TranslationUnit(ast);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 120, in LCompilers::LFortran::SymbolTableVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4878, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4835, in visit_ast_t<LCompilers::LFortran::SymbolTableVisitor>()
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4881, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4465, in visit_mod_t<LCompilers::LFortran::SymbolTableVisitor>()
    case modType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 471, in LCompilers::LFortran::SymbolTableVisitor::visit_Module(LCompilers::LFortran::AST::Module_t const&)
    visit_ModuleSubmoduleCommon<AST::Module_t, ASR::Module_t>(x);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 424, in void LCompilers::LFortran::SymbolTableVisitor::visit_ModuleSubmoduleCommon<LCompilers::LFortran::AST::Module_t, LCompilers::ASR::Module_t>(LCompilers::LFortran::AST::Module_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
    visit_unit_decl1(*x.m_use[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4890, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_unit_decl1(LCompilers::LFortran::AST::unit_decl1_t const&)
    void visit_unit_decl1(const unit_decl1_t &b) { visit_unit_decl1_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4486, in visit_unit_decl1_t<LCompilers::LFortran::SymbolTableVisitor>()
    case unit_decl1Type::Use: { v.visit_Use((const Use_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 2565, in LCompilers::LFortran::SymbolTableVisitor::visit_Use(LCompilers::LFortran::AST::Use_t const&)
    t = (ASR::symbol_t*)(ASRUtils::load_module(al, tu_symtab,
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/asr_utils.cpp", line 307, in LCompilers::ASRUtils::load_module(Allocator&, LCompilers::SymbolTable*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::Location const&, bool, LCompilers::PassOptions&, bool, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::Location const&)>)
    ASR::TranslationUnit_t *mod1 = find_and_load_module(al, module_name,
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/asr_utils.cpp", line 456, in LCompilers::ASRUtils::find_and_load_module(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::SymbolTable&, bool, LCompilers::PassOptions&)
    ASR::TranslationUnit_t *asr = load_modfile(al, modfile, false, symtab);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/modfile.cpp", line 93, in LCompilers::load_modfile(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::SymbolTable&)
    ASR::asr_t *asr = deserialize_asr(al, asr_binary, load_symtab_id, symtab);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/serialization.cpp", line 414, in LCompilers::deserialize_asr(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::SymbolTable&)
    return deserialize_asr(al, s, load_symtab_id);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/serialization.cpp", line 430, in LCompilers::deserialize_asr(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
    if (!asr_verify(*tu, false, diagnostics)) {
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/asr_verify.cpp", line 1242, in LCompilers::asr_verify(LCompilers::ASR::TranslationUnit_t const&, bool, LCompilers::diag::Diagnostics&)
    v.visit_TranslationUnit(unit);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/asr_verify.cpp", line 112, in LCompilers::ASR::VerifyVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5143, in LCompilers::ASR::BaseVisitor<LCompilers::ASR::VerifyVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4856, in visit_symbol_t<LCompilers::ASR::VerifyVisitor>()
    case symbolType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/asr_verify.cpp", line 334, in LCompilers::ASR::VerifyVisitor::visit_Module(LCompilers::ASR::Module_t const&)
    this->visit_symbol(*a.second);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5143, in LCompilers::ASR::BaseVisitor<LCompilers::ASR::VerifyVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4857, in visit_symbol_t<LCompilers::ASR::VerifyVisitor>()
    case symbolType::Function: { v.visit_Function((const Function_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/asr_verify.cpp", line 454, in LCompilers::ASR::VerifyVisitor::visit_Function(LCompilers::ASR::Function_t const&)
    visit_stmt(*x.m_body[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5160, in LCompilers::ASR::BaseVisitor<LCompilers::ASR::VerifyVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4893, in visit_stmt_t<LCompilers::ASR::VerifyVisitor>()
    case stmtType::If: { v.visit_If((const If_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5558, in LCompilers::ASR::BaseWalkVisitor<LCompilers::ASR::VerifyVisitor>::visit_If(LCompilers::ASR::If_t const&)
    self().visit_stmt(*x.m_body[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5160, in LCompilers::ASR::BaseVisitor<LCompilers::ASR::VerifyVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4893, in visit_stmt_t<LCompilers::ASR::VerifyVisitor>()
    case stmtType::If: { v.visit_If((const If_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5558, in LCompilers::ASR::BaseWalkVisitor<LCompilers::ASR::VerifyVisitor>::visit_If(LCompilers::ASR::If_t const&)
    self().visit_stmt(*x.m_body[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5160, in LCompilers::ASR::BaseVisitor<LCompilers::ASR::VerifyVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4878, in visit_stmt_t<LCompilers::ASR::VerifyVisitor>()
    case stmtType::Allocate: { v.visit_Allocate((const Allocate_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/asr_verify.cpp", line 1218, in LCompilers::ASR::VerifyVisitor::visit_Allocate(LCompilers::ASR::Allocate_t const&)
    BaseWalkVisitor<VerifyVisitor>::visit_Allocate(x);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5477, in LCompilers::ASR::BaseWalkVisitor<LCompilers::ASR::VerifyVisitor>::visit_Allocate(LCompilers::ASR::Allocate_t const&)
    self().visit_alloc_arg(x.m_args[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 6619, in LCompilers::ASR::BaseWalkVisitor<LCompilers::ASR::VerifyVisitor>::visit_alloc_arg(LCompilers::ASR::alloc_arg_t const&)
    self().visit_dimension(x.m_dims[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/asr_verify.cpp", line 1171, in LCompilers::ASR::VerifyVisitor::visit_dimension(LCompilers::ASR::dimension_t const&)
    require_with_loc(ASRUtils::is_integer(
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr_utils.h", line 294, in expr_type()
    return ASR::expr_type0(f);
AssertFailed: e->m_external
make: *** [Makefile:176: output.o] Error 1
```

**Comment by Pranavchiku** [comment]
I tried and I think there is now way we can find the symbol and point to it in `ExternalSymbol` while deserializing, and it is a pointer so I don't think it makes any sense to serialize it. Not sure what can be a good way forward.
cc @certik

**Comment by certik** [comment]
Let's investigate what is going on. According to the stacktrace, here is the `visit_dimension` verifier:
```c++
    void visit_dimension(const dimension_t &x) {
        if (x.m_start) {
            require_with_loc(ASRUtils::is_integer(
                *ASRUtils::expr_type(x.m_start)),
                "Start dimension must be a signed integer", x.loc);
            visit_expr(*x.m_start);
        }

        if (x.m_length) {
            require_with_loc(ASRUtils::is_integer(
                *ASRUtils::expr_type(x.m_length)),
                "Length dimension must be a signed integer", x.loc);
            visit_expr(*x.m_length);
        }
    }
```
In here, the `expr_type` is in `asr_utils.h`:
```c++
static inline ASR::ttype_t* expr_type(const ASR::expr_t *f)
{
    return ASR::expr_type0(f);
}
```
Which goes to `asr.h`:
```c++
        case ASR::exprType::Var: {
            ASR::symbol_t *s = ((ASR::Var_t*)f)->m_v;
            if (s->type == ASR::symbolType::ExternalSymbol) {
                ASR::ExternalSymbol_t *e = ASR::down_cast<ASR::ExternalSymbol_t>(s);
                LCOMPILERS_ASSERT(e->m_external);
                LCOMPILERS_ASSERT(!ASR::is_a<ASR::ExternalSymbol_t>(*e->m_external));
                s = e->m_external;
            }
            ...
```
It's the last assert that fails, i.e., `e->m_external` is null.

I think this happens right here:
```fortran
    ALLOCATE( ref_flux(nx), ref_fluxm(nx) )
```
where `nx` is a `Var -> ExternalSymbol -> XX: INTEGER, PUBLIC :: nx = 1000`. When we are checking the type of `nx`, we resolve the external symbol to figure out the type.

Consequently, in the current design, we can't check types of variables from other modules.

Here are some possible way forward:

* Add ttype to ExternalSymbol. So that you know what the type is even if you can't resolve the symbol itself yet. Pros: clean, easier to figure out the type, fixes this bug. Cons: if it is only needed to run verify after serialization but before full ASR is loaded, it might not be worth the possible performance penalty of copying / dealing with the type in ExternalSymbol.
* Skip this check `is_integer` check for `Var`s that are external symbols. Pros: doesn't modify ASR, no performance penalty in Release mode; Cons: this means we can't use `expr_type`, currently used at 10 places in verify()
* Do not check ASR after deserialization, only when external symbols are fully loaded. That's the approach taken here: https://github.com/lfortran/lfortran/pull/4158. Pros: no performance hit in Release mode (if implemented properly), doesn't require maintaining two modes for ExternalSymbol in verify; Cons: the ASR is not checked right after it is deserialized. We'll only find problems once all dependent modules are recursively fully loaded. Requires careful accounting which modules must be checked, since some modules might already be loaded.

**Comment by Pranavchiku** [comment]
To add ttype to ExternalSymbol, I am only worried about possibility of type of a variable depending on another variable, example: array dimension depending on other variable but I do not think it is possible, so that should be fine. I do not think skipping check `is_integer` is a good way forward. 

The third approach makes more sense because we verify that ASR is correct before serializing and thus if there are  *no bugs in our deserializer* it should deserialize correctly and we can assume ASR is correct.  Also, do we load the dependent modules right after deserialization or at some point later? If done right after deserialization, I think this is a better way to proceed.

**Comment by Pranavchiku** [comment]
My initial thoughts were to skip verify and populate ExternalSymbols correctly after deserialization, this is clean and we know how to do it.

**Comment by assem2002** [comment]
> To add ttype to ExternalSymbol, I am only worried about possibility of type of a variable depending on another variable, example: array dimension depending on other variable but I do not think it is possible, so that should be fine. I do not think skipping check `is_integer` is a good way forward.
> 
> The third approach makes more sense because we verify that ASR is correct before serializing and thus if there are _no bugs in our deserializer_ it should deserialize correctly and we can assume ASR is correct. Also, do we load the dependent modules right after deserialization or at some point later? If done right after deserialization, I think this is a better way to proceed.

We load every dependent modules right after deserialization (you can see this [figure1](https://github.com/lfortran/lfortran/pull/4158#issue-2336658889)).
The only thing that happens in middle of loading module and the other one is just inserting them into the symbolTable.

**Comment by assem2002** [comment]
The second solution is good also. We can just utilize `check_external` parameter that is passed to the `asr_verify()` to bypass these 10 spots where `expr_type` exists when the parameter is set to false.

Although we won't verify some nodes, but we would check these passed check nodes when we verify the whole ASR after deserializing all needed mod files. It still has its own cons but we follow that practice with many visitors in the verification phase.
If it seems a good approach, I can just push this fix and compare between them. @certik

**Comment by certik** [comment]
I think we are down to two options:
* Skip the verification after deserialization
* Skip all ExternalSymbol nodes, including within declarations.

Let's do the following: @assem@002, can you modify the verify to skip the type verification if `check_external=false` and see if it fixes the problem? If so, let's go with that. (If this becomes too complex, then let's go with the first option.)

That leaves the door open to later just remove this verification completely after deserialization. We didn't have bug in serialization/deserialization for some time, but I think it's good to check what we can. We'll keep the door open, and if we run into more issues with the second approach, then we'll go with the first approach.
