### ISSUE TITLE
AssertFailed: e->m_external

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#3977]
```console
$ make
lfortran  -c global.f90 -o global.o
lfortran  -c sn.f90 -o sn.o
lfortran  -c data.f90 -o data.o
lfortran  -c geom.f90 -o geom.o
lfortran  -c control.f90 -o control.o
cpp -P  time.0.F90 >time.f90
lfortran  -c time.f90
warning: Assuming implicit save attribute for variable declaration
  --> time.f90:60:25
   |
60 |     CHARACTER(LEN=1) :: star='*'
   |                         ^^^^^^^^ help: add explicit save attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
cpp -P  plib.0.F90 >plib.f90
lfortran  -c plib.f90
lfortran  -c mms.f90 -o mms.o
warning: Assuming implicit save attribute for variable declaration
   --> mms.f90:522:25
    |
522 |     CHARACTER(LEN=1) :: star='*'
    |                         ^^^^^^^^ help: add explicit save attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran  -c solvar.f90 -o solvar.o
lfortran  -c dealloc.f90 -o dealloc.o
Internal Compiler Error: Unhandled exception
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
Traceback (most recent call last):
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in _start()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_start_main()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_init_first()
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in main()
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in main_app(int, char**)
  File "lfortran.cpp", line 0, in (anonymous namespace)::compile_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LFortran::symbol_table_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, LCompilers::CompilerOptions&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompilers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::allocator<int> > > > >&, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> >&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LFortran::SymbolTableVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
  File "ast_symboltable_visitor.cpp", line 0, in void LCompilers::LFortran::AST::visit_ast_t<LCompilers::LFortran::SymbolTableVisitor>(LCompilers::LFortran::AST::ast_t const&, LCompilers::LFortran::SymbolTableVisitor&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
  File "ast_symboltable_visitor.cpp", line 0, in void LCompilers::LFortran::AST::visit_mod_t<LCompilers::LFortran::SymbolTableVisitor>(LCompilers::LFortran::AST::mod_t const&, LCompilers::LFortran::SymbolTableVisitor&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LFortran::SymbolTableVisitor::visit_Module(LCompilers::LFortran::AST::Module_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in void LCompilers::LFortran::SymbolTableVisitor::visit_ModuleSubmoduleCommon<LCompilers::LFortran::AST::Module_t, LCompilers::ASR::Module_t>(LCompilers::LFortran::AST::Module_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_unit_decl1(LCompilers::LFortran::AST::unit_decl1_t const&)
  File "ast_symboltable_visitor.cpp", line 0, in void LCompilers::LFortran::AST::visit_unit_decl1_t<LCompilers::LFortran::SymbolTableVisitor>(LCompilers::LFortran::AST::unit_decl1_t const&, LCompilers::LFortran::SymbolTableVisitor&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LFortran::SymbolTableVisitor::visit_Use(LCompilers::LFortran::AST::Use_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASRUtils::load_module(Allocator&, LCompilers::SymbolTable*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::Location const&, bool, LCompilers::PassOptions&, bool, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::Location const&)>)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASRUtils::find_and_load_module(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::SymbolTable&, bool, LCompilers::PassOptions&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::load_modfile(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::SymbolTable&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::deserialize_asr(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::SymbolTable&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::deserialize_asr(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::asr_verify(LCompilers::ASR::TranslationUnit_t const&, bool, LCompilers::diag::Diagnostics&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::VerifyVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::BaseVisitor<LCompilers::ASR::VerifyVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
  File "asr_verify.cpp", line 0, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASR::VerifyVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASR::VerifyVisitor&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::VerifyVisitor::visit_Module(LCompilers::ASR::Module_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::BaseVisitor<LCompilers::ASR::VerifyVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
  File "asr_verify.cpp", line 0, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASR::VerifyVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASR::VerifyVisitor&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::VerifyVisitor::visit_Function(LCompilers::ASR::Function_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::BaseVisitor<LCompilers::ASR::VerifyVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
  File "asr_verify.cpp", line 0, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASR::VerifyVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASR::VerifyVisitor&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::VerifyVisitor::visit_Allocate(LCompilers::ASR::Allocate_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::BaseWalkVisitor<LCompilers::ASR::VerifyVisitor>::visit_Allocate(LCompilers::ASR::Allocate_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::BaseWalkVisitor<LCompilers::ASR::VerifyVisitor>::visit_alloc_arg(LCompilers::ASR::alloc_arg_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::VerifyVisitor::visit_dimension(LCompilers::ASR::dimension_t const&)
  File "asr_verify.cpp", line 0, in LCompilers::ASRUtils::expr_type(LCompilers::ASR::expr_t const*)
AssertFailed: e->m_external
make: *** [Makefile:147: dealloc.o] Error 1
```

Possibly a duplicate of #3968.

**Comment by Pranavchiku** [comment]
This is same as #3968
