### ISSUE TITLE
add support for `c_funptr`

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3989]
Required in #3777, #3991

```fortran
module libgompinterop
use iso_c_binding
implicit none

interface
subroutine GOMP_parallel (fn) bind (C, name="GOMP_parallel")
import :: c_funptr
type(c_funptr), value :: fn
end subroutine
end interface
end module
```

```console
% lfortran -c a.f90 
LCOMPILERS_ASSERT failed: /Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.h
function replace_Struct(), line number 3972 at 
derived_type_sym != nullptr
ERROR MESSAGE:
derived_type_sym cannot be nullptr
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2459
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2391
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 906
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 252
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 274
    compiler_options.symtab_only, compiler_options);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 77
    if (res.ok) {
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 3457
    v.visit_TranslationUnit(ast);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 120
    visit_ast(*x.m_items[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4878
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4834
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4881
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4465
    case modType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 471
    visit_ModuleSubmoduleCommon<AST::Module_t, ASR::Module_t>(x);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 427
    visit_unit_decl2(*x.m_decl[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4892
    void visit_unit_decl2(const unit_decl2_t &b) { visit_unit_decl2_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4495
    case unit_decl2Type::DeclarationPragma: { v.visit_DeclarationPragma((const DeclarationPragma_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1815
    visit_interface_item(*x.m_items[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4911
    void visit_interface_item(const interface_item_t &b) { visit_interface_item_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4525
    case interface_itemType::InterfaceProc: { v.visit_InterfaceProc((const InterfaceProc_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1702
    is_interface = true;
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4886
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4476
    case program_unitType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1064
    tmp = ASRUtils::make_Function_t_util(
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.h", line 4059
    ASR::ttype_t* func_type = ASRUtils::TYPE(ASRUtils::make_FunctionType_t_util(
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.h", line 4025
    expr_type(a_args[i]), current_scope);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.h", line 3989
    replace_ttype(t);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr.h", line 46232
    self().replace_Struct(down_cast<ASR::Struct_t>(x));
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.h", line 3971
    LCOMPILERS_ASSERT_MSG( derived_type_sym != nullptr,
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x180353a1f
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x180446c1f
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x180477583
Abort: Signal SIGABRT (abort) received

zsh: abort      lfortran -c a.f90
```

cc @certik @Thirumalai-Shaktivel

**Comment by Pranavchiku** [comment]
```diff
diff --git a/src/runtime/pure/lfortran_intrinsic_iso_c_binding.f90 b/src/runtime/pure/lfortran_intrinsic_iso_c_binding.f90
index 64f2661a8..06777c3c8 100644
--- a/src/runtime/pure/lfortran_intrinsic_iso_c_binding.f90
+++ b/src/runtime/pure/lfortran_intrinsic_iso_c_binding.f90
@@ -5,6 +5,10 @@ type :: c_ptr
     integer ptr
 end type
 
+type :: c_funptr
+    integer ptr
+end type
+
 integer, parameter :: c_int8_t = 1
 integer, parameter :: c_int16_t = 2
```

makes it work.
