### ISSUE TITLE
compile array initialisation example

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#4031]
Towards #3777

```fortran
subroutine initialize_array(n, a)
use omp_lib
implicit none
integer, intent(in) :: n
real, dimension(n), intent(out) :: a

integer :: i

!$omp parallel
!$omp do
do i = 1, n
  a(i) = 12.91
end do
!$omp end do
!$omp end parallel
end subroutine

program openmp
integer, parameter :: n = 1000000
real, dimension(n) :: a

call initialize_array(n, a)

print *, a(1), a(n)
end program
```

gets transformed to 

```fortran
module thread_data_module
    use, intrinsic :: iso_c_binding
    type, bind(C) :: thread_data
        integer(c_int) :: n
        type(c_ptr) :: a
    end type thread_data
end module thread_data_module

subroutine lcompilers_initialise_array(data) bind(C)
use thread_data_module
use iso_c_binding
use libgompinterop
implicit none
type(c_ptr), value :: data
type(thread_data), pointer :: tdata
real(c_float), pointer :: a(:)

integer(c_int) :: i, n, num_threads, chunk, leftovers, thread_num, start, end

call c_f_pointer(data, tdata)

n = tdata%n

call c_f_pointer(tdata%a, a, [n])

num_threads = omp_get_max_threads()
chunk = n / num_threads
leftovers = mod(n, num_threads)

thread_num = omp_get_thread_num()
start = chunk * thread_num

if (thread_num < leftovers) then
    start = start + thread_num
else
    start = start + leftovers
end if

end = start + chunk

if (thread_num < leftovers) then
    end = end + 1
end if

do i = start, end
    ! print *, "Thread ", thread_num, " is processing element ", i
    a(i) = 1.0
end do

call GOMP_barrier()

end subroutine

subroutine initialize_array(n, a)
use thread_data_module
use libgompinterop
implicit none

interface
subroutine lcompilers_initialise_array(data) bind(C)
use iso_c_binding
type(c_ptr), value :: data
end subroutine
end interface

integer(c_int), intent(in) :: n
real(c_float), dimension(:), intent(inout), pointer :: a

type(thread_data), target :: data
type(c_ptr) :: tdata

data%n = n
allocate(a(data%n))
data%a = c_loc(a)

tdata = c_loc(data)

call GOMP_parallel(c_funloc(lcompilers_initialise_array), tdata, 0, 0)

end subroutine

program main
use libgompinterop
use thread_data_module
implicit none

interface
subroutine initialize_array(n, a)
use iso_c_binding
integer(c_int), intent(in) :: n
real(c_float), dimension(:), pointer :: a
end subroutine
end interface

integer(c_int) :: n = 1000000
real(c_float), dimension(:), pointer :: a

call initialize_array(n, a)
print *, "Done"

print *, "a[1] = ", a(1)
print * , "a[1000000] = ", a(1000000)
end program main
```

```console
% time lfortran -c libgompinterop.f90 && time lfortran e-transformed.f90 -L/Users/pranavchiku/repos/llvm-project/openmp/build/runtime/src/ -lomp
-Wl,-rpath,/Users/pranavchiku/repos/llvm-project/openmp/build/runtime/src/
lfortran -c libgompinterop.f90  0.07s user 0.02s system 57% cpu 0.168 total
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2459
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2423
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 948
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 359
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9813
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 5140
  File "../libasr/asr.h", line 5116
  File "../libasr/asr.h", line 5141
  File "../libasr/asr.h", line 4847
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 919
    visit_Function(*ASR::down_cast<ASR::Function_t>(item.second));
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3715
    llvm_goto_targets.clear();
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3756
    llvm::FunctionType* function_type = llvm_utils->get_function_type(x, module.get());
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1119
    std::vector<llvm::Type*> args = convert_args(x, module);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/llvm_utils.cpp", line 891
    LCOMPILERS_ASSERT(ASRUtils::is_arg_dummy(arg->m_intent));
AssertFailed: ASRUtils::is_arg_dummy(arg->m_intent)
lfortran e-transformed.f90  -lomp   0.21s user 0.03s system 90% cpu 0.268 total
```

This will be a small fix, not so difficult.

**Comment by Pranavchiku** [comment]
With the following diff

```diff
diff --git a/a.f90 b/a.f90
index 21ea98765..975b25c2d 100644
--- a/a.f90
+++ b/a.f90
@@ -64,7 +64,7 @@ end subroutine
 end interface
 
 integer(c_int), intent(in) :: n
-real(c_float), dimension(:), pointer :: a
+real(c_float), dimension(:), intent(inout), pointer :: a
 
 type(thread_data), target :: data
 type(c_ptr) :: tdata
```

it throws

```console
% lfortran -c libgompinterop.f90 && lfortran a.f90 -L/Users/pranavchiku/repos/llvm-project/openmp/build/runtime/src/ -lomp
Assertion failed: (Ty && "Invalid GetElementPtrInst indices for type!"), function checkGEPType, file Instructions.h, line 897.
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2462
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2426
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 948
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 359
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9875
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 5140
  File "../libasr/asr.h", line 5116
  File "../libasr/asr.h", line 5141
  File "../libasr/asr.h", line 4847
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 945
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5143
  File "../libasr/asr.h", line 4856
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3784
    visit_procedures(x);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3981
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5160
  File "../libasr/asr.h", line 4915
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4155
    builder->CreateStore(llvm::ConstantInt::get(context, llvm::APInt(32, 0)),
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 541
    llvm::Value* offset = llvm_utils->create_gep(arr, 1);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1548
    return LLVM::CreateGEP(*builder, ds, idx_vec);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/llvm_utils.cpp", line 27
    return builder.CreateGEP(t2, x, idx);
  File "/Users/pranavchiku/mambaforge/envs/lf/include/llvm/IR/IRBuilder.h", line 1773
    return Insert(GetElementPtrInst::Create(Ty, Ptr, IdxList), Name);
  File "/Users/pranavchiku/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 943
    NameStr, InsertBefore);
  File "/Users/pranavchiku/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1151
    }
  File "/Users/pranavchiku/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1143
    : Instruction(getGEPReturnType(PointeeType, Ptr, IdxList), GetElementPtr,
  File "/Users/pranavchiku/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1074
    Type *PtrTy = PointerType::get(checkGEPType(getIndexedType(ElTy, IdxList)),
  File "/Users/pranavchiku/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 897
    assert(Ty && "Invalid GetElementPtrInst indices for type!");
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x180352d0f
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x180353a1f
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x180446c1f
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x180477583
Abort: Signal SIGABRT (abort) received

zsh: abort      lfortran a.f90  -lomp
```

**Comment by Pranavchiku** [comment]
MRE:

```fortran
module thread_data_module
use, intrinsic :: iso_c_binding
type, bind(C) :: thread_data
type(c_ptr) :: a
end type thread_data
end module thread_data_module

subroutine lcompilers_initialise_array(data) bind(C)
use thread_data_module
use iso_c_binding
implicit none
type(c_ptr), value :: data
type(thread_data), pointer :: tdata
real(c_float), pointer :: a(:)
call c_f_pointer(tdata%a, a, [5])
end subroutine

program main
end program main
```

**Comment by Pranavchiku** [comment]
I think there is trouble in getting type of `a` because of physical types. I am not sure what is causing this, I'll ask @Shaikh-Ubaid @nikabot @certik to take a look. I am working to write an ASR pass using example in https://github.com/lfortran/lfortran/issues/4136

**Comment by certik** [comment]
@Shaikh-Ubaid If you have time to fix this one, that would be awesome.

**Comment by certik** [comment]
Using https://github.com/lfortran/lfortran/issues/4177:
```
real(c_float), pointer :: a(:)  ! `PointerToDataArray`
call c_f_pointer(tdata%a, a, [5]) ! the `a` is `DescriptorArray`
```
So we need to add a `ArrayPhysicalCast` from `PointerToDataArray` to `DescriptorArray`. 

The cast implementation might require to introduce a temporary. In that case the temporary will be eventually handled by https://github.com/lfortran/lfortran/issues/3770#issuecomment-2145669584.

**Comment by certik** [comment]
The test case above https://github.com/lfortran/lfortran/issues/4031#issue-2303897390 is not in integration tests, so I am reopening the issue until it is added.

**Comment by Pranavchiku** [comment]
Ahh, this got closed by mistake through #4219

**Comment by Pranavchiku** [comment]
With #4224, the transformed example at https://github.com/lfortran/lfortran/issues/4031#issue-2303897390 segfaults, but with following diff it works, I think this has to do with temporary allocation of variables.

```diff
diff --git a/a.f90 b/a.f90
index e9ad30727..90ae15c03 100644
--- a/a.f90
+++ b/a.f90
@@ -44,7 +44,7 @@ end if
 
 do i = start + 1, end
     ! print *, "Thread ", thread_num, " is processing element ", i
-    a(i) = 1.0
+    ! a(i) = 1.0
 end do
 
 call GOMP_barrier()
```

**Comment by Pranavchiku** [comment]
With https://github.com/lfortran/lfortran/pull/4246 we get it working, next step is to support it via ASR pass. I'll open other issue for it.
