### ISSUE TITLE
Throw a nice error message for unsupported type conversions

### ISSUE THREAD

**Issue by kmr-srbh** [lfortran/lfortran#4043]
Currently, illegal type conversions lead to an unhandled exception.
```fortran
program main
   character :: x(5) = [1, 1, 0, 2, 3]
   print*, x
end program
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main_impl()
  File "./csu/../sysdeps/x86/libc-start.c", line 58, in __libc_start_call_main()
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2462, in main()
    return main_app(argc, argv);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2423, in main_app(int, char**)
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 948, in compile_to_object_file()
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/fortran_evaluator.cpp", line 359, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9807, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/pass_manager.h", line 311, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/pass_manager.h", line 167, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/init_expr.cpp", line 221, in LCompilers::pass_replace_init_expr(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    v.visit_TranslationUnit(unit);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 46823, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::InitExprVisitor>::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5143, in LCompilers::ASR::BaseVisitor<LCompilers::InitExprVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4855, in visit_symbol_t<LCompilers::InitExprVisitor>()
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/init_expr.cpp", line 155, in LCompilers::InitExprVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    visit_SymbolsContainingSymbolTable();
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/init_expr.cpp", line 147, in LCompilers::InitExprVisitor::visit_SymbolsContainingSymbolTable()
    this->visit_symbol(*sym);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5143, in LCompilers::ASR::BaseVisitor<LCompilers::InitExprVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4864, in visit_symbol_t<LCompilers::InitExprVisitor>()
    case symbolType::Variable: { v.visit_Variable((const Variable_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/init_expr.cpp", line 202, in LCompilers::InitExprVisitor::visit_Variable(LCompilers::ASR::Variable_t const&)
    call_replacer();
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/init_expr.cpp", line 121, in LCompilers::InitExprVisitor::call_replacer()
    replacer.replace_expr(*current_expr);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 46020, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceInitExpr>::replace_expr(LCompilers::ASR::expr_t*)
    self().replace_ArrayConstant(down_cast<ASR::ArrayConstant_t>(x));
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/init_expr.cpp", line 49, in LCompilers::ReplaceInitExpr::replace_ArrayConstant(LCompilers::ASR::ArrayConstant_t*)
    PassUtils::ReplacerUtils::replace_ArrayConstant(x, this,
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/pass/pass_utils.h", line 851, in replace_ArrayConstant<LCompilers::ReplaceInitExpr>()
    visit_ArrayConstant(x, replacer->al, replacer->result_var, result_vec,
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/pass_utils.cpp", line 1206, in LCompilers::PassUtils::ReplacerUtils::visit_ArrayConstant(LCompilers::ASR::ArrayConstant_t*, Allocator&, LCompilers::ASR::expr_t*, LCompilers::Vec<LCompilers::ASR::stmt_t*>*, LCompilers::ASR::expr_t*, LCompilers::SymbolTable*, bool, LCompilers::ASR::cast_kindType, LCompilers::ASR::ttype_t*)
    ASR::stmt_t* assign = builder.Assignment(res, curr_init);
AssertFailed: check_equal_type(expr_type(lhs), expr_type(rhs))
```

We should instead throw a nice error message stating the unsupported type conversion like GFortran.
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran ./examples/example.f90
./examples/example.f90:2:22:

    2 |    character :: x(5) = [1, 1, 0, 2, 3]
      |                      1
Error: Cannot convert INTEGER(4) to CHARACTER(1) at (1)
```

**Comment by kmr-srbh** [comment]
Here are some more examples:
```fortran
program example
   implicit none
   integer(4) :: nx = "a"

end program example
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
; ModuleID = 'LFortran'
source_filename = "LFortran"
.
.
.
code generation error: asr_to_llvm: module failed verification. Error:
Stored value type does not match pointer operand type!
  store i8* getelementptr inbounds ([2 x i8], [2 x i8]* @0, i32 0, i32 0), i32* @example.nx, align 8
 i32


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

<br>

```fortran
program example
   implicit none
   character, dimension(:) :: nx = "a"

end program example
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
Traceback (most recent call last):
  Binary file "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main_impl()
.
.
.
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4930, in visit_expr_t<LCompilers::ASRToLLVMVisitor>()
    LCOMPILERS_ASSERT(x.base.type == asrType::expr)
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __GI___sigaction()
Segfault: Signal SIGSEGV (segmentation fault) received
```

<br>

```fortran

```
