### ISSUE TITLE
Many Intrinsic functions dont support Boz constants. Need to fix this

### ISSUE THREAD

**Issue by parth121101** [lfortran/lfortran#4145]
```
cat a.f90                                                                               
program main
    print *, dshiftl( z"A", 10, 5)
end program
                                                                                                                                                     
gfortran a.f90 && ./a.out
         320

 lfortran a.f90
Traceback (most recent call last):
  File "/Users/parth1211/repos/lfortran/src/bin/lfortran.cpp", line 2462
    LCompilers::print_stack_on_segfault();
  File "/Users/parth1211/repos/lfortran/src/bin/lfortran.cpp", line 2426
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/parth1211/repos/lfortran/src/bin/lfortran.cpp", line 906
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/parth1211/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 252
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/parth1211/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 274
    compiler_options.symtab_only, compiler_options);
  File "/Users/parth1211/repos/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 107
    if (res.ok) {
  File "/Users/parth1211/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3718
    b.is_body_visitor = true;
  File "/Users/parth1211/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 144
    visit_ast(*x.m_items[i]);
  File "/Users/parth1211/repos/lfortran/src/lfortran/ast.h", line 4878
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/parth1211/repos/lfortran/src/lfortran/ast.h", line 4834
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/parth1211/repos/lfortran/src/lfortran/ast.h", line 4881
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/parth1211/repos/lfortran/src/lfortran/ast.h", line 4467
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/parth1211/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1569
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/parth1211/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 115
    this->visit_stmt(*m_body[i]);
  File "/Users/parth1211/repos/lfortran/src/lfortran/ast.h", line 4924
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/parth1211/repos/lfortran/src/lfortran/ast.h", line 4594
    case stmtType::Pragma: { v.visit_Pragma((const Pragma_t &)x); return; }
  File "/Users/parth1211/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3088
    visit_expr(*x.m_values[i]);
  File "/Users/parth1211/repos/lfortran/src/lfortran/ast.h", line 4976
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/parth1211/repos/lfortran/src/lfortran/ast.h", line 4632
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/Users/parth1211/repos/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 6337
    bool is_function = true;
  File "/Users/parth1211/repos/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5550
    tmp = create_func(al, x.base.base.loc, args, diag);
  File "/Users/parth1211/repos/lfortran/src/libasr/pass/intrinsic_function_registry_util.h", line 5646
    ASR::ttype_t *arg_type2 = ASRUtils::expr_type(args[2]);
  File "/Users/parth1211/repos/lfortran/src/libasr/asr_utils.h", line 2050
    type_get_past_pointer(&x))));
  File "/Users/parth1211/repos/lfortran/src/libasr/asr_utils.h", line 157
    if (ASR::is_a<ASR::Pointer_t>(*f)) {
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x18046da23
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by Pranavchiku** [comment]
This now works maybe because of https://github.com/lfortran/lfortran/pull/4487. Let's add a test and close this.
