### ISSUE TITLE
How to run integration tests with cpp backend?

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#4216]
When I run the following command, I get the following. Given there are errors, why don't we catch them up with CI checks?
```console
$ ./integration_tests/run_tests.py -b cpp
+ rm -rf /home/harshita/Desktop/lfortran/integration_tests/test-llvm
+ rm -rf /home/harshita/Desktop/lfortran/integration_tests/test-llvm2
+ rm -rf /home/harshita/Desktop/lfortran/integration_tests/test-llvm_rtlib
+ rm -rf /home/harshita/Desktop/lfortran/integration_tests/test-c
+ rm -rf /home/harshita/Desktop/lfortran/integration_tests/test-cpp
+ rm -rf /home/harshita/Desktop/lfortran/integration_tests/test-x86
+ rm -rf /home/harshita/Desktop/lfortran/integration_tests/test-wasm
+ rm -rf /home/harshita/Desktop/lfortran/integration_tests/test-gfortran
+ rm -rf /home/harshita/Desktop/lfortran/integration_tests/test-llvmImplicit
+ rm -rf /home/harshita/Desktop/lfortran/integration_tests/test-llvmStackArray
+ rm -rf /home/harshita/Desktop/lfortran/integration_tests/test-fortran
+ rm -rf /home/harshita/Desktop/lfortran/integration_tests/test-c_nopragma
+ rm -rf /home/harshita/Desktop/lfortran/integration_tests/test-llvm_nopragma
+ rm -rf /home/harshita/Desktop/lfortran/integration_tests/test-llvm_wasm
+ rm -rf /home/harshita/Desktop/lfortran/integration_tests/test-llvm_wasm_emcc
+ rm -rf /home/harshita/Desktop/lfortran/integration_tests/test-llvm_omp
+ mkdir /home/harshita/Desktop/lfortran/integration_tests/test-cpp
+ FC=lfortran FFLAGS="--openmp" cmake -DLFORTRAN_BACKEND=cpp -DFAST=no -DCURRENT_BINARY_DIR=/home/harshita/Desktop/lfortran/integration_tests/test-cpp -S /home/harshita/Desktop/lfortran/integration_tests -B /home/harshita/Desktop/lfortran/integration_tests/test-cpp
-- The C compiler identification is GNU 11.4.0
-- The Fortran compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /home/harshita/Desktop/lfortran/src/bin/lfortran - skipped


Configuration results
---------------------
Fortran compiler: /home/harshita/Desktop/lfortran/src/bin/lfortran
C compiler      : /usr/bin/cc
Build type: Debug
Fortran compiler flags: 
C compiler flags      : -g
Installation prefix: /usr/local
LFORTRAN_BACKEND: cpp
FAST: no
-- Configuring done (0.9s)
-- Generating done (0.1s)
-- Build files have been written to: /home/harshita/Desktop/lfortran/integration_tests/test-cpp
+ make -j8
[  1%] Building Fortran object CMakeFiles/program_cmake_01.dir/program_cmake_01.f90.o
[  2%] Building Fortran object CMakeFiles/program_cmake_02.dir/program_cmake_02.f90.o
[  3%] Building Fortran object CMakeFiles/error_stop_01.dir/error_stop_01.f90.o
[  4%] Building Fortran object CMakeFiles/expr_01.dir/expr_01.f90.o
[  5%] Building Fortran object CMakeFiles/print_01.dir/print_01.f90.o
[  6%] Building Fortran object CMakeFiles/cond_01.dir/cond_01.f90.o
[  7%] Building Fortran object CMakeFiles/expr_03.dir/expr_03.f90.o
[  8%] Building Fortran object CMakeFiles/expr_02.dir/expr_02.f90.o
The code C++ generated by the C++ LFortran backend uses the Kokkos libraryThe code C++ generated by the C++ LFortran backend uses the Kokkos library
(https://github.com/kokkos/kokkos). Please define the LFORTRAN_KOKKOS_DIR
environment variable to point to the Kokkos installation.
The code C++ generated by the C++ LFortran backend uses the Kokkos library

(https://github.com/kokkos/kokkos). Please define the LFORTRAN_KOKKOS_DIR(https://github.com/kokkos/kokkos). Please define the LFORTRAN_KOKKOS_DIR
environment variable to point to the Kokkos installation.

environment variable to point to the Kokkos installation.
Internal Compiler Error: Unhandled exceptionInternal Compiler Error: Unhandled exception

Internal Compiler Error: Unhandled exception
The code C++ generated by the C++ LFortran backend uses the Kokkos library
(https://github.com/kokkos/kokkos). Please define the LFORTRAN_KOKKOS_DIR
environment variable to point to the Kokkos installation.
Internal Compiler Error: Unhandled exception
The code C++ generated by the C++ LFortran backend uses the Kokkos library
(https://github.com/kokkos/kokkos). Please define the LFORTRAN_KOKKOS_DIR
environment variable to point to the Kokkos installation.
Internal Compiler Error: Unhandled exception
The code C++ generated by the C++ LFortran backend uses the Kokkos library
(https://github.com/kokkos/kokkos). Please define the LFORTRAN_KOKKOS_DIR
environment variable to point to the Kokkos installation.
Internal Compiler Error: Unhandled exception
style suggestion: Use '==' instead of '.eq.'
 --> /home/harshita/Desktop/lfortran/integration_tests/program_cmake_02.f90:4:49
  |
4 |       integer stop ; stop = 1 ; do while ( stop .eq. 0 ) ; end do
  |                                                 ^^^^ help: write this as '=='


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
The code C++ generated by the C++ LFortran backend uses the Kokkos library
(https://github.com/kokkos/kokkos). Please define the LFORTRAN_KOKKOS_DIR
environment variable to point to the Kokkos installation.
Internal Compiler Error: Unhandled exception
The code C++ generated by the C++ LFortran backend uses the Kokkos library
(https://github.com/kokkos/kokkos). Please define the LFORTRAN_KOKKOS_DIR
environment variable to point to the Kokkos installation.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2481, in ??
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2420, in main_app(int, char**)
    return compile_to_object_file_cpp(arg_file, outfile, arg_v, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 1307, in ??
    std::string kokkos_includedir = LCompilers::LFortran::get_kokkos_includedir();
LCompilersException: LFORTRAN_KOKKOS_DIR is not defined
make[2]: *** [CMakeFiles/program_cmake_01.dir/build.make:75: CMakeFiles/program_cmake_01.dir/program_cmake_01.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:171: CMakeFiles/program_cmake_01.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2481, in ??
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2420, in main_app(int, char**)
    return compile_to_object_file_cpp(arg_file, outfile, arg_v, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 1307, in ??
    std::string kokkos_includedir = LCompilers::LFortran::get_kokkos_includedir();
LCompilersException: LFORTRAN_KOKKOS_DIR is not defined
make[2]: *** [CMakeFiles/expr_02.dir/build.make:75: CMakeFiles/expr_02.dir/expr_02.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:327: CMakeFiles/expr_02.dir/all] Error 2
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2481, in ??
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2420, in main_app(int, char**)
    return compile_to_object_file_cpp(arg_file, outfile, arg_v, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 1307, in ??
    std::string kokkos_includedir = LCompilers::LFortran::get_kokkos_includedir();
LCompilersException: LFORTRAN_KOKKOS_DIR is not defined
make[2]: *** [CMakeFiles/error_stop_01.dir/build.make:75: CMakeFiles/error_stop_01.dir/error_stop_01.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:223: CMakeFiles/error_stop_01.dir/all] Error 2
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2481, in ??
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2420, in main_app(int, char**)
    return compile_to_object_file_cpp(arg_file, outfile, arg_v, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 1307, in ??
    std::string kokkos_includedir = LCompilers::LFortran::get_kokkos_includedir();
LCompilersException: LFORTRAN_KOKKOS_DIR is not defined
make[2]: *** [CMakeFiles/cond_01.dir/build.make:75: CMakeFiles/cond_01.dir/cond_01.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:275: CMakeFiles/cond_01.dir/all] Error 2
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2481, in ??
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2420, in main_app(int, char**)
    return compile_to_object_file_cpp(arg_file, outfile, arg_v, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 1307, in ??
    std::string kokkos_includedir = LCompilers::LFortran::get_kokkos_includedir();
LCompilersException: LFORTRAN_KOKKOS_DIR is not defined
make[2]: *** [CMakeFiles/program_cmake_02.dir/build.make:75: CMakeFiles/program_cmake_02.dir/program_cmake_02.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:197: CMakeFiles/program_cmake_02.dir/all] Error 2
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2481, in ??
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2420, in main_app(int, char**)
    return compile_to_object_file_cpp(arg_file, outfile, arg_v, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 1307, in ??
    std::string kokkos_includedir = LCompilers::LFortran::get_kokkos_includedir();
LCompilersException: LFORTRAN_KOKKOS_DIR is not defined
make[2]: *** [CMakeFiles/expr_03.dir/build.make:75: CMakeFiles/expr_03.dir/expr_03.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:353: CMakeFiles/expr_03.dir/all] Error 2
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2481, in ??
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2420, in main_app(int, char**)
    return compile_to_object_file_cpp(arg_file, outfile, arg_v, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 1307, in ??
    std::string kokkos_includedir = LCompilers::LFortran::get_kokkos_includedir();
LCompilersException: LFORTRAN_KOKKOS_DIR is not defined
make[2]: *** [CMakeFiles/expr_01.dir/build.make:75: CMakeFiles/expr_01.dir/expr_01.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:301: CMakeFiles/expr_01.dir/all] Error 2
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2481, in ??
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2420, in main_app(int, char**)
    return compile_to_object_file_cpp(arg_file, outfile, arg_v, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 1307, in ??
    std::string kokkos_includedir = LCompilers::LFortran::get_kokkos_includedir();
LCompilersException: LFORTRAN_KOKKOS_DIR is not defined
make[2]: *** [CMakeFiles/print_01.dir/build.make:75: CMakeFiles/print_01.dir/print_01.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:249: CMakeFiles/print_01.dir/all] Error 2
make: *** [Makefile:101: all] Error 2
Command failed.
```

**Comment by kmr-srbh** [comment]
I had faced the same issue a few days ago. You need an installation of the Kokkos library to run this. You can follow the following commands to install it:

```bash
git clone https://github.com/kokkos/kokkos.git
cd kokkos
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$HOME/kokkos ..
make -j8
make install
```

Post this, add the following environment variable to your `.bashrc` file:
```bash
export LFORTRAN_KOKKOS_DIR=$HOME/kokkos
```

You can change the installation directory according to your needs.

**Comment by HarshitaKalani** [comment]
Oh I see. Thanks for this @kmr-srbh :)

**Comment by gxyd** [comment]
Ah yes, it's documented here: https://docs.lfortran.org/en/usage/?highlight=kokkos#compiler-feature-selections
