### ISSUE TITLE
bug: add support for element-wise operations using the `WHERE` statement on logical arrays 

### ISSUE THREAD

**Issue by kmr-srbh** [lfortran/lfortran#4238]
### Minimum Reproducible Example

```fortran
PROGRAM test_program  

   LOGICAL, DIMENSION(4) :: l
   
   l = [.true., .false., .true., .false.]

   WHERE (l .neqv. .true.)
      l = .true.
   END WHERE

   PRINT *, l

END PROGRAM test_program
```

### Output

```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main_impl()
  File "./csu/../sysdeps/x86/libc-start.c", line 58, in __libc_start_call_main()
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2481, in main()
    return main_app(argc, argv);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2442, in main_app(int, char**)
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 954, in compile_to_object_file()
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/fortran_evaluator.cpp", line 363, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9904, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/pass_manager.h", line 315, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/pass_manager.h", line 169, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/where.cpp", line 349, in LCompilers::pass_replace_where(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    v.visit_TranslationUnit(unit);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 40665, in LCompilers::ASR::ASRPassBaseWalkVisitor<LCompilers::WhereVisitor>::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5157, in LCompilers::ASR::BaseVisitor<LCompilers::WhereVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4869, in visit_symbol_t<LCompilers::WhereVisitor>()
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/pass/pass_utils.h", line 299, in LCompilers::PassUtils::PassVisitor<LCompilers::WhereVisitor>::visit_Program(LCompilers::ASR::Program_t const&)
    transform_stmts(xx.m_body, xx.n_body);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/pass/pass_utils.h", line 274, in LCompilers::PassUtils::PassVisitor<LCompilers::WhereVisitor>::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    self().visit_stmt(*m_body[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5174, in LCompilers::ASR::BaseVisitor<LCompilers::WhereVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4923, in visit_stmt_t<LCompilers::WhereVisitor>()
    case stmtType::Where: { v.visit_Where((const Where_t &)x); return; }
LCompilersException: Unsupported type, 35
```

This bug was caught when manually compiling the code for `translv.f90`, which is a subroutine, by pasting it into `snap_main.f90`. This subroutine call had been previously commented out due to #4175.

**Comment by Pranavchiku** [comment]
Let's work it around and proceed, you need to do:

```fortran
do i = lbound(l, 1), ubound(l, 1)
if (l .neqv. .true.) l = .true.
end do
```
