### ISSUE TITLE
`x1 .neqv. .true.` throws compiler error

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#4279]
```fortran
program main
    logical, parameter :: x1(2) = [.true., .false.]
    print *, x1 .neqv. .true.
end program
```
```console
$ gfortran a.f90 && ./a.out
 F T
$ lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2481, in ??
    return main_app(argc, argv);

...
 b.visit_TranslationUnit(ast);
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 144, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4878, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4835, in ??
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4881, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4468, in ??
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1569, in LCompilers::LFortran::BodyVisitor::visit_Program(LCompilers::LFortran::AST::Program_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 115, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4924, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4595, in ??
    case stmtType::Print: { v.visit_Print((const Print_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3088, in LCompilers::LFortran::BodyVisitor::visit_Print(LCompilers::LFortran::AST::Print_t const&)
    visit_expr(*x.m_values[i]);
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4976, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_expr(LCompilers::LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4626, in ??
    case exprType::BoolOp: { v.visit_BoolOp((const BoolOp_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 7461, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_BoolOp(LCompilers::LFortran::AST::BoolOp_t const&)
    CommonVisitorMethods::visit_BoolOp(al, x, left, right, tmp, diag);
AssertFailed: ASR::is_a<ASR::Logical_t>(*dest_type)

```

**Comment by kmr-srbh** [comment]
Due to implicit casting, `dest_type`, which we get from `right_type`, is converted from `logical` to `logical[:]` for the operation. I think handling logical arrays should work. I have a fix in mind. Let me try to see if it works.

**Comment by Pranavchiku** [comment]
@kmr-srbh thanks for this! do you know how to fix it? If yes, go ahead and submit a PR. In general I'll ask you and @assem2002 to prioritise SNAP while @parth121101 and @HarshitaKalani tackle intrinsic related bugs.

**Comment by kmr-srbh** [comment]
This works now:
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
False True 
```

I will open the PR with the tests tomorrow morning (IST) after doing some cleanups.
