### ISSUE TITLE
Experiences with LFortran

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#431]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/574

The code for the [demo](https://gitlab.com/lfortran/examples/mvp_demo/-/tree/master/src) uses arrays. With LFortran on WSL 2, I can run a small program interactively such as 

```
integer :: i
i = 3
print*,i,i**2
```

but I can't use arrays. When run interactively the program

```
integer :: ivec(1)
ivec(1)  = 3
```
gives a segmentation fault.

However, if I store

```
program main
integer :: ivec(1)
ivec(1) = 3
print*,ivec
end program main
```
in `vec.f90` I can compile it with `lfortran vec.f90` and run it.

LFortran does not recognize the one-line program `end`. 

`lfortran end.f90`

gives

`input:1:1 semantic error: Variable 'end' not declared`

**Comment by certik** [comment]
Yes, we will fix all these issues in interactive mode. Our main focus right now is to bring LFortran from "alpha" to "beta", focusing on minpack (#512). If you want to help iron out some of the interactive issues, I am happy to meet over video to get you started. It's not difficult.

**Comment by omaclaren** [comment]
That sounds good! I will send you an email...

**Comment by certik** [comment]
Here is how to reproduce the problem in a non-interactive mode:
```console
$ cat a.f90 
integer :: x(3)
x = 5
$ lfortran --show-llvm a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1696
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 688
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 266
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 287
    Result<std::unique_ptr<LLVMModule>> res = get_llvm3(*asr.result, pass_manager, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 320
    compiler_options, run_fn);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6127
    v.nested_func_types = pass_find_nested_vars(asr, context,
  File "../libasr/asr.h", line 4080
  File "../libasr/asr.h", line 4057
  File "../libasr/asr.h", line 4081
  File "../libasr/asr.h", line 3836
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1145
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 4083
  File "../libasr/asr.h", line 3846
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3021
    visit_procedures(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3335
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4098
  File "../libasr/asr.h", line 3867
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3730
    this->visit_expr_wrapper(x.m_value, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3788
    this->visit_expr(*x);
  File "../libasr/asr.h", line 4141
  File "../libasr/asr.h", line 3927
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4229
    this->visit_expr_wrapper(x.m_left, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3788
    this->visit_expr(*x);
  File "../libasr/asr.h", line 4141
  File "../libasr/asr.h", line 3964
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6089
    llvm::Value* dim_des_val = arr_descr->get_pointer_to_dimension_descriptor_array(llvm_arg1);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 249
    llvm::Value* dim_des_arr_ptr = llvm_utils->create_gep(arr, 2);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 120
    return LLVM::CreateGEP(*builder, ds, idx_vec);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 24
    LFORTRAN_ASSERT(t->isPointerTy());
AssertFailed: t->isPointerTy()
```

**Comment by certik** [comment]
Here I resurrected the old patch and it makes progress towards fixing it: https://github.com/lfortran/lfortran/pull/931

**Comment by HarshitaKalani** [comment]
This works fine with the latest main!

**Comment by certik** [comment]
The following:
```fortran
integer :: x(3)
x = 5
```
Now gives:
```console
$ lfortran a.f90 
syntax error: Expected program end
 --> a.f90:1:1 - 2:5
  |
1 |    integer :: x(3)
  |    ^^^^^^^^^^^^^^^...
...
  |
2 |    x = 5
  | ...^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
So that's not a bad error message. Adding `end` at the end now works.

In interactive mode I get:
```console
$ lfortran 
Interactive Fortran. Experimental prototype, not ready for end users.
LFortran version: 0.19.0-1011-gf876312da
  * Use Ctrl-D to exit
  * Use Enter to submit
  * Use Alt-Enter or Ctrl-N to make a new line
    - Editing (Keys: Left, Right, Home, End, Backspace, Delete)
    - History (Keys: Up, Down)
>>> integer :: x(3)                                                      1,16  ]
code generation error: Variable type not supported 20
 --> input:1:12
  |
1 | integer :: x(3)
  |            ^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
So it still does not work yet.

**Comment by kmr-srbh** [comment]
The above example now works interactively in the latest main.

```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran
Interactive Fortran. Experimental prototype, not ready for end users.
LFortran version: 0.38.0-178-gf348de56f
  * Use Ctrl-D to exit
  * Use Enter to submit
  * Use Alt-Enter or Ctrl-N to make a new line
    - Editing (Keys: Left, Right, Home, End, Backspace, Delete)
    - History (Keys: Up, Down)
>>> integer :: x(3)                                                                                                                                                               1,16  ]
>>> x = 5                                                                                                                                                                         1,6   ]
>>> print *, x                                                                                                                                                                    1,11  ]
5 5 5 
```

**Comment by certik** [comment]
It looks like this particular bug is indeed fixed. If we haven't done so yet, let's add a test for this into `src/lfortran/tests/test_llvm.cpp` then we can close this issue.

**Comment by omaclaren** [comment]
very cool, awesome work!
