### ISSUE TITLE
Compile parallel sparse matrix vector multiply with openmp

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#4333]
https://github.com/certik/hfsolver/blob/b4c50c1979fb7e468b1852b144ba756f5a51788d/src/sparse.f90#L200

```fortran
function csr_matvec(Ap, Aj, Ax, x) result(y)
! Compute y = A*x for CSR matrix A and dense vectors x, y
integer, intent(in) :: Ap(:), Aj(:)
real(dp), intent(in) :: Ax(:), x(:)
real(dp) :: y(size(Ap)-1)
integer :: i
!$omp parallel default(none) shared(Ap, Aj, Ax, x, y) private(i)
!$omp do
do i = 1, size(Ap)-1
    y(i) = dot_product(Ax(Ap(i):Ap(i+1)-1), x(Aj(Ap(i):Ap(i+1)-1)))
end do
!$omp end do
!$omp end parallel
end function
```

**Comment by Pranavchiku** [comment]
I think we need to do a few bug fixes before we can run this code ( without `--openmp` )

```fortran
% lfortran a.f90 --show-asr
semantic error: `dot_product` accepts arrays of rank 1 only, provided an array with rank, 0
  --> a.f90:10:45
   |
10 |     y(i) = dot_product(Ax(Ap(i):Ap(i+1)-1), x(Aj(Ap(i):Ap(i+1)-1)))
   |                                             ^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

**Comment by Pranavchiku** [comment]
I am using this instead:

```fortran
function csr_matvec(Ap, Aj, Ax, x) result(y)
! Compute y = A*x for CSR matrix A and dense vectors x, y
integer, intent(in) :: Ap(:), Aj(:)
real, intent(in) :: Ax(:), x(:)
real :: y(size(Ap)-1)
integer :: i
!$omp parallel shared(Ap, Aj, Ax, x, y) private(i)
!$omp do
do i = 1, size(Ap)-1
    y(i) = dot_product2(Ax(Ap(i):Ap(i+1)-1), x(Aj(Ap(i):Ap(i+1)-1)))
end do
!$omp end do
!$omp end parallel
contains
real function dot_product2(x, y) result(s)
! Compute the dot product of two vectors x and y
real, intent(in) :: x(:), y(:)
integer :: i
s = 0.0
do i = 1, size(x)
    s = s + x(i)*y(i)
end do
end function
end function
```

**Comment by Pranavchiku** [comment]
Here is full example that works with `gfortran`, and `lfortran --openmp` translates it correctly but it fails with same error as without `--openmp`

```fortran
real function dot_product2(x, y) result(s)
! Compute the dot product of two vectors x and y
real, intent(in) :: x(:), y(:)
integer :: i
s = 0.0
do i = 1, size(x)
    s = s + x(i)*y(i)
end do
end function

subroutine csr_matvec(Ap, Aj, Ax, x, y)
! Compute y = A*x for CSR matrix A and dense vectors x, y
interface
real function dot_product2(x, y) result(s)
real, intent(in) :: x(:), y(:)
end function
end interface
integer, intent(in) :: Ap(:), Aj(:)
real, intent(in) :: Ax(:), x(:)
real, intent(inout) :: y(size(Ap)-1)
integer :: i
!$omp parallel shared(Ap, Aj, Ax, x, y) private(i)
!$omp do
do i = 1, size(Ap)-1
    y(i) = dot_product2(Ax(Ap(i):Ap(i+1)-1), x(Aj(Ap(i):Ap(i+1)-1)))
end do
!$omp end do
!$omp end parallel
print *, y(1:10)
end subroutine

program main
use omp_lib
implicit none
interface
subroutine csr_matvec(Ap, Aj, Ax, x, y)
integer, intent(in) :: Ap(:), Aj(:) 
real, intent(in) :: Ax(:), x(:)
real, intent(inout) :: y(size(Ap)-1)
end subroutine
end interface

integer, parameter :: n = 100
integer :: i
real :: x(n), y(n)
integer, allocatable :: Ap(:), Aj(:)
real, allocatable :: Ax(:)
! Initialize CSR matrix A
allocate(Ap(n+1), Aj(3*n), Ax(3*n))
Ap = [(3*i, i=0,n)]
Aj = [(3*i-1, 3*i, 3*i+1, i=1,n)]
Ax = [(1.0, 2.0, 3.0, i=1,3*n)]
! Initialize vector x
x = [(i, i=1,n)]
! Compute y = A*x
call csr_matvec(Ap, Aj, Ax, x, y)
! Print the result
end program
```

```console
% gfortran a.f90 -fopenmp && ./a.out
   8.00000000       29.0000000       47.0000000       65.0000000       83.0000000       101.000000       119.000000       137.000000       155.000000       173.000000    
```


```console
% lfortran a.f90                    
Assertion failed: (V->getType()->isIntOrIntVectorTy() && DestTy->isIntOrIntVectorTy() && "Can only sign extend/truncate integers!"), function CreateSExtOrTrunc, file IRBuilder.h, line 1991.
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2478
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2442
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 954
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 363
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9973
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 5154
  File "../libasr/asr.h", line 5130
  File "../libasr/asr.h", line 5155
  File "../libasr/asr.h", line 4861
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 973
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5157
  File "../libasr/asr.h", line 4870
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3865
    visit_procedures(x);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4062
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5174
  File "../libasr/asr.h", line 4923
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5884
    create_loop(x.m_name, [=]() {
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 347
    start_new_block(loopbody); {
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5890
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5174
  File "../libasr/asr.h", line 4894
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4946
    ptr_loads = 2 - (ASRUtils::is_character(*value_type) ||
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5363
    this->visit_expr(*x);
  File "../libasr/asr.h", line 5222
  File "../libasr/asr.h", line 4948
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9544
    std::vector<llvm::Value *> args2 = convert_call_args(x, is_method);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8484
    this->visit_expr_wrapper(x.m_args[i].m_value);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5363
    this->visit_expr(*x);
  File "../libasr/asr.h", line 5222
  File "../libasr/asr.h", line 5010
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2372
    tmp = arr_descr->get_single_element(type, array, indices, x.n_args,
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 643
    idx = cmo_convertor_single_element_data_only(llvm_diminfo, m_args, n_args, check_for_bounds, is_unbounded_pointer_to_data);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 615
    curr_llvm_idx = builder->CreateSExtOrTrunc(curr_llvm_idx, llvm::Type::getInt32Ty(context));
  File "/Users/pranavchiku/mambaforge/envs/lf/include/llvm/IR/IRBuilder.h", line 1989
    assert(V->getType()->isIntOrIntVectorTy() &&
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x180352d1f
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x180353a2f
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x180446c1f
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x180477583
Abort: Signal SIGABRT (abort) received

zsh: abort      lfortran a.f90
```

**Comment by Pranavchiku** [comment]
MRE:

```fortran
subroutine csr_matvec(Ap, Aj, x)
integer, intent(in) :: Ap(:), Aj(:)
real, intent(in) :: x(:)
integer :: i
print *, x(Aj(Ap(i):Ap(i+1)-1))
end subroutine

program main
end program
```

```console
% lfortran b.f90
Assertion failed: (V->getType()->isIntOrIntVectorTy() && DestTy->isIntOrIntVectorTy() && "Can only sign extend/truncate integers!"), function CreateSExtOrTrunc, file IRBuilder.h, line 1991.
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2478
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2442
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 954
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 363
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9973
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 5154
  File "../libasr/asr.h", line 5130
  File "../libasr/asr.h", line 5155
  File "../libasr/asr.h", line 4861
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 973
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5157
  File "../libasr/asr.h", line 4870
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3865
    visit_procedures(x);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4062
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5174
  File "../libasr/asr.h", line 4908
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7869
    handle_print(x);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8164
    compute_fmt_specifier_and_arg(fmt, args, x.m_values[i], x.base.base.loc);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7983
    this->visit_expr_wrapper(v, true);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5363
    this->visit_expr(*x);
  File "../libasr/asr.h", line 5222
  File "../libasr/asr.h", line 5010
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2372
    tmp = arr_descr->get_single_element(type, array, indices, x.n_args,
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 643
    idx = cmo_convertor_single_element_data_only(llvm_diminfo, m_args, n_args, check_for_bounds, is_unbounded_pointer_to_data);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 615
    curr_llvm_idx = builder->CreateSExtOrTrunc(curr_llvm_idx, llvm::Type::getInt32Ty(context));
  File "/Users/pranavchiku/mambaforge/envs/lf/include/llvm/IR/IRBuilder.h", line 1989
    assert(V->getType()->isIntOrIntVectorTy() &&
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x180352d1f
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x180353a2f
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x180446c1f
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x180477583
Abort: Signal SIGABRT (abort) received

zsh: abort      lfortran b.f90
```
