### ISSUE TITLE
Give better error message when trying to compile a missing program

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#434]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/577

If `main.f90` does not exist,
`$ gfortran main.f90`
gives
`gfortran: error: main.f90: No such file or directory`
which is a better error message than
```
$ lfortran main.f90
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
The command 'gcc -o a.out a.out.tmp.o  -L"/home/bingy/miniconda3/envs/mvp_demo/bin/../share/lfortran/lib" -Wl,-rpath,"/home/bingy/miniconda3/envs/mvp_demo/bin/../share/lfortran/lib" -llfortran_runtime -lm' failed.
```
which is an error message I would expect if main.f90 existed but did not contain a main program.

**Comment by HarshitaKalani** [comment]
With the latest main, it is as below:
```console
$ gfortran main.f90
f951: Error: Cannot open file ‘main.f90’
<built-in>: Fatal Error: cannot open input file: main.f90
compilation terminated.
$ lfortran main.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
LCompilersException: File does not exist: main.f90
```
