### ISSUE TITLE
bug: calling `MAXLOC` on an array whose dimension is set using a subroutine argument leads to an `ASR verify pass error`

### ISSUE THREAD

**Issue by kmr-srbh** [lfortran/lfortran#4342]
### Minimal Reproducible Example

```fortran
MODULE thrd_comm_module
   IMPLICIT NONE

CONTAINS

   SUBROUTINE assign_thrd_set (tlen, do_task)

      INTEGER, INTENT(IN) ::tlen
      INTEGER, DIMENSION(tlen), INTENT(OUT) :: do_task

      INTEGER :: next
      next = MAXLOC( do_task, 1 )
      PRINT *, next

   END SUBROUTINE assign_thrd_set

END MODULE thrd_comm_module

PROGRAM main

   USE thrd_comm_module, ONLY: assign_thrd_set

   INTEGER, DIMENSION(1) :: do_grp
   CALL assign_thrd_set(1, do_grp)

END PROGRAM main
```

### Output
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
ASR verify pass error: ASR verify: The symbol table was not found in the scope of `symtab`.

ASR verify pass error: Var::m_v `tlen` cannot point outside of its symbol table
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main_impl()
  File "./csu/../sysdeps/x86/libc-start.c", line 58, in __libc_start_call_main()
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2481, in main()
    return main_app(argc, argv);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2442, in main_app(int, char**)
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 954, in compile_to_object_file()
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/fortran_evaluator.cpp", line 363, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9967, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/pass_manager.h", line 315, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
LCompilersException: Verify failed in the pass: intrinsic_function
```

**Comment by kmr-srbh** [comment]
In the transformed code after the `intrinsic_function` pass, we observe that in the created `_lcompilers_MaxLoc` function, the dimension of array `array` is set to `tlen`, but `tlen` is found neither in the function scope nor the program scope as it is present inside the subroutine `assign_thrd_set`.

```fortran
! Fortran code after applying the pass: intrinsic_function
module thrd_comm_module
implicit none

contains

subroutine assign_thrd_set(tlen, do_task)
    integer(4), intent(in) :: tlen
    integer(4), dimension(tlen), intent(out) :: do_task
    integer(4) :: next
    next = _lcompilers_MaxLoc(do_task, 1)
    print *, next
end subroutine assign_thrd_set

end module thrd_comm_module

program main
use thrd_comm_module, only: assign_thrd_set
implicit none
integer(4), dimension(1) :: do_grp
call assign_thrd_set(1, do_grp)

contains

integer(4) function _lcompilers_MaxLoc(array, dim) result(result)
    integer(4) :: __1_j
    integer(4), dimension(tlen), intent(in) :: array
    integer(4), intent(in) :: dim
    result = 1
    if (dim == 1) then
        do __1_j = lbound(array, 1), ubound(array, 1)
            if (array(__1_j) > array(result)) then
                result = __1_j
            end if
        end do
    end if
    return
end function _lcompilers_MaxLoc

end program main
```

**Comment by assem2002** [comment]
is it possible to fix it without passing the dimension itself as arg to to `_lcompilers_MaxLoc`?
