### ISSUE TITLE
Throw error when the type of argument is different for runtime evaluation of `dshiftl`

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#4373]
```fortran
program main
    integer :: i1 = 1
    integer(8) :: i2 = 1_8
    print *, dshiftl(i1, i2, 1)
end program
```
```console
$ gfortran b.f90 && ./a.out
b.f90:4:25:

    4 |     print *, dshiftl(i1, i2, 1)
      |                         1
Error: ‘j’ argument of ‘dshiftl’ intrinsic at (1) must be the same type and kind as ‘i’
$ lfortran b.f90
; ModuleID = 'LFortran'
source_filename = "LFortran"

@main.i1 = internal global i32 0
@main.i2 = internal global i64 0
@0 = private unnamed_addr constant [2 x i8] c" \00", align 1
@1 = private unnamed_addr constant [2 x i8] c"\0A\00", align 1
@2 = private unnamed_addr constant [5 x i8] c"%d%s\00", align 1

define i32 @_lcompilers_dshiftl_i32(i32* %i, i64* %j, i32* %shift) {
.entry:
  %_lcompilers_dshiftl_i32 = alloca i32, align 4
  %0 = load i32, i32* %i, align 4
  %1 = load i32, i32* %shift, align 4
  %2 = shl i32 %0, %1
  store i32 %2, i32* %_lcompilers_dshiftl_i32, align 4
  br i1 true, label %then, label %else

then:                                             ; preds = %.entry
  %3 = load i32, i32* %_lcompilers_dshiftl_i32, align 4
  %4 = load i64, i64* %j, align 4
  %5 = load i32, i32* %shift, align 4
  %6 = sub i32 32, %5
  %7 = ashr i64 %4, i32 %6
  %8 = or i32 %3, i64 %7
  store i32 %8, i32* %_lcompilers_dshiftl_i32, align 4
  br label %ifcont

else:                                             ; preds = %.entry
  %9 = load i32, i32* %_lcompilers_dshiftl_i32, align 4
  %10 = load i64, i64* %j, align 4
  %11 = load i32, i32* %shift, align 4
  %12 = sub i32 64, %11
  %13 = ashr i64 %10, i32 %12
  %14 = or i32 %9, i64 %13
  store i32 %14, i32* %_lcompilers_dshiftl_i32, align 4
  br label %ifcont

ifcont:                                           ; preds = %else, %then
  br label %return

return:                                           ; preds = %ifcont
  %15 = load i32, i32* %_lcompilers_dshiftl_i32, align 4
  ret i32 %15
}

define i32 @main(i32 %0, i8** %1) {
.entry:
  %call_arg_value = alloca i32, align 4
  call void @_lpython_call_initial_functions(i32 %0, i8** %1)
  store i32 1, i32* @main.i1, align 4
  store i64 1, i64* @main.i2, align 4
  store i32 1, i32* %call_arg_value, align 4
  %2 = call i32 @_lcompilers_dshiftl_i32(i32* @main.i1, i64* @main.i2, i32* %call_arg_value)
  call void (i8*, ...) @_lfortran_printf(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @2, i32 0, i32 0), i32 %2, i8* getelementptr inbounds ([2 x i8], [2 x i8]* @1, i32 0, i32 0))
  ret i32 0
}

declare void @_lpython_call_initial_functions(i32, i8**)

declare void @_lfortran_printf(i8*, ...)
asr_to_llvm: module failed verification. Error:
Both operands to a binary operator are not of the same type!
  %7 = ashr i64 %4, i32 %6
Both operands to a binary operator are not of the same type!
  %8 = or i32 %3, i64 %7
Both operands to a binary operator are not of the same type!
  %13 = ashr i64 %10, i32 %12
Both operands to a binary operator are not of the same type!
  %14 = or i32 %9, i64 %13

code generation error: asr_to_llvm: module failed verification. Error:
Both operands to a binary operator are not of the same type!
  %7 = ashr i64 %4, i32 %6
Both operands to a binary operator are not of the same type!
  %8 = or i32 %3, i64 %7
Both operands to a binary operator are not of the same type!
  %13 = ashr i64 %10, i32 %12
Both operands to a binary operator are not of the same type!
  %14 = or i32 %9, i64 %13



Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

**Comment by HarshitaKalani** [comment]
The following happens for `ior`, `iand` and `ieor`
```fortran
program main
    integer :: i1 = 1
    integer(8) :: i2 = 1_8
    print *, ior(i1, i2)
end program
```
```console
$ lfortran b.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2481, in ??
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2442, in main_app(int, char**)
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 954, in ??
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 363, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9967, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 315, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 169, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/intrinsic_function.cpp", line 433, in LCompilers::pass_replace_intrinsic_function(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    v.visit_TranslationUnit(unit);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 47036, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5157, in LCompilers::ASR::BaseVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4869, in ??
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 47047, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_Program(LCompilers::ASR::Program_t const&)
    self().transform_stmts(xx.m_body, xx.n_body);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 47029, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    self().visit_stmt(*m_body[i]);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5174, in LCompilers::ASR::BaseVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4909, in ??
    case stmtType::Print: { v.visit_Print((const Print_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 47389, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_Print(LCompilers::ASR::Print_t const&)
    self().call_replacer();
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/intrinsic_function.cpp", line 147, in LCompilers::ReplaceIntrinsicFunctionsVisitor::call_replacer()
    replacer.replace_expr(*current_expr);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 45993, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceIntrinsicFunctions>::replace_expr(LCompilers::ASR::expr_t*)
    self().replace_IntrinsicElementalFunction(down_cast<ASR::IntrinsicElementalFunction_t>(x));
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/intrinsic_function.cpp", line 76, in LCompilers::ReplaceIntrinsicFunctions::replace_IntrinsicElementalFunction(LCompilers::ASR::IntrinsicElementalFunction_t*)
    ASR::expr_t* current_expr_ = instantiate_function(al, x->base.base.loc,
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/pass/intrinsic_functions.h", line 1708, in ??
    body.push_back(al, b.Assignment(result, b.Or(args[0], args[1])));
AssertFailed: check_equal_type(expr_type(left), expr_type(right))
$ gfortran a.f90 && ./a.out
a.f90:4:17:

    4 |     print *, ior(i1, i2)
      |                 1
Error: Arguments of ‘ior’ have different kind type parameters at (1)
```

**Comment by HarshitaKalani** [comment]
closing this as works now.
```console
$ gfortran a.f90 && ./a.out
a.f90:4:17:

    4 |     print *, ior(i1, i2)
      |                 1
Error: Arguments of ‘ior’ have different kind type parameters at (1)
$ lfortran a.f90
semantic error: Kind of all the arguments of Ior must be the same
 --> a.f90:4:14
  |
4 |     print *, ior(i1, i2)
  |              ^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
