### ISSUE TITLE
defining function variable to specify return type throws error

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#4376]
Required for #4346

```fortran
subroutine r8_mxm( l, m )
implicit none
integer :: l, m
double precision :: b(l,m)
integer :: seed
double precision :: r8_uniform_01
b(1,1) = r8_uniform_01( seed )
end
function r8_uniform_01( seed )
implicit none
double precision :: r8_uniform_01
integer :: seed
r8_uniform_01 = real(seed, kind=8)
return
end
```

```console
% lfortran a.f90 
ASR verify pass error: The variable in ArrayItem must be an array, not a scalar
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2478
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2442
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 912
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 256
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 278
    compiler_options.symtab_only, compiler_options);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 107
    if (res.ok) {
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3811
    b.is_body_visitor = true;
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 144
    visit_ast(*x.m_items[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4878
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4835
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4886
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4477
    case program_unitType::Procedure: { v.visit_Procedure((const Procedure_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2037
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 115
    this->visit_stmt(*m_body[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4924
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4569
    case stmtType::Assign: { v.visit_Assign((const Assign_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2352
    ASR::expr_t *target = ASRUtils::EXPR(tmp);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4976
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4632
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 6470
    bool is_function = true;
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5727
    return resolve_intrinsic_function(x.base.base.loc, var_name);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 6800
    ASR::Module_t *m = ASRUtils::load_module(al, tu_symtab, module_name,
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.cpp", line 392
    throw LCompilersException("Verify failed");
LCompilersException: Verify failed
```

**Comment by Jatinagarwal24** [comment]
Current behaviour on main 
```
(lf) root@LAPTOP-8SLTQKJO:~/lfortran# lfortran examples/expr2.f90 --implicit-interface -c
```
```
(lf) root@LAPTOP-8SLTQKJO:~/lfortran# gfortran examples/expr2.f90 -c
```

**Comment by Jatinagarwal24** [comment]
I will soon raise a pr to fix it.
