### ISSUE TITLE
Error in accessing array elements with integer index array

### ISSUE THREAD

**Issue by shivimathur** [lfortran/lfortran#4420]
Towards: https://github.com/lfortran/lfortran/issues/4397
```f90
program main
  implicit none

  ! Logical array
  logical, dimension(5) :: x = [.TRUE., .FALSE., .TRUE., .FALSE., .TRUE.]

  ! Integer array with indices
  integer, dimension(3) :: loc = [2, 4, 1]

  ! Access elements using x(loc)
  print*, "x(loc) =", x(loc)

end program
```
```console
$ gfortran a.f90 && ./a.out
 x(loc) = F F T
$ lfortran a.f90 
lfortran: /home/shivi/anaconda3/envs/lf/include/llvm/IR/IRBuilder.h:1989: llvm::Value* llvm::IRBuilderBase::CreateSExtOrTrunc(llvm::Value*, llvm::Type*, const llvm::Twine&): Assertion `V->getType()->isIntOrIntVectorTy() && DestTy->isIntOrIntVectorTy() && "Can only sign extend/truncate integers!"' failed.
Traceback (most recent call last):
  Binary file "/home/shivi/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/shivi/lfortran/src/bin/lfortran.cpp", line 2481, in ??
    return main_app(argc, argv);
  File "/home/shivi/lfortran/src/bin/lfortran.cpp", line 2442, in main_app(int, char**)
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/shivi/lfortran/src/bin/lfortran.cpp", line 954, in ??
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/shivi/lfortran/src/lfortran/fortran_evaluator.cpp", line 363, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/shivi/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9973, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/shivi/lfortran/src/libasr/../libasr/asr.h", line 5154, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/shivi/lfortran/src/libasr/../libasr/asr.h", line 5130, in ??
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/shivi/lfortran/src/libasr/../libasr/asr.h", line 5155, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/shivi/lfortran/src/libasr/../libasr/asr.h", line 4861, in ??
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/shivi/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 980, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/home/shivi/lfortran/src/libasr/../libasr/asr.h", line 5157, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/shivi/lfortran/src/libasr/../libasr/asr.h", line 4869, in ??
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/shivi/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3186, in LCompilers::ASRToLLVMVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/home/shivi/lfortran/src/libasr/../libasr/asr.h", line 5174, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/shivi/lfortran/src/libasr/../libasr/asr.h", line 4909, in ??
    case stmtType::Print: { v.visit_Print((const Print_t &)x); return; }
  File "/home/shivi/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7869, in LCompilers::ASRToLLVMVisitor::visit_Print(LCompilers::ASR::Print_t const&)
    handle_print(x);
  File "/home/shivi/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8164, in void LCompilers::ASRToLLVMVisitor::handle_print<LCompilers::ASR::Print_t>(LCompilers::ASR::Print_t const&)
    compute_fmt_specifier_and_arg(fmt, args, x.m_values[i], x.base.base.loc);
  File "/home/shivi/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7983, in LCompilers::ASRToLLVMVisitor::compute_fmt_specifier_and_arg(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&, LCompilers::ASR::expr_t*, LCompilers::Location const&)
    this->visit_expr_wrapper(v, true);
  File "/home/shivi/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5363, in LCompilers::ASRToLLVMVisitor::visit_expr_wrapper(LCompilers::ASR::expr_t*, bool)
    this->visit_expr(*x);
  File "/home/shivi/lfortran/src/libasr/../libasr/asr.h", line 5222, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/shivi/lfortran/src/libasr/../libasr/asr.h", line 5011, in ??
    case exprType::ArrayItem: { v.visit_ArrayItem((const ArrayItem_t &)x); return; }
  File "/home/shivi/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2372, in LCompilers::ASRToLLVMVisitor::visit_ArrayItem(LCompilers::ASR::ArrayItem_t const&)
    tmp = arr_descr->get_single_element(type, array, indices, x.n_args,
  File "/home/shivi/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 643, in LCompilers::LLVMArrUtils::SimpleCMODescriptor::get_single_element(llvm::Type*, llvm::Value*, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&, int, bool, bool, llvm::Value**, bool, llvm::Type*, bool)
    idx = cmo_convertor_single_element_data_only(llvm_diminfo, m_args, n_args, check_for_bounds, is_unbounded_pointer_to_data);
  File "/home/shivi/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 615, in LCompilers::LLVMArrUtils::SimpleCMODescriptor::cmo_convertor_single_element_data_only(llvm::Value**, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&, int, bool, bool)
    curr_llvm_idx = builder->CreateSExtOrTrunc(curr_llvm_idx, llvm::Type::getInt32Ty(context));
  File "/home/shivi/anaconda3/envs/lf/include/llvm/IR/IRBuilder.h", line 1989, in llvm::IRBuilderBase::CreateSExtOrTrunc(llvm::Value*, llvm::Type*, llvm::Twine const&)
    assert(V->getType()->isIntOrIntVectorTy() &&
  File "./assert/assert.c", line 101, in __GI___assert_fail()
  File "./assert/assert.c", line 92, in __assert_fail_base()
  File "./stdlib/abort.c", line 79, in __GI_abort()
  File "./signal/../sysdeps/posix/raise.c", line 26, in __GI_raise()
  File "./nptl/pthread_kill.c", line 43, in __pthread_kill_implementation()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __GI___sigaction()
Abort: Signal SIGABRT (abort) received

Aborted (core dumped)
```

**Comment by kmr-srbh** [comment]
The transformed code after applying all passes has `loc` passed to `x` directly as `x(loc)`:

<details>

```fortran
! Fortran code after applying the pass: insert_deallocate
program main
implicit none
integer(4) :: __1_k
integer(4), dimension(3), save :: loc
logical(4), dimension(5), save :: x
__1_k = lbound(loc, 1)
loc(__1_k) = 2
__1_k = __1_k + 1
loc(__1_k) = 4
__1_k = __1_k + 1
loc(__1_k) = 1
__1_k = __1_k + 1
__1_k = lbound(x, 1)
x(__1_k) = .true.
__1_k = __1_k + 1
x(__1_k) = .false.
__1_k = __1_k + 1
x(__1_k) = .true.
__1_k = __1_k + 1
x(__1_k) = .false.
__1_k = __1_k + 1
x(__1_k) = .true.
__1_k = __1_k + 1
print *, "x(loc) =", x(loc)
end program main
```

</details>

I think we probably need to convert it to:
```fortran
do i = 1, ubound(loc, 1)
  print *, x(loc(i))
end do
```
in the `array_op` pass. 

GFortran handles this in the same way:

<details>

```c
__attribute__((fn spec (". ")))
void MAIN__ ()
{
  static integer(kind=4) loc[3] = {2, 4, 1};
  static logical(kind=4) x[5] = {1, 0, 1, 0, 1};

  {
    struct __st_parameter_dt dt_parm.0;

    dt_parm.0.common.filename = &"./examples/example.f90"[1]{lb: 1 sz: 1};
    dt_parm.0.common.line = 11;
    dt_parm.0.common.flags = 128;
    dt_parm.0.common.unit = 6;
    _gfortran_st_write (&dt_parm.0);
    _gfortran_transfer_character_write (&dt_parm.0, &"x(loc) ="[1]{lb: 1 sz: 1}, 8);
    {
      struct array01_integer(kind=4) parm.1;
      struct array01_logical(kind=4) atmp.2;
      logical(kind=4) A.3[3];

      parm.1.span = 4;
      parm.1.dtype = {.elem_len=4, .rank=1, .type=1};
      parm.1.dim[0].lbound = 1;
      parm.1.dim[0].ubound = 3;
      parm.1.dim[0].stride = 1;
      parm.1.data = (void *) &loc[0];
      parm.1.offset = -1;
            typedef logical(kind=4) [3];
      atmp.2.dtype = {.elem_len=4, .rank=1, .type=2};
      atmp.2.dim[0].stride = 1;
      atmp.2.dim[0].lbound = 0;
      atmp.2.dim[0].ubound = 2;
      atmp.2.span = 4;
      atmp.2.data = (void * restrict) &A.3;
      atmp.2.offset = 0;
      {
        integer(kind=8) S.4;

        S.4 = 0;
        while (1)
          {
            if (S.4 > 2) goto L.1;
            {
              integer(kind=4) D.4301;

              D.4301 = *(integer(kind=4) *) (parm.1.data + (sizetype) ((parm.1.dim[0].stride * NON_LVALUE_EXPR <S.4>) * 4));
              (*(logical(kind=4)[3] * restrict) atmp.2.data)[S.4] = x[(integer(kind=8)) D.4301 + -1];
            }
            S.4 = S.4 + 1;
          }
        L.1:;
      }
      _gfortran_transfer_array_write (&dt_parm.0, &atmp.2, 4, 0);
    }
    _gfortran_st_write_done (&dt_parm.0);
  }
}


__attribute__((externally_visible))
integer(kind=4) main (integer(kind=4) argc, character(kind=1) * * argv)
{
  static integer(kind=4) options.5[7] = {2116, 4095, 0, 1, 1, 0, 31};

  _gfortran_set_args (argc, argv);
  _gfortran_set_options (7, &options.5[0]);
  MAIN__ ();
  return 0;
}
```


I will try to look into this after I am done with #4405.

**Comment by Pranavchiku** [comment]
Precisely, I think you got correct fix.  More specifically 

```fortran
do i = lbound(loc, 1), ubound(loc, 1)
  print *, x(loc(i))
end do
```

**Comment by Pranavchiku** [comment]
@shivimathur you can try this out maybe, it is similar to broadcasting `IntrinsicElementalFunction`.

Take the following example:

```fortran
program main
        real :: loc(3)
        print *, sin(loc)
end program
```

Here `sin` is an `IntrinsicElementalFunction` and `loc` is an array.  In original example `x` is Array and `loc` as well, so the node turns out to be `ArrayItem`

```clojure
(IntrinsicElementalFunction
    Sin
    [(Var 2 x)]
    0
    (Array
        (Real 4)
        [((IntegerConstant 1 (Integer 4))
        (IntegerConstant 5 (Integer 4)))]
        FixedSizeArray
    )
    ()
)
```

```clojure
(ArrayItem
    (Var 2 x)
    [(()
    (Var 2 loc)
    ())]
    (Logical 4)
    ColMajor
    ()
)
```


Now, when you execute the command `lfortran a.f90 --dump-all-passes` on this example and observe `pass_11_subroutine_from_function.clj` you will find `IntrinsicElementalFunction` node as it is but when you do observe `pass_12_array_op.clj` you will find something like:


```clojure
                (DoLoop
                        ()
                        ((Var 2 __1_t)
                        (ArrayBound
                            (Var 2 __libasr__created__var__0__elemental_func_call_res)
                            (IntegerConstant 1 (Integer 4))
                            (Integer 4)
                            LBound
                            ()
                        )
                        (ArrayBound
                            (Var 2 __libasr__created__var__0__elemental_func_call_res)
                            (IntegerConstant 1 (Integer 4))
                            (Integer 4)
                            UBound
                            ()
                        )
                        ())
                        [(Assignment
                            (ArrayItem
                                (Var 2 __libasr__created__var__0__elemental_func_call_res)
                                [(()
                                (Var 2 __1_t)
                                ())]
                                (Real 4)
                                RowMajor
                                ()
                            )
                            (IntrinsicElementalFunction
                                Sin
                                [(ArrayItem
                                    (Var 2 x)
                                    [(()
                                    (Var 2 __1_v)
                                    ())]
                                    (Real 4)
                                    RowMajor
                                    ()
                                )]
                                0
                                (Real 4)
                                ()
                            )
                            ()
                        )
                        (Assignment
                            (Var 2 __1_v)
                            (IntegerBinOp
                                (Var 2 __1_v)
                                Add
                                (IntegerConstant 1 (Integer 4))
                                (Integer 4)
                                ()
                            )
                            ()
                        )]
                        []
                    )
```

and with following diff

```diff
diff --git a/src/libasr/pass/array_op.cpp b/src/libasr/pass/array_op.cpp
index a94f6e297..4ce2f96a1 100644
--- a/src/libasr/pass/array_op.cpp
+++ b/src/libasr/pass/array_op.cpp
@@ -421,6 +421,13 @@ class ReplaceArrayOp: public ASR::BaseExprReplacer<ReplaceArrayOp> {
 
     void replace_ArrayItem(ASR::ArrayItem_t* x) {
         replace_vars_helper(x);
+        // check if any array_index is array
+        for ( size_t i = 0; i < x->n_args; i++ ) {
+            ASR::expr_t* arg = x->m_args[i].m_right;
+            if (ASRUtils::is_array(ASRUtils::expr_type(arg))) {
+                // create a do loop
+            }
+        }
     }
 
     void replace_ComplexConstructor(ASR::ComplexConstructor_t* x) {
@@ -1391,6 +1398,7 @@ class ReplaceArrayOp: public ASR::BaseExprReplacer<ReplaceArrayOp> {
         Vec<ASR::expr_t*> idx_vars, loop_vars, idx_vars_value;
         std::vector<int> loop_var_indices;
         Vec<ASR::stmt_t*> doloop_body;
+        std::cout<<"creating do loop"<<std::endl;
         create_do_loop(loc, common_rank, idx_vars, idx_vars_value,
             loop_vars, loop_var_indices, doloop_body, first_array_operand,
             [=, &operands, &idx_vars, &idx_vars_value, &doloop_body] () {
@@ -1421,6 +1429,7 @@ class ReplaceArrayOp: public ASR::BaseExprReplacer<ReplaceArrayOp> {
     }
 
     void replace_IntrinsicElementalFunction(ASR::IntrinsicElementalFunction_t* x) {
+        std::cout<<"replace_IntrinsicElementalFunction\n";
         replace_intrinsic_function(x);
     }
 
```

You can understand how it is unrolled and how to get it working.

**Comment by Pranavchiku** [comment]
The original code gets transformed to:

```fortran
program main
  implicit none

  integer :: i ! we introduced this `i`

  ! Logical array
  logical, dimension(5) :: x = [.TRUE., .FALSE., .TRUE., .FALSE., .TRUE.]

  ! Integer array with indices
  integer, dimension(3) :: loc = [2, 4, 1]

  ! Access elements using x(loc)
  ! print*, "x(loc) =", x(loc)
  ! transforms to

  do i = lbound(loc,1), ubound(loc,1)
    print *, x(loc(i))
  end do


end program
```

**Comment by kmr-srbh** [comment]
That's exactly the idea, thanks for this @Pranavchiku! I support that we should let @shivimathur implement this. :+1:
