### ISSUE TITLE
Bug : llvm error in initializing array of character in module

### ISSUE THREAD

**Issue by assem2002** [lfortran/lfortran#4514]
**MRE**

```fortran
module  b
    character(100) :: arr2(10) ="abcd"
end module 

program a
end program a
```

```shell
Traceback (most recent call last):
  Binary file "/home/assem/lfortran_test/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/assem/lfortran_test/lfortran/src/bin/lfortran.cpp", line 2481, in ??
    return main_app(argc, argv);
  File "/home/assem/lfortran_test/lfortran/src/bin/lfortran.cpp", line 2442, in main_app(int, char**)
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/assem/lfortran_test/lfortran/src/bin/lfortran.cpp", line 954, in ??
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/assem/lfortran_test/lfortran/src/lfortran/fortran_evaluator.cpp", line 363, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9987, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    if (llvm::verifyModule(*v.module, &err)) {
  Binary file "/home/assem/lfortran_test/lfortran/src/bin/lfortran", in llvm::verifyModule(llvm::Module const&, llvm::raw_ostream*, bool*)
  File "Verifier.cpp", line 0, in (anonymous namespace)::Verifier::verify()
  File "Verifier.cpp", line 0, in (anonymous namespace)::Verifier::visitGlobalValue(llvm::GlobalValue const&)
  File "Verifier.cpp", line 0, in forEachUser(llvm::Value const*, llvm::SmallPtrSet<llvm::Value const*, 32u>&, llvm::function_ref<bool (llvm::Value const*)>) [clone .constprop.0]
  File "Verifier.cpp", line 0, in forEachUser(llvm::Value const*, llvm::SmallPtrSet<llvm::Value const*, 32u>&, llvm::function_ref<bool (llvm::Value const*)>) [clone .constprop.0]
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __GI___sigaction()
Segfault: Signal SIGSEGV (segmentation fault) received
```
The problem is related to creating an array of characters and initialize its value in the same expression.

**Comment by kmr-srbh** [comment]
I think this error occurs because in my implementation of initializing global arrays, I had not handled character arrays. I think handling it should fix this. I am trying to open a PR.
