### ISSUE TITLE
bug: allocating using a subroutine parameter variable leads to an `ASR verify pass error`

### ISSUE THREAD

**Issue by kmr-srbh** [lfortran/lfortran#4529]
### Minimal Reproducible Example

```fortran
MODULE control_module
   implicit none
   integer, allocatable, dimension(:) :: dfmxi

contains
   subroutine control_allocate ( ng )
      integer, intent(in) :: ng
      allocate (dfmxi(ng))
   end subroutine control_allocate

END MODULE control_module


PROGRAM main
   USE control_module
   implicit none

   integer :: ng
   ng = 2
   call control_allocate ( ng )

END PROGRAM main
```

### Output

```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90 --fast
ASR verify pass error: ASR verify: The symbol table was not found in the scope of `symtab`.

ASR verify pass error: Var::m_v `ng` cannot point outside of its symbol table
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main_impl()
  File "./csu/../sysdeps/x86/libc-start.c", line 58, in __libc_start_call_main()
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2481, in main()
    return main_app(argc, argv);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2442, in main_app(int, char**)
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 954, in compile_to_object_file()
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/fortran_evaluator.cpp", line 363, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10010, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/pass_manager.h", line 312, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _with_optimization_passes, pass_options,
LCompilersException: Verify failed in the pass: promote_allocatable_to_nonallocatable
```

**Comment by kmr-srbh** [comment]
### Fortran code after `promote_allocatable_to_nonallocatable` pass

```fortran
! Fortran code after applying the pass: promote_allocatable_to_nonallocatable
module control_module
   implicit none
   integer(4), dimension(ng) :: dfmxi

contains

   subroutine control_allocate(ng)
      integer(4), intent(in) :: ng
   end subroutine control_allocate

end module control_module

program main
   use control_module, only: control_allocate
   use control_module, only: dfmxi
   implicit none
   integer(4) :: ng
   ng = 2
   call control_allocate(ng)
end program main
```

When we look at the transformed ASR and Fortran code after the `promote_allocatable_to_nonallocatable` pass, we notice that the variable `ng`, dimension of `dfmxi`, is not present in the `module` scope and points to the variable `ng` inside the subroutine.

```clojure
(Module
      (SymbolTable
         2
         {
               control_allocate:
                  (Function
                     (SymbolTable
                           3
                           {
                              ng:
                                 (Variable
                                       3
                                       ng
                                       []
                                       In
                                       ()
                                       ()
                                       Default
                                       (Integer 4)
                                       ()
                                       Source
                                       Public
                                       Required
                                       .false.
                                 )
                           })
                     control_allocate
                     (FunctionType
                           [(Integer 4)]
                           ()
                           Source
                           Implementation
                           ()
                           .false.
                           .false.
                           .false.
                           .false.
                           .false.
                           []
                           .false.
                     )
                     []
                     [(Var 3 ng)]
                     []
                     ()
                     Public
                     .false.
                     .false.
                     ()
                  ),
               dfmxi:
                  (Variable
                     2
                     dfmxi
                     [ng]
                     Local
                     ()
                     ()
                     Default
                     (Array
                           (Integer 4)
                           [((IntegerConstant 1 (Integer 4) Decimal)
                           (Var 3 ng))]
                           PointerToDataArray
                     )
                     ()
                     Source
                     Public
                     Required
                     .false.
                  )
         })
      control_module
      []
      .false.
      .false.
   )
```
