### ISSUE TITLE
bug: array assignment inside subroutine leads to an LLVM error

### ISSUE THREAD

**Issue by kmr-srbh** [lfortran/lfortran#4531]
### Minimal Reproducible Example

```fortran
MODULE sweep_module
   IMPLICIT NONE

   LOGICAL, ALLOCATABLE, DIMENSION(:) :: inrdone

CONTAINS

   SUBROUTINE sweep

      ALLOCATE(inrdone(5))
      inrdone = [.true., .false., .true., .false., .true.]

      PRINT *, inrdone

   END SUBROUTINE sweep

END MODULE sweep_module

PROGRAM main
   USE sweep_module, ONLY: sweep
   IMPLICIT NONE

   CALL sweep

END PROGRAM main
```

### Output

```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90 --fast
lfortran: /home/saurabh-kumar/miniforge3/envs/lf/include/llvm/IR/Instructions.h:939: static llvm::GetElementPtrInst* llvm::GetElementPtrInst::Create(llvm::Type*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&, llvm::Instruction*): Assertion `PointeeType == cast<PointerType>(Ptr->getType()->getScalarType())->getElementType()' failed.
Traceback (most recent call last):
  Binary file "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main_impl()
  File "./csu/../sysdeps/x86/libc-start.c", line 58, in __libc_start_call_main()
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2481, in main()
    return main_app(argc, argv);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2442, in main_app(int, char**)
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 954, in compile_to_object_file()
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/fortran_evaluator.cpp", line 363, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10018, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5134, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5110, in visit_asr_t<LCompilers::ASRToLLVMVisitor>()
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5135, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4842, in visit_unit_t<LCompilers::ASRToLLVMVisitor>()
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 985, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*mod);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5137, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4851, in visit_symbol_t<LCompilers::ASRToLLVMVisitor>()
    case symbolType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3114, in LCompilers::ASRToLLVMVisitor::visit_Module(LCompilers::ASR::Module_t const&)
    visit_procedures(x);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4139, in void LCompilers::ASRToLLVMVisitor::visit_procedures<LCompilers::ASR::Module_t>(LCompilers::ASR::Module_t const&)
    visit_Function(*s);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3895, in LCompilers::ASRToLLVMVisitor::visit_Function(LCompilers::ASR::Function_t const&)
    generate_function(x);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4091, in LCompilers::ASRToLLVMVisitor::generate_function(LCompilers::ASR::Function_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5154, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4905, in visit_stmt_t<LCompilers::ASRToLLVMVisitor>()
    case stmtType::WhileLoop: { v.visit_WhileLoop((const WhileLoop_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5915, in LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)
    create_loop(x.m_name, [=]() {
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 348, in void LCompilers::ASRToLLVMVisitor::create_loop<LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::{lambda()#1}, LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::{lambda()#2}>(char*, LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::{lambda()#1}, LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::{lambda()#2})
    loop_body();
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5921, in LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::{lambda()#2}::operator()() const
    this->visit_stmt(*x.m_body[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5154, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4876, in visit_stmt_t<LCompilers::ASRToLLVMVisitor>()
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4863, in LCompilers::ASRToLLVMVisitor::visit_Assignment(LCompilers::ASR::Assignment_t const&)
    this->visit_expr(*x.m_target);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5202, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4991, in visit_expr_t<LCompilers::ASRToLLVMVisitor>()
    case exprType::ArrayItem: { v.visit_ArrayItem((const ArrayItem_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2390, in LCompilers::ASRToLLVMVisitor::visit_ArrayItem(LCompilers::ASR::ArrayItem_t const&)
    tmp = arr_descr->get_single_element(type, array, indices, x.n_args,
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 645, in LCompilers::LLVMArrUtils::SimpleCMODescriptor::get_single_element(llvm::Type*, llvm::Value*, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&, int, bool, bool, llvm::Value**, bool, llvm::Type*, bool)
    tmp = llvm_utils->create_gep2(type, array, idx);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1584, in LCompilers::LLVMUtils::create_gep2(llvm::Type*, llvm::Value*, llvm::Value*)
    return LLVM::CreateGEP2(*builder, t, ds, idx_vec);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/llvm_utils.cpp", line 37, in LCompilers::LLVM::CreateGEP2(llvm::IRBuilder<llvm::ConstantFolder, llvm::IRBuilderDefaultInserter>&, llvm::Type*, llvm::Value*, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&)
    return builder.CreateGEP(t, x, idx);
  File "/home/saurabh-kumar/miniforge3/envs/lf/include/llvm/IR/IRBuilder.h", line 1773, in llvm::IRBuilderBase::CreateGEP(llvm::Type*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&)
    return Insert(GetElementPtrInst::Create(Ty, Ptr, IdxList), Name);
  File "/home/saurabh-kumar/miniforge3/envs/lf/include/llvm/IR/Instructions.h", line 939, in llvm::GetElementPtrInst::Create(llvm::Type*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&, llvm::Instruction*)
    assert(
  File "./assert/./assert/assert.c", line 103, in __assert_fail()
  File "./assert/./assert/assert.c", line 94, in __assert_fail_base()
  File "./stdlib/./stdlib/abort.c", line 79, in __GI_abort()
  File "./signal/../sysdeps/posix/raise.c", line 26, in __GI_raise()
  File "./nptl/./nptl/pthread_kill.c", line 43, in __pthread_kill_implementation()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __GI___sigaction()
Abort: Signal SIGABRT (abort) received

Aborted (core dumped)
```

**Comment by kmr-srbh** [comment]
Turns out that this was a false positive, caused by some changes I made to the compiler while testing SNAP. Closing it.

**Comment by certik** [comment]
Yes, happened to me many times.
