### ISSUE TITLE
Comparison of real arrays of different kind throw compiler error

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#4559]
```fortran
program main
    real(8), parameter :: ar2(3) = anint([123.41_8, 4.23_8, -31.0_8])
    if (any(ar2 /= [123_8, 4_8, -31_8])) error stop
end program
```
```console
$ lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2481, in ??
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2442, in main_app(int, char**)
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 912, in ??
    result = fe.get_asr2(input, lm, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 256, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 278, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 106, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    instantiate_types, instantiate_symbols, entry_functions, entry_function_arguments_mapping, data_structure);
.
.
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 146, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4878, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4835, in ??
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4881, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4468, in ??
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1571, in LCompilers::LFortran::BodyVisitor::visit_Program(LCompilers::LFortran::AST::Program_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 117, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4924, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4612, in ??
    case stmtType::If: { v.visit_If((const If_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3140, in LCompilers::LFortran::BodyVisitor::visit_If(LCompilers::LFortran::AST::If_t const&)
    visit_expr(*x.m_test);
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4976, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_expr(LCompilers::LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4633, in ??
    case exprType::FuncCallOrArray: { v.visit_FuncCallOrArray((const FuncCallOrArray_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 6477, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_FuncCallOrArray(LCompilers::LFortran::AST::FuncCallOrArray_t const&)
    v = intrinsic_as_node(x, is_function);
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5649, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::intrinsic_as_node(LCompilers::LFortran::AST::FuncCallOrArray_t const&, bool&)
    signature_matched = handle_intrinsic_node_args(
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4837, in bool LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::handle_intrinsic_node_args<LCompilers::LFortran::AST::FuncCallOrArray_t>(LCompilers::LFortran::AST::FuncCallOrArray_t const&, LCompilers::Vec<LCompilers::ASR::expr_t*>&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, unsigned long, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
    this->visit_expr(*x.m_args[i].m_end);
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4976, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_expr(LCompilers::LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4632, in ??
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 7626, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_Compare(LCompilers::LFortran::AST::Compare_t const&)
    CommonVisitorMethods::visit_Compare(al, x, left, right, tmp,
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 402, in LCompilers::LFortran::CommonVisitorMethods::visit_Compare(Allocator&, LCompilers::LFortran::AST::Compare_t const&, LCompilers::ASR::expr_t*&, LCompilers::ASR::expr_t*&, LCompilers::ASR::asr_t*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, LCompilers::SymbolTable*, LCompilers::SetChar&, LCompilers::SetChar&, LCompilers::CompilerOptions const&)
    value = evaluate_compiletime_values(al, comptime_values, left, right, asr_op, type, x.base.base.loc);
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 244, in LCompilers::LFortran::CommonVisitorMethods::evaluate_compiletime_values(Allocator&, std::vector<std::pair<LCompilers::ASR::expr_t*, LCompilers::ASR::expr_t*>, std::allocator<std::pair<LCompilers::ASR::expr_t*, LCompilers::ASR::expr_t*> > >&, LCompilers::ASR::expr_t*, LCompilers::ASR::expr_t*, LCompilers::ASR::cmpopType, LCompilers::ASR::ttype_t*, LCompilers::Location)
    args.push_back(al, compare_helper(al, left_val, right_val, asr_op, loc));
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 122, in LCompilers::LFortran::CommonVisitorMethods::compare_helper(Allocator&, LCompilers::ASR::expr_t*, LCompilers::ASR::expr_t*, LCompilers::ASR::cmpopType, LCompilers::Location)
    double right_val = ASR::down_cast<ASR::RealConstant_t>(right_value)->m_r;
AssertFailed: is_a<T>(*f)
$ gfortran a.f90 && ./a.out
```

**Comment by HarshitaKalani** [comment]
```console
% gfortran a.f90 && ./a.out
% lfortran a.f90           
% echo $?                  
0
```
