### ISSUE TITLE
compile time evaluation of `pack` intrinsic fails

### ISSUE THREAD

**Issue by gxyd** [lfortran/lfortran#4614]
### Minimal Reproducible Example

```fortran
program main
    integer, parameter :: x(2) = pack([1, 2, 3], [.true., .false., .true.])
    print *, x
end program main
```

on compilation with LFortran, it produces the below error:
```bash
Traceback (most recent call last):
  File "/Users/gxyd/Downloads/lfortran/src/bin/lfortran.cpp", line 2478
    LCompilers::print_stack_on_segfault();
  File "/Users/gxyd/Downloads/lfortran/src/bin/lfortran.cpp", line 2356
    return emit_asr(arg_file, lfortran_pass_manager,
  File "/Users/gxyd/Downloads/lfortran/src/bin/lfortran.cpp", line 627
    r = fe.get_asr2(input, lm, diagnostics);
  File "/Users/gxyd/Downloads/lfortran/src/lfortran/fortran_evaluator.cpp", line 256
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/gxyd/Downloads/lfortran/src/lfortran/fortran_evaluator.cpp", line 278
    compiler_options.symtab_only, compiler_options);
  File "/Users/gxyd/Downloads/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 107
    if (res.ok) {
  File "/Users/gxyd/Downloads/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3807
    b.is_body_visitor = true;
  File "/Users/gxyd/Downloads/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 146
    visit_ast(*x.m_items[i]);
  File "/Users/gxyd/Downloads/lfortran/src/lfortran/ast.h", line 4878
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/gxyd/Downloads/lfortran/src/lfortran/ast.h", line 4834
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/gxyd/Downloads/lfortran/src/lfortran/ast.h", line 4881
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/gxyd/Downloads/lfortran/src/lfortran/ast.h", line 4467
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/gxyd/Downloads/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1571
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/gxyd/Downloads/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 117
    this->visit_stmt(*m_body[i]);
  File "/Users/gxyd/Downloads/lfortran/src/lfortran/ast.h", line 4924
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/gxyd/Downloads/lfortran/src/lfortran/ast.h", line 4594
    case stmtType::Pragma: { v.visit_Pragma((const Pragma_t &)x); return; }
  File "/Users/gxyd/Downloads/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3090
    visit_expr(*x.m_values[i]);
  File "/Users/gxyd/Downloads/lfortran/src/lfortran/ast.h", line 4976
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/gxyd/Downloads/lfortran/src/lfortran/ast.h", line 4632
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/Users/gxyd/Downloads/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 6477
    bool is_function = true;
  File "/Users/gxyd/Downloads/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5691
    tmp = create_func(al, x.base.base.loc, args, diag);
  File "/Users/gxyd/Downloads/lfortran/src/libasr/pass/intrinsic_array_function_registry.h", line 4082
    value = eval_Pack(al, loc, ret_type, m_args, diag);
  File "/Users/gxyd/Downloads/lfortran/src/libasr/pass/intrinsic_array_function_registry.h", line 3877
    ASR::ttype_t *type_array = ASRUtils::type_get_past_pointer(ASRUtils::type_get_past_allocatable(expr_type(array)));
  File "/Users/gxyd/Downloads/lfortran/src/libasr/asr_utils.h", line 296
    return ASR::expr_type0(f);
  File "/Users/gxyd/Downloads/lfortran/src/libasr/asr.h", line 50295
    LCOMPILERS_ASSERT(f != nullptr);
AssertFailed: f != nullptr
```

### Output of GFortran

```
           1           3
```

I believe there is already an open issue to track intrinsics TODO here: https://github.com/lfortran/lfortran/issues/4593. Probably it belongs there as well?

**Comment by HarshitaKalani** [comment]
It's almost done. Will push the changes.
