### ISSUE TITLE
reshape with shape as reshape function call segfaults

### ISSUE THREAD

**Issue by gxyd** [lfortran/lfortran#4649]
### Minimal Reproducible Example

```fortran
program main
    implicit none

    complex(8) :: my_complex(2, 3)
    my_complex = reshape([(1, 2), (3, 4), (5, 6), (7, 8), (9, 10), (11, 12)], reshape([2, 3], [2]))
    print *, my_complex
end program
```

The above fortran program causes segfault with LFortran.

While the below program, where a variable is assigned for the shape (i.e. `reshape` function call), it works well, i.e.:
```fortran
program main
    implicit none
    complex(8) :: my_complex(2, 3)
    integer(4) :: shape(2) = reshape([2, 3], [2])
    my_complex = reshape([(1, 2), (3, 4), (5, 6), (7, 8), (9, 10), (11, 12)], shape)
    print *, my_complex
end program

```

the below program produces the correct output:
```bash
(1.000000,2.000000) (5.000000,6.000000) (9.000000,10.000000)
(3.000000,4.000000) (7.000000,8.000000) (11.000000,12.000000)
```

**Comment by gxyd** [comment]
This issue seems to have been fixed in the latest *main*:
```console
> lfortran --version
LFortran version: 0.42.0-459-g9b2bcaccb-dirty
Platform: macOS ARM
LLVM: 11.1.0
Default target: arm64-apple-darwin23.6.0

> lfortran test.f90
1.00000000000000000e+00    2.00000000000000000e+00    3.00000000000000000e+00    4.00000000000000000e+00    1.00000000000000000e+00    2.00000000000000000e+00    3.00000000000000000e+00    4.00000000000000000e+00
```

though the output *printed* isn't correct because of some issue with printing (that's a separate issue).

I think we just need to add a test case here, and we should be good to close this issue.

**Comment by dsaw** [comment]
i can take a shot at this one if no one is working on it yet.

**Comment by dsaw** [comment]
i can take this up, if no one has done this yet.

**Comment by gxyd** [comment]
Yes, you can send in a PR.

**Comment by Jaysukh-409** [comment]
With lastest main also above code is giving error.

```
(lf) jaysukh@Jaysukh-Ubuntu:~/Desktop/lfortran$ lfortran --version
LFortran version: 0.43.0-98-ge0a1a30f9
Platform: Linux
LLVM: 11.0.1
Default target: x86_64-unknown-linux-gnu
(lf) jaysukh@Jaysukh-Ubuntu:~/Desktop/lfortran$ lfortran integration_tests/reshape_param_shape.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/jaysukh/Desktop/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/jaysukh/Desktop/lfortran/src/bin/lfortran.cpp", line 2741, in main
    return main_app(argc, argv);
  File "/home/jaysukh/Desktop/lfortran/src/bin/lfortran.cpp", line 2679, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/home/jaysukh/Desktop/lfortran/src/bin/lfortran.cpp", line 1052, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/jaysukh/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 382, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/jaysukh/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10496, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/jaysukh/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 403, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes_with_experimental_simplifier, pass_options, diagnostics);
  File "/home/jaysukh/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 180, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/home/jaysukh/Desktop/lfortran/src/libasr/pass/simplifier.cpp", line 2458, in LCompilers::pass_simplifier(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    c.visit_TranslationUnit(unit);
  File "/home/jaysukh/Desktop/lfortran/src/libasr/../libasr/asr_expr_call_replacer_visitor.h", line 40, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ReplaceExprWithTemporaryVisitor>::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/home/jaysukh/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 319, in LCompilers::ASR::BaseVisitor<LCompilers::ReplaceExprWithTemporaryVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/jaysukh/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 30, in void LCompilers::ASR::visit_symbol_t<LCompilers::ReplaceExprWithTemporaryVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ReplaceExprWithTemporaryVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/jaysukh/Desktop/lfortran/src/libasr/../libasr/asr_expr_call_replacer_visitor.h", line 51, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ReplaceExprWithTemporaryVisitor>::visit_Program(LCompilers::ASR::Program_t const&)
    self().transform_stmts(xx.m_body, xx.n_body);
  File "/home/jaysukh/Desktop/lfortran/src/libasr/pass/simplifier.cpp", line 1846, in LCompilers::ReplaceExprWithTemporaryVisitor::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    transform_stmts_impl
  File "/home/jaysukh/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 336, in LCompilers::ASR::BaseVisitor<LCompilers::ReplaceExprWithTemporaryVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/jaysukh/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 56, in void LCompilers::ASR::visit_stmt_t<LCompilers::ReplaceExprWithTemporaryVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ReplaceExprWithTemporaryVisitor&)
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/home/jaysukh/Desktop/lfortran/src/libasr/pass/simplifier.cpp", line 1900, in LCompilers::ReplaceExprWithTemporaryVisitor::visit_Assignment(LCompilers::ASR::Assignment_t const&)
    call_replacer();
  File "/home/jaysukh/Desktop/lfortran/src/libasr/pass/simplifier.cpp", line 1834, in LCompilers::ReplaceExprWithTemporaryVisitor::call_replacer()
    replacer.replace_expr(*current_expr);
  File "/home/jaysukh/Desktop/lfortran/src/libasr/../libasr/asr_expr_base_replacer_visitor.h", line 2298, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceExprWithTemporary>::replace_expr(LCompilers::ASR::expr_t*)
    self().replace_Cast(down_cast<ASR::Cast_t>(x));
  File "/home/jaysukh/Desktop/lfortran/src/libasr/../libasr/asr_expr_base_replacer_visitor.h", line 1481, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceExprWithTemporary>::replace_Cast(LCompilers::ASR::Cast_t*)
    self().replace_expr(x->m_arg);
  File "/home/jaysukh/Desktop/lfortran/src/libasr/../libasr/asr_expr_base_replacer_visitor.h", line 2246, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceExprWithTemporary>::replace_expr(LCompilers::ASR::expr_t*)
    self().replace_ArrayReshape(down_cast<ASR::ArrayReshape_t>(x));
  File "/home/jaysukh/Desktop/lfortran/src/libasr/pass/simplifier.cpp", line 1691, in LCompilers::ReplaceExprWithTemporary::replace_ArrayReshape(LCompilers::ASR::ArrayReshape_t*)
    replace_current_expr("_array_reshape_")
  File "/home/jaysukh/Desktop/lfortran/src/libasr/pass/simplifier.cpp", line 766, in LCompilers::create_and_allocate_temporary_variable_for_array(LCompilers::ASR::expr_t*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Allocator&, LCompilers::Vec<LCompilers::ASR::stmt_t*>*&, LCompilers::SymbolTable*, std::map<LCompilers::ASR::expr_t*, std::pair<LCompilers::ASR::expr_t*, LCompilers::targetType>, std::less<LCompilers::ASR::expr_t*>, std::allocator<std::pair<LCompilers::ASR::expr_t* const, std::pair<LCompilers::ASR::expr_t*, LCompilers::targetType> > > >&, bool, LCompilers::ASR::expr_t*)
    insert_allocate_stmt_for_array(al, array_var_temporary, allocate_size_reference, current_body);
AssertFailed: target_n_dims == allocate_dims.size()
```

**Comment by Pranavchiku** [comment]
I get the same error with latest main.

**Comment by gxyd** [comment]
Fixed the labels based on the recent comments that the test case doesn't work anymore
