### ISSUE TITLE
Throw error for incompatible ranks in assignment

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#4678]
```fortran
program main
    integer :: x = [1, 2, 3]
end program
```
```console
$ lfortran a.f90
LCOMPILERS_ASSERT failed: /home/harshita/Desktop/lfortran/src/libasr/../libasr/pass/pass_utils.h
function replace_ArrayConstant(), line number 855 at 
ASRUtils::extract_n_dims_from_ttype(result_var_type) == 1
ERROR MESSAGE:
Initialisation using ArrayConstant is supported only for single dimensional arrays, found: 0
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2482, in ??
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2443, in main_app(int, char**)
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 954, in ??
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 363, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10170, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 315, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 169, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/init_expr.cpp", line 221, in LCompilers::pass_replace_init_expr(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    v.visit_TranslationUnit(unit);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 46904, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::InitExprVisitor>::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5137, in LCompilers::ASR::BaseVisitor<LCompilers::InitExprVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4850, in ??
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/init_expr.cpp", line 155, in LCompilers::InitExprVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    visit_SymbolsContainingSymbolTable();
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/init_expr.cpp", line 147, in LCompilers::InitExprVisitor::visit_SymbolsContainingSymbolTable()
    this->visit_symbol(*sym);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5137, in LCompilers::ASR::BaseVisitor<LCompilers::InitExprVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4859, in ??
    case symbolType::Variable: { v.visit_Variable((const Variable_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/init_expr.cpp", line 202, in LCompilers::InitExprVisitor::visit_Variable(LCompilers::ASR::Variable_t const&)
    call_replacer();
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/init_expr.cpp", line 121, in LCompilers::InitExprVisitor::call_replacer()
    replacer.replace_expr(*current_expr);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 46101, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceInitExpr>::replace_expr(LCompilers::ASR::expr_t*)
    self().replace_ArrayConstant(down_cast<ASR::ArrayConstant_t>(x));
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/init_expr.cpp", line 49, in LCompilers::ReplaceInitExpr::replace_ArrayConstant(LCompilers::ASR::ArrayConstant_t*)
    PassUtils::ReplacerUtils::replace_ArrayConstant(x, this,
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/pass/pass_utils.h", line 855, in ??
    LCOMPILERS_ASSERT_MSG(ASRUtils::extract_n_dims_from_ttype(result_var_type) == 1,
  File "./stdlib/abort.c", line 79, in __GI_abort()
  File "./signal/../sysdeps/posix/raise.c", line 26, in __GI_raise()
  File "./nptl/pthread_kill.c", line 43, in __pthread_kill_implementation()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __GI___sigaction()
Abort: Signal SIGABRT (abort) received

Aborted (core dumped)
$ gfortran a.f90 && ./a.out
a.f90:2:16:

    2 |     integer :: x = [1, 2, 3]
      |                1
Error: Incompatible ranks 0 and 1 in assignment at (1)
```

**Comment by shubhneetgrover** [comment]
Instead of LCOMPILERS_ASSERT_MSG, a throw LCompilersException needs to be used ?

**Comment by certik** [comment]
Both `LCOMPILERS_ASSERT_MSG` and `LCompilersException` are for internal compiler errors (ICE). Rather, a diagnostic message must be created and the we need to exit. This error message must be reported already in AST->ASR phase as all other messages. See other semantic error messages in AST->ASR for an example how to do that.

**Comment by Pranavchiku** [comment]
```diff
diff --git a/src/libasr/pass/implied_do_loops.cpp b/src/libasr/pass/implied_do_loops.cpp
index a5fe72313..c9faa3ecf 100644
--- a/src/libasr/pass/implied_do_loops.cpp
+++ b/src/libasr/pass/implied_do_loops.cpp
@@ -6,6 +6,7 @@
 #include <libasr/pass/replace_implied_do_loops.h>
 #include <libasr/pass/pass_utils.h>
 #include <libasr/pass/intrinsic_function_registry.h>
+#include <libasr/semantic_exception.h>
 
 #include <vector>
 #include <utility>
@@ -376,7 +377,7 @@ class ReplaceArrayConstant: public ASR::BaseExprReplacer<ReplaceArrayConstant> {
         }
         LCOMPILERS_ASSERT(result_var != nullptr);
         Vec<ASR::stmt_t*>* result_vec = &pass_result;
-        PassUtils::ReplacerUtils::replace_ArrayConstant(x, this,
+        PassUtils::ReplacerUtils::replace_ArrayConstant<LCompilers::SemanticError>(x, this,
             remove_original_statement, result_vec);
         result_var = result_var_copy;
     }
diff --git a/src/libasr/pass/init_expr.cpp b/src/libasr/pass/init_expr.cpp
index 83e62b527..eb4c97196 100644
--- a/src/libasr/pass/init_expr.cpp
+++ b/src/libasr/pass/init_expr.cpp
@@ -5,6 +5,7 @@
 #include <libasr/asr_verify.h>
 #include <libasr/pass/replace_init_expr.h>
 #include <libasr/pass/pass_utils.h>
+#include <libasr/semantic_exception.h>
 
 #include <vector>
 #include <utility>
@@ -46,7 +47,7 @@ class ReplaceInitExpr: public ASR::BaseExprReplacer<ReplaceInitExpr> {
         if( casted_type != nullptr ) {
             casted_type = ASRUtils::type_get_past_array(casted_type);
         }
-        PassUtils::ReplacerUtils::replace_ArrayConstant(x, this,
+        PassUtils::ReplacerUtils::replace_ArrayConstant<LCompilers::SemanticError>(x, this,
             remove_original_statement, result_vec,
             perform_cast, cast_kind, casted_type);
         *current_expr = nullptr;
diff --git a/src/libasr/pass/pass_utils.h b/src/libasr/pass/pass_utils.h
index 1d65992f3..755315d5f 100644
--- a/src/libasr/pass/pass_utils.h
+++ b/src/libasr/pass/pass_utils.h
@@ -837,7 +837,7 @@ namespace LCompilers {
             bool perform_cast=false, ASR::cast_kindType cast_kind=ASR::cast_kindType::IntegerToInteger,
             ASR::ttype_t* casted_type=nullptr);
 
-        template <typename T>
+        template <typename SemanticError, typename T>
         static inline void replace_ArrayConstant(ASR::ArrayConstant_t* x, T* replacer,
             bool& remove_original_statement, Vec<ASR::stmt_t*>* result_vec,
             bool perform_cast=false,
@@ -852,10 +852,21 @@ namespace LCompilers {
             const Location& loc = x->base.base.loc;
             if( ASR::is_a<ASR::Var_t>(*replacer->result_var) ) {
                 [[maybe_unused]] ASR::ttype_t* result_var_type = ASRUtils::expr_type(replacer->result_var);
-                LCOMPILERS_ASSERT_MSG(ASRUtils::extract_n_dims_from_ttype(result_var_type) == 1,
-                                    "Initialisation using ArrayConstant is "
-                                    "supported only for single dimensional arrays, found: " +
-                                    std::to_string(ASRUtils::extract_n_dims_from_ttype(result_var_type)))
+                std::cout<<"Here 1"<<std::endl;
+                if ( ASRUtils::extract_n_dims_from_ttype(result_var_type) != 1 ) {
+                    std::cout<<"Here 2"<<std::endl;
+                    throw SemanticError("Initialisation using ArrayConstant is supported only for single dimensional arrays, found:" +
+                        std::to_string(ASRUtils::extract_n_dims_from_ttype(result_var_type)),
+                        x->base.base.loc);
+                    std::cout<<"here 4"<<std::endl;
+                    return;
+                } else {
+                    std::cout<<"Here 3"<<std::endl;
+                }
+                // LCOMPILERS_ASSERT_MSG(ASRUtils::extract_n_dims_from_ttype(result_var_type) == 1,
+                //                     "Initialisation using ArrayConstant is "
+                //                     "supported only for single dimensional arrays, found: " +
+                //                     std::to_string(ASRUtils::extract_n_dims_from_ttype(result_var_type)))
                 Vec<ASR::expr_t*> idx_vars;
                 PassUtils::create_idx_vars(idx_vars, 1, loc, replacer->al, replacer->current_scope);
                 ASR::expr_t* idx_var = idx_vars[0];
```

**Comment by NishantBansal2003** [comment]
Is this issue already fixed? as I am getting this output -
```error
$ ./src/bin/lfortran incompatible_rank_assignment.f90 
semantic error: Incompatible ranks `0` and `1` in assignment
 --> incompatible_rank_assignment.f90:2:5
  |
2 |     integer :: x = [1, 2, 3]
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
for this test-
```fortran
program main
    integer :: x = [1, 2, 3]
end program
```

**Comment by HarshitaKalani** [comment]
Yes. Thanks for bringing it into notice.
Closing as completed with https://github.com/lfortran/lfortran/pull/4775
