### ISSUE TITLE
Compile MGLET

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#4702]
This seems to be a modern Fortran code:

https://github.com/kmturbulenz/mglet-base

**Comment by opixdown** [comment]
Here are the steps for building with lfortran:
```
git clone https://github.com/kmturbulenz/mglet-base.git
cd mglet-base
git remote add opixdown https://github.com/opixdown/mglet-base.git
git fetch opixdown
git checkout -b lf1 opixdown/lf1
./build.sh 
```

Current Status
```
Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
[203/255] Building Fortran object src/ib/CMakeFiles/ib.dir/stencils_mod.F90.o
FAILED: src/ib/CMakeFiles/ib.dir/stencils_mod.F90.o modules/stencils_mod.mod 
/tmp/mglet-lfortran-wrappers/lfortran -I/Users/opixdown/lfortran/mglet-base/src/ib -I/opt/homebrew/Cellar/open-mpi/5.0.9/include -I/opt/homebrew/Cellar/open-mpi/5.0.9/lib -I/opt/homebrew/opt/hdf5-mpi/include -O3 -Jmodules -fPIC -g -ffree-line-length-none -fpreprocessed -c src/ib/CMakeFiles/ib.dir/stencils_mod.F90-pp.f90 -o src/ib/CMakeFiles/ib.dir/stencils_mod.F90.o
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/opixdown/lfortran/src/bin/lfortran.cpp", line 2809
    LCompilers::print_stack_on_segfault();
  File "/Users/opixdown/lfortran/src/bin/lfortran.cpp", line 2678
    result = compile_src_to_object_file(opts.arg_file, outfile, compiler_options.time_report, false,
  File "/Users/opixdown/lfortran/src/bin/lfortran.cpp", line 1193
    t2 = std::chrono::high_resolution_clock::now();
     .
     .
     .
  File "/Users/opixdown/lfortran/src/libasr/asr_utils.h", line 3753
    LCOMPILERS_ASSERT(args.size() + offset == (func->n_args));
AssertFailed: args.size() + offset == (func->n_args)
[208/255] Building Fortran object src/ib/CMakeFiles/ib.dir/cutcorner_mod.F90.o
```
