### ISSUE TITLE
Compile numerical-methods-fortran

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#4703]
This code seems relatively simple and small:

https://github.com/planelles20/numerical-methods-fortran

**Comment by Pranavchiku** [comment]
With this https://github.com/lfortran/lfortran/pull/5244 and https://github.com/Pranavchiku/numerical-methods-fortran/commits/lf1/, we compile it fully, 1 workaround, 2 commented tests ( which will be easy to fix )

**Comment by Jaysukh-409** [comment]
By following above instruction, I am getting this error.

```console
(lf) jaysukh@Jaysukh-Ubuntu:~/Desktop/numerical-methods-fortran$ FC=lfortran make
lfortran -c ./modules/module_linear_equations.f90
lfortran -c ./modules/module_no_linear_equations.f90
lfortran -c ./modules/module_edo.f90
lfortran -c ./modules/module_integrate.f90
lfortran -c ./modules/module_probability_distributions.f90
style suggestion: Use '<=' instead of '.le.'
  --> ./modules/module_probability_distributions.f90:46:22
   |
46 |             if (x**2 .le. -4.0*log(u1)) then
   |                      ^^^^ help: write this as '<='


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran -c ./modules/module_sdo.f90
lfortran -c ./modules/dislin.f90
lfortran -c ./functions/chemical_reaction_function.f90
lfortran -c ./functions/dynamical_systems_function.f90
lfortran -c ./functions/lotka_volterra_function.f90
lfortran -c ./functions/one_dimension_function.f90
lfortran -c ./functions/whatever_function.f90
lfortran -c ./functions/stochastic_dynamical_systems_function.f90
lfortran -c ./test/linear_sys.f90
semantic error: reshape accepts only 2 arguments, got 2 arguments instead.
  --> ./test/linear_sys.f90:17:5
   |
17 | A = reshape([2,-2,1, 1,3,-2, 3,-1,-1],[3,3], order = [2,1])
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
make: *** [Makefile:92: pruebas] Error 1
```

**Comment by Pranavchiku** [comment]
This is weird error. Try running after a clean build on latest main.

**Comment by Jaysukh-409** [comment]
Current Status:
- [ ]  ode.f90 fails due to precision issue (gfortran return 30.3195057 and lfortran return 30.3195095)
- [ ]  linear_sys.f90 fails due to not implemented the order and pad for reshape function (#6157)

**Comment by Pranavchiku** [comment]
@Jaysukh-409 let's test uptil 4 decimal places i.e. `if ( abs( xx - 30.3195057 ) > 1e-4 ) error stop` and set it at CI. Let me know if you need any help.

@HarshilShah1804 as per what was discussed I assume you are working on reshape implementation, feel free to reach out. 

Let's push this will be a good win.

**Comment by Pranavchiku** [comment]
Next step is to use: https://github.com/Pranavchiku/numerical-methods-fortran/tree/lf6 and get it compiled. In this branch we just remove calls to `pgplot` library and test values instead. It works with GFortran whereas we are yet to compile it with LFortran:


```console
% FC=lfortran make
lfortran -c ./modules/module_linear_equations.f90
lfortran -c ./modules/module_no_linear_equations.f90
lfortran -c ./modules/module_edo.f90
lfortran -c ./modules/module_integrate.f90
lfortran -c ./modules/module_probability_distributions.f90
style suggestion: Use '<=' instead of '.le.'
  --> ./modules/module_probability_distributions.f90:46:22
   |
46 |             if (x**2 .le. -4.0*log(u1)) then
   |                      ^^^^ help: write this as '<='


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran -c ./modules/module_sdo.f90
lfortran -c ./modules/dislin.f90
lfortran -c ./functions/chemical_reaction_function.f90
lfortran -c ./functions/dynamical_systems_function.f90
lfortran -c ./functions/lotka_volterra_function.f90
lfortran -c ./functions/one_dimension_function.f90
lfortran -c ./functions/whatever_function.f90
lfortran -c ./functions/stochastic_dynamical_systems_function.f90
lfortran -c ./test/linear_sys.f90 -I/usr/local/dislin/gf -ldislin
lfortran -c ./test/ode.f90 -I/usr/local/dislin/gf -ldislin
lfortran -c ./test/fix_point.f90 -I/usr/local/dislin/gf -ldislin
lfortran -c ./test/integrate_one_dimension.f90 -I/usr/local/dislin/gf -ldislin
lfortran -c ./test/newton_test.f90 -I/usr/local/dislin/gf -ldislin
lfortran -c ./test/sde.f90 -I/usr/local/dislin/gf -ldislin
lfortran -c ./test/probability_distribution.f90 -I/usr/local/dislin/gf -ldislin
lfortran -c ./plot/plot_bogdanov_takens_bifurcation.f90 -I/usr/local/dislin/gf -ldislin
style suggestion: Use '/=' instead of '.ne.'
  --> ./plot/plot_bogdanov_takens_bifurcation.f90:27:8
   |
27 | if (IER.NE.1) stop
   |        ^^^^ help: write this as '/='


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
ASR verify pass error: The symbol table was not found in the scope of `symtab`.

ASR verify pass error: Var::m_v `f_real____1` cannot point outside of its symbol table
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2766
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2662
    return compile_src_to_object_file(arg_file, outfile, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 1051
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 382
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10692
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 297
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 189
    throw LCompilersException("Verify failed in the pass: "
LCompilersException: Verify failed in the pass: pass_array_by_data
make: *** [plots] Error 1
```

**Comment by jinangshah21** [comment]
With #6481 

```console
(base) jinang_shah@JNSLAP:~/Desktop/numerical-methods-fortran$ FC=lfortran make
lfortran -c ./modules/module_linear_equations.f90
lfortran -c ./modules/module_no_linear_equations.f90
lfortran -c ./modules/module_edo.f90
lfortran -c ./modules/module_integrate.f90
lfortran -c ./modules/module_probability_distributions.f90
style suggestion: Use '<=' instead of '.le.'
  --> ./modules/module_probability_distributions.f90:46:22
   |
46 |             if (x**2 .le. -4.0*log(u1)) then
   |                      ^^^^ help: write this as '<='


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran -c ./modules/module_sdo.f90
lfortran -c ./modules/dislin.f90
lfortran -c ./functions/chemical_reaction_function.f90
lfortran -c ./functions/dynamical_systems_function.f90
lfortran -c ./functions/lotka_volterra_function.f90
lfortran -c ./functions/one_dimension_function.f90
lfortran -c ./functions/whatever_function.f90
lfortran -c ./functions/stochastic_dynamical_systems_function.f90
lfortran -c ./test/linear_sys.f90 -I/usr/local/dislin/gf -ldislin
lfortran -c ./test/ode.f90 -I/usr/local/dislin/gf -ldislin
lfortran -c ./test/fix_point.f90 -I/usr/local/dislin/gf -ldislin
lfortran -c ./test/integrate_one_dimension.f90 -I/usr/local/dislin/gf -ldislin
lfortran -c ./test/newton_test.f90 -I/usr/local/dislin/gf -ldislin
lfortran -c ./test/sde.f90 -I/usr/local/dislin/gf -ldislin
lfortran -c ./test/probability_distribution.f90 -I/usr/local/dislin/gf -ldislin
lfortran -c ./plot/plot_bogdanov_takens_bifurcation.f90 -I/usr/local/dislin/gf -ldislin
style suggestion: Use '/=' instead of '.ne.'
  --> ./plot/plot_bogdanov_takens_bifurcation.f90:27:8
   |
27 | if (IER.NE.1) stop
   |        ^^^^ help: write this as '/='


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran -c ./plot/plot_bruinsma.f90 -I/usr/local/dislin/gf -ldislin
style suggestion: Use '/=' instead of '.ne.'
  --> ./plot/plot_bruinsma.f90:27:8
   |
27 | if (IER.NE.1) stop
   |        ^^^^ help: write this as '/='


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran -c ./plot/plot_lorenz_attractor.f90 -I/usr/local/dislin/gf -ldislin
lfortran -c ./plot/plot_lotka_volterra.f90 -I/usr/local/dislin/gf -ldislin
style suggestion: Use '/=' instead of '.ne.'
  --> ./plot/plot_lotka_volterra.f90:24:8
   |
24 | if (IER.NE.1) stop
   |        ^^^^ help: write this as '/='


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran -c ./plot/plot_lotka_volterra2.f90 -I/usr/local/dislin/gf -ldislin
style suggestion: Use '/=' instead of '.ne.'
  --> ./plot/plot_lotka_volterra2.f90:24:8
   |
24 | if (IER.NE.1) stop
   |        ^^^^ help: write this as '/='


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran -c ./plot/plot_ode_fun1.f90 -I/usr/local/dislin/gf -ldislin
style suggestion: Use '/=' instead of '.ne.'
  --> ./plot/plot_ode_fun1.f90:22:8
   |
22 | if (IER.NE.1) stop
   |        ^^^^ help: write this as '/='


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran -c ./plot/plot_pendulum.f90 -I/usr/local/dislin/gf -ldislin
style suggestion: Use '/=' instead of '.ne.'
  --> ./plot/plot_pendulum.f90:26:8
   |
26 | if (IER.NE.1) stop
   |        ^^^^ help: write this as '/='


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran -c ./plot/plot_transesterification_isoterm.f90 -I/usr/local/dislin/gf -ldislin
style suggestion: Use '/=' instead of '.ne.'
  --> ./plot/plot_transesterification_isoterm.f90:25:8
   |
25 | if (IER.NE.1) stop
   |        ^^^^ help: write this as '/='


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran -o test_newton.exe newton_test.o whatever_function.o module_linear_equations.o module_no_linear_equations.o
lfortran -o test_linear.exe linear_sys.o whatever_function.o module_linear_equations.o
lfortran -o test_fix_point.exe fix_point.o whatever_function.o module_no_linear_equations.o module_linear_equations.o
lfortran -o test_ode.exe ode.o whatever_function.o module_edo.o
lfortran -o test_integrate_one.exe integrate_one_dimension.o one_dimension_function.o module_integrate.o
lfortran -o test_sde.exe sde.o module_probability_distributions.o stochastic_dynamical_systems_function.o module_sdo.o
lfortran -o test_probability_distribution.exe probability_distribution.o module_probability_distributions.o
lfortran -o plot_fun1.exe plot_ode_fun1.o whatever_function.o module_edo.o
lfortran -o plot_lotka_volterra1.exe plot_lotka_volterra.o lotka_volterra_function.o module_edo.o
lfortran -o plot_lotka_volterra2.exe plot_lotka_volterra2.o lotka_volterra_function.o module_edo.o
lfortran -o plot_transes_iso.exe plot_transesterification_isoterm.o chemical_reaction_function.o module_edo.o
lfortran -o plot_bogdanov_takens.exe plot_bogdanov_takens_bifurcation.o dynamical_systems_function.o module_edo.o
lfortran -o plot_pendulum.exe plot_pendulum.o dynamical_systems_function.o module_edo.o
lfortran -o plot_lorenz.exe plot_lorenz_attractor.o dynamical_systems_function.o module_edo.o
lfortran -o plot_bruinsma.exe plot_bruinsma.o module_probability_distributions.o stochastic_dynamical_systems_function.o module_sdo.o
rm *.o *.mod
```

It compiles well without error.

**Comment by Pranavchiku** [comment]
Perfect, @jinangshah21 let’s try to execute the binary and check if it works. I have already added error stop conditions in plot_* files.

**Comment by jinangshah21** [comment]
3/9 plot_* binary executes without error stop.
Also for `newton_test` and `fix_point_test` it outputs : 
```console
(base) jinang_shah@JNSLAP:~/Desktop/numerical-methods-fortran$ ./test_fix_point.exe
Initial vector:
2.00000000e+00    -1.00000000e+00    2.00000000e+01
The method does not converge
```

**Comment by Pranavchiku** [comment]
With the following diff we get `plot_lorenz` working.

```diff
diff --git a/modules/module_edo.f90 b/modules/module_edo.f90
index c4eface..94ab9f5 100644
--- a/modules/module_edo.f90
+++ b/modules/module_edo.f90
@@ -197,22 +197,37 @@ contains
         step = (b-a)/(N-1)
 
         AB5(:,1) = y0
+        AB5(:,0) = 0.0
```

The reason it is valid is because on runtime we access `AB5(:,0)` without initialising it.

**Comment by Jaysukh-409** [comment]
With the above diff also It is not working for me.
```console
$ ./plot_lorenz.exe 
2.23949953e+05
STOP
```

**Comment by Pranavchiku** [comment]
Yes, GFortran diverges again on Linux and Mac

**Comment by jinangshah21** [comment]
Sorry, my bad. They are same. Update : 5/8 binary works without error stop.

**Comment by Pranavchiku** [comment]
There is a stop at the end.

**Comment by jinangshah21** [comment]
why GFortran don't give stop?

**Comment by Pranavchiku** [comment]
It does not print anything. Only prints when 

```console
% cat a.f90 
program main
        stop "only prints when written"
end program
% gfortran a.f90 && ./a.out
STOP only prints when written
```

**Comment by Pranavchiku** [comment]
Divergence of `plot_pendulum`

```fortran
program plot_pendulum
integer :: Mx = 3
print *, 1.0/Mx-3*3.1
end program
```

```console
% lfortran a.f90
-8.96666718e+00
% gfortran a.f90 && ./a.out
  -8.96666622    
```
