### ISSUE TITLE
Code to compile: fman

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#4711]
https://fortran-lang.discourse.group/t/oddly-slow-compilation-of-character-data-with-ifx/8465

Code: https://github.com/lockstockandbarrel/mars/blob/55c2d6f7ae618003f1ad4c389dace74881fa0c19/bootstrap/fman.f90

**Comment by gxyd** [comment]
Update on *fman* compilation:

we're able to see the AST by doing `lfortran mars/bootstrap/fman.f90 --no-prescan --show-ast`, and now we use `lf1` branch here: https://github.com/gxyd/mars/tree/lf1, which currently only has the below workarounds:
* https://github.com/lockstockandbarrel/mars/commit/4d103173d2a5a45820aa890cbba14c627c14050e: which is a workaround for *namelist*

**Comment by gxyd** [comment]
Current error that I get for it's compilation:
```console
> lfortran -c bootstrap/fman.f90 --no-prescan --show-asr
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2726
    LCompilers::print_stack_on_segfault();
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2551
    return emit_asr(arg_file, lfortran_pass_manager,
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 655
    r = fe.get_asr2(input, lm, diagnostics);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 275
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics, lm);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 297
    compiler_options.symtab_only, compiler_options, lm);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 104
    if (res.ok) {
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 4648
    b.is_body_visitor = true;
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 156
    visit_ast(*x.m_items[i]);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4943
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4898
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4946
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4521
    case modType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1919
    visit_SubmoduleModuleCommon(x);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1895
    visit_program_unit(*x.m_contains[i]);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4951
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4533
    case program_unitType::Procedure: { v.visit_Procedure((const Procedure_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2476
    visit_program_unit(*x.m_contains[i]);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4951
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4532
    case program_unitType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2387
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 118
    this->visit_stmt(*m_body[i]);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4991
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4675
    case stmtType::ForAll: { v.visit_ForAll((const ForAll_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3825
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 118
    this->visit_stmt(*m_body[i]);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4991
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4675
    case stmtType::ForAll: { v.visit_ForAll((const ForAll_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3825
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 118
    this->visit_stmt(*m_body[i]);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4991
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4633
    case stmtType::Assign: { v.visit_Assign((const Assign_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2836
    ASR::expr_t *target = ASRUtils::EXPR(tmp);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 5043
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4692
    case exprType::DefBinOp: { v.visit_DefBinOp((const DefBinOp_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 8668
    LCOMPILERS_ASSERT(ASRUtils::extract_n_dims_from_ttype(right_type_) == 0);
AssertFailed: ASRUtils::extract_n_dims_from_ttype(right_type_) == 0
```

We'll need to extract MRE for this from *fman* repository.

**Comment by gxyd** [comment]
I've extracted the MRE for the above failure and reported an issue here: https://github.com/lfortran/lfortran/issues/5845

**Comment by gxyd** [comment]
After the latest fix, the new MRE has been extracted here: https://github.com/lfortran/lfortran/issues/5857, one can try to get that error on `lf2` branch here: https://github.com/gxyd/mars/tree/lf2
