### ISSUE TITLE
Compile neural-fortran

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#4748]
https://github.com/modern-fortran/neural-fortran

Issues:
* [ ] https://github.com/lfortran/lfortran/issues/4745

**Comment by gxyd** [comment]
With the latest main, this repository fails with an error with MRE described in https://github.com/lfortran/lfortran/issues/4759

**Comment by Pranavchiku** [comment]
```fortran
module nf_activation
    type :: softmax
    contains
      procedure :: eval_1d
    end type softmax
  
  contains
  
    pure function eval_1d(self, x) result(res)
      class(softmax), intent(in) :: self
      real, intent(in) :: x(:)
      real :: res(size(x))
    end function eval_1d
  
    pure function eval_1d_prime(self, x) result(res)
      class(softmax), intent(in) :: self
      real, intent(in) :: x(:)
      real :: res(size(x))
      res = self%eval_1d(x)
    end function eval_1d_prime
  
end module nf_activation
  
program main
end program main

```

With https://github.com/lfortran/lfortran/pull/4828 it gives:

```console
(lf) pranavchiku@pranavchikus-MacBook-Air:~/repos/lfortran(gh4759) % lfortran a.f90 --show-llvm
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2624, in main
    return main_app(argc, argv);
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2466, in main_app(int, char**)
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 928, in (anonymous namespace)::emit_llvm(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::PassManager&, LCompilers::CompilerOptions&)
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 298, in LCompilers::FortranEvaluator::get_llvm(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&)
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 319, in LCompilers::FortranEvaluator::get_llvm2(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&)
    Result<std::unique_ptr<LLVMModule>> res = get_llvm3(*asr.result, pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 364, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
    = asr_to_llvm(asr, diagnostics,
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10112, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5158, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5134, in void LCompilers::ASR::visit_asr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::asr_t const&, LCompilers::ASRToLLVMVisitor&)
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5159, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 4865, in void LCompilers::ASR::visit_unit_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::unit_t const&, LCompilers::ASRToLLVMVisitor&)
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 940, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*mod);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5161, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 4874, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToLLVMVisitor&)
    case symbolType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3092, in LCompilers::ASRToLLVMVisitor::visit_Module(LCompilers::ASR::Module_t const&)
    visit_procedures(x);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4145, in void LCompilers::ASRToLLVMVisitor::visit_procedures<LCompilers::ASR::Module_t>(LCompilers::ASR::Module_t const&)
    visit_Function(*s);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3901, in LCompilers::ASRToLLVMVisitor::visit_Function(LCompilers::ASR::Function_t const&)
    generate_function(x);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4097, in LCompilers::ASRToLLVMVisitor::generate_function(LCompilers::ASR::Function_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5178, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 4899, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4977, in LCompilers::ASRToLLVMVisitor::visit_Assignment(LCompilers::ASR::Assignment_t const&)
    this->visit_expr_wrapper(m_value, true);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5387, in LCompilers::ASRToLLVMVisitor::visit_expr_wrapper(LCompilers::ASR::expr_t*, bool)
    this->visit_expr(*x);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5226, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 4953, in void LCompilers::ASR::visit_expr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ASRToLLVMVisitor&)
    case exprType::FunctionCall: { v.visit_FunctionCall((const FunctionCall_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9694, in LCompilers::ASRToLLVMVisitor::visit_FunctionCall(LCompilers::ASR::FunctionCall_t const&)
    ASR::ttype_t *return_var_type0 = EXPR2VAR(s->m_return_var)->m_type;
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr_utils.h", line 285, in LCompilers::ASRUtils::EXPR2VAR(LCompilers::ASR::expr_t const*)
    ASR::down_cast<ASR::Var_t>(f)->m_v));
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 40, in LCompilers::ASR::Var_t* LCompilers::ASR::down_cast<LCompilers::ASR::Var_t, LCompilers::ASR::expr_t>(LCompilers::ASR::expr_t const*)
    LCOMPILERS_ASSERT(f != nullptr);
AssertFailed: f != nullptr

```

**Comment by HarshilShah1804** [comment]
```console
git clone https://www.github.com/HarshilShah1804/neural-fortran.git
cd neural-fortran
git checkout -t origin/lf1
cmake -DCMAKE_Fortran_COMPILER=lfortran .
cmake --build .
```

With this #6579 and https://github.com/HarshilShah1804/neural-fortran/commit/1723aa4c73c3e2ba91c4b273443b6085808fd1d4 the package currently compiles up to 24 % with some warnings of for the `open` statement because of `iostat`, `iomsg`, `recl`, `action`, `access` not supported yet in lfortran.

```console
(base) harshil-shah@harshil-shah-HP-Pavilion-Laptop-15-eg2xxx:~/neural-fortran$ cmake  --build .
[  1%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/nf_activation.f90.o
[  2%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/nf_datasets_mnist.f90.o
[  3%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/nf_base_layer.f90.o
[  4%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/nf_optimizers.f90.o
[  6%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/nf_layer.f90.o
[  7%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/nf_layer_constructors.f90.o
[  8%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/nf_metrics.f90.o
[  9%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/nf_loss.f90.o
[ 11%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/nf_network.f90.o
[ 12%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf.f90.o
[ 13%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/io/nf_io_binary.f90.o
[ 14%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/io/nf_io_binary_submodule.f90.o
warning: Argument `access` isn't supported yet
  --> /home/harshil-shah/neural-fortran/src/nf/io/nf_io_binary_submodule.f90:17:5 - 18:74
   |
17 |        open(newunit=fileunit, file=filename, access='direct', action='read', &
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
18 |          recl=dtype * nrec, status='old', iostat=io_status, iomsg=io_message)
   | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now

warning: Argument `action` isn't supported yet
  --> /home/harshil-shah/neural-fortran/src/nf/io/nf_io_binary_submodule.f90:17:5 - 18:74
   |
17 |        open(newunit=fileunit, file=filename, access='direct', action='read', &
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
18 |          recl=dtype * nrec, status='old', iostat=io_status, iomsg=io_message)
   | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now

warning: Argument `recl` isn't supported yet
  --> /home/harshil-shah/neural-fortran/src/nf/io/nf_io_binary_submodule.f90:17:5 - 18:74
   |
17 |        open(newunit=fileunit, file=filename, access='direct', action='read', &
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
18 |          recl=dtype * nrec, status='old', iostat=io_status, iomsg=io_message)
   | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now

warning: Argument `iostat` isn't supported yet
  --> /home/harshil-shah/neural-fortran/src/nf/io/nf_io_binary_submodule.f90:17:5 - 18:74
   |
17 |        open(newunit=fileunit, file=filename, access='direct', action='read', &
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
18 |          recl=dtype * nrec, status='old', iostat=io_status, iomsg=io_message)
   | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now

warning: Argument `iomsg` isn't supported yet
  --> /home/harshil-shah/neural-fortran/src/nf/io/nf_io_binary_submodule.f90:17:5 - 18:74
   |
17 |        open(newunit=fileunit, file=filename, access='direct', action='read', &
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
18 |          recl=dtype * nrec, status='old', iostat=io_status, iomsg=io_message)
   | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now

warning: Argument `access` isn't supported yet
  --> /home/harshil-shah/neural-fortran/src/nf/io/nf_io_binary_submodule.f90:33:5 - 34:75
   |
33 |        open(newunit=fileunit, file=filename, access='direct', action='read', &
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
34 |          recl=dtype * dsize, status='old', iostat=io_status, iomsg=io_message)
   | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now

warning: Argument `action` isn't supported yet
  --> /home/harshil-shah/neural-fortran/src/nf/io/nf_io_binary_submodule.f90:33:5 - 34:75
   |
33 |        open(newunit=fileunit, file=filename, access='direct', action='read', &
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
34 |          recl=dtype * dsize, status='old', iostat=io_status, iomsg=io_message)
   | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now

warning: Argument `recl` isn't supported yet
  --> /home/harshil-shah/neural-fortran/src/nf/io/nf_io_binary_submodule.f90:33:5 - 34:75
   |
33 |        open(newunit=fileunit, file=filename, access='direct', action='read', &
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
34 |          recl=dtype * dsize, status='old', iostat=io_status, iomsg=io_message)
   | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now

warning: Argument `iostat` isn't supported yet
  --> /home/harshil-shah/neural-fortran/src/nf/io/nf_io_binary_submodule.f90:33:5 - 34:75
   |
33 |        open(newunit=fileunit, file=filename, access='direct', action='read', &
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
34 |          recl=dtype * dsize, status='old', iostat=io_status, iomsg=io_message)
   | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now

warning: Argument `iomsg` isn't supported yet
  --> /home/harshil-shah/neural-fortran/src/nf/io/nf_io_binary_submodule.f90:33:5 - 34:75
   |
33 |        open(newunit=fileunit, file=filename, access='direct', action='read', &
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
34 |          recl=dtype * dsize, status='old', iostat=io_status, iomsg=io_message)
   | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
[ 16%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/nf_conv2d_layer.f90.o
[ 17%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/nf_random.f90.o
[ 18%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/nf_conv2d_layer_submodule.f90.o
[ 19%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/nf_datasets.f90.o
[ 20%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/nf_datasets_mnist_submodule.f90.o
[ 22%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/nf_datasets_submodule.f90.o
[ 23%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/nf_dense_layer.f90.o
[ 24%] Building Fortran object CMakeFiles/neural-fortran.dir/src/nf/nf_dense_layer_submodule.f90.o
style suggestion: Use 'end do' instead of 'enddo'
  --> /home/harshil-shah/neural-fortran/src/nf/nf_dense_layer_submodule.f90:36:5
   |
36 |     enddo
   |     ^^^^^ help: write this as 'end do'

warning: #ifdef ignored
   --> /home/harshil-shah/neural-fortran/src/nf/nf_dense_layer_submodule.f90:131:1
    |
131 | #ifdef PARALLEL
    | ^^^^^^^^^^^^^^^^ help: use the '--cpp' command line option to preprocess it

warning: #endif ignored
   --> /home/harshil-shah/neural-fortran/src/nf/nf_dense_layer_submodule.f90:133:1
    |
133 | #endif
    | ^^^^^^^ help: use the '--cpp' command line option to preprocess it

semantic error: Coarrays are not supported yet
   --> /home/harshil-shah/neural-fortran/src/nf/nf_dense_layer_submodule.f90:132:5
    |
132 |     call co_broadcast(self % weights, 1)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
gmake[2]: *** [CMakeFiles/neural-fortran.dir/build.make:205: CMakeFiles/neural-fortran.dir/src/nf/nf_dense_layer_submodule.f90.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:158: CMakeFiles/neural-fortran.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

**Comment by HarshilShah1804** [comment]
Perfect. I will turn off `PARALLEL` in all the files.

**Comment by HarshilShah1804** [comment]
With #10508 and https://github.com/HarshilShah1804/neural-fortran/commit/651185c527d059a58f119a065b2a811540494b00, all tests except for 10 run correctly.
```console
(base) harshil-shah@harshil-shah-HP-Pavilion-Laptop-15-eg2xxx:~/neural-fortran$ time fpm test --compiler=lfortran --flag "--cpp --realloc-l
hs-arrays"
 + mkdir -p build/dependencies
nf_random.f90                          done.
nf_activation.f90                      done.
nf_parallel.f90                        done.
nf_optimizers.f90                      done.
nf_base_layer.f90                      done.
nf_datasets.f90                        done.
nf_metrics.f90                         done.
nf_datasets_mnist.f90                  done.
nf_io_binary.f90                       done.
tuff.f90                               done.
nf_embedding_layer.f90                 done.
nf_flatten_layer.f90                   done.
nf_reshape3d_layer.f90                 done.
nf_conv2d_layer.f90                    done.
nf_avgpool2d_layer.f90                 done.
nf_avgpool1d_layer.f90                 done.
nf_input3d_layer.f90                   done.
nf_conv1d_layer.f90                    done.
nf_layer.f90                           done.
nf_dense_layer.f90                     done.
nf_linear2d_layer.f90                  done.
nf_input1d_layer.f90                   done.
nf_locally_connected2d_layer.f90       done.
nf_maxpool2d_layer.f90                 done.
nf_input2d_layer.f90                   done.
nf_datasets_submodule.f90              done.
nf_parallel_submodule.f90              done.
nf_datasets_mnist_submodule.f90        done.
nf_dropout_layer.f90                   done.
nf_layernorm.f90                       done.
nf_maxpool1d_layer.f90                 done.
nf_reshape2d_layer.f90                 done.
nf_loss.f90                            done.
nf_io_binary_submodule.f90             done.
nf_layernorm_submodule.f90             done.
nf_dense_layer_submodule.f90           done.
nf_avgpool1d_layer_submodule.f90       done.
nf_locally_connected2d_layer_submodule.done.
nf_linear2d_layer_submodule.f90        done.
nf_dropout_layer_submodule.f90         done.
nf_reshape2d_layer_submodule.f90       done.
nf_input1d_layer_submodule.f90         done.
nf_input2d_layer_submodule.f90         done.
nf_multihead_attention_layer.f90       done.
nf_maxpool2d_layer_submodule.f90       done.
nf_conv1d_layer_submodule.f90          done.
nf_maxpool1d_layer_submodule.f90       done.
nf_network.f90                         done.
nf_reshape3d_layer_submodule.f90       done.
nf_flatten_layer_submodule.f90         done.
nf_input3d_layer_submodule.f90         done.
nf_conv2d_layer_submodule.f90          done.
nf_avgpool2d_layer_submodule.f90       done.
nf_loss_submodule.f90                  done.
nf_embedding_layer_submodule.f90       done.
nf_layer_constructors.f90              done.
test_linear2d_layer.f90                done.
nf.f90                                 done.
nf_multihead_attention_layer_submodule.done.
nf_self_attention_layer.f90            done.
nf_cross_attention_layer.f90           done.
test_embedding_layer.f90               done.
nf_layer_constructors_submodule.f90    done.
nf_network_submodule.f90               done.
nf_layer_submodule.f90                 done.
dense_mnist.f90                        done.
simple.f90                             done.
mha_simple.f90                         done.
cnn_mnist.f90                          done.
cnn_mnist_1d.f90                       done.
quadratic.f90                          done.
sine.f90                               done.
merge_networks.f90                     done.
get_set_network_params.f90             done.
network_parameters.f90                 done.
test_loss.f90                          done.
test_maxpool2d_layer.f90               done.
test_insert_flatten.f90                done.
test_input2d_layer.f90                 done.
test_maxpool1d_layer.f90               done.
test_flatten_layer.f90                 done.
test_avgpool2d_layer.f90               done.
test_layernorm.f90                     done.
test_reshape2d_layer.f90               done.
test_conv2d_layer.f90                  done.
test_dropout_layer.f90                 done.
test_optimizers.f90                    done.
test_input3d_layer.f90                 done.
test_dense_layer.f90                   done.
test_conv1d_network.f90                done.
test_get_set_network_params.f90        done.
test_multihead_attention_layer.f90     done.
test_conv1d_layer.f90                  done.
test_avgpool1d_layer.f90               done.
test_conv2d_network.f90                done.
test_metrics.f90                       done.
test_locally_connected2d_layer.f90     done.
test_reshape_layer.f90                 done.
test_parametric_activation.f90         done.
test_input1d_layer.f90                 done.
test_dense_network.f90                 done.
libneural-fortran.a                    done.
dense_mnist                            done.
simple                                 done.
mha_simple                             done.
cnn_mnist                              done.
cnn_mnist_1d                           done.
quadratic                              done.
sine                                   done.
merge_networks                         done.
get_set_network_params                 done.
network_parameters                     done.
test_loss                              done.
test_maxpool2d_layer                   done.
test_insert_flatten                    done.
test_input2d_layer                     done.
test_maxpool1d_layer                   done.
test_flatten_layer                     done.
test_avgpool2d_layer                   done.
test_layernorm                         done.
test_embedding_layer                   done.
test_reshape2d_layer                   done.
test_conv2d_layer                      done.
test_dropout_layer                     done.
test_linear2d_layer                    done.
test_optimizers                        done.
test_input3d_layer                     done.
test_dense_layer                       done.
test_conv1d_network                    done.
test_get_set_network_params            done.
test_multihead_attention_layer         done.
test_conv1d_layer                      done.
test_avgpool1d_layer                   done.
test_conv2d_network                    done.
test_metrics                           done.
test_locally_connected2d_layer         done.
test_reshape_layer                     done.
test_parametric_activation             done.
test_input1d_layer                     done.
test_dense_network                     done.
[100%] Project compiled successfully.
test_loss: All tests passed.
test_maxpool2d_layer: All tests passed.
test_insert_flatten: All tests passed.
test_input2d_layer: All tests passed.
test_maxpool1d_layer: All tests passed.
test_flatten_layer: All tests passed.
test_avgpool2d_layer: All tests passed.
Segmentation fault (core dumped)
test_embedding_layer: All tests passed.
test_reshape2d_layer: All tests passed.
test_conv2d_layer: All tests passed.
Segmentation fault (core dumped)
Segmentation fault (core dumped)
Segmentation fault (core dumped)
test_input3d_layer: All tests passed.
test_dense_layer: All tests passed.
runtime error: Array shape mismatch in assignment to '__libasr_created__subroutine_call_1_optimizer_base_type_minimize'. Tried to match size -2032454768 of dimension 1 of LHS with size 1842165560 of dimension 1 of RHS. Use '--realloc-lhs-arrays' option to reallocate LHS automatically.
   --> ././src/nf/nf_network_submodule.f90:735:65
    |
735 |           call self % layers(n) % optimizer % minimize(weights, dw / batch_size_)
    |                                                                 ^^^^^^^^^^^^^^^^ LHS size is -2032454768
    |
735 |           call self % layers(n) % optimizer % minimize(weights, dw / batch_size_)
    |                                                                 ^^ RHS size is 1842165560
Segmentation fault (core dumped)
Segmentation fault (core dumped)
test_conv1d_layer: All tests passed.
test_avgpool1d_layer: All tests passed.
runtime error: Array shape mismatch in assignment to '__libasr_created__subroutine_call_1_optimizer_base_type_minimize'. Tried to match size 190764496 of dimension 1 of LHS with size 1129630496 of dimension 1 of RHS. Use '--realloc-lhs-arrays' option to reallocate LHS automatically.
   --> ././src/nf/nf_network_submodule.f90:742:65
    |
742 |           call self % layers(n) % optimizer % minimize(weights, dw / batch_size_)
    |                                                                 ^^^^^^^^^^^^^^^^ LHS size is 190764496
    |
742 |           call self % layers(n) % optimizer % minimize(weights, dw / batch_size_)
    |                                                                 ^^ RHS size is 1129630496
Segmentation fault (core dumped)
test_locally_connected2d_layer: All tests passed.
test_reshape_layer: All tests passed.
test_parametric_activation: All tests passed.
test_input1d_layer: All tests passed.
Segmentation fault (core dumped)
<ERROR> Execution for object " test_layernorm " returned exit code  139
<ERROR> Execution for object " test_dropout_layer " returned exit code  139
<ERROR> Execution for object " test_linear2d_layer " returned exit code  139
<ERROR> Execution for object " test_optimizers " returned exit code  139
<ERROR> Execution for object " test_conv1d_network " returned exit code  1
<ERROR> Execution for object " test_get_set_network_params " returned exit code  139
<ERROR> Execution for object " test_multihead_attention_layer " returned exit code  139
<ERROR> Execution for object " test_conv2d_network " returned exit code  1
<ERROR> Execution for object " test_metrics " returned exit code  139
<ERROR> Execution for object " test_dense_network " returned exit code  139
<ERROR> *cmd_run*:stopping due to failed executions
STOP 139
```
