### ISSUE TITLE
Expression type, 19 ?

### ISSUE THREAD

**Issue by harperjf** [lfortran/lfortran#4837]
The error message from lfortran with some of my programs ends
```
 LCompilersException: Expression type, 19 not yet supported
```
and the traceback refers only to binary files that I did not write. How do I find out what that 19 means and which line in my Fortran program caused the trouble? The programs compiled and ran with several other compilers, suggesting that they are standard-conforming.

**Comment by certik** [comment]
This is an internal error, the 19 is an ASR node, in this case an `expr` (I think), counted from here: https://github.com/lfortran/lfortran/blob/576604da7068bcd5c7ae191ff61a0edcc35be5ca/src/libasr/ASR.asdl#L79, so if I count correctly, it's `UnsignedIntegerBitNot` that doesn't have an implementation somewhere. If you can post a minimal reproducible example of code that triggers it, then we can fix it.

**Comment by kmr-srbh** [comment]
Yes, I recently fixed some of these. I will open a PR to refactor this in the code-base.

**Comment by harperjf** [comment]
This is the shortest program I have that triggers this bug. The ```do``` loop and ```advance=``` options in the ```write``` statements were to avoid a different lfortran bug.
```
program kindtest
  implicit none
  integer,parameter::  kr1 = selected_real_kind(1), maxkr = 3, &
       skr2 = selected_real_kind(precision(1.0_kr1)+1), &
       kr2  = merge(skr2,kr1, skr2>0),                & 
       skr3 = selected_real_kind(precision(1.0_kr2)+1), &
       kr3  = merge(skr3,kr2, skr3>0),&
! kr3 = skr3 if that's a valid real kind, kr2 if not
       allkr(maxkr+1) = [kr1,kr2,kr3,kr3],&
       nkr = minloc(abs(allkr(1:maxkr)-allkr(2:maxkr+1)),1)
  
  call realkinds(nkr)
contains
  subroutine realkinds( nkr)
    integer,intent(in)::nkr
    integer :: n
    integer:: goodkr(nkr) !!= [(allkr(n),n=1,nkr)]
    goodkr = allkr(1:nkr)
    print "(A,I0)",'precision(1.0_kr1) = ',precision(1.0_kr1)
    if(nkr>=2) print "(A,I0)",'precision(1.0_kr2) = ',precision(1.0_kr2)
    if(nkr>=3) print "(A,I0)",'precision(1.0_kr3) = ',precision(1.0_kr3)
    write(*,"(A,I0,A)",advance='no') &
         'Number of different real kinds = ',nkr,', real kinds:'
    do n = 1,nkr ! lfortran write can't use implied-do or array section
       write(*,"(1X,I0)",advance=merge('no ','yes',n<nkr)) allkr(n)
    end do
    print "(3A)",'There ',merge('may be','are no',nkr>=maxkr),' more real kinds'
  end subroutine realkinds
end program kindtest
```
```With lfortran 0.40.0 using --std=f23 this is its compile-time output:
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/john/conda_root/envs/lf/bin/lfortran", local address: 0x7e50d5
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", local address: 0x2a28a
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", local address: 0x2a1c9
  Binary file "/home/john/conda_root/envs/lf/bin/lfortran", local address: 0x687d68
  Binary file "/home/john/conda_root/envs/lf/bin/lfortran", local address: 0x861331
  Binary file "/home/john/conda_root/envs/lf/bin/lfortran", local address: 0x84e369
  Binary file "/home/john/conda_root/envs/lf/bin/lfortran", local address: 0x949fc1
  Binary file "/home/john/conda_root/envs/lf/bin/lfortran", local address: 0x2327672
  Binary file "/home/john/conda_root/envs/lf/bin/lfortran", local address: 0x229fb18
  Binary file "/home/john/conda_root/envs/lf/bin/lfortran", local address: 0x1c21dcb
  Binary file "/home/john/conda_root/envs/lf/bin/lfortran", local address: 0x1c2177c
  Binary file "/home/john/conda_root/envs/lf/bin/lfortran", local address: 0x1c21b3b
  Binary file "/home/john/conda_root/envs/lf/bin/lfortran", local address: 0x1b610d5
  Binary file "/home/john/conda_root/envs/lf/bin/lfortran", local address: 0x1b61f49
LCompilersException: Expression type, 19 not yet supported
```
With gfortran  14 this is its run-time ouput:
```
precision(1.0_kr1) = 6
precision(1.0_kr2) = 15
precision(1.0_kr3) = 18
Number of different real kinds = 3, real kinds: 4 8 10
There may be more real kinds
```

**Comment by certik** [comment]
@harperjf awesome, thanks for this!

**Comment by harperjf** [comment]
This version of my kindtest program compiled and ran with lfortran! Was the bug causing an ICE triggered by ```nkr``` being a constant not a variable? 
```
program kindtestd
  implicit none
  integer,parameter::  kr1 = selected_real_kind(1), maxkr = 3, &
       skr2 = selected_real_kind(precision(1.0_kr1)+1), &
       kr2  = merge(skr2,kr1, skr2>0),                & 
       skr3 = selected_real_kind(precision(1.0_kr2)+1), &
       kr3  = merge(skr3,kr2, skr3>0),&
! kr3 = skr3 if that's a valid real kind, kr2 if not
       allkr(maxkr+1) = [kr1,kr2,kr3,kr3] !! ,&
  integer:: nkr
  nkr = minloc(abs(allkr(1:maxkr)-allkr(2:maxkr+1)),1)
  
  call realkinds(nkr)
contains
  subroutine realkinds( nkr)
    integer,intent(in)::nkr
    integer :: n
    print "(A,I0)",'precision(1.0_kr1) = ',precision(1.0_kr1)
    if(nkr>=2) print "(A,I0)",'precision(1.0_kr2) = ',precision(1.0_kr2)
    if(nkr>=3) print "(A,I0)",'precision(1.0_kr3) = ',precision(1.0_kr3)
    write(*,"(A,I0,A)",advance='no') &
         'Number of different real kinds = ',nkr,', real kinds:'
    print "(*(1X,I0))",allkr(1:nkr) 
    print "(3A)",'There ',merge('may be','are no',nkr>=maxkr),' more real kinds'
  end subroutine realkinds
end program kindtestd
```
Run-time output with lfortran 0.40.0:
```
precision(1.0_kr1) = 6
precision(1.0_kr2) = 15
Number of different real kinds = 2, real kinds: 4 8
There are no more real kinds
```

**Comment by certik** [comment]
Possibly. For constants we do compile time evaluation of the intrinsics, so perhaps there is a bug in it.

**Comment by HarshitaKalani** [comment]
```fortran
program kindtest
  integer, parameter:: allkr(4) = [-1,2,-3,4]
  integer, parameter :: nkr(4) = abs(allkr(1:4))
  print *, nkr
end program kindtest
```
```console
$ gfortran a.f90 &&  ./a.out
           1           2           3           4
$ lfortran a.f90
type: 19
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2668, in main
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2611, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 1042, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 377, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10196, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 315, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 169, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/intrinsic_function.cpp", line 433, in LCompilers::pass_replace_intrinsic_function(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    v.visit_TranslationUnit(unit);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 49166, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5163, in LCompilers::ASR::BaseVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4875, in void LCompilers::ASR::visit_symbol_t<LCompilers::ReplaceIntrinsicFunctionsVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ReplaceIntrinsicFunctionsVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 49175, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_Program(LCompilers::ASR::Program_t const&)
    this->visit_symbol(*a.second);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5163, in LCompilers::ASR::BaseVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4884, in void LCompilers::ASR::visit_symbol_t<LCompilers::ReplaceIntrinsicFunctionsVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ReplaceIntrinsicFunctionsVisitor&)
    case symbolType::Variable: { v.visit_Variable((const Variable_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 49280, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ReplaceIntrinsicFunctionsVisitor>::visit_Variable(LCompilers::ASR::Variable_t const&)
    self().call_replacer();
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/intrinsic_function.cpp", line 147, in LCompilers::ReplaceIntrinsicFunctionsVisitor::call_replacer()
    replacer.replace_expr(*current_expr);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 48123, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceIntrinsicFunctions>::replace_expr(LCompilers::ASR::expr_t*)
    self().replace_IntrinsicElementalFunction(down_cast<ASR::IntrinsicElementalFunction_t>(x));
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/intrinsic_function.cpp", line 76, in LCompilers::ReplaceIntrinsicFunctions::replace_IntrinsicElementalFunction(LCompilers::ASR::IntrinsicElementalFunction_t*)
    ASR::expr_t* current_expr_ = instantiate_function(al, x->base.base.loc,
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/pass/intrinsic_functions.h", line 848, in LCompilers::ASRUtils::Abs::instantiate_Abs(Allocator&, LCompilers::Location const&, LCompilers::SymbolTable*, LCompilers::Vec<LCompilers::ASR::ttype_t*>&, LCompilers::ASR::ttype_t*, LCompilers::Vec<LCompilers::ASR::call_arg_t>&, long)
    body.push_back(al, b.If(b.GtE(args[0], b.i_t(0, arg_types[0])), {
LCompilersException: Expression type, i32[:] not yet supported
```
