### ISSUE TITLE
Twin primes code not working

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#494]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/644

With gfortran, Intel Fortran, and flang the code prints many twin primes. LFortran says there are none.

```
(base) /mnt/c/fortran/test$ lfortran --version
LFortran version: 0.14.0-1016-gd53a3b83
Platform: Linux
Default target: x86_64-unknown-linux-gnu
(base) /mnt/c/fortran/test$ cat twinprimes.f90
! https://craftofcoding.wordpress.com/2022/01/17/translating-basic-to-fortran-twin-primes/
program twinPrime
implicit none
integer, parameter :: n = 1000
integer :: A(n), B(n), i, nprimes, d
real, parameter :: s = sqrt(real(n))
A = 0
nprimes = 0
do d = 2, n
   if (A(d) >= 0) then
      nprimes = nprimes + 1
      B(nprimes) = d
      if (d <= s) A(d:n:d) = -1
   end if
end do
write (*,*) "Twin primes"
do i = 2,nprimes
   if (B(i)-B(i-1) == 2) write (*,*) B(i-1), B(i)
end do
end program twinPrime
(base) /mnt/c/fortran/test$ lfortran twinprimes.f90
(base) /mnt/c/fortran/test$ ./a.out
Twin primes
(base) /mnt/c/fortran/test$ 
```

**Comment by lucifer1004** [comment]
The code above cannot compile now since range increment / do-loop increment have not been supported in the current C++ version.

**Comment by certik** [comment]
Here is the current exception:
```console
$ lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1756
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 761
    res = fe.get_llvm3(*asr, lpm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 319
    compiler_options.platform, run_fn);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5704
    v.nested_func_types = pass_find_nested_vars(asr, context,
  File "../libasr/asr.h", line 3818
  File "../libasr/asr.h", line 3795
  File "../libasr/asr.h", line 3819
  File "../libasr/asr.h", line 3584
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1047
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 3821
  File "../libasr/asr.h", line 3593
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1811
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 3834
  File "../libasr/asr.h", line 3640
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3657
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 3834
  File "../libasr/asr.h", line 3625
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3607
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 3834
  File "../libasr/asr.h", line 3625
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3607
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 3834
  File "../libasr/asr.h", line 3613
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3257
    is_assignment_target = true;
  File "../libasr/asr.h", line 3877
  File "../libasr/asr.h", line 3706
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1527
    LFORTRAN_ASSERT(ASR::is_a<ASR::Character_t>(*ASRUtils::expr_type(x.m_v)) &&
AssertFailed: ASR::is_a<ASR::Character_t>(*ASRUtils::expr_type(x.m_v)) && n_dims == 0
```

**Comment by harperjf** [comment]
While looking at old bug reports I found that #494 has been fixed. Lfortran 0.56.0 gives the same output as gfortran except for the number of blanks to put in when printing. The standard allows that difference with * format. I don't know when this happy event occurred.

**Comment by certik** [comment]
Thanks! Let's add the example to integration tests and we can close it.
