### ISSUE TITLE
SNAP MRE for simplifier

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#4985]
```fortran
SUBROUTINE setup_echo()
INTEGER :: i
REAL, DIMENSION(5,5) :: sigt
print *, ( i, sigt(2,i), i = 1, 6 )
END SUBROUTINE setup_echo

```

```console
% lfortran a.f90 --show-llvm
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2668, in main
    return main_app(argc, argv);
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2510, in main_app(int, char**)
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 940, in (anonymous namespace)::emit_llvm(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::PassManager&, LCompilers::CompilerOptions&)
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 309, in LCompilers::FortranEvaluator::get_llvm(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&)
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 330, in LCompilers::FortranEvaluator::get_llvm2(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&)
    Result<std::unique_ptr<LLVMModule>> res = get_llvm3(*asr.result, pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 375, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
    = asr_to_llvm(asr, diagnostics,
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10184, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 316, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 166, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 715, in LCompilers::pass_replace_array_op(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    v.visit_TranslationUnit(unit);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 49353, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayOpVisitor>::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5163, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayOpVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 4877, in void LCompilers::ASR::visit_symbol_t<LCompilers::ArrayOpVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ArrayOpVisitor&)
    case symbolType::Function: { v.visit_Function((const Function_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 49391, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayOpVisitor>::visit_Function(LCompilers::ASR::Function_t const&)
    self().transform_stmts(xx.m_body, xx.n_body);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 397, in LCompilers::ArrayOpVisitor::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    visit_stmt(*m_body[i]);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5180, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayOpVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 4901, in void LCompilers::ASR::visit_stmt_t<LCompilers::ArrayOpVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ArrayOpVisitor&)
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 653, in LCompilers::ArrayOpVisitor::visit_Assignment(LCompilers::ASR::Assignment_t const&)
    this->call_replacer();
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 367, in LCompilers::ArrayOpVisitor::call_replacer()
    replacer.replace_expr(*current_expr);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 48545, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceArrayOp>::replace_expr(LCompilers::ASR::expr_t*)
    self().replace_ArrayConstructor(down_cast<ASR::ArrayConstructor_t>(x));
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 282, in LCompilers::ReplaceArrayOp::replace_ArrayConstructor(LCompilers::ASR::ArrayConstructor_t*)
    PassUtils::ReplacerUtils::replace_ArrayConstructor(
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/pass/pass_utils.h", line 960, in LCompilers::PassUtils::ReplacerUtils::replace_ArrayConstructor(Allocator&, LCompilers::ASR::ArrayConstructor_t*, LCompilers::ASR::expr_t*, LCompilers::Vec<LCompilers::ASR::stmt_t*>*, LCompilers::SymbolTable*, bool, LCompilers::ASR::cast_kindType, LCompilers::ASR::ttype_t*)
    visit_ArrayConstructor(x, al, result_var, result_vec,
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_utils.cpp", line 1310, in LCompilers::PassUtils::ReplacerUtils::visit_ArrayConstructor(LCompilers::ASR::ArrayConstructor_t*, Allocator&, LCompilers::ASR::expr_t*, LCompilers::Vec<LCompilers::ASR::stmt_t*>*, LCompilers::ASR::expr_t*, LCompilers::SymbolTable*, bool, LCompilers::ASR::cast_kindType, LCompilers::ASR::ttype_t*)
    create_do_loop(al, idoloop, arr_var, result_vec, idx_var, perform_cast, cast_kind, casted_type);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/pass/pass_utils.h", line 731, in LCompilers::PassUtils::ReplacerUtils::create_do_loop(Allocator&, LCompilers::ASR::ImpliedDoLoop_t*, LCompilers::ASR::expr_t*, LCompilers::Vec<LCompilers::ASR::stmt_t*>*, LCompilers::ASR::expr_t*, bool, LCompilers::ASR::cast_kindType, LCompilers::ASR::ttype_t*)
    array_ref_type = ASRUtils::duplicate_type(al, array_ref_type, &empty_dims);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr_utils.h", line 2559, in LCompilers::ASRUtils::duplicate_type(Allocator&, LCompilers::ASR::ttype_t const*, LCompilers::Vec<LCompilers::ASR::dimension_t>*, LCompilers::ASR::array_physical_typeType, bool)
    ASR::ttype_t* duplicated_element_type = duplicate_type(al, tnew->m_type);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr_utils.h", line 2674, in LCompilers::ASRUtils::duplicate_type(Allocator&, LCompilers::ASR::ttype_t const*, LCompilers::Vec<LCompilers::ASR::dimension_t>*, LCompilers::ASR::array_physical_typeType, bool)
    default : throw LCompilersException("Not implemented " + ASRUtils::type_to_str_python(t));
LCompilersException: Not implemented tuple[i32, f32]

```

**Comment by kmr-srbh** [comment]
Thanks for this! This was reported at https://github.com/lfortran/lfortran/issues/4761#issuecomment-2334189295. :)
