### ISSUE TITLE
Segmentation Fault on Array Slice Assignment

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#5066]
```fortran
program main
  integer(8) ilist(1, 1)
  integer, parameter :: x = 1
  ilist(1,1:1) = [x]
  print *, ilist
end program
```
```console
$ gfortran b.f90 && ./a.out
                    1
$ lfortran b.f90
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2668, in main
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2611, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 1042, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 377, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10202, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5160, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5136, in void LCompilers::ASR::visit_asr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::asr_t const&, LCompilers::ASRToLLVMVisitor&)
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5161, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4867, in void LCompilers::ASR::visit_unit_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::unit_t const&, LCompilers::ASRToLLVMVisitor&)
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 957, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5163, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4875, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToLLVMVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3243, in LCompilers::ASRToLLVMVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5180, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4930, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::WhileLoop: { v.visit_WhileLoop((const WhileLoop_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5982, in LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)
    create_loop(x.m_name, [=]() {
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 317, in void LCompilers::ASRToLLVMVisitor::create_loop<LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda'(), LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda0'()>(char*, LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda'(), LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda0'())
    loop_body();
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5988, in LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda0'()::operator()() const
    this->visit_stmt(*x.m_body[i]);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5180, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4901, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5054, in LCompilers::ASRToLLVMVisitor::visit_Assignment(LCompilers::ASR::Assignment_t const&)
    this->visit_expr_wrapper(m_value, true);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5459, in LCompilers::ASRToLLVMVisitor::visit_expr_wrapper(LCompilers::ASR::expr_t*, bool)
    this->visit_expr(*x);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5228, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5036, in void LCompilers::ASR::visit_expr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ASRToLLVMVisitor&)
    case exprType::Cast: { v.visit_Cast((const Cast_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7187, in LCompilers::ASRToLLVMVisitor::visit_Cast(LCompilers::ASR::Cast_t const&)
    this->visit_expr_wrapper(x.m_arg, true);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5459, in LCompilers::ASRToLLVMVisitor::visit_expr_wrapper(LCompilers::ASR::expr_t*, bool)
    this->visit_expr(*x);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5228, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5017, in void LCompilers::ASR::visit_expr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ASRToLLVMVisitor&)
    case exprType::ArrayItem: { v.visit_ArrayItem((const ArrayItem_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2358, in LCompilers::ASRToLLVMVisitor::visit_ArrayItem(LCompilers::ASR::ArrayItem_t const&)
    ptr_loads = 2 - !LLVM::is_llvm_pointer(*ASRUtils::expr_type(m_dims[idim].m_start));
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr_utils.h", line 298, in LCompilers::ASRUtils::expr_type(LCompilers::ASR::expr_t const*)
    return ASR::expr_type0(f);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 52591, in LCompilers::ASR::expr_type0(LCompilers::ASR::expr_t const*)
    switch (f->type) {
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in <invalid>
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by harperjf** [comment]
Looks like #4501 where this still gives a seg.fault:
```
  implicit none
  integer,parameter:: k = selected_int_kind(0) ! smallest integer type
  integer :: iarray(3,4)
  iarray(1,1:2) = [bit_size(1_k),huge(1_k)]
  print *,kind(1_k),iarray(1,1:2)
end program
```

**Comment by HarshitaKalani** [comment]
Yeah, these are both the same issues.
The following works.
```fortran
program main
  integer(4) ilist(1, 1)
  integer, parameter :: x = 1
  ilist(1,1:1) = [x]
  print *, ilist
end program
```

**Comment by HarshitaKalani** [comment]
```console
 % lfortran b.f90
1
% gfortran b.f90 && ./a.out
                    1
 % gfortran b.f90 && ./a.out
           1           8         127
% lfortran b.f90           
1    8    127
```
