### ISSUE TITLE
set allocation size not set for IntrinsicElementalFunction 'Sqrt'

### ISSUE THREAD

**Issue by gxyd** [lfortran/lfortran#5093]
## MRE

```f90
program array_operations
    implicit none
  
    ! Declare variables
    integer, dimension(5) :: array
    real :: scalar_value
    integer :: i
    real, dimension(5) :: x, y, z

    array = (/ 1, 0, 3, 0, 5 /)
    x = (/ 1.0, 2.0, 3.0, 4.0, 5.0 /)
    y = (/ 2.0, 4.0, 6.0, 8.0, 10.0 /)
    
    scalar_value = 2.5
    
    print *, "Result:", square(scalar_value)

    z = array_function(x, y)
    print *, "Result (z):", z

    where (array == 0)
      array = 10
    end where

    do i = 1, size(array)
      print *, "array(", i, ") squared =", square(real(array(i)))
    end do

  contains

    real function square(a)
      real, intent(in) :: a
      square = a * a
    end function

    real function array_function(a, b)
      real, intent(in) :: a(:), b(:)
      real :: temp(size(a))
      array_function = 0.0

      temp = a + sqrt(b)
      array_function = temp(0)
    end function
  
end program array_operations

```

## Output with *simplifier_pass* branch

On execution of the above fortran program on *simplifier_pass* branch:
```console
> lfortran test.f90
LCOMPILERS_ASSERT failed: /Users/gxyd/OpenSource/lfortran/src/libasr/pass/simplifier.cpp
function set_allocation_size(), line number 595 at 
false
ERROR MESSAGE:
ASR::IntrinsicElementalFunctions::Sqrt not handled yet in set_allocation_size
[1]    98858 abort      /Users/gxyd/OpenSource/lfortran/src/bin/lfortran test1.f90
```

## Output with current *main*

while it's execution with current main with commit: `474790bc55619460146d8e8ffc5d8ad36897705f` as the top, I get the correct output:
```console
> lfortran test.f90
Result:    6.25000000e+00
Result (z):    0.00000000e+00    0.00000000e+00    0.00000000e+00    0.00000000e+00    0.00000000e+00
array(    1    ) squared =    1.00000000e+00
array(    2    ) squared =    1.00000000e+02
array(    3    ) squared =    9.00000000e+00
array(    4    ) squared =    1.00000000e+02
array(    5    ) squared =    2.50000000e+01
```

**Comment by HarshitaKalani** [comment]
```diff
$ git diff
diff --git a/src/libasr/pass/simplifier.cpp b/src/libasr/pass/simplifier.cpp
index df86ac71a..91d20761e 100644
--- a/src/libasr/pass/simplifier.cpp
+++ b/src/libasr/pass/simplifier.cpp
@@ -585,6 +585,7 @@ bool set_allocation_size(
                 case static_cast<int64_t>(ASRUtils::IntrinsicElementalFunctions::Aimag):
                 case static_cast<int64_t>(ASRUtils::IntrinsicElementalFunctions::Int):
                 case static_cast<int64_t>(ASRUtils::IntrinsicElementalFunctions::SubstrIndex):
+                case static_cast<int64_t>(ASRUtils::IntrinsicElementalFunctions::Sqrt):
                 case static_cast<int64_t>(ASRUtils::IntrinsicElementalFunctions::Merge): {
                     set_allocation_size_elemental_function(al, loc, intrinsic_elemental_function,
                         allocate_dims);
```

After this diff, there's another error:
```fortran
program array_operations
    implicit none
    real, dimension(2) :: x, z
    x = [ 1.0, 2.0 ]
    
    z = array_function(x)

  contains

    real function array_function(a)
      real, intent(in) :: a(:)
      print*, a 
    end function
  
end program array_operations

```
```console
$ gfortran a.f90 && ./a.out
   1.00000000       2.00000000    
(lf) harshita@harshita-linux:~/Desktop/lfortran$ lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2668, in main
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2611, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 1042, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 377, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10206, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 320, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 170, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 720, in LCompilers::pass_array_by_data(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    u.visit_TranslationUnit(unit);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 42782, in LCompilers::ASR::ASRPassBaseWalkVisitor<LCompilers::EditProcedureCallsVisitor>::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5163, in LCompilers::ASR::BaseVisitor<LCompilers::EditProcedureCallsVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4875, in void LCompilers::ASR::visit_symbol_t<LCompilers::EditProcedureCallsVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::EditProcedureCallsVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 42793, in LCompilers::ASR::ASRPassBaseWalkVisitor<LCompilers::EditProcedureCallsVisitor>::visit_Program(LCompilers::ASR::Program_t const&)
    self().transform_stmts(xx.m_body, xx.n_body);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 42775, in LCompilers::ASR::ASRPassBaseWalkVisitor<LCompilers::EditProcedureCallsVisitor>::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    self().visit_stmt(*m_body[i]);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5180, in LCompilers::ASR::BaseVisitor<LCompilers::EditProcedureCallsVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4907, in void LCompilers::ASR::visit_stmt_t<LCompilers::EditProcedureCallsVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::EditProcedureCallsVisitor&)
    case stmtType::DoLoop: { v.visit_DoLoop((const DoLoop_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 43000, in LCompilers::ASR::ASRPassBaseWalkVisitor<LCompilers::EditProcedureCallsVisitor>::visit_DoLoop(LCompilers::ASR::DoLoop_t const&)
    self().transform_stmts(xx.m_body, xx.n_body);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 42775, in LCompilers::ASR::ASRPassBaseWalkVisitor<LCompilers::EditProcedureCallsVisitor>::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    self().visit_stmt(*m_body[i]);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5180, in LCompilers::ASR::BaseVisitor<LCompilers::EditProcedureCallsVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4901, in void LCompilers::ASR::visit_stmt_t<LCompilers::EditProcedureCallsVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::EditProcedureCallsVisitor&)
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 42960, in LCompilers::ASR::ASRPassBaseWalkVisitor<LCompilers::EditProcedureCallsVisitor>::visit_Assignment(LCompilers::ASR::Assignment_t const&)
    self().visit_expr(*x.m_value);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5228, in LCompilers::ASR::BaseVisitor<LCompilers::EditProcedureCallsVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4955, in void LCompilers::ASR::visit_expr_t<LCompilers::EditProcedureCallsVisitor>(LCompilers::ASR::expr_t const&, LCompilers::EditProcedureCallsVisitor&)
    case exprType::FunctionCall: { v.visit_FunctionCall((const FunctionCall_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 612, in LCompilers::EditProcedureCallsVisitor::visit_FunctionCall(LCompilers::ASR::FunctionCall_t const&)
    visit_Call(x);
LCompilersException: Number of arguments in the new function call array_function doesn't satisfy min_args <= new_args.size() <= max_args, 3 <= 1 <= 3
```

**Comment by HarshitaKalani** [comment]
Here the `min_args <= new_args.size() <= max_args, 3 <= 1 <= 3`
min_args and max_args are always equal to 3*new_args.size(). I'm trying to investigate the source of this generation.

**Comment by Pranavchiku** [comment]
@HarshitaKalani let's do the following, can you assure that `set_allocation_size()` function has handling for all intrinsics that we support and add corresponding tests?

**Comment by HarshitaKalani** [comment]
Yep, I'll do that.
The issue exists in main as well. I'll patch https://github.com/lfortran/lfortran/pull/5096 to main.
