### ISSUE TITLE
Preprocessing error while using defined in "#if"

### ISSUE THREAD

**Issue by jinangshah21** [lfortran/lfortran#5100]
Towards #4397.
```
program temp
#if (defined __flang__ && __flang_major__ <= 19)
integer,parameter :: x = 0
#else
integer,parameter :: y = 0
#endif
end program
```

Lfortran Error : 
```
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/mnt/c/lfortran/src/bin/lfortran", in _start
  File "/build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c", line 308, in __libc_start_main
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2668, in main
    return main_app(argc, argv);
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2611, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 1000, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    result = fe.get_asr2(input, lm, diagnostics);
  File "/mnt/c/lfortran/src/lfortran/fortran_evaluator.cpp", line 261, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    res = get_ast2(code_orig, lm, diagnostics);
  File "/mnt/c/lfortran/src/lfortran/fortran_evaluator.cpp", line 205, in LCompilers::FortranEvaluator::get_ast2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    tmp = cpp.run(code_orig, lm, cpp.macro_definitions);
  File "/mnt/c/lfortran/src/lfortran/parser/preprocessor.re", line 355, in LCompilers::LFortran::CPreprocessor::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::LFortran::CPPMacro, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::LFortran::CPPMacro> > >&) const (.localalias)
    bool test_true = parse_bexpr(t1, macro_definitions) > 0;
  File "/mnt/c/lfortran/src/lfortran/parser/preprocessor.re", line 767, in LCompilers::LFortran::(anonymous namespace)::parse_bexpr(unsigned char*&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::LFortran::CPPMacro, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::LFortran::CPPMacro> > > const&)
    int tmp = parse_bfactor(cur, macro_definitions);
  File "/mnt/c/lfortran/src/lfortran/parser/preprocessor.re", line 984, in LCompilers::LFortran::(anonymous namespace)::parse_bfactor(unsigned char*&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::LFortran::CPPMacro, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::LFortran::CPPMacro> > > const&)
    int result = parse_relation(cur, macro_definitions);
  File "/mnt/c/lfortran/src/lfortran/parser/preprocessor.re", line 928, in LCompilers::LFortran::(anonymous namespace)::parse_relation(unsigned char*&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::LFortran::CPPMacro, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::LFortran::CPPMacro> > > const&)
    lhs = parse_expr(cur, macro_definitions);
  File "/mnt/c/lfortran/src/lfortran/parser/preprocessor.re", line 793, in LCompilers::LFortran::(anonymous namespace)::parse_expr(unsigned char*&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::LFortran::CPPMacro, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::LFortran::CPPMacro> > > const&)
    tmp = parse_term(cur, macro_definitions);
  File "/mnt/c/lfortran/src/lfortran/parser/preprocessor.re", line 819, in LCompilers::LFortran::(anonymous namespace)::parse_term(unsigned char*&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::LFortran::CPPMacro, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::LFortran::CPPMacro> > > const&)
    tmp = parse_factor(cur, macro_definitions);
  File "/mnt/c/lfortran/src/lfortran/parser/preprocessor.re", line 907, in LCompilers::LFortran::(anonymous namespace)::parse_factor(unsigned char*&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::LFortran::CPPMacro, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::LFortran::CPPMacro> > > const&)
    int result = parse_bexpr(cur, macro_definitions);
  File "/mnt/c/lfortran/src/lfortran/parser/preprocessor.re", line 767, in LCompilers::LFortran::(anonymous namespace)::parse_bexpr(unsigned char*&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::LFortran::CPPMacro, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::LFortran::CPPMacro> > > const&)
    int tmp = parse_bfactor(cur, macro_definitions);
  File "/mnt/c/lfortran/src/lfortran/parser/preprocessor.re", line 969, in LCompilers::LFortran::(anonymous namespace)::parse_bfactor(unsigned char*&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::LFortran::CPPMacro, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::LFortran::CPPMacro> > > const&)
    accept(cur, CPPTokenType::TK_LPAREN);
LCompilersException: Unexpected token type 1, expected type 7
```

**Comment by certik** [comment]
I see, we are expecting `defined(__flang__)` in parentheses. As a workaround, do:
```
#if (defined(__flang__) && __flang_major__ <= 19)
```
Which works. 

To fix this bug, do something like:
```diff
--- a/src/lfortran/parser/preprocessor.re
+++ b/src/lfortran/parser/preprocessor.re
@@ -957,6 +957,7 @@ int parse_relation(unsigned char *&cur, const cpp_symtab &macro_definitions) {
 /*
 b-factor
     = "defined(" TK_NAME ")"
+    | "defined " TK_NAME
     | "!" b-factor
     | relation
 */
@@ -966,9 +967,14 @@ int parse_bfactor(unsigned char *&cur, const cpp_symtab &macro_definitions) {
     unsigned char *old_cur = cur;
     get_next_token(cur, type, str);
     if (type == CPPTokenType::TK_NAME && str == "defined") {
-        accept(cur, CPPTokenType::TK_LPAREN);
-        std::string macro_name = accept_name(cur);
-        accept(cur, CPPTokenType::TK_RPAREN);
+        std::string macro_name;
+        if (type == CPPTokenType::TK_LPAREN) {
+            accept(cur, CPPTokenType::TK_LPAREN);
+            macro_name = accept_name(cur);
+            accept(cur, CPPTokenType::TK_RPAREN);
+        } else {
+            macro_name = accept_name(cur);
+        }
         if (macro_definitions.find(macro_name) != macro_definitions.end()) {
             return true;
         } else {
```
Which should work.

**Comment by HarshitaKalani** [comment]
```fortran
program temp
#if (defined __flang__ && __flang_major__ <= 19)
integer,parameter :: x = 0
#else
integer,parameter :: y = 0
#endif
end program
```
```console
$ gfortran a.f90 && ./a.out
a.f90:2:2:

    2 | #if (defined __flang__ && __flang_major__ <= 19)
      |  1
Warning: Illegal preprocessor directive
a.f90:4:2:

    4 | #else
      |  1
Warning: Illegal preprocessor directive
a.f90:6:2:

    6 | #endif
      |  1
Warning: Illegal preprocessor directive
$ lfortran a.f90
warning: Unsupported macro
 --> a.f90:2:1
  |
2 | #if (defined __flang__ && __flang_major__ <= 19)
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Ignored

warning: #else ignored
 --> a.f90:4:1
  |
4 | #else
  | ^^^^^^ help: use the '--cpp' command line option to preprocess it

warning: #endif ignored
 --> a.f90:6:1
  |
6 | #endif
  | ^^^^^^^ help: use the '--cpp' command line option to preprocess it


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

It worked fine for me in the main branch (linux ubuntu).

**Comment by jinangshah21** [comment]
We have to use `--cpp`. With it above program gives error.

**Comment by HarshitaKalani** [comment]
I see. I can now reproduce the error. Thanks!
