### ISSUE TITLE
Passing ArraySection of 2D array in function generates error

### ISSUE THREAD

**Issue by jinangshah21** [lfortran/lfortran#5121]
Towards #4397 

MRE :
```fortran
module my_module
  implicit none
contains
  function func(x) result(y)
    integer, intent(in) :: x(:)
    integer :: y(size(x))
    y = x  
  end function func
end module my_module

program main
  use my_module
  implicit none
  integer :: x(2)
  integer :: y(2, 3)
  y = reshape([6, 3, 8, 5, 2, 7], shape(y))
  x = func(y(:,1)) !! issue in this assignment
end program main
```

LFortran error : 
```
    b.visit_TranslationUnit(ast);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 146, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4884, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4841, in void LCompilers::LFortran::AST::visit_ast_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::ast_t const&, LCompilers::LFortran::BodyVisitor&)
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4887, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4474, in void LCompilers::LFortran::AST::visit_mod_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::mod_t const&, LCompilers::LFortran::BodyVisitor&)
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1598, in LCompilers::LFortran::BodyVisitor::visit_Program(LCompilers::LFortran::AST::Program_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 117, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4930, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4576, in void LCompilers::LFortran::AST::visit_stmt_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::stmt_t const&, LCompilers::LFortran::BodyVisitor&)
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2390, in LCompilers::LFortran::BodyVisitor::visit_Assignment(LCompilers::LFortran::AST::Assignment_t const&)
    this->visit_expr(*x.m_value);
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4982, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_expr(LCompilers::LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4639, in void LCompilers::LFortran::AST::visit_expr_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::expr_t const&, LCompilers::LFortran::BodyVisitor&)
    case exprType::FuncCallOrArray: { v.visit_FuncCallOrArray((const FuncCallOrArray_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 7161, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_FuncCallOrArray(LCompilers::LFortran::AST::FuncCallOrArray_t const&)
    switch (f2->type) {
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4973, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_FunctionCallWithASTNode(LCompilers::LFortran::AST::FuncCallOrArray_t const&, LCompilers::ASR::symbol_t*, LCompilers::Vec<LCompilers::ASR::call_arg_t>&, bool)
    } else {
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4890, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_Function(LCompilers::Location const&, LCompilers::Vec<LCompilers::ASR::call_arg_t>&, LCompilers::ASR::symbol_t*)
    if (ASR::is_a<ASR::ExternalSymbol_t>(*v)) {
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4258, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::handle_return_type(LCompilers::ASR::ttype_t*, LCompilers::Location const&, LCompilers::Vec<LCompilers::ASR::call_arg_t>&, LCompilers::ASR::Function_t*)
    return ASRUtils::make_Array_t_util(
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4212, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::fix_exprs_ttype_t(std::vector<LCompilers::ASR::expr_t*, std::allocator<LCompilers::ASR::expr_t*> >&, LCompilers::Vec<LCompilers::ASR::call_arg_t>&, LCompilers::ASR::Function_t*)
    }
  File "/mnt/c/lfortran/src/libasr/asr.h", line 48375, in LCompilers::ASR::BaseExprReplacer<LCompilers::ASRUtils::ReplaceArgVisitor>::replace_expr(LCompilers::ASR::expr_t*)
    self().replace_ArraySize(down_cast<ASR::ArraySize_t>(x));
  File "/mnt/c/lfortran/src/libasr/asr_utils.h", line 3886, in LCompilers::ASRUtils::ReplaceArgVisitor::replace_ArraySize(LCompilers::ASR::ArraySize_t*) 
    *current_expr = ASRUtils::EXPR(ASRUtils::make_ArraySize_t_util(
  File "/mnt/c/lfortran/src/libasr/asr_utils.h", line 2373, in LCompilers::ASRUtils::make_ArraySize_t_util(Allocator&, LCompilers::Location const&, LCompilers::ASR::expr_t*, LCompilers::ASR::expr_t*, LCompilers::ASR::ttype_t*, LCompilers::ASR::expr_t*, bool)
    start = CastingUtil::perform_casting(start, a_type, al, a_loc);
  File "/mnt/c/lfortran/src/libasr/casting_utils.cpp", line 117, in LCompilers::CastingUtil::perform_casting(LCompilers::ASR::expr_t*, LCompilers::ASR::ttype_t*, Allocator&, LCompilers::Location const&)
    ASR::ttype_t* src = ASRUtils::expr_type(expr);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_utils.h", line 298, in LCompilers::ASRUtils::expr_type(LCompilers::ASR::expr_t const*)
    return ASR::expr_type0(f);
AssertFailed: f != nullptr
```

It works with GFortran.

**Comment by kmr-srbh** [comment]
Thanks for this! Following the stacktrace, I think we can minimize the MRE to:

```fortran
program main
   implicit none
   integer :: x(2)
   integer :: y(2, 3)
   y = reshape([6, 3, 8, 5, 2, 7], shape(y))
   print *, size(y(:, 1))
end program main
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2670, in main
    } catch(const LCompilers::LCompilersException &e) {
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2613, in main_app(int, char**)
    compiler_options, lfortran_pass_manager);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 1001, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    std::cerr << diagnostics.render(lm, compiler_options);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/fortran_evaluator.cpp", line 270, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/fortran_evaluator.cpp", line 292, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 103, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    instantiate_types, instantiate_symbols, entry_functions, entry_function_arguments_mapping, data_structure);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3892, in LCompilers::LFortran::body_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::ASR::asr_t*, LCompilers::CompilerOptions&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompilers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::allocator<int> > > > >&, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> >&)
    b.visit_TranslationUnit(ast);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 146, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4884, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4841, in void LCompilers::LFortran::AST::visit_ast_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::ast_t const&, LCompilers::LFortran::BodyVisitor&)
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4887, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4474, in void LCompilers::LFortran::AST::visit_mod_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::mod_t const&, LCompilers::LFortran::BodyVisitor&)
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1598, in LCompilers::LFortran::BodyVisitor::visit_Program(LCompilers::LFortran::AST::Program_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 117, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4930, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4601, in void LCompilers::LFortran::AST::visit_stmt_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::stmt_t const&, LCompilers::LFortran::BodyVisitor&)
    case stmtType::Print: { v.visit_Print((const Print_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3169, in LCompilers::LFortran::BodyVisitor::visit_Print(LCompilers::LFortran::AST::Print_t const&)
    visit_expr(*x.m_values[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4982, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_expr(LCompilers::LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4639, in void LCompilers::LFortran::AST::visit_expr_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::expr_t const&, LCompilers::LFortran::BodyVisitor&)
    case exprType::FuncCallOrArray: { v.visit_FuncCallOrArray((const FuncCallOrArray_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 6876, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_FuncCallOrArray(LCompilers::LFortran::AST::FuncCallOrArray_t const&)
    v = intrinsic_as_node(x, is_function);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 6103, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::intrinsic_as_node(LCompilers::LFortran::AST::FuncCallOrArray_t const&, bool&)
    tmp = create_ArraySize(x);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5390, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_ArraySize(LCompilers::LFortran::AST::FuncCallOrArray_t const&)
    return ASRUtils::make_ArraySize_t_util(al, x.base.base.loc, v_Var, dim, type, size_compiletime, false);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/asr_utils.h", line 2399, in LCompilers::ASRUtils::make_ArraySize_t_util(Allocator&, LCompilers::Location const&, LCompilers::ASR::expr_t*, LCompilers::ASR::expr_t*, LCompilers::ASR::ttype_t*, LCompilers::ASR::expr_t*, bool)
    start = CastingUtil::perform_casting(start, a_type, al, a_loc);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/casting_utils.cpp", line 117, in LCompilers::CastingUtil::perform_casting(LCompilers::ASR::expr_t*, LCompilers::ASR::ttype_t*, Allocator&, LCompilers::Location const&)
    ASR::ttype_t* src = ASRUtils::expr_type(expr);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr_utils.h", line 312, in LCompilers::ASRUtils::expr_type(LCompilers::ASR::expr_t const*)
    return ASR::expr_type0(f);
AssertFailed: f != nullptr
```

**Comment by Pranavchiku** [comment]
```diff
diff --git a/src/libasr/asr_utils.h b/src/libasr/asr_utils.h
index 9609300dc..61b88b48c 100644
--- a/src/libasr/asr_utils.h
+++ b/src/libasr/asr_utils.h
@@ -2396,6 +2396,9 @@ static inline ASR::asr_t* make_ArraySize_t_util(
                 ASR::expr_t* start = array_section_t->m_args[i].m_left;
                 ASR::expr_t* end = array_section_t->m_args[i].m_right;
                 ASR::expr_t* d = array_section_t->m_args[i].m_step;
+                if ( start == nullptr || d == nullptr || end == nullptr ) {
+                    continue;
+                }
                 start = CastingUtil::perform_casting(start, a_type, al, a_loc);
                 end = CastingUtil::perform_casting(end, a_type, al, a_loc);
                 d = CastingUtil::perform_casting(d, a_type, al, a_loc);
```
