### ISSUE TITLE
(PRIMA) Error while using module which contains procedure(external_subroutine)

### ISSUE THREAD

**Issue by jinangshah21** [lfortran/lfortran#5142]
Towards #4397 

**file 1** : 
```fortran
module temp
contains
    subroutine OBJCON()
    end subroutine OBJCON
end module temp

module evaluate_mod
contains
subroutine evaluate(calcfc)
    use temp
    implicit none
    procedure(OBJCON) :: calcfc 
end subroutine evaluate
end module evaluate_mod
```
**file 2** : 
```fortran
program initialize
use, non_intrinsic :: evaluate_mod
end program initialize
```

**LFortran Error** : 
```
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/mnt/c/lfortran/src/bin/lfortran", in _start
  File "/build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c", line 308, in __libc_start_main
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2669, in main
    return main_app(argc, argv);
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2612, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 1000, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    result = fe.get_asr2(input, lm, diagnostics);
  File "/mnt/c/lfortran/src/lfortran/fortran_evaluator.cpp", line 270, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/mnt/c/lfortran/src/lfortran/fortran_evaluator.cpp", line 292, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 73, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    instantiate_types, instantiate_symbols, entry_functions, entry_function_arguments_mapping, data_structure);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 3499, in LCompilers::LFortran::symbol_table_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, LCompilers::CompilerOptions&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompilers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::allocator<int> > > > >&, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> >&)
    v.visit_TranslationUnit(ast);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 120, in LCompilers::LFortran::SymbolTableVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4884, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4841, in void LCompilers::LFortran::AST::visit_ast_t<LCompilers::LFortran::SymbolTableVisitor>(LCompilers::LFortran::AST::ast_t const&, LCompilers::LFortran::SymbolTableVisitor&)
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4887, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4474, in void LCompilers::LFortran::AST::visit_mod_t<LCompilers::LFortran::SymbolTableVisitor>(LCompilers::LFortran::AST::mod_t const&, LCompilers::LFortran::SymbolTableVisitor&)
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 520, in LCompilers::LFortran::SymbolTableVisitor::visit_Program(LCompilers::LFortran::AST::Program_t const&)
    visit_unit_decl1(*x.m_use[i]);
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4896, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_unit_decl1(LCompilers::LFortran::AST::unit_decl1_t const&)
    void visit_unit_decl1(const unit_decl1_t &b) { visit_unit_decl1_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4492, in void LCompilers::LFortran::AST::visit_unit_decl1_t<LCompilers::LFortran::SymbolTableVisitor>(LCompilers::LFortran::AST::unit_decl1_t const&, LCompilers::LFortran::SymbolTableVisitor&)
    case unit_decl1Type::Use: { v.visit_Use((const Use_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 2607, in LCompilers::LFortran::SymbolTableVisitor::visit_Use(LCompilers::LFortran::AST::Use_t const&)
    t = (ASR::symbol_t*)(ASRUtils::load_module(al, tu_symtab,
  File "/mnt/c/lfortran/src/libasr/asr_utils.cpp", line 308, in LCompilers::ASRUtils::load_module(Allocator&, LCompilers::SymbolTable*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::Location const&, bool, LCompilers::PassOptions&, bool, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::Location const&)>)
    ASR::TranslationUnit_t *mod1 = find_and_load_module(al, module_name,
  File "/mnt/c/lfortran/src/libasr/asr_utils.cpp", line 457, in LCompilers::ASRUtils::find_and_load_module(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::SymbolTable&, bool, LCompilers::PassOptions&)
    ASR::TranslationUnit_t *asr = load_modfile(al, modfile, false, symtab);
  File "/mnt/c/lfortran/src/libasr/modfile.cpp", line 93, in LCompilers::load_modfile(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::SymbolTable&)
    ASR::asr_t *asr = deserialize_asr(al, asr_binary, load_symtab_id, symtab);
  File "/mnt/c/lfortran/src/libasr/serialization.cpp", line 414, in LCompilers::deserialize_asr(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::SymbolTable&)
    return deserialize_asr(al, s, load_symtab_id);
  File "/mnt/c/lfortran/src/libasr/serialization.cpp", line 420, in LCompilers::deserialize_asr(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
    ASR::asr_t *node = v.deserialize_node();
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 35906, in LCompilers::ASR::DeserializationBaseVisitor<LCompilers::ASRDeserializationVisitor>::deserialize_node()
    case (ASR::asrType::unit) : return self().deserialize_unit();
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 35952, in LCompilers::ASR::DeserializationBaseVisitor<LCompilers::ASRDeserializationVisitor>::deserialize_unit()
    case (ASR::unitType::TranslationUnit) : return self().deserialize_TranslationUnit();
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 35936, in LCompilers::ASR::DeserializationBaseVisitor<LCompilers::ASRDeserializationVisitor>::deserialize_TranslationUnit()
    symbol_t *sym = down_cast<symbol_t>(deserialize_symbol());
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 36555, in LCompilers::ASR::DeserializationBaseVisitor<LCompilers::ASRDeserializationVisitor>::deserialize_symbol()
    case (ASR::symbolType::Module) : return self().deserialize_Module();
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 36010, in LCompilers::ASR::DeserializationBaseVisitor<LCompilers::ASRDeserializationVisitor>::deserialize_Module()
    symbol_t *sym = down_cast<symbol_t>(deserialize_symbol());
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 36556, in LCompilers::ASR::DeserializationBaseVisitor<LCompilers::ASRDeserializationVisitor>::deserialize_symbol()
    case (ASR::symbolType::Function) : return self().deserialize_Function();
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 36044, in LCompilers::ASR::DeserializationBaseVisitor<LCompilers::ASRDeserializationVisitor>::deserialize_Function()
    symbol_t *sym = down_cast<symbol_t>(deserialize_symbol());
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 36563, in LCompilers::ASR::DeserializationBaseVisitor<LCompilers::ASRDeserializationVisitor>::deserialize_symbol()
    case (ASR::symbolType::Variable) : return self().deserialize_Variable();
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 36354, in LCompilers::ASR::DeserializationBaseVisitor<LCompilers::ASRDeserializationVisitor>::deserialize_Variable()
    m_type_declaration = self().read_symbol();
AssertFailed: id_symtab_map.find(symtab_id) != id_symtab_map.end()
```

It works with GFortran.

**Some things I noticed with LFortran**: 
1) If we keep both code in one file it works.
2) If we remove Procedure(OBJCON) then it works. 
3) If I keep OBJCON subroutine in evalute_mod module itself then it works.

**Comment by jinangshah21** [comment]
Consider below snippet from` asr.h` : 
```cpp
size_t n = self().read_int64();
            for (size_t i=0; i<n; i++) {
                std::string name = self().read_string();
                symbol_t *sym = down_cast<symbol_t>(deserialize_symbol());
                self().symtab_insert_symbol(*m_symtab, name, sym);
         }
```
this is inside `deserialize_function()`. So when we are deserializing `evaluate` subroutine from `evaluate_mod`. Above loop deserialize `calcfc` first, So therefore `OBJCON` is not `id_symtab_map`. But when we deserialize `calcfc` we need `OBJCON` because `calcfc` is of `OBJCON` type. So this is causing this error.

I am not sure how to solve this.

**Comment by certik** [comment]
Here is how to solve this:
* OBJCON must be an ExternalSymbol inside `evaluate` function table. So it will get deserialized correctly and correctly connected later.
* The bug might be that OBJCON is not an ExternalSymbol, but rather pointing to the other module directly, which indeed cannot work and must fail in deserialize.

So this should be simple to fix, most likely in AST->ASR the OBJCON is used incorrectly.

**Comment by jinangshah21** [comment]
evaluate:
                                (Function
                                    (SymbolTable
                                        5
                                        {
                                            calcfc:
                                                (Variable
                                                    5
                                                    calcfc
                                                    []
                                                    Unspecified
                                                    ()
                                                    ()
                                                    Default
                                                    (FunctionType
                                                        []
                                                        ()
                                                        Source
                                                        Implementation
                                                        ()
                                                        .false.
                                                        .false.
                                                        .false.
                                                        .false.
                                                        .false.
                                                        []
                                                        .false.
                                                    )
                                                    2 objcon
                                                    Source
                                                    Public
                                                    Required
                                                    .false.
                                                ),
                                            objcon:
                                                (ExternalSymbol
                                                    5
                                                    objcon
                                                    2 objcon
                                                    temp
                                                    []
                                                    objcon
                                                    Public
                                                )
                                        })
                                    evaluate
             
In ASR, `evaluate` symboltable already stores OBJCON as ExternalSymbol.

**Comment by jinangshah21** [comment]
Here Issue is we are visiting modules after deserialization, so first deserialization is for `evaluate_mod` in which OBJCON is `m_type_declaration` for variable calcfc so OBJCON is not discovered yet, that causes error.
One thing we can do is we can assign empty SymbolTable for OBJCON in `id_symtab_map`, then we must handle in ASR.
Please give suggestion on this.

**Comment by certik** [comment]
`evaluate_mod` must have everything it needs, including the FunctionType. So you deserialize and it works. It roughly is correct, but we might need to meet to see what exactly breaks. We might need to redesign how procedure is handled perhaps.

**Comment by jinangshah21** [comment]
File 1 ASR : 
```
(TranslationUnit
    (SymbolTable
        1
        {
            evaluate_mod:
                (Module
                    (SymbolTable
                        4
                        {
                            evaluate:
                                (Function
                                    (SymbolTable
                                        5
                                        {
                                            calcfc:
                                                (Variable
                                                    5
                                                    calcfc
                                                    []
                                                    Unspecified
                                                    ()
                                                    ()
                                                    Default
                                                    (FunctionType
                                                        []
                                                        ()
                                                        Source
                                                        Implementation
                                                        ()
                                                        .false.
                                                        .false.
                                                        .false.
                                                        .false.
                                                        .false.
                                                        []
                                                        .false.
                                                    )
                                                    2 objcon
                                                    Source
                                                    Public
                                                    Required
                                                    .false.
                                                ),
                                            objcon:
                                                (ExternalSymbol
                                                    5
                                                    objcon
                                                    2 objcon
                                                    temp
                                                    []
                                                    objcon
                                                    Public
                                                )
                                        })
                                    evaluate
                                    (FunctionType
                                        [(FunctionType
                                            []
                                            ()
                                            Source
                                            Implementation
                                            ()
                                            .false.
                                            .false.
                                            .false.
                                            .false.
                                            .false.
                                            []
                                            .false.
                                        )]
                                        ()
                                        Source
                                        Implementation
                                        ()
                                        .false.
                                        .false.
                                        .false.
                                        .false.
                                        .false.
                                        []
                                        .false.
                                    )
                                    []
                                    [(Var 5 calcfc)]
                                    []
                                    ()
                                    Public
                                    .false.
                                    .false.
                                    ()
                                )
                        })
                    evaluate_mod
                    [temp]
                    .false.
                    .false.
                ),
            temp:
                (Module
                    (SymbolTable
                        2
                        {
                            objcon:
                                (Function
                                    (SymbolTable
                                        3
                                        {

                                        })
                                    objcon
                                    (FunctionType
                                        []
                                        ()
                                        Source
                                        Implementation
                                        ()
                                        .false.
                                        .false.
                                        .false.
                                        .false.
                                        .false.
                                        []
                                        .false.
                                    )
                                    []
                                    []
                                    []
                                    ()
                                    Public
                                    .false.
                                    .false.
                                    ()
                                )
                        })
                    temp
                    []
                    .false.
                    .false.
                )
        })
    []
)
```
