### ISSUE TITLE
unnecessary cast node

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#5243]
Towards https://github.com/lfortran/lfortran/issues/4703

```fortran
subroutine lu(L, U)
    real, intent(out), allocatable :: L(:,:), U(:,:)
    integer :: i, j

    allocate(L(5,5), U(5,5))
    print *, dot_product(L(4,1:3), U(1:3,4))
end subroutine
```

```console
% lfortran a.f90 --show-llvm
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2673, in main
    return main_app(argc, argv);
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2515, in main_app(int, char**)
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 941, in (anonymous namespace)::emit_llvm(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::PassManager&, LCompilers::CompilerOptions&)
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 309, in LCompilers::FortranEvaluator::get_llvm(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&)
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 330, in LCompilers::FortranEvaluator::get_llvm2(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&)
    Result<std::unique_ptr<LLVMModule>> res = get_llvm3(*asr.result, pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 375, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
    = asr_to_llvm(asr, diagnostics,
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10317, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 401, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 178, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 2149, in LCompilers::pass_replace_array_op(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    v.visit_TranslationUnit(unit);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 1730, in LCompilers::ArrayOpVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*item.second);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5189, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayOpVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 4902, in void LCompilers::ASR::visit_symbol_t<LCompilers::ArrayOpVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ArrayOpVisitor&)
    case symbolType::Function: { v.visit_Function((const Function_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 49621, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayOpVisitor>::visit_Function(LCompilers::ASR::Function_t const&)
    self().transform_stmts(xx.m_body, xx.n_body);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 1694, in LCompilers::ArrayOpVisitor::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    visit_stmt(*m_body[i]);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5206, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayOpVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 4932, in void LCompilers::ASR::visit_stmt_t<LCompilers::ArrayOpVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ArrayOpVisitor&)
    case stmtType::DoLoop: { v.visit_DoLoop((const DoLoop_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 49893, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayOpVisitor>::visit_DoLoop(LCompilers::ASR::DoLoop_t const&)
    self().transform_stmts(xx.m_body, xx.n_body);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 1694, in LCompilers::ArrayOpVisitor::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    visit_stmt(*m_body[i]);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5206, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayOpVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 4926, in void LCompilers::ASR::visit_stmt_t<LCompilers::ArrayOpVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ArrayOpVisitor&)
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 1909, in LCompilers::ArrayOpVisitor::visit_Assignment(LCompilers::ASR::Assignment_t const&)
    visit_AssignmentUtil(x);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 1789, in LCompilers::ArrayOpVisitor::visit_AssignmentUtil(LCompilers::ASR::Assignment_t const&)
    this->visit_expr(*x.m_value);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5254, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayOpVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5002, in void LCompilers::ASR::visit_expr_t<LCompilers::ArrayOpVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ArrayOpVisitor&)
    case exprType::RealBinOp: { v.visit_RealBinOp((const RealBinOp_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 51250, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayOpVisitor>::visit_RealBinOp(LCompilers::ASR::RealBinOp_t const&)
    self().visit_expr(*x.m_right);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5254, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayOpVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5002, in void LCompilers::ASR::visit_expr_t<LCompilers::ArrayOpVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ArrayOpVisitor&)
    case exprType::RealBinOp: { v.visit_RealBinOp((const RealBinOp_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 51250, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayOpVisitor>::visit_RealBinOp(LCompilers::ASR::RealBinOp_t const&)
    self().visit_expr(*x.m_right);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5254, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayOpVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5043, in void LCompilers::ASR::visit_expr_t<LCompilers::ArrayOpVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ArrayOpVisitor&)
    case exprType::ArrayItem: { v.visit_ArrayItem((const ArrayItem_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 52050, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayOpVisitor>::visit_ArrayItem(LCompilers::ASR::ArrayItem_t const&)
    self().call_replacer();
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 1674, in LCompilers::ArrayOpVisitor::call_replacer()
    replacer.replace_expr(*current_expr);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 48858, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceArrayOp>::replace_expr(LCompilers::ASR::expr_t*)
    self().replace_Cast(down_cast<ASR::Cast_t>(x));
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/array_op.cpp", line 1102, in LCompilers::ReplaceArrayOp::replace_Cast(LCompilers::ASR::Cast_t*)
    PassUtils::fix_dimension(x_, tmp_val);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_utils.cpp", line 349, in LCompilers::PassUtils::fix_dimension(LCompilers::ASR::Cast_t*, LCompilers::ASR::expr_t*)
    PassUtils::set_dim_rank(x_type, m_dims, ndims);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_utils.cpp", line 50, in LCompilers::PassUtils::set_dim_rank(LCompilers::ASR::ttype_t*, LCompilers::ASR::dimension_t*&, int&, bool, Allocator*)
    ASRUtils::type_get_past_allocatable(new_type)));
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr_utils.h", line 174, in LCompilers::ASRUtils::type_get_past_allocatable(LCompilers::ASR::ttype_t*)
    if (ASR::is_a<ASR::Allocatable_t>(*f)) {
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x180477583
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by Pranavchiku** [comment]
Closing as fixed via #5244.
