### ISSUE TITLE
random_seed throws segfault

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#5245]
Towards #4703

```fortran
subroutine init_random_seed()
      INTEGER :: i, n, clock
      INTEGER, DIMENSION(:), ALLOCATABLE :: seed

      CALL RANDOM_SEED(size = n)
      ALLOCATE(seed(n))

      CALL SYSTEM_CLOCK(COUNT=clock)

      seed = clock + 37 * (/ (i - 1, i = 1, n) /)
      CALL RANDOM_SEED(put=seed)

      DEALLOCATE(seed)
end subroutine init_random_seed
```

```console
% lfortran c.f90 
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2673, in main
    return main_app(argc, argv);
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2616, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 1001, in (anonymous namespace)::compile_src_to_object_file(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 270, in LCompilers::FortranEvaluator::get_asr2(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 291, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
    auto res = LFortran::ast_to_asr(al, ast, diagnostics, symbol_table,
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 101, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    auto res = body_visitor(al, ast, diagnostics, unit, compiler_options,
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 4008, in LCompilers::LFortran::body_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::ASR::asr_t*, LCompilers::CompilerOptions&, std::__1::map<unsigned long long, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, LCompilers::ASR::ttype_t*, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::__1::less<unsigned long long>, std::__1::allocator<std::__1::pair<unsigned long long const, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, LCompilers::ASR::ttype_t*, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::__1::map<unsigned long long, LCompilers::ASR::symbol_t*, std::__1::less<unsigned long long>, std::__1::allocator<std::__1::pair<unsigned long long const, LCompilers::ASR::symbol_t*> > >&, std::__1::map<unsigned long long, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, std::__1::less<unsigned long long>, std::__1::allocator<std::__1::pair<unsigned long long const, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > > >&, std::__1::map<unsigned int, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, LCompilers::ASR::ttype_t*, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, LCompilers::ASR::ttype_t*, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::__1::map<unsigned int, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, LCompilers::ASR::symbol_t*, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, LCompilers::ASR::symbol_t*, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<LCompilers::LFortran::AST::stmt_t*, std::__1::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<LCompilers::LFortran::AST::stmt_t*, std::__1::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<LCompilers::LFortran::AST::stmt_t*, std::__1::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<LCompilers::LFortran::AST::stmt_t*, std::__1::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<int, std::__1::allocator<int> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<int, std::__1::allocator<int> > > > >&, std::__1::vector<LCompilers::ASR::stmt_t*, std::__1::allocator<LCompilers::ASR::stmt_t*> >&)
    b.visit_TranslationUnit(ast);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 150, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4884, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4842, in void LCompilers::LFortran::AST::visit_ast_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::ast_t const&, LCompilers::LFortran::BodyVisitor&)
    case astType::program_unit: { v.visit_program_unit((const program_unit_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4892, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_program_unit(LCompilers::LFortran::AST::program_unit_t const&)
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4482, in void LCompilers::LFortran::AST::visit_program_unit_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::program_unit_t const&, LCompilers::LFortran::BodyVisitor&)
    case program_unitType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2039, in LCompilers::LFortran::BodyVisitor::visit_Subroutine(LCompilers::LFortran::AST::Subroutine_t const&)
    create_and_replace_structType();
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 3828, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_and_replace_structType()
    v.visit_Function(*f);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr.h", line 5436, in LCompilers::ASR::BaseWalkVisitor<LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_and_replace_structType()::StructTypeVisitor>::visit_Function(LCompilers::ASR::Function_t const&)
    self().visit_stmt(*x.m_body[i]);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr.h", line 5206, in LCompilers::ASR::BaseVisitor<LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_and_replace_structType()::StructTypeVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr.h", line 4953, in void LCompilers::ASR::visit_stmt_t<LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_and_replace_structType()::StructTypeVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::LFortran::BodyVisitor&)
    case stmtType::IntrinsicImpureSubroutine: { v.visit_IntrinsicImpureSubroutine((const IntrinsicImpureSubroutine_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr.h", line 5791, in LCompilers::ASR::BaseWalkVisitor<LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_and_replace_structType()::StructTypeVisitor>::visit_IntrinsicImpureSubroutine(LCompilers::ASR::IntrinsicImpureSubroutine_t const&)
    self().visit_expr(*x.m_args[i]);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr.h", line 5254, in LCompilers::ASR::BaseVisitor<LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_and_replace_structType()::StructTypeVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr.h", line 5254, in LCompilers::ASR::BaseVisitor<LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_and_replace_structType()::StructTypeVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x180477583
Segfault: Signal SIGSEGV (segmentation fault) received
```

@parth121101 @HarshitaKalani would you like to take a look?

**Comment by HarshitaKalani** [comment]
> CALL RANDOM_SEED(put=seed)

Passing optional arguments with keywords is not yet handled for array intrinsics and subroutines. I'll formulate a design and post it in Zulip. We will discuss and that should solve this issue.

**Comment by HarshitaKalani** [comment]
Closing this as fixed in https://github.com/lfortran/lfortran/pull/6250.
