### ISSUE TITLE
enh: fortran backend to support openmp dump

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#5260]
This is much required feature for anyone to understand how openmp pass works and therefore I'll ask @adit4443ya to prioritise it before getting on to implement `collapse` in openmp pass. This will help him to understand how openmp pass works and help streamline development of it.

```fortran
program openmp_05
use omp_lib
integer :: n = 10, i

call omp_set_num_threads(4)

!$omp parallel private(i) shared(n)
!$omp do
do i = 1, n
    print *, "xyz"
    print *, "i = ", i, "from thread = ", omp_get_thread_num()
    if (omp_get_thread_num() > 4) error stop
end do
!$omp end do
!$omp end parallel

print *, "end program"

end program
```

```console
(lf) pranavchiku@pranavchikus-MacBook-Air:~/repos/lfortran(ci-speedup-2) % lfortran a.f90 --dump-all-passes-fortran
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2673, in main
    return main_app(argc, argv);
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2467, in main_app(int, char**)
    dump_all_passes(arg_file, compiler_options);
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 789, in (anonymous namespace)::dump_all_passes(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::CompilerOptions&)
    LCompilers::Result<LCompilers::ASR::TranslationUnit_t*> asr = fe.get_asr2(input, lm, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 270, in LCompilers::FortranEvaluator::get_asr2(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 291, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
    auto res = LFortran::ast_to_asr(al, ast, diagnostics, symbol_table,
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 86, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    LCompilers::Result<std::string> fortran_code = LCompilers::asr_to_fortran(*tu, diagnostics, false, 4);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_fortran.cpp", line 1913, in LCompilers::asr_to_fortran(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, bool, int)
    v.visit_TranslationUnit(asr);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_fortran.cpp", line 275, in LCompilers::ASRToFortranVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5189, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToFortranVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 4901, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToFortranVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToFortranVisitor&)
    case symbolType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_fortran.cpp", line 444, in LCompilers::ASRToFortranVisitor::visit_Module(LCompilers::ASR::Module_t const&)
    visit_symbol(*x.m_symtab->get_symbol(interface_func_name[i]));
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5189, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToFortranVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 4902, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToFortranVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToFortranVisitor&)
    case symbolType::Function: { v.visit_Function((const Function_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_fortran.cpp", line 530, in LCompilers::ASRToFortranVisitor::visit_Function(LCompilers::ASR::Function_t const&)
    visit_symbol(*var_sym);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 5189, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToFortranVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/../libasr/asr.h", line 4909, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToFortranVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToFortranVisitor&)
    case symbolType::Variable: { v.visit_Variable((const Variable_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_fortran.cpp", line 655, in LCompilers::ASRToFortranVisitor::visit_Variable(LCompilers::ASR::Variable_t const&)
    r += get_type(x.m_type);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_fortran.cpp", line 251, in LCompilers::ASRToFortranVisitor::get_type(LCompilers::ASR::ttype_t const*)
    throw LCompilersException("The type `"
LCompilersException: The type `CPtr` is not handled yet
```
cc @certik

**Comment by certik** [comment]
Yes, definitely. Being able to see all passes as Fortran code is invaluable to get most of the high level structure. The only things not represented are physical types, types for each intermediate expression, and other small things: and if those are relevant, one can consult the lisp like output itself which has everything.
