### ISSUE TITLE
(PRIMA) Handle External Function in Where

### ISSUE THREAD

**Issue by jinangshah21** [lfortran/lfortran#5288]
Towards #4397 

**File 1** : 
```fortran
module ispos_mod
implicit none 
private
public :: is_pos
contains
    pure elemental function is_pos(x) result(y)
        implicit none
        real, intent(in) :: x
        logical :: y
        y = (x > 0)
    end function is_pos
end module ispos_mod
```

**File 2** : 
```fortran
program bobyqa_exmp
use, non_intrinsic :: ispos_mod
real :: V(2) = [-1,2]
logical :: W(2) 
where (is_pos(V))
        V = 1
elsewhere
        V = 0
end where
print *, V
end program bobyqa_exmp
```

LFortran Error : 
```console
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/mnt/c/lfortran/src/bin/lfortran", in _start
  File "/build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c", line 308, in __libc_start_main
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2677, in main
    return main_app(argc, argv);
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2619, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 1045, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/mnt/c/lfortran/src/lfortran/fortran_evaluator.cpp", line 377, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10317, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/mnt/c/lfortran/src/libasr/pass/pass_manager.h", line 401, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/mnt/c/lfortran/src/libasr/pass/pass_manager.h", line 178, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/mnt/c/lfortran/src/libasr/pass/where.cpp", line 509, in LCompilers::pass_replace_where(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    v.visit_TranslationUnit(unit);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 42975, in LCompilers::ASR::ASRPassBaseWalkVisitor<LCompilers::WhereVisitor>::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5189, in LCompilers::ASR::BaseVisitor<LCompilers::WhereVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 4900, in void LCompilers::ASR::visit_symbol_t<LCompilers::WhereVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::WhereVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/../libasr/pass/pass_utils.h", line 305, in LCompilers::PassUtils::PassVisitor<LCompilers::WhereVisitor>::visit_Program(LCompilers::ASR::Program_t const&)
    transform_stmts(xx.m_body, xx.n_body);
  File "/mnt/c/lfortran/src/libasr/../libasr/pass/pass_utils.h", line 280, in LCompilers::PassUtils::PassVisitor<LCompilers::WhereVisitor>::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    self().visit_stmt(*m_body[i]);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5206, in LCompilers::ASR::BaseVisitor<LCompilers::WhereVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 4954, in void LCompilers::ASR::visit_stmt_t<LCompilers::WhereVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::WhereVisitor&)
    case stmtType::Where: { v.visit_Where((const Where_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/pass/where.cpp", line 456, in LCompilers::WhereVisitor::visit_Where(LCompilers::ASR::Where_t const&)
    ASR::Function_t* fn = ASR::down_cast<ASR::Function_t>(fc->m_name);
AssertFailed: is_a<T>(*f)
```

Above error can just be solved by doing `symbol_get_past_external` in `ASR::Function_t* fn = ASR::down_cast<ASR::Function_t>(fc->m_name);`. But After that a different Error originates which looks like : 
```console
   case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 979, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5189, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 4900, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToLLVMVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3287, in LCompilers::ASRToLLVMVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5206, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 4926, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5104, in LCompilers::ASRToLLVMVisitor::visit_Assignment(LCompilers::ASR::Assignment_t const&)
    this->visit_expr_wrapper(m_value, true);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5509, in LCompilers::ASRToLLVMVisitor::visit_expr_wrapper(LCompilers::ASR::expr_t*, bool)
    this->visit_expr(*x);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5254, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 4993, in void LCompilers::ASR::visit_expr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ASRToLLVMVisitor&)
    case exprType::IntegerBinOp: { v.visit_IntegerBinOp((const IntegerBinOp_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6490, in LCompilers::ASRToLLVMVisitor::visit_IntegerBinOp(LCompilers::ASR::IntegerBinOp_t const&)
    handle_SU_IntegerBinOp(x, true);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6412, in void LCompilers::ASRToLLVMVisitor::handle_SU_IntegerBinOp<LCompilers::ASR::IntegerBinOp_t>(LCompilers::ASR::IntegerBinOp_t const&, bool)
    this->visit_expr_wrapper(x.m_left, true);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5509, in LCompilers::ASRToLLVMVisitor::visit_expr_wrapper(LCompilers::ASR::expr_t*, bool)
    this->visit_expr(*x);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5254, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5046, in void LCompilers::ASR::visit_expr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ASRToLLVMVisitor&)
    case exprType::ArrayBound: { v.visit_ArrayBound((const ArrayBound_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10105, in LCompilers::ASRToLLVMVisitor::visit_ArrayBound(LCompilers::ASR::ArrayBound_t const&)
    ASR::array_physical_typeType physical_type = ASRUtils::extract_physical_type(x_mv_type);
LCompilersException: Cannot extract the physical type of bool type. 
```

**Comment by Pranavchiku** [comment]
The problem is `__libasr__created__var__1_y` created as a temporary in `where` pass is a scalar and we can't do `ArrayBound` on it, so need to debug `where` pass.

```clojure
                        (ArrayBound
                            (Var 4 __libasr__created__var__1_y)
                            (IntegerConstant 1 (Integer 4) Decimal)
                            (Integer 4)
                            LBound
                            ()
                        )
```

**Comment by Pranavchiku** [comment]
I knew this, see it works with simplifier:

```console
% lfortran a.f90 --experimental-simplifier
-1.00000000e+00    1.00000000e+00
% gfortran a.f90&& ./a.out
  -1.00000000       1.00000000    
```
