### ISSUE TITLE
Error not reported for array with deferred shape

### ISSUE THREAD

**Issue by AnshMehta1** [lfortran/lfortran#5304]
MRE 

GFortan error 
```
(lf) lordansh@LordAnsh:~/dev/lfort1/lfortran$ gfortran try.f90
try.f90:4:15:

    4 | integer :: a(:)
      |               1
Error: Array ‘a’ at (1) cannot have a deferred shape
```

LFortran behaviour

```
Traceback (most recent call last):
  Binary file "/home/lordansh/dev/lfort1/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/lordansh/dev/lfort1/lfortran/src/bin/lfortran.cpp", line 2679, in main
    return main_app(argc, argv);
  File "/home/lordansh/dev/lfort1/lfortran/src/bin/lfortran.cpp", line 2621, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/home/lordansh/dev/lfort1/lfortran/src/bin/lfortran.cpp", line 1045, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/fortran_evaluator.cpp", line 377, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/lordansh/dev/lfort1/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10325, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/lordansh/dev/lfort1/lfortran/src/libasr/../libasr/asr.h", line 5186, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/lordansh/dev/lfort1/lfortran/src/libasr/../libasr/asr.h", line 5162, in void LCompilers::ASR::visit_asr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::asr_t const&, LCompilers::ASRToLLVMVisitor&)
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/lordansh/dev/lfort1/lfortran/src/libasr/../libasr/asr.h", line 5187, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/lordansh/dev/lfort1/lfortran/src/libasr/../libasr/asr.h", line 4892, in void LCompilers::ASR::visit_unit_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::unit_t const&, LCompilers::ASRToLLVMVisitor&)
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/lordansh/dev/lfort1/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 983, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/home/lordansh/dev/lfort1/lfortran/src/libasr/../libasr/asr.h", line 5189, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/lordansh/dev/lfort1/lfortran/src/libasr/../libasr/asr.h", line 4900, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToLLVMVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/lordansh/dev/lfort1/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3275, in LCompilers::ASRToLLVMVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    declare_vars(x);
  File "/home/lordansh/dev/lfort1/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3890, in void LCompilers::ASRToLLVMVisitor::declare_vars<LCompilers::ASR::Program_t>(LCompilers::ASR::Program_t const&, bool)
    process_Variable(var_sym, x, debug_arg_count);
  File "/home/lordansh/dev/lfort1/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3745, in void LCompilers::ASRToLLVMVisitor::process_Variable<LCompilers::ASR::Program_t const>(LCompilers::ASR::symbol_t*, LCompilers::ASR::Program_t const&, unsigned int&)
    fill_array_details_(ptr, type_, m_dims, n_dims,
  File "/home/lordansh/dev/lfort1/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3349, in LCompilers::ASRToLLVMVisitor::fill_array_details_(llvm::Value*, llvm::Type*, LCompilers::ASR::dimension_t*, unsigned long, bool, bool, bool, LCompilers::ASR::ttype_t*, bool)
    fill_array_details(ptr, llvm_data_type, m_dims, n_dims, is_data_only);
  File "/home/lordansh/dev/lfort1/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 444, in LCompilers::ASRToLLVMVisitor::fill_array_details(llvm::Value*, llvm::Type*, LCompilers::ASR::dimension_t*, int, bool, bool)
    visit_expr(*(m_dim.m_start));
  File "/home/lordansh/dev/lfort1/lfortran/src/libasr/../libasr/asr.h", line 5254, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/lordansh/dev/lfort1/lfortran/src/libasr/../libasr/asr.h", line 4975, in void LCompilers::ASR::visit_expr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ASRToLLVMVisitor&)
    LCOMPILERS_ASSERT(x.base.type == asrType::expr)
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in <invalid>
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by certik** [comment]
@AnshMehta1 go ahead and post a full reproducible example.
