### ISSUE TITLE
(PRIMA) Handle Generic Procedure in `pass_array_by_data.cpp`

### ISSUE THREAD

**Issue by jinangshah21** [lfortran/lfortran#5327]
Towards #4397 

MRE : 
```fortran
module inf_mod_1
implicit none
private
public::is_finite
interface is_finite
    module procedure is_finite_1
end interface is_finite
contains
subroutine is_finite_1() 
end subroutine is_finite_1
end module inf_mod_1

module infnan_mod_1
use, non_intrinsic :: inf_mod_1, only : is_finite
end module infnan_mod_1


program bobyqa_exmp
contains
subroutine calfun(x)
use, non_intrinsic :: infnan_mod_1, only : is_finite
real, intent(in) :: x(:)
end subroutine calfun
end program bobyqa_exmp
```

LFortran Error : 
```console
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/mnt/c/lfortran/src/bin/lfortran", in _start
  File "/build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c", line 308, in __libc_start_main
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2677, in main
    return main_app(argc, argv);
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2619, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 1045, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/mnt/c/lfortran/src/lfortran/fortran_evaluator.cpp", line 377, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10317, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/mnt/c/lfortran/src/libasr/pass/pass_manager.h", line 401, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/mnt/c/lfortran/src/libasr/pass/pass_manager.h", line 178, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/mnt/c/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 715, in LCompilers::pass_array_by_data(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    v.visit_TranslationUnit(unit);
  File "/mnt/c/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 268, in LCompilers::PassArrayByDataProcedureVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5189, in LCompilers::ASR::BaseVisitor<LCompilers::PassArrayByDataProcedureVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 4900, in void LCompilers::ASR::visit_symbol_t<LCompilers::PassArrayByDataProcedureVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::PassArrayByDataProcedureVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 274, in LCompilers::PassArrayByDataProcedureVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    bfs_visit_SymbolContainingFunctions()
  File "/mnt/c/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 235, in bool LCompilers::PassArrayByDataProcedureVisitor::visit_SymbolContainingFunctions<LCompilers::ASR::Program_t>(LCompilers::ASR::Program_t const&, std::deque<LCompilers::ASR::Function_t*, std::allocator<LCompilers::ASR::Function_t*> >&)
    ASR::symbol_t* sym = insert_new_procedure(subrout, arg_indices);
  File "/mnt/c/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 105, in LCompilers::PassArrayByDataProcedureVisitor::insert_new_procedure(LCompilers::ASR::Function_t*, std::vector<unsigned long, std::allocator<unsigned long> >&)
    symbol_duplicator.duplicate_symbol(item.second, new_symtab);
LCompilersException: Duplicating ASR::symbolType::3 is not supported yet.
```
Works with GFortran

**Comment by jinangshah21** [comment]
Some Observations : 
-->If we remove interface and just keep is_finite as subroutine in inf_mod_1, program works.
-->Issue is caused by x array in calfun
-->If I use is_finite directly from inf_mod_1 in program , it works.

**Comment by jinangshah21** [comment]
Here ASR is : 
```asr
is_finite:
          (GenericProcedure
              6
              is_finite
              [6 is_finite_1@is_finite]
              Public
          ),
      is_finite_1@is_finite:
          (ExternalSymbol
              6
              is_finite_1@is_finite
              2 is_finite_1
              inf_mod_1
              []
              is_finite_1
              Public
          ),
```

But if we remove intermediate module ASR is : 
```asr
is_finite:
 (ExternalSymbol
                      5
                      is_finite
                      2 is_finite
                      inf_mod_1
                      []
                      is_finite
                      Public
                  ),
              is_finite_1@is_finite:
                  (ExternalSymbol
                      5
                      is_finite_1@is_finite
                      2 is_finite_1
                      inf_mod_1
                      []
                      is_finite_1
                      Public
                  ),
```

So I think we should store ExternalSymbol in Symbol table here.

**Comment by certik** [comment]
I remember having lots of issues with bugs like this one when I implemented generic procedures.

I think we could make the `is_finite` be an ExternalSymbol in the main program, however then it will be hard to implement the feature of appending new implementations into the same generic procedure from several modules. 

Consequently, I think I opted out for the design of duplicating the GenericProcedure, and have its contents be ExternalSymbols. That way each module/program can see slightly different GenericProcedure, depending on which modules are imported.

What exactly is the issue with the error and the stacktrace in the symbol duplicator?

**Comment by jinangshah21** [comment]
We currently don't have function to duplicate **GenericProcedure**.

**Comment by certik** [comment]
I am pretty sure we have tests for declaring a generic procuedure in a module and improting it in another module. How do our current tests differ from your MRE above? There is a bug somewhere.

**Comment by jinangshah21** [comment]
Consider Following code : 
```fortran
module inf_mod_1
implicit none
private
public::is_finite
interface is_finite
    module procedure is_finite_1
end interface is_finite
contains
subroutine is_finite_1() 
end subroutine is_finite_1
end module inf_mod_1

module infnan_mod_1
use, non_intrinsic :: inf_mod_1, only : is_finite
end module infnan_mod_1

program bobyqa_exmp
contains
subroutine calfun(x)
use, non_intrinsic :: infnan_mod_1   !!! Here we don't use only
real, intent(in) :: x(:)
end subroutine calfun
end program bobyqa_exmp
```

It is working by just removing `only`  in calfun from MRE. And then ASR is as below : 

```fortran
is_finite:
            (ExternalSymbol
            6
            is_finite
            2 is_finite
            inf_mod_1
            []
            is_finite
            Public
            ),
            is_finite_1:
            (ExternalSymbol
            6
            is_finite_1
            2 is_finite_1
            inf_mod_1
            []
            is_finite_1
            Public
            ),
```
So it is storing `is_finite` as ExternalSymbol only.

**Comment by jinangshah21** [comment]
So I guess bug is in `only` of `visit_Use`.
I will try this after sometime.

**Comment by certik** [comment]
Now imagine the `infnan_mod_1` module adds another specific implementation `is_finite_1` to the same generic procedure `is_finite`. If it is an ExternalSymbol, how would it add it in? I think the GenericProcedure has to be duplicated. It thought we already do it.

**Comment by jinangshah21** [comment]
> Now imagine the `infnan_mod_1` module adds another specific implementation `is_finite_1` to the same generic procedure `is_finite`. If it is an ExternalSymbol, how would it add it in? I think the GenericProcedure has to be duplicated. It thought we already do it.

Yes I Understand.

**Comment by jinangshah21** [comment]
> Now imagine the `infnan_mod_1` module adds another specific implementation `is_finite_1` to the same generic procedure `is_finite`. If it is an ExternalSymbol, how would it add it in? I think the GenericProcedure has to be duplicated. It thought we already do it.

Opened #5366 for this.

**Comment by assem2002** [comment]
> Now imagine the `infnan_mod_1` module adds another specific implementation `is_finite_1` to the same generic procedure `is_finite`. If it is an ExternalSymbol, how would it add it in? I think the GenericProcedure has to be duplicated. It thought we already do it.

I think we do have this feature. This example works with LFortran :
```Fortran
module inf_mod_1
 implicit none
 private
 public::is_finite
 interface is_finite
     module procedure is_finite_1
 end interface is_finite
 contains
 subroutine is_finite_1() 
    print *, "is_finite_1 called"
 end subroutine is_finite_1
 end module inf_mod_1
 
 module infnan_mod_1
 use, non_intrinsic :: inf_mod_1, only : is_finite
 interface is_finite
    module procedure fff
 end interface
 contains
 subroutine fff(x)
    integer :: x
    print *, x
 end subroutine fff
 end module infnan_mod_1
 
 
 program bobyqa_exmp
    call calfun()
    contains
    subroutine calfun()
       use, non_intrinsic :: infnan_mod_1, only : is_finite
       call is_finite()
       call is_finite(2)
    end subroutine calfun
 end program bobyqa_exmp
```  
but this still issue [#5366 ](https://github.com/lfortran/lfortran/issues/5366)still has a valid bug we have to fix.

**Comment by assem2002** [comment]
Extending in program fails :
```fortran
module inf_mod_1
    implicit none
    private
    public::is_finite
    interface is_finite
        module procedure is_finite_1
    end interface is_finite
    contains
    subroutine is_finite_1() 
       print *, "is_finite_1 called"
    end subroutine is_finite_1
    end module inf_mod_1
    
    module infnan_mod_1
    use, non_intrinsic :: inf_mod_1
    interface is_finite
       module procedure fff
    end interface
    contains
    subroutine fff(x)
       integer :: x
       print *, x
    end subroutine fff
end module infnan_mod_1


program bobyqa_exmp
    use, non_intrinsic :: infnan_mod_1
    interface is_finite
         procedure fffm
    end interface
    call calfun()
        contains
    subroutine fffm(x)
        real :: x
        print *, x
    end subroutine fffm
    subroutine calfun()
        call is_finite()
        call is_finite(2)
        call is_finite(2.2)
    end subroutine calfun
    end program bobyqa_exmp
```
If we import the genericProcedure `is_finite` in program specifically :
- with `only` we import `is_finite` as duplicated `genericProcedure` and and interface extension works
- without `only` we import `is_finite` as ExternalSymbol. so interface extension does no effect on it.
