### ISSUE TITLE
(PRIMA) Intrinsic function call in args of function causes error in Arraysize

### ISSUE THREAD

**Issue by jinangshah21** [lfortran/lfortran#5334]
Towards #4397

MRE : 
```fortran
program main

contains

subroutine trans(A)
real(8), intent(in) :: A(:,:)
print *, matprod(transpose(A))
end subroutine

function matprod(x) result(k)
real(8),intent(in) :: x(:,:)
real(8) :: k(size(x,1))
end function

end program 
```

LFortran Error : 
```console
LCOMPILERS_ASSERT failed: /mnt/c/lfortran/src/libasr/asr_utils.h
function make_ArraySize_t_util(), line number 2625 at
ASR::is_a<ASR::Var_t>(*a_v) || ASR::is_a<ASR::StructInstanceMember_t>(*a_v) || ASR::is_a<ASR::FunctionParam_t>(*a_v)
ERROR MESSAGE:
Found ASR::exprType::5
Traceback (most recent call last):
  Binary file "/mnt/c/lfortran/src/bin/lfortran", in _start
  File "/build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c", line 308, in __libc_start_main
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2679, in main
    return main_app(argc, argv);
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2621, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 1002, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    result = fe.get_asr2(input, lm, diagnostics);
  File "/mnt/c/lfortran/src/lfortran/fortran_evaluator.cpp", line 270, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/mnt/c/lfortran/src/lfortran/fortran_evaluator.cpp", line 292, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 103, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    instantiate_types, instantiate_symbols, entry_functions, entry_function_arguments_mapping, data_structure);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 4056, in LCompilers::LFortran::body_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::ASR::asr_t*, LCompilers::CompilerOptions&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompilers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::allocator<int> > > > >&, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> >&)
    b.visit_TranslationUnit(ast);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 166, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4884, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4841, in void LCompilers::LFortran::AST::visit_ast_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::ast_t const&, LCompilers::LFortran::BodyVisitor&)
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4887, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4474, in void LCompilers::LFortran::AST::visit_mod_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::mod_t const&, LCompilers::LFortran::BodyVisitor&)
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1647, in LCompilers::LFortran::BodyVisitor::visit_Program(LCompilers::LFortran::AST::Program_t const&)
    visit_program_unit(*x.m_contains[i]);
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4892, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_program_unit(LCompilers::LFortran::AST::program_unit_t const&)
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4482, in void LCompilers::LFortran::AST::visit_program_unit_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::program_unit_t const&, LCompilers::LFortran::BodyVisitor&)
    case program_unitType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2049, in LCompilers::LFortran::BodyVisitor::visit_Subroutine(LCompilers::LFortran::AST::Subroutine_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 121, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4930, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4601, in void LCompilers::LFortran::AST::visit_stmt_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::stmt_t const&, LCompilers::LFortran::BodyVisitor&)
    case stmtType::Print: { v.visit_Print((const Print_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3279, in LCompilers::LFortran::BodyVisitor::visit_Print(LCompilers::LFortran::AST::Print_t const&)
    this->visit_expr(*x.m_values[i]);
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4982, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_expr(LCompilers::LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4639, in void LCompilers::LFortran::AST::visit_expr_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::expr_t const&, LCompilers::LFortran::BodyVisitor&)
    case exprType::FuncCallOrArray: { v.visit_FuncCallOrArray((const FuncCallOrArray_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 7330, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_FuncCallOrArray(LCompilers::LFortran::AST::FuncCallOrArray_t const&)
    tmp = create_FunctionCallWithASTNode(x, v, args);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5086, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_FunctionCallWithASTNode(LCompilers::LFortran::AST::FuncCallOrArray_t const&, LCompilers::ASR::symbol_t*, LCompilers::Vec<LCompilers::ASR::call_arg_t>&, bool)
    return create_Function(x.base.base.loc, args, v);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5003, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_Function(LCompilers::Location const&, LCompilers::Vec<LCompilers::ASR::call_arg_t>&, LCompilers::ASR::symbol_t*)
    return_type = handle_return_type(return_type, loc, args, func);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4374, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::handle_return_type(LCompilers::ASR::ttype_t*, LCompilers::Location const&, LCompilers::Vec<LCompilers::ASR::call_arg_t>&, LCompilers::ASR::Function_t*)
    return ASRUtils::make_Array_t_util(
  File "/mnt/c/lfortran/src/libasr/asr_utils.h", line 2647, in LCompilers::ASRUtils::make_Array_t_util(Allocator&, LCompilers::Location const&, LCompilers::ASR::ttype_t*, LCompilers::ASR::dimension_t*, unsigned long, LCompilers::ASR::abiType, bool, LCompilers::ASR::array_physical_typeType, bool, bool)    
    m_dims[i].m_length = ASRUtils::EXPR(ASRUtils::make_ArraySize_t_util(
  File "/mnt/c/lfortran/src/libasr/asr_utils.h", line 2625, in LCompilers::ASRUtils::make_ArraySize_t_util(Allocator&, LCompilers::Location const&, LCompilers::ASR::expr_t*, LCompilers::ASR::expr_t*, LCompilers::ASR::ttype_t*, LCompilers::ASR::expr_t*, bool)
    LCOMPILERS_ASSERT_MSG(
  File "/build/glibc-LcI20x/glibc-2.31/stdlib/abort.c", line 79, in abort
  File "/build/glibc-LcI20x/glibc-2.31/signal/../sysdeps/unix/sysv/linux/internal-signals.h", line 86, in raise
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in <invalid>
Abort: Signal SIGABRT (abort) received

Aborted (core dumped)
```

I was working before a week, today I just updated my branch and got this error, so likely this is caused because of some recent PR.

**Comment by jinangshah21** [comment]
Here `real(8) :: k(size(x,1))` is considering x as`**IntrinsicArrayFunction**, which is causing error.

**Comment by jinangshah21** [comment]
Same Issue occurs with Arraysection `pqlag = matprod(zmat, zmat(knew, :))`.

**Comment by Pranavchiku** [comment]
Yes, that is correct explanation. With the following diff it segfaults:

```diff
diff --git a/src/libasr/asr_utils.h b/src/libasr/asr_utils.h
index 0265a6df6..bc012c33d 100644
--- a/src/libasr/asr_utils.h
+++ b/src/libasr/asr_utils.h
@@ -2586,6 +2586,15 @@ static inline ASR::asr_t* make_ArraySize_t_util(
                 break;
             }
         }
+    } else if ( ASR::is_a<ASR::IntrinsicArrayFunction_t>(*a_v) && for_type ) {
+        std::cout<<"IntrinsicArrayFunction_t"<<std::endl;
+        ASR::IntrinsicArrayFunction_t* af = ASR::down_cast<ASR::IntrinsicArrayFunction_t>(a_v);
+        for ( size_t i = 0; i < af->n_args; i++ ) {
+            if ( ASRUtils::is_array(ASRUtils::expr_type(af->m_args[i])) ) {
+                a_v = af->m_args[i];
+                break;
+            }
+        }
     } else if( is_binop_expr(a_v) && for_type ) {
         if( ASR::is_a<ASR::Var_t>(*extract_member_from_binop(a_v, 1)) ) {
             return make_ArraySize_t_util(al, a_loc, extract_member_from_binop(a_v, 1), a_dim, a_type, a_value, for_type);
```

**Comment by jinangshah21** [comment]
But it is strange that a week ago it was working well and now it causes error.

**Comment by Pranavchiku** [comment]
This happens. We might have pushed a commit that caused this and we do not test PRIMA yet on CI hence it went unnoticed.

**Comment by jinangshah21** [comment]
```fortran
program main

contains

subroutine trans(A)
real(8), intent(in) :: A(:,:)
integer,parameter :: x = 2
print *, matprod(transpose(A(:, 1:x)))
end subroutine

function matprod(x) result(k)
real(8),intent(in) :: x(:,:)
real(8) :: k(size(x,1))
end function

end program 
```

This is also giving same error with `exprType : 67` which is of ArraySection means `transpose(A(:, 1:x))` is considered as ArraySection in `make_ArraySize_util_t` .

**Comment by jinangshah21** [comment]
I guess IntrinsicArrayFunction check (done in #5346 ) in `make_ArraySize_util_t` should be done before `Arraysection` check

**Comment by gxyd** [comment]
@jinangshah21 , could you please provide in the issue description for how to run the program with LFortran? Any flags that need to be used?

because running the program as: `lfortran test.f90` doesn't cause any error with it.

**Comment by jinangshah21** [comment]
I think #5367 will fix https://github.com/lfortran/lfortran/issues/5334#issuecomment-2468742181

**Comment by Pranavchiku** [comment]
So if we create a full example:

```fortran
program arrays_58

real :: A(2,2) = reshape([1.0,2.0,3.0,4.0], [2,2])
call trans(A)
print *, A
if ( any(abs( A - 12.91 ) > 1e-8) ) error stop 
contains

subroutine trans(A)
real, intent(inout) :: A(:, :)
A = matprod(transpose(A))
end subroutine

function matprod(x) result(k)
real,intent(in) :: x(:,:)
real :: k(size(x, 1), size(x, 2))
k = 12.91
end function

end program
```

This does not work.

**Comment by jinangshah21** [comment]
> So if we create a full example:
> 
> ```fortran
> program arrays_58
> 
> real :: A(2,2) = reshape([1.0,2.0,3.0,4.0], [2,2])
> call trans(A)
> print *, A
> if ( any(abs( A - 12.91 ) > 1e-8) ) error stop 
> contains
> 
> subroutine trans(A)
> real, intent(inout) :: A(:, :)
> A = matprod(transpose(A))
> end subroutine
> 
> function matprod(x) result(k)
> real,intent(in) :: x(:,:)
> real :: k(size(x, 1), size(x, 2))
> k = 12.91
> end function
> 
> end program
> ```
> 
> This does not work.

It is Working for me.
