### ISSUE TITLE
(PRIMA) nested function call in `sum` fails

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#5430]
```fortran
subroutine sub()
real :: gnew(5)
integer :: xbdi(5)
print *, sum(gnew(trueloc(gnew == 0)))
contains
function trueloc(x) result(loc)

logical, intent(in) :: x(:)
integer, allocatable :: loc(:)
end function trueloc
end subroutine
```

```console
 % lfortran a.f90 --show-llvm
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2685
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2528
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 942
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 314
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 336
    diagnostics, lm.files.back().in_filename);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 382
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10366
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 403
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 180
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/intrinsic_function.cpp", line 608
    u.visit_TranslationUnit(unit);
  File "../libasr/asr.h", line 49582
  File "../libasr/asr.h", line 5189
  File "../libasr/asr.h", line 4901
  File "../libasr/asr.h", line 49621
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/intrinsic_function.cpp", line 534
    visit_stmt(*m_body[i]);
  File "../libasr/asr.h", line 5206
  File "../libasr/asr.h", line 5206
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x180477583
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by assem2002** [comment]
I think this expression `gnew(trueloc(gnew == 0))` is related to this issue https://github.com/lfortran/lfortran/pull/5154

**Comment by assem2002** [comment]
Now it's relaying on #5484 :)

**Comment by HarshitaKalani** [comment]
This now works. Closing wrt #5154
