### ISSUE TITLE
Bug : indexing on arrays using array

### ISSUE THREAD

**Issue by assem2002** [lfortran/lfortran#5484]
MRE

```Fortran

program a
    integer :: gnew(5)
    integer :: loc(3)
    integer :: res(3)
    gnew = [10,20,30,40,50]
    loc = [4,5,1]
    print *, loc
    res =  gnew(loc)
    print *, res

end program
```

```console
lfortran: /home/assem/conda_root/envs/lf/include/llvm/IR/IRBuilder.h:1989: llvm::Value* llvm::IRBuilderBase::CreateSExtOrTrunc(llvm::Value*, llvm::Type*, const llvm::Twine&): Assertion `V->getType()->isIntOrIntVectorTy() && DestTy->isIntOrIntVectorTy() && "Can only sign extend/truncate integers!"' failed.
Traceback (most recent call last):
  Binary file "/home/assem/lfortran_test/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/assem/lfortran_test/lfortran/src/bin/lfortran.cpp", line 2685, in main
    return main_app(argc, argv);
  File "/home/assem/lfortran_test/lfortran/src/bin/lfortran.cpp", line 2624, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/home/assem/lfortran_test/lfortran/src/bin/lfortran.cpp", line 1045, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/assem/lfortran_test/lfortran/src/lfortran/fortran_evaluator.cpp", line 382, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10372, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/assem/lfortran_test/lfortran/src/libasr/../libasr/asr.h", line 5186, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/assem/lfortran_test/lfortran/src/libasr/../libasr/asr.h", line 5162, in void LCompilers::ASR::visit_asr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::asr_t const&, LCompilers::ASRToLLVMVisitor&)
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/assem/lfortran_test/lfortran/src/libasr/../libasr/asr.h", line 5187, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/assem/lfortran_test/lfortran/src/libasr/../libasr/asr.h", line 4892, in void LCompilers::ASR::visit_unit_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::unit_t const&, LCompilers::ASRToLLVMVisitor&)
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 988, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/home/assem/lfortran_test/lfortran/src/libasr/../libasr/asr.h", line 5189, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/assem/lfortran_test/lfortran/src/libasr/../libasr/asr.h", line 4900, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToLLVMVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3292, in LCompilers::ASRToLLVMVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/home/assem/lfortran_test/lfortran/src/libasr/../libasr/asr.h", line 5206, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/assem/lfortran_test/lfortran/src/libasr/../libasr/asr.h", line 4955, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::WhileLoop: { v.visit_WhileLoop((const WhileLoop_t &)x); return; }
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6063, in LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)
    create_loop(x.m_name, [=]() {
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 321, in void LCompilers::ASRToLLVMVisitor::create_loop<LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda'(), LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda0'()>(char*, LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda'(), LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda0'())
    loop_body();
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6069, in LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda0'()::operator()() const
    this->visit_stmt(*x.m_body[i]);
  File "/home/assem/lfortran_test/lfortran/src/libasr/../libasr/asr.h", line 5206, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/assem/lfortran_test/lfortran/src/libasr/../libasr/asr.h", line 4926, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5134, in LCompilers::ASRToLLVMVisitor::visit_Assignment(LCompilers::ASR::Assignment_t const&)
    this->visit_expr_wrapper(m_value, true);
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5539, in LCompilers::ASRToLLVMVisitor::visit_expr_wrapper(LCompilers::ASR::expr_t*, bool)
    this->visit_expr(*x);
  File "/home/assem/lfortran_test/lfortran/src/libasr/../libasr/asr.h", line 5254, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/assem/lfortran_test/lfortran/src/libasr/../libasr/asr.h", line 5043, in void LCompilers::ASR::visit_expr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ASRToLLVMVisitor&)
    case exprType::ArrayItem: { v.visit_ArrayItem((const ArrayItem_t &)x); return; }
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2436, in LCompilers::ASRToLLVMVisitor::visit_ArrayItem(LCompilers::ASR::ArrayItem_t const&)
    tmp = arr_descr->get_single_element(type, array, indices, x.n_args,
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 670, in LCompilers::LLVMArrUtils::SimpleCMODescriptor::get_single_element(llvm::Type*, llvm::Value*, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&, int, bool, bool, llvm::Value**, bool, llvm::Type*, bool)
    idx = cmo_convertor_single_element_data_only(llvm_diminfo, m_args, n_args, check_for_bounds, is_unbounded_pointer_to_data);
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 642, in LCompilers::LLVMArrUtils::SimpleCMODescriptor::cmo_convertor_single_element_data_only(llvm::Value**, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&, int, bool, bool)
    curr_llvm_idx = builder->CreateSExtOrTrunc(curr_llvm_idx, llvm::Type::getInt32Ty(context));
  File "/home/assem/conda_root/envs/lf/include/llvm/IR/IRBuilder.h", line 1989, in llvm::IRBuilderBase::CreateSExtOrTrunc(llvm::Value*, llvm::Type*, llvm::Twine const&)
    assert(V->getType()->isIntOrIntVectorTy() &&
  File "./assert/./assert/assert.c", line 101, in __assert_fail
  File "./assert/./assert/assert.c", line 92, in <invalid>
  File "./stdlib/./stdlib/abort.c", line 79, in abort
  File "./signal/../sysdeps/posix/raise.c", line 26, in raise
  File "./nptl/./nptl/pthread_kill.c", line 43, in pthread_kill
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in <invalid>
Abort: Signal SIGABRT (abort) received

Aborted (core dumped)

```

**Comment by kmr-srbh** [comment]
I think this is the issue with `ArrayItem` which was reported in #4420. #5154 fixes the base case of assignment. We just need to port the `result_var` changes from #4446 to make printing work here. @advikkabra could you please take a look?

**Comment by advikkabra** [comment]
Yes, this change is similar to ArraySection. I'll start working on this.

**Comment by assem2002** [comment]
The MRE now works, so we'll close this issue.

**Comment by assem2002** [comment]
The MRE now works, so we'll close this issue.
