### ISSUE TITLE
dwarf_convert.py cannot parse the new format

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#5496]
It emits empty output.

**Comment by certik** [comment]
With #5497, the stacktrace almost works:
```console
$ lfortran -c tests/string1.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/src/bin/lfortran.cpp", line 2686
    LCompilers::print_stack_on_segfault();
  File "/Users/ondrej/repos/lfortran/src/bin/lfortran.cpp", line 2583
    return compile_src_to_object_file(arg_file, outfile, false,
  File "/Users/ondrej/repos/lfortran/src/bin/lfortran.cpp", line 1003
    bool has_error_w_cc = compiler_options.continue_compilation && diagnostics.has_error();
  File "/Users/ondrej/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 275
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/ondrej/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 297
    compiler_options.symtab_only, compiler_options);
  File "/Users/ondrej/repos/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 72
    if (res.ok) {
  File "/Users/ondrej/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 3835
    v.visit_TranslationUnit(ast);
  File "/Users/ondrej/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 132
    visit_ast(*x.m_items[i]);
  File "/Users/ondrej/repos/lfortran/src/lfortran/ast.h", line 4884
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/src/lfortran/ast.h", line 4840
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/src/lfortran/ast.h", line 4887
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/src/lfortran/ast.h", line 4471
    case modType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 517
    visit_ModuleSubmoduleCommon<AST::Module_t, ASR::Module_t>(x);
  File "/Users/ondrej/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 462
    visit_unit_decl1(*x.m_use[i]);
  File "/Users/ondrej/repos/lfortran/src/lfortran/ast.h", line 4896
    void visit_unit_decl1(const unit_decl1_t &b) { visit_unit_decl1_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/src/lfortran/ast.h", line 4492
    case unit_decl1Type::Use: { v.visit_Use((const Use_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 2836
    t = (ASR::symbol_t*)(ASRUtils::load_module(al, tu_symtab,
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x102140fd3
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x102141abb
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x1022042eb
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x10220452f
LCompilersException: Incompatible format: LFortran Modfile was generated using version '0.42.0-194-ga515d2a58', but current LFortran version is '0.42.0-194-ga515d2a58-dirty'
```
For some reason it doesn't print the last 4 correctly, but other than that it works.
