### ISSUE TITLE
Segfault when compiling source with select type construct

### ISSUE THREAD

**Issue by aradi** [lfortran/lfortran#5515]
Hi guys, I really appreciate your amazing work that goes into LFortran. I thought, I'll test, how far I get with it to build the [Fortuno unit testing](https://github.com/fortuno-repos/fortuno) framework, to give further impulses for the development. :smile: 

I encountered a segfault when compiling the a given source file. The kind of minimal reproducer seems to be:
```fortran
module fortuno_basetypes
  implicit none

  type, abstract :: test_base
    character(:), allocatable :: name
  end type test_base


  type :: test_ptr_item
    class(test_base), pointer :: item => null()                                 
  end type test_ptr_item


  type :: test_list
    private
    type(test_ptr_item), pointer :: storage_(:) => null()                       
    integer :: nitems = 0
  contains
    procedure :: free => test_list_free
  end type


contains

  subroutine test_list_free(this)
    class(test_list), intent(inout) :: this                                     

    select type (item => this%storage_(1)%item)                                 
    class default
    end select

  end subroutine test_list_free

end module fortuno_basetypes
```

When running
```
❯ lfortran --tree -v -c basetypes.f90
```
it triggers 
```
zsh: segmentation fault (core dumped)  lfortran -v -c basetypes.f90
```
I am using the LFortran from conda-forge:
```
LFortran version: 0.42.0
Platform: Linux
LLVM: 19.1.1
Default target: x86_64-conda-linux-gnu
```
Please note, that the code snippet above is the minimal working example I could come up with and is not supposed to deliver something useable (but is standard conforming IMO). See the [complete source file](https://github.com/fortuno-repos/fortuno/blob/672a3981f6b0200d03ccce287c7722c5172e9636/src/fortuno/basetypes.f90) for further details.

**Comment by kmr-srbh** [comment]
@aradi thanks for this. It seems we have a failure here. The output from a debug build of LFortran is:

```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
Traceback (most recent call last):
  Binary file "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2725, in main
    return main_app(argc, argv);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2664, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 1027, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    result = fe.get_asr2(input, lm, diagnostics);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/fortran_evaluator.cpp", line 275, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/fortran_evaluator.cpp", line 297, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 101, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    instantiate_types, instantiate_symbols, entry_functions, entry_function_arguments_mapping, data_structure);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 4619, in LCompilers::LFortran::body_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::ASR::asr_t*, LCompilers::CompilerOptions&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompilers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::allocator<int> > > > >&, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> >&)
    b.visit_TranslationUnit(ast);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 154, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4884, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4841, in void LCompilers::LFortran::AST::visit_ast_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::ast_t const&, LCompilers::LFortran::BodyVisitor&)
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4887, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4471, in void LCompilers::LFortran::AST::visit_mod_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::mod_t const&, LCompilers::LFortran::BodyVisitor&)
    case modType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1885, in LCompilers::LFortran::BodyVisitor::visit_Module(LCompilers::LFortran::AST::Module_t const&)
    visit_SubmoduleModuleCommon(x);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1861, in void LCompilers::LFortran::BodyVisitor::visit_SubmoduleModuleCommon<LCompilers::LFortran::AST::Module_t>(LCompilers::LFortran::AST::Module_t const&)
    visit_program_unit(*x.m_contains[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4892, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_program_unit(LCompilers::LFortran::AST::program_unit_t const&)
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4482, in void LCompilers::LFortran::AST::visit_program_unit_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::program_unit_t const&, LCompilers::LFortran::BodyVisitor&)
    case program_unitType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2353, in LCompilers::LFortran::BodyVisitor::visit_Subroutine(LCompilers::LFortran::AST::Subroutine_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 117, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4930, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4622, in void LCompilers::LFortran::AST::visit_stmt_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::stmt_t const&, LCompilers::LFortran::BodyVisitor&)
    case stmtType::SelectType: { v.visit_SelectType((const SelectType_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1823, in LCompilers::LFortran::BodyVisitor::visit_SelectType(LCompilers::LFortran::AST::SelectType_t const&)
    selector_variable->m_type = selector_variable_type;
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in <invalid>
Segfault: Signal SIGSEGV (segmentation fault) received
```

Here is the relevant piece of code:

https://github.com/lfortran/lfortran/blob/d478e5190a7dffda73c3782cc94549d1a49664fc/src/lfortran/semantics/ast_body_visitor.cpp#L1623-L1640

We initialize `selector_variable` with `nullptr` and set it to something only when `m_selector` is `ASR::Var_t`. In this example, `m_selector` is `ASR::StructInstanceMember_t`.

**Comment by aradi** [comment]
@kmr-srbh Perfect, thanks a lot for digging deeper. Is there anything I can do more for promoting the bug fix process? I'd find it really cool, if we could compile Fortuno with LFortran as well, and I guess, it would be also a kind of milestone for LFortran itself :wink:  (But I can understand, if that is not your highest priority at the moment...)

**Comment by certik** [comment]
@aradi thanks for the bug report. We need to be able to compile codes like Fortuno before we reach beta, I created an issue for it at https://github.com/lfortran/lfortran/issues/5566. Especially when we have an enthusiastic user that would use LFortran, we'll get it done soon. :)
