### ISSUE TITLE
prima: LLVM assertion failure: invalid type conversion

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#5520]
```fortran
program main
    integer, parameter :: RP = kind(0.0D0)
    integer, parameter :: IK = kind(0)
    real(RP) :: G(2, 2)
    integer(IK) :: knew
    real(RP):: zmat(1:1, 1:1) 
    knew = 1
    G = planerot(zmat(knew, [1_IK, 2]))

    contains
    
    function planerot(x) result(G)
        real(RP), intent(in) :: x(:)
        real(RP) :: c, s, r
        real(RP) :: G(2, 2)
        c = x(1) / r
        G = reshape([c, -s, s, c], [2, 2])
    end function
end program
```
```console
$ gfortran a.f90 && ./a.out
(lf) (base) harshita@harshita-linux:~/Desktop/lfortran$ lfortran a.f90
lfortran: /home/harshita/miniconda3/envs/lf/include/llvm/IR/IRBuilder.h:1989: llvm::Value* llvm::IRBuilderBase::CreateSExtOrTrunc(llvm::Value*, llvm::Type*, const llvm::Twine&): Assertion `V->getType()->isIntOrIntVectorTy() && DestTy->isIntOrIntVectorTy() && "Can only sign extend/truncate integers!"' failed.
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2725, in main
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2664, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 1070, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 382, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10383, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5186, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5162, in void LCompilers::ASR::visit_asr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::asr_t const&, LCompilers::ASRToLLVMVisitor&)
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5187, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4892, in void LCompilers::ASR::visit_unit_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::unit_t const&, LCompilers::ASRToLLVMVisitor&)
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 988, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5189, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4900, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToLLVMVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3292, in LCompilers::ASRToLLVMVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5206, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4952, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::SubroutineCall: { v.visit_SubroutineCall((const SubroutineCall_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9424, in LCompilers::ASRToLLVMVisitor::visit_SubroutineCall(LCompilers::ASR::SubroutineCall_t const&)
    std::vector<llvm::Value *> args2 = convert_call_args(x, is_method);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8869, in std::vector<llvm::Value*, std::allocator<llvm::Value*> > LCompilers::ASRToLLVMVisitor::convert_call_args<LCompilers::ASR::SubroutineCall_t>(LCompilers::ASR::SubroutineCall_t const&, bool)
    this->visit_expr_wrapper(x.m_args[i].m_value);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5550, in LCompilers::ASRToLLVMVisitor::visit_expr_wrapper(LCompilers::ASR::expr_t*, bool)
    this->visit_expr(*x);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5254, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5043, in void LCompilers::ASR::visit_expr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ASRToLLVMVisitor&)
    case exprType::ArrayItem: { v.visit_ArrayItem((const ArrayItem_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2436, in LCompilers::ASRToLLVMVisitor::visit_ArrayItem(LCompilers::ASR::ArrayItem_t const&)
    tmp = arr_descr->get_single_element(type, array, indices, x.n_args,
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 670, in LCompilers::LLVMArrUtils::SimpleCMODescriptor::get_single_element(llvm::Type*, llvm::Value*, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&, int, bool, bool, llvm::Value**, bool, llvm::Type*, bool)
    idx = cmo_convertor_single_element_data_only(llvm_diminfo, m_args, n_args, check_for_bounds, is_unbounded_pointer_to_data);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 642, in LCompilers::LLVMArrUtils::SimpleCMODescriptor::cmo_convertor_single_element_data_only(llvm::Value**, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&, int, bool, bool)
    curr_llvm_idx = builder->CreateSExtOrTrunc(curr_llvm_idx, llvm::Type::getInt32Ty(context));
  File "/home/harshita/miniconda3/envs/lf/include/llvm/IR/IRBuilder.h", line 1989, in llvm::IRBuilderBase::CreateSExtOrTrunc(llvm::Value*, llvm::Type*, llvm::Twine const&)
    assert(V->getType()->isIntOrIntVectorTy() &&
  File "./assert/./assert/assert.c", line 101, in __assert_fail
  File "./assert/./assert/assert.c", line 92, in <invalid>
  File "./stdlib/./stdlib/abort.c", line 79, in abort
  File "./signal/../sysdeps/posix/raise.c", line 26, in raise
  File "./nptl/./nptl/pthread_kill.c", line 43, in pthread_kill
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in <invalid>
Abort: Signal SIGABRT (abort) received

Aborted (core dumped)
```

**Comment by jinangshah21** [comment]
I think this issue is same as #5484 where Issue is passing Array indices in Array Reference.

**Comment by gxyd** [comment]
On the latest *main*, this issue seems to be working now without any problem.
```console
> lfortran --version
LFortran version: 0.42.0-739-g15659619e-dirty
Platform: macOS ARM
LLVM: 11.1.0
Default target: arm64-apple-darwin23.6.0

> lfortran test.f90
> echo $?
0

> lfortran test.f90 --experimental-simplifier
> echo $?
0
```

Can we close this issue as completed now? If anything else remains to be done here @HarshitaKalani (like adding MRE to our test-suite)?

**Comment by certik** [comment]
Let's add a test, possibly just improving some existing test and we can close it.
