### ISSUE TITLE
scipy/interpolate/fitpack/fpcuro.f internal error

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#557]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/723

Compiling `scipy/scipy/interpolate/fitpack/fpcuro.f` with `lfortran --no-warnings -c --fixed-form scipy/scipy/interpolate/fitpack/fpcuro.f` yields

```
Internal Compiler Error: Unhandled exception
BFD: DWARF error: section .debug_info is larger than its filesize! (0x5b4757 vs 0x429c68)
BFD: DWARF error: section .debug_info is larger than its filesize! (0x5b4757 vs 0x429c68)
Traceback (most recent call last):
  Binary file "/home/konrad/code/fork/lfortran/src/bin/lfortran", in _start()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_start_main()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_init_first()
  File "/home/konrad/code/fork/lfortran/src/bin/lfortran.cpp", line 1667, in ??
    return compile_to_object_file(arg_file, outfile, false,
  File "/home/konrad/code/fork/lfortran/src/bin/lfortran.cpp", line 710, in ??
    result = fe.get_asr2(input, lm, diagnostics);
  File "/home/konrad/code/fork/lfortran/src/lfortran/fortran_evaluator.cpp", line 225, in LFortran::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LFortran::LocationManager&, LFortran::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/home/konrad/code/fork/lfortran/src/lfortran/fortran_evaluator.cpp", line 247, in LFortran::FortranEvaluator::get_asr3(LFortran::AST::TranslationUnit_t&, LFortran::diag::Diagnostics&)
    compiler_options.symtab_only);
  File "/home/konrad/code/fork/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 46, in LFortran::ast_to_asr(Allocator&, LFortran::AST::TranslationUnit_t&, LFortran::diag::Diagnostics&, LFortran::SymbolTable*, bool)
    auto res = body_visitor(al, ast, diagnostics, unit);
  File "/home/konrad/code/fork/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1505, in LFortran::body_visitor(Allocator&, LFortran::AST::TranslationUnit_t&, LFortran::diag::Diagnostics&, LFortran::ASR::asr_t*)
    b.visit_TranslationUnit(ast);
  File "/home/konrad/code/fork/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 102, in LFortran::BodyVisitor::visit_TranslationUnit(LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/konrad/code/fork/lfortran/src/lfortran/ast.h", line 4595, in LFortran::AST::BaseVisitor<LFortran::BodyVisitor>::visit_ast(LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/konrad/code/fork/lfortran/src/lfortran/ast.h", line 4555, in ??
    case astType::program_unit: { v.visit_program_unit((const program_unit_t &)x); return; }
  File "/home/konrad/code/fork/lfortran/src/lfortran/ast.h", line 4603, in LFortran::AST::BaseVisitor<LFortran::BodyVisitor>::visit_program_unit(LFortran::AST::program_unit_t const&)
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/home/konrad/code/fork/lfortran/src/lfortran/ast.h", line 4218, in ??
    case program_unitType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/home/konrad/code/fork/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 912, in LFortran::BodyVisitor::visit_Subroutine(LFortran::AST::Subroutine_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/konrad/code/fork/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 79, in LFortran::BodyVisitor::transform_stmts(LFortran::Vec<LFortran::ASR::stmt_t*>&, unsigned long, LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/konrad/code/fork/lfortran/src/lfortran/ast.h", line 4636, in LFortran::AST::BaseVisitor<LFortran::BodyVisitor>::visit_stmt(LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/konrad/code/fork/lfortran/src/lfortran/ast.h", line 4307, in ??
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/home/konrad/code/fork/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 957, in LFortran::BodyVisitor::visit_Assignment(LFortran::AST::Assignment_t const&)
    this->visit_expr(*x.m_value);
  File "/home/konrad/code/fork/lfortran/src/lfortran/ast.h", line 4685, in LFortran::AST::BaseVisitor<LFortran::BodyVisitor>::visit_expr(LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/konrad/code/fork/lfortran/src/lfortran/ast.h", line 4361, in ??
    case exprType::BinOp: { v.visit_BinOp((const BinOp_t &)x); return; }
  File "/home/konrad/code/fork/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 2564, in LFortran::CommonVisitor<LFortran::BodyVisitor>::visit_BinOp(LFortran::AST::BinOp_t const&)
    this->visit_expr(*x.m_left);
  File "/home/konrad/code/fork/lfortran/src/lfortran/ast.h", line 4685, in LFortran::AST::BaseVisitor<LFortran::BodyVisitor>::visit_expr(LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/konrad/code/fork/lfortran/src/lfortran/ast.h", line 4367, in ??
    case exprType::FuncCallOrArray: { v.visit_FuncCallOrArray((const FuncCallOrArray_t &)x); return; }
  File "/home/konrad/code/fork/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 2279, in LFortran::CommonVisitor<LFortran::BodyVisitor>::visit_FuncCallOrArray(LFortran::AST::FuncCallOrArray_t const&)
    tmp = create_ArrayRef(x.base.base.loc, x.m_args, x.n_args, v, f2); break;
  File "/home/konrad/code/fork/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 1249, in LFortran::CommonVisitor<LFortran::BodyVisitor>::create_ArrayRef(LFortran::Location const&, LFortran::AST::fnarg_t*, unsigned long, LFortran::ASR::symbol_t*, LFortran::ASR::symbol_t*)
    ASR::IntegerConstant_t *m_right = ASR::down_cast<ASR::IntegerConstant_t>(m_right_expr);
AssertFailed: is_a<T>(*f)
```

**Comment by konradha** [comment]
A minimal reproducer is

```fortran
program main
    real*8 f
    real*8 datan
    f = datan(0.5d+01) / 0.1d0
    print *, a
end 
```

-- the author declares function references. The declaration should thus also look for the intrinsic functions on our end.

**Comment by gptsarthak** [comment]
Fixed in https://github.com/lfortran/lfortran/pull/1799
> A minimal reproducer is

This works in ```master```

**Comment by certik** [comment]
The example from above:
```fortran
program main
    real*8 f
    real*8 datan
    f = datan(0.5d+01) / 0.1d0
end
```
Gives a stacktrace with default options, so this still needs to be fixed to give a nice compile time error:
```console
$ lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2206
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 910
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 252
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 274
    compiler_options.symtab_only, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 116
    if (res.ok) {
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3205
    b.is_body_visitor = true;
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 217
    visit_ast(*x.m_items[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4768
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4725
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4771
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4368
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1564
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 188
    this->visit_stmt(*m_body[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4813
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4469
    case stmtType::Assign: { v.visit_Assign((const Assign_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2154
    ASR::expr_t *target = ASRUtils::EXPR(tmp);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4864
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4525
    case exprType::BoolOp: { v.visit_BoolOp((const BoolOp_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5387
    this->visit_expr(*x.m_left);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4864
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4531
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5054
    tmp = create_ArrayRef(x.base.base.loc, x.m_args, x.n_args, v_expr, v, f2);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 2867
    ASR::expr_t* m_right_expr = ASRUtils::expr_value(a.m_right);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr.h", line 41
    LCOMPILERS_ASSERT(is_a<T>(*f));
AssertFailed: is_a<T>(*f)
```

The option `--implicit-interface` fixes this and then it works.

So let's keep this issue open until it is fixed.

**Comment by gptsarthak** [comment]
Just make a new field for ```datan2``` in the compile_time_map, that should fix it. Then it will work with ```implicit-interface```
