### ISSUE TITLE
Implement visit_Format() / visit_BlockData()

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#559]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/726

Running `./src/bin/lfortran --fixed-form -c --show-stacktrace` on `scipy/sparse/linalg/_eigen/arpack/ARPACK/UTIL/cvout.f` yields

```
Traceback (most recent call last):
  Binary file "/home/konrad/code/fork/lfortran/src/bin/lfortran", in _start()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_start_main()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_init_first()
  File "/home/konrad/code/fork/lfortran/src/bin/lfortran.cpp", line 1671, in ??
    return compile_to_object_file(arg_file, outfile, false,
  File "/home/konrad/code/fork/lfortran/src/bin/lfortran.cpp", line 712, in ??
    result = fe.get_asr2(input, lm, diagnostics);
  File "/home/konrad/code/fork/lfortran/src/lfortran/fortran_evaluator.cpp", line 225, in LFortran::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LFortran::LocationManager&, LFortran::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/home/konrad/code/fork/lfortran/src/lfortran/fortran_evaluator.cpp", line 247, in LFortran::FortranEvaluator::get_asr3(LFortran::AST::TranslationUnit_t&, LFortran::diag::Diagnostics&)
    compiler_options.symtab_only);
  File "/home/konrad/code/fork/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 46, in LFortran::ast_to_asr(Allocator&, LFortran::AST::TranslationUnit_t&, LFortran::diag::Diagnostics&, LFortran::SymbolTable*, bool)
    auto res = body_visitor(al, ast, diagnostics, unit);
  File "/home/konrad/code/fork/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1506, in LFortran::body_visitor(Allocator&, LFortran::AST::TranslationUnit_t&, LFortran::diag::Diagnostics&, LFortran::ASR::asr_t*)
    b.visit_TranslationUnit(ast);
  File "/home/konrad/code/fork/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 103, in LFortran::BodyVisitor::visit_TranslationUnit(LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/konrad/code/fork/lfortran/src/lfortran/ast.h", line 4595, in LFortran::AST::BaseVisitor<LFortran::BodyVisitor>::visit_ast(LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/konrad/code/fork/lfortran/src/lfortran/ast.h", line 4555, in ??
    case astType::program_unit: { v.visit_program_unit((const program_unit_t &)x); return; }
  File "/home/konrad/code/fork/lfortran/src/lfortran/ast.h", line 4603, in LFortran::AST::BaseVisitor<LFortran::BodyVisitor>::visit_program_unit(LFortran::AST::program_unit_t const&)
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/home/konrad/code/fork/lfortran/src/lfortran/ast.h", line 4218, in ??
    case program_unitType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/home/konrad/code/fork/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 913, in LFortran::BodyVisitor::visit_Subroutine(LFortran::AST::Subroutine_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/konrad/code/fork/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 80, in LFortran::BodyVisitor::transform_stmts(LFortran::Vec<LFortran::ASR::stmt_t*>&, unsigned long, LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/konrad/code/fork/lfortran/src/lfortran/ast.h", line 4636, in LFortran::AST::BaseVisitor<LFortran::BodyVisitor>::visit_stmt(LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/konrad/code/fork/lfortran/src/lfortran/ast.h", line 4322, in ??
    case stmtType::Format: { v.visit_Format((const Format_t &)x); return; }
LFortranException: visit_Format() not implemented
```

similarly for the file `scipy/integrate/odepack/blkdta000.f `

**Comment by konradha** [comment]
`visit_Format` poses an issue; #700 makes this more or less high priority too
