### ISSUE TITLE
[Fortuno] Can't declare derived types with members of its own type

### ISSUE THREAD

**Issue by tanay-man** [lfortran/lfortran#5598]
MRE:
```
module nested_type

    implicit none
    type :: nt
        type(nt), allocatable :: previous
    end type nt
    
end module nested_type
```

**Comment by certik** [comment]
This one is tricky in ASR. We want to change `StructType` to represent the type of the struct and its members. However, the type of `previous` is self referencing, so we probably would need some way to encode "self" as a type.

**Comment by kmr-srbh** [comment]
I think we have support for using structs before declaration. We handle it as `ExternalSymbol` in `ast_common_visitor.h`. It was added in #1280 for compiling FPM and was meant to address the case where we declare a variable inside struct B using struct A, but struct A itself is declared later.

We can build on top of it and support variable declarations where we point to the same struct. The following diff gets this working for me, although I must admit that I do not understand the significance of `self` in Fortran and can be completely off here.

```diff
diff --git a/src/lfortran/semantics/ast_symboltable_visitor.cpp b/src/lfortran/semantics/ast_symboltable_visitor.cpp
index aa781e622..377ac5d14 100644
--- a/src/lfortran/semantics/ast_symboltable_visitor.cpp
+++ b/src/lfortran/semantics/ast_symboltable_visitor.cpp
@@ -1854,7 +1854,7 @@ public:
         }
         SetChar struct_dependencies;
         struct_dependencies.reserve(al, 1);
-        for( auto& item: current_scope->get_scope() ) {
+        for( auto item: current_scope->get_scope() ) {
             // ExternalSymbol means that current module/program
             // already depends on the module of ExternalSymbol
             // present inside Struct's scope. So the order
@@ -1873,6 +1873,27 @@ public:
                     ASR::symbol_t* sym = ASR::down_cast<ASR::ClassType_t>(var_type)->m_class_type;
                     aggregate_type_name = ASRUtils::symbol_name(sym);
                 }
+                // Check for data member pointing to the parent struct itself
+                if (ASR::is_a<ASR::Variable_t>(*item.second)
+                    && ASR::is_a<ASR::StructType_t>(
+                        *ASRUtils::type_get_past_array_pointer_allocatable(var_type))) {
+                    ASR::Variable_t* var = ASR::down_cast<ASR::Variable_t>(item.second);
+                    // We check for an ExternalSymbol because we declare it as this when we use a
+                    // Struct before declaration, see `determine_type()` inside `ast_common_visitor.h`
+                    if (ASR::is_a<ASR::ExternalSymbol_t>(
+                        *ASR::down_cast<ASR::StructType_t>(
+                                ASRUtils::type_get_past_array_pointer_allocatable(var->m_type))
+                                ->m_derived_type)) {
+                        // If m_derived_type of StructType is an ExternalSymbol, we can be sure that we
+                        // are using a Struct before declaration, so we point to its parent scope
+                        ASR::down_cast<ASR::ExternalSymbol_t>(
+                            ASR::down_cast<ASR::StructType_t>(
+                                ASRUtils::type_get_past_array_pointer_allocatable(
+                                    var->m_type))->m_derived_type)->m_parent_symtab = parent_scope;
+                        // Update the variable after change in type above
+                        item.second = &var->base;
+                    }
+                }
             }
             if( aggregate_type_name ) {
                 struct_dependencies.push_back(al, aggregate_type_name);
diff --git a/src/libasr/asr_verify.cpp b/src/libasr/asr_verify.cpp
index 3e7230a9e..18352a615 100644
--- a/src/libasr/asr_verify.cpp
+++ b/src/libasr/asr_verify.cpp
@@ -76,8 +76,16 @@ public:
             if (s->counter == symtab_ID) {
                 ASR::symbol_t *sym2 = s->get_symbol(sym_name);
                 if (sym2) {
-                    if (sym2 == sym) {
+                    if ((sym2 == sym)
+                        || (ASR::is_a<ASR::ExternalSymbol_t>(*sym)
+                            && ASR::is_a<ASR::Struct_t>(*sym2))) {
                         // The symbol table was found and the symbol `sym` is in it
+                        // OR
+                        // We are declaring a variable inside a struct using the same struct.
+                        // See `visit_DerivedType()` inside `ast_symboltable_visitor.h`
+                        //      type :: nt
+                        //          type(nt), allocatable :: previous
+                        //      end type nt
                         return true;
                     } else {
                         diagnostics.message_label("The symbol table was found and the symbol in it shares the name, but is not equal to `sym`",
```

### ASR

```clojure
;; ASR after SymbolTable Visitor
(TranslationUnit
    (SymbolTable
        4
        {
            nested_type:
                (Module
                    (SymbolTable
                        5
                        {
                            nt:
                                (Struct
                                    (SymbolTable
                                        6
                                        {
                                            previous:
                                                (Variable
                                                    6
                                                    previous
                                                    []
                                                    Local
                                                    ()
                                                    ()
                                                    Default
                                                    (Allocatable
                                                        (StructType
                                                            5 nt
                                                        )
                                                    )
                                                    ()
                                                    Source
                                                    Public
                                                    Required
                                                    .false.
                                                )
                                        })
                                    nt
                                    []
                                    [previous]
                                    Source
                                    Public
                                    .false.
                                    .false.
                                    []
                                    ()
                                    ()
                                )
                        })
                    nested_type
                    []
                    .false.
                    .false.
                )
        })
    []
)
```

**Comment by kmr-srbh** [comment]
Here is a good example which we can try compiling with LFortran. We can uncomment it's parts as we make more progress. This currently does not compile even with the above diff.

```fortran
program linked_list
   type :: node
      integer :: value
      type(node), pointer :: next => null()
   end type node

   type(node) :: head

   head%value = 1
   ! allocate(head%next)
   ! head%next%value = 2
   ! head%next%next => null()

   print *, "First node value: ", head%value
   ! print *, "Second node value: ", head%next%value
end program linked_list
```

```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2726, in main
    return main_app(argc, argv);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2665, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 1070, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/fortran_evaluator.cpp", line 382, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10394, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 316, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 292, in void LCompilers::ASR::visit_asr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::asr_t const&, LCompilers::ASRToLLVMVisitor&)
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 317, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 22, in void LCompilers::ASR::visit_unit_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::unit_t const&, LCompilers::ASRToLLVMVisitor&)
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 988, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 319, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 30, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToLLVMVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3280, in LCompilers::ASRToLLVMVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    declare_vars(x);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3934, in void LCompilers::ASRToLLVMVisitor::declare_vars<LCompilers::ASR::Program_t>(LCompilers::ASR::Program_t const&, bool)
    process_Variable(var_sym, x, debug_arg_count);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3674, in void LCompilers::ASRToLLVMVisitor::process_Variable<LCompilers::ASR::Program_t const>(LCompilers::ASR::symbol_t*, LCompilers::ASR::Program_t const&, unsigned int&)
    type = llvm_utils->get_type_from_ttype_t(
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1427, in LCompilers::LLVMUtils::get_type_from_ttype_t(LCompilers::ASR::ttype_t*, LCompilers::ASR::symbol_t*, LCompilers::ASR::storage_typeType, bool&, bool&, bool&, LCompilers::ASR::dimension_t*&, int&, int&, llvm::Module*, LCompilers::ASR::abiType, bool) (.localalias)
    llvm_type = getStructType(asr_type, module, false);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/llvm_utils.cpp", line 271, in LCompilers::LLVMUtils::getStructType(LCompilers::ASR::ttype_t*, llvm::Module*, bool)
    llvm::Type* type = getStructType(der_type, module, is_pointer);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/llvm_utils.cpp", line 242, in LCompilers::LLVMUtils::getStructType(LCompilers::ASR::Struct_t*, llvm::Module*, bool) (.localalias)
    llvm::Type* llvm_mem_type = get_type_from_ttype_t_util(member->m_type, module, member->m_abi);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1535, in LCompilers::LLVMUtils::get_type_from_ttype_t_util(LCompilers::ASR::ttype_t*, llvm::Module*, LCompilers::ASR::abiType)
    return get_type_from_ttype_t(asr_type, nullptr, m_storage_local, is_array_type_local,
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1443, in LCompilers::LLVMUtils::get_type_from_ttype_t(LCompilers::ASR::ttype_t*, LCompilers::ASR::symbol_t*, LCompilers::ASR::storage_typeType, bool&, bool&, bool&, LCompilers::ASR::dimension_t*&, int&, int&, llvm::Module*, LCompilers::ASR::abiType, bool) (.localalias)
    handle_llvm_pointers1()
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1427, in LCompilers::LLVMUtils::get_type_from_ttype_t(LCompilers::ASR::ttype_t*, LCompilers::ASR::symbol_t*, LCompilers::ASR::storage_typeType, bool&, bool&, bool&, LCompilers::ASR::dimension_t*&, int&, int&, llvm::Module*, LCompilers::ASR::abiType, bool) (.localalias)
    llvm_type = getStructType(asr_type, module, false);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/llvm_utils.cpp", line 262, in LCompilers::LLVMUtils::getStructType(LCompilers::ASR::ttype_t*, llvm::Module*, bool)
    der_type = ASR::down_cast<ASR::Struct_t>(der_sym);
AssertFailed: f != nullptr
```

**Comment by certik** [comment]
Using ExternalSymbol is probably fine for now, while we use StructType to just point to the symbol table.

This will not work once we move to a fully independent StructType that has types of its members, since it is self-referencial. We might need to introduce SelfType or something like that. We can tackle that later.

**Comment by certik** [comment]
I think we need a special type, maybe `SelfStruct`, or `TypeOfThis`, or something like that, that will be used for the member `Allocatable[SelfStruct]`.
