### ISSUE TITLE
(PRIMA) Handle optional arguments of function (passed as argument)  to another file

### ISSUE THREAD

**Issue by jinangshah21** [lfortran/lfortran#5625]
MRE : 

**File 1** : 
```fortran 
module procedure_07_module
contains
    subroutine cb(x, terminate)
        implicit none
        real(8), intent(in) :: x(:)
        logical, intent(out), optional :: terminate
    end subroutine cb
end module procedure_07_module

program procedure_07
    use procedure_07_module
    use test
    call temp(cb)
end program procedure_07
```

**File 2** : 
```fortran 
module test
contains 
subroutine temp(call_back)
    use procedure_07_module
    implicit none
    procedure(cb), optional :: call_back
    logical :: terminate_var
    real(8) :: x3(2)
    call call_back(x3, terminate_var)   
end subroutine temp
end module
```

LFortran Error : 
```console
Traceback (most recent call last):
  Binary file "/mnt/c/lfortran/src/bin/lfortran", in _start
  File "/build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c", line 308, in __libc_start_main
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2732, in main
    return main_app(argc, argv);
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2670, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 1049, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/mnt/c/lfortran/src/lfortran/fortran_evaluator.cpp", line 382, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10398, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/mnt/c/lfortran/src/libasr/pass/pass_manager.h", line 403, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/mnt/c/lfortran/src/libasr/pass/pass_manager.h", line 180, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/mnt/c/lfortran/src/libasr/pass/transform_optional_argument_functions.cpp", line 580, in LCompilers::pass_transform_optional_argument_functions(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    y.visit_TranslationUnit(unit);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_pass_walk_visitor.h", line 35, in LCompilers::ASR::ASRPassBaseWalkVisitor<LCompilers::ReplaceSubroutineCallsWithOptionalArgumentsVisitor>::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 319, in LCompilers::ASR::BaseVisitor<LCompilers::ReplaceSubroutineCallsWithOptionalArgumentsVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 31, in void LCompilers::ASR::visit_symbol_t<LCompilers::ReplaceSubroutineCallsWithOptionalArgumentsVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ReplaceSubroutineCallsWithOptionalArgumentsVisitor&)
    case symbolType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_pass_walk_visitor.h", line 53, in LCompilers::ASR::ASRPassBaseWalkVisitor<LCompilers::ReplaceSubroutineCallsWithOptionalArgumentsVisitor>::visit_Module(LCompilers::ASR::Module_t const&)
    this->visit_symbol(*a.second);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 319, in LCompilers::ASR::BaseVisitor<LCompilers::ReplaceSubroutineCallsWithOptionalArgumentsVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 32, in void LCompilers::ASR::visit_symbol_t<LCompilers::ReplaceSubroutineCallsWithOptionalArgumentsVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ReplaceSubroutineCallsWithOptionalArgumentsVisitor&)
    case symbolType::Function: { v.visit_Function((const Function_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/../libasr/pass/pass_utils.h", line 350, in LCompilers::PassUtils::PassVisitor<LCompilers::ReplaceSubroutineCallsWithOptionalArgumentsVisitor>::visit_Function(LCompilers::ASR::Function_t const&)
    transform_stmts(xx.m_body, xx.n_body);
  File "/mnt/c/lfortran/src/libasr/../libasr/pass/pass_utils.h", line 295, in LCompilers::PassUtils::PassVisitor<LCompilers::ReplaceSubroutineCallsWithOptionalArgumentsVisitor>::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    self().visit_stmt(*m_body[i]);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 336, in LCompilers::ASR::BaseVisitor<LCompilers::ReplaceSubroutineCallsWithOptionalArgumentsVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 82, in void LCompilers::ASR::visit_stmt_t<LCompilers::ReplaceSubroutineCallsWithOptionalArgumentsVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ReplaceSubroutineCallsWithOptionalArgumentsVisitor&)
    case stmtType::SubroutineCall: { v.visit_SubroutineCall((const SubroutineCall_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/pass/transform_optional_argument_functions.cpp", line 564, in LCompilers::ReplaceSubroutineCallsWithOptionalArgumentsVisitor::visit_SubroutineCall(LCompilers::ASR::SubroutineCall_t const&)
    pass_result.push_back(al, ASRUtils::STMT(ASRUtils::make_SubroutineCall_t_util(al,
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_utils.h", line 6078, in LCompilers::ASRUtils::make_SubroutineCall_t_util(Allocator&, LCompilers::Location const&, LCompilers::ASR::symbol_t*, LCompilers::ASR::symbol_t*, LCompilers::ASR::call_arg_t*, unsigned long, LCompilers::ASR::expr_t*, LCompilers::ASR::stmt_t**, bool, bool)
    Call_t_body(al, a_name, a_args, n_args, a_dt, cast_stmt, implicit_argument_casting, nopass);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_utils.h", line 5862, in LCompilers::ASRUtils::Call_t_body(Allocator&, LCompilers::ASR::symbol_t*, LCompilers::ASR::call_arg_t*, unsigned long, LCompilers::ASR::expr_t*, LCompilers::ASR::stmt_t**, bool, bool)
    ASR::ttype_t* orig_arg_type = ASRUtils::type_get_past_allocatable(
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_utils.h", line 179, in LCompilers::ASRUtils::type_get_past_pointer(LCompilers::ASR::ttype_t*)
    if (ASR::is_a<ASR::Pointer_t>(*f)) {
  File "/mnt/c/lfortran/src/libasr/asr.h", line 32, in bool LCompilers::ASR::is_a<LCompilers::ASR::Pointer_t, LCompilers::ASR::ttype_t>(LCompilers::ASR::ttype_t const&)
    return T::class_type == x.type;
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in <invalid>
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by jinangshah21** [comment]
Here If we merge both files, then it works.

**Comment by advikkabra** [comment]
How did you compile these? What commands did you use?

**Comment by jinangshah21** [comment]
You can do two things : 
1) Run File 1 --> Run File 2 --> Run File 1
2) Take `procedure_07_module` in seperate file and run that first, then File 2 --> File 1.
