### ISSUE TITLE
Code to compile: AoC-2024

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#5629]
How to get started: https://github.com/certik/AoC-2024/tree/lf1

This branch contains some initial workarounds, then:
```
(env) repos/AoC-2024(lf1)$ ./build.sh
+ FPM_FFLAGS=--cpp
+ fpm build --compiler=lfortran
aoc_utilities.F90                      done.
libAoC-2023.a                          done.
problem_08.f90                         failed.
[ 16%] Compiling...
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x100024433
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x100013a5f
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x10001cf63
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x10081628f
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x1024cf977
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x1000bebfb
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x1000bf207
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x101c115d7
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x101c11827
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x101c66497
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x101c665c7
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x101c667eb
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x101c6773f
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x101c67917
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x101c67ad7
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x101c687b7
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x101c6773f
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x101c67917
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x101c67a77
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x101c6818b
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x101c6c293
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x101c6cdc3
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x101c6e9eb
  Binary file "/Users/ondrej/repos/lfortran/src/bin/lfortran", local address: 0x101c13a2f
AssertFailed: is_a<T>(*f)
<ERROR> Compilation failed for object " app_problem_08.f90.o "
<ERROR> stopping due to failed compilation
STOP 1
```

**Comment by AnshMehta1** [comment]
Steps to Compile :- 

Use https://github.com/certik/AoC-2024/commits/lf1/

To Compile with Lfortran :- 
```console
git clone https://github.com/certik/AoC-2024.git
cd AoC-2024
git checkout -t origin/lf1
./build.sh
```

Currently , Project is compiling upto 5% on linux using LFortran

Current Status with Lfortran :- 
```console
Initialized empty Git repository in /home/lordansh/dev/lfort1/lfortran/AoC-2024/build/dependencies/daglib/.git/
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 21 (delta 1), reused 9 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (21/21), 84.10 KiB | 598.00 KiB/s, done.
From https://github.com/jacobwilliams/daglib
 * branch            HEAD       -> FETCH_HEAD
aoc_utilities.F90                      failed.
[  5%] Compiling...
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):

b.visit_TranslationUnit(ast);
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 166, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/ast.h", line 4969, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/ast.h", line 4925, in void LCompilers::LFortran::AST::visit_ast_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::ast_t const&, LCompilers::LFortran::BodyVisitor&)
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/ast.h", line 4972, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/ast.h", line 4546, in void LCompilers::LFortran::AST::visit_mod_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::mod_t const&, LCompilers::LFortran::BodyVisitor&)
    case modType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1973, in LCompilers::LFortran::BodyVisitor::visit_Module(LCompilers::LFortran::AST::Module_t const&)
    visit_SubmoduleModuleCommon(x);
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1949, in void LCompilers::LFortran::BodyVisitor::visit_SubmoduleModuleCommon<LCompilers::LFortran::AST::Module_t>(LCompilers::LFortran::AST::Module_t const&)
    visit_program_unit(*x.m_contains[i]);
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/ast.h", line 4977, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_program_unit(LCompilers::LFortran::AST::program_unit_t const&)
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/ast.h", line 4559, in void LCompilers::LFortran::AST::visit_program_unit_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::program_unit_t const&, LCompilers::LFortran::BodyVisitor&)
    case program_unitType::Function: { v.visit_Function((const Function_t &)x); return; }
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2514, in LCompilers::LFortran::BodyVisitor::visit_Function(LCompilers::LFortran::AST::Function_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 128, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/ast.h", line 5017, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/ast.h", line 4659, in void LCompilers::LFortran::AST::visit_stmt_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::stmt_t const&, LCompilers::LFortran::BodyVisitor&)
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2892, in LCompilers::LFortran::BodyVisitor::visit_Assignment(LCompilers::LFortran::AST::Assignment_t const&)
    this->visit_expr(*x.m_value);
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/ast.h", line 5069, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_expr(LCompilers::LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/ast.h", line 4722, in void LCompilers::LFortran::AST::visit_expr_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::expr_t const&, LCompilers::LFortran::BodyVisitor&)
    case exprType::FuncCallOrArray: { v.visit_FuncCallOrArray((const FuncCallOrArray_t &)x); return; }
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 8626, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_FuncCallOrArray(LCompilers::LFortran::AST::FuncCallOrArray_t const&)
    tmp = create_FunctionCallWithASTNode(x, v, args);
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 6113, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_FunctionCallWithASTNode(LCompilers::LFortran::AST::FuncCallOrArray_t const&, LCompilers::ASR::symbol_t*, LCompilers::Vec<LCompilers::ASR::call_arg_t>&, bool)
    return create_GenericProcedureWithASTNode(x, args, v);
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5686, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_GenericProcedureWithASTNode(LCompilers::LFortran::AST::FuncCallOrArray_t const&, LCompilers::Vec<LCompilers::ASR::call_arg_t>&, LCompilers::ASR::symbol_t*)
    return ASRUtils::make_FunctionCall_t_util(al, loc,
  File "/home/lordansh/dev/lfort1/lfortran/src/libasr/asr_utils.h", line 6027, in LCompilers::ASRUtils::make_FunctionCall_t_util(Allocator&, LCompilers::Location const&, LCompilers::ASR::symbol_t*, LCompilers::ASR::symbol_t*, LCompilers::ASR::call_arg_t*, unsigned long, LCompilers::ASR::ttype_t*, LCompilers::ASR::expr_t*, LCompilers::ASR::expr_t*, bool)
    m_dim_vec.m_length = ASRUtils::EXPR(ASRUtils::make_ArraySize_t_util(al, m_dims[j].loc,
AssertFailed: m_dims[dim - 1].m_length
<ERROR> Compilation failed for object " src_aoc_utilities.F90.o "
<ERROR> stopping due to failed compilation
STOP 1
```

**Comment by YashNagda17** [comment]
On current main, we are able to compile all codes & outputs match with gfortran. 
We are also able to compile & run on `--fast` & `--separate-compilation` flags as well... 

Here's detailed breakdown (The same steps work on upstream code directly):
```bash
$ git clone https://github.com/YashNagda17/AoC-2024.git
$ cd AoC-2024

$ FPM_FFLAGS="--cpp --realloc-lhs-arrays" fpm run --compiler=lfortran --profile release --all

aoc_utilities.F90                      done.
libAoC-2023.a                          done.
problem_12.f90                         done.
problem_06.f90                         done.
problem_07.f90                         done.
problem_05.f90                         done.
problem_01.f90                         done.
problem_02.f90                         done.
problem_08.f90                         done.
problem_10.f90                         done.
problem_14.f90                         done.
problem_09.f90                         done.
problem_15.f90                         done.
problem_03.f90                         done.
problem_11.f90                         done.
problem_13.f90                         done.
problem_04.f90                         done.
problem_12                             done.
problem_06                             done.
problem_07                             done.
problem_05                             done.
problem_01                             done.
problem_02                             done.
problem_08                             done.
problem_10                             done.
problem_14                             done.
problem_09                             done.
problem_15                             done.
problem_03                             done.
problem_11                             done.
problem_13                             done.
problem_04                             done.
[100%] Project compiled successfully.
12a:    1449902
12b:    908042
12 runtime:   246 ms
---------------------------

6a:    4656
6b:    1575
6 runtime:  1312 ms
---------------------------

7a:    465126289353
7b:    70597497486371
7 runtime:  1003 ms
---------------------------

5a:    6505
5b:    6897
5 runtime:    23 ms
---------------------------

1a: sum:    2264607
1b: sum:    19457120
1 runtime:     1 ms
---------------------------

2a:    334
2b:    400
2 runtime:     2 ms
---------------------------

8a:    293
8b:    934
8 runtime:     0 ms
---------------------------

10a:    587
10b:    1340
10 runtime:     0 ms
---------------------------

14a:    233709840
14b:    6620
14 runtime:   586 ms
---------------------------

9a:    6385338159127
9b:    6415163624282
9 runtime:  2561 ms
---------------------------

15a:             1442192
15 runtime:     4 ms
---------------------------

3a:    164730528
3b:    70478672
3 runtime:     0 ms
---------------------------

11a:    175006
11b:    207961583799296
11 runtime:  1411 ms
---------------------------

13a:               26598
13b:     24033600151599.
13 runtime:     0 ms
---------------------------

3a:    2547
3b:    1939
3 runtime:    12 ms
---------------------------
```
