### ISSUE TITLE
Stacktraces stopped working on macOS

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#5630]
```
(lf) src/bin(main)$ llvm-dwarfdump --debug-line lfortran.dSYM
lfortran.dSYM/Contents/Resources/DWARF/lfortran:	file format Mach-O arm64

.debug_line contents:
```
This should print all debugging information. It is using the `/usr/bin/dsymutil` introduced in #5495, so I am not sure what is going on. As a result `lfortran` doesn't print the stacktrace, such as in #5629.

**Comment by gxyd** [comment]
## Machine information

```console
> uname -a
Darwin Gauravs-MacBook-Air.local 24.4.0 Darwin Kernel Version 24.4.0: Wed Mar 19 21:11:02 PDT 2025; root:xnu-11417.101.15~1/RELEASE_ARM64_T8132 arm64

> /usr/bin/dsymutil --version
Apple LLVM version 17.0.0
  Optimized build.
```

## Non-informative stacktrace with LFortran

With LFortran:
```console
> ./src/bin/lfortran --version
LFortran version: 0.50.0-101-g0c6ba2300-dirty
Platform: macOS ARM
LLVM: 11.1.0
Default target: arm64-apple-darwin24.4.0

> # keep in mind that the below program depending on the version of LFortran
> # might actually work as the PR: https://github.com/lfortran/lfortran/pull/6854
> # from where I got the below program, as the fix for the issue is now merged

> cat test.f90
module derived_types_48_m
    implicit none
    type t
        integer :: x = 1
        integer :: y = 2
    end type

    type, extends(t) :: ext_t
        type(t) :: ins = t()
    end type

end module derived_types_48_m

program derived_types_48
    use derived_types_48_m
    implicit none

    type(ext_t) :: i
end program derived_types_48

> ./src/bin/lfortran test.f90 --show-stacktrace
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2687
    LCompilers::print_stack_on_segfault();
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2618
    err = compile_src_to_object_file(arg_file, tmp_o, compiler_options.time_report, false,
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 1165
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 383
    if (res.ok) {
  Binary file "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran", local address: 0x10245ac93
  Binary file "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran", local address: 0x10245b45f
  Binary file "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran", local address: 0x102490067
  Binary file "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran", local address: 0x10249014b
  Binary file "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran", local address: 0x102490463
  Binary file "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran", local address: 0x102490ec3
  Binary file "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran", local address: 0x102490187
  Binary file "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran", local address: 0x1024b5d6f
  Binary file "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran", local address: 0x1024b6723
  Binary file "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran", local address: 0x1024bd8c3
  Binary file "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran", local address: 0x1024bc66b
  Binary file "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran", local address: 0x1024a6f17
  Binary file "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran", local address: 0x1024901ff
  Binary file "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran", local address: 0x1024f8beb
  Binary file "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran", local address: 0x1024fd28b
LCompilersException: visit_StructConstructor() not implemented
```

**Comment by gxyd** [comment]
If it helps, I'm posting more information:
```console
> (lf) gxyd@Gauravs-MacBook-Air src/bin (main) »  llvm-dwarfdump --debug-line lfortran.dSYM
lfortran.dSYM/Contents/Resources/DWARF/lfortran:	file format Mach-O arm64

.debug_line contents:
debug_line[0x00000000]
Line table prologue:
    total_length: 0x0000f86f
          format: DWARF32
         version: 5
    address_size: 8
 seg_select_size: 0
 prologue_length: 0x000003af
 min_inst_length: 1
max_ops_per_inst: 1
 default_is_stmt: 1
       line_base: -5
      line_range: 14
     opcode_base: 13


...
...
...
```
