### ISSUE TITLE
Allocation of struct pointer

### ISSUE THREAD

**Issue by adit4443ya** [lfortran/lfortran#5655]
MRE
```fortran
module p
    implicit none
    integer, parameter, private :: mxdim = 3
    type :: rp1d
        real(8), dimension(:), pointer :: f
    end type

    type :: sds
        integer :: ndim
        integer, dimension(mxdim) :: dims
        logical :: hdf32
        type(rp1d), dimension(mxdim) :: scales
        real(8), dimension(:,:,:), pointer :: f
    end type
end module

program main
    use p
    implicit none
    type(sds) :: s
    allocate(s%scales(1)%f(2))
    s%scales(1)%f=[1,2]
    print *, 'Scale 0:', s%scales(1)%f
    nullify(s%scales(1)%f)
end program
```
on Lfortran compilation
```shell
 aditya-trivedi   lfortran    main ≡  ?1 ~1    lfortran ./integration_tests/nullify_03.f90
lfortran: /home/aditya-trivedi/conda_root/envs/lf/include/llvm/IR/Instructions.h:939: static llvm::GetElementPtrInst* llvm::GetElementPtrInst::Create(llvm::Type*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&, llvm::Instruction*): Assertion `PointeeType == cast<PointerType>(Ptr->getType()->getScalarType())->getElementType()' failed.
Traceback (most recent call last):
  Binary file "/home/aditya-trivedi/thats_me/main/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/bin/lfortran.cpp", line 2732, in main
    return main_app(argc, argv);
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/bin/lfortran.cpp", line 2670, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/bin/lfortran.cpp", line 1049, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/lfortran/fortran_evaluator.cpp", line 382, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10404, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 316, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 292, in void LCompilers::ASR::visit_asr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::asr_t const&, LCompilers::ASRToLLVMVisitor&)
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 317, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 22, in void LCompilers::ASR::visit_unit_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::unit_t const&, LCompilers::ASRToLLVMVisitor&)
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 988, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 319, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 30, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToLLVMVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3292, in LCompilers::ASRToLLVMVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 336, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 53, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::Allocate: { v.visit_Allocate((const Allocate_t &)x); return; }
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1105, in LCompilers::ASRToLLVMVisitor::visit_Allocate(LCompilers::ASR::Allocate_t const&)
    visit_AllocateUtil(x, x.m_stat, false);
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1000, in void LCompilers::ASRToLLVMVisitor::visit_AllocateUtil<LCompilers::ASR::Allocate_t>(LCompilers::ASR::Allocate_t const&, LCompilers::ASR::expr_t*, bool)
    this->visit_expr_wrapper(tmp_expr, false);
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5550, in LCompilers::ASRToLLVMVisitor::visit_expr_wrapper(LCompilers::ASR::expr_t*, bool)
    this->visit_expr(*x);
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 384, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 182, in void LCompilers::ASR::visit_expr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ASRToLLVMVisitor&)
    case exprType::StructInstanceMember: { v.visit_StructInstanceMember((const StructInstanceMember_t &)x); return; }
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2666, in LCompilers::ASRToLLVMVisitor::visit_StructInstanceMember(LCompilers::ASR::StructInstanceMember_t const&)
    tmp = llvm_utils->create_gep2(xtype, tmp, member_idx);
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1551, in LCompilers::LLVMUtils::create_gep2(llvm::Type*, llvm::Value*, int)
    return LLVMUtils::CreateGEP2(t, ds, idx_vec);
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1738, in LCompilers::LLVMUtils::CreateGEP2(llvm::Type*, llvm::Value*, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&)
    return builder->CreateGEP(t, x, idx);
  File "/home/aditya-trivedi/conda_root/envs/lf/include/llvm/IR/IRBuilder.h", line 1773, in llvm::IRBuilderBase::CreateGEP(llvm::Type*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&)
    return Insert(GetElementPtrInst::Create(Ty, Ptr, IdxList), Name);
  File "/home/aditya-trivedi/conda_root/envs/lf/include/llvm/IR/Instructions.h", line 939, in llvm::GetElementPtrInst::Create(llvm::Type*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&, llvm::Instruction*)
    assert(
  File "./assert/./assert/assert.c", line 103, in __assert_fail
  File "./assert/./assert/assert.c", line 94, in <invalid>
  File "./stdlib/./stdlib/abort.c", line 79, in abort
  File "./signal/../sysdeps/posix/raise.c", line 26, in raise
  File "./nptl/./nptl/pthread_kill.c", line 43, in pthread_kill
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in <invalid>
Abort: Signal SIGABRT (abort) received

Aborted (core dumped)
```
while in gfortran compilation
```shell
 aditya-trivedi   lfortran    main ≡  ?1 ~1    gfortran ./integration_tests/nullify_03.f90  -o ../a && ../a
 Scale 0:   1.0000000000000000        2.0000000000000000
 ```

**Comment by kmr-srbh** [comment]
Found the issue. Working on it.

**Comment by Pranavchiku** [comment]
This works with latest main:

```fortran
% lfortran b.f90 
Scale 0:
1.00000000000000000e+00    2.00000000000000000e+00
```

**Comment by Pranavchiku** [comment]
With latest main, MRE segfaults

```fortran
program main
    implicit none
    type :: rp1d
        real, dimension(:), pointer :: f
    end type

    type :: sds
        integer, dimension(3) :: dims
        type(rp1d), dimension(3) :: scales
        real, dimension(:), pointer :: f
    end type

    type(sds) :: s
    allocate(s%scales(1)%f(2))
end program
```

```console
% lfortran a.f90 
% echo $?
10
% gfortran a.f90 && ./a.out
% echo $?
0

```

**Comment by Pranavchiku** [comment]
I think I know what is happening, if you do `lfortran a.f90 --show-llvm > a.ll` and then comment the part shown below:

```llvm
; ModuleID = 'LFortran'
source_filename = "LFortran"

%sds = type { [3 x i32], [3 x %rp1d], %array* }
%rp1d = type { %array* }
%array = type { float*, i32, %dimension_descriptor*, i1, i32 }
%dimension_descriptor = type { i32, i32, i32 }

define i32 @main(i32 %0, i8** %1) {
.entry:
  call void @_lpython_call_initial_functions(i32 %0, i8** %1)
  %s = alloca %sds, align 8
  %2 = getelementptr %sds, %sds* %s, i32 0, i32 0
  %3 = getelementptr %sds, %sds* %s, i32 0, i32 2
  store %array* null, %array** %3, align 8
  %arr_desc = alloca %array, align 8
  %4 = getelementptr %array, %array* %arr_desc, i32 0, i32 2
  %5 = alloca i32, align 4
  store i32 1, i32* %5, align 4
  %6 = load i32, i32* %5, align 4
  %7 = alloca %dimension_descriptor, i32 %6, align 8
  store %dimension_descriptor* %7, %dimension_descriptor** %4, align 8
  %8 = getelementptr %array, %array* %arr_desc, i32 0, i32 4
  store i32 1, i32* %8, align 4
  %9 = getelementptr %array, %array* %arr_desc, i32 0, i32 0
  store float* null, float** %9, align 8
  store %array* %arr_desc, %array** %3, align 8
  %10 = getelementptr %sds, %sds* %s, i32 0, i32 1
  %11 = getelementptr %sds, %sds* %s, i32 0, i32 1
  %12 = getelementptr [3 x %rp1d], [3 x %rp1d]* %11, i32 0, i32 0
  %13 = getelementptr %rp1d, %rp1d* %12, i32 0, i32 0
  %14 = load %array*, %array** %13, align 8
  %15 = ptrtoint %array* %14 to i32
  %16 = icmp eq i32 %15, 0
  br i1 %16, label %then, label %else

then:                                             ; preds = %.entry
  %17 = call i8* @_lfortran_malloc(i32 ptrtoint (%array* getelementptr (%array, %array* null, i32 1) to i32))
  %18 = bitcast i8* %17 to %array*
  %19 = getelementptr %array, %array* %18, i32 0, i32 2
  %20 = alloca i32, align 4
  store i32 1, i32* %20, align 4
  %21 = call i8* @_lfortran_malloc(i32 mul nuw (i32 ptrtoint (i32* getelementptr (i32, i32* null, i32 1) to i32), i32 3))
  %22 = bitcast i8* %21 to %dimension_descriptor*
  store %dimension_descriptor* %22, %dimension_descriptor** %19, align 8
  %23 = getelementptr %array, %array* %18, i32 0, i32 4
  store i32 1, i32* %23, align 4
  store %array* %18, %array** %13, align 8
  br label %ifcont

else:                                             ; preds = %.entry
  br label %ifcont

ifcont:                                           ; preds = %else, %then
  %24 = load %array*, %array** %13, align 8
  %25 = getelementptr %array, %array* %24, i32 0, i32 1
  ; store i32 0, i32* %25, align 4
  ; %26 = getelementptr %array, %array* %24, i32 0, i32 2
  ; %27 = load %dimension_descriptor*, %dimension_descriptor** %26, align 8
  ; %28 = getelementptr inbounds %dimension_descriptor, %dimension_descriptor* %27, i32 0
  ; %29 = getelementptr %dimension_descriptor, %dimension_descriptor* %28, i32 0, i32 0
  ; %30 = getelementptr %dimension_descriptor, %dimension_descriptor* %28, i32 0, i32 1
  ; %31 = getelementptr %dimension_descriptor, %dimension_descriptor* %28, i32 0, i32 2
  ; store i32 1, i32* %29, align 4
  ; store i32 1, i32* %30, align 4
  ; store i32 2, i32* %31, align 4
  ; %32 = getelementptr %array, %array* %24, i32 0, i32 0
  ; %33 = alloca i32, align 4
  ; store i32 8, i32* %33, align 4
  ; %34 = load i32, i32* %33, align 4
  ; %35 = call i8* @_lfortran_malloc(i32 %34)
  ; %36 = bitcast i8* %35 to float*
  ; store float* %36, float** %32, align 8
  ; call void @_lpython_free_argv()
  br label %return

return:                                           ; preds = %ifcont
  ret i32 0
}

declare void @_lpython_call_initial_functions(i32, i8**)

declare i8* @_lfortran_malloc(i32)

declare void @_lpython_free_argv()
```

The example works fine, no segfault. The moment I uncomment `store i32 0, i32* %25, align 4`, it segfaults. Now, if we see:

> b.f90

```fortran
program main
    implicit none
    type :: rp1d
        real, dimension(:), pointer :: f
    end type

    type :: sds
        integer, dimension(3) :: dims
        type(rp1d), dimension(3) :: scales
        real, dimension(:), pointer :: f
    end type

    type(sds) :: s
    allocate(s%f(2))
    ! s%f = [1.0, 2.0]
    ! print *, s%f(2)
end program
```

```llvm
; ModuleID = 'LFortran'
source_filename = "LFortran"

%sds = type { [3 x i32], [3 x %rp1d], %array* }
%rp1d = type { %array* }
%array = type { float*, i32, %dimension_descriptor*, i1, i32 }
%dimension_descriptor = type { i32, i32, i32 }

define i32 @main(i32 %0, i8** %1) {
.entry:
  call void @_lpython_call_initial_functions(i32 %0, i8** %1)
  %s = alloca %sds, align 8
  %2 = getelementptr %sds, %sds* %s, i32 0, i32 0
  %3 = getelementptr %sds, %sds* %s, i32 0, i32 2
  store %array* null, %array** %3, align 8
  %arr_desc = alloca %array, align 8
  %4 = getelementptr %array, %array* %arr_desc, i32 0, i32 2
  %5 = alloca i32, align 4
  store i32 1, i32* %5, align 4
  %6 = load i32, i32* %5, align 4
  %7 = alloca %dimension_descriptor, i32 %6, align 8
  store %dimension_descriptor* %7, %dimension_descriptor** %4, align 8
  %8 = getelementptr %array, %array* %arr_desc, i32 0, i32 4
  store i32 1, i32* %8, align 4
  %9 = getelementptr %array, %array* %arr_desc, i32 0, i32 0
  store float* null, float** %9, align 8
  store %array* %arr_desc, %array** %3, align 8
  %10 = getelementptr %sds, %sds* %s, i32 0, i32 1
  %11 = getelementptr %sds, %sds* %s, i32 0, i32 2
  %12 = load %array*, %array** %11, align 8
  %13 = ptrtoint %array* %12 to i32
  %14 = icmp eq i32 %13, 0
  br i1 %14, label %then, label %else

then:                                             ; preds = %.entry
  %15 = call i8* @_lfortran_malloc(i32 ptrtoint (%array* getelementptr (%array, %array* null, i32 1) to i32))
  %16 = bitcast i8* %15 to %array*
  %17 = getelementptr %array, %array* %16, i32 0, i32 2
  %18 = alloca i32, align 4
  store i32 1, i32* %18, align 4
  %19 = call i8* @_lfortran_malloc(i32 mul nuw (i32 ptrtoint (i32* getelementptr (i32, i32* null, i32 1) to i32), i32 3))
  %20 = bitcast i8* %19 to %dimension_descriptor*
  store %dimension_descriptor* %20, %dimension_descriptor** %17, align 8
  %21 = getelementptr %array, %array* %16, i32 0, i32 4
  store i32 1, i32* %21, align 4
  store %array* %16, %array** %11, align 8
  br label %ifcont

else:                                             ; preds = %.entry
  br label %ifcont

ifcont:                                           ; preds = %else, %then
  %22 = load %array*, %array** %11, align 8
  %23 = getelementptr %array, %array* %22, i32 0, i32 1
  store i32 0, i32* %23, align 4
  %24 = getelementptr %array, %array* %22, i32 0, i32 2
  %25 = load %dimension_descriptor*, %dimension_descriptor** %24, align 8
  %26 = getelementptr inbounds %dimension_descriptor, %dimension_descriptor* %25, i32 0
  %27 = getelementptr %dimension_descriptor, %dimension_descriptor* %26, i32 0, i32 0
  %28 = getelementptr %dimension_descriptor, %dimension_descriptor* %26, i32 0, i32 1
  %29 = getelementptr %dimension_descriptor, %dimension_descriptor* %26, i32 0, i32 2
  store i32 1, i32* %27, align 4
  store i32 1, i32* %28, align 4
  store i32 2, i32* %29, align 4
  %30 = getelementptr %array, %array* %22, i32 0, i32 0
  %31 = alloca i32, align 4
  store i32 8, i32* %31, align 4
  %32 = load i32, i32* %31, align 4
  %33 = call i8* @_lfortran_malloc(i32 %32)
  %34 = bitcast i8* %33 to float*
  store float* %34, float** %30, align 8
  call void @_lpython_free_argv()
  br label %return

return:                                           ; preds = %ifcont
  ret i32 0
}

declare void @_lpython_call_initial_functions(i32, i8**)

declare i8* @_lfortran_malloc(i32)

declare void @_lpython_free_argv()
```

We have similar line `store i32 0, i32* %23, align 4`, it works. This implies that somehow `i32* %25` i.e. `getelementptr %array, %array* %24, i32 0, i32 1` or anything related to `f` is nullptr in our example. Taking a closer look at LLVM of `b.f90` we see that `s` gets allocated space at the beginning of program which means `s%f` is also allocated a space on stack but filled with null:


```llvm
  %s = alloca %sds, align 8
  %2 = getelementptr %sds, %sds* %s, i32 0, i32 0
  %3 = getelementptr %sds, %sds* %s, i32 0, i32 2
  store %array* null, %array** %3, align 8
  %arr_desc = alloca %array, align 8
  %4 = getelementptr %array, %array* %arr_desc, i32 0, i32 2
``


Whereas for our example, there is no place we allocate `rp1d` on stack and thus when we try to access it segfaults.

**Comment by Pranavchiku** [comment]
The allocation issue is resolve, now problem lies in accessing `s%scales(1)%f`, `s%scales(1)%f(1)` works well.

**Comment by Pranavchiku** [comment]
With #6546 allocation problem is fixed, print causes a problem which is independent. I created an issue for this: https://github.com/lfortran/lfortran/issues/6547
