### ISSUE TITLE
(PRIMA) Handle array assigning with array constant as reference

### ISSUE THREAD

**Issue by jinangshah21** [lfortran/lfortran#5656]
Towards #4397
Example 1 : 
```fortran
program test
    integer :: A(4) = [1,2,3,4]
    call temp(A)
    print *, A
contains
    subroutine temp(A)
        integer, intent(inout) :: A(:)
        A([1,2]) = [5,5]
    end subroutine
end program
```
Lfortran Error : 
```console
lfortran: /home/jinu2110/conda_root/envs/lf/include/llvm/IR/IRBuilder.h:1989: llvm::Value* llvm::IRBuilderBase::CreateSExtOrTrunc(llvm::Value*, llvm::Type*, const llvm::Twine&): Assertion `V->getType()->isIntOrIntVectorTy() && DestTy->isIntOrIntVectorTy() && "Can only sign extend/truncate integers!"' failed.
Traceback (most recent call last):
  Binary file "/mnt/c/lfortran/src/bin/lfortran", in _start
  File "/build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c", line 308, in __libc_start_main
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2732, in main
    return main_app(argc, argv);
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2670, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 1049, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/mnt/c/lfortran/src/lfortran/fortran_evaluator.cpp", line 382, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10404, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 316, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 292, in void LCompilers::ASR::visit_asr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::asr_t const&, LCompilers::ASRToLLVMVisitor&)
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 317, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 22, in void LCompilers::ASR::visit_unit_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::unit_t const&, LCompilers::ASRToLLVMVisitor&)
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 988, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 319, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 30, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToLLVMVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3253, in LCompilers::ASRToLLVMVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    visit_procedures(x);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4299, in void LCompilers::ASRToLLVMVisitor::visit_procedures<LCompilers::ASR::Program_t>(LCompilers::ASR::Program_t const&)
    visit_Function(*s);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4055, in LCompilers::ASRToLLVMVisitor::visit_Function(LCompilers::ASR::Function_t const&)
    generate_function(x);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4251, in LCompilers::ASRToLLVMVisitor::generate_function(LCompilers::ASR::Function_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 336, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 56, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5029, in LCompilers::ASRToLLVMVisitor::visit_Assignment(LCompilers::ASR::Assignment_t const&)
    this->visit_expr(*x.m_target);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 384, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 173, in void LCompilers::ASR::visit_expr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ASRToLLVMVisitor&)
    case exprType::ArrayItem: { v.visit_ArrayItem((const ArrayItem_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2436, in LCompilers::ASRToLLVMVisitor::visit_ArrayItem(LCompilers::ASR::ArrayItem_t const&)
    tmp = arr_descr->get_single_element(type, array, indices, x.n_args,
  File "/mnt/c/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 670, in LCompilers::LLVMArrUtils::SimpleCMODescriptor::get_single_element(llvm::Type*, llvm::Value*, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&, int, bool, bool, llvm::Value**, bool, llvm::Type*, bool)
    idx = cmo_convertor_single_element_data_only(llvm_diminfo, m_args, n_args, check_for_bounds, is_unbounded_pointer_to_data);
  File "/mnt/c/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 642, in LCompilers::LLVMArrUtils::SimpleCMODescriptor::cmo_convertor_single_element_data_only(llvm::Value**, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&, int, bool, bool)
    curr_llvm_idx = builder->CreateSExtOrTrunc(curr_llvm_idx, llvm::Type::getInt32Ty(context));
  File "/home/jinu2110/conda_root/envs/lf/include/llvm/IR/IRBuilder.h", line 1989, in llvm::IRBuilderBase::CreateSExtOrTrunc(llvm::Value*, llvm::Type*, llvm::Twine const&)
    assert(V->getType()->isIntOrIntVectorTy() &&
  File "/build/glibc-LcI20x/glibc-2.31/assert/assert.c", line 101, in __assert_fail
  File "/build/glibc-LcI20x/glibc-2.31/assert/assert.c", line 92, in __assert_fail_base
  File "/build/glibc-LcI20x/glibc-2.31/stdlib/abort.c", line 79, in abort
  File "/build/glibc-LcI20x/glibc-2.31/signal/../sysdeps/unix/sysv/linux/internal-signals.h", line 86, in raise
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in <invalid>
Abort: Signal SIGABRT (abort) received

Aborted (core dumped)
```

Example 2 : 
```fortran
program test
    integer :: A(4) = [1,2,3,4]
    call temp(A)
    print *, A
contains
    subroutine temp(A)
        integer, intent(inout) :: A(:)
        A([1,2]) = A([2,1])
    end subroutine
end program
```

LFortran output : 
```console
(lf) jinu2110@JNSLAP:/mnt/c/lfortran$ lfortran a.f90 
1    2    3    4
```

Expected output : `2 1 3 4`

**Comment by jinangshah21** [comment]
Also this should handle multi-dimension arrays

**Comment by AnshMehta1** [comment]
I will work on these array assignment issues.
