### ISSUE TITLE
(PRIMA) Handle Array assigning with ArraySection and ArrayConstant as reference

### ISSUE THREAD

**Issue by jinangshah21** [lfortran/lfortran#5657]
MRE : 
```fortran
program test
    integer :: A(2,2) = reshape([1,2,3,4],[2,2])
    call temp(A)
    print *, A
contains
    subroutine temp(A)
        integer, intent(inout) :: A(:,:)
        A(:, [2,1]) = A(:, [1,2])
    end subroutine
end program
```

LFortran Error : 
```console
Traceback (most recent call last):
  Binary file "/mnt/c/lfortran/src/bin/lfortran", in _start
  File "/build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c", line 308, in __libc_start_main
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2732, in main
    return main_app(argc, argv);
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2670, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 1049, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/mnt/c/lfortran/src/lfortran/fortran_evaluator.cpp", line 382, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10398, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/mnt/c/lfortran/src/libasr/pass/pass_manager.h", line 403, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/mnt/c/lfortran/src/libasr/pass/pass_manager.h", line 180, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/mnt/c/lfortran/src/libasr/pass/array_op.cpp", line 2471, in LCompilers::pass_replace_array_op(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    u.visit_TranslationUnit(unit);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_walk_visitor.h", line 28, in LCompilers::ASR::BaseWalkVisitor<LCompilers::PassUtils::UpdateDependenciesVisitor>::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/mnt/c/lfortran/src/libasr/asr_base_visitor.h", line 319, in LCompilers::ASR::BaseVisitor<LCompilers::PassUtils::UpdateDependenciesVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/asr_base_visitor.h", line 30, in void LCompilers::ASR::visit_symbol_t<LCompilers::PassUtils::UpdateDependenciesVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::PassUtils::UpdateDependenciesVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/asr_walk_visitor.h", line 33, in LCompilers::ASR::BaseWalkVisitor<LCompilers::PassUtils::UpdateDependenciesVisitor>::visit_Program(LCompilers::ASR::Program_t const&)
    this->visit_symbol(*a.second);
  File "/mnt/c/lfortran/src/libasr/asr_base_visitor.h", line 319, in LCompilers::ASR::BaseVisitor<LCompilers::PassUtils::UpdateDependenciesVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/asr_base_visitor.h", line 32, in void LCompilers::ASR::visit_symbol_t<LCompilers::PassUtils::UpdateDependenciesVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::PassUtils::UpdateDependenciesVisitor&)
    case symbolType::Function: { v.visit_Function((const Function_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/pass/pass_utils.h", line 429, in LCompilers::PassUtils::UpdateDependenciesVisitor::visit_Function(LCompilers::ASR::Function_t const&)
    BaseWalkVisitor<UpdateDependenciesVisitor>::visit_Function(x);
  File "/mnt/c/lfortran/src/libasr/asr_walk_visitor.h", line 53, in LCompilers::ASR::BaseWalkVisitor<LCompilers::PassUtils::UpdateDependenciesVisitor>::visit_Function(LCompilers::ASR::Function_t const&)
    self().visit_stmt(*x.m_body[i]);
  File "/mnt/c/lfortran/src/libasr/asr_base_visitor.h", line 336, in LCompilers::ASR::BaseVisitor<LCompilers::PassUtils::UpdateDependenciesVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/asr_base_visitor.h", line 62, in void LCompilers::ASR::visit_stmt_t<LCompilers::PassUtils::UpdateDependenciesVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::PassUtils::UpdateDependenciesVisitor&)
    case stmtType::DoLoop: { v.visit_DoLoop((const DoLoop_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/asr_walk_visitor.h", line 202, in LCompilers::ASR::BaseWalkVisitor<LCompilers::PassUtils::UpdateDependenciesVisitor>::visit_DoLoop(LCompilers::ASR::DoLoop_t const&)
    self().visit_stmt(*x.m_body[i]);
  File "/mnt/c/lfortran/src/libasr/asr_base_visitor.h", line 336, in LCompilers::ASR::BaseVisitor<LCompilers::PassUtils::UpdateDependenciesVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/asr_base_visitor.h", line 56, in void LCompilers::ASR::visit_stmt_t<LCompilers::PassUtils::UpdateDependenciesVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::PassUtils::UpdateDependenciesVisitor&)
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/asr_walk_visitor.h", line 160, in LCompilers::ASR::BaseWalkVisitor<LCompilers::PassUtils::UpdateDependenciesVisitor>::visit_Assignment(LCompilers::ASR::Assignment_t const&)
    self().visit_expr(*x.m_target);
  File "/mnt/c/lfortran/src/libasr/asr_base_visitor.h", line 384, in LCompilers::ASR::BaseVisitor<LCompilers::PassUtils::UpdateDependenciesVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/asr_base_visitor.h", line 105, in void LCompilers::ASR::visit_expr_t<LCompilers::PassUtils::UpdateDependenciesVisitor>(LCompilers::ASR::expr_t const&, LCompilers::PassUtils::UpdateDependenciesVisitor&)
    LCOMPILERS_ASSERT(x.base.type == asrType::expr)
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in <invalid>
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by jinangshah21** [comment]
Closed as done with simplifier.
