### ISSUE TITLE
A variety of blank COMMON bugs

### ISSUE THREAD

**Issue by pjh40** [lfortran/lfortran#5661]
Compiling
```f90
PROGRAM FM011
  COMMON IACE11(3)
  IACE11(1) = 1
END PROGRAM FM011
```
with
```../lfortran/src/bin/lfortran --implicit-typing  ha.f90          
semantic error: Function 'iace11' not found (not user defined nor intrinsic)
 --> ha.f90:2:10
  |
2 |   COMMON IACE11(3)
  |          ^^^^^^^^^ 
```
The common declaration should be creating the equivalent of `INTEGER :: IACE11(3)`, but lfortran thinks that it is a function.  gfortran compiles correctly.

If we add `--implicit-interface`, then we get an unhandled exception:
```
(lf) FCVS_95 % ../lfortran/src/bin/lfortran --implicit-typing --implicit-interface  ha.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/phenning/Packages/lfortran/src/bin/lfortran.cpp", line 2732, in main
    return main_app(argc, argv);
  File "/Users/phenning/Packages/lfortran/src/bin/lfortran.cpp", line 2670, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/Users/phenning/Packages/lfortran/src/bin/lfortran.cpp", line 1006, in (anonymous namespace)::compile_src_to_object_file(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/phenning/Packages/lfortran/src/lfortran/fortran_evaluator.cpp", line 275, in LCompilers::FortranEvaluator::get_asr2(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/phenning/Packages/lfortran/src/lfortran/fortran_evaluator.cpp", line 296, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
    auto res = LFortran::ast_to_asr(al, ast, diagnostics, symbol_table,
  File "/Users/phenning/Packages/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 69, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    auto res = symbol_table_visitor(al, ast, diagnostics, symbol_table,
  File "/Users/phenning/Packages/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 3852, in LCompilers::LFortran::symbol_table_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, LCompilers::CompilerOptions&, std::__1::map<unsigned long long, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, LCompilers::ASR::ttype_t*, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::__1::less<unsigned long long>, std::__1::allocator<std::__1::pair<unsigned long long const, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, LCompilers::ASR::ttype_t*, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::__1::map<unsigned long long, LCompilers::ASR::symbol_t*, std::__1::less<unsigned long long>, std::__1::allocator<std::__1::pair<unsigned long long const, LCompilers::ASR::symbol_t*> > >&, std::__1::map<unsigned long long, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, std::__1::less<unsigned long long>, std::__1::allocator<std::__1::pair<unsigned long long const, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > > >&, std::__1::map<unsigned int, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, LCompilers::ASR::ttype_t*, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, LCompilers::ASR::ttype_t*, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::__1::map<unsigned int, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, LCompilers::ASR::symbol_t*, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, LCompilers::ASR::symbol_t*, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<LCompilers::LFortran::AST::stmt_t*, std::__1::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<LCompilers::LFortran::AST::stmt_t*, std::__1::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<LCompilers::LFortran::AST::stmt_t*, std::__1::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<LCompilers::LFortran::AST::stmt_t*, std::__1::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<int, std::__1::allocator<int> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<int, std::__1::allocator<int> > > > >&, std::__1::vector<LCompilers::ASR::stmt_t*, std::__1::allocator<LCompilers::ASR::stmt_t*> >&)
    v.visit_TranslationUnit(ast);
  File "/Users/phenning/Packages/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 132, in LCompilers::LFortran::SymbolTableVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/Users/phenning/Packages/lfortran/src/lfortran/ast.h", line 4943, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/phenning/Packages/lfortran/src/lfortran/ast.h", line 4899, in void LCompilers::LFortran::AST::visit_ast_t<LCompilers::LFortran::SymbolTableVisitor>(LCompilers::LFortran::AST::ast_t const&, LCompilers::LFortran::SymbolTableVisitor&)
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/Users/phenning/Packages/lfortran/src/lfortran/ast.h", line 4946, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/phenning/Packages/lfortran/src/lfortran/ast.h", line 4524, in void LCompilers::LFortran::AST::visit_mod_t<LCompilers::LFortran::SymbolTableVisitor>(LCompilers::LFortran::AST::mod_t const&, LCompilers::LFortran::SymbolTableVisitor&)
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/Users/phenning/Packages/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 578, in LCompilers::LFortran::SymbolTableVisitor::visit_Program(LCompilers::LFortran::AST::Program_t const&)
    visit_unit_decl2(*x.m_decl[i]);
  File "/Users/phenning/Packages/lfortran/src/lfortran/ast.h", line 4957, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_unit_decl2(LCompilers::LFortran::AST::unit_decl2_t const&)
    void visit_unit_decl2(const unit_decl2_t &b) { visit_unit_decl2_t(b, self()); }
  File "/Users/phenning/Packages/lfortran/src/lfortran/ast.h", line 4550, in void LCompilers::LFortran::AST::visit_unit_decl2_t<LCompilers::LFortran::SymbolTableVisitor>(LCompilers::LFortran::AST::unit_decl2_t const&, LCompilers::LFortran::SymbolTableVisitor&)
    case unit_decl2Type::Declaration: { v.visit_Declaration((const Declaration_t &)x); return; }
  File "/Users/phenning/Packages/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1721, in LCompilers::LFortran::SymbolTableVisitor::visit_Declaration(LCompilers::LFortran::AST::Declaration_t const&)
    visit_DeclarationUtil(x);
  File "/Users/phenning/Packages/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 2399, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_DeclarationUtil(LCompilers::LFortran::AST::Declaration_t const&)
    populate_common_dictionary(x, common_block_struct_sym, struct_type, common_block_name, i);
  File "/Users/phenning/Packages/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 2081, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::SymbolTableVisitor>::populate_common_dictionary(LCompilers::LFortran::AST::Declaration_t const&, LCompilers::ASR::symbol_t*, LCompilers::ASR::Struct_t*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long&)
    ASR::Variable_t* var_ = extract_common_variable(expr, x.base.base.loc, s.loc);
  File "/Users/phenning/Packages/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 2070, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::SymbolTableVisitor>::extract_common_variable(LCompilers::LFortran::AST::expr_t*, LCompilers::Location, LCompilers::Location)
    var_ = ASRUtils::EXPR2VAR(ASRUtils::EXPR(tmp));
  File "/Users/phenning/Packages/lfortran/src/libasr/asr_utils.h", line 319, in LCompilers::ASRUtils::EXPR2VAR(LCompilers::ASR::expr_t const*)
    ASR::down_cast<ASR::Var_t>(f)->m_v));
  File "/Users/phenning/Packages/lfortran/src/libasr/asr.h", line 41, in LCompilers::ASR::Var_t* LCompilers::ASR::down_cast<LCompilers::ASR::Var_t, LCompilers::ASR::expr_t>(LCompilers::ASR::expr_t const*)
    LCOMPILERS_ASSERT(is_a<T>(*f));
AssertFailed: is_a<T>(*f)
```
and, finally if we use the legal alternative syntax for blank common:
```f90
PROGRAM FM011
  COMMON // IACE11(3)
  IACE11(1) = 1
END PROGRAM FM011
```
we get the invalid syntax error 
```
(lf) FCVS_95 % ../lfortran/src/bin/lfortran --implicit-typing  ha.f90          
syntax error: Newline is unexpected here
 --> ha.f90:2:22
  |
2 |   COMMON // IACE11(3)
  |                      ^ 
```
regardless of command-line options.

**Comment by certik** [comment]
Here is our main issue for common blocks: https://github.com/lfortran/lfortran/issues/661, we haven't implemented them yet, but probably should soon.

**Comment by pjh40** [comment]
Closed by #5811
