### ISSUE TITLE
internal compile error for assumed rank subroutine argument

### ISSUE THREAD

**Issue by gxyd** [lfortran/lfortran#5685]
## Minimal Reproducible Example

For the below Fortran program:
```f90
program main
    implicit none
    contains

    subroutine MPI_Allreduce(sendbuf)
        real(8), dimension(..), intent(in) :: sendbuf
    end subroutine

    subroutine magnetic_energy
        implicit none
        real(8), parameter :: MPI_IN_PLACE = 1
        integer, parameter :: MPI_SUM = 1
        call MPI_Allreduce(MPI_IN_PLACE)
    end subroutine
end program main

```

on running the above program as below, I get an error:

```console
> lfortran test.f90 --show-llvm
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2729
    LCompilers::print_stack_on_segfault();
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2670
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 1049
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 382
    compiler_options, run_fn, infile);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10431
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/pass_manager.h", line 399
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/pass_manager.h", line 180
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 777
    u.visit_TranslationUnit(unit);
  File "src/libasr/../libasr/asr_pass_walk_visitor.h", line 34
    for (auto &a : x.m_symtab->get_scope()) {
  File "src/libasr/../libasr/asr_base_visitor.h", line 319
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "src/libasr/../libasr/asr_base_visitor.h", line 30
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "src/libasr/../libasr/asr_pass_walk_visitor.h", line 43
    for (auto &a : x.m_symtab->get_scope()) {
  File "src/libasr/../libasr/asr_base_visitor.h", line 319
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "src/libasr/../libasr/asr_base_visitor.h", line 31
    case symbolType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "src/libasr/../libasr/asr_pass_walk_visitor.h", line 68
    self().transform_stmts(xx.m_body, xx.n_body);
  File "src/libasr/../libasr/asr_pass_walk_visitor.h", line 28
    self().visit_stmt(*m_body[i]);
  File "src/libasr/../libasr/asr_base_visitor.h", line 336
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "src/libasr/../libasr/asr_base_visitor.h", line 81
    case stmtType::Assert: { v.visit_Assert((const Assert_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 626
    visit_Call(x);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 590
    throw LCompilersException("Number of arguments in the new function call " +
LCompilersException: Number of arguments in the new function call mpi_allreduce doesn't satisfy min_args <= new_args.size() <= max_args, 3 <= 1 <= 3
```

GFortran compiles and runs the program without any error.

**Comment by certik** [comment]
Note that this is not needed for POT3D. The way to do the MPI is as follows:
```
interface MPI_Allreduce
    subroutine MPI_Allreduce_1d(sendbuf)
        real(8), dimension(:), intent(in) :: sendbuf
    end subroutine
    subroutine MPI_Allreduce_2d(sendbuf)
        real(8), dimension(:,:), intent(in) :: sendbuf
    end subroutine
end interface
```
etc.

**Comment by gxyd** [comment]
I'm not really sure of the support that we've for assumed rank arrays in LFortran though.

It's also possible that to continue with compilation of POT3D, we can find a better workaround as the MRE is mostly because of how the code in `mpi.f90` file is written here: https://github.com/gxyd/POT3D/blob/mpi_with_workaround/src/mpi.f90#L31-L37

**Comment by gxyd** [comment]
> Note that this is not needed for POT3D. The way to do the MPI is as follows:

Yes, I realized this and I think we need to improve the `mpi.f90` for that now.

**Comment by gxyd** [comment]
I've removed the POT3D label, as this can be fixed without us depending on this issue to be fixed to continue with *POT3D* compilation.

**Comment by dsaw** [comment]
from the looks of it, the assumer rank is not implemented right? I would like to take a look at it if this feasible.  any directions on how to go about it?

**Comment by certik** [comment]
You have to debug the compiler internals to understand why it fails and then fix it. Test the Fortran test code with gfortran first to ensure it is correct, and then we implement it in LFortran to also work.
