### ISSUE TITLE
fix findloc to handle different  (conformable) types of `array` and `value` argument

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#5711]
```fortran
program main
    real(8), dimension(2) :: dc = [1.3, 2.3]
    real :: x = 1
    print *, findloc(dc, x)
end program
```
```console
$ gfortran a.f90 && ./a.out
           0
(lf) (base) harshita@harshita-linux:~/Desktop/lfortran$ lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2732, in main
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2670, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
...
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/intrinsic_function.cpp", line 137, in LCompilers::ReplaceIntrinsicFunctions::replace_IntrinsicArrayFunction(LCompilers::ASR::IntrinsicArrayFunction_t*)
    ASR::expr_t* current_expr_ = instantiate_function(al, x->base.base.loc,
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/pass/intrinsic_array_function_registry.h", line 3572, in LCompilers::ASRUtils::FindLoc::instantiate_FindLoc(Allocator&, LCompilers::Location const&, LCompilers::SymbolTable*, LCompilers::Vec<LCompilers::ASR::ttype_t*>&, LCompilers::ASR::ttype_t*, LCompilers::Vec<LCompilers::ASR::call_arg_t>&, long)
    b.If(b.Eq(ArrayItem_02(array, i), value), {
AssertFailed: check_equal_type(expr_type(left), expr_type(right))
```

**Comment by HarshitaKalani** [comment]
The following should work too.
```fortran
program main
    integer(8), dimension(2) :: dc = [1.4, 2.3]
    real :: x = 1.3
    print *, findloc(dc, x)
end program
```
```console
$ gfortran a.f90 && ./a.out
           1
$ lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start
 ...
    b.If(b.Eq(ArrayItem_02(array, i), value), {
AssertFailed: check_equal_type(expr_type(left), expr_type(right))
```
