### ISSUE TITLE
Third party codes to be compiled with `--experimental-simplifier`

### ISSUE THREAD

**Issue by czgdp1807** [lfortran/lfortran#5717]
Following are the third party tests which need to be compiled with `--experimental-simplifier`,

- [x] PRIMA
- [x] POT3D
- [x] Legacy Minpack (SciPy)
- [x] Modern Minpack (Fortran-Lang)
- [x] Modern Minpack (check results)
- [x] dftatom
- [x] dftatom (with `--fast`)
- [x] fastGPT
- [x] fastGPT (with `--fast`)
- [x] fpm
- [x] stdlib
- [x] SNAP
- [x] SNAP (with `--fast`)

Basic intent is to make everything work with `--experimental-simplifier` which used to work with older LFortran.

**Comment by Pranavchiku** [comment]
Awesome, PRIMA is a very good candidate vouching for PRIMA. Almost every MRE we submit against main works with `--experimental-simplifier`.

**Comment by czgdp1807** [comment]
Only one left here. PRIMA.

**Comment by harperjf** [comment]
In my Linux system the command ```man lfortran``` lists what I had presumed was all the valid options. It doe not include ```--experimental-simplifier```. Could it list all of them, please?

**Comment by certik** [comment]
That option is not meant for end users to use, it's just a temporary option that we will remove once we switch to the new simplifier pass.

**Comment by gxyd** [comment]
@czgdp1807 I've reported the MRE for *PRIMA* here : https://github.com/lfortran/lfortran/issues/5795, I think that can act as a good MRE for *simplifier pass*.

As for fixing the issue, anyone can take up that issue to fix, as my availability is on and off.

**Comment by gxyd** [comment]
Current status of *PRIMA* compilation with LFortran:
```console
> lfortran --version
LFortran version: 0.42.0-706-gbfdd6ad0a-dirty
Platform: macOS ARM
LLVM: 11.1.0
Default target: arm64-apple-darwin23.6.0

> FC="$(pwd)/../src/bin/lfortran --cpp --skip-pass=pass_array_by_data --experimental-simplifier" cmake -S . -B build -DCMAKE_INSTALL_PREFIX=$(pwd)/install -DCMAKE_Fortran_FLAGS=""  -DCMAKE_SHARED_LIBRARY_CREATE_Fortran_FLAGS=""  -DCMAKE_MACOSX_RPATH=OFF -DCMAKE_SKIP_INSTALL_RPATH=ON  -DCMAKE_SKIP_RPATH=ON && cmake --build build --target install -j1

...
...

[ 80%] Building Fortran object fortran/CMakeFiles/example_cobyla_fortran_2_exe.dir/examples/cobyla/cobyla_example_2.f90.o
[ 81%] Linking Fortran executable example_cobyla_fortran_2_exe
[ 81%] Built target example_cobyla_fortran_2_exe
[ 82%] Building Fortran object fortran/CMakeFiles/example_bobyqa_fortran_1_exe.dir/examples/bobyqa/bobyqa_example_1.f90.o
LCOMPILERS_ASSERT failed: /Users/gxyd/OpenSource/lfortran/src/libasr/asr_utils.cpp
function make_ArraySize_t_util(), line number 2086 at 
ASR::is_a<ASR::Var_t>(*a_v) || ASR::is_a<ASR::StructInstanceMember_t>(*a_v) || ASR::is_a<ASR::FunctionParam_t>(*a_v)
ERROR MESSAGE:
Found ASR::exprType::66
Traceback (most recent call last):
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2726
    LCompilers::print_stack_on_segfault();
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2622
    return compile_src_to_object_file(arg_file, outfile, false,
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 1050
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 382
    compiler_options, run_fn, infile);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10456
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/pass_manager.h", line 403
    apply_passes(al, asr, _passes_with_experimental_simplifier, pass_options, diagnostics);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/pass_manager.h", line 180
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/implied_do_loops.cpp", line 787
    v.visit_TranslationUnit(unit);
  File "src/libasr/../libasr/asr_expr_call_replacer_visitor.h", line 39
  File "src/libasr/../libasr/asr_base_visitor.h", line 319
  File "src/libasr/../libasr/asr_base_visitor.h", line 30
  File "src/libasr/../libasr/asr_expr_call_replacer_visitor.h", line 57
  File "src/libasr/../libasr/asr_base_visitor.h", line 319
  File "src/libasr/../libasr/asr_base_visitor.h", line 31
  File "src/libasr/../libasr/asr_expr_call_replacer_visitor.h", line 78
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/implied_do_loops.cpp", line 524
    visit_stmt(*m_body[i]);
  File "src/libasr/../libasr/asr_base_visitor.h", line 336
  File "src/libasr/../libasr/asr_base_visitor.h", line 67
  File "src/libasr/../libasr/asr_expr_call_replacer_visitor.h", line 384
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/implied_do_loops.cpp", line 524
    visit_stmt(*m_body[i]);
  File "src/libasr/../libasr/asr_base_visitor.h", line 336
  File "src/libasr/../libasr/asr_base_visitor.h", line 55
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/implied_do_loops.cpp", line 561
    current_expr = const_cast<ASR::expr_t**>(&(x.m_value));
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/implied_do_loops.cpp", line 505
    replacer.replace_expr(*current_expr);
  File "src/libasr/../libasr/asr_expr_base_replacer_visitor.h", line 1974
  File "src/libasr/../libasr/asr_expr_base_replacer_visitor.h", line 114
  File "src/libasr/../libasr/asr_expr_base_replacer_visitor.h", line 1978
  File "src/libasr/../libasr/asr_expr_base_replacer_visitor.h", line 131
  File "src/libasr/../libasr/asr_expr_base_replacer_visitor.h", line 2302
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/implied_do_loops.cpp", line 440
    ASR::BaseExprReplacer<ReplaceArrayConstant>::replace_ArrayPhysicalCast(x);
  File "src/libasr/../libasr/asr_expr_base_replacer_visitor.h", line 1496
  File "src/libasr/../libasr/asr_expr_base_replacer_visitor.h", line 2214
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/implied_do_loops.cpp", line 344
    PassUtils::ReplacerUtils::replace_ArrayConstructor_(al, x, result_var,
  File "src/libasr/../libasr/pass/pass_utils.h", line 1017
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/pass_utils.cpp", line 1435
    ASR::expr_t* curr_init_array_size_for_type = ASRUtils::get_size(curr_init, al, true);
  File "src/libasr/../libasr/asr_utils.h", line 4924
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/asr_utils.cpp", line 2047
    return make_ArraySize_t_util(al, a_loc, extract_member_from_binop(a_v, 0), a_dim, a_type, a_value, for_type);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/asr_utils.cpp", line 2082
    LCOMPILERS_ASSERT_MSG(
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x180356a2f
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x180449c1f
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x18047a583
Abort: Signal SIGABRT (abort) received

/bin/sh: line 1: 47909 Abort trap: 6           /Users/gxyd/OpenSource/lfortran/src/bin/lfortran --cpp --skip-pass=pass_array_by_data --experimental-simplifier -DPRIMA_INTEGER_KIND=0 -DPRIMA_REAL_PRECISION=64 -I/Users/gxyd/OpenSource/lfortran/prima/build/fortran -I/Users/gxyd/OpenSource/lfortran/prima/build/fortran/mod --cpp -c /Users/gxyd/OpenSource/lfortran/prima/fortran/examples/bobyqa/bobyqa_example_1.f90 -o CMakeFiles/example_bobyqa_fortran_1_exe.dir/examples/bobyqa/bobyqa_example_1.f90.o
make[2]: *** [fortran/CMakeFiles/example_bobyqa_fortran_1_exe.dir/build.make:75: fortran/CMakeFiles/example_bobyqa_fortran_1_exe.dir/examples/bobyqa/bobyqa_example_1.f90.o] Error 134
make[1]: *** [CMakeFiles/Makefile2:277: fortran/CMakeFiles/example_bobyqa_fortran_1_exe.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

```

I've reported an MRE for this failure here: https://github.com/lfortran/lfortran/issues/5807

**Comment by czgdp1807** [comment]
Completed in https://github.com/lfortran/lfortran/pull/5822
