### ISSUE TITLE
segfault with simplifier pass for nested intrinsic function call

### ISSUE THREAD

**Issue by gxyd** [lfortran/lfortran#5807]
## Minimal Reproducible Example

```f90
module preproc_mod
    implicit none
    public :: preproc

    contains

    function falseloc(x) result(loc)
        implicit none

        logical, intent(in) :: x(:)
        integer, allocatable :: loc(:)
    end function falseloc

    subroutine preproc(n, rhobeg, rhoend, xl, xu, x0)
        implicit none

        integer, intent(in) :: n

        real, intent(in), optional :: xl(:)
        real, intent(in), optional :: xu(:)
        
        real, intent(inout) :: rhobeg
        real, intent(inout) :: rhoend

        real, intent(inout), optional :: x0(:)
        real, parameter :: ZERO = 0.0_4
        real, parameter :: EPS = epsilon(ZERO)

        logical :: lbx(n)
        rhobeg = max(EPS, minval([rhobeg, x0(falseloc(lbx)) - xl(falseloc(lbx))]))
    end subroutine preproc

end module preproc_mod

program main
    use preproc_mod
    implicit none
end program main

```

For the above fortran program on it's execution with LFortran, it works *without* use of *simplifier pass* but fails when *simplifier pass* is used, see the commands below:
```console
> lfortran --version
LFortran version: 0.42.0-706-gbfdd6ad0a-dirty
Platform: macOS ARM
LLVM: 11.1.0
Default target: arm64-apple-darwin23.6.0

> lfortran test.f90
> echo $?
0

> lfortran test.f90 --experimental-simplifier
LCOMPILERS_ASSERT failed: /Users/gxyd/OpenSource/lfortran/src/libasr/asr_utils.cpp
function make_ArraySize_t_util(), line number 2086 at 
ASR::is_a<ASR::Var_t>(*a_v) || ASR::is_a<ASR::StructInstanceMember_t>(*a_v) || ASR::is_a<ASR::FunctionParam_t>(*a_v)
ERROR MESSAGE:
Found ASR::exprType::66
Traceback (most recent call last):
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2726
    LCompilers::print_stack_on_segfault();
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2667
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 1050
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 382
    compiler_options, run_fn, infile);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10456
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/pass_manager.h", line 403
    apply_passes(al, asr, _passes_with_experimental_simplifier, pass_options, diagnostics);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/pass_manager.h", line 180
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/implied_do_loops.cpp", line 787
    v.visit_TranslationUnit(unit);
  File "src/libasr/../libasr/asr_expr_call_replacer_visitor.h", line 39
    for (auto &a : x.m_symtab->get_scope()) {
  File "src/libasr/../libasr/asr_base_visitor.h", line 319
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "src/libasr/../libasr/asr_base_visitor.h", line 30
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "src/libasr/../libasr/asr_expr_call_replacer_visitor.h", line 57
    for (auto &a : x.m_symtab->get_scope()) {
  File "src/libasr/../libasr/asr_base_visitor.h", line 319
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "src/libasr/../libasr/asr_base_visitor.h", line 31
    case symbolType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "src/libasr/../libasr/asr_expr_call_replacer_visitor.h", line 78
    self().transform_stmts(xx.m_body, xx.n_body);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/implied_do_loops.cpp", line 524
    visit_stmt(*m_body[i]);
  File "src/libasr/../libasr/asr_base_visitor.h", line 336
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "src/libasr/../libasr/asr_base_visitor.h", line 55
    case stmtType::Assign: { v.visit_Assign((const Assign_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/implied_do_loops.cpp", line 561
    current_expr = const_cast<ASR::expr_t**>(&(x.m_value));
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/implied_do_loops.cpp", line 505
    replacer.replace_expr(*current_expr);
  File "src/libasr/../libasr/asr_expr_base_replacer_visitor.h", line 1974
    self().replace_IntrinsicElementalFunction(down_cast<ASR::IntrinsicElementalFunction_t>(x));
  File "src/libasr/../libasr/asr_expr_base_replacer_visitor.h", line 114
    self().replace_expr(x->m_args[i]);
  File "src/libasr/../libasr/asr_expr_base_replacer_visitor.h", line 1978
    self().replace_IntrinsicArrayFunction(down_cast<ASR::IntrinsicArrayFunction_t>(x));
  File "src/libasr/../libasr/asr_expr_base_replacer_visitor.h", line 131
    self().replace_expr(x->m_args[i]);
  File "src/libasr/../libasr/asr_expr_base_replacer_visitor.h", line 2302
    self().replace_ArrayPhysicalCast(down_cast<ASR::ArrayPhysicalCast_t>(x));
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/implied_do_loops.cpp", line 440
    ASR::BaseExprReplacer<ReplaceArrayConstant>::replace_ArrayPhysicalCast(x);
  File "src/libasr/../libasr/asr_expr_base_replacer_visitor.h", line 1496
    self().replace_expr(x->m_arg);
  File "src/libasr/../libasr/asr_expr_base_replacer_visitor.h", line 2214
    self().replace_ArrayConstructor(down_cast<ASR::ArrayConstructor_t>(x));
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/implied_do_loops.cpp", line 344
    PassUtils::ReplacerUtils::replace_ArrayConstructor_(al, x, result_var,
  File "src/libasr/../libasr/pass/pass_utils.h", line 1017
    visit_ArrayConstructor(x, al, result_var, result_vec,
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/pass_utils.cpp", line 1435
    ASR::expr_t* curr_init_array_size_for_type = ASRUtils::get_size(curr_init, al, true);
  File "src/libasr/../libasr/asr_utils.h", line 4924
    return ASRUtils::EXPR(ASRUtils::make_ArraySize_t_util(al, arr_expr->base.loc, arr_expr, nullptr, int32_type, nullptr, for_type));
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/asr_utils.cpp", line 2047
    return make_ArraySize_t_util(al, a_loc, extract_member_from_binop(a_v, 0), a_dim, a_type, a_value, for_type);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/asr_utils.cpp", line 2082
    LCOMPILERS_ASSERT_MSG(
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x180356a2f
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x180449c1f
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x18047a583
Abort: Signal SIGABRT (abort) received

[1]    47345 abort      /Users/gxyd/OpenSource/lfortran/src/bin/lfortran test.f90
```

This can act as an MRE for current failure of *PRIMA* with *simplifier pass* enabled here: https://github.com/lfortran/lfortran/issues/5717

**Comment by gxyd** [comment]
A workaround for this is:
```diff
diff --git a/test.f90 b/test.f90
index 537db9cf5..b8b1eb117 100644
--- a/test.f90
+++ b/test.f90
@@ -27,7 +27,9 @@ module preproc_mod
         real, parameter :: EPS = epsilon(ZERO)
 
         logical :: lbx(n)
-        rhobeg = max(EPS, minval([rhobeg, x0(falseloc(lbx)) - xl(falseloc(lbx))]))
+        real, dimension(1) :: diff_result
+        diff_result = x0(falseloc(lbx)) - xl(falseloc(lbx))
+        rhobeg = max(EPS, minval([rhobeg, diff_result]))
     end subroutine preproc
 
 end module preproc_mod
```

**Comment by gxyd** [comment]
Closing this issue as it's fixed by https://github.com/lfortran/lfortran/pull/5809 and it added a similar test case as well.
