### ISSUE TITLE
bug : `pass_by_array` doesn't replace the name for the changed function with use of `class`

### ISSUE THREAD

**Issue by assem2002** [lfortran/lfortran#5844]
MRE
```fortran
module modd
    interface oo
    procedure :: ff
    end interface oo
    contains 
    function ff(rr) result(r)
        integer, allocatable :: r(:)
        integer :: rr(:)
    end function
end module modd

program test
    use modd
    
    type :: m
    end type m
    integer, allocatable :: ll(:)

    type(m) :: tt2
    contains
    subroutine ffo(dummy) 
        class(m):: dummy
        integer, allocatable :: r(:)
        integer, dimension(5) :: rr
        r = oo(rr)
    end subroutine ffo
end program test
```
```console
ASR verify pass error: ExternalSymbol::m_original_name ('ff') + scope_names not found in a module 'modd'
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/assem/lfortran_test/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/assem/lfortran_test/lfortran/src/bin/lfortran.cpp", line 2729, in main
    LCompilers::print_stack_on_segfault();
  File "/home/assem/lfortran_test/lfortran/src/bin/lfortran.cpp", line 2521, in main_app(int, char**)
    }
  File "/home/assem/lfortran_test/lfortran/src/bin/lfortran.cpp", line 822, in (anonymous namespace)::dump_all_passes(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::CompilerOptions&)
    pass_manager.dump_all_passes(al, asr.result, compiler_options.po, diagnostics, lm);
LCompilersException: Verify failed in the pass: pass_array_by_data

```

If we change `class` into --> `type`, it works. That's due to some externalSymbol that gets created when we use `class` instead of `type`. after `pass_by_array` run, it changes function `ff` name into another name which raises that error we have.

**Comment by assem2002** [comment]
working on it.
