### ISSUE TITLE
AssertionFailure on string concatenation of allocatable array

### ISSUE THREAD

**Issue by gxyd** [lfortran/lfortran#5845]
## Minimal Reproducible Example

For the below Fortran program extracted from *fman* repository:

```f90
function f() result(textblock)
    character(len=256), allocatable :: textblock(:)
    textblock=[character(len=len(textblock)+1) :: ' ',textblock]
    textblock=' '//textblock
end function

```

On it's execution with LFortran, I get an error:
```console
> lfortran --versionLFortran version: 0.42.0-785-ga97b0da4b-dirty
Platform: macOS ARM
LLVM: 11.1.0
Default target: arm64-apple-darwin23.6.0

> lfortran -c test.f90 --show-asr
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2729
    LCompilers::print_stack_on_segfault();
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2554
    return emit_asr(arg_file, lfortran_pass_manager,
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 655
    r = fe.get_asr2(input, lm, diagnostics);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 275
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics, lm);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 297
    compiler_options.symtab_only, compiler_options, lm);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 104
    if (res.ok) {
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 4648
    b.is_body_visitor = true;
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 156
    visit_ast(*x.m_items[i]);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4943
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4899
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4951
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4533
    case program_unitType::Procedure: { v.visit_Procedure((const Procedure_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2460
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 118
    this->visit_stmt(*m_body[i]);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4991
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4633
    case stmtType::Assign: { v.visit_Assign((const Assign_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2836
    ASR::expr_t *target = ASRUtils::EXPR(tmp);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 5043
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4692
    case exprType::DefBinOp: { v.visit_DefBinOp((const DefBinOp_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 8668
    LCOMPILERS_ASSERT(ASRUtils::extract_n_dims_from_ttype(right_type_) == 0);
AssertFailed: ASRUtils::extract_n_dims_from_ttype(right_type_) == 0
```

**Comment by HarshitaKalani** [comment]
Working on it.
