### ISSUE TITLE
--openmp fails

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#5871]
The example from https://gist.github.com/hakostra/ac5ed9279136fe1e7f6f217f2561f08e, modified to compile: https://gist.github.com/certik/924cf554b0144f00d15937970310fab7 works like this:
```console
$ lfortran --cpp -D_USE_DO_CONCURRENT_ a.f90 -o a.out
$ lfortran --cpp  a.f90 -o a.out 
```
But fails to compile when you add `--openmp` to either line above:
```console
$ lfortran --cpp -D_USE_DO_CONCURRENT_ --openmp a.f90 -o x.omp
zsh: segmentation fault  lfortran --cpp -D_USE_DO_CONCURRENT_ --openmp a.f90 -o x.omp
```
LFortran was compiled in Release mode using `./build_release.sh`. In Debug mode we get:
```
$ lfortran --cpp -D_USE_DO_CONCURRENT_ --openmp a.f90 -o x.omp
Undefined symbols for architecture arm64:
  "_GOMP_barrier", referenced from:
      _lcompilers_function in a.tmp.o
      _lcompilers_function1 in a.tmp.o
  "_GOMP_parallel", referenced from:
      _main in a.tmp.o
      _main in a.tmp.o
  "_omp_get_max_threads", referenced from:
      _lcompilers_function in a.tmp.o
      _lcompilers_function1 in a.tmp.o
  "_omp_get_thread_num", referenced from:
      _lcompilers_function in a.tmp.o
      _lcompilers_function1 in a.tmp.o
  "_zatan2", referenced from:
      _lcompilers_function in a.tmp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
The command 'clang -o x.omp a.tmp.o  -L"/Users/ondrej/repos/lfortran/src/bin/../runtime" -Wl,-rpath,"/Users/ondrej/repos/lfortran/src/bin/../runtime" -llfortran_runtime -lm' failed.
Tip: If there is a linker issue, switch the linker using --linker=<CC> option or create an environment variable `export LFORTRAN_LINKER=<CC>`, where CC is clang or gcc
Also, if required use --linker-path=<PATH>, where PATH has location to look for the linker execuatable
```

We should tell the user to use the following option:
```
$ lfortran --cpp -D_USE_DO_CONCURRENT_ --openmp a.f90 -o x.omp --openmp-lib-dir=$CONDA_PREFIX/lib
Undefined symbols for architecture arm64:
  "_zatan2", referenced from:
      _lcompilers_function in a.tmp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
The command 'clang -o x.omp a.tmp.o  -L"/Users/ondrej/repos/lfortran/src/bin/../runtime" -Wl,-rpath,"/Users/ondrej/repos/lfortran/src/bin/../runtime" -llfortran_runtime -lm -L/Users/ondrej/miniforge3/envs/lf/lib -Wl,-rpath,/Users/ondrej/miniforge3/envs/lf/lib -lomp' failed.
Tip: If there is a linker issue, switch the linker using --linker=<CC> option or create an environment variable `export LFORTRAN_LINKER=<CC>`, where CC is clang or gcc
Also, if required use --linker-path=<PATH>, where PATH has location to look for the linker execuatable
```

It still fails with a linker error, I have not figured out how to fix it yet.

**Comment by adit4443ya** [comment]
I Got the what's hindering in here for 
> Fix OpenMP input to run like `do concurrent`, something is wrong there

It is because there is change in ASR ,,, 
We have not tested Collapse feature when it's in do loop 
MRE for this is 
```fortran
program openmp_38
    use omp_lib
! declare variables as required
    integer :: ny, nx, nz  , i,j
    integer :: iy, ix, iz
    ny=3
    nx=4
    nz=5
do j=1,2
do i =1,3
#ifdef _USE_DO_CONCURRENT_
do concurrent( iy=1:ny, ix=1:nx , iz=1:nz)
#else
!$omp parallel do collapse(3) private(iy, ix, iz)
do iy = 1, ny
    do ix = 1, nx
        do iz = 1, nz
#endif
            print *,"iy->", iy,"ix->", ix,"iz->", iz
#ifdef _USE_DO_CONCURRENT_
end do 

#else 
        end do
    end do
end do
!$omp end parallel do
#endif
end do
end do
end program
```

Here the level till which this !$omp directive is nested is not handled 
And hence there is null body for doconcurrent which is formed at ASR level 

I will make a PR for it now quickly

**Comment by adit4443ya** [comment]
Here is it #5877

**Comment by adit4443ya** [comment]
For Function and Subroutine in DoConcurrent both fails .

MRE 

```fortran

program openmp_43
USE iso_fortran_env, ONLY: real64
integer :: i, j, res=0
do concurrent ( i =1:4)
    call SUB(i)
    print *, FUN(i)
end do 

CONTAINS

subroutine SUB(x)
    integer, intent(in) :: x
    print *,x*x
end subroutine SUB

REAL(real64) FUNCTION FUN(x)
    integer, intent(in) :: x
    integer, intent(out) :: y
    y=x*x
end function FUN
end program

```

Errors

For Function
```clojure

 Observer    \thats_me\main\lfortran  ➜ (   omp_bug  4)   226ms   5:32 PM   
 ⚡aditya-trivedi ❯❯ lfortran ./integration_tests/openmp_43.f90 --openmp  --linker=gcc  --openmp-lib-dir={$CONDA_PREFIX}/lib                           (base) 
/home/aditya-trivedi/conda_root/envs/lf/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/../../../../x86_64-conda-linux-gnu/bin/ld: ./integration_tests/openmp_43.tmp.o: in function `lcompilers_function':
LFortran:(.text+0x11d): undefined reference to `fun'
collect2: error: ld returned 1 exit status
The command 'gcc -o openmp_43.out ./integration_tests/openmp_43.tmp.o  -L"/home/aditya-trivedi/thats_me/main/lfortran/src/bin/../runtime" -Wl,-rpath,"/home/aditya-trivedi/thats_me/main/lfortran/src/bin/../runtime" -llfortran_runtime -lm -L/home/aditya-trivedi/conda_root/envs/lf/lib -Wl,-rpath,/home/aditya-trivedi/conda_root/envs/lf/lib -lomp' failed.
Tip: If there is a linker issue, switch the linker using --linker=<CC> option or create an environment variable `export LFORTRAN_LINKER=<CC>`, where CC is clang or gcc
Also, if required use --linker-path=<PATH>, where PATH has location to look for the linker execuatable

```

For Subroutine Call

```clojure
 Observer    \thats_me\main\lfortran  ➜ (   omp_bug  4)   109ms   5:29 PM   
 ⚡aditya-trivedi ❯❯ lfortran ./integration_tests/openmp_43.f90 --openmp  --linker=gcc  --openmp-lib-dir={$CONDA_PREFIX}/lib                           (base) 
ASR verify pass error: The symbol table was not found in the scope of `symtab`.

ASR verify pass error: SubroutineCall::m_name 'sub' cannot point outside of its symbol table
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/aditya-trivedi/thats_me/main/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/bin/lfortran.cpp", line 2733, in main
    return main_app(argc, argv);
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/bin/lfortran.cpp", line 2671, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/bin/lfortran.cpp", line 1051, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/lfortran/fortran_evaluator.cpp", line 382, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10459, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/aditya-trivedi/thats_me/main/lfortran/src/libasr/pass/pass_manager.h", line 403, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes_with_experimental_simplifier, pass_options, diagnostics);
LCompilersException: Verify failed in the pass: openmp
```

**Comment by kmr-srbh** [comment]
Using the MRE:

```fortran
program openmp_43
   implicit none

   integer :: i

   do concurrent (i = 1:4)
      print *,"Fun->", FUN(i)
   end do

contains

   PURE integer function FUN(x)
      integer, intent(in) :: x
      FUN = x * x
   end function FUN

end program openmp_43
```

For the issue with `Function`, if we do `objdump -t test.tmp.o`

```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ objdump -t test.tmp.o

test.tmp.o:     file format elf64-x86-64

SYMBOL TABLE:
0000000000000000 l    df *ABS*  0000000000000000 LFortran
0000000000000002 l     O .rodata.str1.1 0000000000000006 .L__unnamed_1
0000000000000008 l     O .rodata.str1.1 0000000000000005 .L__unnamed_2
0000000000000000 l     O .rodata.str1.1 0000000000000002 .L__unnamed_3
0000000000000000 l    d  .text  0000000000000000 .text
0000000000000000         *UND*  0000000000000000 GOMP_barrier
0000000000000000         *UND*  0000000000000000 GOMP_parallel
0000000000000000 g     F .text  0000000000000017 _lcompilers_optimization_mod_i32
0000000000000020 g     F .text  0000000000000017 _lcompilers_optimization_mod_i321
0000000000000000         *UND*  0000000000000000 _lcompilers_string_format_fortran
0000000000000000         *UND*  0000000000000000 _lfortran_printf
0000000000000000         *UND*  0000000000000000 _lpython_call_initial_functions
0000000000000000         *UND*  0000000000000000 _lpython_free_argv
0000000000000000         *UND*  0000000000000000 fun
0000000000000040 g     F .text  0000000000000136 lcompilers_function
0000000000000180 g     F .text  0000000000000034 main
0000000000000000         *UND*  0000000000000000 omp_get_max_threads
0000000000000000         *UND*  0000000000000000 omp_get_thread_num

```

we see that the symbol `fun` is know to the linker, but neither defined anywhere nor linked through an external library, hence the `*UND*`. If we look at the LLVM IR the code creates:

```llvm
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran test.f90 --linker=gcc --openmp-lib-dir=$CONDA_PREFIX/lib/ --openmp --show-llvm
; ModuleID = 'LFortran'
source_filename = "LFortran"

%thread_data = type { i32 }

@0 = private unnamed_addr constant [2 x i8] c"\0A\00", align 1
@1 = private unnamed_addr constant [6 x i8] c"Fun->\00", align 1
@2 = private unnamed_addr constant [5 x i8] c"%s%s\00", align 1

define i32 @_lcompilers_optimization_mod_i32(i32* %a, i32* %p) {
.entry:
  %_lcompilers_optimization_mod_i32 = alloca i32, align 4
  %0 = load i32, i32* %a, align 4
  %1 = load i32, i32* %p, align 4
  %2 = load i32, i32* %a, align 4
  %3 = load i32, i32* %p, align 4
  %4 = sdiv i32 %2, %3
  %5 = mul i32 %1, %4
  %6 = sub i32 %0, %5
  store i32 %6, i32* %_lcompilers_optimization_mod_i32, align 4
  br label %return

return:                                           ; preds = %.entry
  %7 = load i32, i32* %_lcompilers_optimization_mod_i32, align 4
  ret i32 %7
}

define i32 @_lcompilers_optimization_mod_i321(i32* %a, i32* %p) {
.entry:
  %_lcompilers_optimization_mod_i321 = alloca i32, align 4
  %0 = load i32, i32* %a, align 4
  %1 = load i32, i32* %p, align 4
  %2 = load i32, i32* %a, align 4
  %3 = load i32, i32* %p, align 4
  %4 = sdiv i32 %2, %3
  %5 = mul i32 %1, %4
  %6 = sub i32 %0, %5
  store i32 %6, i32* %_lcompilers_optimization_mod_i321, align 4
  br label %return

return:                                           ; preds = %.entry
  %7 = load i32, i32* %_lcompilers_optimization_mod_i321, align 4
  ret i32 %7
}

define void @lcompilers_function(void* %data) {
.entry:
  %call_arg_value4 = alloca i32, align 4
  %call_arg_value = alloca i32, align 4
  %I = alloca i32, align 4
  %chunk = alloca i32, align 4
  %end = alloca i32, align 4
  %i = alloca i32, align 4
  %leftovers = alloca i32, align 4
  %num_threads = alloca i32, align 4
  %start = alloca i32, align 4
  %tdata = alloca %thread_data*, align 8
  store %thread_data* null, %thread_data** %tdata, align 8
  %thread_num = alloca i32, align 4
  %0 = bitcast void* %data to %thread_data*
  store %thread_data* %0, %thread_data** %tdata, align 8
  %1 = load %thread_data*, %thread_data** %tdata, align 8
  %2 = getelementptr %thread_data, %thread_data* %1, i32 0, i32 0
  %3 = load i32, i32* %2, align 4
  store i32 %3, i32* %i, align 4
  %4 = call i32 @omp_get_max_threads()
  store i32 %4, i32* %num_threads, align 4
  %5 = load i32, i32* %num_threads, align 4
  %6 = sdiv i32 4, %5
  store i32 %6, i32* %chunk, align 4
  store i32 4, i32* %call_arg_value, align 4
  %7 = call i32 @_lcompilers_optimization_mod_i32(i32* %call_arg_value, i32* %num_threads)
  store i32 %7, i32* %leftovers, align 4
  %8 = call i32 @omp_get_thread_num()
  store i32 %8, i32* %thread_num, align 4
  %9 = load i32, i32* %chunk, align 4
  %10 = load i32, i32* %thread_num, align 4
  %11 = mul i32 %9, %10
  store i32 %11, i32* %start, align 4
  %12 = load i32, i32* %thread_num, align 4
  %13 = load i32, i32* %leftovers, align 4
  %14 = icmp slt i32 %12, %13
  br i1 %14, label %then, label %else

then:                                             ; preds = %.entry
  %15 = load i32, i32* %start, align 4
  %16 = load i32, i32* %thread_num, align 4
  %17 = add i32 %15, %16
  store i32 %17, i32* %start, align 4
  br label %ifcont

else:                                             ; preds = %.entry
  %18 = load i32, i32* %start, align 4
  %19 = load i32, i32* %leftovers, align 4
  %20 = add i32 %18, %19
  store i32 %20, i32* %start, align 4
  br label %ifcont

ifcont:                                           ; preds = %else, %then
  %21 = load i32, i32* %start, align 4
  %22 = load i32, i32* %chunk, align 4
  %23 = add i32 %21, %22
  store i32 %23, i32* %end, align 4
  %24 = load i32, i32* %thread_num, align 4
  %25 = load i32, i32* %leftovers, align 4
  %26 = icmp slt i32 %24, %25
  br i1 %26, label %then1, label %else2

then1:                                            ; preds = %ifcont
  %27 = load i32, i32* %end, align 4
  %28 = add i32 %27, 1
  store i32 %28, i32* %end, align 4
  br label %ifcont3

else2:                                            ; preds = %ifcont
  br label %ifcont3

ifcont3:                                          ; preds = %else2, %then1
  %29 = load i32, i32* %start, align 4
  %30 = add i32 %29, 1
  %31 = sub i32 %30, 1
  store i32 %31, i32* %I, align 4
  br label %loop.head

loop.head:                                        ; preds = %loop.body, %ifcont3
  %32 = load i32, i32* %I, align 4
  %33 = add i32 %32, 1
  %34 = load i32, i32* %end, align 4
  %35 = icmp sle i32 %33, %34
  br i1 %35, label %loop.body, label %loop.end

loop.body:                                        ; preds = %loop.head
  %36 = load i32, i32* %I, align 4
  %37 = add i32 %36, 1
  store i32 %37, i32* %I, align 4
  store i32 4, i32* %call_arg_value4, align 4
  %38 = call i32 @_lcompilers_optimization_mod_i321(i32* %I, i32* %call_arg_value4)
  %39 = add i32 %38, 1
  store i32 %39, i32* %i, align 4
  %40 = call i32 @fun(i32* %i)
  %41 = sext i32 %40 to i64
  %42 = call i8* (i32, i8*, ...) @_lcompilers_string_format_fortran(i32 4, i8* null, i32 7, i8* getelementptr inbounds ([6 x i8], [6 x i8]* @1, i32 0, i32 0), i32 2, i64 %41)
  call void (i8*, ...) @_lfortran_printf(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @2, i32 0, i32 0), i8* %42, i8* getelementptr inbounds ([2 x i8], [2 x i8]* @0, i32 0, i32 0))
  br label %loop.head

loop.end:                                         ; preds = %loop.head
  call void @GOMP_barrier()
  br label %return

return:                                           ; preds = %loop.end
  ret void
}

declare i32 @fun(i32*)

declare void @GOMP_atomic_end()

declare void @GOMP_atomic_start()

declare void @GOMP_barrier()

declare void @GOMP_critical_end()

declare void @GOMP_critical_start()

declare void @GOMP_parallel(void*, void*, i32, i32)

declare i32 @omp_get_max_threads()

declare i32 @omp_get_num_procs()

declare i32 @omp_get_thread_num()

declare double @omp_get_wtime()

declare void @omp_set_num_threads(i32)

declare i8* @_lcompilers_string_format_fortran(i32, i8*, ...)

declare void @_lfortran_printf(i8*, ...)

define i32 @main(i32 %0, i8** %1) {
.entry:
  %i = alloca i32, align 4
  call void @_lpython_call_initial_functions(i32 %0, i8** %1)
  %data = alloca %thread_data, align 8
  %2 = getelementptr %thread_data, %thread_data* %data, i32 0, i32 0
  %i1 = alloca i32, align 4
  %tdata = alloca void*, align 8
  %3 = getelementptr %thread_data, %thread_data* %data, i32 0, i32 0
  %4 = load i32, i32* %i1, align 4
  store i32 %4, i32* %3, align 4
  %5 = bitcast %thread_data* %data to void*
  store void* %5, void** %tdata, align 8
  %6 = load void*, void** %tdata, align 8
  call void @GOMP_parallel(void* bitcast (void (void*)* @lcompilers_function to void*), void* %6, i32 0, i32 0)
  call void @_lpython_free_argv()
  br label %return

return:                                           ; preds = %.entry
  ret i32 0
}

declare void @_lpython_call_initial_functions(i32, i8**)

declare void @_lpython_free_argv()
```

we see that function `fun` is declared, but not defined. This can be attributed to how `openmp` pass transforms the code - moving user-defined function definitions inside a function `lcompilers_function` and setting the `deftType` to `Interface`. So the LLVM code is not generated for this function and the linker expects it from an external library. The comment in the pass says we need to create an interface for user-defined functions. @Pranavchiku should know more about this.

**Comment by certik** [comment]
We need to fully resolve in ASR which function gets called. For each interface, we have to have a link to the actual function that it links to in ASR itself, before LLVM gets called (the only exception is `bind(c)` interface, which means some C function that will be linked at link time).

We have thus several options how to fix this:

* Allow interfaces to link to internal functions (`FUN`) via ExternalSymbol
* Move the internal `FUN` function into some module and call it from both the main program and the `do concurrent` module
* Duplicate the `FUN` function into the `do concurrent` module.

Any of these options should work, the unused function pass will not remove `FUN` anymore, since it will be used, and everything should work.

Note: the function `FUN` actually has to be both side-effects-free (`pure` keyword) *and* deterministic (required by the `simple` keyword) in order to be allowed inside `do concurrent`.
