### ISSUE TITLE
iso_fortran_env is missing `real_kinds`

### ISSUE THREAD

**Issue by kargl** [lfortran/lfortran#606]
See Fortran 2018, 16.10.2.24 REAL_KINDS
````
program a
   use iso_fortran_env
   print *, real_kinds
end program a

% lfortran a.f90
semantic error: Variable 'real_kinds' is not declared
 --> a.f90:3:13
  |
3 |    print *, real_kinds
  |             ^^^^^^^^^^ 'real_kinds' is undeclared
```

I suspect that `integer_kinds` and other are also missing.

**Comment by certik** [comment]
Awesome, thanks @kargl for reporting it. I have a fix in #611, but it uncovered some bug that we will fix first, then it will work.

**Comment by kargl** [comment]
Do you want to close this issue?  I thought I search for `real_kinds` before submitting the PR.

**Comment by certik** [comment]
We implemented `real_kinds` and the other kinds too in #611, but the above code still does not work due to another bug (#616) so I'll keep this issue open until we fix it:
```console
$ cat a.f90 
program a
   use iso_fortran_env
   print *, real_kinds
end program a
$ lfortran a.f90 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1724
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 743
    res = fe.get_llvm3(*asr, lpm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 318
    compiler_options.platform, run_fn);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5352
    v.nested_func_types = pass_find_nested_vars(asr, context,
  File "../libasr/asr.h", line 3728
  File "../libasr/asr.h", line 3706
  File "../libasr/asr.h", line 3729
  File "../libasr/asr.h", line 3505
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1065
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 3731
  File "../libasr/asr.h", line 3514
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1673
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 3744
  File "../libasr/asr.h", line 3561
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3345
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 3744
  File "../libasr/asr.h", line 3548
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4486
    handle_print(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4536
    this->visit_expr_wrapper(x.m_values[i], true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3070
    this->visit_expr(*x);
  File "../libasr/asr.h", line 3786
  File "../libasr/asr.h", line 3625
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1302
    LFORTRAN_ASSERT(llvm_symtab.find(v_h) != llvm_symtab.end());
AssertFailed: llvm_symtab.find(v_h) != llvm_symtab.end()
```

**Comment by kargl** [comment]
Any progress?

**Comment by certik** [comment]
This bug is still there with the latest master:
```fortran
program a
   use iso_fortran_env
   print *, real_kinds
end program a
```
This gives:
```console
$ lfortran b.f90
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2332
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 959
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9320
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "../libasr/asr.h", line 5059
  File "../libasr/asr.h", line 5035
  File "../libasr/asr.h", line 5060
  File "../libasr/asr.h", line 4767
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 945
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5062
  File "../libasr/asr.h", line 4776
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3062
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5079
  File "../libasr/asr.h", line 4829
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5629
    create_loop(x.m_name, [=]() {
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 320
    start_new_block(loopbody); {
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5635
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5079
  File "../libasr/asr.h", line 4815
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7418
    handle_print(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7695
    compute_fmt_specifier_and_arg(fmt, args, x.m_values[i], x.base.base.loc);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7522
    this->visit_expr_wrapper(v, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5109
    this->visit_expr(*x);
  File "../libasr/asr.h", line 5126
  File "../libasr/asr.h", line 4914
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2356
    tmp = arr_descr->get_single_element(array, indices, x.n_args,
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 630
    tmp = llvm_utils->create_gep(array, idx);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1324
    return LLVM::CreateGEP(*builder, ds, idx_vec);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 24
    llvm::Type *t = x->getType();
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by certik** [comment]
I think this bug has something to do with indexing of module arrays. This fails:
```fortran
program a
use iso_fortran_env
integer :: i
do i = 1, size(real_kinds)
    print *, real_kinds(i)
end do
end program a
```
But this works:
```fortran
program a
use iso_fortran_env
print *, size(real_kinds)
print *, real_kinds(1)
print *, real_kinds(2)
end program a
```
Which gives:
```console
$ lfortran b.f90 
2
4
8
$ gfortran b.f90 && ./a.out 
           3
           4
           8
```

**Comment by certik** [comment]
I opened up a dedicated issue for the indexing bug: https://github.com/lfortran/lfortran/issues/2969, and I am closing this issue as fixed, since `real_kinds` is now implemented.
