### ISSUE TITLE
LLVM backend: Bug in visit_ArraySize

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#610]
There is some bug in ArraySize handling for this simple example:
```fortran
program arrays_17
    integer, parameter :: real_kinds(2) = [4, 8]
    print *, size(real_kinds)
end program
```

It fails with:

```console
$ lfortran arrays_17.f90 --show-llvm
Assertion failed: (Ty && "Invalid GetElementPtrInst indices for type!"), function checkGEPType, file Instructions.h, line 897.
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1651
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 663
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 264
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 285
    Result<std::unique_ptr<LLVMModule>> res = get_llvm3(*asr.result, pass_manager, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 318
    compiler_options.platform, run_fn);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5352
    v.nested_func_types = pass_find_nested_vars(asr, context,
  File "../libasr/asr.h", line 3728
  File "../libasr/asr.h", line 3706
  File "../libasr/asr.h", line 3729
  File "../libasr/asr.h", line 3505
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1065
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 3731
  File "../libasr/asr.h", line 3514
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1673
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 3744
  File "../libasr/asr.h", line 3548
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4486
    handle_print(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4536
    this->visit_expr_wrapper(x.m_values[i], true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3070
    this->visit_expr(*x);
  File "../libasr/asr.h", line 3786
  File "../libasr/asr.h", line 3627
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5292
    tmp = arr_descr->get_array_size(llvm_arg, llvm_dim, output_kind, dim_kind);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 492
    llvm::Value* dim_des_val = this->get_pointer_to_dimension_descriptor_array(array);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 265
    llvm::Value* dim_des_arr_ptr = llvm_utils->create_gep(arr, 2);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 82
    return LLVM::CreateGEP(*builder, ds, idx_vec);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 25
    return builder.CreateGEP(t2, x, idx);
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/IRBuilder.h", line 1773
    return Insert(GetElementPtrInst::Create(Ty, Ptr, IdxList), Name);
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 943
    NameStr, InsertBefore);
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1151
    }
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1143
    : Instruction(getGEPReturnType(PointeeType, Ptr, IdxList), GetElementPtr,
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1074
    Type *PtrTy = PointerType::get(checkGEPType(getIndexedType(ElTy, IdxList)),
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 897
    assert(Ty && "Invalid GetElementPtrInst indices for type!");
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18024972b
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18024a313
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x18030ceaf
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Abort: Signal SIGABRT (abort) received

zsh: abort      lfortran arrays_17.f90 --show-llvm
```

But both of these work:
```fortran
program arrays_17
    integer :: real_kinds(2)
    print *, size(real_kinds)
end program
```
and:
```fortran
program arrays_17
    integer, parameter :: real_kinds(2) = [4, 8]
    print *, real_kinds(1), real_kinds(2)
end program
```

I tried debugging it, but can't figure it out. The LLVM code (if I can print it) seems correct, but it seems `GetElementPtrInst` has invalid indices somehow. @czgdp1807 by any chance do you know what could be causing this?

**Comment by czgdp1807** [comment]
Sure. I will look into it. Can you tell how urgent the issue is?
