### ISSUE TITLE
dev.lfortran.org: the example program throws a runtime error on the cpp tab

### ISSUE THREAD

**Issue by sloorush** [lfortran/lfortran#821]
I was checking out the online playground at https://dev.lfortran.org/ and when I run the default program on the website the code executes successfully but in the cpp tab it shows an error saying:

```
RuntimeError: Aborted(native code called abort())
ERROR: CPP could not be generated from the code
```

<details>
  <summary>Relevant screenshots</summary>

## stdout tab

![image](https://user-images.githubusercontent.com/54478821/193378376-17863ada-06a4-4350-b197-dde4f7f61451.png)

## cpp tab

![image](https://user-images.githubusercontent.com/54478821/193378410-29b702e7-2f7f-44f8-8cd8-9367ac1151a1.png)
</details>

I also checked with a simple hello world program and the cpp tab works and generates code.

**Comment by certik** [comment]
Thanks! Yes, I noticed that too. I think our C++ backend cannot compile the code yet.

**Comment by sloorush** [comment]
> I think our C++ backend cannot compile the code yet.

I am curious, Is there any particular reason it can compile a hello world program but not this?

**Comment by certik** [comment]
I think it's just a bug, you can test it like this:
```console
$ lfortran --show-cpp a.f90 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1699
    return emit_cpp(arg_file, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 578
    LFortran::Result<std::string> cpp = fe.get_cpp(input, lm, diagnostics, 1);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 404
    return get_cpp2(*asr.result, diagnostics, default_lower_bound);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 415
    return asr_to_cpp(al, asr, diagnostics, compiler_options.platform,
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_cpp.cpp", line 718
    v.visit_asr((ASR::asr_t &)asr);
  File "../libasr/asr.h", line 3818
  File "../libasr/asr.h", line 3795
  File "../libasr/asr.h", line 3819
  File "../libasr/asr.h", line 3584
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_cpp.cpp", line 452
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 3821
  File "../libasr/asr.h", line 3593
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_cpp.cpp", line 485
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 3834
  File "../libasr/asr.h", line 3619
  File "../libasr/codegen/asr_to_c_cpp.h", line 1152
  File "../libasr/asr.h", line 3834
  File "../libasr/asr.h", line 3619
  File "../libasr/codegen/asr_to_c_cpp.h", line 1152
  File "../libasr/asr.h", line 3834
  File "../libasr/asr.h", line 3619
  File "../libasr/codegen/asr_to_c_cpp.h", line 1109
  File "../libasr/asr_utils.h", line 77
  File "../libasr/asr.h", line 39
AssertFailed: f != nullptr
```

**Comment by lucifer1004** [comment]
The problem is here:

```fortran
do
                x_sqr = x ** 2; y_sqr = y ** 2
...
end do
```

**Comment by lucifer1004** [comment]
The C/C++ (as well as Julia) backend does not handle such `do`s properly.

**Comment by certik** [comment]
That's easy to fix (https://github.com/lfortran/lfortran/pull/822). Now it works for me locally:
```console
$ lfortran --show-cpp a.f90 
#include <iostream>
#include <string>
#include <vector>
#include <cassert>
#include <cmath>
#include <complex>
#include <Kokkos_Core.hpp>
#include <lfortran_intrinsics.h>

template <typename T>
Kokkos::View<T*> from_std_vector(const std::vector<T> &v)
{
    Kokkos::View<T*> r("r", v.size());
    for (size_t i=0; i < v.size(); i++) {
        r(i) = v[i];
    }
    return r;
}


struct dimension_descriptor
{
    int32_t lower_bound, length;
};

struct i32_600_450_2
{
    Kokkos::View<int32_t*>* data;
    dimension_descriptor dims[2];
    bool is_allocated;

    i32_600_450_2(Kokkos::View<int32_t*>* data_): data{data_} {};
};


struct i32_4_600_450_3
{
    Kokkos::View<int32_t*>* data;
    dimension_descriptor dims[3];
    bool is_allocated;

    i32_4_600_450_3(Kokkos::View<int32_t*>* data_): data{data_} {};
};


struct i32_3_4_2
{
    Kokkos::View<int32_t*>* data;
    dimension_descriptor dims[2];
    bool is_allocated;

    i32_3_4_2(Kokkos::View<int32_t*>* data_): data{data_} {};
};

// Forward declarations
int32_t kind(bool x);
namespace {

template <typename T0>
void show_img(int32_t w, int32_t h, T0* a);

template <typename T0>
void show_img_color(int32_t w, int32_t h, T0* a);
}

// Implementations
int32_t kind(bool x)
{
    int32_t r;
    r = 4;
    return r;
}

namespace {

template <typename T0>
void show_img(int32_t w, int32_t h, T0* a);


template <typename T0>
void show_img_color(int32_t w, int32_t h, T0* a);


void main2() {
    int32_t dp=kind(  0.00000000000000000e+00);
    double dx_di=width/(double)(nx);
    double dy_dj=(-height)/(double)(ny);
    double height=(double)(3);
    int32_t i;
    int32_t idx;
    Kokkos::View<int32_t*> image_data("image_data", 270000);
    i32_600_450_2 image_value(&image_data);
    i32_600_450_2* image = &image_value;
    image->dims[0].lower_bound = 1;
    image->dims[0].length = 600;
    image->dims[1].lower_bound = 1;
    image->dims[1].length = 450;
    Kokkos::View<int32_t*> image_color_data("image_color_data", 1080000);
    i32_4_600_450_3 image_color_value(&image_color_data);
    i32_4_600_450_3* image_color = &image_color_value;
    image_color->dims[0].lower_bound = 1;
    image_color->dims[0].length = 4;
    image_color->dims[1].lower_bound = 1;
    image_color->dims[1].length = 600;
    image_color->dims[2].lower_bound = 1;
    image_color->dims[2].length = 450;
    int32_t j;
    int32_t n;
    int32_t n_max=255;
    int32_t nx=600;
    int32_t ny=450;
    Kokkos::View<int32_t*> palette_data("palette_data", 12);
    i32_3_4_2 palette_value(&palette_data);
    i32_3_4_2* palette = &palette_value;
    palette->dims[0].lower_bound = 1;
    palette->dims[0].length = 3;
    palette->dims[1].lower_bound = 1;
    palette->dims[1].length = 4;
    double width=(double)(4);
    double x;
    double x_0;
    double x_offset=xcenter - (double)(nx + 1)*dx_di/(double)(2);
    double x_sqr;
    double xcenter=-  5.00000000000000000e-01;
    double y;
    double y_0;
    double y_offset=ycenter - (double)(ny + 1)*dy_dj/(double)(2);
    double y_sqr;
    double ycenter=  0.00000000000000000e+00;
    for (j=1; j<=ny; j++) {
        y_0 = y_offset + dy_dj*(double)(j);
        for (i=1; i<=nx; i++) {
            x_0 = x_offset + dx_di*(double)(i);
            x = (double)(0);
            y = (double)(0);
            n = 0;
            while (true) {
                x_sqr = std::pow(x, (double)(2));
                y_sqr = std::pow(y, (double)(2));
                if (x_sqr + y_sqr > (double)(4) || n == n_max) {
                    image->data->operator[](i - image->dims[0].lower_bound, j - image->dims[1].lower_bound) = 255 - n;
                    break;
                }
                y = y_0 + (double)(2)*x*y;
                x = x_0 + x_sqr - y_sqr;
                n = n + 1;
            }
        }
    }
    palette->data->operator[](1 - palette->dims[0].lower_bound, 1 - palette->dims[1].lower_bound) = 0;
    palette->data->operator[](2 - palette->dims[0].lower_bound, 1 - palette->dims[1].lower_bound) = 135;
    palette->data->operator[](3 - palette->dims[0].lower_bound, 1 - palette->dims[1].lower_bound) = 68;
    palette->data->operator[](1 - palette->dims[0].lower_bound, 2 - palette->dims[1].lower_bound) = 0;
    palette->data->operator[](2 - palette->dims[0].lower_bound, 2 - palette->dims[1].lower_bound) = 87;
    palette->data->operator[](3 - palette->dims[0].lower_bound, 2 - palette->dims[1].lower_bound) = 231;
    palette->data->operator[](1 - palette->dims[0].lower_bound, 3 - palette->dims[1].lower_bound) = 214;
    palette->data->operator[](2 - palette->dims[0].lower_bound, 3 - palette->dims[1].lower_bound) = 45;
    palette->data->operator[](3 - palette->dims[0].lower_bound, 3 - palette->dims[1].lower_bound) = 32;
    palette->data->operator[](1 - palette->dims[0].lower_bound, 4 - palette->dims[1].lower_bound) = 255;
    palette->data->operator[](2 - palette->dims[0].lower_bound, 4 - palette->dims[1].lower_bound) = 167;
    palette->data->operator[](3 - palette->dims[0].lower_bound, 4 - palette->dims[1].lower_bound) = 0;
    for (j=1; j<=ny; j++) {
        for (i=1; i<=nx; i++) {
            idx = image->data->operator[](i - image->dims[0].lower_bound, j - image->dims[1].lower_bound) - image->data->operator[](i - image->dims[0].lower_bound, j - image->dims[1].lower_bound)/4*4 + 1;
            image_color->data->operator[](1 - image_color->dims[0].lower_bound, i - image_color->dims[1].lower_bound, j - image_color->dims[2].lower_bound) = palette->data->operator[](1 - palette->dims[0].lower_bound, idx - palette->dims[1].lower_bound);
            image_color->data->operator[](2 - image_color->dims[0].lower_bound, i - image_color->dims[1].lower_bound, j - image_color->dims[2].lower_bound) = palette->data->operator[](2 - palette->dims[0].lower_bound, idx - palette->dims[1].lower_bound);
            image_color->data->operator[](3 - image_color->dims[0].lower_bound, i - image_color->dims[1].lower_bound, j - image_color->dims[2].lower_bound) = palette->data->operator[](3 - palette->dims[0].lower_bound, idx - palette->dims[1].lower_bound);
            image_color->data->operator[](4 - image_color->dims[0].lower_bound, i - image_color->dims[1].lower_bound, j - image_color->dims[2].lower_bound) = 255;
        }
    }
    std::cout << "The Mandelbrot image in color:" << std::endl;
    show_img_color(nx, ny, image_color);
    std::cout << "The Mandelbrot image in grayscale:" << std::endl;
    show_img(nx, ny, image);
    std::cout << "Done." << std::endl;
}

}
int main(int argc, char* argv[])
{
    Kokkos::initialize(argc, argv);
    main2();
    Kokkos::finalize();
    return 0;
}
```
