### ISSUE TITLE
Array with expression type

### ISSUE THREAD

**Issue by ansharlubis** [lfortran/lfortran#840]
The following program where the array is typed with a `size` expression does not work yet.
````
program test

real :: x(1), y(1), z(1)

z = f(x, y)

contains

function f(a, b) result(r)
real, intent(in) :: a(:), b(:)
real :: r(size(a))
integer :: i
do i = 1, size(a)
    r(i) = a(i) + b(i)
end do
end function

end program
````
The resulting error is:
````
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1726
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 743
    res = fe.get_llvm3(*asr, lpm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 318
    compiler_options.platform, run_fn);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5699
    pass_manager.apply_passes(al, &asr, pass_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 172
    _apply_passes(al, asr, _passes, pass_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 85
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 423
    LFORTRAN_ASSERT(asr_verify(unit));
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_verify.cpp", line 521
    v.visit_TranslationUnit(unit);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_verify.cpp", line 110
    for (auto &a : x.m_global_scope->get_scope()) {
  File "../libasr/asr.h", line 3799
  File "../libasr/asr.h", line 3572
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_verify.cpp", line 145
    for (auto &a : x.m_symtab->get_scope()) {
  File "../libasr/asr.h", line 3799
  File "../libasr/asr.h", line 3573
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_verify.cpp", line 247
    for (auto &a : x.m_symtab->get_scope()) {
  File "../libasr/asr.h", line 3799
  File "../libasr/asr.h", line 3578
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_verify.cpp", line 298
    visit_ttype(*x.m_type);
  File "../libasr/asr.h", line 3927
  File "../libasr/asr.h", line 3718
  File "../libasr/asr.h", line 4833
  File "../libasr/asr.h", line 4899
  File "../libasr/asr.h", line 3855
  File "../libasr/asr.h", line 3686
  File "../libasr/asr.h", line 4658
  File "../libasr/asr.h", line 3855
  File "../libasr/asr.h", line 3682
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_verify.cpp", line 337
    require(symtab_in_scope(current_symtab, x.m_v),
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_verify.cpp", line 49
    throw LCompilersException("ASR verify failed: " + error_msg);
LCompilersException: ASR verify failed: Var::m_v `a` cannot point outside of its symbol table
````

**Comment by certik** [comment]
Thanks! This is a good one to get fixed. From the stacktrace this looks like a bug in `pass_array_by_data`, I think if you disable this pass it might even work (I think we got it working before).

CC @czgdp1807.

**Comment by certik** [comment]
This works now in master, but let's still add a test for this before closing this issue.
