### ISSUE TITLE
CreateGEP fails

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#955]
The following code is a minimal reproducible example:
```fortran
program print_array

contains

subroutine f(n, x)
integer :: n, x(n)
print *, x
end subroutine

end program
```
And it gives the following error:
```console
$ lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1793
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 773
    res = fe.get_llvm3(*asr, lpm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 321
    compiler_options, run_fn);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6195
    v.nested_func_types = pass_find_nested_vars(asr, context,
  File "../libasr/asr.h", line 4080
  File "../libasr/asr.h", line 4057
  File "../libasr/asr.h", line 4081
  File "../libasr/asr.h", line 3836
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1157
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 4083
  File "../libasr/asr.h", line 3845
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2150
    visit_procedures(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3398
    ASR::Function_t *s = ASR::down_cast<ASR::Function_t>(item.second);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3037
    visit_procedures(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3351
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4098
  File "../libasr/asr.h", line 3867
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3767
    this->visit_expr_wrapper(x.m_value, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3825
    this->visit_expr(*x);
  File "../libasr/asr.h", line 4141
  File "../libasr/asr.h", line 3927
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4266
    this->visit_expr_wrapper(x.m_left, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3825
    this->visit_expr(*x);
  File "../libasr/asr.h", line 4141
  File "../libasr/asr.h", line 3964
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6152
    llvm::Value* dim_des_val = arr_descr->get_pointer_to_dimension_descriptor_array(llvm_arg1);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 249
    llvm::Value* dim_des_arr_ptr = llvm_utils->create_gep(arr, 2);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 120
    return LLVM::CreateGEP(*builder, ds, idx_vec);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 24
    LFORTRAN_ASSERT(t->isPointerTy());
AssertFailed: t->isPointerTy()
```

The actual error was discovered by:
```console
$ lfortran -Isrc --rtlib -c ../examples/example_hybrd.f90 -o a.o
Assertion failed: (Ty && "Invalid GetElementPtrInst indices for type!"), function checkGEPType, file Instructions.h, line 897.
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1762
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 773
    res = fe.get_llvm3(*asr, lpm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 321
    compiler_options, run_fn);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6195
    v.nested_func_types = pass_find_nested_vars(asr, context,
  File "../libasr/asr.h", line 4080
  File "../libasr/asr.h", line 4057
  File "../libasr/asr.h", line 4081
  File "../libasr/asr.h", line 3836
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1157
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 4083
  File "../libasr/asr.h", line 3845
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2150
    visit_procedures(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3398
    ASR::Function_t *s = ASR::down_cast<ASR::Function_t>(item.second);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3037
    visit_procedures(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3351
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4098
  File "../libasr/asr.h", line 3867
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3767
    this->visit_expr_wrapper(x.m_value, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3825
    this->visit_expr(*x);
  File "../libasr/asr.h", line 4141
  File "../libasr/asr.h", line 3927
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4266
    this->visit_expr_wrapper(x.m_left, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3825
    this->visit_expr(*x);
  File "../libasr/asr.h", line 4141
  File "../libasr/asr.h", line 3964
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6152
    llvm::Value* dim_des_val = arr_descr->get_pointer_to_dimension_descriptor_array(llvm_arg1);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 249
    llvm::Value* dim_des_arr_ptr = llvm_utils->create_gep(arr, 2);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 120
    return LLVM::CreateGEP(*builder, ds, idx_vec);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/llvm_utils.cpp", line 26
    return builder.CreateGEP(t2, x, idx);
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/IRBuilder.h", line 1773
    return Insert(GetElementPtrInst::Create(Ty, Ptr, IdxList), Name);
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 943
    NameStr, InsertBefore);
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1151
    }
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1143
    : Instruction(getGEPReturnType(PointeeType, Ptr, IdxList), GetElementPtr,
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1074
    Type *PtrTy = PointerType::get(checkGEPType(getIndexedType(ElTy, IdxList)),
  File "/Users/ondrej/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 897
    assert(Ty && "Invalid GetElementPtrInst indices for type!");
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18024972b
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18024a313
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x18030ceaf
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Abort: Signal SIGABRT (abort) received

zsh: abort      lfortran -Isrc --rtlib -c ../examples/example_hybrd.f90 -o a.o
```
Which is a slightly different error stacktrace, but it is most likely the same
issue.

Once we fix the minimum example above, we have to test for the actual error to
see if there is more than one issue.

**Comment by certik** [comment]
@czgdp1807 You might now what the issue is, since you fixed several of these already.

**Comment by certik** [comment]
I took the scipy label off, since it is not needed for SciPy, I discovered this while debugging for SciPy using print statements. The workaround is to simply print as `print *, x(1), x(2), x(3)`.

**Comment by czgdp1807** [comment]
Well its an issue with array bounds not being processed correctly in pass array by data pass. Probably it got left out and then LLVM backend (will and should) assumed that the array argument provided to `lbound` or `ubound` is an array descriptor. But that's not the case here since `x` has non-empty dimensions so it will be passed as a data pointer and not an array descriptor. Should be fixable by correcting the passes. Self assigning.
