### ISSUE TITLE
Implement `integer, parameter :: x(*) = [1, 2, 3]`

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#967]
Example:
```fortran
program const_arrays
integer, parameter :: x(*) = [1, 2, 3]
print *, x
end
```
Currently one gets:
```console
$ lfortran arrays_01.f90 
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1794
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 774
    res = fe.get_llvm3(*asr, lpm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 321
    compiler_options, run_fn);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6195
    v.nested_func_types = pass_find_nested_vars(asr, context,
  File "../libasr/asr.h", line 4080
  File "../libasr/asr.h", line 4057
  File "../libasr/asr.h", line 4081
  File "../libasr/asr.h", line 3836
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1157
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 4083
  File "../libasr/asr.h", line 3845
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2160
    declare_vars(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2505
    fill_array_details(ptr, llvm_data_type, m_dims, n_dims);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 426
    visit_expr(*(m_dim.m_start));
  File "../libasr/asr.h", line 4141
  File "../libasr/asr.h", line 4141
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Segfault: Signal SIGSEGV (segmentation fault) received
```

I don't think it's difficult to fix, we just need to get the compile time length of the RHS, and use that as the length of the LHS.

**Comment by Smit-create** [comment]
This still doesn't work:
```fortran
program const_array_01
use iso_fortran_env, only: dp=>real64
implicit none
real(dp), parameter :: y(*) = [1, 3]
print *, y
end
```
Error:
```
semantic error: Value of a parameter variable must evaluate to a compile-time constant
 --> a.f90:4:1
  |
4 | real(dp), parameter :: y(*) = [1, 3]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
```

**Comment by Smit-create** [comment]
This produces a different error in casting:
```fortran
program const_array_01
use iso_fortran_env, only: dp=>real64
implicit none
real(dp), parameter :: y(*) = [1.0, 3.2]
print *, y
end
```

Output:
```
  File "/Users/thebigbool/repos2/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 1343
    ImplicitCastRules::set_converted_value(al, x.base.base.loc, &init_expr, init_type, type);
  File "/Users/thebigbool/repos2/lfortran/src/lfortran/semantics/asr_implicit_cast_rules.h", line 162
    LFORTRAN_ASSERT(ASR::is_a<ASR::RealConstant_t>(*value))
AssertFailed: ASR::is_a<ASR::RealConstant_t>(*value)
```

**Comment by certik** [comment]
I just checked and the last two files still fail as indicated. @Pranavchiku go ahead and work on it if you want.
