### ISSUE TITLE
Implied do loops

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#981]
The implied do loop in Fortran is kind of like a generator expression in Python. It is a loop that is an expression, so it returns an expression, typically an array (or a list in Python).

Just like we have `If` (statement) and `IfExp` which is an expression, and we have `DoLoop` (statement), we could have `DoLoopExpr` (which would be an expression). 

Note: It seems `IfExp` should be renamed to `IfExpr`, just like `NamedExpr`.

**Comment by Pranavchiku** [comment]
>AST->ASR, add the `DoLoopExpr` node

@certik if you could brief what exactly needs to be done here?

I added a new node for `DoLoopExpr_t` in `asr.h`. Thereafter referring to `NamedExpr_t` added `void visit_DoLoopExpr(const DoLoopExpr_t &x)` functions.

```
    struct DoLoopExpr_t // Constructor
    {
        const static exprType class_type = exprType::DoLoopExpr;
        typedef expr_t parent_type;
        expr_t base;
        do_loop_head_t* m_head;
        expr_t* m_body;
        expr_t* m_type;
        expr_t* m_value;
    };
    static inline asr_t* make_DoLoopExpr_t(Allocator &al, const Location &a_loc, do_loop_head_t* a_head, expr_t* a_body, expr_t* a_type, expr_t* a_value) {
        DoLoopExpr_t *n;
        n = al.make_new<DoLoopExpr_t>();
        n->base.type = exprType::DoLoopExpr;
        n->base.base.type = asrType::expr;
        n->base.base.loc = a_loc;
        n->m_head = a_head;
        n->m_body = a_body;
        n->m_type = a_type;
        n->m_value = a_value;
        return (asr_t*)n;
    };
    ```

**Comment by certik** [comment]
Perfect. Now construct `DoLoopExpr` appropriately when the AST->ASR translation encounters implied do loop.

**Comment by Pranavchiku** [comment]
@certik if you could please brief a bit more it would be of great help.

What I understood is, whenever we encounter an implied do loop, we need to create `DoLoopExpr` node which will return an array.

**Comment by certik** [comment]
See https://github.com/lfortran/lfortran/pull/985#discussion_r1014643860, it looks like we already do everything we planned to do. :) That's even better. So now just see why the implied do loops do not work in Minpack, mabye it's some ASR->ASR pass.

**Comment by Pranavchiku** [comment]
Yeah, on it.

**Comment by Pranavchiku** [comment]
I am unable to find use of `ImpliedDoLoop` node in ASR of files of minpack (explicitly).

For `integration_tests/implied_do_loop2.f90`, latest main shows the following error
```
semantic error: reshape only accept arrays for shape arguments, found i32 instead.
 --> /home/pranavchiku/lfortran/integration_tests/implied_do_loops2.f90:4:10
  |
4 |  array = reshape([(i,(i+j,j=1,4),i=1,3)], shape(array))
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 

```

**Comment by certik** [comment]
See here: https://github.com/certik/minpack/commit/123becc96d9d90f5b01a204abbe1052b3ce00cf8

**Comment by Pranavchiku** [comment]
```
(lf2) pranavchiku@pranavchiku-Yoga-Slim-7-14IIL05:~/minpack(scipy21)$ make


Configuration results
---------------------
Fortran compiler: /home/pranavchiku/lfortran/src/bin/lfortran
Build type: Debug
Fortran compiler flags: 
Installation prefix: /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pranavchiku/minpack
Scanning dependencies of target minpack
[  2%] Building Fortran object src/CMakeFiles/minpack.dir/r1updt.f.o
[  4%] Building Fortran object src/CMakeFiles/minpack.dir/chkder.f.o
[  7%] Building Fortran object src/CMakeFiles/minpack.dir/fdjac1.f.o
[  9%] Building Fortran object src/CMakeFiles/minpack.dir/hybrd1.f.o
[ 12%] Building Fortran object src/CMakeFiles/minpack.dir/lmder1.f.o
[ 14%] Building Fortran object src/CMakeFiles/minpack.dir/lmpar.f.o
[ 17%] Building Fortran object src/CMakeFiles/minpack.dir/qform.f.o
[ 19%] Building Fortran object src/CMakeFiles/minpack.dir/rwupdt.f.o
[ 21%] Building Fortran object src/CMakeFiles/minpack.dir/dogleg.f.o
[ 24%] Building Fortran object src/CMakeFiles/minpack.dir/fdjac2.f.o
[ 26%] Building Fortran object src/CMakeFiles/minpack.dir/hybrd.f.o
[ 29%] Building Fortran object src/CMakeFiles/minpack.dir/lmder.f.o
[ 31%] Building Fortran object src/CMakeFiles/minpack.dir/lmstr1.f.o
[ 34%] Building Fortran object src/CMakeFiles/minpack.dir/qrfac.f.o
[ 36%] Building Fortran object src/CMakeFiles/minpack.dir/dpmpar.f.o
[ 39%] Building Fortran object src/CMakeFiles/minpack.dir/hybrj1.f.o
[ 41%] Building Fortran object src/CMakeFiles/minpack.dir/lmdif1.f.o
[ 43%] Building Fortran object src/CMakeFiles/minpack.dir/lmstr.f.o
[ 46%] Building Fortran object src/CMakeFiles/minpack.dir/qrsolv.f.o
[ 48%] Building Fortran object src/CMakeFiles/minpack.dir/enorm.f.o
[ 51%] Building Fortran object src/CMakeFiles/minpack.dir/hybrj.f.o
[ 53%] Building Fortran object src/CMakeFiles/minpack.dir/lmdif.f.o
[ 56%] Building Fortran object src/CMakeFiles/minpack.dir/r1mpyq.f.o
[ 58%] Linking Fortran static library libminpack.a
[ 95%] Built target minpack
Scanning dependencies of target example_hybrd
[ 97%] Building Fortran object examples/CMakeFiles/example_hybrd.dir/example_hybrd.f90.o
warning: Format statement is not implemented yet, for now we will ignore it
  --> /home/pranavchiku/minpack/examples/example_hybrd.f90:61:6 - 64:58
   |
61 |    1000 format(5x, "FINAL L2 NORM OF THE RESIDUALS", d15.7// &
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
64 |               5x, "FINAL APPROXIMATE SOLUTION"//(5x, 3d15.7))
   | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/pranavchiku/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 1763, in ??
    return compile_to_object_file(arg_file, outfile, false,
  File "/home/pranavchiku/lfortran/src/bin/lfortran.cpp", line 777, in ??
    res = fe.get_llvm3(*asr, lpm, diagnostics);
  File "/home/pranavchiku/lfortran/src/lfortran/fortran_evaluator.cpp", line 321, in LFortran::FortranEvaluator::get_llvm3(LFortran::ASR::TranslationUnit_t&, LCompilers::PassManager&, LFortran::diag::Diagnostics&)
    compiler_options, run_fn);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6204, in LFortran::asr_to_llvm(LFortran::ASR::TranslationUnit_t&, LFortran::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LFortran::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4112, in LFortran::ASR::BaseVisitor<LFortran::ASRToLLVMVisitor>::visit_asr(LFortran::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4089, in ??
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4113, in LFortran::ASR::BaseVisitor<LFortran::ASRToLLVMVisitor>::visit_unit(LFortran::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 3868, in ??
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1157, in LFortran::ASRToLLVMVisitor::visit_TranslationUnit(LFortran::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4115, in LFortran::ASR::BaseVisitor<LFortran::ASRToLLVMVisitor>::visit_symbol(LFortran::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 3876, in ??
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2164, in LFortran::ASRToLLVMVisitor::visit_Program(LFortran::ASR::Program_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4130, in LFortran::ASR::BaseVisitor<LFortran::ASRToLLVMVisitor>::visit_stmt(LFortran::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 3919, in ??
    case stmtType::FileWrite: { v.visit_FileWrite((const FileWrite_t &)x); return; }
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5265, in LFortran::ASRToLLVMVisitor::visit_FileWrite(LFortran::ASR::FileWrite_t const&)
    handle_print(x);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5303, in void LFortran::ASRToLLVMVisitor::handle_print<LFortran::ASR::FileWrite_t>(LFortran::ASR::FileWrite_t const&)
    this->visit_expr_wrapper(x.m_values[i], true);
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3831, in LFortran::ASRToLLVMVisitor::visit_expr_wrapper(LFortran::ASR::expr_t const*, bool)
    this->visit_expr(*x);
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 4173, in LFortran::ASR::BaseVisitor<LFortran::ASRToLLVMVisitor>::visit_expr(LFortran::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 3954, in ??
    case exprType::ImpliedDoLoop: { v.visit_ImpliedDoLoop((const ImpliedDoLoop_t &)x); return; }
LCompilersException: visit_ImpliedDoLoop() not implemented
make[2]: *** [examples/CMakeFiles/example_hybrd.dir/build.make:75: examples/CMakeFiles/example_hybrd.dir/example_hybrd.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:116: examples/CMakeFiles/example_hybrd.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by Pranavchiku** [comment]
I guess we need to implement `visit_ImpliedDoLoop()` in `ast_symboltable_visitor`.

**Comment by certik** [comment]
So going with our TODO list: https://github.com/lfortran/lfortran/issues/981#issuecomment-1302328560, it seems the step 2. is done (AST->ASR always works?). You mentioned `ast_symboltable_visitor`, is there something that doesn't work there?

The last step is the number 3: "The ASR->ASR pass implementation might work by creating a pure function that returns an array, and inside the function we simply do a regular DoLoop.".

**Comment by Pranavchiku** [comment]
>You mentioned ast_symboltable_visitor, is there something that doesn't work there?

Yeah it looks like that we are missing `visit_ImpliedDoLoop()` implementation in `ast_symboltable_visitor`.

**Comment by certik** [comment]
Can you show an example program that triggers such a problem?

It seems we don't need that for Minpack at least.

**Comment by Pranavchiku** [comment]
If I undo the changes of this [commit](https://github.com/certik/minpack/commit/123becc96d9d90f5b01a204abbe1052b3ce00cf8) at minpack, 

It gives the following [log](https://github.com/lfortran/lfortran/issues/981#issuecomment-1304721999)

**Comment by certik** [comment]
In that log you can see the error is from `asr_to_llvm`:
```
  File "/home/pranavchiku/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3831, in LFortran::ASRToLLVMVisitor::visit_expr_wrapper(LFortran::ASR::expr_t const*, bool)
    this->visit_expr(*x);
```

**Comment by Pranavchiku** [comment]
Yeah I looked at it lately,

Then it shows 
```
 File "/home/pranavchiku/lfortran/src/libasr/../libasr/asr.h", line 3954, in ??
    case exprType::ImpliedDoLoop: { v.visit_ImpliedDoLoop((const ImpliedDoLoop_t &)x); return; }
 ```
 Doesn't this mean missing implementation?

**Comment by Pranavchiku** [comment]
```fortran
program implied_do_loop1
	integer :: j
	integer :: a(10)=(/(j,j=1,10)/)
	print*, (a(j),j=1,10)
end program
```
This does not compiles to ASR.

**Comment by certik** [comment]
I see. Yes, that's one issue.

The other issue is in asr_to_llvm, where indeed the visitor is not implemented yet, so it fails.

**Comment by Pranavchiku** [comment]
Along with that when we encounter ImpliedDoLoop ex: `(i,i=1,3)` here in `lfortran` we need to have `integer::i` declared, else it shows `variable i not declared` error, whereas in `gfortran` it works without explicitly declaring variable i

**Comment by Pranavchiku** [comment]
Okay so, with #994 step2 is done.(to the best of my knowledge)

If you could brief me about implementing asr_to_llvm, that would be of great help.

**Comment by certik** [comment]
> If you could brief me about implementing asr_to_llvm, that would be of great help.

https://github.com/lfortran/lfortran/issues/981#issuecomment-1304723176

**Comment by certik** [comment]
I am thinking the easiest way to implement this is to create an ASR pass that transforms ImpliedDoLoop into a function call that just calls a regular loop. That way we don't need to touch any of the backends.

**Comment by certik** [comment]
So what remains is the ASR->ASR pass. Roughly speaking, it will take a code like this:
```fortran
program test_a
implicit none
integer :: x(6), i
x = [(i*2, i = 1, 6)]
print *, x
end program
```
and transform it into:
```fortran
program test_b
implicit none
integer :: x(6)
x = implied_do_loop_01()
print *, x

contains

    pure function implied_do_loop_01() result(x)
    integer :: x(6), i
    do i = 1, 6
        x(i) = i*2
    end do
    end function

end program
```

**Comment by gptsarthak** [comment]
What is the current status of ```ImpliedDoLoops```? It is used in a lot of print statements in ```scipy```.

**Comment by Pranavchiku** [comment]
We support a few implied do loops but, there might be various cases that we do not support. I tried to get those working, it took around a week of mine, I made progress but not that much.

**Comment by Pranavchiku** [comment]
You may find the draft PR here: https://github.com/lfortran/lfortran/pull/1993, I got astray in this PR, I thought we had no implementation but later on I found that we have initial implementation done, so I backed of as it consumed lot of my time and we decided to go depth first for SciPy.

**Comment by certik** [comment]
I can see two ways forward so far for IO implied do loops:

* Add a node to initiate the print, then add a node to append an argument to it, and then we can call this node in a loop
* Add a node to unpack an array/list into arguments, like in Python `*args`.

**Comment by certik** [comment]
Let's go with the second approach. This will be reusable in Python as well. Here is how to do it. We start with this:
```python
args = [1, 2, 3]
def f(a, b, c):
    print(a, b, c)

f(*args)
print(*args)
```
Here "args" can be a list, a tuple, or even a numpy array and it will work. We want this feature to be purely a compile time feature. To do that, the compile must translate `f(*args)` using the fact that it knows that "f" accepts exactly three arguments, as follow:
```python
assert len(args) == 3
f(args[0], args[1], args[2])
```

Regarding how to translate `print(*args)`, I think we should do `Print(UnpackArguments(args))`.
