### ISSUE TITLE
Modules don't work with WASM yet

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#988]
The following code fails with the WASM backend:
```fortran
module template_add_m
    implicit none

contains

    subroutine test_template()
    end subroutine

end module

program template_add
use template_add_m
implicit none

call test_template()

end program template_add
```
with:
```console
$ lfortran --backend=wasm template_add.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1786
    return compile_to_binary_wasm(arg_file, outfile,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 988
    result = LFortran::asr_to_wasm(*asr, al, outfile, time_report, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 2162
    Result<Vec<uint8_t>> wasm = asr_to_wasm_bytes_stream(asr, al, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 2136
    pass_unused_functions(al, asr, pass_options);
  File "../libasr/asr.h", line 4088
  File "../libasr/asr.h", line 4065
  File "../libasr/asr.h", line 4089
  File "../libasr/asr.h", line 3844
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 325
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 4091
  File "../libasr/asr.h", line 3853
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 363
    emit_function_prototype(*((ASR::Function_t *)main_func));
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 601
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4106
  File "../libasr/asr.h", line 3900
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_wasm.cpp", line 1648
    LFORTRAN_ASSERT(m_func_name_idx_map.find(get_hash((ASR::asr_t *)s)) !=
AssertFailed: m_func_name_idx_map.find(get_hash((ASR::asr_t *)s)) != m_func_name_idx_map.end()
```

**Comment by certik** [comment]
@Shaikh-Ubaid if you wanted to fix that, that would be awesome!

**Comment by Shaikh-Ubaid** [comment]
>@Shaikh-Ubaid if you wanted to fix that, that would be awesome!

Got it. Sure, I would love to fix it.

**Comment by Shaikh-Ubaid** [comment]
The example shared in the description of this issue (with an added `print` statement) seems to work with the latest `lfortran` in the `main` branch.

```bash
$ cat examples/expr2.f90     
module template_add_m
    implicit none

contains

    subroutine test_template()
        print *, "hi from test_template()"
    end subroutine

end module

program template_add
use template_add_m
implicit none

call test_template()

end program template_add
$ gfortran examples/expr2.f90 && ./a.out 
 hi from test_template()
$ lfortran examples/expr2.f90           
hi from test_template()
```

I am closing this issue as it seems fixed.
